export default function SketchFlowStyles({ accent }) {
  return (
    <style>{`
      @import url('https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap');
      .sketchflow-shell{position:fixed;inset:0;z-index:2147483000;width:100vw;height:100dvh;overflow:hidden;background:#fff;color:#1a1a1a;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
      .sf-root{--sf-bg:#fff;--sf-panel:#f8f8fb;--sf-border:#e3e3ea;--sf-text:#1f1f2d;--sf-muted:#6d6d7b;--sf-soft:#fff;--sf-control:#fff;--sf-shadow:0 16px 48px rgba(20,20,40,.13);position:relative;width:100%;height:100%;background:var(--sf-bg);color:var(--sf-text);overflow:hidden}
      [data-sf-theme="dark"] .sf-root{--sf-bg:#121212;--sf-panel:#1e1e1e;--sf-border:#34343d;--sf-text:#f8f8fb;--sf-muted:#a9a9b6;--sf-soft:#25252b;--sf-control:#24242a;--sf-shadow:0 18px 60px rgba(0,0,0,.35)}
      .sf-canvas-wrap{position:absolute;inset:0;min-width:0;min-height:0;overflow:hidden;background:var(--sf-bg);cursor:crosshair}.sf-canvas{display:block;width:100%;height:100%;touch-action:none}
      .sf-topbar{position:absolute;top:12px;left:12px;right:12px;z-index:20;display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);align-items:start;gap:12px;pointer-events:none}
      .sf-brand,.sf-options,.sf-actions{pointer-events:auto;border:1px solid var(--sf-border);background:color-mix(in srgb,var(--sf-panel) 94%,transparent);backdrop-filter:blur(16px);box-shadow:var(--sf-shadow)}
      .sf-brand{justify-self:start;display:flex;align-items:center;gap:10px;min-width:0;border-radius:12px;padding:8px 12px;color:${accent}}.sf-brand h1{margin:0;font-size:17px;font-weight:900;letter-spacing:-.02em;color:var(--sf-text)}.sf-brand p{margin:0;font-size:11px;font-weight:750;color:var(--sf-muted);white-space:nowrap}
      .sf-options{justify-self:center;display:flex;align-items:center;gap:8px;min-width:0;border-radius:12px;padding:6px}.sf-actions{justify-self:end;display:flex;align-items:center;gap:6px;min-width:0;border-radius:12px;padding:6px}
      .sf-pill,.sf-mini{display:inline-flex;align-items:center;gap:7px;border:1px solid var(--sf-border);background:var(--sf-control);border-radius:10px;padding:8px 11px;font-size:12px;font-weight:850;color:var(--sf-text);white-space:nowrap}.sf-step{width:70px;height:36px;border:1px solid var(--sf-border);border-radius:10px;background:var(--sf-control);color:var(--sf-text);padding:0 8px;font-weight:850}
      .sf-toolbar{position:absolute;left:50%;top:64px;z-index:21;display:grid;grid-auto-flow:column;grid-auto-columns:40px;gap:4px;border:1px solid var(--sf-border);background:color-mix(in srgb,var(--sf-panel) 94%,transparent);backdrop-filter:blur(16px);border-radius:14px;padding:6px;box-shadow:var(--sf-shadow);transform:translateX(-50%)}
      .sf-icon-btn{display:grid;place-items:center;width:40px;height:40px;border:1px solid transparent;border-radius:9px;background:transparent;color:var(--sf-text);transition:.14s ease;cursor:pointer}.sf-icon-btn:hover:not(:disabled){background:var(--sf-control);border-color:var(--sf-border);color:${accent}}.sf-icon-btn:disabled{opacity:.42;cursor:not-allowed}.sf-icon-btn.is-active{background:${accent};border-color:${accent};color:#fff;box-shadow:0 9px 22px rgba(105,101,219,.28)}
      .sf-panel{position:absolute;right:16px;top:118px;bottom:16px;z-index:22;width:min(336px,calc(100vw - 32px));overflow:auto;border:1px solid var(--sf-border);background:color-mix(in srgb,var(--sf-panel) 96%,transparent);backdrop-filter:blur(18px);border-radius:16px;padding:16px;box-shadow:var(--sf-shadow);animation:sfSlide .18s ease}.sf-panel::-webkit-scrollbar{width:8px}.sf-panel::-webkit-scrollbar-thumb{background:color-mix(in srgb,${accent} 30%,transparent);border-radius:999px}
      @keyframes sfSlide{from{opacity:0;transform:translateX(14px)}to{opacity:1;transform:none}}.sf-panel-head{display:flex;align-items:center;gap:10px;margin-bottom:16px}.sf-panel h2{font-size:20px;margin:0;font-weight:900}.sf-panel p{margin:0;color:var(--sf-muted);font-size:12px;font-weight:800}
      .sf-field-row{display:grid;grid-template-columns:auto minmax(0,.85fr) minmax(0,1.25fr);gap:8px;align-items:center;margin-bottom:12px}.sf-field-row label,.sf-label{font-size:12px;font-weight:900;color:var(--sf-muted);text-transform:uppercase;letter-spacing:.03em}.sf-field-row input,.sf-field-row select,.sf-panel input,.sf-panel select{min-width:0;height:38px;border:1px solid var(--sf-border);border-radius:10px;background:var(--sf-control);color:var(--sf-text);padding:0 10px;font-weight:800}.sf-field-row input[type=color]{padding:3px}
      .sf-prop-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:8px 0 14px}.sf-prop-grid.sf-three{grid-template-columns:repeat(3,minmax(0,1fr))}.sf-prop-btn{min-height:36px;border:1px solid var(--sf-border);border-radius:10px;background:var(--sf-control);color:var(--sf-text);font-size:12px;font-weight:900;text-transform:capitalize}.sf-prop-btn.is-active{background:${accent};color:#fff;border-color:${accent}}.export-bg{width:100%;justify-content:center;margin-top:14px;border-radius:12px}
      .sf-bottombar{position:absolute;left:14px;bottom:14px;z-index:21;display:flex;align-items:center;gap:4px;border:1px solid var(--sf-border);background:color-mix(in srgb,var(--sf-panel) 94%,transparent);backdrop-filter:blur(16px);border-radius:12px;padding:6px;box-shadow:var(--sf-shadow)}.sf-bottombar button{display:inline-flex;align-items:center;gap:5px;border:0;background:transparent;color:var(--sf-text);font-weight:850;border-radius:9px;padding:8px 9px}.sf-bottombar button:hover{background:var(--sf-control);color:${accent}}.sf-bottombar span{min-width:54px;text-align:center;font-weight:900;font-variant-numeric:tabular-nums}
      .sf-toast{position:absolute;right:18px;bottom:18px;z-index:25;border:1px solid rgba(16,185,129,.35);background:#ecfdf5;color:#047857;border-radius:999px;padding:10px 14px;font-size:13px;font-weight:900;box-shadow:0 12px 30px rgba(16,185,129,.18)}[data-sf-theme="dark"] .sf-toast{background:#062d21;color:#86efac}
      .sf-menu{position:fixed;z-index:2147483020;display:grid;gap:4px;width:198px;border:1px solid var(--sf-border);background:var(--sf-panel);border-radius:14px;padding:8px;box-shadow:0 18px 50px rgba(0,0,0,.22)}.sf-menu button{display:flex;align-items:center;gap:8px;border:0;background:transparent;border-radius:9px;color:var(--sf-text);font-weight:800;padding:9px 10px;text-align:left}.sf-menu button:hover{background:var(--sf-control);color:${accent}}
      .sf-palette-backdrop{position:fixed;inset:0;z-index:2147483030;display:grid;place-items:start center;background:rgba(15,23,42,.35);padding-top:12vh}.sf-palette{width:min(620px,calc(100vw - 28px));border:1px solid var(--sf-border);background:var(--sf-panel);border-radius:18px;padding:12px;box-shadow:0 26px 80px rgba(0,0,0,.28)}.sf-search{display:flex;align-items:center;gap:10px;border:1px solid var(--sf-border);background:var(--sf-control);border-radius:14px;padding:0 12px}.sf-search input{height:48px;flex:1;border:0;background:transparent;color:var(--sf-text);font-size:16px;font-weight:800;outline:none}.sf-command-list{display:grid;gap:6px;max-height:340px;overflow:auto;margin-top:10px}.sf-command-list button{display:flex;align-items:center;gap:10px;border:0;border-radius:12px;background:transparent;color:var(--sf-text);padding:11px 12px;font-weight:850}.sf-command-list button.is-active,.sf-command-list button:hover{background:${accent};color:#fff}
      .sf-text-editor{position:absolute;z-index:24;border:1.5px solid ${accent};border-radius:8px;background:rgba(255,255,255,.78);outline:none;padding:4px 6px;resize:none;line-height:1.25;overflow:hidden;white-space:pre-wrap;caret-color:${accent};box-shadow:0 10px 28px rgba(105,101,219,.18)}[data-sf-theme="dark"] .sf-text-editor{background:rgba(18,18,18,.8)}.sf-root [type=range]{accent-color:${accent}}.sf-root input[type=checkbox]{accent-color:${accent}}
      @media (max-width:1024px){.sf-topbar{grid-template-columns:1fr auto}.sf-options{grid-column:1/-1;justify-self:start;max-width:calc(100vw - 24px);overflow:auto}.sf-toolbar{top:106px;max-width:calc(100vw - 24px);overflow-x:auto;overflow-y:hidden}.sf-panel{top:auto;left:12px;right:12px;bottom:76px;width:auto;max-height:42dvh}.sf-bottombar{max-width:calc(100vw - 24px);overflow:auto}.sf-toast{right:12px;bottom:78px}}
      @media (max-width:640px){.sf-topbar{top:8px;left:8px;right:8px;display:flex;align-items:flex-start}.sf-brand{padding:7px 9px}.sf-brand h1{font-size:15px}.sf-brand p,.sf-options{display:none}.sf-actions{margin-left:auto;max-width:calc(100vw - 126px);overflow:auto}.sf-actions .sf-icon-btn{width:36px;height:36px}.sf-toolbar{left:8px;right:8px;top:62px;transform:none;grid-auto-columns:38px;border-radius:12px}.sf-icon-btn{width:38px;height:38px}.sf-panel{left:8px;right:8px;bottom:74px;max-height:46dvh;padding:14px}.sf-field-row{grid-template-columns:1fr 1fr}.sf-field-row label{grid-column:1/-1}.sf-bottombar{left:8px;right:8px;bottom:8px;border-radius:12px}.sf-bottombar button{padding:8px}.sf-bottombar button:nth-of-type(n+4){display:none}.sf-toast{left:8px;right:auto;bottom:70px}.sf-palette-backdrop{padding-top:8vh}}
    `}</style>
  );
}
