const seo = {
  title: "Play Sudoku: Daily Challenge & Unlimited Puzzles",
  metaDescription:
    "Same daily grid for every player worldwide, plus unlimited easy to expert boards. Every puzzle has one solution; notes, hints and streaks built in.",
  steps: [
    "Pick the 'Daily Challenge' tab for today's shared puzzle or 'Unlimited' with Easy, Medium, Hard or Expert, then press 'Play today's puzzle' or 'New game'.",
    "Select a cell and fill it from the 'Number pad'; toggle 'Notes' for pencil marks, or use the 'Hint' and 'Check' buttons when stuck.",
    "Solve the grid to log your Time, Mistakes and Hints — finishing the daily puzzle extends your day streak, which is saved in your browser.",
  ],
  intro:
    "This Sudoku plays a shared daily puzzle — seeded from the calendar date, so every player worldwide gets the identical grid — plus unlimited puzzles at easy, medium, hard and expert. Every grid is generated by carving clues out of a solved board in rotationally symmetric pairs and keeping a removal only when the puzzle still has exactly one solution, so nothing is ever guessable two ways. Pencil-mark notes, conflict highlighting, hints and a daily completion streak are all built in.",
  useCases: [
    "You want the same puzzle your friend is doing so you can compare times fairly, without either of you paying for an app subscription.",
    "Ten minutes on a commute and you want an expert grid down near 22-26 clues, not a warm-up.",
    "Learning to use pencil marks properly and needing conflict highlighting to catch the moment a candidate becomes impossible.",
  ],
  benefits: [
    ["Every puzzle has exactly one solution", "Each clue removal is tested with a solution counter and reverted if it creates a second answer, so no grid ever requires guessing."],
    ["Four genuinely separated difficulties", "Easy, medium and hard land on exactly 40, 32 and 26 clues every time. Expert targets 22 but the uniqueness check often stops it a little short, so expert puzzles typically settle around 22-26 clues instead of being labelled by feel."],
    ["Progress and streaks survive a refresh", "The board, your notes, the timer and your daily completion history are stored locally, so you can close the tab mid-puzzle."],
  ],
  faqs: [
    [
      "Is everyone playing the same daily sudoku?",
      "Yes. The daily puzzle is generated from a seed derived from the calendar date, so the same date produces the same grid for every player, and it changes at local midnight.",
    ],
    [
      "How many clues does each difficulty give me?",
      "Easy leaves 40 given numbers, medium 32 and hard 26, out of 81 cells. Expert targets 22 but the solution-uniqueness check often can't remove that many, so expert puzzles usually land around 22-26 clues. Fewer clues means more of the grid has to be deduced, which is what makes the harder levels slower rather than trickier arithmetic.",
    ],
    [
      "Can a puzzle here have more than one answer?",
      "No. During generation each pair of cells is only cleared if the remaining grid still solves exactly one way, verified by a solver that stops as soon as it finds a second solution. A puzzle with two answers is never served.",
    ],
    [
      "How does the streak counter work?",
      "It counts consecutive calendar days on which you finished that day's daily puzzle, and it also keeps your longest run and lifetime total. Missing a day resets the current streak but leaves the longest one intact.",
    ],
  ],
};

export default seo;
