/**
 * Feng shui room, element and bagua reference.
 *
 * Feng shui is a traditional Chinese practice, not a measurable science.
 * Everything here is a record of what the tradition holds, set out so it can be
 * applied consistently rather than piecemeal.
 *
 * The computational part is the five-element (wu xing) cycle, which is a
 * closed system and therefore exact.
 *
 * GENERATING CYCLE (sheng): Wood feeds Fire, Fire makes Earth (ash), Earth
 * yields Metal, Metal carries Water (condensation), Water grows Wood. Listing
 * the elements in that order makes "generates" the next index and "is
 * generated by" the previous index.
 *
 * CONTROLLING CYCLE (ke): Wood breaks Earth, Earth dams Water, Water quenches
 * Fire, Fire melts Metal, Metal cuts Wood. In the same ordering that is
 * exactly two steps forward, so:
 *
 *   relationship(a, b) is decided by (index(b) - index(a)) mod 5
 *     0 = same element
 *     1 = a generates b
 *     2 = a controls b
 *     3 = b controls a
 *     4 = b generates a
 *
 * MEDIATION. When one element controls another the traditional remedy is not
 * to remove either but to introduce the element that sits between them in the
 * generating cycle, because it is fed by the controller and in turn feeds the
 * controlled element. If a controls b, that mediator is at index(a) + 1. Wood
 * controlling Earth is softened by Fire; Water quenching Fire is softened by
 * Wood.
 *
 * THE BAGUA. The eight trigrams plus the centre, mapped onto a plan. Two
 * schools place it differently and both are given: the classical (compass)
 * school anchors each trigram to a compass direction, while the Black Sect
 * (BTB) school lays a three-by-three grid over the plan with the bottom row on
 * the wall containing the main door.
 */

/**
 * Rough split for applying the two elements in a room. It mirrors the
 * decorating convention of one dominant colour, one secondary and a small
 * accent, which is how the element palettes are used in practice.
 */
export const LEAD_SHARE = 60;
export const SUPPORT_SHARE = 30;

/** The five elements in generating-cycle order. Do not reorder. */
export const ELEMENTS = ["wood", "fire", "earth", "metal", "water"];

/** Element names, colours, shapes and materials as the tradition assigns them. */
export const ELEMENT_INFO = {
  wood: {
    label: "Wood",
    chinese: "Mu",
    colours: [
      { name: "Leaf green", hex: "#5E8C4E" },
      { name: "Sage", hex: "#A8BC96" },
      { name: "Blue-green", hex: "#4E8C82" },
    ],
    shape: "Tall columns and upright rectangles",
    materials: "Living plants, timber, rattan, cotton and linen",
    quality: "Growth, expansion and new plans",
  },
  fire: {
    label: "Fire",
    chinese: "Huo",
    colours: [
      { name: "Red", hex: "#C2402F" },
      { name: "Orange", hex: "#DB8340" },
      { name: "Deep pink", hex: "#C45A76" },
    ],
    shape: "Triangles, points and anything that tapers upward",
    materials: "Candles, lamps, leather, animal prints",
    quality: "Visibility, passion and recognition",
  },
  earth: {
    label: "Earth",
    chinese: "Tu",
    colours: [
      { name: "Ochre yellow", hex: "#D2A64B" },
      { name: "Sand", hex: "#DCC9A6" },
      { name: "Warm clay", hex: "#B98C6B" },
    ],
    shape: "Squares and low, flat horizontals",
    materials: "Ceramic, terracotta, brick, stone, wool",
    quality: "Stability, nourishment and steadiness",
  },
  metal: {
    label: "Metal",
    chinese: "Jin",
    colours: [
      { name: "White", hex: "#F2F2EF" },
      { name: "Grey", hex: "#B9BCC0" },
      { name: "Pale gold", hex: "#D8C79A" },
    ],
    shape: "Circles, arcs and domes",
    materials: "Steel, brass, copper, marble, glass",
    quality: "Precision, clarity and completion",
  },
  water: {
    label: "Water",
    chinese: "Shui",
    colours: [
      { name: "Deep blue", hex: "#2F4F73" },
      { name: "Near-black", hex: "#22252B" },
      { name: "Slate", hex: "#5C6B7A" },
    ],
    shape: "Wavy, irregular and free-flowing outlines",
    materials: "Mirrors, glass, reflective surfaces, still water",
    quality: "Depth, career movement and reflection",
  },
};

/**
 * The nine bagua areas. `direction` is the classical compass anchor.
 * `gridRow` and `gridCol` are the Black Sect placement, standing in the main
 * doorway looking into the home: row 1 is the wall you are standing on, row 3
 * is the far wall; column 1 is to your left, column 3 to your right.
 */
export const BAGUA = [
  { id: "xun", trigram: "Xun", life: "Wealth and abundance", element: "wood", direction: "South-East", gridRow: 3, gridCol: 1, note: "Traditionally kept in good repair and free of clutter; purple is added to the wood palette here." },
  { id: "li", trigram: "Li", life: "Fame and reputation", element: "fire", direction: "South", gridRow: 3, gridCol: 2, note: "Where awards, certificates and anything you want to be known for are placed." },
  { id: "kun", trigram: "Kun", life: "Love and partnership", element: "earth", direction: "South-West", gridRow: 3, gridCol: 3, note: "Objects are traditionally kept in pairs here rather than singly." },
  { id: "zhen", trigram: "Zhen", life: "Family and health", element: "wood", direction: "East", gridRow: 2, gridCol: 1, note: "Family photographs and living plants belong in this area." },
  { id: "taiqi", trigram: "Tai Qi", life: "Overall wellbeing", element: "earth", direction: "Centre", gridRow: 2, gridCol: 2, note: "The centre of the plan, kept open and uncluttered because everything else connects through it." },
  { id: "dui", trigram: "Dui", life: "Children and creativity", element: "metal", direction: "West", gridRow: 2, gridCol: 3, note: "Where unfinished creative work and children's things are traditionally kept." },
  { id: "gen", trigram: "Gen", life: "Knowledge and self-study", element: "earth", direction: "North-East", gridRow: 1, gridCol: 1, note: "Books and quiet study belong here; the tradition adds dark blue to the earth palette." },
  { id: "kan", trigram: "Kan", life: "Career and path in life", element: "water", direction: "North", gridRow: 1, gridCol: 2, note: "Contains the main door in the Black Sect layout, so it is the first thing chi meets." },
  { id: "qian", trigram: "Qian", life: "Helpful people and travel", element: "metal", direction: "North-West", gridRow: 1, gridCol: 3, note: "Grey, white and metal objects; traditionally where you place things connected to mentors and journeys." },
];

/**
 * Rooms, the element the practice associates with their activity, and the
 * layout rules attached to them. The commanding-position rule is the one that
 * appears in every school: the bed, desk or stove should let the user see the
 * door without being directly in line with it.
 */
export const ROOMS = [
  {
    id: "bedroom",
    label: "Bedroom",
    element: "earth",
    yin: true,
    rules: [
      "Place the bed in the commanding position — able to see the door from the bed, but not in a straight line with it.",
      "A solid headboard against a solid wall, with space to walk on both sides.",
      "No bed directly under a window, and nothing heavy on a shelf above the head.",
      "Mirrors kept out of the direct line of the bed, and screens out of the room entirely if possible.",
    ],
  },
  {
    id: "kitchen",
    label: "Kitchen",
    element: "fire",
    yin: false,
    rules: [
      "The cook should not stand with their back to the door; if the hob faces a wall, a mirror or reflective splashback restores the view.",
      "Keep the hob and the sink out of direct opposition — fire and water in a straight line is the classic kitchen clash.",
      "A wood element between them, such as a timber board or a plant, is the traditional mediator.",
      "Keep the hob clean and use all the burners in rotation.",
    ],
  },
  {
    id: "office",
    label: "Home office / study",
    element: "wood",
    yin: false,
    rules: [
      "Desk in the commanding position, facing into the room with the door in view and a solid wall behind.",
      "Never sit with your back to a door or a window.",
      "Keep the space in front of the desk open — the tradition treats that as the space your work has to expand into.",
      "Cables and clutter under the desk are treated as an obstruction; box them in.",
    ],
  },
  {
    id: "living",
    label: "Living room",
    element: "wood",
    yin: false,
    rules: [
      "Arrange seating so nobody has their back to the main entrance to the room.",
      "Sofas against a solid wall rather than floating with a walkway behind.",
      "Round or soft-edged tables where a walkway passes, so no corner points at a seat.",
      "Keep a clear path from the door through the room — chi should not have to squeeze past furniture.",
    ],
  },
  {
    id: "dining",
    label: "Dining room",
    element: "earth",
    yin: false,
    rules: [
      "A round or oval table keeps everyone equal and removes pointed corners.",
      "An even number of chairs, and a mirror reflecting the table is the traditional way to double the abundance it represents.",
      "Nobody seated with their back to the door.",
    ],
  },
  {
    id: "entrance",
    label: "Entrance hall",
    element: "water",
    yin: false,
    rules: [
      "The front door is the mouth of chi: it should open fully, be well lit, and have nothing stored behind it.",
      "No mirror directly facing the front door — the tradition holds that it reflects incoming chi straight back out.",
      "Keep shoes, bins and clutter out of the first two metres inside the door.",
    ],
  },
  {
    id: "bathroom",
    label: "Bathroom",
    element: "water",
    yin: true,
    rules: [
      "Keep the door closed and the toilet lid down; the tradition treats drains as places chi leaves.",
      "Add a wood element — a plant or timber — which is fed by water rather than fighting it.",
      "Avoid a bathroom directly facing or above the front door, and keep it well ventilated.",
    ],
  },
  {
    id: "children",
    label: "Children's room",
    element: "metal",
    yin: true,
    rules: [
      "Bed in the commanding position, as in any bedroom, with a solid headboard.",
      "Keep the study area and the sleeping area visually separate.",
      "Store toys behind closed doors so the room reads as restful at night.",
    ],
  },
  {
    id: "gym",
    label: "Home gym",
    element: "fire",
    yin: false,
    rules: [
      "A yang, active room — bright light and movement are appropriate here in a way they are not in a bedroom.",
      "Mirrors are welcome, unlike in a bedroom, and help the room feel larger.",
      "Keep it out of the quiet corners of the plan if it shares a wall with a bedroom.",
    ],
  },
  {
    id: "laundry",
    label: "Laundry / utility",
    element: "water",
    yin: true,
    rules: [
      "Another drain-heavy room, so keep the door closed and the space dry.",
      "Metal fittings suit it, since metal carries water in the generating cycle.",
      "Do not let it become the household dumping ground — stagnation is the thing the practice objects to most.",
    ],
  },
];

const round = (value, places = 0) => {
  const factor = 10 ** places;
  return Math.round(value * factor) / factor;
};

/** Index of an element in the generating cycle, or -1. */
export function elementIndex(element) {
  return ELEMENTS.indexOf(element);
}

/** The element this one feeds in the generating cycle. */
export function generates(element) {
  const i = elementIndex(element);
  return i < 0 ? null : ELEMENTS[(i + 1) % ELEMENTS.length];
}

/** The element that controls this one. */
export function controlledBy(element) {
  const i = elementIndex(element);
  return i < 0 ? null : ELEMENTS[(i + ELEMENTS.length - 2) % ELEMENTS.length];
}

/**
 * How element `a` stands to element `b`.
 * Returns one of: same, a-generates-b, a-controls-b, b-controls-a, b-generates-a.
 */
export function elementRelationship(a, b) {
  const ia = elementIndex(a);
  const ib = elementIndex(b);
  if (ia < 0 || ib < 0) return null;
  const step = (ib - ia + ELEMENTS.length) % ELEMENTS.length;
  if (step === 0) return "same";
  if (step === 1) return "a-generates-b";
  if (step === 2) return "a-controls-b";
  if (step === 3) return "b-controls-a";
  return "b-generates-a";
}

/**
 * The mediating element for a controlling pair: the one that the controller
 * feeds and that in turn feeds the controlled element. Only defined when `a`
 * controls `b`.
 */
export function mediatingElement(a, b) {
  if (elementRelationship(a, b) !== "a-controls-b") return null;
  return generates(a);
}

/** Bagua area for a Black Sect grid cell (row 1-3 from the door wall). */
export function baguaByGrid(row, col) {
  const r = Number(row);
  const c = Number(col);
  if (!Number.isInteger(r) || !Number.isInteger(c) || r < 1 || r > 3 || c < 1 || c > 3) return null;
  return BAGUA.find((area) => area.gridRow === r && area.gridCol === c) || null;
}

/**
 * Guidance for one room sitting in one bagua area.
 *
 * @param {object} input
 * @param {string} input.room    one of ROOMS ids
 * @param {string} input.area    one of BAGUA ids
 * @returns {object} { error } or the guidance
 */
export function roomGuidance({ room, area } = {}) {
  const space = ROOMS.find((r) => r.id === room);
  if (!space) return { error: "Choose which room you are looking at." };
  const zone = BAGUA.find((b) => b.id === area);
  if (!zone) return { error: "Choose which bagua area of the plan the room falls in." };

  const roomElement = space.element;
  const areaElement = zone.element;
  const relation = elementRelationship(roomElement, areaElement);

  let harmony = "neutral";
  let harmonyLabel = "";
  let advice = "";
  let mediator = null;

  if (relation === "same") {
    harmony = "aligned";
    harmonyLabel = `Both the room and the area are ${ELEMENT_INFO[areaElement].label}`;
    advice = `The room and its position agree. Use the ${ELEMENT_INFO[areaElement].label.toLowerCase()} palette confidently, but add a little of the ${ELEMENT_INFO[generates(areaElement)].label.toLowerCase()} it feeds so a single element does not dominate the whole space.`;
  } else if (relation === "a-generates-b") {
    harmony = "supportive";
    harmonyLabel = `${ELEMENT_INFO[roomElement].label} feeds ${ELEMENT_INFO[areaElement].label}`;
    advice = `The room's activity nourishes the life area it sits in. Lead with the ${ELEMENT_INFO[areaElement].label.toLowerCase()} colours of the area and keep the ${ELEMENT_INFO[roomElement].label.toLowerCase()} of the room as the supporting accent.`;
  } else if (relation === "b-generates-a") {
    harmony = "supportive";
    harmonyLabel = `${ELEMENT_INFO[areaElement].label} feeds ${ELEMENT_INFO[roomElement].label}`;
    advice = `The position nourishes the room. Lead with the ${ELEMENT_INFO[roomElement].label.toLowerCase()} colours of the room and use the area's ${ELEMENT_INFO[areaElement].label.toLowerCase()} as the grounding second colour.`;
  } else if (relation === "a-controls-b") {
    harmony = "clash";
    mediator = mediatingElement(roomElement, areaElement);
    harmonyLabel = `${ELEMENT_INFO[roomElement].label} controls ${ELEMENT_INFO[areaElement].label}`;
    advice = `The room's element works against the life area it occupies. The traditional fix is not to remove either but to bring in ${ELEMENT_INFO[mediator].label} — it is fed by ${ELEMENT_INFO[roomElement].label.toLowerCase()} and in turn feeds ${ELEMENT_INFO[areaElement].label.toLowerCase()}, so it turns the conflict into a chain. Keep strong ${ELEMENT_INFO[roomElement].label.toLowerCase()} colours to accents here.`;
  } else {
    harmony = "clash";
    mediator = mediatingElement(areaElement, roomElement);
    harmonyLabel = `${ELEMENT_INFO[areaElement].label} controls ${ELEMENT_INFO[roomElement].label}`;
    advice = `The position works against the room's activity. Introduce ${ELEMENT_INFO[mediator].label}, which ${ELEMENT_INFO[areaElement].label.toLowerCase()} feeds and which in turn feeds ${ELEMENT_INFO[roomElement].label.toLowerCase()}, and keep the area's own colours to accents rather than covering whole walls.`;
  }

  // Lead colour: the area's element whenever the room already feeds, matches or
  // (per the advice above) has to stand down in favour of it — i.e. every
  // relation except "b-generates-a" and "b-controls-a", where the room's own
  // element leads instead. Support and Reduce are then picked per relation so
  // that all three slots are always three distinct elements — see the a-controls-b
  // and b-controls-a cases below, where naively reusing the generic rules made
  // Lead and Reduce (or Support and the promised "area's own colour") collide.
  const leadElement =
    relation === "a-generates-b" || relation === "same" || relation === "a-controls-b"
      ? areaElement
      : roomElement;

  let supportElement;
  if (relation === "same") {
    supportElement = generates(areaElement);
  } else if (relation === "a-generates-b") {
    // Lead is the area's element here, so the room's own element is the support.
    supportElement = roomElement;
  } else if (relation === "b-generates-a") {
    // Lead is the room's own element here, so the area's element supports it.
    supportElement = areaElement;
  } else if (relation === "a-controls-b") {
    // The room's element is being pushed down to an accent (see reduceElement
    // below), so the mediator being introduced is the supporting colour.
    supportElement = mediator;
  } else {
    // b-controls-a: the mediator is the colour being introduced to break the
    // clash, so it takes the supporting slot (mirrors how a-controls-b puts
    // its mediator in supportElement above).
    supportElement = mediator;
  }

  // Reduce ("keep to accents only"): the aggressor element, pushed down to an
  // accent. In a-controls-b that's the room's own element, which is exactly
  // what controlledBy(areaElement) resolves to (the element controlling the
  // area). In b-controls-a the aggressor is the area's own element instead,
  // so it must be used directly rather than re-deriving it via controlledBy.
  const reduceElement = relation === "b-controls-a" ? areaElement : controlledBy(areaElement);

  return {
    roomId: space.id,
    roomLabel: space.label,
    roomElement,
    roomElementLabel: ELEMENT_INFO[roomElement].label,
    roomIsYin: space.yin,
    rules: space.rules,
    areaId: zone.id,
    trigram: zone.trigram,
    lifeArea: zone.life,
    areaElement,
    areaElementLabel: ELEMENT_INFO[areaElement].label,
    areaDirection: zone.direction,
    areaGrid: `row ${zone.gridRow} from the door wall, column ${zone.gridCol} from the left`,
    areaNote: zone.note,
    relation,
    harmony,
    harmonyLabel,
    advice,
    mediator,
    mediatorLabel: mediator ? ELEMENT_INFO[mediator].label : null,
    leadElement,
    leadColours: ELEMENT_INFO[leadElement].colours,
    supportElement,
    supportColours: ELEMENT_INFO[supportElement].colours,
    reduceElement,
    reduceElementLabel: ELEMENT_INFO[reduceElement].label,
    reduceColours: ELEMENT_INFO[reduceElement].colours,
    shape: ELEMENT_INFO[leadElement].shape,
    materials: ELEMENT_INFO[leadElement].materials,
    quality: ELEMENT_INFO[leadElement].quality,
    percentLead: LEAD_SHARE,
    percentSupport: SUPPORT_SHARE,
    percentRest: round(100 - LEAD_SHARE - SUPPORT_SHARE),
  };
}
