export const pantryGroups = [
  { id: "grains", label: "Grains & breads" },
  { id: "dals", label: "Dals & beans" },
  { id: "veggies", label: "Veggies & aromatics" },
  { id: "dairy", label: "Dairy, paneer & eggs" },
  { id: "sauces", label: "Sauces & condiments" },
  { id: "nonveg", label: "Meat & seafood" },
];

export const ingredients = [
  { id: "cooked-rice", label: "Cooked rice", group: "grains" },
  { id: "raw-rice", label: "Raw rice", group: "grains" },
  { id: "roti", label: "Roti / chapati", group: "grains" },
  { id: "bread", label: "Bread slices", group: "grains" },
  { id: "pasta", label: "Pasta", group: "grains" },
  { id: "noodles", label: "Noodles", group: "grains" },
  { id: "poha", label: "Poha", group: "grains" },
  { id: "rava", label: "Rava / suji", group: "grains" },
  { id: "oats", label: "Oats", group: "grains" },
  { id: "atta", label: "Atta (wheat flour)", group: "grains" },
  { id: "maida", label: "Maida", group: "grains" },
  { id: "besan", label: "Besan (gram flour)", group: "grains" },
  { id: "rice-flour", label: "Rice flour", group: "grains" },
  { id: "tortilla", label: "Tortilla / wrap", group: "grains" },
  { id: "quinoa", label: "Cooked quinoa", group: "grains" },

  { id: "cooked-dal", label: "Cooked dal (leftover)", group: "dals" },
  { id: "moong-dal", label: "Moong dal", group: "dals" },
  { id: "toor-dal", label: "Toor / arhar dal", group: "dals" },
  { id: "chana-dal", label: "Chana dal", group: "dals" },
  { id: "urad-dal", label: "Urad dal", group: "dals" },
  { id: "chana", label: "Chickpeas / chole", group: "dals" },
  { id: "rajma", label: "Rajma", group: "dals" },
  { id: "black-beans", label: "Black beans", group: "dals" },
  { id: "sprouts", label: "Sprouts", group: "dals" },

  { id: "onion", label: "Onion", group: "veggies" },
  { id: "tomato", label: "Tomato", group: "veggies" },
  { id: "potato", label: "Potato", group: "veggies" },
  { id: "garlic", label: "Garlic", group: "veggies" },
  { id: "ginger", label: "Ginger", group: "veggies" },
  { id: "green-chilli", label: "Green chilli", group: "veggies" },
  { id: "coriander", label: "Coriander leaves", group: "veggies" },
  { id: "curry-leaves", label: "Curry leaves", group: "veggies" },
  { id: "mint", label: "Mint leaves", group: "veggies" },
  { id: "lemon", label: "Lemon", group: "veggies" },
  { id: "capsicum", label: "Capsicum", group: "veggies" },
  { id: "carrot", label: "Carrot", group: "veggies" },
  { id: "peas", label: "Green peas", group: "veggies" },
  { id: "spinach", label: "Spinach / palak", group: "veggies" },
  { id: "cabbage", label: "Cabbage", group: "veggies" },
  { id: "cauliflower", label: "Cauliflower", group: "veggies" },
  { id: "corn", label: "Sweet corn", group: "veggies" },
  { id: "mushroom", label: "Mushroom", group: "veggies" },
  { id: "cucumber", label: "Cucumber", group: "veggies" },
  { id: "french-beans", label: "French beans", group: "veggies" },
  { id: "broccoli", label: "Broccoli", group: "veggies" },
  { id: "avocado", label: "Avocado", group: "veggies" },

  { id: "paneer", label: "Paneer", group: "dairy" },
  { id: "eggs", label: "Eggs", group: "dairy" },
  { id: "milk", label: "Milk", group: "dairy" },
  { id: "curd", label: "Curd / yoghurt", group: "dairy" },
  { id: "butter", label: "Butter", group: "dairy" },
  { id: "cheese", label: "Cheese", group: "dairy" },
  { id: "cream", label: "Fresh cream", group: "dairy" },
  { id: "ghee", label: "Ghee", group: "dairy" },

  { id: "soy-sauce", label: "Soy sauce", group: "sauces" },
  { id: "ketchup", label: "Tomato ketchup", group: "sauces" },
  { id: "mayo", label: "Mayonnaise", group: "sauces" },
  { id: "chilli-sauce", label: "Chilli / schezwan sauce", group: "sauces" },
  { id: "vinegar", label: "Vinegar", group: "sauces" },
  { id: "pasta-sauce", label: "Pasta / pizza sauce", group: "sauces" },
  { id: "peanut-butter", label: "Peanut butter", group: "sauces" },
  { id: "jam", label: "Jam", group: "sauces" },
  { id: "honey", label: "Honey", group: "sauces" },
  { id: "chaat-masala", label: "Chaat masala", group: "sauces" },
  { id: "garam-masala", label: "Garam masala", group: "sauces" },
  { id: "pav-bhaji-masala", label: "Pav bhaji masala", group: "sauces" },
  { id: "oregano-mix", label: "Mixed herbs / oregano", group: "sauces" },
  { id: "sugar", label: "Sugar", group: "sauces" },
  { id: "jaggery", label: "Jaggery", group: "sauces" },
  { id: "peanuts", label: "Peanuts", group: "sauces" },
  { id: "coconut", label: "Grated coconut", group: "sauces" },
  { id: "cashew", label: "Cashew", group: "sauces" },
  { id: "raisins", label: "Raisins", group: "sauces" },
  { id: "tamarind", label: "Tamarind", group: "sauces" },
  { id: "sesame-seeds", label: "Sesame seeds", group: "sauces" },

  { id: "cooked-chicken", label: "Cooked chicken (leftover)", group: "nonveg" },
  { id: "chicken", label: "Raw chicken", group: "nonveg" },
  { id: "keema", label: "Keema (minced meat)", group: "nonveg" },
  { id: "fish", label: "Fish fillet", group: "nonveg" },
  { id: "prawns", label: "Prawns", group: "nonveg" },
];

export const staples = "Salt, oil, water, turmeric, red chilli powder, cumin & mustard seeds are assumed to be in your kitchen — they are not part of the matching.";

export const recipeIdeas = [
  {
    id: "leftover-fried-rice",
    name: "Leftover Rice Fried Rice",
    cuisine: "Indo-Chinese",
    tag: "veg",
    time: 12,
    stove: true,
    need: ["cooked-rice", "onion", "soy-sauce"],
    optional: ["carrot", "peas", "capsicum", "cabbage", "chilli-sauce", "vinegar"],
    method:
      "Heat 2 tsp oil in a wide pan on the highest flame and toss 1 sliced onion plus any diced hard veg for 2 minutes — they should stay crunchy. Add 2 cups cold cooked rice, 1 tbsp soy sauce and a generous pinch of black pepper. Stir-fry 3 minutes, folding rather than mashing so the grains stay separate.",
  },
  {
    id: "curd-rice",
    name: "Curd Rice (Thayir Sadam)",
    cuisine: "South Indian",
    tag: "veg",
    time: 10,
    stove: false,
    need: ["cooked-rice", "curd"],
    optional: ["curry-leaves", "green-chilli", "ginger", "coriander", "peanuts"],
    method:
      "Mash 2 cups cooked rice while still warm so it loses its grain, then fold in 1 cup curd, 3 tbsp milk and ½ tsp salt — it should be loose, as it thickens on standing. Rest 15 minutes for the tang to develop. A 1-minute tempering of mustard, curry leaves and chilli is traditional but the dish is complete without it.",
  },
  {
    id: "lemon-rice",
    name: "Lemon Rice (Chitranna)",
    cuisine: "South Indian",
    tag: "veg",
    time: 12,
    stove: true,
    need: ["cooked-rice", "lemon"],
    optional: ["peanuts", "curry-leaves", "green-chilli", "ginger", "coriander"],
    method:
      "Temper 1 tsp mustard seeds in 2 tbsp oil, add 2 tbsp peanuts and fry till golden, then curry leaves, 2 slit chillies and ¼ tsp turmeric. Fold in 2 cups cooled rice off the heat and squeeze in the juice of 1 lemon. Adding lemon off the flame keeps it fragrant instead of bitter.",
  },
  {
    id: "tomato-rice",
    name: "Tomato Rice (Thakkali Sadam)",
    cuisine: "South Indian",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["cooked-rice", "tomato", "onion"],
    optional: ["garlic", "curry-leaves", "garam-masala", "coriander", "peanuts"],
    method:
      "Fry 1 sliced onion in 2 tbsp oil till soft, add 3 chopped tomatoes with ½ tsp chilli powder and cook 6 minutes till the mix darkens and oil separates. Fold in 2 cups rice and salt, cover for 2 minutes on low. The tomatoes must break down completely or the rice turns watery.",
  },
  {
    id: "rice-cutlet",
    name: "Crispy Rice & Potato Tikki",
    cuisine: "Indian",
    tag: "veg",
    time: 20,
    stove: true,
    need: ["cooked-rice", "potato", "bread"],
    optional: ["green-chilli", "coriander", "garam-masala", "onion", "chaat-masala"],
    method:
      "Mash 1 cup rice with 2 boiled potatoes, 2 slices of bread crumbled fine, ½ tsp garam masala and salt — the bread absorbs moisture so the tikkis hold. Shape 8 patties and rest them 10 minutes. Shallow-fry on medium 3 minutes a side till a hard golden crust forms.",
  },
  {
    id: "rice-kheer",
    name: "Rice Kheer",
    cuisine: "Indian",
    tag: "veg",
    time: 25,
    stove: true,
    need: ["cooked-rice", "milk", "sugar"],
    optional: ["cashew", "raisins", "ghee", "cream"],
    method:
      "Simmer 1 cup cooked rice in 750 ml full-fat milk on low, stirring every few minutes so it never catches at the base. After 18 minutes it thickens and turns cream-coloured; stir in 5 tbsp sugar and cook 4 more minutes. Sugar goes in last — added early it stops the milk from reducing.",
  },
  {
    id: "rice-pakora",
    name: "Rice Pakora Fritters",
    cuisine: "Indian",
    tag: "veg",
    time: 20,
    stove: true,
    need: ["cooked-rice", "besan", "onion"],
    optional: ["green-chilli", "coriander", "curry-leaves", "chaat-masala"],
    method:
      "Mix 1 cup rice with ¾ cup besan, 1 finely chopped onion, 2 chopped chillies, ½ tsp ajwain and salt, adding water 1 tbsp at a time to a thick dropping batter. Drop rough spoonfuls into 170°C oil. Fry 4 minutes till deep gold — a thin batter makes them soggy, so keep it stiff.",
  },
  {
    id: "instant-rice-dosa",
    name: "Instant Rice Dosa",
    cuisine: "South Indian",
    tag: "veg",
    time: 20,
    stove: true,
    need: ["cooked-rice", "rice-flour", "curd"],
    optional: ["onion", "green-chilli", "coriander", "curry-leaves"],
    method:
      "Blend 1 cup cooked rice with ½ cup curd and 200 ml water to a smooth cream, then whisk in ½ cup rice flour and salt — the batter must be as thin as buttermilk. Rest 10 minutes. Pour from the outside in onto a very hot tawa and cook 2 minutes without flipping for lacy edges.",
  },
  {
    id: "arancini",
    name: "Cheesy Rice Arancini",
    cuisine: "Italian",
    tag: "veg",
    time: 25,
    stove: true,
    need: ["cooked-rice", "cheese", "bread"],
    optional: ["oregano-mix", "garlic", "onion", "pasta-sauce"],
    method:
      "Mash 2 cups cold rice with salt and 1 tsp mixed herbs, take a golf-ball portion, press a cube of cheese into the centre and seal completely. Roll in crumbs made from 3 blitzed bread slices. Deep-fry at 180°C for 3 minutes; cold rice is essential or the balls fall apart.",
  },
  {
    id: "rice-salad-bowl",
    name: "Cold Rice Salad Bowl",
    cuisine: "Global",
    tag: "veg",
    time: 10,
    stove: false,
    need: ["cooked-rice", "cucumber", "tomato", "lemon"],
    optional: ["corn", "coriander", "onion", "avocado", "peanuts"],
    method:
      "Fluff 2 cups chilled rice with a fork and toss with 1 diced cucumber, 1 deseeded tomato and 2 tbsp chopped coriander. Whisk juice of 1 lemon with 2 tbsp oil, ½ tsp salt and pepper, then fold through. Deseeding the tomato is what keeps the bowl crisp instead of watery.",
  },
  {
    id: "burrito-bowl",
    name: "Rajma Burrito Bowl",
    cuisine: "Mexican",
    tag: "veg",
    time: 15,
    stove: false,
    need: ["cooked-rice", "rajma", "tomato"],
    optional: ["corn", "cheese", "avocado", "lemon", "onion", "coriander"],
    method:
      "Layer 1 cup rice in a bowl, spoon over 1 cup cooked rajma, and top with a quick salsa of 1 chopped tomato, ¼ onion, lemon juice and salt. Finish with corn and grated cheese. Squeeze lemon over the rice itself, not just the top — it wakes the whole bowl up.",
  },
  {
    id: "roti-churma",
    name: "Roti Churma",
    cuisine: "Rajasthani",
    tag: "veg",
    time: 12,
    stove: true,
    need: ["roti", "ghee", "jaggery"],
    optional: ["cashew", "sesame-seeds", "coconut", "raisins"],
    method:
      "Tear 4 rotis and pulse to a coarse crumb — stop before it turns to powder. Roast the crumb in 3 tbsp ghee on low for 6 minutes till it smells nutty and turns a shade darker. Take off the heat, cool 2 minutes, then mix in 4 tbsp grated jaggery so it melts without going sticky.",
  },
  {
    id: "roti-quesadilla",
    name: "Roti Quesadilla",
    cuisine: "Fusion",
    tag: "veg",
    time: 12,
    stove: true,
    need: ["roti", "cheese", "onion"],
    optional: ["capsicum", "corn", "chilli-sauce", "tomato", "oregano-mix"],
    method:
      "Scatter ½ cup grated cheese over one roti with sliced onion, capsicum and a drizzle of chilli sauce, then cover with a second roti. Toast in a dry pan on low for 3 minutes a side, pressing with a spatula. Low heat matters — high heat browns the roti before the cheese melts.",
  },
  {
    id: "roti-noodles",
    name: "Chapati Noodles",
    cuisine: "Fusion",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["roti", "onion", "soy-sauce"],
    optional: ["capsicum", "carrot", "cabbage", "chilli-sauce", "vinegar"],
    method:
      "Roll 4 rotis into tight cigars and slice into thin ribbons. Stir-fry shredded cabbage, carrot and onion on high for 3 minutes, add 1 tbsp soy sauce, 1 tsp chilli sauce and 1 tsp vinegar. Toss the roti strips through for the last minute only, or they soften into a lump.",
  },
  {
    id: "roti-upma",
    name: "Chapati Upma",
    cuisine: "South Indian",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["roti", "onion", "tomato"],
    optional: ["curry-leaves", "green-chilli", "coriander", "peanuts", "lemon"],
    method:
      "Tear 4 rotis into bite-sized pieces. Temper mustard seeds, curry leaves and 2 chillies in 2 tbsp oil, fry 1 onion till pink, then 1 tomato with ¼ tsp turmeric till mushy. Fold in the roti with 2 tbsp water, cover 2 minutes — the steam softens them just enough.",
  },
  {
    id: "roti-pizza",
    name: "Roti Pizza",
    cuisine: "Fusion",
    tag: "veg",
    time: 12,
    stove: true,
    need: ["roti", "cheese", "pasta-sauce"],
    optional: ["capsicum", "onion", "corn", "oregano-mix", "mushroom"],
    method:
      "Spread 2 tbsp pizza sauce on a roti, leaving a thin border, and top with veggies and ½ cup cheese. Cook covered in a pan on low for 5 minutes till the base crisps and the cheese melts. A tight lid is what replaces the oven here.",
  },
  {
    id: "roti-nachos",
    name: "Roti Nachos",
    cuisine: "Fusion",
    tag: "veg",
    time: 12,
    stove: true,
    need: ["roti"],
    optional: ["chaat-masala", "chilli-sauce", "cheese", "tomato", "onion"],
    method:
      "Cut 3 rotis into triangles, brush lightly with oil and dust with chaat masala and chilli powder. Shallow-fry or pan-toast 2 minutes a side till they snap when bent. Serve with salsa or melted cheese — they crisp further as they cool, so pull them early.",
  },
  {
    id: "roti-kathi-roll",
    name: "Paneer Kathi Roll",
    cuisine: "Kolkata street",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["roti", "onion", "paneer"],
    optional: ["capsicum", "chaat-masala", "mayo", "lemon", "green-chilli"],
    method:
      "Toss 150 g paneer cubes with ½ tsp chilli powder and sear 3 minutes till spotted brown. Warm a roti, spread mayo, pile on the paneer with thin onion rings, a squeeze of lemon and a heavy dust of chaat masala. Roll tight and wrap the base in paper so it holds.",
  },
  {
    id: "roti-kheer",
    name: "Roti Kheer",
    cuisine: "Indian",
    tag: "veg",
    time: 20,
    stove: true,
    need: ["roti", "milk", "sugar"],
    optional: ["cashew", "raisins", "ghee", "coconut"],
    method:
      "Tear 3 rotis very small and roast in 1 tbsp ghee for 3 minutes. Pour in 600 ml milk and simmer 12 minutes, mashing occasionally till the pieces dissolve into a thick porridge. Stir in 4 tbsp sugar at the end and finish with cashews.",
  },
  {
    id: "roti-pb-rollup",
    name: "Peanut Butter Roti Roll-Up",
    cuisine: "Quick fix",
    tag: "veg",
    time: 5,
    stove: false,
    need: ["roti", "peanut-butter", "honey"],
    optional: ["jam", "raisins", "sesame-seeds", "cashew"],
    method:
      "Spread 2 tbsp peanut butter across a soft roti right to the edges, drizzle 1 tsp honey and scatter a few raisins. Roll tight and slice on the diagonal into pinwheels. If the roti is stiff, 10 seconds in the microwave makes it roll without cracking.",
  },
  {
    id: "bread-upma",
    name: "Bread Upma",
    cuisine: "Indian",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["bread", "onion", "tomato"],
    optional: ["curry-leaves", "green-chilli", "coriander", "peanuts", "lemon"],
    method:
      "Cube 6 slices of bread and toast dry in a pan for 3 minutes so they hold their shape later. Temper mustard and curry leaves, fry 1 onion and 1 tomato with ¼ tsp turmeric till soft, then fold the bread through with a sprinkle of water. Slightly stale bread works better than fresh.",
  },
  {
    id: "bread-pakora",
    name: "Bread Pakora",
    cuisine: "Indian street",
    tag: "veg",
    time: 25,
    stove: true,
    need: ["bread", "besan", "potato"],
    optional: ["green-chilli", "coriander", "chaat-masala", "onion"],
    method:
      "Mash 2 boiled potatoes with chilli, coriander, ½ tsp chaat masala and salt, sandwich between bread slices and halve them. Whisk 1 cup besan with ½ tsp ajwain, a pinch of soda and water to a thick coating batter. Dip and deep-fry at 180°C for 4 minutes till deep gold.",
  },
  {
    id: "bread-halwa",
    name: "Bread Halwa",
    cuisine: "Indian",
    tag: "veg",
    time: 25,
    stove: true,
    need: ["bread", "milk", "sugar", "ghee"],
    optional: ["cashew", "raisins", "cream"],
    method:
      "Fry 6 cubed bread slices in 4 tbsp ghee till evenly deep brown — this browning is the entire flavour of the dish, so do not rush it. Pour in 300 ml hot milk and mash to a paste. Add 6 tbsp sugar and cook 6 minutes till it thickens and leaves the pan.",
  },
  {
    id: "bread-omelette",
    name: "Bread Omelette",
    cuisine: "Indian street",
    tag: "egg",
    time: 10,
    stove: true,
    need: ["bread", "eggs", "onion"],
    optional: ["green-chilli", "coriander", "cheese", "ketchup"],
    method:
      "Beat 2 eggs with ¼ chopped onion, 1 chilli, coriander and salt. Pour into a hot buttered pan and immediately lay 2 bread slices on top, pressing so the egg grips. After 2 minutes flip the whole thing and cook 1 minute more.",
  },
  {
    id: "french-toast",
    name: "French Toast",
    cuisine: "Global",
    tag: "egg",
    time: 12,
    stove: true,
    need: ["bread", "eggs", "milk", "sugar"],
    optional: ["butter", "honey", "jam", "cream"],
    method:
      "Whisk 2 eggs with 80 ml milk, 2 tbsp sugar and a pinch of cinnamon in a shallow dish. Soak each bread slice 10 seconds a side — longer and it collapses. Fry in butter on medium for 2 minutes a side till custardy inside and lacquered outside.",
  },
  {
    id: "bread-croutons",
    name: "Garlic Croutons",
    cuisine: "Global",
    tag: "veg",
    time: 12,
    stove: true,
    need: ["bread"],
    optional: ["butter", "garlic", "oregano-mix", "cheese"],
    method:
      "Cube 4 bread slices and toss with 2 tbsp melted butter, 2 minced garlic cloves, 1 tsp mixed herbs and salt. Toast in a dry pan on medium-low for 8 minutes, shaking every 2 minutes. They keep a week in a jar once fully cooled.",
  },
  {
    id: "bread-dahi-vada",
    name: "Instant Bread Dahi Vada",
    cuisine: "Indian",
    tag: "veg",
    time: 15,
    stove: false,
    need: ["bread", "curd"],
    optional: ["tamarind", "chaat-masala", "coriander", "peanuts"],
    method:
      "Trim the crusts from 4 slices, dip each briefly in water and press between your palms to squeeze it almost dry, then fold into a ball. Whisk 1½ cups curd with 1 tsp sugar and salt and pour over. Top with tamarind chutney, chaat masala and coriander; rest 10 minutes before eating.",
  },
  {
    id: "chilli-cheese-toast",
    name: "Chilli Cheese Toast",
    cuisine: "Indian bakery",
    tag: "veg",
    time: 12,
    stove: true,
    need: ["bread", "cheese", "capsicum"],
    optional: ["onion", "chilli-sauce", "oregano-mix", "butter", "green-chilli"],
    method:
      "Mix 1 cup grated cheese with finely chopped capsicum, onion, 2 green chillies and a pinch of pepper. Butter 4 bread slices, pile the mix on thickly and press it down. Cook covered in a pan on low for 5 minutes till the cheese bubbles and the base is crisp.",
  },
  {
    id: "veg-mayo-sandwich",
    name: "Veg Mayo Sandwich",
    cuisine: "Global",
    tag: "veg",
    time: 8,
    stove: false,
    need: ["bread", "mayo", "cucumber"],
    optional: ["tomato", "onion", "capsicum", "chaat-masala", "cheese"],
    method:
      "Slice cucumber, tomato and onion paper-thin and pat dry on a towel so the bread stays crisp. Mix 4 tbsp mayo with ½ tsp chaat masala, pepper and a squeeze of lemon, spread on both slices edge to edge. Layer the veg, press gently and cut diagonally.",
  },
  {
    id: "bread-rolls",
    name: "Potato Bread Rolls",
    cuisine: "Indian",
    tag: "veg",
    time: 25,
    stove: true,
    need: ["bread", "potato", "green-chilli"],
    optional: ["coriander", "garam-masala", "onion", "peas"],
    method:
      "Mash 3 boiled potatoes with 2 chillies, coriander, ½ tsp garam masala and salt, and roll into 6 logs. Dip each bread slice in water, squeeze out fully, flatten in your palm, wrap around a log and seal every seam. Deep-fry at 180°C for 3 minutes till mahogany.",
  },
  {
    id: "bruschetta",
    name: "Tomato Bruschetta",
    cuisine: "Italian",
    tag: "veg",
    time: 12,
    stove: true,
    need: ["bread", "tomato", "garlic"],
    optional: ["oregano-mix", "cheese", "onion", "coriander"],
    method:
      "Toast 4 thick bread slices dry till rigid, then rub a raw garlic clove hard across the hot surface — the toast grates the garlic into it. Toss 2 deseeded diced tomatoes with 1 tbsp olive oil, salt and herbs, and spoon on just before serving so the toast stays crunchy.",
  },
  {
    id: "mushroom-toast",
    name: "Garlic Mushroom Toast",
    cuisine: "Global",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["mushroom", "garlic", "bread", "butter"],
    optional: ["oregano-mix", "cheese", "cream", "coriander"],
    method:
      "Sear 200 g sliced mushrooms in 2 tbsp butter on high without stirring for 3 minutes so they colour instead of steaming — only then add salt. Add 3 sliced garlic cloves and pepper, cook 1 minute more. Pile on toast; a spoon of cream turns it into a full supper.",
  },
  {
    id: "guacamole-toast",
    name: "Guacamole Toast",
    cuisine: "Global",
    tag: "veg",
    time: 10,
    stove: false,
    need: ["avocado", "bread", "lemon"],
    optional: ["tomato", "onion", "green-chilli", "coriander", "corn"],
    method:
      "Mash 1 ripe avocado with the juice of half a lemon, ½ tsp salt and pepper, keeping it chunky. Fold in finely chopped onion, tomato and chilli. Pile onto toast — the lemon is structural, it stops the avocado browning within minutes.",
  },
  {
    id: "dal-paratha",
    name: "Dal Paratha",
    cuisine: "North Indian",
    tag: "veg",
    time: 25,
    stove: true,
    need: ["cooked-dal", "atta", "onion"],
    optional: ["green-chilli", "coriander", "garam-masala", "ghee"],
    method:
      "Thicken 1 cup leftover dal in a pan for 4 minutes till almost dry, then mix with chopped onion, chilli, coriander and ½ tsp garam masala. Knead into 2 cups atta with no extra water — the dal carries all the moisture. Roll and roast on a tawa with ghee, 2 minutes a side.",
  },
  {
    id: "dal-chilla",
    name: "Dal Chilla",
    cuisine: "Indian",
    tag: "veg",
    time: 20,
    stove: true,
    need: ["cooked-dal", "besan", "onion"],
    optional: ["green-chilli", "coriander", "tomato", "chaat-masala"],
    method:
      "Whisk 1 cup dal with ¾ cup besan and enough water to a pouring batter, then stir in chopped onion, tomato, chilli and coriander. Rest 10 minutes. Ladle onto a hot greased tawa, spread thin, drizzle oil around the rim and flip once at 2 minutes.",
  },
  {
    id: "dal-khichdi",
    name: "Dal Khichdi Bowl",
    cuisine: "Indian",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["cooked-dal", "cooked-rice"],
    optional: ["ghee", "onion", "tomato", "garam-masala", "coriander"],
    method:
      "Simmer 1 cup dal with 1 cup rice and 150 ml water for 6 minutes, mashing lightly till it turns soft and spoonable. Pour over a tempering of 1 tbsp ghee with cumin, hing and a dried chilli. Khichdi should pour off the spoon, so keep it looser than feels right.",
  },
  {
    id: "dal-soup",
    name: "Garlic Dal Soup",
    cuisine: "Indian",
    tag: "veg",
    time: 12,
    stove: true,
    need: ["cooked-dal", "garlic", "lemon"],
    optional: ["coriander", "tomato", "ginger", "butter"],
    method:
      "Blend 1 cup dal with 300 ml water till silky and pass it through a sieve if you want it restaurant-smooth. Sizzle 4 sliced garlic cloves in 1 tbsp ghee till pale gold, pour in the dal and simmer 5 minutes. Finish off the heat with lemon juice and cracked pepper.",
  },
  {
    id: "dal-tadka",
    name: "Everyday Dal Tadka",
    cuisine: "North Indian",
    tag: "veg",
    time: 30,
    stove: true,
    need: ["toor-dal", "tomato", "garlic"],
    optional: ["onion", "ghee", "coriander", "green-chilli", "ginger"],
    method:
      "Pressure-cook 1 cup toor dal with 3 cups water, ½ tsp turmeric and salt for 4 whistles, then whisk it smooth. Temper cumin, 5 sliced garlic cloves and 2 chillies in 2 tbsp ghee till the garlic is golden, add 1 chopped tomato and cook 3 minutes. Pour over the dal and simmer 5 minutes.",
  },
  {
    id: "masala-vada",
    name: "Chana Dal Masala Vada",
    cuisine: "South Indian",
    tag: "veg",
    time: 30,
    stove: true,
    need: ["chana-dal", "onion", "green-chilli"],
    optional: ["curry-leaves", "ginger", "coriander", "coconut"],
    method:
      "Soak 1 cup chana dal 2 hours, drain fully, and pulse to a coarse paste with chillies and ginger — no water, and leave a third of the dal whole for crunch. Mix in onion, curry leaves and salt only just before frying. Flatten into discs and fry at 170°C for 4 minutes.",
  },
  {
    id: "medu-vada",
    name: "Medu Vada",
    cuisine: "South Indian",
    tag: "veg",
    time: 35,
    stove: true,
    need: ["urad-dal", "green-chilli"],
    optional: ["curry-leaves", "ginger", "coriander", "coconut"],
    method:
      "Soak 1 cup urad dal 3 hours and grind with barely 3 tbsp water to a fluffy batter — whip it till a dropped spoonful floats in water. Fold in chilli, ginger and curry leaves. Shape with wet hands, poke a hole, and fry at 175°C for 4 minutes till evenly golden.",
  },
  {
    id: "moong-khichdi",
    name: "Moong Dal Khichdi",
    cuisine: "Indian",
    tag: "veg",
    time: 30,
    stove: true,
    need: ["raw-rice", "moong-dal"],
    optional: ["ghee", "peas", "carrot", "ginger", "green-chilli"],
    method:
      "Rinse ½ cup rice with ½ cup moong dal, then pressure-cook with 3½ cups water, ½ tsp turmeric, ginger and salt for 3 whistles. The 1:7 grain-to-water ratio is what gives the soft porridge texture. Finish with a cumin tempering in 1 tbsp ghee.",
  },
  {
    id: "veg-pulao",
    name: "Veg Pulao",
    cuisine: "North Indian",
    tag: "veg",
    time: 30,
    stove: true,
    need: ["raw-rice", "onion", "carrot", "peas"],
    optional: ["garam-masala", "ginger", "cashew", "coriander", "ghee"],
    method:
      "Soak 1 cup basmati 20 minutes and drain. Fry whole spices and 1 sliced onion in 2 tbsp ghee till golden, add the veg and rice, toasting 2 minutes. Pour in exactly 1½ cups water, cover and cook 12 minutes on low, then rest 10 minutes off the heat before opening.",
  },
  {
    id: "chole-chaat",
    name: "Chole Chaat",
    cuisine: "Indian street",
    tag: "veg",
    time: 10,
    stove: false,
    need: ["chana", "onion", "tomato", "lemon"],
    optional: ["chaat-masala", "coriander", "green-chilli", "tamarind"],
    method:
      "Toss 1½ cups boiled chickpeas with finely chopped onion, tomato and green chilli. Season with 1 tsp chaat masala, ½ tsp roasted cumin, black salt and the juice of a whole lemon. Let it sit 5 minutes so the chickpeas drink the dressing, then add coriander.",
  },
  {
    id: "hummus",
    name: "Creamy Hummus",
    cuisine: "Middle Eastern",
    tag: "veg",
    time: 10,
    stove: false,
    need: ["chana", "lemon", "garlic"],
    optional: ["sesame-seeds", "coriander", "cucumber"],
    method:
      "Blend 1½ cups boiled chickpeas with 3 tbsp sesame paste, 1 garlic clove, juice of 1 lemon, 4 tbsp olive oil and ½ tsp salt. Add 4–6 tbsp iced water while running — the cold water is what makes it pale and whipped rather than pasty. Blend a full 3 minutes.",
  },
  {
    id: "chana-sundal",
    name: "Chana Sundal",
    cuisine: "South Indian",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["chana", "coconut"],
    optional: ["curry-leaves", "green-chilli", "ginger", "lemon"],
    method:
      "Temper 1 tsp mustard seeds, 2 dried chillies and curry leaves in 1 tbsp coconut oil with a pinch of hing. Toss in 1½ cups boiled chickpeas and salt, stir 3 minutes till dry. Take off the heat before folding in ⅓ cup grated coconut so it stays fresh and white.",
  },
  {
    id: "rajma-tikki",
    name: "Rajma Burger Tikki",
    cuisine: "Fusion",
    tag: "veg",
    time: 25,
    stove: true,
    need: ["rajma", "potato", "bread"],
    optional: ["green-chilli", "coriander", "garam-masala", "onion", "cheese"],
    method:
      "Coarsely mash 1 cup rajma with 2 boiled potatoes, 2 crumbled bread slices, ½ tsp garam masala, chilli and salt — leave some beans whole for bite. Chill the shaped patties 15 minutes so they firm up. Pan-sear in 2 tbsp oil, 3 minutes a side, undisturbed.",
  },
  {
    id: "rajma-chawal",
    name: "Quick Rajma Chawal Bowl",
    cuisine: "North Indian",
    tag: "veg",
    time: 12,
    stove: true,
    need: ["rajma", "cooked-rice", "onion"],
    optional: ["coriander", "lemon", "garam-masala", "ghee", "tomato"],
    method:
      "Fry 1 sliced onion in 1 tbsp ghee till deep brown, add 1 cup cooked rajma with ½ tsp garam masala and 100 ml water, and mash a quarter of the beans against the pan to thicken the gravy. Simmer 5 minutes and spoon over hot rice with raw onion and lemon.",
  },
  {
    id: "black-bean-quesadilla",
    name: "Black Bean Quesadilla",
    cuisine: "Mexican",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["black-beans", "tortilla", "cheese"],
    optional: ["onion", "tomato", "capsicum", "avocado", "coriander"],
    method:
      "Mash 1 cup black beans roughly with ½ tsp cumin, salt and a squeeze of lemon. Spread over half a tortilla, top with ⅓ cup cheese and chopped onion, fold over. Dry-toast 3 minutes a side on medium-low, pressing flat, till the outside blisters.",
  },
  {
    id: "sprouts-bhel",
    name: "Sprouts Bhel",
    cuisine: "Indian street",
    tag: "veg",
    time: 10,
    stove: false,
    need: ["sprouts", "onion", "tomato", "lemon"],
    optional: ["chaat-masala", "coriander", "green-chilli", "peanuts", "tamarind"],
    method:
      "Toss 1½ cups sprouts with finely chopped onion, tomato and chilli. Season with 1 tsp chaat masala, ½ tsp black salt and the juice of a lemon. Mix and serve within minutes — salt draws water from the tomato and it goes limp if it stands.",
  },
  {
    id: "sprouts-usal",
    name: "Sprouts Usal",
    cuisine: "Maharashtrian",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["sprouts", "onion", "garlic"],
    optional: ["tomato", "coconut", "garam-masala", "coriander", "curry-leaves"],
    method:
      "Temper mustard seeds and curry leaves in 2 tbsp oil, fry 1 onion and 4 crushed garlic cloves till golden. Add 2 cups sprouts, ½ tsp turmeric, 1 tsp goda or garam masala and 150 ml water; simmer covered 8 minutes. Finish with coconut and a big handful of coriander.",
  },
  {
    id: "paneer-bhurji",
    name: "Paneer Bhurji",
    cuisine: "North Indian",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["paneer", "onion", "tomato"],
    optional: ["green-chilli", "coriander", "garam-masala", "capsicum", "butter"],
    method:
      "Fry 1 chopped onion and 2 chillies in 2 tbsp butter, add 1 tomato and cook 4 minutes till it collapses. Crumble in 200 g paneer with ¼ tsp turmeric and ½ tsp garam masala, and stir just 2 minutes. Any longer and the paneer turns rubbery instead of soft.",
  },
  {
    id: "paneer-tikka",
    name: "Pan-Seared Paneer Tikka",
    cuisine: "North Indian",
    tag: "veg",
    time: 25,
    stove: true,
    need: ["paneer", "curd", "capsicum"],
    optional: ["garam-masala", "lemon", "onion", "chaat-masala", "ginger"],
    method:
      "Whisk ½ cup thick curd with 1 tsp chilli powder, ½ tsp garam masala, 1 tsp ginger-garlic paste, 1 tbsp oil and salt. Coat 250 g paneer cubes with capsicum and onion chunks; marinate 15 minutes. Sear on a screaming-hot pan 2 minutes a side, then hit with lemon and chaat masala.",
  },
  {
    id: "paneer-paratha",
    name: "Paneer Paratha",
    cuisine: "North Indian",
    tag: "veg",
    time: 25,
    stove: true,
    need: ["paneer", "atta", "green-chilli"],
    optional: ["coriander", "onion", "garam-masala", "ghee", "ginger"],
    method:
      "Grate 200 g paneer and mix with 2 chopped chillies, coriander, ½ tsp chaat masala and salt — no onion unless you squeeze it dry first. Stuff into a small disc of atta dough, seal, and roll gently with even pressure. Roast on a tawa with ghee, 2 minutes a side.",
  },
  {
    id: "chilli-paneer",
    name: "Chilli Paneer",
    cuisine: "Indo-Chinese",
    tag: "veg",
    time: 20,
    stove: true,
    need: ["paneer", "capsicum", "soy-sauce", "onion"],
    optional: ["chilli-sauce", "ketchup", "garlic", "vinegar", "maida"],
    method:
      "Toss 250 g paneer cubes in 2 tbsp cornflour and fry till crusted, then set aside. In the same pan sear garlic, onion petals and capsicum on high for 2 minutes, add 1 tbsp soy sauce, 1 tbsp chilli sauce, 1 tsp vinegar and 3 tbsp water. Return the paneer and toss 30 seconds only.",
  },
  {
    id: "palak-paneer-sabzi",
    name: "Palak Sabzi",
    cuisine: "North Indian",
    tag: "veg",
    time: 20,
    stove: true,
    need: ["spinach", "garlic", "onion"],
    optional: ["tomato", "green-chilli", "paneer", "cream", "ginger"],
    method:
      "Blanch 400 g spinach for 90 seconds and drop straight into ice water — this is what keeps it emerald instead of khaki. Blend coarsely. Fry onion, 5 garlic cloves and chilli in 2 tbsp ghee, add the purée and simmer just 5 minutes. Fold in paneer at the end.",
  },
  {
    id: "masala-omelette",
    name: "Masala Omelette",
    cuisine: "Indian",
    tag: "egg",
    time: 8,
    stove: true,
    need: ["eggs", "onion", "green-chilli"],
    optional: ["tomato", "coriander", "cheese", "capsicum"],
    method:
      "Beat 3 eggs hard for 30 seconds till frothy, then stir in ¼ chopped onion, 1 chilli, coriander, salt and a pinch of turmeric. Pour into a buttered pan on medium-low and pull the set edges inward for the first minute. Fold once the top is just barely wet.",
  },
  {
    id: "egg-bhurji",
    name: "Egg Bhurji",
    cuisine: "Indian",
    tag: "egg",
    time: 12,
    stove: true,
    need: ["eggs", "onion", "tomato"],
    optional: ["green-chilli", "coriander", "garam-masala", "butter", "bread"],
    method:
      "Fry 1 chopped onion and 2 chillies in 2 tbsp butter till pink, add 1 tomato with ¼ tsp turmeric and cook 3 minutes. Pour in 4 beaten eggs and wait 20 seconds before stirring, then scramble on low. Take it off while it still looks slightly underdone — it carries on cooking.",
  },
  {
    id: "veg-frittata",
    name: "Veggie Frittata",
    cuisine: "Italian",
    tag: "egg",
    time: 25,
    stove: true,
    need: ["eggs", "potato", "onion"],
    optional: ["capsicum", "cheese", "spinach", "mushroom", "oregano-mix"],
    method:
      "Soften 2 sliced boiled potatoes and 1 onion in 3 tbsp oil in a small pan. Beat 5 eggs with salt, pepper and ⅓ cup cheese, pour over the veg and cook on the lowest flame, covered, for 12 minutes till only the centre wobbles. Rest 5 minutes before sliding out and slicing.",
  },
  {
    id: "egg-fried-rice",
    name: "Egg Fried Rice",
    cuisine: "Indo-Chinese",
    tag: "egg",
    time: 12,
    stove: true,
    need: ["cooked-rice", "eggs", "soy-sauce"],
    optional: ["onion", "carrot", "peas", "chilli-sauce", "cabbage"],
    method:
      "Scramble 2 eggs in a hot oiled wok and remove while still soft. Stir-fry the veg 2 minutes on high, add 2 cups cold rice and 1 tbsp soy sauce, tossing 3 minutes. Return the egg for the last 30 seconds so it stays in fluffy ribbons rather than dissolving.",
  },
  {
    id: "shakshuka",
    name: "Shakshuka",
    cuisine: "Middle Eastern",
    tag: "egg",
    time: 25,
    stove: true,
    need: ["eggs", "tomato", "onion", "capsicum"],
    optional: ["garlic", "cheese", "coriander", "bread", "oregano-mix"],
    method:
      "Cook 1 sliced onion and 1 capsicum in 3 tbsp olive oil for 6 minutes, add 4 chopped tomatoes, 3 garlic cloves, 1 tsp paprika and ½ tsp cumin. Simmer 10 minutes to a thick sauce. Make 4 wells, crack an egg into each, cover and cook 6 minutes till the whites just set.",
  },
  {
    id: "egg-curry",
    name: "Egg Curry",
    cuisine: "Indian",
    tag: "egg",
    time: 30,
    stove: true,
    need: ["eggs", "onion", "tomato", "garam-masala"],
    optional: ["garlic", "ginger", "coriander", "curd", "green-chilli"],
    method:
      "Halve 4 boiled eggs and sear the cut sides in oil for a minute — the light crust stops them turning slippery in the gravy. Fry 2 onions to deep brown, add ginger-garlic, 2 tomatoes, 1 tsp garam masala and ½ tsp chilli powder, cook till oil separates. Add 200 ml water, simmer 8 minutes, slide the eggs in.",
  },
  {
    id: "pasta-bake",
    name: "Leftover Pasta Bake",
    cuisine: "Italian",
    tag: "veg",
    time: 25,
    stove: true,
    need: ["pasta", "cheese", "pasta-sauce"],
    optional: ["capsicum", "onion", "oregano-mix", "corn", "mushroom"],
    method:
      "Toss 3 cups cooked pasta with 1 cup pasta sauce, sautéed veg and 4 tbsp milk so it does not dry out. Layer in a pan, blanket with 1 cup cheese, cover with a tight lid and cook on the lowest flame for 12 minutes. The lid traps steam and browns the top like a grill would.",
  },
  {
    id: "desi-masala-pasta",
    name: "Desi Masala Pasta",
    cuisine: "Fusion",
    tag: "veg",
    time: 20,
    stove: true,
    need: ["pasta", "onion", "tomato"],
    optional: ["capsicum", "garam-masala", "ketchup", "cheese", "green-chilli"],
    method:
      "Fry 1 onion and 1 capsicum in 2 tbsp oil, add 2 puréed tomatoes with ½ tsp turmeric, 1 tsp chilli powder and ½ tsp garam masala; cook 6 minutes till thick. Fold in 3 cups boiled pasta with 3 tbsp ketchup and a splash of the pasta water. That starchy water is what makes the sauce cling.",
  },
  {
    id: "aglio-e-olio",
    name: "Aglio e Olio",
    cuisine: "Italian",
    tag: "veg",
    time: 12,
    stove: true,
    need: ["pasta", "garlic"],
    optional: ["oregano-mix", "cheese", "broccoli", "coriander"],
    method:
      "Warm 6 thinly sliced garlic cloves in 5 tbsp olive oil on the lowest heat for 4 minutes till pale gold, never brown, with a pinch of chilli flakes. Add 3 cups hot pasta and 80 ml pasta water, tossing hard for a minute till the oil and water emulsify into a glossy sauce.",
  },
  {
    id: "mac-and-cheese",
    name: "Stovetop Mac & Cheese",
    cuisine: "American",
    tag: "veg",
    time: 20,
    stove: true,
    need: ["pasta", "milk", "cheese", "butter"],
    optional: ["maida", "oregano-mix", "garlic"],
    method:
      "Cook 2 tbsp butter with 2 tbsp maida for 2 minutes, then whisk in 400 ml milk a little at a time and simmer till it coats a spoon. Kill the heat before stirring in 1½ cups cheese — boiling cheese sauce splits. Fold through 3 cups pasta with mustard and pepper.",
  },
  {
    id: "pasta-frittata",
    name: "Pasta Frittata",
    cuisine: "Italian",
    tag: "egg",
    time: 20,
    stove: true,
    need: ["pasta", "eggs", "cheese"],
    optional: ["onion", "oregano-mix", "capsicum", "pasta-sauce"],
    method:
      "Beat 4 eggs with ½ cup cheese, salt and pepper, and fold in 2 cups leftover pasta — sauced pasta works even better. Pour into a small oiled pan and cook covered on the lowest flame for 10 minutes. Flip onto a plate and slide back for 3 minutes to set the second face.",
  },
  {
    id: "cold-pasta-salad",
    name: "Cold Pasta Salad",
    cuisine: "Global",
    tag: "veg",
    time: 10,
    stove: false,
    need: ["pasta", "cucumber", "tomato", "mayo"],
    optional: ["corn", "capsicum", "oregano-mix", "lemon", "onion"],
    method:
      "Rinse 3 cups cooked pasta under cold water and drain thoroughly. Whisk 4 tbsp mayo with 1 tbsp lemon juice, 1 tsp mixed herbs, salt and pepper, then toss with diced cucumber, tomato and corn. Chill 20 minutes; loosen with a spoon of milk if it tightens up.",
  },
  {
    id: "hakka-noodles",
    name: "Veg Hakka Noodles",
    cuisine: "Indo-Chinese",
    tag: "veg",
    time: 20,
    stove: true,
    need: ["noodles", "cabbage", "soy-sauce", "onion"],
    optional: ["carrot", "capsicum", "chilli-sauce", "vinegar", "garlic"],
    method:
      "Boil the noodles 1 minute short of the packet time, rinse cold and toss with 1 tsp oil. Stir-fry garlic and julienned cabbage, carrot and capsicum on the highest flame for 3 minutes — they must stay crunchy. Add the noodles, 1 tbsp soy sauce, 1 tsp vinegar and 1 tsp chilli sauce, and toss with tongs for 2 minutes.",
  },
  {
    id: "kanda-poha",
    name: "Kanda Poha",
    cuisine: "Maharashtrian",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["poha", "onion", "potato"],
    optional: ["peanuts", "curry-leaves", "green-chilli", "lemon", "coriander"],
    method:
      "Rinse 2 cups thick poha in a colander for 20 seconds, then leave to swell for 10 minutes — never soak it in standing water. Temper mustard, curry leaves and peanuts, fry onion and diced potato till tender. Fold in the poha with ½ tsp sugar, ¼ tsp turmeric and salt; steam covered 3 minutes and finish with lemon.",
  },
  {
    id: "rava-upma",
    name: "Rava Upma",
    cuisine: "South Indian",
    tag: "veg",
    time: 20,
    stove: true,
    need: ["rava", "onion"],
    optional: ["carrot", "peas", "curry-leaves", "green-chilli", "ginger", "lemon"],
    method:
      "Dry-roast 1 cup rava for 5 minutes till it smells nutty and stops clumping, then set aside. Temper mustard, urad dal and curry leaves in 2 tbsp oil, fry onion, chilli and ginger, add 3 cups water and salt and bring to a rolling boil. Rain the rava in with one hand while stirring hard with the other, cover 3 minutes.",
  },
  {
    id: "rava-sheera",
    name: "Rava Sheera",
    cuisine: "Indian",
    tag: "veg",
    time: 20,
    stove: true,
    need: ["rava", "sugar", "ghee"],
    optional: ["milk", "cashew", "raisins"],
    method:
      "Roast 1 cup rava in 6 tbsp ghee on low for 8 minutes till it turns pale gold — this decides the whole texture. Pour in 3 cups boiling water or milk carefully, standing back from the steam, and stir till it absorbs. Add ¾ cup sugar, cook 4 minutes more till it leaves the pan.",
  },
  {
    id: "suji-toast",
    name: "Suji Veg Toast",
    cuisine: "Indian",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["rava", "curd", "bread"],
    optional: ["capsicum", "carrot", "coriander", "onion", "green-chilli"],
    method:
      "Mix ½ cup rava with ½ cup curd, salt and 2 tbsp water to a thick spreadable paste and rest 10 minutes. Stir in finely chopped capsicum, carrot, onion and coriander. Spread thickly on bread slices and cook paste-side down in a buttered pan on low for 4 minutes till crusted.",
  },
  {
    id: "oats-chilla",
    name: "Savoury Oats Chilla",
    cuisine: "Indian",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["oats", "besan", "onion"],
    optional: ["tomato", "green-chilli", "coriander", "carrot", "curd"],
    method:
      "Blitz 1 cup oats to a coarse flour, whisk with ½ cup besan, salt and 250 ml water to a thin batter, and rest 10 minutes so it thickens naturally. Stir in chopped onion, tomato, chilli and coriander. Spread thin on a hot tawa, oil the edges, and flip once at 2 minutes.",
  },
  {
    id: "masala-oats",
    name: "Masala Oats",
    cuisine: "Indian",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["oats", "onion", "tomato"],
    optional: ["peas", "carrot", "green-chilli", "coriander", "garam-masala"],
    method:
      "Temper cumin, fry 1 onion, chilli and diced veg for 3 minutes, then add 1 tomato with ¼ tsp turmeric and ½ tsp garam masala. Pour in 400 ml water, bring to a boil and stir in 1 cup oats. Cook just 4 minutes — oats keep swelling off the heat and turn to paste if overdone.",
  },
  {
    id: "overnight-oats",
    name: "Overnight Oats",
    cuisine: "Global",
    tag: "veg",
    time: 5,
    stove: false,
    need: ["oats", "milk", "honey"],
    optional: ["peanut-butter", "jam", "cashew", "raisins", "curd"],
    method:
      "Stir ½ cup rolled oats with 150 ml milk, 2 tbsp curd, 1 tbsp honey and a pinch of salt in a jar — the 1:3 oats-to-liquid ratio is what sets the texture. Add 1 tbsp peanut butter or chopped nuts. Refrigerate at least 6 hours; it keeps 3 days and thickens each day.",
  },
  {
    id: "aloo-paratha",
    name: "Aloo Paratha",
    cuisine: "North Indian",
    tag: "veg",
    time: 30,
    stove: true,
    need: ["potato", "atta", "green-chilli"],
    optional: ["coriander", "onion", "garam-masala", "ghee", "chaat-masala"],
    method:
      "Mash 3 boiled potatoes while cold with chilli, coriander, ½ tsp garam masala, 1 tsp chaat masala and salt — warm potato leaks water and tears the paratha. Stuff a generous ball into a dough disc, seal and roll evenly. Roast on a hot tawa with ghee till both sides are freckled brown.",
  },
  {
    id: "jeera-aloo",
    name: "Jeera Aloo",
    cuisine: "North Indian",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["potato"],
    optional: ["coriander", "green-chilli", "lemon", "chaat-masala", "ginger"],
    method:
      "Crackle 1½ tsp cumin seeds in 3 tbsp oil, add 2 slit chillies, then 4 cubed boiled potatoes with ¼ tsp turmeric, ½ tsp chilli powder, 1 tsp coriander powder and salt. Fry 8 minutes on medium without stirring too often so a crust forms. Finish with lemon and coriander.",
  },
  {
    id: "aloo-chaat",
    name: "Aloo Chaat",
    cuisine: "Indian street",
    tag: "veg",
    time: 12,
    stove: true,
    need: ["potato", "lemon", "chaat-masala"],
    optional: ["onion", "tomato", "coriander", "tamarind", "green-chilli"],
    method:
      "Crisp 3 cubed boiled potatoes in 3 tbsp oil on high for 6 minutes till the edges are hard and golden. Drain and toss while hot with 1 tsp chaat masala, ½ tsp roasted cumin, black salt, lemon juice and chopped onion. Dress at the last moment or the crust softens.",
  },
  {
    id: "pav-bhaji",
    name: "Pav Bhaji",
    cuisine: "Mumbai street",
    tag: "veg",
    time: 30,
    stove: true,
    need: ["potato", "peas", "pav-bhaji-masala", "tomato"],
    optional: ["capsicum", "butter", "bread", "onion", "lemon", "cauliflower"],
    method:
      "Fry 1 onion and 1 capsicum in 3 tbsp butter, add 3 tomatoes and cook to a pulp, then 2 tbsp pav bhaji masala and 1 tsp chilli powder. Add 3 boiled potatoes and ½ cup peas with 200 ml water and mash relentlessly for 8 minutes. Finish with more butter and lemon; toast the pav in the leftover masala butter.",
  },
  {
    id: "vada-pav",
    name: "Vada Pav",
    cuisine: "Mumbai street",
    tag: "veg",
    time: 30,
    stove: true,
    need: ["potato", "besan", "bread"],
    optional: ["garlic", "green-chilli", "coriander", "curry-leaves"],
    method:
      "Mash 3 boiled potatoes with a tempering of mustard, curry leaves, 5 crushed garlic cloves, 2 chillies and ¼ tsp turmeric; roll into 6 balls. Dip in a batter of 1 cup besan, a pinch of soda and water, and fry at 180°C for 4 minutes. Serve in pav with dry garlic chutney.",
  },
  {
    id: "veg-cutlet",
    name: "Mixed Veg Cutlet",
    cuisine: "Indian",
    tag: "veg",
    time: 30,
    stove: true,
    need: ["potato", "carrot", "peas", "bread"],
    optional: ["green-chilli", "coriander", "garam-masala", "corn", "french-beans"],
    method:
      "Boil and finely chop carrot, beans and peas, then squeeze the mix dry in a cloth — wet filling is why cutlets break. Combine with 3 mashed potatoes, 2 crumbled bread slices, ½ tsp garam masala and salt. Shape, coat in crumbs, and shallow-fry 3 minutes a side.",
  },
  {
    id: "cabbage-thoran",
    name: "Cabbage Thoran",
    cuisine: "Kerala",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["cabbage", "coconut"],
    optional: ["curry-leaves", "green-chilli", "garlic", "ginger"],
    method:
      "Crush ½ cup grated coconut with 2 green chillies, 2 garlic cloves and ¼ tsp turmeric — a rough pound, not a paste. Temper mustard and curry leaves in coconut oil, add 4 cups shredded cabbage and salt, and cook uncovered 6 minutes. Stir in the coconut mix and cook 2 minutes more.",
  },
  {
    id: "beans-poriyal",
    name: "Beans Poriyal",
    cuisine: "South Indian",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["french-beans", "coconut"],
    optional: ["curry-leaves", "green-chilli", "carrot", "ginger"],
    method:
      "Chop 300 g beans as finely as you can — the cut is the dish. Temper mustard, urad dal and curry leaves in 2 tbsp oil, add the beans with 3 tbsp water and salt, cover and steam 8 minutes. Uncover, dry off any water, and fold in ⅓ cup grated coconut off the heat.",
  },
  {
    id: "gobi-65",
    name: "Gobi 65",
    cuisine: "South Indian",
    tag: "veg",
    time: 30,
    stove: true,
    need: ["cauliflower", "besan", "rice-flour"],
    optional: ["curd", "garlic", "green-chilli", "curry-leaves", "ginger"],
    method:
      "Blanch florets from 1 cauliflower for 3 minutes in salted water and dry them completely. Coat in a thick batter of ½ cup besan, ¼ cup rice flour, 3 tbsp curd, 1 tsp chilli powder, ginger-garlic and salt. Fry at 180°C for 4 minutes; the rice flour is what keeps them crunchy as they cool.",
  },
  {
    id: "tomato-soup",
    name: "Tomato Garlic Soup",
    cuisine: "Global",
    tag: "veg",
    time: 25,
    stove: true,
    need: ["tomato", "garlic"],
    optional: ["butter", "cream", "bread", "oregano-mix", "onion"],
    method:
      "Simmer 6 quartered tomatoes with 1 onion, 6 garlic cloves and 400 ml water for 15 minutes till everything collapses. Blend and pass through a sieve for a velvet texture. Return to the pan with 1 tbsp butter, ½ tsp sugar to cut the acidity, salt and pepper; swirl in cream.",
  },
  {
    id: "corn-chaat",
    name: "Buttery Corn Chaat",
    cuisine: "Indian street",
    tag: "veg",
    time: 10,
    stove: true,
    need: ["corn", "onion", "lemon"],
    optional: ["butter", "chaat-masala", "coriander", "tomato", "green-chilli"],
    method:
      "Toss 2 cups boiled corn in 1 tbsp butter on high for 2 minutes till a few kernels blister and pop. Off the heat, mix with finely chopped onion, tomato and chilli, 1 tsp chaat masala, black salt and a full squeeze of lemon. Eat warm — it is a different dish cold.",
  },
  {
    id: "broccoli-stirfry",
    name: "Garlic Broccoli Stir-Fry",
    cuisine: "Asian",
    tag: "veg",
    time: 12,
    stove: true,
    need: ["broccoli", "garlic", "soy-sauce"],
    optional: ["sesame-seeds", "chilli-sauce", "corn", "ginger", "honey"],
    method:
      "Blanch florets from 1 broccoli for 90 seconds and shock in cold water to lock the colour. Sear 4 sliced garlic cloves in 2 tbsp oil for 30 seconds, add the broccoli on the highest flame, then 1 tbsp soy sauce, 1 tsp honey and 2 tbsp water. Toss 2 minutes till glazed.",
  },
  {
    id: "cucumber-raita",
    name: "Cucumber Raita",
    cuisine: "Indian",
    tag: "veg",
    time: 5,
    stove: false,
    need: ["curd", "cucumber"],
    optional: ["coriander", "chaat-masala", "green-chilli", "mint", "onion"],
    method:
      "Grate 1 cucumber and squeeze out the water in your fist, saving it to thin the raita later. Whisk 1 cup curd smooth with ½ tsp roasted cumin, black salt and a pinch of sugar, then fold in the cucumber, mint and coriander. Chill 10 minutes.",
  },
  {
    id: "mint-chutney",
    name: "Mint Coriander Chutney",
    cuisine: "Indian",
    tag: "veg",
    time: 10,
    stove: false,
    need: ["mint", "coriander", "green-chilli", "lemon"],
    optional: ["curd", "garlic", "peanuts", "ginger", "onion"],
    method:
      "Blend 1 cup mint leaves with 1 cup coriander, 2 chillies, 1 garlic clove, ½ tsp salt and 2 tbsp lemon juice, using ice water instead of tap water — the cold stops the leaves oxidising to brown. Blend in short pulses. Add 2 tbsp curd for a creamier, milder version.",
  },
  {
    id: "tamarind-chutney",
    name: "Sweet Tamarind Chutney",
    cuisine: "Indian",
    tag: "veg",
    time: 15,
    stove: true,
    need: ["tamarind", "jaggery"],
    optional: ["ginger", "raisins", "chaat-masala"],
    method:
      "Simmer 50 g tamarind with 300 ml water for 8 minutes, then mash and strain out the fibre. Return the pulp with 100 g jaggery, 1 tsp roasted cumin, ½ tsp dry ginger and ½ tsp chilli powder, and cook 5 minutes to a pouring syrup. It thickens a lot once cold, so pull it early.",
  },
  {
    id: "quinoa-salad",
    name: "Quinoa Salad Bowl",
    cuisine: "Global",
    tag: "veg",
    time: 10,
    stove: false,
    need: ["quinoa", "cucumber", "tomato", "lemon"],
    optional: ["corn", "coriander", "avocado", "onion", "mint"],
    method:
      "Fluff 2 cups cooled quinoa and toss with diced cucumber, deseeded tomato, red onion and a fistful of chopped mint and coriander. Whisk juice of 1 lemon with 3 tbsp olive oil, ½ tsp salt and pepper, and dress generously — quinoa is bland and drinks far more dressing than you expect.",
  },
  {
    id: "chicken-fried-rice",
    name: "Chicken Fried Rice",
    cuisine: "Indo-Chinese",
    tag: "non-veg",
    time: 15,
    stove: true,
    need: ["cooked-rice", "cooked-chicken", "soy-sauce"],
    optional: ["eggs", "onion", "carrot", "capsicum", "chilli-sauce"],
    method:
      "Shred 1 cup leftover chicken. Scramble 2 eggs in a hot wok and remove, then stir-fry onion and diced veg on high for 2 minutes. Add 2 cups cold rice, the chicken and 1 tbsp soy sauce, tossing 3 minutes, and return the egg at the very end.",
  },
  {
    id: "chicken-roll",
    name: "Chicken Kathi Roll",
    cuisine: "Kolkata street",
    tag: "non-veg",
    time: 12,
    stove: true,
    need: ["cooked-chicken", "roti", "onion"],
    optional: ["mayo", "chaat-masala", "capsicum", "lemon", "green-chilli"],
    method:
      "Toss 1 cup shredded chicken in a hot pan with ½ tsp chilli powder and ½ tsp garam masala for 2 minutes to wake it up. Warm a roti, spread mayo, add the chicken, thin onion rings, lemon and a heavy dust of chaat masala. Roll tight and toast the seam side down for 30 seconds.",
  },
  {
    id: "chicken-sandwich",
    name: "Chicken Mayo Sandwich",
    cuisine: "Global",
    tag: "non-veg",
    time: 10,
    stove: false,
    need: ["cooked-chicken", "bread", "mayo"],
    optional: ["cucumber", "onion", "cheese", "coriander", "lemon"],
    method:
      "Shred 1 cup cooked chicken and mix with 4 tbsp mayo, ½ tsp mustard, chopped onion, pepper and a squeeze of lemon. Taste and salt properly — cold fillings always need more than they seem to. Spread thickly on bread, add cucumber for crunch, and press before slicing.",
  },
  {
    id: "chicken-pasta",
    name: "Creamy Chicken Pasta",
    cuisine: "Italian",
    tag: "non-veg",
    time: 20,
    stove: true,
    need: ["pasta", "cooked-chicken", "pasta-sauce"],
    optional: ["cheese", "garlic", "oregano-mix", "cream", "capsicum"],
    method:
      "Sear 3 sliced garlic cloves in 2 tbsp butter, add 1 cup shredded chicken and 1 cup pasta sauce with 4 tbsp cream, and simmer 5 minutes. Fold in 3 cups pasta with a splash of pasta water and 1 tsp mixed herbs. Toss over the heat for a minute so the sauce grips the pasta.",
  },
  {
    id: "chicken-soup",
    name: "Chicken Sweet Corn Soup",
    cuisine: "Indo-Chinese",
    tag: "non-veg",
    time: 20,
    stove: true,
    need: ["cooked-chicken", "corn", "garlic"],
    optional: ["eggs", "coriander", "vinegar", "chilli-sauce", "carrot"],
    method:
      "Simmer 1 litre stock or water with 2 minced garlic cloves, 1 cup corn and 1 cup shredded chicken for 8 minutes. Stir in 2 tbsp cornflour slaked in cold water and cook 2 minutes till it turns glossy. Trickle 1 beaten egg in while stirring one way for ribbons; finish with vinegar and pepper.",
  },
  {
    id: "chicken-curry",
    name: "Everyday Chicken Curry",
    cuisine: "Indian",
    tag: "non-veg",
    time: 40,
    stove: true,
    need: ["chicken", "onion", "tomato", "garam-masala"],
    optional: ["ginger", "garlic", "curd", "coriander", "green-chilli"],
    method:
      "Brown 2 sliced onions in 3 tbsp oil for a full 10 minutes — this is the body of the gravy. Add 1 tbsp ginger-garlic paste, 2 tomatoes, 1 tsp chilli powder, ½ tsp turmeric and 1 tsp garam masala, and cook till oil separates. Add 600 g chicken, sear 5 minutes, then 250 ml water and simmer covered 18 minutes.",
  },
  {
    id: "keema-pav",
    name: "Keema Pav",
    cuisine: "Mumbai street",
    tag: "non-veg",
    time: 30,
    stove: true,
    need: ["keema", "onion", "tomato", "garam-masala"],
    optional: ["bread", "green-chilli", "coriander", "peas", "ginger"],
    method:
      "Fry 2 chopped onions to deep brown, add ginger-garlic and 2 tomatoes and cook till pulpy. Add 400 g keema on high and break it up constantly for 5 minutes till no pink remains and it starts to fry. Add 1 tsp garam masala, ½ cup peas and 150 ml water; simmer 12 minutes till dry. Serve with buttered pav.",
  },
  {
    id: "fish-fry",
    name: "Crispy Fish Fry",
    cuisine: "Coastal Indian",
    tag: "non-veg",
    time: 25,
    stove: true,
    need: ["fish", "rice-flour", "lemon"],
    optional: ["garlic", "curry-leaves", "green-chilli", "ginger"],
    method:
      "Marinate 4 fish fillets in 1 tsp chilli powder, ¼ tsp turmeric, 1 tsp ginger-garlic, lemon juice and salt for 15 minutes. Dredge in ½ cup rice flour, pressing it on. Shallow-fry on medium-high 3 minutes a side, and only turn once — fish breaks the more you touch it.",
  },
  {
    id: "prawn-pulao",
    name: "Prawn Pulao",
    cuisine: "Coastal Indian",
    tag: "non-veg",
    time: 30,
    stove: true,
    need: ["prawns", "raw-rice", "onion"],
    optional: ["garam-masala", "ginger", "coriander", "green-chilli", "coconut"],
    method:
      "Soak 1 cup basmati 20 minutes. Sear 250 g prawns in oil for 90 seconds only and lift them out — they finish in the steam later. Fry onion, ginger-garlic, chilli and 1 tsp garam masala, add the drained rice and 1½ cups water, cook covered 12 minutes, and fold the prawns back in for the last 3.",
  },
];
