export const DAY = 24;
export const WEEK = 168;
export const MONTH = 720;
export const YEAR = 8760;

export const CATEGORIES = [
  { id: "dairy", label: "Dairy", risk: "high" },
  { id: "eggs", label: "Eggs", risk: "high" },
  { id: "meat", label: "Meat & Fish", risk: "high" },
  { id: "cooked", label: "Cooked & Leftovers", risk: "high" },
  { id: "produce", label: "Fruits & Vegetables", risk: "quality" },
  { id: "bread", label: "Breads & Bakery", risk: "quality" },
  { id: "pantry", label: "Pantry Staples", risk: "quality" },
  { id: "condiments", label: "Condiments & Sauces", risk: "quality" },
];

export const LOCATIONS = [
  { id: "pantry", label: "Pantry / counter", hint: "Room temperature, 25-35 C in most Indian homes" },
  { id: "fridge", label: "Fridge", hint: "4 C or below" },
  { id: "freezer", label: "Freezer", hint: "-18 C, frozen solid" },
];

export const FOODS = [
  {
    id: "milk-packet",
    name: "Milk (pasteurised packet, unopened)",
    category: "dairy",
    indian: true,
    pantry: { max: 4, label: "2-4 hours" },
    fridge: { max: 5 * DAY, label: "Up to 5 days, respect the pack date" },
    freezer: { max: 3 * MONTH, label: "About 3 months" },
    tips: "Move the pouch to the fridge within an hour of buying. Boiling extends it, but each re-boil costs nutrients and taste.",
    signs: ["Sour or off smell on opening", "Splits or curdles when heated", "Thickened, slimy texture", "Yellowish tinge"],
  },
  {
    id: "milk-boiled",
    name: "Milk (boiled or opened)",
    category: "dairy",
    indian: true,
    pantry: { max: 4, label: "2-4 hours, less in summer" },
    fridge: { max: 3 * DAY, label: "2-3 days in a covered vessel" },
    freezer: { max: MONTH, label: "1 month, fat separates on thawing" },
    tips: "Cool it fast before refrigerating and keep it covered. Re-boiling once a day helps in summer but changes the taste.",
    signs: ["Sour smell", "Curdles in tea or on heating", "Skin forms unusually thick and sticky"],
  },
  {
    id: "milk-uht",
    name: "UHT / tetra pack milk (unopened)",
    category: "dairy",
    pantry: { max: 6 * MONTH, label: "Up to 6 months at room temperature" },
    fridge: { max: 6 * MONTH, label: "Same as pantry, no benefit" },
    freezer: { max: 0, label: "Not needed" },
    tips: "Shelf-stable only while the pack is sealed. Once opened it behaves exactly like ordinary fresh milk.",
    signs: ["Swollen or leaking pack", "Sour smell on opening", "Separated, grainy liquid"],
  },
  {
    id: "milk-uht-open",
    name: "UHT / tetra pack milk (opened)",
    category: "dairy",
    pantry: { max: 4, label: "2-4 hours" },
    fridge: { max: 4 * DAY, label: "3-4 days" },
    freezer: { max: MONTH, label: "1 month" },
    tips: "Fold the spout shut and stand the pack upright. Never pour leftover milk back into the pack.",
    signs: ["Sour smell", "Lumps in the pour", "Bitter aftertaste"],
  },
  {
    id: "curd-home",
    name: "Curd / dahi (homemade)",
    category: "dairy",
    indian: true,
    pantry: { max: 8, label: "6-8 hours, then it turns sour" },
    fridge: { max: 7 * DAY, label: "5-7 days, sourer each day" },
    freezer: { max: 0, label: "Not recommended, it splits" },
    tips: "Refrigerate as soon as it sets or it keeps fermenting. Always use a dry spoon; a wet one seeds mould.",
    signs: ["Pink, black or fuzzy patches on top", "Sharp, yeasty or alcoholic smell", "Watery layer with a bitter taste", "Slimy strings when spooned"],
  },
  {
    id: "curd-cup",
    name: "Curd (sealed store cup)",
    category: "dairy",
    indian: true,
    pantry: { max: 4, label: "2-4 hours" },
    fridge: { max: 7 * DAY, label: "Follow the pack date, 5-7 days once opened" },
    freezer: { max: 0, label: "Not recommended" },
    tips: "A little clear whey on top is normal, just stir it in. Once opened, treat the pack date as void.",
    signs: ["Puffed or domed lid", "Mould spots", "Fizzy or yeasty smell"],
  },
  {
    id: "paneer-loose",
    name: "Paneer (fresh, loose)",
    category: "dairy",
    indian: true,
    pantry: { max: 4, label: "2-4 hours only" },
    fridge: { max: 3 * DAY, label: "2-3 days submerged in water" },
    freezer: { max: MONTH, label: "1 month, texture gets rubbery" },
    tips: "Keep it in a box of cold water and change the water every day. Dropping cubes in hot salted water before cooking revives softness.",
    signs: ["Sour or ammonia-like smell", "Slimy or sticky surface", "Yellow or pink discolouration", "Crumbles into a grainy mush"],
  },
  {
    id: "paneer-packed",
    name: "Paneer (vacuum packed, unopened)",
    category: "dairy",
    indian: true,
    pantry: { max: 4, label: "2-4 hours" },
    fridge: { max: 15 * DAY, label: "Up to the pack date, often 10-15 days" },
    freezer: { max: 3 * MONTH, label: "About 3 months" },
    tips: "Once you cut the pack, it is the same as loose paneer: 2-3 days in water.",
    signs: ["Bloated pack", "Cloudy liquid inside", "Sour smell on opening"],
  },
  {
    id: "cheese-hard",
    name: "Cheese (hard block, cheddar / gouda)",
    category: "dairy",
    pantry: { max: 4, label: "2-4 hours" },
    fridge: { max: 4 * WEEK, label: "3-4 weeks after opening" },
    freezer: { max: 6 * MONTH, label: "6 months, becomes crumbly" },
    tips: "Wrap in butter paper, then loosely in foil so it can breathe. On hard cheese you may cut 2.5 cm around a mould spot and use the rest.",
    signs: ["Fuzzy blue, green or black mould", "Ammonia smell", "Slimy rind", "Rock hard and cracked all through"],
  },
  {
    id: "cheese-slices",
    name: "Cheese slices / processed cubes",
    category: "dairy",
    pantry: { max: 4, label: "2-4 hours" },
    fridge: { max: 3 * WEEK, label: "About 3 weeks after opening" },
    freezer: { max: 2 * MONTH, label: "2 months" },
    tips: "Keep the slices in their sleeve inside a box, not in the fridge door where the temperature swings.",
    signs: ["Mould anywhere (discard the whole pack for soft cheese)", "Slimy film", "Sour smell"],
  },
  {
    id: "butter",
    name: "Butter (salted)",
    category: "dairy",
    pantry: { max: DAY, label: "1 day in a covered dish, cool weather only" },
    fridge: { max: 3 * MONTH, label: "1-3 months" },
    freezer: { max: YEAR, label: "Up to 1 year" },
    tips: "Salted butter keeps longer than unsalted. Keep it wrapped, fat absorbs fridge smells fast.",
    signs: ["Rancid, crayon-like smell", "Darker yellow, dried edges", "Mould specks"],
  },
  {
    id: "ghee",
    name: "Ghee",
    category: "dairy",
    indian: true,
    pantry: { max: YEAR, label: "Up to 1 year in a dry, airtight jar" },
    fridge: { max: YEAR, label: "Over a year, but it sets hard" },
    freezer: { max: 0, label: "Not needed" },
    tips: "Water is ghee's enemy. One wet spoon can spoil the whole jar, so always use a dry one and keep it away from the stove.",
    signs: ["Sour or paint-like rancid smell", "White or green mould on top", "Turns cloudy and grainy at room temperature"],
  },
  {
    id: "cream",
    name: "Fresh cream / malai (opened)",
    category: "dairy",
    indian: true,
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: 7 * DAY, label: "5-7 days" },
    freezer: { max: MONTH, label: "1 month, cooking use only" },
    tips: "Collected malai should go straight into a fridge box, not sit on the counter between meals.",
    signs: ["Sour smell", "Yellow tinge", "Lumps that will not whisk out", "Bitter taste"],
  },
  {
    id: "khoya",
    name: "Khoya / mawa",
    category: "dairy",
    indian: true,
    pantry: { max: 4, label: "2-4 hours" },
    fridge: { max: 5 * DAY, label: "4-5 days" },
    freezer: { max: 2 * MONTH, label: "2 months" },
    tips: "Festival-season khoya is the most adulterated item in the market. Buy from a shop with turnover and refrigerate it the moment you get home.",
    signs: ["Sour smell", "Grainy, sandy feel between fingers", "Bitter or chalky taste", "Grey or pink patches"],
  },
  {
    id: "buttermilk",
    name: "Buttermilk / chaas",
    category: "dairy",
    indian: true,
    pantry: { max: 4, label: "2-4 hours" },
    fridge: { max: 7 * DAY, label: "Up to 7 days, gets sharper" },
    freezer: { max: 0, label: "Not recommended, it splits" },
    tips: "Salted, spiced chaas sours faster than plain. Make what you will drink the same day.",
    signs: ["Fizzy or bubbling", "Yeasty smell", "Separated with a bitter top layer"],
  },
  {
    id: "condensed-milk",
    name: "Condensed milk (opened tin)",
    category: "dairy",
    pantry: { max: 0, label: "Refrigerate once opened" },
    fridge: { max: 2 * WEEK, label: "Up to 2 weeks in a glass jar" },
    freezer: { max: 3 * MONTH, label: "3 months, will not freeze solid" },
    tips: "Never store it in the opened tin, the metal taints it. Move it to a clean glass or steel container.",
    signs: ["Darkened to deep brown", "Thickened to a paste", "Mould at the surface", "Sour smell"],
  },
  {
    id: "milk-powder",
    name: "Milk powder (opened)",
    category: "dairy",
    pantry: { max: 3 * MONTH, label: "About 3 months in an airtight jar" },
    fridge: { max: 6 * MONTH, label: "6 months, seal it well against moisture" },
    freezer: { max: 0, label: "Not recommended, condensation ruins it" },
    tips: "Humidity is the killer. Keep the sachet clipped or decant into a jar with a tight lid and a dry scoop.",
    signs: ["Hard lumps that will not break", "Yellow-brown colour", "Stale, cardboard smell"],
  },

  {
    id: "eggs-raw",
    name: "Eggs (raw, in shell)",
    category: "eggs",
    pantry: { max: WEEK, label: "About 1 week in a cool spot" },
    fridge: { max: 5 * WEEK, label: "3-5 weeks" },
    freezer: { max: 0, label: "Never freeze in the shell" },
    tips: "Do not wash eggs before storing, that strips the protective bloom. Float test: a fresh egg sinks flat, a stale one stands up, a spoiled one floats.",
    signs: ["Floats in a glass of water", "Sulphur smell on cracking", "Pink, green or black white", "Runny white that spreads flat"],
  },
  {
    id: "eggs-boiled",
    name: "Eggs (hard boiled, in shell)",
    category: "eggs",
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: WEEK, label: "1 week, keep the shell on" },
    freezer: { max: 0, label: "Not recommended, the white turns rubbery" },
    tips: "Boiling removes the protective bloom, so boiled eggs actually keep worse than raw ones. Peel only when you eat.",
    signs: ["Sulphur or rotten smell", "Slimy white", "Greenish grey slime under the shell"],
  },
  {
    id: "eggs-beaten",
    name: "Eggs (raw, out of shell / beaten)",
    category: "eggs",
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: 2 * DAY, label: "2 days in a sealed box" },
    freezer: { max: YEAR, label: "Up to 1 year, beaten with a pinch of salt" },
    tips: "Cover the surface directly so it does not form a skin, and label the box with the date.",
    signs: ["Off or sulphur smell", "Pink or iridescent sheen", "Slimy strings"],
  },
  {
    id: "egg-white",
    name: "Egg whites (separated)",
    category: "eggs",
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: 4 * DAY, label: "2-4 days" },
    freezer: { max: YEAR, label: "Up to 1 year, freeze in an ice tray" },
    tips: "Whites freeze beautifully and whip up almost as well after thawing overnight in the fridge.",
    signs: ["Cloudy pink tinge", "Off smell", "Slimy or stringy"],
  },
  {
    id: "egg-cooked",
    name: "Egg curry / bhurji (cooked)",
    category: "eggs",
    indian: true,
    pantry: { max: 2, label: "2 hours, 1 hour above 32 C" },
    fridge: { max: 3 * DAY, label: "3 days" },
    freezer: { max: MONTH, label: "1 month, texture suffers" },
    tips: "Cool it uncovered for 20 minutes, then refrigerate in a shallow box so the centre chills fast.",
    signs: ["Sour smell", "Slimy gravy", "Fizzing when stirred"],
  },

  {
    id: "chicken-raw",
    name: "Chicken (raw, whole or curry cut)",
    category: "meat",
    pantry: { max: 2, label: "2 hours, 1 hour in summer" },
    fridge: { max: 2 * DAY, label: "1-2 days" },
    freezer: { max: 9 * MONTH, label: "9-12 months" },
    tips: "Store on the bottom shelf in a sealed box so drips cannot land on anything else. Freeze in meal-size portions, never refreeze thawed chicken.",
    signs: ["Sour or ammonia smell", "Slimy, sticky film", "Grey or greenish tinge", "Meat stays dented when pressed"],
  },
  {
    id: "chicken-mince",
    name: "Chicken keema / mince (raw)",
    category: "meat",
    indian: true,
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: DAY, label: "1 day only" },
    freezer: { max: 4 * MONTH, label: "3-4 months" },
    tips: "Mince spoils faster than whole cuts because grinding spreads surface bacteria all through it. Cook or freeze the same day.",
    signs: ["Grey-brown all the way through", "Sour smell", "Sticky, tacky feel"],
  },
  {
    id: "mutton-raw",
    name: "Mutton / goat (raw chops, curry cut)",
    category: "meat",
    indian: true,
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: 5 * DAY, label: "3-5 days" },
    freezer: { max: 9 * MONTH, label: "6-9 months" },
    tips: "Pat it dry and store in a box, not the shop's polythene. A vinegar or curd marinade buys a day but is not a substitute for cold.",
    signs: ["Sour, sweetish rotten smell", "Slimy surface", "Grey-brown or green patches", "Fat turns yellow and sticky"],
  },
  {
    id: "mutton-keema",
    name: "Mutton keema (raw)",
    category: "meat",
    indian: true,
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: 2 * DAY, label: "1-2 days" },
    freezer: { max: 4 * MONTH, label: "3-4 months" },
    tips: "Flatten it in a zip bag before freezing, it thaws in minutes and you can snap off what you need.",
    signs: ["Sour smell", "Grey throughout", "Slimy and tacky"],
  },
  {
    id: "fish-fresh",
    name: "Fish (fresh, whole or fillet)",
    category: "meat",
    indian: true,
    pantry: { max: 1, label: "1 hour, it is the fastest spoiler in the kitchen" },
    fridge: { max: 2 * DAY, label: "1-2 days, on ice if possible" },
    freezer: { max: 6 * MONTH, label: "3-6 months, lean fish keeps longest" },
    tips: "Clean it the day you buy it and store on a bed of ice in a strainer set over a bowl so meltwater drains away.",
    signs: ["Strong fishy or ammonia smell", "Cloudy, sunken eyes", "Grey-brown gills instead of bright red", "Flesh does not spring back when pressed"],
  },
  {
    id: "prawns-raw",
    name: "Prawns (raw)",
    category: "meat",
    pantry: { max: 1, label: "1 hour" },
    fridge: { max: 2 * DAY, label: "1-2 days" },
    freezer: { max: 6 * MONTH, label: "3-6 months" },
    tips: "Buy them frozen if you cannot cook them the same day. Devein before freezing, it is miserable to do half-thawed.",
    signs: ["Ammonia smell (never cook these)", "Black spots spreading on the shell", "Mushy, falling-apart flesh", "Slimy feel"],
  },
  {
    id: "curry-nonveg",
    name: "Chicken / mutton curry (cooked)",
    category: "meat",
    indian: true,
    pantry: { max: 2, label: "2 hours, 1 hour above 32 C" },
    fridge: { max: 4 * DAY, label: "3-4 days" },
    freezer: { max: 3 * MONTH, label: "2-3 months" },
    tips: "Reheat only the portion you will eat, and take it to a rolling boil rather than a warm-through.",
    signs: ["Sour or fermented smell", "Bubbles or froth without heat", "Slimy gravy", "Mould on the surface"],
  },
  {
    id: "chicken-fried",
    name: "Fried / tandoori chicken (cooked)",
    category: "meat",
    indian: true,
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: 4 * DAY, label: "3-4 days" },
    freezer: { max: 4 * MONTH, label: "About 4 months" },
    tips: "Refrigerate uncovered for the first 30 minutes so steam escapes, then cover. Reheat in an oven or air fryer to bring the crust back.",
    signs: ["Sour smell under the masala", "Slimy skin", "Grey meat"],
  },
  {
    id: "sausages",
    name: "Sausages / salami (opened pack)",
    category: "meat",
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: WEEK, label: "Up to 7 days" },
    freezer: { max: 2 * MONTH, label: "1-2 months" },
    tips: "Cured does not mean safe at room temperature once the vacuum seal is broken.",
    signs: ["Slimy coating", "Sour or sharp smell", "Grey-green edges", "Sticky casing"],
  },
  {
    id: "bacon",
    name: "Bacon (opened)",
    category: "meat",
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: WEEK, label: "7 days" },
    freezer: { max: MONTH, label: "1 month, the salt speeds up rancidity" },
    tips: "Roll the rashers in butter paper before freezing so you can peel off one at a time.",
    signs: ["Slimy surface", "Sour or rancid smell", "Fat turns yellow-brown"],
  },

  {
    id: "rice-cooked",
    name: "Cooked rice",
    category: "cooked",
    indian: true,
    pantry: { max: 2, label: "2 hours - Bacillus cereus risk" },
    fridge: { max: 4 * DAY, label: "3-4 days" },
    freezer: { max: MONTH, label: "1 month" },
    tips: "The most under-rated food poisoning risk in an Indian kitchen. Bacillus cereus spores survive cooking and multiply in rice left out overnight, and reheating does not destroy the toxin they make. Spread it out to cool and refrigerate within an hour.",
    signs: ["Slimy or sticky clumps", "Sour or musty smell", "Dry, hard grains with a stale taste", "Any rice left out overnight, no matter how it looks"],
  },
  {
    id: "dal-cooked",
    name: "Cooked dal (tadka or plain)",
    category: "cooked",
    indian: true,
    pantry: { max: 2, label: "2 hours, 1 hour in peak summer" },
    fridge: { max: 4 * DAY, label: "3-4 days" },
    freezer: { max: 2 * MONTH, label: "2 months" },
    tips: "Cool it in a wide vessel rather than the deep pot it cooked in, the centre of a full patila stays warm for hours. Boil it hard when you reheat.",
    signs: ["Sour, fermented smell", "Bubbles or froth on top when cold", "Slimy, ropey texture", "Thin white film on the surface"],
  },
  {
    id: "sabzi-dry",
    name: "Dry sabzi (aloo gobi, bhindi)",
    category: "cooked",
    indian: true,
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: 3 * DAY, label: "2-3 days" },
    freezer: { max: MONTH, label: "1 month, texture goes soft" },
    tips: "Potato-based sabzi sours faster than others. Use a shallow box so it chills through quickly.",
    signs: ["Sour smell", "Slimy coating on the vegetables", "Fizzing when stirred", "Mould specks"],
  },
  {
    id: "sabzi-gravy",
    name: "Gravy sabzi (paneer, chole, kofta)",
    category: "cooked",
    indian: true,
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: 4 * DAY, label: "3-4 days" },
    freezer: { max: 2 * MONTH, label: "2 months, cream-based ones may split" },
    tips: "Dairy-heavy gravies spoil faster than tomato-onion ones. Reheat to a full boil, not just warm.",
    signs: ["Sour or yeasty smell", "Froth without heat", "Gravy turns stringy", "Off, sharp taste"],
  },
  {
    id: "chapati-cooked",
    name: "Chapati / roti (cooked)",
    category: "cooked",
    indian: true,
    pantry: { max: 12, label: "8-12 hours wrapped in a cloth" },
    fridge: { max: 2 * DAY, label: "2 days, they go leathery" },
    freezer: { max: MONTH, label: "1 month with butter paper between them" },
    tips: "To revive a fridge-cold roti, sprinkle a few drops of water and heat on a tawa, not the microwave alone.",
    signs: ["Green or black mould spots", "Musty smell", "Hard, cracking edges", "Sticky surface in humid weather"],
  },
  {
    id: "rajma-chole",
    name: "Rajma / chole (cooked)",
    category: "cooked",
    indian: true,
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: 4 * DAY, label: "3-4 days" },
    freezer: { max: 2 * MONTH, label: "2 months" },
    tips: "Beans ferment fast. If you soaked them overnight in warm weather, refrigerate the soaking bowl too.",
    signs: ["Sour, fermented smell", "Foam on the surface", "Slimy gravy", "Bitter taste"],
  },
  {
    id: "idli-batter",
    name: "Idli / dosa batter (fermented)",
    category: "cooked",
    indian: true,
    pantry: { max: 12, label: "8-12 hours after it rises, then it over-ferments" },
    fridge: { max: 5 * DAY, label: "4-5 days, sourer each day" },
    freezer: { max: MONTH, label: "1 month, thaw in the fridge overnight" },
    tips: "Refrigerate the moment it has doubled. Leave headroom in the container, it will keep rising. Sour batter still makes good dosa even when it is past idli stage.",
    signs: ["Sharp alcoholic or vinegar smell", "Grey or pink tinge", "Watery layer that will not stir back in", "Batter that has collapsed and will not rise again"],
  },
  {
    id: "chapati-dough",
    name: "Chapati dough (kneaded atta)",
    category: "cooked",
    indian: true,
    pantry: { max: 4, label: "3-4 hours before it darkens and sours" },
    fridge: { max: 2 * DAY, label: "Up to 2 days, best within 24 hours" },
    freezer: { max: 2 * WEEK, label: "2 weeks in a greased ball, wrapped tight" },
    tips: "Smear a little oil over the ball and press cling film onto the surface. The grey-brown colour on day two is oxidation, not mould, but the rotis will taste flat and turn stiff.",
    signs: ["Sour, yeasty or alcoholic smell", "Sticky, slack dough that will not roll", "Grey-black patches (mould, not oxidation)", "Bitter taste in the cooked roti"],
  },
  {
    id: "coconut-chutney",
    name: "Coconut chutney",
    category: "cooked",
    indian: true,
    pantry: { max: 4, label: "3-4 hours, the fastest-spoiling chutney" },
    fridge: { max: DAY, label: "1 day, 2 at the very most" },
    freezer: { max: MONTH, label: "1 month frozen in ice-tray cubes" },
    tips: "Fresh coconut ferments quickly, and the curd or water in the grind speeds it up. Make it for the meal, not for the week. The tempering on top helps a little; a dry spoon helps more.",
    signs: ["Sour or fizzy smell", "Bitter, sharp taste", "Watery separation with a grey tinge", "Any bubbling at all"],
  },
  {
    id: "sambar",
    name: "Sambar",
    category: "cooked",
    indian: true,
    pantry: { max: 4, label: "3-4 hours, tamarind buys a little time" },
    fridge: { max: 4 * DAY, label: "3-4 days" },
    freezer: { max: 2 * MONTH, label: "2 months" },
    tips: "The tamarind acidity slows spoilage slightly, but the dal and vegetables still ferment. Boil hard when reheating.",
    signs: ["Sour beyond the tamarind sourness", "Froth on top", "Slimy vegetables", "Yeasty smell"],
  },
  {
    id: "biryani",
    name: "Biryani / pulao",
    category: "cooked",
    indian: true,
    pantry: { max: 2, label: "2 hours - it is rice, treat it as rice" },
    fridge: { max: 4 * DAY, label: "3-4 days" },
    freezer: { max: MONTH, label: "1 month" },
    tips: "A big handi holds heat for hours. Break it into shallow boxes so the middle actually cools.",
    signs: ["Sour smell", "Sticky, slimy grains", "Off taste in the first bite"],
  },
  {
    id: "pasta-cooked",
    name: "Cooked pasta / noodles",
    category: "cooked",
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: 5 * DAY, label: "3-5 days plain, 3 days with sauce" },
    freezer: { max: MONTH, label: "1 month" },
    tips: "Toss plain pasta in a little oil before refrigerating so it does not weld into a block.",
    signs: ["Slimy strands", "Sour smell", "Grey or dull colour", "Mould spots"],
  },
  {
    id: "soup-stock",
    name: "Soup / stock",
    category: "cooked",
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: 4 * DAY, label: "3-4 days" },
    freezer: { max: 6 * MONTH, label: "4-6 months" },
    tips: "Freeze stock in an ice tray, then bag the cubes. A deep pot of hot stock must be cooled in a wide tray, not left on the stove.",
    signs: ["Cloudy where it was clear", "Sour smell", "Bubbles rising when cold", "Slimy film"],
  },
  {
    id: "restaurant-leftovers",
    name: "Restaurant leftovers / pizza",
    category: "cooked",
    pantry: { max: 2, label: "2 hours from when it left the kitchen" },
    fridge: { max: 4 * DAY, label: "3-4 days" },
    freezer: { max: MONTH, label: "1 month" },
    tips: "The 2-hour clock starts when the food was cooked, not when you got home. Delivery time counts.",
    signs: ["Sour or off smell", "Slimy toppings", "Mould", "Anything that sat in the car or on the counter overnight"],
  },
  {
    id: "kheer-halwa",
    name: "Kheer / halwa (milk sweets)",
    category: "cooked",
    indian: true,
    pantry: { max: 4, label: "3-4 hours, milk and sugar ferment fast" },
    fridge: { max: 3 * DAY, label: "2-3 days" },
    freezer: { max: MONTH, label: "1 month, texture changes" },
    tips: "Ghee-heavy halwa keeps a day longer than milk-heavy kheer. Refrigerate both as soon as they stop steaming.",
    signs: ["Sour smell", "Watery separation", "Fizzy or bubbling", "Slimy strings when spooned"],
  },
  {
    id: "mithai",
    name: "Mithai (barfi, peda, khoya sweets)",
    category: "cooked",
    indian: true,
    pantry: { max: DAY, label: "1 day in winter, refrigerate otherwise" },
    fridge: { max: WEEK, label: "5-7 days" },
    freezer: { max: 2 * MONTH, label: "2 months" },
    tips: "Dry sweets like besan ladoo last far longer than khoya ones. Festival mithai bought in bulk should go into the fridge the same evening.",
    signs: ["Sour or fermented smell", "Sticky, weeping surface", "Mould spots", "Grainy, sandy bite"],
  },
  {
    id: "cut-fruit",
    name: "Cut fruit / fruit salad",
    category: "cooked",
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: 3 * DAY, label: "2-3 days, quality drops fast" },
    freezer: { max: 0, label: "Not recommended, it turns to mush" },
    tips: "A squeeze of lemon slows browning on apple and banana. Melon is the highest-risk cut fruit, keep it cold.",
    signs: ["Slimy or weeping surface", "Fermented, boozy smell", "Dull, browned flesh", "Pooled cloudy juice"],
  },

  {
    id: "potato",
    name: "Potato",
    category: "produce",
    indian: true,
    pantry: { max: 2 * MONTH, label: "1-2 months in a dark, airy basket" },
    fridge: { max: 0, label: "Not recommended, starch turns sweet" },
    freezer: { max: 0, label: "Not raw" },
    tips: "Never store potatoes next to onions, they make each other sprout. Keep them dark: light is what turns the skin green.",
    signs: ["Green patches under the skin (solanine, cut them away generously)", "Long sprouts and a shrivelled body", "Soft, weeping spots", "Musty, earthy-sour smell"],
  },
  {
    id: "onion",
    name: "Onion",
    category: "produce",
    indian: true,
    pantry: { max: 2 * MONTH, label: "1-2 months, dry and ventilated" },
    fridge: { max: 2 * WEEK, label: "2 weeks once cut, in a sealed box" },
    freezer: { max: 3 * MONTH, label: "3 months chopped, for cooking" },
    tips: "Store in a basket or net, never a closed polythene bag. A cut onion belongs in a box in the fridge, not on the counter.",
    signs: ["Soft, squishy layers", "Black powdery mould at the neck", "Sharp rotten smell", "Slimy outer layers"],
  },
  {
    id: "tomato",
    name: "Tomato",
    category: "produce",
    indian: true,
    pantry: { max: 5 * DAY, label: "3-5 days, they ripen better outside" },
    fridge: { max: 2 * WEEK, label: "Up to 2 weeks once ripe, flavour dulls" },
    freezer: { max: 2 * MONTH, label: "2 months whole, for gravies" },
    tips: "Counter first for flavour, fridge only once fully ripe. Store stem-side down so they bruise less.",
    signs: ["Wrinkled, weeping skin", "White or grey fuzz", "Sour smell", "Leaking juice"],
  },
  {
    id: "garlic",
    name: "Garlic (whole bulb)",
    category: "produce",
    indian: true,
    pantry: { max: 4 * MONTH, label: "3-5 months whole and unpeeled" },
    fridge: { max: WEEK, label: "1 week peeled, in a sealed box" },
    freezer: { max: YEAR, label: "Up to 1 year peeled or as paste" },
    tips: "Whole bulbs want air and darkness. Peeled cloves want the fridge. Never store garlic in oil at room temperature, that is a botulism risk.",
    signs: ["Green shoots through the centre (safe but bitter)", "Soft, hollow cloves", "Brown or grey spots", "Powdery mould on the skin"],
  },
  {
    id: "ginger",
    name: "Ginger",
    category: "produce",
    indian: true,
    pantry: { max: WEEK, label: "About 1 week" },
    fridge: { max: 4 * WEEK, label: "3-4 weeks in a paper bag" },
    freezer: { max: 6 * MONTH, label: "6 months, grate it straight from frozen" },
    tips: "Freezing is the trick nobody uses: a frozen knob grates finer than a fresh one and never goes mouldy.",
    signs: ["Soft, wrinkled skin", "Grey-blue mould", "Dried, fibrous flesh", "Musty smell"],
  },
  {
    id: "leafy-greens",
    name: "Leafy greens (palak, methi)",
    category: "produce",
    indian: true,
    pantry: { max: 12, label: "Half a day, they wilt fast" },
    fridge: { max: 5 * DAY, label: "3-5 days in a perforated bag" },
    freezer: { max: 3 * MONTH, label: "3 months blanched and squeezed dry" },
    tips: "Do not wash before storing. Wrap unwashed leaves in a dry cloth or paper towel inside a loose bag; moisture is what turns them to slime.",
    signs: ["Slimy, blackened leaves", "Sour smell", "Yellowing all over", "Pooled water at the bottom of the bag"],
  },
  {
    id: "coriander-mint",
    name: "Coriander / mint (fresh)",
    category: "produce",
    indian: true,
    pantry: { max: 12, label: "Half a day" },
    fridge: { max: WEEK, label: "About 1 week wrapped in a dry paper towel" },
    freezer: { max: 2 * MONTH, label: "2 months chopped in an ice tray with water" },
    tips: "Pick out the yellow leaves before storing, one rotting leaf takes the bunch down with it.",
    signs: ["Blackened, slimy stems", "Yellow leaves throughout", "Musty smell", "Mush at the base of the bunch"],
  },
  {
    id: "carrot",
    name: "Carrot",
    category: "produce",
    pantry: { max: 3 * DAY, label: "2-3 days" },
    fridge: { max: 4 * WEEK, label: "3-4 weeks in the crisper" },
    freezer: { max: 3 * MONTH, label: "3 months blanched" },
    tips: "Snap off the green tops before storing, they pull moisture out of the root and leave it limp.",
    signs: ["Rubbery and bendy", "White blush that will not rinse off", "Black soft spots", "Slimy film"],
  },
  {
    id: "cauliflower-cabbage",
    name: "Cauliflower / cabbage",
    category: "produce",
    indian: true,
    pantry: { max: 2 * DAY, label: "2 days" },
    fridge: { max: 2 * WEEK, label: "1-2 weeks whole" },
    freezer: { max: 3 * MONTH, label: "3 months blanched florets" },
    tips: "Keep them whole until you cook. A cut cauliflower browns and dries within a day.",
    signs: ["Brown or black spots on the florets", "Strong sulphur smell", "Slimy leaves", "Limp, yellowing head"],
  },
  {
    id: "capsicum",
    name: "Capsicum / bell pepper",
    category: "produce",
    pantry: { max: 3 * DAY, label: "2-3 days" },
    fridge: { max: 2 * WEEK, label: "1-2 weeks" },
    freezer: { max: 3 * MONTH, label: "3 months sliced, no blanching needed" },
    tips: "Store dry and whole. Once cut, use within two days, the seeds and pith go slimy first.",
    signs: ["Wrinkled, soft skin", "Watery dark spots", "White mould inside around the seeds", "Sour smell"],
  },
  {
    id: "brinjal-bhindi",
    name: "Brinjal / bhindi",
    category: "produce",
    indian: true,
    pantry: { max: 2 * DAY, label: "2 days" },
    fridge: { max: 5 * DAY, label: "3-5 days" },
    freezer: { max: 2 * MONTH, label: "2 months, bhindi turns slimy on thawing" },
    tips: "Both hate cold and damp. Keep them dry, unwashed, and out of a sealed bag.",
    signs: ["Brown, sunken patches", "Spongy or wrinkled skin", "Slimy surface on bhindi", "Bitter taste in brinjal"],
  },
  {
    id: "banana",
    name: "Banana",
    category: "produce",
    pantry: { max: 5 * DAY, label: "3-5 days depending on ripeness" },
    fridge: { max: WEEK, label: "1 week, the skin blackens but the flesh is fine" },
    freezer: { max: 3 * MONTH, label: "3 months peeled, for smoothies" },
    tips: "Keep them away from other fruit, the ethylene they give off ripens everything nearby. Wrapping the crown slows ripening.",
    signs: ["Leaking liquid", "Fruit flies hovering", "Grey mushy flesh", "Fermented, boozy smell"],
  },
  {
    id: "apple",
    name: "Apple",
    category: "produce",
    pantry: { max: WEEK, label: "About 1 week" },
    fridge: { max: 2 * MONTH, label: "1-2 months in the crisper" },
    freezer: { max: 2 * MONTH, label: "2 months sliced with lemon" },
    tips: "One bad apple really does spoil the basket. Store them away from bananas and leafy greens.",
    signs: ["Soft, brown bruises", "Wrinkled skin", "Mealy, dry flesh", "Mould at the stem or core"],
  },
  {
    id: "mango",
    name: "Mango",
    category: "produce",
    indian: true,
    pantry: { max: 5 * DAY, label: "3-5 days to ripen at room temperature" },
    fridge: { max: 5 * DAY, label: "5 days once fully ripe" },
    freezer: { max: 6 * MONTH, label: "6 months as pulp or chunks" },
    tips: "Never refrigerate an unripe mango, the cold stops it ripening for good. Fridge only after it gives to a gentle press.",
    signs: ["Black sunken spots that spread", "Fermented, alcoholic smell", "Sap-oozing skin", "Stringy, sour flesh"],
  },
  {
    id: "citrus",
    name: "Citrus (orange, mosambi, lemon)",
    category: "produce",
    indian: true,
    pantry: { max: WEEK, label: "About 1 week" },
    fridge: { max: 4 * WEEK, label: "3-4 weeks" },
    freezer: { max: 4 * MONTH, label: "4 months as juice or zest" },
    tips: "Lemons last three times longer in the fridge than in the counter bowl. Freeze the zest before you juice.",
    signs: ["Green or white powdery mould", "Soft, collapsing spots", "Dry, light-feeling fruit", "Fermented smell"],
  },
  {
    id: "grapes-berries",
    name: "Grapes / berries",
    category: "produce",
    pantry: { max: DAY, label: "1 day" },
    fridge: { max: 5 * DAY, label: "3-5 days, wash only before eating" },
    freezer: { max: YEAR, label: "Up to 1 year, freeze on a tray first" },
    tips: "Washing before storing is the single fastest way to ruin berries. Keep them dry in a vented box.",
    signs: ["Grey fuzz on any berry", "Weeping, sticky juice at the bottom", "Wrinkled, dull skin", "Fermented smell"],
  },
  {
    id: "cucumber",
    name: "Cucumber",
    category: "produce",
    pantry: { max: 2 * DAY, label: "2 days" },
    fridge: { max: WEEK, label: "About 1 week" },
    freezer: { max: 0, label: "Not recommended, it collapses" },
    tips: "Cucumbers suffer below 7 C, so the crisper drawer beats the coldest shelf.",
    signs: ["Slimy, dark ends", "Wrinkled, hollow feel", "Watery soft spots", "Bitter taste"],
  },
  {
    id: "mushroom",
    name: "Mushroom",
    category: "produce",
    pantry: { max: 12, label: "Half a day" },
    fridge: { max: 5 * DAY, label: "3-5 days in a paper bag" },
    freezer: { max: 3 * MONTH, label: "3 months sauteed first" },
    tips: "Paper bag, never plastic. Do not wash until the moment you cook, mushrooms soak up water like a sponge.",
    signs: ["Slimy, wet caps", "Dark brown or black patches", "Fishy or sour smell", "Wrinkled, shrivelled caps"],
  },
  {
    id: "coconut-fresh",
    name: "Fresh coconut (grated)",
    category: "produce",
    indian: true,
    pantry: { max: 4, label: "3-4 hours" },
    fridge: { max: 2 * DAY, label: "1-2 days" },
    freezer: { max: MONTH, label: "1 month, freezes very well" },
    tips: "Grate the whole coconut at once and freeze it in flat bags. It shaves off straight from the freezer.",
    signs: ["Sour or fermented smell", "Grey or yellow tinge", "Slimy clumps", "Rancid, soapy taste"],
  },

  {
    id: "bread-packaged",
    name: "Bread (packaged white or brown)",
    category: "bread",
    pantry: { max: 5 * DAY, label: "3-5 days, only 2-3 in the monsoon" },
    fridge: { max: 2 * WEEK, label: "Up to 2 weeks but it goes stale faster" },
    freezer: { max: MONTH, label: "1 month, toast straight from frozen" },
    tips: "The fridge delays mould but speeds up staling. For anything beyond three days, the freezer is the right answer.",
    signs: ["Any green, white or black fuzz (throw the whole loaf, not just the slice)", "Musty smell", "Hard, dry crumb", "Sticky, wet slices"],
  },
  {
    id: "pav-buns",
    name: "Pav / buns",
    category: "bread",
    indian: true,
    pantry: { max: 3 * DAY, label: "2-3 days" },
    fridge: { max: WEEK, label: "1 week" },
    freezer: { max: MONTH, label: "1 month" },
    tips: "Soft breads mould faster than crusty ones because they hold more moisture. Bag them loosely.",
    signs: ["Mould spots", "Sour smell", "Hard, cracking surface"],
  },
  {
    id: "cake-plain",
    name: "Cake (plain sponge, no cream)",
    category: "bread",
    pantry: { max: 2 * DAY, label: "2 days, well wrapped" },
    fridge: { max: WEEK, label: "About 1 week" },
    freezer: { max: 2 * MONTH, label: "2 months" },
    tips: "Wrap cut edges with cling film so the crumb does not dry out. Bring to room temperature before serving.",
    signs: ["Mould spots", "Dry, crumbling texture", "Sour or alcoholic smell"],
  },
  {
    id: "cake-cream",
    name: "Cake (fresh cream or frosting)",
    category: "bread",
    pantry: { max: 2, label: "2 hours - it is a dairy product" },
    fridge: { max: 3 * DAY, label: "2-3 days" },
    freezer: { max: MONTH, label: "1 month, cream may weep on thawing" },
    tips: "A birthday cake sitting out through a party is on the 2-hour clock like any other dairy dish.",
    signs: ["Sour cream smell", "Weeping, separated frosting", "Mould", "Dull, greying cream"],
  },
  {
    id: "biscuits",
    name: "Biscuits / cookies (opened)",
    category: "bread",
    indian: true,
    pantry: { max: MONTH, label: "About 1 month in an airtight jar" },
    fridge: { max: 0, label: "Not recommended, they go soft" },
    freezer: { max: 0, label: "Not needed" },
    tips: "Humidity, not time, is what kills a biscuit. Decant the packet into a jar with a tight lid the day you open it.",
    signs: ["Soft, bendy instead of snapping", "Rancid or stale-oil smell", "Musty taste", "Any visible mould in the jar"],
  },
  {
    id: "rusk",
    name: "Rusk / khari / toast",
    category: "bread",
    indian: true,
    pantry: { max: 2 * MONTH, label: "About 2 months airtight" },
    fridge: { max: 0, label: "Not recommended" },
    freezer: { max: 0, label: "Not needed" },
    tips: "These are baked dry on purpose. Keep them dry and they last; let humidity in and they are done in a day.",
    signs: ["Bends instead of snapping", "Stale oil smell", "Musty taste"],
  },
  {
    id: "paratha-cooked",
    name: "Stuffed paratha (cooked)",
    category: "bread",
    indian: true,
    pantry: { max: 8, label: "6-8 hours, less if the filling has paneer" },
    fridge: { max: 2 * DAY, label: "2 days" },
    freezer: { max: MONTH, label: "1 month with butter paper between them" },
    tips: "Aloo filling keeps a day longer than paneer filling. Cool them on a rack so the base does not steam and go soggy.",
    signs: ["Sour smell from the filling", "Sticky, slimy surface", "Mould spots", "Off taste in the first bite"],
  },

  {
    id: "atta",
    name: "Atta (whole wheat flour)",
    category: "pantry",
    indian: true,
    pantry: { max: 3 * MONTH, label: "2-3 months before weevils and rancidity" },
    fridge: { max: 6 * MONTH, label: "6 months in a sealed jar" },
    freezer: { max: YEAR, label: "Up to 1 year" },
    tips: "Whole wheat has the germ oil in it, so it goes rancid long before maida does. A few bay leaves in the drum keep weevils down; a week in the freezer kills any eggs already there.",
    signs: ["Weevils or webbing in the drum", "Stale, bitter, oily smell", "Damp lumps", "Off taste in the rotis"],
  },
  {
    id: "maida",
    name: "Maida / refined flour",
    category: "pantry",
    indian: true,
    pantry: { max: 8 * MONTH, label: "6-8 months airtight" },
    fridge: { max: YEAR, label: "Up to 1 year" },
    freezer: { max: YEAR, label: "Over a year" },
    tips: "The germ is milled out, so maida keeps far longer than atta. Moisture is still the enemy.",
    signs: ["Insects", "Musty smell", "Hard lumps", "Grey tinge"],
  },
  {
    id: "rice-raw",
    name: "Rice (raw, white)",
    category: "pantry",
    indian: true,
    pantry: { max: 2 * YEAR, label: "1-2 years airtight, practically indefinite" },
    fridge: { max: 0, label: "Not needed" },
    freezer: { max: 0, label: "Only to kill weevil eggs" },
    tips: "Basmati genuinely improves with a year of ageing. Store in a steel or food-grade plastic drum, not the jute sack it came in.",
    signs: ["Weevils or moth webbing", "Musty or damp smell", "Yellow or grey grains", "Powdery dust at the bottom"],
  },
  {
    id: "rice-brown",
    name: "Brown rice",
    category: "pantry",
    pantry: { max: 6 * MONTH, label: "About 6 months, the bran oil goes rancid" },
    fridge: { max: YEAR, label: "Up to 1 year" },
    freezer: { max: 2 * YEAR, label: "Over a year" },
    tips: "Unlike white rice, brown rice has a real expiry. Buy small packs and keep them in the fridge if you use it slowly.",
    signs: ["Oily, crayon-like rancid smell", "Bitter taste", "Insects", "Dull, greasy-feeling grains"],
  },
  {
    id: "dal-dry",
    name: "Dal / pulses (dry)",
    category: "pantry",
    indian: true,
    pantry: { max: YEAR, label: "Up to 1 year, best within 6 months" },
    fridge: { max: 0, label: "Not needed" },
    freezer: { max: 0, label: "Freeze new stock 1 week to kill weevil eggs" },
    tips: "Old dal is safe but takes far longer to cook and never softens properly. Label the jar with the month you bought it.",
    signs: ["Weevils or small holes in the grains", "Musty smell", "Dal that will not soften after long soaking", "Powdery residue"],
  },
  {
    id: "sugar",
    name: "Sugar",
    category: "pantry",
    pantry: { max: 2 * YEAR, label: "Practically indefinite while it stays dry" },
    fridge: { max: 0, label: "Not needed" },
    freezer: { max: 0, label: "Not needed" },
    tips: "Sugar does not spoil, it only clumps or attracts ants. A tight jar solves both.",
    signs: ["Ants", "Rock-hard clumps from moisture", "Any off smell it has picked up"],
  },
  {
    id: "salt",
    name: "Salt",
    category: "pantry",
    pantry: { max: 2 * YEAR, label: "Indefinite" },
    fridge: { max: 0, label: "Not needed" },
    freezer: { max: 0, label: "Not needed" },
    tips: "Iodised salt loses iodine potency over about a year in a warm, light kitchen. Keep it in an opaque, closed container.",
    signs: ["Hard caking (still safe, just break it up)", "Damp clumping in humid weather"],
  },
  {
    id: "oil-cooking",
    name: "Cooking oil (opened)",
    category: "pantry",
    indian: true,
    pantry: { max: 6 * MONTH, label: "About 6 months from opening" },
    fridge: { max: YEAR, label: "Up to 1 year, may go cloudy" },
    freezer: { max: 0, label: "Not needed" },
    tips: "Heat, light and air turn oil rancid. Keep the bottle away from the stove and never top up a new tin into an old one. Re-used frying oil lasts only 2-3 fries.",
    signs: ["Crayon or paint-like rancid smell", "Bitter, scratchy aftertaste", "Sticky residue on the bottle", "Cloudiness at room temperature"],
  },
  {
    id: "spices-whole",
    name: "Whole spices (jeera, elaichi, dalchini)",
    category: "pantry",
    indian: true,
    pantry: { max: 2 * YEAR, label: "2-3 years, aroma fades well before that" },
    fridge: { max: 0, label: "Not needed" },
    freezer: { max: 2 * YEAR, label: "Long term storage only" },
    tips: "Whole spices hold their oils for years, which is why buying whole and grinding small batches beats buying powder.",
    signs: ["No aroma when crushed", "Insects in the jar", "Faded, dusty colour", "Musty smell"],
  },
  {
    id: "spices-ground",
    name: "Ground masala (haldi, mirch, dhania)",
    category: "pantry",
    indian: true,
    pantry: { max: YEAR, label: "About 1 year, but aroma fades after 6 months" },
    fridge: { max: 0, label: "Not needed" },
    freezer: { max: 0, label: "Not recommended, condensation clumps it" },
    tips: "Never shake masala straight from the jar over a steaming pan, the steam gets in and seeds mould. Spoon it into your hand first.",
    signs: ["Weak or no smell on opening", "Clumped, damp powder", "Faded colour", "Musty or mouldy smell"],
  },
  {
    id: "tea-leaves",
    name: "Tea leaves",
    category: "pantry",
    indian: true,
    pantry: { max: YEAR, label: "About 1 year airtight" },
    fridge: { max: 0, label: "Not recommended, it absorbs fridge smells" },
    freezer: { max: 0, label: "Not needed" },
    tips: "Tea is a sponge for odours. Keep it in an opaque, airtight tin far from masalas and onions.",
    signs: ["Flat, papery smell", "Weak colour when brewed", "Damp clumps", "Musty taste"],
  },
  {
    id: "nuts",
    name: "Nuts (almonds, cashew, walnut)",
    category: "pantry",
    indian: true,
    pantry: { max: 3 * MONTH, label: "About 3 months, walnuts less" },
    fridge: { max: YEAR, label: "Up to 1 year" },
    freezer: { max: 2 * YEAR, label: "About 2 years" },
    tips: "Nuts are mostly oil, so they go rancid rather than mouldy. The fridge or freezer roughly quadruples their life, and they taste no different.",
    signs: ["Bitter, paint-like taste", "Rancid oily smell", "Shrivelled, dark kernels", "Any mould (discard, aflatoxin risk)"],
  },
  {
    id: "poha-suji",
    name: "Poha / suji / rava",
    category: "pantry",
    indian: true,
    pantry: { max: 4 * MONTH, label: "3-4 months, suji attracts insects fast" },
    fridge: { max: 6 * MONTH, label: "6 months in a sealed jar" },
    freezer: { max: YEAR, label: "Up to 1 year" },
    tips: "Suji is the first thing in an Indian pantry to get weevils. Dry roast a fresh pack lightly and cool it before jarring, it keeps far longer.",
    signs: ["Weevils or webbing", "Musty, sour smell", "Bitter taste", "Damp clumps"],
  },
  {
    id: "honey",
    name: "Honey",
    category: "pantry",
    pantry: { max: 2 * YEAR, label: "Practically never spoils" },
    fridge: { max: 0, label: "Not recommended, it crystallises hard" },
    freezer: { max: 0, label: "Not needed" },
    tips: "Crystallising is natural, not spoilage. Stand the jar in warm water to bring it back. Keep water out with a dry spoon.",
    signs: ["Fermented or boozy smell", "Bubbles or froth", "Sour taste"],
  },

  {
    id: "ketchup",
    name: "Tomato ketchup (opened)",
    category: "condiments",
    pantry: { max: MONTH, label: "About 1 month" },
    fridge: { max: 6 * MONTH, label: "About 6 months" },
    freezer: { max: 0, label: "Not needed" },
    tips: "The vinegar and sugar do most of the preserving, but in Indian summers the fridge is worth it.",
    signs: ["Dark brown at the top", "Watery separation that will not shake back", "Fizzing when opened", "Mould around the cap"],
  },
  {
    id: "mayonnaise",
    name: "Mayonnaise (opened)",
    category: "condiments",
    risk: "high",
    pantry: { max: 0, label: "Refrigerate always once opened" },
    fridge: { max: 2 * MONTH, label: "About 2 months" },
    freezer: { max: 0, label: "Not recommended, it splits" },
    tips: "Eggless mayo is safer at room temperature than egg mayo, but neither should live on the counter. Never double-dip the spoon.",
    signs: ["Yellowed or darkened surface", "Oil separating on top", "Sour or sharp smell", "Any mould at the rim"],
  },
  {
    id: "achar",
    name: "Achar / Indian pickle (oil-based)",
    category: "condiments",
    indian: true,
    pantry: { max: YEAR, label: "A year or more if the oil covers it" },
    fridge: { max: YEAR, label: "Over a year, oil will solidify" },
    freezer: { max: 0, label: "Not needed" },
    tips: "The oil layer is the preservative, so keep the pieces submerged and top up with oil if they poke out. One wet or dirty spoon is what ruins a jar that would otherwise last years.",
    signs: ["White or green fuzz on top", "Fermented, yeasty smell (beyond normal tang)", "Slimy pieces", "Pieces sitting above the oil line and turning dark"],
  },
  {
    id: "jam",
    name: "Jam (opened)",
    category: "condiments",
    pantry: { max: WEEK, label: "1 week, refrigeration is safer" },
    fridge: { max: 6 * MONTH, label: "About 6 months" },
    freezer: { max: 0, label: "Not needed" },
    tips: "Butter crumbs from a used knife are what seed mould in a jam jar. Always use a clean, dry spoon.",
    signs: ["Any mould on the surface (discard the jar)", "Fermented or boozy smell", "Bubbles", "Darkened, weeping surface"],
  },
  {
    id: "peanut-butter",
    name: "Peanut butter (opened)",
    category: "condiments",
    pantry: { max: 3 * MONTH, label: "About 3 months" },
    fridge: { max: 6 * MONTH, label: "About 6 months, goes stiff" },
    freezer: { max: 0, label: "Not needed" },
    tips: "Natural peanut butter separates and needs the fridge after opening. Stabilised commercial ones are fine in the cupboard.",
    signs: ["Rancid, bitter taste", "Hard, dry texture throughout", "Dark colour", "Mould (discard, aflatoxin risk)"],
  },
  {
    id: "soy-vinegar",
    name: "Soy sauce / vinegar (opened)",
    category: "condiments",
    pantry: { max: 6 * MONTH, label: "About 6 months, flavour dulls" },
    fridge: { max: 2 * YEAR, label: "2-3 years" },
    freezer: { max: 0, label: "Not needed" },
    tips: "Both are so salty or acidic that spoilage is rare. The fridge is about keeping the flavour, not safety.",
    signs: ["Cloudy sediment in vinegar (mother, harmless)", "Flat or musty taste", "Mould at the neck", "Fizzing"],
  },
  {
    id: "green-chutney",
    name: "Green chutney (coriander-mint)",
    category: "condiments",
    indian: true,
    risk: "high",
    pantry: { max: 4, label: "3-4 hours" },
    fridge: { max: 3 * DAY, label: "2-3 days" },
    freezer: { max: MONTH, label: "1 month in ice-tray cubes" },
    tips: "A squeeze of lemon and a spoon of oil on top keep the colour and buy an extra day. Freeze in cubes and thaw one at a time.",
    signs: ["Blackened, dull colour", "Sour or fermented smell", "Bubbles or froth", "Watery separation with a bitter taste"],
  },
  {
    id: "ginger-garlic-paste",
    name: "Ginger-garlic paste (homemade)",
    category: "condiments",
    indian: true,
    risk: "high",
    pantry: { max: 4, label: "3-4 hours" },
    fridge: { max: 2 * WEEK, label: "About 2 weeks with salt and a film of oil" },
    freezer: { max: 3 * MONTH, label: "3 months, freeze in tablespoon dollops" },
    tips: "Grind with a little salt and oil, never water, and top the jar with a film of oil. Never store garlic paste in oil at room temperature, that is a genuine botulism risk.",
    signs: ["Green or blue-grey colour (harmless but bitter)", "Fermented smell", "Bubbling in the jar", "Mould on top"],
  },
  {
    id: "raita",
    name: "Raita (curd-based)",
    category: "condiments",
    indian: true,
    risk: "high",
    pantry: { max: 2, label: "2 hours - curd plus raw vegetables" },
    fridge: { max: 2 * DAY, label: "1-2 days, gets watery" },
    freezer: { max: 0, label: "Not recommended" },
    tips: "Cucumber and onion leach water and speed up souring. Mix raita just before the meal rather than in the morning.",
    signs: ["Sharply sour smell", "Watery separation", "Fizzy or bubbling", "Slimy vegetables in it"],
  },
  {
    id: "cream-cheese",
    name: "Cream cheese / cheese spread (opened)",
    category: "condiments",
    risk: "high",
    pantry: { max: 2, label: "2 hours" },
    fridge: { max: 2 * WEEK, label: "About 2 weeks" },
    freezer: { max: 0, label: "Not recommended, it goes grainy" },
    tips: "Soft cheese cannot be rescued by cutting mould away, the threads run right through. Discard the tub.",
    signs: ["Any mould at all", "Watery pooling on top", "Sour, sharp smell", "Yellow crust at the edges"],
  },
];

export const CATEGORY_BY_ID = CATEGORIES.reduce((map, category) => {
  map[category.id] = category;
  return map;
}, {});

export const riskOf = (food) => food.risk || CATEGORY_BY_ID[food.category]?.risk || "quality";

export const STORAGE_ZONES = [
  {
    id: "door",
    zone: "Fridge door",
    temp: "Warmest, 7-10 C",
    keep: "Water bottles, ketchup, jam, pickles, soy sauce",
    avoid: "Milk and eggs - the swing every time you open the door is exactly what they hate",
  },
  {
    id: "upper",
    zone: "Upper shelves",
    temp: "Steady, 4-5 C",
    keep: "Leftovers in shallow boxes, cooked dal and sabzi, chaas, ready-to-eat food",
    avoid: "Anything raw that can drip",
  },
  {
    id: "middle",
    zone: "Middle shelves",
    temp: "Steady, 4 C",
    keep: "Milk, curd, paneer, cheese, eggs (in a box, not the door rack)",
    avoid: "Bread - it stales here faster than on the counter",
  },
  {
    id: "bottom",
    zone: "Bottom shelf",
    temp: "Coldest, 1-3 C",
    keep: "Raw chicken, mutton and fish, always in a sealed box",
    avoid: "Salad and cut fruit - never store them below raw meat",
  },
  {
    id: "crisper",
    zone: "Crisper drawer",
    temp: "4-6 C, higher humidity",
    keep: "Leafy greens, carrots, capsicum, cucumber, herbs wrapped in cloth",
    avoid: "Potato, onion, garlic, unripe mango and banana",
  },
  {
    id: "freezer",
    zone: "Freezer",
    temp: "-18 C, frozen solid",
    keep: "Meat portioned flat, chapati with butter paper between, chutney cubes, peas",
    avoid: "Curd, raita, cucumber, boiled egg whites, cream sauces",
  },
];
