"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Settings, AlertCircle, BarChart3, HelpCircle } from "lucide-react";
import useAuraGenerator from "../hooks/useAuraGenerator";
import UploadPanel from "../components/UploadPanel";
import AuraGenerator from "../components/AuraGenerator";
import AuraViewer from "../components/AuraViewer";
import AuraCard from "../components/AuraCard";
import HistoryPanel from "../components/HistoryPanel";
import ShareDialog from "../components/ShareDialog";
import SettingsModal from "../components/SettingsModal";
import { getAuraStats } from "../utils/helpers";

const FAQS = [
  { q: "What is an aura color?", a: "An aura is believed to be an energy field that surrounds living beings. This tool generates a fictional aura color based on your photo for entertainment purposes." },
  { q: "How is my aura color determined?", a: "The color is algorithmically generated by analyzing pixel data from your uploaded photo. It's purely for fun and not based on any scientific measurements." },
  { q: "Can I save my aura readings?", a: "Yes! Your aura readings are automatically saved to your browser's local storage. You can also favorite them for quick access." },
  { q: "Is my photo stored anywhere?", a: "No. All processing happens entirely in your browser. Your photo is never uploaded to any server." },
];

export default function AuraColorGeneratorMain() {
  const {
    imagePreview,
    aura,
    loading,
    history,
    favorites,
    settings,
    toast,
    handleImageUpload,
    clearImage,
    generateAura,
    generateRandomAura,
    toggleFavorite,
    isFavorited,
    deleteHistoryItem,
    clearHistory,
    updateSettings,
    showToast,
    setAura,
  } = useAuraGenerator();

  const [shareOpen, setShareOpen] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [showFaq, setShowFaq] = useState(false);
  const [showDashboard, setShowDashboard] = useState(false);

  const stats = getAuraStats(history);

  const handleSelectHistory = (item) => {
    setAura(item);
  };

  return (
    <div className="min-h-screen bg-(--background) px-4 py-8 text-(--foreground) sm:px-6">
      <div className="mx-auto max-w-7xl space-y-8">
        <motion.section
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="rounded-2xl border border-(--border) bg-(--card) p-6 text-center shadow-lg sm:p-8"
        >
          <div className="mb-3 inline-flex items-center gap-2 rounded-full bg-(--primary-soft) px-4 py-1.5 text-xs font-bold uppercase text-(--primary)">
            <Sparkles className="h-4 w-4" />
            Aura Color Generator
          </div>
          <h1 className="text-3xl font-bold text-(--foreground) sm:text-4xl">Discover Your Aura</h1>
          <p className="mt-2 text-(--muted-foreground)">Upload a photo and uncover the color of your energy</p>
          <p className="mt-4 max-w-2xl mx-auto text-xs text-(--muted-foreground) italic">
            This tool is for entertainment purposes only. Aura colors are algorithmically generated and not based on actual energy readings or scientific measurements.
          </p>
        </motion.section>
      </div>

      <div className="grid gap-6 lg:grid-cols-[1fr_400px]">
        <div className="space-y-6">
          <UploadPanel imagePreview={imagePreview} onUpload={handleImageUpload} onClear={clearImage} />
          {imagePreview && !aura && (
            <AuraGenerator onGenerate={generateAura} onRandom={generateRandomAura} loading={loading} />
          )}
          {loading && (
            <div className="flex flex-col items-center gap-3 rounded-2xl border border-(--border) bg-(--card) p-8">
              <div className="relative h-20 w-20">
                <div className="absolute inset-0 animate-spin rounded-full border-4 border-(--border) border-t-(--primary)" />
                <div className="absolute inset-3 rounded-full bg-(--card)" />
                <div className="absolute inset-0 flex items-center justify-center">
                  <Sparkles className="h-6 w-6 text-(--primary)" />
                </div>
              </div>
              <p className="text-sm font-semibold text-(--muted-foreground)">Analyzing your energy field...</p>
              <div className="flex gap-1">
                {[0, 1, 2].map((i) => (
                  <motion.div
                    key={i}
                    className="h-2 w-2 rounded-full bg-(--primary)"
                    animate={{ opacity: [0.3, 1, 0.3] }}
                    transition={{ duration: 1, repeat: Infinity, delay: i * 0.3 }}
                  />
                ))}
              </div>
            </div>
          )}
        </div>

        <div className="space-y-6">
          {aura && (
            <>
              <AuraViewer aura={aura} imagePreview={imagePreview} />
              <AuraCard
                aura={aura}
                imagePreview={imagePreview}
                onSave={() => toggleFavorite(aura)}
                isFavorited={isFavorited(aura)}
                onShare={() => setShareOpen(true)}
              />
            </>
          )}
        </div>
      </div>

      {history.length > 0 && (
        <section>
          <HistoryPanel
            history={history}
            favorites={favorites}
            onSelect={handleSelectHistory}
            onDelete={deleteHistoryItem}
            onToggleFavorite={toggleFavorite}
          />
        </section>
      )}

      <section className="rounded-2xl border border-(--border) bg-(--card) p-6">
        <button
          onClick={() => setShowFaq(!showFaq)}
          className="flex w-full items-center justify-between"
        >
          <div className="flex items-center gap-2">
            <HelpCircle className="h-5 w-5 text-(--primary)" />
            <h3 className="text-lg font-semibold text-(--foreground)">FAQ</h3>
          </div>
          <span className="text-(--muted-foreground)">{showFaq ? "−" : "+"}</span>
        </button>
        {showFaq && (
          <div className="mt-4 space-y-4">
            {FAQS.map((faq, i) => (
              <div key={i} className="rounded-xl bg-(--background) p-4">
                <p className="text-sm font-semibold text-(--foreground)">{faq.q}</p>
                <p className="mt-1 text-sm text-(--muted-foreground)">{faq.a}</p>
              </div>
            ))}
          </div>
        )}
      </section>

      {history.length > 0 && (
        <section className="rounded-2xl border border-(--border) bg-(--card) p-6">
          <button
            onClick={() => setShowDashboard(!showDashboard)}
            className="flex w-full items-center justify-between"
          >
            <div className="flex items-center gap-2">
              <BarChart3 className="h-5 w-5 text-(--primary)" />
              <h3 className="text-lg font-semibold text-(--foreground)">Dashboard</h3>
            </div>
            <span className="text-(--muted-foreground)">{showDashboard ? "−" : "+"}</span>
          </button>
          {showDashboard && (
            <div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-4">
              <div className="rounded-xl border border-(--border) bg-(--background) p-4 text-center">
                <p className="text-2xl font-bold text-(--primary)">{stats.total}</p>
                <p className="text-xs text-(--muted-foreground)">Total Readings</p>
              </div>
              <div className="rounded-xl border border-(--border) bg-(--background) p-4 text-center">
                <p className="text-2xl font-bold text-(--primary)">{favorites.length}</p>
                <p className="text-xs text-(--muted-foreground)">Favorites</p>
              </div>
              <div className="rounded-xl border border-(--border) bg-(--background) p-4 text-center">
                <p className="text-2xl font-bold text-(--primary)">{Object.keys(stats.colorCounts).length}</p>
                <p className="text-xs text-(--muted-foreground)">Unique Colors</p>
              </div>
              <div className="rounded-xl border border-(--border) bg-(--background) p-4 text-center">
                <p className="text-2xl font-bold text-(--primary) capitalize">{stats.favoriteColor || "N/A"}</p>
                <p className="text-xs text-(--muted-foreground)">Favorite Color</p>
              </div>
            </div>
          )}
        </section>
      )}

      <ShareDialog open={shareOpen} onClose={() => setShareOpen(false)} aura={aura} />
      <SettingsModal
        open={settingsOpen}
        onClose={() => setSettingsOpen(false)}
        settings={settings}
        onUpdate={updateSettings}
        onClearHistory={clearHistory}
      />

      <AnimatePresence>
        {toast && (
          <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 50 }}
            className={`fixed bottom-8 left-1/2 -translate-x-1/2 rounded-2xl px-6 py-3 text-sm font-semibold shadow-2xl z-50 ${
              toast.type === "error" ? "bg-(--danger) text-white" : "bg-(--primary) text-white"
            }`}
          >
            {toast.message}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
