import { useCallback, useEffect, useMemo, useState } from "react";
import { formatJson, generateGoStructs } from "../utils/goStructGenerator";

const STORAGE_KEY = "json_to_go_struct_workspace";

const defaultWorkspace = {
  jsonInput: "",
  rootName: "AutoGenerated",
  packageName: "models",
  nullableBehavior: "pointer",
  history: [],
};

function getReadiness(jsonInput, rootName, result, error) {
  const checks = [
    { label: "JSON provided", done: Boolean(jsonInput.trim()) },
    { label: "Syntax valid", done: Boolean(result && !error) },
    { label: "Root struct named", done: Boolean(rootName.trim()) },
    { label: "Go code generated", done: Boolean(result?.code) },
    { label: "Nested data detected", done: (result?.stats?.nestingDepth || 0) > 2 },
    { label: "JSON tags ready", done: Boolean(result?.code?.includes("`json:")) },
  ];

  return {
    checks,
    score: Math.round((checks.filter((item) => item.done).length / checks.length) * 100),
  };
}

export function useJsonToGoStruct() {
  const [workspace, setWorkspace] = useState(() => {
    if (typeof window === "undefined") return defaultWorkspace;
    try {
      const stored = JSON.parse(localStorage.getItem(STORAGE_KEY) || "null");
      return stored ? { ...defaultWorkspace, ...stored } : defaultWorkspace;
    } catch {
      localStorage.removeItem(STORAGE_KEY);
      return defaultWorkspace;
    }
  });
  const [copied, setCopied] = useState(false);
  const [notice, setNotice] = useState("");

  useEffect(() => {
    if (typeof window === "undefined") return;
    localStorage.setItem(STORAGE_KEY, JSON.stringify(workspace));
  }, [workspace]);

  const generatedState = useMemo(() => {
    if (!workspace.jsonInput.trim()) {
      return {
        result: null,
        error: "Paste or upload JSON to generate Go structs.",
      };
    }

    try {
      return {
        result: generateGoStructs(workspace.jsonInput, workspace),
        error: "",
      };
    } catch (err) {
      return {
        result: null,
        error: err.message || "Invalid JSON input.",
      };
    }
  }, [workspace]);

  const { result, error } = generatedState;

  const updateField = useCallback((field, value) => {
    setWorkspace((current) => ({ ...current, [field]: value }));
    setNotice("");
  }, []);

  const loadFile = useCallback((file) => {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      setWorkspace((current) => ({ ...current, jsonInput: String(reader.result || "") }));
      setNotice(`Loaded ${file.name}`);
    };
    reader.onerror = () => setNotice("Could not read that file.");
    reader.readAsText(file);
  }, []);

  const transformJson = useCallback((mode) => {
    try {
      updateField("jsonInput", formatJson(workspace.jsonInput, mode));
      setNotice(mode === "minify" ? "JSON minified." : "JSON beautified.");
    } catch (err) {
      setNotice(err.message || "Fix JSON before formatting.");
    }
  }, [updateField, workspace.jsonInput]);

  const clearJson = useCallback(() => {
    setWorkspace((current) => ({ ...current, jsonInput: "" }));
    setNotice("Workspace cleared.");
  }, []);

  const resetWorkspace = useCallback(() => {
    setWorkspace(defaultWorkspace);
    setNotice("Settings reset.");
  }, []);

  const saveHistory = useCallback(() => {
    if (!result?.code) return;
    setWorkspace((current) => {
      const item = {
        id: Date.now(),
        rootName: current.rootName,
        packageName: current.packageName,
        jsonInput: current.jsonInput,
        code: result.code,
        createdAt: new Date().toLocaleString(),
      };
      return { ...current, history: [item, ...current.history.filter((entry) => entry.code !== item.code)].slice(0, 5) };
    });
    setNotice("Saved to history.");
  }, [result]);

  const restoreHistory = useCallback((item) => {
    setWorkspace((current) => ({
      ...current,
      jsonInput: item.jsonInput,
      rootName: item.rootName,
      packageName: item.packageName,
    }));
  }, []);

  const readiness = useMemo(
    () => getReadiness(workspace.jsonInput, workspace.rootName, result, error),
    [workspace.jsonInput, workspace.rootName, result, error]
  );

  return {
    workspace,
    updateField,
    result,
    error,
    copied,
    setCopied,
    notice,
    setNotice,
    readiness,
    loadFile,
    transformJson,
    clearJson,
    resetWorkspace,
    saveHistory,
    restoreHistory,
  };
}
