/**
 * AI Content Disclosure Statement Generator.
 *
 * One AI-assisted asset usually needs three different pieces of disclosure
 * text — a full statement for the page or description, a short label that fits
 * beside the asset, and a provenance credit line for metadata — plus an answer
 * to "which platform rule applies to this?". This module produces all four.
 *
 * The obligations modelled here:
 *  - Regulation (EU) 2024/1689 (the AI Act), Article 50(2): providers of AI
 *    systems that generate synthetic audio, image, video or text must mark the
 *    output in a machine-readable format and make it detectable as
 *    artificially generated or manipulated.
 *  - AI Act, Article 50(4), first paragraph: deployers of an AI system that
 *    generates or manipulates image, audio or video constituting a deep fake
 *    must disclose that the content has been artificially generated or
 *    manipulated.
 *  - AI Act, Article 50(4), second paragraph: deployers of AI-generated or
 *    AI-manipulated TEXT published to inform the public on matters of public
 *    interest must disclose it, unless the content underwent human review or
 *    editorial control and a natural or legal person holds editorial
 *    responsibility for its publication.
 *  - The AI Act entered into force on 1 August 2024; its general application
 *    date, which covers the Article 50 transparency obligations, is
 *    2 August 2026 (AI_ACT_TRANSPARENCY_DATE below).
 *  - FTC Act Section 5 and the FTC's endorsement guidance: a disclosure has to
 *    be clear and conspicuous — placed with the claim it qualifies, not buried
 *    in a policy page or behind a link.
 *  - Platform rules: YouTube requires creators to disclose realistic altered
 *    or synthetic content at upload; Meta applies "AI info" labelling; TikTok
 *    requires AI-generated content to be labelled and reads Content
 *    Credentials. C2PA Content Credentials is the provenance standard the
 *    metadata credit line is written for.
 *
 * The risk score is a HEURISTIC, not a legal test: it ranks the situations
 * that the rules above single out, so that the highest-exposure combinations
 * (a photorealistic depiction of a real person, in a public-interest context,
 * with no human review) sort to the top. It is not a compliance determination.
 */

/** General application date of the AI Act, covering the Article 50 duties. */
export const AI_ACT_TRANSPARENCY_DATE = "2 August 2026";

/** What is being disclosed. */
export const ASSET_TYPES = [
  { id: "article", label: "Article or written post", media: false, noun: "article" },
  { id: "image", label: "Image or illustration", media: true, noun: "image" },
  { id: "video", label: "Video", media: true, noun: "video" },
  { id: "audio", label: "Audio, voice-over or music", media: true, noun: "audio" },
];

/** How much of the asset the model produced. */
export const AI_ROLES = [
  {
    id: "assisted",
    label: "AI assisted a human (editing, clean-up, ideas)",
    weight: 0,
    phrase: "AI tools were used to assist a human creator; the finished work is substantially human-made",
    short: "AI-assisted",
  },
  {
    id: "partial",
    label: "Partly AI-generated, human reworked it",
    weight: 8,
    phrase: "parts of this work were generated with AI and then reworked by a human",
    short: "Partly AI-generated",
  },
  {
    id: "generated",
    label: "Fully AI-generated from a prompt",
    weight: 15,
    phrase: "this work was generated by an AI system from a human-written prompt",
    short: "AI-generated",
  },
  {
    id: "manipulated",
    label: "Real material altered with AI",
    weight: 15,
    phrase: "real source material was altered or manipulated using AI",
    short: "AI-altered",
  },
];

/**
 * Risk factors and their heuristic weights. The weights order the situations
 * the AI Act and FTC guidance single out; they are not a legal test.
 */
export const RISK_WEIGHTS = {
  /** Photorealism is what turns synthetic media into a deep-fake question. */
  photorealistic: 25,
  /** Depicting an identifiable real person is the core deep-fake trigger. */
  realPerson: 30,
  /** Public-interest text is the trigger in Article 50(4), second paragraph. */
  publicInterest: 25,
  /** No human review removes the editorial-responsibility exemption. */
  noHumanReview: 15,
  /** Advertising brings FTC clear-and-conspicuous expectations into play. */
  commercial: 10,
};

/** Where the asset will be published. */
export const CHANNELS = [
  {
    id: "own-site",
    label: "Own website or blog",
    obligation:
      "Place the statement adjacent to the content — byline area, caption or an 'About this content' note. FTC guidance treats a disclosure buried in a separate policy page as not clear and conspicuous.",
  },
  {
    id: "youtube",
    label: "YouTube",
    obligation:
      "Tick the altered or synthetic content disclosure in the upload flow. YouTube requires creators to disclose realistic altered or synthetic content, and applies a label in the description or on the player.",
  },
  {
    id: "meta",
    label: "Facebook or Instagram",
    obligation:
      "Expect Meta's 'AI info' label. Provenance signals such as C2PA Content Credentials in the file can trigger it automatically; where they are absent, mark the post as AI-generated yourself.",
  },
  {
    id: "tiktok",
    label: "TikTok",
    obligation:
      "Use TikTok's AI-generated content toggle. TikTok also reads Content Credentials and labels recognised AI content automatically.",
  },
  {
    id: "ads",
    label: "Paid advertising",
    obligation:
      "The disclosure has to sit with the claim it qualifies, in the creative itself where the AI element could mislead. Undisclosed AI use that misleads consumers is exposure under Section 5 of the FTC Act.",
  },
  {
    id: "email",
    label: "Newsletter or email",
    obligation:
      "Put the statement in the issue itself, near the assisted content, rather than only in a site-wide policy.",
  },
  {
    id: "print",
    label: "Print or PDF",
    obligation:
      "Add the credit line under the asset and repeat the full statement in the colophon or methodology section, since metadata does not survive print.",
  },
];

const MAX_FIELD = 120;

function clean(value) {
  return String(value ?? "").trim().replace(/\s+/g, " ");
}

/**
 * Score the disclosure exposure of an asset. Pure and bounded to 0-100.
 *
 * @param {object} input
 * @param {string} input.assetTypeId
 * @param {string} input.aiRoleId
 * @param {boolean} input.photorealistic
 * @param {boolean} input.realPerson
 * @param {boolean} input.publicInterest
 * @param {boolean} input.humanReviewed
 * @param {boolean} input.commercial
 * @returns {{score:number, band:string, drivers:string[]}|{error:string}}
 */
export function scoreDisclosureRisk({
  assetTypeId,
  aiRoleId,
  photorealistic = false,
  realPerson = false,
  publicInterest = false,
  humanReviewed = true,
  commercial = false,
}) {
  const asset = ASSET_TYPES.find((a) => a.id === assetTypeId);
  const role = AI_ROLES.find((r) => r.id === aiRoleId);
  if (!asset || !role) return { error: "Choose the asset type and how the AI was used." };

  let score = role.weight;
  const drivers = [];
  if (role.weight > 0) drivers.push(role.label);

  if (asset.media && photorealistic) {
    score += RISK_WEIGHTS.photorealistic;
    drivers.push("Photorealistic rather than obviously stylised");
  }
  if (realPerson) {
    score += RISK_WEIGHTS.realPerson;
    drivers.push("Depicts or imitates an identifiable real person");
  }
  if (publicInterest) {
    score += RISK_WEIGHTS.publicInterest;
    drivers.push("Concerns a matter of public interest");
  }
  if (!humanReviewed) {
    score += RISK_WEIGHTS.noHumanReview;
    drivers.push("No human review before publication");
  }
  if (commercial) {
    score += RISK_WEIGHTS.commercial;
    drivers.push("Used in advertising or a commercial claim");
  }

  const capped = Math.max(0, Math.min(100, score));
  const band =
    capped >= 80
      ? "Critical"
      : capped >= 55
        ? "High"
        : capped >= 25
          ? "Moderate"
          : "Low";

  return { score: capped, band, drivers };
}

/**
 * Work out which published obligations are engaged.
 *
 * @param {object} input Same shape as scoreDisclosureRisk plus channelIds.
 * @returns {{title:string, detail:string}[]}
 */
export function obligationsFor({
  assetTypeId,
  aiRoleId,
  photorealistic = false,
  realPerson = false,
  publicInterest = false,
  humanReviewed = true,
  channelIds = [],
}) {
  const asset = ASSET_TYPES.find((a) => a.id === assetTypeId);
  const role = AI_ROLES.find((r) => r.id === aiRoleId);
  if (!asset || !role) return [];
  const generated = role.id === "generated" || role.id === "partial" || role.id === "manipulated";
  const list = [];

  if (generated) {
    list.push({
      title: "AI Act Article 50(2) — machine-readable marking",
      detail: `Synthetic audio, image, video or text has to be marked in a machine-readable format and be detectable as artificially generated or manipulated. The duty falls on the provider of the AI system, but publishers should preserve the marking rather than strip it. Applies from ${AI_ACT_TRANSPARENCY_DATE}.`,
    });
  }
  if (asset.media && generated && (photorealistic || realPerson)) {
    list.push({
      title: "AI Act Article 50(4) — deep fake disclosure",
      detail: `A deployer of an AI system generating or manipulating image, audio or video that constitutes a deep fake must disclose that the content has been artificially generated or manipulated. Applies from ${AI_ACT_TRANSPARENCY_DATE}.`,
    });
  }
  if (!asset.media && generated && publicInterest) {
    list.push({
      title: "AI Act Article 50(4) — public-interest text",
      detail: humanReviewed
        ? `AI-generated text published to inform the public on matters of public interest must be disclosed, unless it underwent human review or editorial control and a person or organisation holds editorial responsibility. You have recorded human review, so name who holds that responsibility in the statement. Applies from ${AI_ACT_TRANSPARENCY_DATE}.`
        : `AI-generated text published to inform the public on matters of public interest must be disclosed. The exemption requires human review or editorial control with someone holding editorial responsibility, and you have recorded none. Applies from ${AI_ACT_TRANSPARENCY_DATE}.`,
    });
  }
  if (realPerson) {
    list.push({
      title: "Rights of the person depicted",
      detail:
        "Beyond the AI rules, using an identifiable person's likeness or voice raises personality, publicity and data-protection questions. Get written consent, and do not rely on a disclosure label to cure its absence.",
    });
  }

  CHANNELS.filter((channel) => channelIds.includes(channel.id)).forEach((channel) => {
    list.push({ title: channel.label, detail: channel.obligation });
  });

  return list;
}

/**
 * Build the three disclosure texts plus the obligations and the risk score.
 *
 * @param {object} input
 * @param {string} input.assetTypeId
 * @param {string} input.aiRoleId
 * @param {boolean} input.photorealistic
 * @param {boolean} input.realPerson
 * @param {boolean} input.publicInterest
 * @param {boolean} input.humanReviewed
 * @param {boolean} input.commercial
 * @param {string[]} input.channelIds
 * @param {string} [input.toolNames]   Comma-separated model or tool names.
 * @param {string} [input.publisher]   Organisation taking responsibility.
 * @param {string} [input.reviewer]    Who reviewed the asset.
 * @returns {{longStatement:string, shortLabel:string, metadataCredit:string,
 *            obligations:object[], score:number, band:string, drivers:string[]}
 *          | {error:string}}
 */
export function buildDisclosureSet({
  assetTypeId,
  aiRoleId,
  photorealistic = false,
  realPerson = false,
  publicInterest = false,
  humanReviewed = true,
  commercial = false,
  channelIds = [],
  toolNames = "",
  publisher = "",
  reviewer = "",
}) {
  const asset = ASSET_TYPES.find((a) => a.id === assetTypeId);
  const role = AI_ROLES.find((r) => r.id === aiRoleId);
  if (!asset || !role) return { error: "Choose the asset type and how the AI was used." };
  if (!Array.isArray(channelIds)) return { error: "Channels must be given as a list." };

  const org = clean(publisher);
  const who = clean(reviewer);
  if (org.length > MAX_FIELD || who.length > MAX_FIELD) {
    return { error: `Keep the publisher and reviewer fields under ${MAX_FIELD} characters.` };
  }
  const tools = String(toolNames)
    .split(",")
    .map((t) => t.trim())
    .filter(Boolean);
  if (tools.some((t) => t.length > MAX_FIELD)) {
    return { error: `Keep each tool name under ${MAX_FIELD} characters.` };
  }

  // A photorealistic depiction of a real person with no human review is the
  // one combination that should not be published behind a label at all.
  if (asset.media && photorealistic && realPerson && !humanReviewed && role.id !== "assisted") {
    return {
      error:
        "A photorealistic AI depiction of an identifiable real person, published with no human review, should not go out with a disclosure label alone. Add human review and documented consent from the person depicted first.",
    };
  }

  const risk = scoreDisclosureRisk({
    assetTypeId,
    aiRoleId,
    photorealistic,
    realPerson,
    publicInterest,
    humanReviewed,
    commercial,
  });
  if (risk.error) return { error: risk.error };

  const toolPhrase =
    tools.length === 0
      ? ""
      : tools.length === 1
        ? ` using ${tools[0]}`
        : ` using ${tools.slice(0, -1).join(", ")} and ${tools[tools.length - 1]}`;

  const sentences = [`AI disclosure: ${role.phrase}${toolPhrase}.`];

  if (asset.media && photorealistic) {
    sentences.push(
      `This ${asset.noun} is photorealistic and does not depict a real event as it occurred.`,
    );
  }
  if (realPerson) {
    sentences.push(
      "It depicts or imitates an identifiable real person, whose consent was obtained for this use.",
    );
  }
  if (humanReviewed) {
    const reviewerName = who || (org ? `the ${org} editorial team` : "a human editor");
    sentences.push(
      `The published version was reviewed and approved by ${reviewerName}, who holds editorial responsibility for it.`,
    );
  } else {
    sentences.push(`This ${asset.noun} has not undergone human editorial review.`);
  }
  if (org) {
    sentences.push(`${org} is accountable for this content.`);
  }

  const shortLabel = humanReviewed ? `${role.short} · human-reviewed` : role.short;

  const metadataCredit = [
    `${role.short} ${asset.noun}`,
    tools.length > 0 ? `Tool: ${tools.join(", ")}` : null,
    org ? `Publisher: ${org}` : null,
    humanReviewed ? "Human review: yes" : "Human review: no",
    "Provenance: attach C2PA Content Credentials where the tool supports them",
  ]
    .filter(Boolean)
    .join(" | ");

  return {
    longStatement: sentences.join(" "),
    shortLabel,
    metadataCredit,
    obligations: obligationsFor({
      assetTypeId,
      aiRoleId,
      photorealistic,
      realPerson,
      publicInterest,
      humanReviewed,
      channelIds,
    }),
    score: risk.score,
    band: risk.band,
    drivers: risk.drivers,
  };
}
