export const DEFAULT_SETTINGS = {
  hero: {
    heading: "Smarter Financial Decisions,\nPowered by AI",
    subheading: "SmartLucky combines cutting-edge AI with real-time data to help you find the best credit cards, loans, and financial products tailored to your unique profile.",
    primaryCta: "Find Your Match",
    secondaryCta: "See How It Works",
  },
  stats: [
    { value: "500K+", prefix: "", suffix: "+", label: "Matches Made", sublabel: "and counting every day" },
    { value: "98.7", prefix: "", suffix: "%", label: "Approval Rate", sublabel: "among qualified applicants" },
    { value: "4.8", prefix: "", suffix: "/5", label: "User Rating", sublabel: "from verified reviews" },
    { value: "15M+", prefix: "", suffix: "+", label: "Data Points", sublabel: "analyzed daily" },
  ],
  clientLogos: [
    { name: "Visa", src: "/images/logos/visa.svg", width: 80 },
    { name: "Mastercard", src: "/images/logos/mastercard.svg", width: 100 },
    { name: "Amex", src: "/images/logos/amex.svg", width: 100 },
    { name: "Chase", src: "/images/logos/chase.svg", width: 90 },
    { name: "Capital One", src: "/images/logos/capital-one.svg", width: 110 },
  ],
  testimonials: [
    {
      name: "Sarah Chen",
      role: "Freelance Designer",
      company: "Design Studio",
      quote: "SmartLucky found me a card with 2x the cashback I was getting before. The AI really understood my spending habits.",
      avatar: "https://i.pravatar.cc/80?img=1",
      metric: "$2,400",
      metricLabel: "earned back",
      location: "San Francisco, CA",
      rating: 5,
    },
  ],
  servicesGrid: [
    {
      icon: "ShieldCheck",
      title: "Smart Matching",
      description: "Our AI analyzes thousands of data points to find the perfect financial products for your unique profile.",
      badge: "AI Powered",
      badgeColor: "teal",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80",
    },
  ],
  industries: [
    {
      name: "Credit Cards",
      tagline: "Find Your Ideal Card",
      description: "Compare rewards, APR, and benefits across 200+ cards tailored to your credit profile.",
      stat: "200+",
      statLabel: "Cards Compared",
      tags: ["Rewards", "Balance Transfer", "Travel"],
      image: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&q=80",
    },
  ],
  portfolio: [
    {
      industry: "Personal Finance AI",
      metric: "4.2x",
      metricLabel: "ROI Improvement",
      timeframe: "12 months",
      person: "Marcus Johnson",
      role: "CFO, FinFlow Corp",
      image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80",
      badge: "Case Study",
      badgeVariant: "default",
      description: "Implemented SmartLucky's AI recommendation engine, resulting in a 4.2x improvement in customer acquisition ROI.",
    },
  ],
  faqs: [
    {
      question: "How does SmartLucky's AI matching work?",
      answer: "Our AI analyzes your financial profile, credit history, spending patterns, and goals to match you with the best products.",
      category: "General",
    },
  ],
  team: [
    {
      name: "Alex Thompson",
      role: "CEO & Co-Founder",
      avatar: "https://i.pravatar.cc/80?img=3",
      bio: "Former fintech executive with 15 years in consumer lending.",
    },
  ],
  footer: {
    about: "SmartLucky uses AI to match you with the best financial products. We analyze thousands of data points to save you money.",
    copyright: "© 2026 SmartLucky. All rights reserved.",
    columns: [
      {
        title: "Products",
        links: [
          { label: "Credit Cards", href: "/services" },
          { label: "Personal Loans", href: "/services" },
          { label: "Mortgages", href: "/services" },
        ],
      },
      {
        title: "Company",
        links: [
          { label: "About Us", href: "/about" },
          { label: "Careers", href: "/about" },
          { label: "Press", href: "/resources" },
        ],
      },
      {
        title: "Support",
        links: [
          { label: "Help Center", href: "/resources" },
          { label: "Contact Us", href: "/contact" },
          { label: "Privacy Policy", href: "/resources" },
        ],
      },
      {
        title: "Resources",
        links: [
          { label: "Blog", href: "/blog" },
          { label: "Guides", href: "/resources" },
          { label: "FAQ", href: "/resources" },
        ],
      },
    ],
    social: [
      { label: "Twitter", href: "#" },
      { label: "LinkedIn", href: "#" },
      { label: "Facebook", href: "#" },
    ],
  },
  nav: {
    services: [
      {
        category: "Personal",
        items: [
          { name: "Credit Cards", href: "/services" },
          { name: "Personal Loans", href: "/services" },
        ],
      },
    ],
    solutions: [
      { name: "For Individuals", href: "/solutions" },
      { name: "For Businesses", href: "/solutions" },
    ],
  },
  cta: {
    title: "Ready to Make Smarter Financial Decisions?",
    subtitle: "Join 500,000+ users who have found their perfect financial products with SmartLucky's AI.",
    primaryCta: "Get Started Free",
    secondaryCta: "Talk to an Expert",
  },
  newsletter: {
    title: "Stay Ahead in Personal Finance",
    subtitle: "Get weekly insights, tips, and exclusive offers curated by our AI.",
    buttonText: "Subscribe",
    socialProof: "Join 50,000+ subscribers",
  },
  whyChooseUs: {
    features: [
      {
        icon: "Zap",
        title: "AI Powered",
        description: "Proprietary models that predict trends before they happen.",
        badge: "Autonomous",
        stat: "94%",
        statLabel: "Prediction Accuracy",
        image: "https://images.pexels.com/photos/3861957/pexels-photo-3861957.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=260&w=400",
        badgeColor: "bg-blue-500/85",
      },
      {
        icon: "BarChart3",
        title: "Data Driven",
        description: "Every decision backed by billions of real-time data points.",
        badge: "Real-Time",
        stat: "2B+",
        statLabel: "Data Points Daily",
        image: "https://images.pexels.com/photos/7947849/pexels-photo-7947849.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=260&w=400",
        badgeColor: "bg-emerald-500/85",
      },
      {
        icon: "Shield",
        title: "Transparent Reporting",
        description: "Live dashboards with 100% visibility into every dollar spent.",
        badge: "Full Visibility",
        stat: "100%",
        statLabel: "Reporting Coverage",
        image: "https://images.pexels.com/photos/590041/pexels-photo-590041.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=260&w=400",
        badgeColor: "bg-violet-500/85",
      },
      {
        icon: "TrendingUp",
        title: "ROI Focused",
        description: "We don't just deliver clicks; we deliver bottom-line growth.",
        badge: "Results First",
        stat: "127%",
        statLabel: "Average ROI Lift",
        image: "https://images.pexels.com/photos/9052188/pexels-photo-9052188.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=260&w=400",
        badgeColor: "bg-orange-500/85",
      },
    ],
    comparisonData: [
      { feature: "Integration Speed", traditional: "3–6 Months typical cycle", advantage: "2–4 Weeks with native API" },
      { feature: "Data Privacy", traditional: "Manual compliance checks", advantage: "Automated regulatory engine" },
      { feature: "Scalability", traditional: "Requires infrastructure overhaul", advantage: "Elastic cloud-native core" },
      { feature: "Cost Model", traditional: "High upfront capital expense", advantage: "Performance-aligned pricing" },
    ],
  },
  process: {
    steps: [
      {
        number: "01", title: "Discovery",
        description: "We audit your existing channels and identify high-leverage growth opportunities through deep AI analysis.",
        icon: "Search",
        accentColor: "bg-blue-500", softBg: "bg-blue-50",
        iconBg: "bg-blue-100", iconText: "text-blue-600", borderColor: "border-blue-100",
      },
      {
        number: "02", title: "Strategy",
        description: "Creation of a custom marketing engine including affiliate portals, ad campaigns, and content schedules.",
        icon: "Target",
        accentColor: "bg-violet-500", softBg: "bg-violet-50",
        iconBg: "bg-violet-100", iconText: "text-violet-600", borderColor: "border-violet-100",
      },
      {
        number: "03", title: "Design",
        description: "Creative development of landing pages, ad assets, email templates, and complete brand guidelines.",
        icon: "Settings",
        accentColor: "bg-pink-500", softBg: "bg-pink-50",
        iconBg: "bg-pink-100", iconText: "text-pink-600", borderColor: "border-pink-100",
      },
      {
        number: "04", title: "Development",
        description: "Technical implementation of tracking, automation, integrations, and campaign infrastructure.",
        icon: "Zap",
        accentColor: "bg-amber-500", softBg: "bg-amber-50",
        iconBg: "bg-amber-100", iconText: "text-amber-600", borderColor: "border-amber-100",
      },
      {
        number: "05", title: "Launch",
        description: "Deployment of automation tools and live reporting. Real-time feedback loops begin immediately.",
        icon: "Rocket",
        accentColor: "bg-emerald-500", softBg: "bg-emerald-50",
        iconBg: "bg-emerald-100", iconText: "text-emerald-600", borderColor: "border-emerald-100",
      },
      {
        number: "06", title: "Optimization",
        description: "Continuous A/B testing, bid management, and creative optimization based on live performance data.",
        icon: "BarChart3",
        accentColor: "bg-cyan-500", softBg: "bg-cyan-50",
        iconBg: "bg-cyan-100", iconText: "text-cyan-600", borderColor: "border-cyan-100",
      },
      {
        number: "07", title: "Reporting",
        description: "Weekly performance reports with actionable insights and forward-looking strategic recommendations.",
        icon: "BarChart",
        accentColor: "bg-indigo-500", softBg: "bg-indigo-50",
        iconBg: "bg-indigo-100", iconText: "text-indigo-600", borderColor: "border-indigo-100",
      },
      {
        number: "08", title: "Growth",
        description: "Aggressive expansion of high-ROI channels and continuous optimisation of ad spend efficiency.",
        icon: "ArrowUpRight",
        accentColor: "bg-teal-500", softBg: "bg-teal-50",
        iconBg: "bg-teal-100", iconText: "text-teal-600", borderColor: "border-teal-100",
      },
    ],
  },
  aboutPage: {
    mission: "Mission: AI-Powered Growth",
    heading: "Revolutionizing Growth with Intelligence.",
    description: "GrowthPlatform exists to bridge the gap between complex data and strategic growth. We build the infrastructure for the next generation of affiliate and referral ecosystems, powered by autonomous AI.",
    primaryCta: "Join Our Mission",
    secondaryCta: "View Careers",
    heroImages: [
      "https://images.pexels.com/photos/6805161/pexels-photo-6805161.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=700&w=500",
      "https://images.pexels.com/photos/5324892/pexels-photo-5324892.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=500",
      "https://images.pexels.com/photos/17737193/pexels-photo-17737193.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=500",
      "https://images.pexels.com/photos/6804073/pexels-photo-6804073.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=700&w=500",
    ],
    stats: [
      { value: "2,000+", label: "Enterprise Clients" },
      { value: "$120M+", label: "Revenue Generated" },
      { value: "50+", label: "Countries Served" },
      { value: "98%", label: "Client Retention" },
    ],
    timeline: [
      {
        year: "2018",
        title: "The Genesis",
        description: "Founded by a team of ex-Meta and Google engineers in a San Francisco garage with a clear vision: automate world-class affiliate and referral marketing for every business.",
        image: "https://images.pexels.com/photos/6804612/pexels-photo-6804612.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
        alt: "Early team working on startup",
      },
      {
        year: "2020",
        title: "Growth Platform V1",
        description: "Launched our first flagship product, helping 500+ SaaS companies seamlessly manage their affiliate networks and track real-time partner performance.",
        image: "https://images.pexels.com/photos/6804068/pexels-photo-6804068.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
        alt: "Engineering team building platform",
      },
      {
        year: "2022",
        title: "The AI Pivot",
        description: "Integrated deep learning models to predict partner performance, leading to a 300% increase in client ROI and becoming the industry's first AI-native growth platform.",
        image: "https://images.pexels.com/photos/7413913/pexels-photo-7413913.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
        alt: "Team reviewing AI growth charts",
      },
      {
        year: "2024",
        title: "Global Expansion",
        description: "Expanded to 50+ countries, serving thousands of enterprise clients worldwide with full-stack growth infrastructure trusted by category-defining brands.",
        image: "https://images.pexels.com/photos/7793691/pexels-photo-7793691.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
        alt: "Team celebrating global expansion",
      },
    ],
    values: [
      {
        icon: "Shield",
        title: "Radical Trust",
        description: "We believe transparency is the foundation of every successful partnership. Our AI is open-book — every decision is explainable and every dollar is accounted for.",
        image: "https://images.pexels.com/photos/15543048/pexels-photo-15543048.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500",
        alt: "Team values whiteboard session",
        tags: ["Transparency", "Open AI", "Accountability"],
      },
      {
        icon: "Lightbulb",
        title: "Pure Innovation",
        description: "We don't follow trends; we set them. Our engineering culture is obsessed with pushing machine learning to its limits to solve real business problems.",
        image: "https://images.pexels.com/photos/17737193/pexels-photo-17737193.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500",
        alt: "Colleagues collaborating on innovation",
        tags: ["Machine Learning", "R&D", "Engineering"],
      },
      {
        icon: "Globe",
        title: "Global Reach",
        description: "Scale beyond borders. Our platform empowers businesses to connect with partners across 50+ countries instantly with multi-currency payout support.",
        image: "https://images.pexels.com/photos/819087/pexels-photo-819087.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500",
        alt: "Globe representing global reach",
        tags: ["50+ Countries", "Multi-Currency", "Global"],
      },
    ],
    vision: {
      heading: "Growth Platform Vision",
      subheading: "Building the unified intelligence layer for the commerce ecosystem.",
      sustainableScaling: {
        tag: "Sustainable Scaling",
        title: "Building infrastructure to enable petabytes of data with zero carbon footprint.",
        description: "Our cloud-native architecture is optimized for efficiency at every layer.",
        image: "https://images.pexels.com/photos/7693692/pexels-photo-7693692.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1200",
      },
      autonomousGrowth: {
        title: "Autonomous Growth",
        description: "Self-optimizing campaigns that learn from market fluctuations in real-time.",
      },
      aiFirst: {
        title: "AI-First Strategy",
        subtitle: "Every decision, data-driven",
        image: "https://images.pexels.com/photos/8370345/pexels-photo-8370345.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=500&w=600",
      },
    },
    global: {
      heading: "San Francisco",
      city: "San Francisco",
      hubsText: "With hubs in London, Tokyo, Singapore, and Sydney.",
      description: "The growth engine for the next generation of enterprise performance marketing, operating at planetary scale.",
      image: "https://images.pexels.com/photos/6804073/pexels-photo-6804073.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=700&w=1400",
      stats: [
        { value: "180+", label: "Team Members" },
        { value: "2.5M", label: "Campaigns Run" },
        { value: "50+", label: "Countries" },
        { value: "99.99%", label: "Uptime SLA" },
      ],
      cities: ["🇺🇸 San Francisco", "🇬🇧 London", "🇯🇵 Tokyo", "🇸🇬 Singapore", "🇦🇺 Sydney"],
    },
    careers: {
      heading: "Build the Future of Growth",
      subheading: "Growth",
      description: "We're a team of builders, dreamers, and data scientists working on problems that matter. Join us and help redefine how the world grows.",
      perks: [
        "Unlimited PTO & flexible remote work",
        "Competitive equity packages",
        "World-class health & dental coverage",
        "$5,000 annual learning budget",
        "Monthly wellness stipend",
        "Global team retreats twice a year",
      ],
      images: [
        "https://images.pexels.com/photos/15543028/pexels-photo-15543028.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=500&w=400",
        "https://images.pexels.com/photos/6405773/pexels-photo-6405773.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=400",
        "https://images.pexels.com/photos/6804580/pexels-photo-6804580.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=400",
        "https://images.pexels.com/photos/7710118/pexels-photo-7710118.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=500&w=400",
      ],
    },
  },
  servicesPage: {
    heading: "Enterprise Growth Engineered for Scale",
    subheading: "From precision SEO to AI-driven automation, we provide the strategic infrastructure and execution excellence required to dominate your market.",
    seoSection: {
      heading: "Precision Search Engine Optimization",
      description: "Move beyond simple keywords. Our SEO methodology focuses on topical authority, technical excellence, and revenue-driving intent that secures your digital footprint.",
      image: "https://images.pexels.com/photos/7693148/pexels-photo-7693148.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=840&w=900",
      metricBadge: { icon: "TrendingUp", value: "+240%", label: "Organic Lift", metricLabel: "Traffic Growth YoY" },
      statCards: [
        { value: "4.2x", label: "Average ROI" },
        { value: "240%", label: "Traffic Growth" },
        { value: "90 Days", label: "Time to Scale" },
      ],
      checklist: ["Technical Audit & Core Web Vitals", "Authority Building via PR Outreach", "Content Strategy & Execution", "Local & International SEO"],
    },
    paidPerformance: {
      heading: "Paid Performance & Acquisition",
      description: "Deploy capital where it generates the highest yield. We combine deep data analysis with creative excellence to scale paid acquisition across Google, LinkedIn, and Meta.",
      image: "https://images.pexels.com/photos/8353799/pexels-photo-8353799.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=840&w=900",
      roasTarget: "400%",
      roasCurrent: "512%",
      checklist: ["Google Ads & Search", "Meta & Instagram Ads", "LinkedIn B2B Campaigns", "Programmatic Display"],
      overlayTitle: "Global Expansion",
      overlayStats: [
        { value: "892K", label: "Impressions" },
        { value: "12.4%", label: "CTR" },
        { value: "$14.20", label: "CPC" },
      ],
    },
    affiliateSection: {
      heading: "Affiliate & Partner Ecosystems",
      description: "Build an army of advocates. We design and manage world-class referral programs that turn your customers into your most effective sales force.",
      cards: [
        { icon: "Users", title: "Partner Discovery", desc: "AI-driven identification of top-tier creators and affiliates aligned with your brand values.", stat: "5K+ Vetted Partners" },
        { icon: "TrendingUp", title: "Lifecycle Management", desc: "End-to-end recruitment, onboarding, and incentive management at global scale.", stat: "30% Revenue Lift", popular: true },
        { icon: "Zap", title: "Payout Automation", desc: "Global compliance, multi-currency payouts, and transparent reporting for all partners.", stat: "99.9% Uptime" },
      ],
      expertSpotlight: {
        image: "https://images.pexels.com/photos/7693692/pexels-photo-7693692.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=500&w=700",
        quote: "Technology provides the rails, but relationships are the engine. Our affiliate specialists act as an extension of your team to ensure every partnership is high-value and sustainable.",
        name: "Elena Rodriguez",
        title: "Global VP of Partnerships",
      },
    },
    aiAutomation: {
      heading: "AI-Driven Growth Automation",
      description: "Automate the complex, optimize the routine. We deploy proprietary AI models to predict customer behavior, automate outreach, and optimize partner payouts in real-time.",
      image: "https://images.pexels.com/photos/3861957/pexels-photo-3861957.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=800&w=900",
      overlayItems: ["Auto-Discovery", "Churn Prediction", "Dynamic Incentives"],
      checklist: ["Predictive Lead Scoring with 94% Accuracy", "Autonomous Partner Onboarding Workflows", "Real-time Revenue Attribution across 12+ Channels"],
      ctaText: "Request AI Audit",
      ctaHref: "/contact",
    },
    solutionFinder: {
      heading: "Solution Finder",
      description: "Select your industry to see tailored solutions.",
      industries: [
        {
          name: "Healthcare",
          features: ["End-to-end Data Encryption", "HIPAA Compliance", "Audit-ready Reporting"],
          description: "HIPAA-compliant infrastructure with automated patient data management. Scale your practice without compromising security.",
          image: "https://images.pexels.com/photos/106344/pexels-photo-106344.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=700",
        },
        {
          name: "Finance",
          features: ["SOC2 Certified", "Fraud Detection", "Regulatory Compliance"],
          description: "Secure, compliant financial marketing infrastructure built for modern fintech and banking.",
          image: "https://images.pexels.com/photos/106344/pexels-photo-106344.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=700",
        },
        {
          name: "E-commerce",
          features: ["Cart Recovery", "Dynamic Pricing", "Product Feed Optimization"],
          description: "Omnichannel marketing automation that drives sales and customer retention at scale.",
          image: "https://images.pexels.com/photos/106344/pexels-photo-106344.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=700",
        },
      ],
    },
  },
  resourcesPage: {
    heading: "Scale Faster with Expert Resources",
    subheading: "Actionable guides, templates, webinars, and case studies covering digital marketing, affiliate marketing, paid advertising, SEO, and performance marketing — built for growth teams who want results.",
    heroPills: [
      { label: "Digital Marketing", icon: "Globe" },
      { label: "Affiliate Marketing", icon: "Users" },
      { label: "Google & Meta Ads", icon: "Target" },
      { label: "SEO & Content", icon: "TrendingUp" },
      { label: "Email Marketing", icon: "Mail" },
      { label: "Performance Marketing", icon: "BarChart3" },
    ],
    searchPlaceholder: "Search affiliate guides, Google Ads webinars, SEO templates…",
    featured: {
      main: {
        image: "https://images.pexels.com/photos/9052188/pexels-photo-9052188.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=720&w=1000",
        badge: "NEW RELEASE",
        badgeText: "32 Min Read",
        topic: "Affiliate Marketing",
        title: "State of Affiliate Marketing 2024: Global Benchmarks & Trends",
        description: "Our comprehensive study of 500+ global affiliate programmes revealing the commission structures, partner types, fraud trends, and technology stacks driving affiliate revenue in 2024.",
        primaryLabel: "Download Free",
        secondaryLabel: "Preview",
      },
      sub1: {
        image: "https://images.pexels.com/photos/7877027/pexels-photo-7877027.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=500&w=900",
        topic: "Paid Advertising",
        title: "Google Ads Mastery: 2024 Complete Playbook",
        description: "Everything from Search to Performance Max — smart bidding, creative, landing pages, and ROAS optimisation.",
        buttonLabel: "Get Free Guide",
      },
      sub2: {
        image: "https://images.pexels.com/photos/15635241/pexels-photo-15635241.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=900",
        topic: "SEO & Content",
        title: "12-Month Digital Marketing Calendar — Free Template",
        buttonLabel: "Download",
      },
    },
    categories: [
      { id: "all", label: "All Resources" },
      { id: "ebooks", label: "Guides & Ebooks" },
      { id: "templates", label: "Templates" },
      { id: "webinars", label: "Webinars" },
      { id: "case-studies", label: "Case Studies" },
    ],
    resources: [
      {
        id: "saas-pricing", cat: "ebooks", type: "Ebook", typeColor: "text-blue-700", typeBg: "bg-blue-100", icon: "BookOpen",
        title: "The 2024 SaaS Pricing Handbook",
        description: "Master subscription tier optimisation and maximise LTV with proven data-driven pricing frameworks used by the fastest-growing SaaS companies.",
        topic: "Digital Marketing", topicColor: "text-blue-600",
        image: "https://images.pexels.com/photos/5972329/pexels-photo-5972329.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=700",
        imageAlt: "Person analyzing financial charts on phone and laptop",
        readTime: "24 min read", tags: ["Pricing", "SaaS", "LTV"], isFree: true,
      },
      {
        id: "affiliate-state", cat: "ebooks", type: "Whitepaper", typeColor: "text-orange-700", typeBg: "bg-orange-100", icon: "BookOpen",
        title: "State of Affiliate Marketing 2024",
        description: "Comprehensive study of 500+ global brands revealing the tactics, technology, and trends driving affiliate programme success this year.",
        topic: "Affiliate Marketing", topicColor: "text-orange-600",
        image: "https://images.pexels.com/photos/590011/pexels-photo-590011.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=700",
        imageAlt: "Business growth charts and analytics papers",
        readTime: "32 min read", tags: ["Affiliate", "Research", "2024"], isFree: true,
      },
      {
        id: "multi-touch", cat: "webinars", type: "Webinar", typeColor: "text-purple-700", typeBg: "bg-purple-100", icon: "Video",
        title: "Multi-Touch Attribution Masterclass",
        description: "On-demand session solving the attribution puzzle across 12+ digital marketing channels — from first click to closed deal.",
        topic: "Performance Marketing", topicColor: "text-violet-600",
        image: "https://images.pexels.com/photos/8369683/pexels-photo-8369683.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=700",
        imageAlt: "Woman presenting at podium digital marketing conference",
        readTime: "45 min", tags: ["Attribution", "Analytics", "Paid Ads"], isFree: false,
      },
      {
        id: "google-ads-guide", cat: "ebooks", type: "Guide", typeColor: "text-red-700", typeBg: "bg-red-100", icon: "BookOpen",
        title: "Google Ads Mastery: 2024 Playbook",
        description: "Complete Google Ads management guide — from Search and Shopping to Performance Max, smart bidding, and AI-powered creative optimisation.",
        topic: "Google Ads", topicColor: "text-red-600",
        image: "https://images.pexels.com/photos/6986455/pexels-photo-6986455.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=700",
        imageAlt: "Google search on laptop for paid advertising",
        readTime: "28 min read", tags: ["Google Ads", "PPC", "ROAS"], isFree: true,
      },
      {
        id: "seo-authority", cat: "ebooks", type: "Guide", typeColor: "text-emerald-700", typeBg: "bg-emerald-100", icon: "BookOpen",
        title: "The Complete SEO Authority Blueprint",
        description: "From technical foundations to topical authority building — rank #1 for your highest-value keywords and dominate organic search in your category.",
        topic: "SEO Optimization", topicColor: "text-emerald-600",
        image: "https://images.pexels.com/photos/9822732/pexels-photo-9822732.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=700",
        imageAlt: "SEO wooden blocks on laptop keyboard",
        readTime: "35 min read", tags: ["SEO", "Organic", "Content"], isFree: true,
      },
      {
        id: "paid-ads-scaling", cat: "webinars", type: "Webinar", typeColor: "text-purple-700", typeBg: "bg-purple-100", icon: "Video",
        title: "Scaling Paid Ads Without Burning Budget",
        description: "Live workshop recording: how to cut CAC by 40% while scaling spend 3× using AI-driven bid management across Google, Meta, and LinkedIn.",
        topic: "Paid Advertising", topicColor: "text-orange-600",
        image: "https://images.pexels.com/photos/7013900/pexels-photo-7013900.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=700",
        imageAlt: "Online digital marketing webinar on laptop",
        readTime: "62 min", tags: ["Paid Ads", "AI Bidding", "CAC"], isFree: false,
      },
      {
        id: "affiliate-programme", cat: "templates", type: "Template", typeColor: "text-teal-700", typeBg: "bg-teal-100", icon: "FileSpreadsheet",
        title: "Affiliate Programme Launch Kit",
        description: "Complete templates for launching a high-performing affiliate programme — commission structure, partner brief, payout model, and tier design framework.",
        topic: "Affiliate Marketing", topicColor: "text-orange-600",
        image: "https://images.pexels.com/photos/7876383/pexels-photo-7876383.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=700",
        imageAlt: "Business review charts and financial report on whiteboard",
        readTime: "Free Download", tags: ["Affiliate", "Template", "Free"], isFree: true,
      },
      {
        id: "content-calendar", cat: "templates", type: "Template", typeColor: "text-teal-700", typeBg: "bg-teal-100", icon: "FileSpreadsheet",
        title: "12-Month Digital Marketing Calendar",
        description: "Complete content and campaign calendar with topic clustering, keyword mapping, and multi-channel distribution planning for digital and affiliate teams.",
        topic: "Content Marketing", topicColor: "text-blue-600",
        image: "https://images.pexels.com/photos/38285024/pexels-photo-38285024.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=700",
        imageAlt: "Content creator block letters marketing strategy",
        readTime: "Free Download", tags: ["Content", "Calendar", "Strategy"], isFree: true,
      },
      {
        id: "email-automation", cat: "ebooks", type: "Guide", typeColor: "text-cyan-700", typeBg: "bg-cyan-100", icon: "Mail",
        title: "Email Automation Playbook for Growth Teams",
        description: "Step-by-step sequences for onboarding, nurture, win-back, and referral campaigns — automated revenue streams that work while you sleep.",
        topic: "Email Marketing", topicColor: "text-cyan-600",
        image: "https://images.pexels.com/photos/7430701/pexels-photo-7430701.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=700",
        imageAlt: "Email marketing envelopes and subscribe card",
        readTime: "20 min read", tags: ["Email", "Automation", "Sequences"], isFree: true,
      },
      {
        id: "meta-ads-creative", cat: "ebooks", type: "Guide", typeColor: "text-blue-700", typeBg: "bg-blue-100", icon: "BookOpen",
        title: "Meta Ads Creative Strategy Guide",
        description: "Master Facebook and Instagram ad creative that stops the scroll — from UGC-style video to dynamic product ads and full-funnel creative architecture.",
        topic: "Meta Ads", topicColor: "text-blue-600",
        image: "https://images.pexels.com/photos/3850271/pexels-photo-3850271.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=700",
        imageAlt: "Social media phone content creation for Meta ads",
        readTime: "22 min read", tags: ["Meta Ads", "Creative", "Social"], isFree: true,
      },
      {
        id: "growth-forecast", cat: "templates", type: "Template", typeColor: "text-teal-700", typeBg: "bg-teal-100", icon: "FileSpreadsheet",
        title: "Quarterly Growth Forecasting Sheet",
        description: "Plug-and-play Google Sheets framework for predicting your next four quarters of revenue expansion from digital marketing and affiliate channels.",
        topic: "Performance Marketing", topicColor: "text-violet-600",
        image: "https://images.pexels.com/photos/7947746/pexels-photo-7947746.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=700",
        imageAlt: "Revenue forecast report with calculator and notebook",
        readTime: "Free Download", tags: ["Forecasting", "Revenue", "Planning"], isFree: true,
      },
      {
        id: "data-pipeline", cat: "case-studies", type: "Case Study", typeColor: "text-indigo-700", typeBg: "bg-indigo-100", icon: "BarChart3",
        title: "127% ROI: Cloud Infrastructure Digital Marketing",
        description: "How a B2B SaaS company used our affiliate and performance marketing engine to unlock 127% ROI through precision partner targeting and AI bid optimisation.",
        topic: "Digital Marketing", topicColor: "text-blue-600",
        image: "https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=700",
        imageAlt: "Server infrastructure data center technology",
        readTime: "8 min read", tags: ["Case Study", "B2B", "ROI"], isFree: true,
      },
    ],
    popular: [
      { category: "AFFILIATE", categoryColor: "text-orange-500", title: "How to Launch a $50M Affiliate Programme from Scratch" },
      { category: "PAID ADS", categoryColor: "text-blue-600", title: "10 Google Ads Mistakes Burning Your Budget Right Now" },
      { category: "SEO", categoryColor: "text-emerald-600", title: "Topical Authority: The SEO Strategy That Beats Every Algorithm" },
      { category: "META ADS", categoryColor: "text-violet-600", title: "Meta Ads After iOS14: The Full Recovery Playbook" },
    ],
    patterns: [
      {
        metric: "340%", metricLabel: "Affiliate Revenue Growth", tag: "Affiliate Marketing",
        tagColor: "text-orange-600", tagBg: "bg-orange-50",
        title: "How GlobalRetail Built a $50M Affiliate Revenue Channel in 6 Months",
        desc: "By rebuilding their affiliate programme with AI-powered partner discovery and automated payouts, GlobalRetail grew affiliate revenue 340% and reduced payout errors to zero.",
        img: "https://images.pexels.com/photos/7172856/pexels-photo-7172856.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=160&w=200",
        alt: "Business growth thumbs up charts",
      },
      {
        metric: "4.8×", metricLabel: "Google Ads ROAS", tag: "Paid Advertising",
        tagColor: "text-blue-600", tagBg: "bg-blue-50",
        title: "CloudPath Achieves 4.8× ROAS by Switching to AI Bid Management",
        desc: "Moving from manual bidding to smart bidding — with proper conversion tracking and audience architecture — transformed CloudPath's Google Ads ROAS from 1.9× to 4.8×.",
        img: "https://images.pexels.com/photos/106344/pexels-photo-106344.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=160&w=200",
        alt: "Analytics tablet showing charts and data",
      },
      {
        metric: "240%", metricLabel: "Organic Traffic Growth", tag: "SEO Optimization",
        tagColor: "text-emerald-600", tagBg: "bg-emerald-50",
        title: "TechStartup Ranks #1 for 200+ Keywords with Topical Authority SEO",
        desc: "A complete SEO overhaul focused on topical authority rather than individual keywords delivered 240% organic traffic growth and a $2.1M reduction in annual paid search spend.",
        img: "https://images.pexels.com/photos/7876984/pexels-photo-7876984.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=160&w=200",
        alt: "Presenting digital marketing data charts",
      },
    ],
    patternsBanner: {
      title: "50+ digital marketing & affiliate case studies",
      subtitle: "Real results from real GrowthPlatform clients worldwide",
    },
    services: [
      { icon: "Globe", label: "Digital Marketing", href: "/services/seo-optimization" },
      { icon: "Users", label: "Affiliate Marketing", href: "/services/affiliate" },
      { icon: "Target", label: "Paid Advertising", href: "/services/google-ads" },
      { icon: "TrendingUp", label: "SEO Optimization", href: "/services/seo-optimization" },
      { icon: "Mail", label: "Email Marketing", href: "/services/lead-gen" },
      { icon: "BarChart3", label: "Performance Marketing", href: "/services/performance" },
    ],
    newsletter: {
      heading: "Get the Growth Playbook",
      description: "Weekly insights on affiliate marketing, digital advertising, SEO, and performance marketing — delivered to 24,000+ growth leaders every Tuesday.",
    },
  },
  contactPage: {
    heading: "Let's Build Your Growth Engine",
    subheading: "Our team of growth experts is ready to help accelerate your digital marketing efforts.",
    address: "100 Market Street, Suite 400<br />San Francisco, CA 94105",
    email: "hello@growthplatform.com<br />support@growthplatform.com",
    phone: "+1 (555) 123-4567<br />Mon-Fri, 9am-6pm PST",
    hours: "Monday - Friday: 9:00 AM - 6:00 PM<br />Saturday - Sunday: Closed",
    successHeading: "Message Sent!",
    successDescription: "Thanks for reaching out. Our team will get back to you within 24 hours.",
    services: [
      "SEO Optimization",
      "Google Ads",
      "Meta Ads",
      "Affiliate Marketing",
      "Performance Marketing",
      "Social Media Marketing",
      "Email Marketing",
      "Web Development",
      "Marketing Automation",
      "AI Marketing Solutions",
      "Other",
    ],
  },
  platformsPage: {
    badge: "Enterprise Infrastructure",
    heading: "Powerful Growth Platform",
    subheading: "Select the platform component that best fits your enterprise needs and scale with us.",
    cardTags: ["Enterprise", "Scalable", "Secure"],
    icons: ["Target", "Globe", "Layers"],
    cta: {
      title: "Choose Your Platform",
      subtitle: "Get access to the complete GrowthPlatform ecosystem with 24/7 support and continuous updates.",
    },
    detailCta: {
      title: "Ready to start building with {title}?",
      description: "Join 500+ enterprises that trust GrowthPlatform for their growth infrastructure needs.",
      primaryCta: "Get Started",
      secondaryCta: "Talk to Sales",
      primaryHref: "/contact",
      secondaryHref: "/contact",
    },
  },
};
