const seo = {
  title: "Beard Style Preview — Try 18 Styles on a Photo",
  h1: "Beard Style Preview: Try Beard Styles on Your Own Photo",
  metaDescription:
    "Upload a photo and preview 18 beard styles — stubble, goatee, Balbo, full beard — placed on your jawline by 68-point face detection. Nothing is uploaded.",
  intro:
    "Beard Style Preview draws facial hair onto your own photo by first locating the face with the TinyFaceDetector and 68-point landmark models from face-api.js (@vladmandic/face-api, running on TensorFlow.js), then building the beard outline from jaw landmarks 0–16, the chin point (landmark 8) and the outer-lip contour. That outline is smoothed with a Catmull-Rom spline, filled with a vertical gradient whose colour is graded 18% toward the photo's own mean colour, textured with individual hair strands from a seeded xorshift RNG so re-renders never flicker, then alpha-feathered with a separable box blur and given a contact shadow offset in the direction the light appears to come from (measured by comparing left-half and right-half luminance). The detection models are served from the site's own /models directory and every step — model loading, detection, lighting analysis and canvas rendering — runs in your browser, so the photo is never sent to a server.",
  useCases: [
    "Seeing whether a goatee, Balbo, chin strap or full beard suits your jaw shape before committing six weeks to growing one out.",
    "Showing a barber the exact shape you want — export the preview as a PNG up to 3840px on the long edge and bring it to the appointment.",
    "Comparing stubble density and length settings against your current look with the before/after slider before changing a profile photo.",
  ],
  benefits: [
    [
      "Placed on your actual jawline",
      "The beard outline is generated from your own detected jaw and lip landmarks — jaw points 0, 2, 4, 12, 14 and 16, the chin at point 8, and the averaged outer-lip centre — not stretched from a fixed sticker, so it follows your real chin width and face proportions.",
    ],
    [
      "Colour matched to your photo's lighting",
      "The colour you pick is blended 18% toward the photo's average colour, lifted by its measured brightness, and shaded with a gradient that darkens toward the neck. A soft contact shadow is cast in the estimated light direction so the beard reads as part of the photo rather than a flat overlay.",
    ],
    [
      "Nothing leaves your device",
      "The face models are served from the site itself and run through TensorFlow.js in the browser. Your image stays in a local object URL and canvas — there is no upload endpoint, no account, and no server round-trip anywhere in the pipeline.",
    ],
    [
      "Five sliders for fine control",
      "Scale (50–150), length (10–100), density (10–100), darkness (10–100) and opacity (0–100) re-render the preview instantly, and a draggable before/after slider keeps the original visible underneath for comparison.",
    ],
  ],
  faqs: [
    [
      "Is there a way to see what I'd look like with a beard using my own photo?",
      "Yes — upload or capture a photo here and the tool renders a beard onto it using your detected facial landmarks. It offers 18 named styles plus clean-shaven and a custom preset: light, medium and heavy stubble, goatee, circle beard, Van Dyke, Balbo, anchor, French beard, full beard, Garibaldi, ducktail, corporate, Bandholz, mutton chops, chin strap, soul patch and a handlebar combo.",
    ],
    [
      "Is this AI-generated, or is the beard drawn on?",
      "The face detection is a neural network — face-api.js running on TensorFlow.js — but the beard itself is drawn with Canvas 2D vector shapes and individual strand strokes, not generated by an image model. Treat it as an accurate shape-and-placement preview, not a photorealistic render of how the hair would actually grow.",
    ],
    [
      "Does the beard preview upload my photo anywhere?",
      "No. The detection models are fetched from the site's own /models path and everything after that — face detection, lighting analysis, beard rendering and export — happens on your device in a canvas element. The tool is free and does not require an account or sign-in.",
    ],
    [
      "How does it know where to put the beard?",
      "It runs face-api.js TinyFaceDetector at a 416px input size with a 0.4 confidence threshold, then the 68-point landmark model. Jaw points 0 through 16 give the jaw contour and width, point 8 gives the chin, and the 12 outer-lip points are averaged into a lip centre. Those anchors define the beard outline and a downward neck extension scaled by your length setting.",
    ],
    [
      "Why does it say no face detected?",
      "The detector runs at a 416px input with a 0.4 score threshold, so faces that are small in frame, sharply turned, or in dim light can fall below it. Use a front-facing, well-lit photo where the face fills a decent part of the frame. The built-in Edit Image panel lets you crop, rotate, flip and adjust brightness and contrast first, then retry detection.",
    ],
    [
      "What beard colours can I choose?",
      "Six presets: black (#1a1a1a), brown (#5c3a1e), gray (#9a9a9a), golden (#c4a843), white (#e8e8e8) and red (#b83a1a). Whichever you pick is graded toward the photo's own average colour and brightness before rendering, so the same preset looks different in warm indoor light than in daylight.",
    ],
    [
      "What image formats and file sizes work?",
      "JPG, PNG, WEBP and HEIC/HEIF up to 20 MB. You can drag and drop a file, click to browse, paste an image straight from the clipboard, or capture one with your webcam through the front-facing camera at roughly 640x480.",
    ],
    [
      "Can I download or share the preview?",
      "Yes — download as PNG or JPG (JPEG at 0.95 quality), saved as beard-preview.png or beard-preview.jpg. Before saving, the canvas is upscaled to at most 4x with the long edge capped at 3840px, and never below your device pixel ratio. A Share button uses the Web Share API on browsers that support it.",
    ],
  ],
  steps: [
    "Add a photo — drag and drop, click to browse, paste from the clipboard, or capture one with your webcam. JPG, PNG, WEBP and HEIC up to 20 MB are accepted.",
    "Wait for the face models to load and detect the face. If the photo has more than one person, a face picker appears so you can choose which one to apply the beard to.",
    "Pick a style category and style, choose a colour, then fine-tune scale, length, density, darkness and opacity. Compare with the before/after slider and download as PNG or JPG.",
  ],
};

export default seo;
