/**
 * AI Content Disclosure Generator.
 *
 * Assembles a plain-language disclosure statement for AI-assisted content.
 * The structure follows the elements that current transparency frameworks ask
 * for:
 *  - EU AI Act, Article 50 (transparency obligations): AI-generated or
 *    AI-manipulated text published to inform the public on matters of public
 *    interest must be disclosed, unless it underwent human review with a
 *    natural or legal person holding editorial responsibility.
 *  - FTC guidance on endorsements and deceptive practices: disclosures must be
 *    clear and conspicuous, not buried.
 *  - Common newsroom and publisher policies (AP, Reuters, Wired): say WHAT the
 *    AI did, WHO reviewed it, and WHO is accountable.
 * A good disclosure therefore names: the content type, the role AI played,
 * the tool (optionally), and the human review / accountability statement.
 */

/** What kind of content is being disclosed. */
export const CONTENT_TYPES = [
  { id: "article", label: "Article / blog post", noun: "article" },
  { id: "report", label: "Report / whitepaper", noun: "report" },
  { id: "newsletter", label: "Newsletter", noun: "newsletter" },
  { id: "social", label: "Social media post", noun: "post" },
  { id: "marketing", label: "Marketing copy", noun: "marketing copy" },
  { id: "documentation", label: "Documentation / help content", noun: "documentation" },
];

/**
 * The role AI played, ordered from lightest to heaviest involvement.
 * The phrasing states the human/AI split explicitly — the fact regulators and
 * readers care about most.
 */
export const ASSISTANCE_LEVELS = [
  {
    id: "research",
    label: "Research and summarisation only",
    phrase: "AI tools were used for background research and summarising source material; all of the published text was written by a human",
  },
  {
    id: "editing",
    label: "Editing and proofreading",
    phrase: "AI tools were used to edit, proofread and improve the clarity of human-written text",
  },
  {
    id: "outline",
    label: "Outlining and structure",
    phrase: "AI tools helped outline and structure this piece; the text itself was written by a human",
  },
  {
    id: "drafting",
    label: "Drafting assistance (human rewrote)",
    phrase: "portions of this piece were first drafted with AI assistance and then substantially rewritten by a human author",
  },
  {
    id: "generated",
    label: "Largely AI-generated",
    phrase: "the majority of this text was generated by AI from a human-provided brief",
  },
];

/** Whether images/media were also AI-generated. */
export const MEDIA_OPTIONS = [
  { id: "none", label: "No AI images or media", phrase: "" },
  { id: "images", label: "AI-generated images included", phrase: "Some images accompanying this piece were generated with AI." },
  { id: "edited", label: "AI-edited images included", phrase: "Some images accompanying this piece were edited or enhanced with AI." },
];

/** Placement guidance keyed by content type — from FTC "clear and conspicuous" guidance. */
export const PLACEMENT_TIPS = {
  article: "Place the disclosure at the top or bottom of the article, in the byline area or a labelled note — not only in a site-wide policy page.",
  report: "Put the disclosure in the methodology or acknowledgements section, and mention it in the executive summary if AI drafted substantial text.",
  newsletter: "Add the disclosure in the footer of the issue where the assisted content appears.",
  social: "Disclose in the post itself (for example a #MadeWithAI or 'AI-assisted' label) — platform-level labels may also apply.",
  marketing: "Keep the disclosure adjacent to the claim or content it covers; the FTC treats buried disclosures as ineffective.",
  documentation: "Add the disclosure to the page footer or a dedicated 'About this content' note.",
};

const MAX_FIELD = 120;

/**
 * Build the disclosure statement.
 * @param {object} input
 * @param {string} input.contentTypeId  One of CONTENT_TYPES ids.
 * @param {string} input.assistanceId   One of ASSISTANCE_LEVELS ids.
 * @param {string} input.mediaId        One of MEDIA_OPTIONS ids.
 * @param {string} [input.toolNames]    Comma-separated tool names (optional).
 * @param {boolean} input.humanReviewed Whether a human reviewed and approved the final content.
 * @param {string} [input.reviewerRole] Who is editorially responsible (e.g. "the editorial team").
 * @param {string} [input.orgName]      Publisher / organisation name (optional).
 * @returns {{statement:string, shortLabel:string, placementTip:string}|{error:string}}
 */
export function buildDisclosure({
  contentTypeId,
  assistanceId,
  mediaId = "none",
  toolNames = "",
  humanReviewed = true,
  reviewerRole = "",
  orgName = "",
}) {
  const contentType = CONTENT_TYPES.find((c) => c.id === contentTypeId);
  const assistance = ASSISTANCE_LEVELS.find((a) => a.id === assistanceId);
  const media = MEDIA_OPTIONS.find((m) => m.id === mediaId);
  if (!contentType || !assistance || !media) {
    return { error: "Choose a content type, level of AI assistance and media option from the lists." };
  }

  const tools = String(toolNames)
    .split(",")
    .map((t) => t.trim())
    .filter(Boolean);
  if (tools.some((t) => t.length > MAX_FIELD)) {
    return { error: `Keep each tool name under ${MAX_FIELD} characters.` };
  }
  const org = String(orgName).trim();
  const reviewer = String(reviewerRole).trim();
  if (org.length > MAX_FIELD) return { error: `Keep the organisation name under ${MAX_FIELD} characters.` };
  if (reviewer.length > MAX_FIELD) return { error: `Keep the reviewer description under ${MAX_FIELD} characters.` };

  // Article 50(4) EU AI Act exempts AI-assisted public-interest text from the
  // disclosure duty only where human review AND editorial responsibility exist —
  // so an AI-generated piece without human review must never claim review.
  if (assistanceId === "generated" && !humanReviewed) {
    return {
      error:
        "A largely AI-generated piece with no human review should not be published with this disclosure — add human review, or state explicitly that the content is unreviewed machine output.",
    };
  }

  const toolPhrase =
    tools.length === 0
      ? ""
      : tools.length === 1
        ? ` (${tools[0]})`
        : ` (${tools.slice(0, -1).join(", ")} and ${tools[tools.length - 1]})`;

  const sentences = [];
  const opener = `AI disclosure: In preparing this ${contentType.noun}, ${assistance.phrase}${toolPhrase}.`;
  sentences.push(opener);

  if (media.phrase) sentences.push(media.phrase);

  if (humanReviewed) {
    const who = reviewer || (org ? `the ${org} editorial team` : "a human editor");
    sentences.push(
      `The final ${contentType.noun} was reviewed, fact-checked and approved by ${who}, who ${reviewer.includes(" and ") ? "hold" : "holds"} full editorial responsibility for it.`,
    );
  } else {
    sentences.push(`This ${contentType.noun} has not undergone human editorial review.`);
  }

  if (org) {
    sentences.push(`${org} remains accountable for the accuracy of everything published under its name.`);
  }

  const shortLabel =
    assistanceId === "generated"
      ? "AI-generated, human-reviewed"
      : humanReviewed
        ? "AI-assisted, human-reviewed"
        : "AI-assisted";

  return {
    statement: sentences.join(" "),
    shortLabel,
    placementTip: PLACEMENT_TIPS[contentType.id],
  };
}
