const seo = {
  intro:
    "The AI Content Disclosure Generator produces a ready-to-publish statement declaring how AI was used in an article, report, newsletter or marketing piece — what the AI did, whether a human reviewed it, and who holds editorial responsibility. Its structure mirrors what transparency frameworks such as Article 50 of the EU AI Act and FTC 'clear and conspicuous' disclosure guidance expect. It is built for content teams, publishers and agencies formalising an AI-use policy.",
  useCases: [
    "A content marketing team adding a standard AI-assistance note to blog posts that were drafted with ChatGPT and rewritten by staff writers",
    "A research firm disclosing in a whitepaper's methodology section that AI summarised sources while analysts wrote the findings",
    "A newsletter publisher labelling issues that include AI-generated images alongside human-written text",
  ],
  benefits: [
    ["Framework-aligned structure", "Covers the three elements regulators and readers look for: what the AI did, who reviewed it, who is accountable."],
    ["Honest by design", "Refuses to generate a disclosure claiming review for unreviewed AI-generated text."],
    ["Placement guidance included", "Tells you where the disclosure should appear for each content type, following FTC conspicuousness guidance."],
  ],
  faqs: [
    [
      "Do I legally have to disclose AI-generated content?",
      "It depends on jurisdiction and context. Under Article 50 of the EU AI Act, AI-generated text published to inform the public on matters of public interest must be disclosed unless it underwent human review with a person or organisation holding editorial responsibility; deepfake-style AI images and video must be labelled. In the US there is no single federal AI-disclosure law, but the FTC can treat undisclosed AI use as deceptive where it misleads consumers. This tool is informational — check your own jurisdiction's rules with counsel.",
    ],
    [
      "What should an AI disclosure statement include?",
      "Three things: what the AI actually did (research, editing, drafting or full generation), whether and by whom the output was reviewed and fact-checked, and who holds final editorial responsibility. Naming the specific tool is optional but adds credibility; vague lines like 'AI may have been used' satisfy no framework.",
    ],
    [
      "Where should the disclosure appear on the page?",
      "Adjacent to the content it covers — at the top or bottom of an article, in a report's methodology section, or in the post itself for social media. FTC guidance treats disclosures buried in a separate policy page or behind a link as not 'clear and conspicuous', so a site-wide AI policy alone is generally insufficient.",
    ],
    [
      "Is AI-edited content the same as AI-generated content?",
      "No, and the disclosure should say which one applies. Editing and proofreading human-written text is the lightest form of assistance and many newsroom policies do not require disclosure for it, while text largely generated by a model from a brief sits at the other end and is the case transparency rules primarily target. This tool offers five graded levels so the statement matches reality.",
    ],
  ],
};

export default seo;
