"use client";

import { useId, useState } from "react";
import {
  MapPin,
  Globe,
  Copy,
  Check,
  Heart,
  Star,
  Sun,
  DollarSign,
  UtensilsCrossed,
  HeartHandshake,
} from "lucide-react";
import { useCopyToClipboard } from "@/hooks/useCopyToClipboard";

function StarRating({ rating }) {
  const full = Math.floor(rating);
  const partial = rating - full;
  return (
    <div className="flex items-center gap-1">
      {Array.from({ length: full }, (_, i) => (
        <Star key={i} className="w-3.5 h-3.5 fill-amber-400 text-amber-400" />
      ))}
      {partial > 0 && (
        <Star className="w-3.5 h-3.5 fill-amber-400/50 text-amber-400" />
      )}
      <span className="text-xs font-medium ml-1">{rating.toFixed(1)}</span>
    </div>
  );
}

export default function DestinationCard({
  destination,
  rank,
  onSave,
  isSaved,
}) {
  const [expanded, setExpanded] = useState(false);
  const { copy, isCopied, announcement } = useCopyToClipboard();
  const detailsId = useId();

  if (!destination) return null;

  const scorePercent = Math.round((destination.score || 0.5) * 100);

  const matchColor =
    scorePercent >= 80
      ? "text-[var(--success)] bg-[var(--success)]/10"
      : scorePercent >= 60
      ? "text-[var(--warning)] bg-[var(--warning)]/10"
      : "text-[var(--info)] bg-[var(--info)]/10";

  const copyText = () => {
    const lines = [
      `🌴 ${destination.name}, ${destination.country}`,
      `Match: ${scorePercent}%`,
      `Best time: ${destination.bestTime}`,
      `Est. cost: ${destination.costEstimate}`,
      ``,
      destination.description,
      ``,
      `Top highlights:`,
      ...destination.highlights.map((h) => `• ${h}`),
      ``,
      `Generated by ALTFTool Dream Vacation Finder`,
    ];
    copy("card", lines.join("\n"), { label: `${destination.name} details` });
  };

  return (
    <div className="rounded-2xl border border-(--border) bg-(--surface) shadow-md overflow-hidden animate-in fade-in zoom-in-95 duration-300">
      <div className="relative h-40 bg-gradient-to-br from-(--primary)/20 to-(--primary)/5 flex items-center justify-center">
        <div className="text-center">
          <MapPin className="w-8 h-8 text-(--primary) mx-auto mb-1" />
          <p className="text-lg font-bold">{destination.name}</p>
          <p className="text-sm text-(--muted-foreground)">{destination.country}</p>
        </div>
        {rank !== undefined && (
          <div className="absolute top-3 left-3 w-8 h-8 rounded-full bg-(--primary) text-white flex items-center justify-center text-sm font-bold shadow-md">
            {rank + 1}
          </div>
        )}
        <div className={`absolute top-3 right-3 px-2.5 py-1 rounded-full text-xs font-bold ${matchColor}`}>
          {scorePercent}% match
        </div>
      </div>

      <div className="p-5 space-y-4">
        <div className="flex items-start justify-between gap-2">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1">
              <Globe className="w-3.5 h-3.5 text-(--muted-foreground)" />
              <span className="text-xs text-(--muted-foreground) capitalize">{destination.continent}</span>
            </div>
            <p className="text-sm leading-relaxed line-clamp-2">{destination.description}</p>
          </div>
        </div>

        <div className="flex flex-wrap gap-2">
          <span className="flex items-center gap-1 px-2.5 py-1 rounded-full bg-(--page) border border-(--border) text-xs">
            <Sun className="w-3 h-3 text-amber-500" />
            {destination.bestTime}
          </span>
          <span className="flex items-center gap-1 px-2.5 py-1 rounded-full bg-(--page) border border-(--border) text-xs">
            <DollarSign className="w-3 h-3 text-emerald-500" />
            {destination.costEstimate}
          </span>
          <StarRating rating={destination.rating} />
        </div>

        {expanded && (
          <div id={detailsId} className="space-y-4 animate-in fade-in slide-in-from-top-2 duration-200">
            <div>
              <p className="text-xs font-semibold text-(--muted-foreground) uppercase tracking-wide mb-2">
                Top Highlights
              </p>
              <ul className="space-y-1.5">
                {destination.highlights.map((h, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm">
                    <span className="w-1.5 h-1.5 rounded-full bg-(--primary) mt-1.5 flex-shrink-0" />
                    {h}
                  </li>
                ))}
              </ul>
            </div>

            <div>
              <p className="text-xs font-semibold text-(--muted-foreground) uppercase tracking-wide mb-1">
                Local Cuisine
              </p>
              <p className="text-sm flex items-center gap-1.5">
                <UtensilsCrossed className="w-3.5 h-3.5 text-(--muted-foreground)" />
                {destination.cuisine}
              </p>
            </div>

            <div className="p-3 rounded-xl bg-(--page) border border-(--border)">
              <p className="text-xs font-semibold text-(--muted-foreground) uppercase tracking-wide mb-1">Fun Fact</p>
              <p className="text-sm">
                <HeartHandshake className="w-3.5 h-3.5 inline text-amber-400 mr-1" />
                {destination.funFact}
              </p>
            </div>
          </div>
        )}

        <div className="flex items-center justify-between pt-1">
          <button
            onClick={() => setExpanded(!expanded)}
            aria-expanded={expanded}
            aria-controls={detailsId}
            className="text-xs font-medium text-(--primary) hover:underline"
          >
            {expanded ? "Show less" : "Show more"}
          </button>

          <div className="flex gap-1.5">
            <button
              onClick={copyText}
              aria-label={isCopied("card") ? `Copied ${destination.name} details to clipboard` : `Copy ${destination.name} details`}
              className="p-1.5 rounded-lg hover:bg-(--page) transition border border-(--border)"
              title="Copy"
            >
              {isCopied("card") ? (
                <Check className="w-3.5 h-3.5 text-(--primary)" />
              ) : (
                <Copy className="w-3.5 h-3.5 text-(--muted-foreground)" />
              )}
            </button>
            <button
              onClick={() => onSave(destination)}
              aria-label={isSaved ? `Remove ${destination.name} from saved` : `Save ${destination.name}`}
              aria-pressed={isSaved}
              className={`p-1.5 rounded-lg border border-(--border) transition ${
                isSaved ? "bg-red-50 dark:bg-red-900/20" : "hover:bg-(--page)"
              }`}
              title={isSaved ? "Saved" : "Save"}
            >
              <Heart
                className={`w-3.5 h-3.5 ${
                  isSaved ? "text-red-500 fill-red-500" : "text-(--muted-foreground)"
                }`}
              />
            </button>
          </div>
        </div>
      </div>
      <span className="sr-only" role="status" aria-live="polite">
        {announcement}
      </span>
    </div>
  );
}
