export const barGroups = [
  { id: "juices", label: "Juices & pulps" },
  { id: "fizz", label: "Soda, tonic & fizz" },
  { id: "fresh", label: "Lemon, mint & ginger" },
  { id: "fruits", label: "Fresh fruits" },
  { id: "syrups", label: "Syrups & sweeteners" },
  { id: "dairy", label: "Dairy & creamy" },
  { id: "extras", label: "Masala & extras" },
];

export const barItems = [
  { id: "orange-juice", label: "Orange juice", group: "juices" },
  { id: "pineapple-juice", label: "Pineapple juice", group: "juices" },
  { id: "cranberry-juice", label: "Cranberry juice", group: "juices" },
  { id: "apple-juice", label: "Apple juice", group: "juices" },
  { id: "grape-juice", label: "Grape juice", group: "juices" },
  { id: "mango-pulp", label: "Mango pulp", group: "juices" },
  { id: "mosambi-juice", label: "Mosambi juice", group: "juices" },
  { id: "litchi-juice", label: "Litchi juice", group: "juices" },
  { id: "coconut-water", label: "Coconut water", group: "juices" },
  { id: "tomato-juice", label: "Tomato juice", group: "juices" },

  { id: "soda", label: "Club soda", group: "fizz" },
  { id: "lemon-soda", label: "Lemon-lime soda", group: "fizz" },
  { id: "tonic-water", label: "Tonic water", group: "fizz" },
  { id: "ginger-ale", label: "Ginger ale", group: "fizz" },
  { id: "cola", label: "Cola", group: "fizz" },

  { id: "lemon", label: "Lemon / lime", group: "fresh" },
  { id: "mint", label: "Mint leaves", group: "fresh" },
  { id: "ginger", label: "Fresh ginger", group: "fresh" },
  { id: "basil", label: "Basil leaves", group: "fresh" },
  { id: "cucumber", label: "Cucumber", group: "fresh" },
  { id: "green-chilli", label: "Green chilli", group: "fresh" },

  { id: "watermelon", label: "Watermelon", group: "fruits" },
  { id: "raw-mango", label: "Raw green mango", group: "fruits" },
  { id: "banana", label: "Banana", group: "fruits" },
  { id: "strawberry", label: "Strawberry", group: "fruits" },
  { id: "pineapple", label: "Pineapple chunks", group: "fruits" },
  { id: "orange", label: "Orange", group: "fruits" },
  { id: "green-apple", label: "Green apple", group: "fruits" },
  { id: "pomegranate", label: "Pomegranate", group: "fruits" },
  { id: "kiwi", label: "Kiwi", group: "fruits" },
  { id: "muskmelon", label: "Muskmelon", group: "fruits" },

  { id: "sugar", label: "Sugar", group: "syrups" },
  { id: "sugar-syrup", label: "Sugar syrup", group: "syrups" },
  { id: "honey", label: "Honey", group: "syrups" },
  { id: "rose-syrup", label: "Rose syrup (Rooh Afza)", group: "syrups" },
  { id: "khus-syrup", label: "Khus syrup", group: "syrups" },
  { id: "blue-curacao", label: "Blue curacao syrup", group: "syrups" },
  { id: "grenadine", label: "Grenadine", group: "syrups" },
  { id: "chocolate-syrup", label: "Chocolate syrup", group: "syrups" },
  { id: "vanilla-essence", label: "Vanilla essence", group: "syrups" },

  { id: "milk", label: "Milk", group: "dairy" },
  { id: "curd", label: "Curd / yoghurt", group: "dairy" },
  { id: "cream", label: "Fresh cream", group: "dairy" },
  { id: "ice-cream", label: "Vanilla ice cream", group: "dairy" },
  { id: "coconut-milk", label: "Coconut milk", group: "dairy" },
  { id: "condensed-milk", label: "Condensed milk", group: "dairy" },

  { id: "black-salt", label: "Black salt", group: "extras" },
  { id: "chaat-masala", label: "Chaat masala", group: "extras" },
  { id: "roasted-cumin", label: "Roasted cumin powder", group: "extras" },
  { id: "jaljeera-powder", label: "Jaljeera powder", group: "extras" },
  { id: "black-pepper", label: "Black pepper", group: "extras" },
  { id: "cardamom", label: "Cardamom", group: "extras" },
  { id: "cinnamon", label: "Cinnamon", group: "extras" },
  { id: "instant-coffee", label: "Instant coffee", group: "extras" },
  { id: "cocoa", label: "Cocoa powder", group: "extras" },
  { id: "tamarind", label: "Tamarind", group: "extras" },
];

export const occasions = [
  { id: "summer", label: "Summer coolers" },
  { id: "party", label: "Party pitcher" },
  { id: "kids", label: "Kids' favourite" },
];

export const roleMeta = {
  base: { label: "Base", color: "var(--primary)" },
  fizz: { label: "Fizz", color: "var(--anslation-ds-info)" },
  sour: { label: "Sour", color: "var(--anslation-ds-warning)" },
  sweet: { label: "Sweet", color: "var(--anslation-ds-secondary)" },
  creamy: { label: "Creamy", color: "var(--anslation-ds-accent)" },
  flavour: { label: "Flavour", color: "var(--anslation-ds-success)" },
};

export const staples = "Ice, drinking water and plain salt are assumed to be on hand — they are not part of the matching.";

export const syrupTip = "Sugar syrup: dissolve 1 cup sugar in 1 cup hot water, cool it, and keep it in a bottle in the fridge for up to two weeks. It blends into cold drinks instantly, which loose sugar never does.";

export const drinks = [
  {
    id: "virgin-mojito",
    name: "Virgin Mojito",
    glass: "Highball",
    garnish: "Mint sprig and a lime wheel",
    occasions: ["summer", "party", "kids"],
    sweetness: 2,
    tang: 3,
    need: ["lemon", "mint", "soda", "sugar-syrup"],
    optional: ["green-apple", "cucumber", "basil", "black-salt"],
    pour: [
      { label: "Chilled club soda", ml: 150, role: "fizz" },
      { label: "Fresh lime juice", ml: 30, role: "sour" },
      { label: "Sugar syrup", ml: 20, role: "sweet" },
    ],
    add: [
      { label: "Mint leaves", qty: 10, unit: "leaves", role: "flavour" },
      { label: "Crushed ice", qty: 1, unit: "cup", role: "base" },
    ],
    method:
      "Press the mint against the side of the glass with the back of a spoon three or four times — you want the oils, not shredded leaves, so never grind it. Add lime juice and sugar syrup, fill with crushed ice and top with soda. Slide the spoon to the bottom and lift once to lace the mint through.",
  },
  {
    id: "shikanji",
    name: "Shikanji",
    glass: "Tall tumbler",
    garnish: "Lemon wheel and a mint sprig",
    occasions: ["summer", "kids", "party"],
    sweetness: 2,
    tang: 3,
    need: ["lemon", "sugar", "black-salt"],
    optional: ["roasted-cumin", "mint", "black-pepper", "soda"],
    pour: [
      { label: "Chilled water", ml: 170, role: "base" },
      { label: "Fresh lemon juice", ml: 30, role: "sour" },
    ],
    add: [
      { label: "Sugar", qty: 2, unit: "tsp", role: "sweet" },
      { label: "Black salt", qty: 0.5, unit: "tsp", role: "flavour" },
      { label: "Roasted cumin powder", qty: 0.25, unit: "tsp", role: "flavour" },
      { label: "Ice cubes", qty: 5, unit: "cubes", role: "base" },
    ],
    method:
      "Stir the sugar into a splash of the water first until it fully dissolves — cold water will never take it. Add lemon juice, black salt and cumin, then the rest of the water and ice. Taste before serving; shikanji should sting slightly with salt, not just read as lemonade.",
  },
  {
    id: "jaljeera-fizz",
    name: "Jaljeera Fizz",
    glass: "Tall tumbler",
    garnish: "Boondi float and a mint sprig",
    occasions: ["summer", "party"],
    sweetness: 1,
    tang: 3,
    need: ["jaljeera-powder", "lemon", "soda"],
    optional: ["mint", "black-salt", "tamarind", "roasted-cumin"],
    pour: [
      { label: "Chilled club soda", ml: 150, role: "fizz" },
      { label: "Chilled water", ml: 30, role: "base" },
      { label: "Lemon juice", ml: 20, role: "sour" },
    ],
    add: [
      { label: "Jaljeera powder", qty: 2, unit: "tsp", role: "flavour" },
      { label: "Black salt", qty: 0.25, unit: "tsp", role: "flavour" },
      { label: "Ice cubes", qty: 4, unit: "cubes", role: "base" },
    ],
    method:
      "Whisk the jaljeera powder into the plain water and lemon juice until there are no lumps — dumping it into soda makes it clump and foam over. Add ice, then top with soda poured down the side of the glass. Stir once, gently, so it keeps its fizz.",
  },
  {
    id: "nimbu-soda",
    name: "Masala Nimbu Soda",
    glass: "Tall tumbler",
    garnish: "Lemon wedge",
    occasions: ["summer", "party"],
    sweetness: 1,
    tang: 3,
    need: ["lemon", "soda", "black-salt"],
    optional: ["sugar", "roasted-cumin", "mint", "chaat-masala"],
    pour: [
      { label: "Chilled club soda", ml: 180, role: "fizz" },
      { label: "Lemon juice", ml: 25, role: "sour" },
    ],
    add: [
      { label: "Black salt", qty: 0.5, unit: "tsp", role: "flavour" },
      { label: "Sugar", qty: 1.5, unit: "tsp", role: "sweet" },
      { label: "Roasted cumin powder", qty: 0.25, unit: "tsp", role: "flavour" },
      { label: "Ice cubes", qty: 5, unit: "cubes", role: "base" },
    ],
    method:
      "Put lemon juice, sugar, black salt and cumin in the glass and stir until the sugar has gone. Add ice, then pour the soda in slowly against the wall of the glass. Serve immediately — this one dies flat within a few minutes.",
  },
  {
    id: "mint-lemonade",
    name: "Nimbu Pudina Cooler",
    glass: "Tall tumbler",
    garnish: "Mint sprig",
    occasions: ["summer", "kids", "party"],
    sweetness: 2,
    tang: 3,
    need: ["lemon", "mint", "sugar-syrup"],
    optional: ["soda", "black-salt", "cucumber", "basil"],
    pour: [
      { label: "Chilled water", ml: 140, role: "base" },
      { label: "Lemon juice", ml: 25, role: "sour" },
      { label: "Sugar syrup", ml: 25, role: "sweet" },
    ],
    add: [
      { label: "Mint leaves", qty: 15, unit: "leaves", role: "flavour" },
      { label: "Ice cubes", qty: 6, unit: "cubes", role: "base" },
    ],
    method:
      "Blend the mint with the water and a couple of ice cubes for 20 seconds, then strain through a sieve — blending longer turns it bitter and grassy. Stir in lemon juice and sugar syrup, and pour over fresh ice.",
  },
  {
    id: "watermelon-cooler",
    name: "Watermelon Cooler",
    glass: "Highball",
    garnish: "Watermelon wedge on the rim",
    occasions: ["summer", "kids", "party"],
    sweetness: 2,
    tang: 2,
    need: ["watermelon", "lemon"],
    optional: ["mint", "black-salt", "soda", "sugar-syrup"],
    pour: [
      { label: "Fresh watermelon juice", ml: 180, role: "base" },
      { label: "Lemon juice", ml: 15, role: "sour" },
      { label: "Sugar syrup", ml: 10, role: "sweet" },
    ],
    add: [
      { label: "Mint leaves", qty: 6, unit: "leaves", role: "flavour" },
      { label: "Black salt", qty: 0.25, unit: "tsp", role: "flavour" },
      { label: "Ice cubes", qty: 5, unit: "cubes", role: "base" },
    ],
    method:
      "Blend deseeded watermelon cubes for 15 seconds and strain — about 400 g of fruit gives you 180 ml of juice. Stir in lemon, sugar syrup and a pinch of black salt, which is what makes the melon taste more like itself. Serve over ice at once, as it separates on standing.",
  },
  {
    id: "aam-panna",
    name: "Aam Panna",
    glass: "Tall tumbler",
    garnish: "Mint sprig",
    occasions: ["summer", "party"],
    sweetness: 2,
    tang: 3,
    need: ["raw-mango", "sugar", "black-salt"],
    optional: ["roasted-cumin", "mint", "black-pepper"],
    pour: [
      { label: "Chilled water", ml: 160, role: "base" },
      { label: "Raw mango pulp, boiled and cooled", ml: 40, role: "sour" },
    ],
    add: [
      { label: "Sugar", qty: 2.5, unit: "tsp", role: "sweet" },
      { label: "Black salt", qty: 0.5, unit: "tsp", role: "flavour" },
      { label: "Roasted cumin powder", qty: 0.25, unit: "tsp", role: "flavour" },
      { label: "Mint leaves", qty: 8, unit: "leaves", role: "flavour" },
    ],
    method:
      "Boil 1 whole raw mango in water for 12 minutes until the skin wrinkles, cool it, then squeeze the pulp off the stone — one mango yields roughly 80 ml of pulp. Blend the pulp with sugar, black salt, cumin and mint. Dilute to taste with chilled water and serve over ice.",
  },
  {
    id: "cucumber-refresher",
    name: "Cucumber Mint Refresher",
    glass: "Highball",
    garnish: "Cucumber ribbon",
    occasions: ["summer", "party"],
    sweetness: 1,
    tang: 2,
    need: ["cucumber", "mint", "lemon"],
    optional: ["soda", "sugar-syrup", "black-salt", "basil"],
    pour: [
      { label: "Cucumber juice", ml: 120, role: "base" },
      { label: "Chilled club soda", ml: 60, role: "fizz" },
      { label: "Lemon juice", ml: 15, role: "sour" },
      { label: "Sugar syrup", ml: 15, role: "sweet" },
    ],
    add: [
      { label: "Mint leaves", qty: 10, unit: "leaves", role: "flavour" },
      { label: "Ice cubes", qty: 5, unit: "cubes", role: "base" },
    ],
    method:
      "Blend 1 peeled cucumber with the mint and strain firmly through a sieve to get about 120 ml of juice. Stir in lemon and sugar syrup, pour over ice and top with soda. Peeling matters here — the skin is what turns it bitter.",
  },
  {
    id: "ginger-lemon-fizz",
    name: "Ginger Lemon Fizz",
    glass: "Highball",
    garnish: "Lemon wheel and candied ginger",
    occasions: ["summer", "party"],
    sweetness: 2,
    tang: 3,
    need: ["ginger", "lemon", "soda", "sugar-syrup"],
    optional: ["mint", "black-pepper", "honey"],
    pour: [
      { label: "Chilled club soda", ml: 150, role: "fizz" },
      { label: "Lemon juice", ml: 20, role: "sour" },
      { label: "Sugar syrup", ml: 20, role: "sweet" },
      { label: "Fresh ginger juice", ml: 15, role: "flavour" },
    ],
    add: [{ label: "Ice cubes", qty: 6, unit: "cubes", role: "base" }],
    method:
      "Grate a 4 cm piece of ginger and squeeze it in your fist to get about 15 ml of juice; never blend it, or the drink turns cloudy and fibrous. Stir the ginger juice with lemon and syrup, add ice and top with soda.",
  },
  {
    id: "rose-sharbat",
    name: "Rose Sharbat",
    glass: "Tall tumbler",
    garnish: "Rose petal",
    occasions: ["summer", "kids", "party"],
    sweetness: 3,
    tang: 1,
    need: ["rose-syrup"],
    optional: ["lemon", "soda", "mint", "basil", "milk"],
    pour: [
      { label: "Chilled water", ml: 180, role: "base" },
      { label: "Rose syrup", ml: 30, role: "sweet" },
    ],
    add: [
      { label: "Soaked basil (sabja) seeds", qty: 1, unit: "tsp", role: "flavour" },
      { label: "Ice cubes", qty: 6, unit: "cubes", role: "base" },
    ],
    method:
      "Soak the basil seeds in 3 tbsp water for 10 minutes until each one grows a clear jelly coat. Stir the rose syrup into chilled water, add the seeds and ice. A 1:6 syrup-to-water ratio is the sweet spot — most people pour far more syrup than they need.",
  },
  {
    id: "khus-cooler",
    name: "Khus Cooler",
    glass: "Tall tumbler",
    garnish: "Mint sprig and a lemon wheel",
    occasions: ["summer", "kids"],
    sweetness: 3,
    tang: 1,
    need: ["khus-syrup"],
    optional: ["lemon", "soda", "mint"],
    pour: [
      { label: "Chilled water", ml: 170, role: "base" },
      { label: "Khus syrup", ml: 30, role: "sweet" },
      { label: "Lemon juice", ml: 10, role: "sour" },
    ],
    add: [{ label: "Ice cubes", qty: 6, unit: "cubes", role: "base" }],
    method:
      "Stir khus syrup into chilled water and add just a squeeze of lemon — without it the drink is flat and perfumey. Pour over a tall glass of ice. Swapping half the water for soda turns it into a khus fizz.",
  },
  {
    id: "blue-lagoon",
    name: "Blue Lagoon",
    glass: "Hurricane",
    garnish: "Lemon wheel and a cherry",
    occasions: ["party", "kids"],
    sweetness: 3,
    tang: 2,
    need: ["blue-curacao", "lemon", "lemon-soda"],
    optional: ["mint", "sugar-syrup", "soda"],
    pour: [
      { label: "Chilled lemon-lime soda", ml: 150, role: "fizz" },
      { label: "Blue curacao syrup", ml: 30, role: "sweet" },
      { label: "Lemon juice", ml: 20, role: "sour" },
    ],
    add: [{ label: "Ice cubes", qty: 8, unit: "cubes", role: "base" }],
    method:
      "Fill the glass to the brim with ice, pour the blue curacao over it, then add lemon juice. Top with lemon-lime soda poured slowly and do not stir — the syrup settles low and gives you the lagoon gradient. Stirring turns the whole thing a flat teal.",
  },
  {
    id: "virgin-pina-colada",
    name: "Virgin Pina Colada",
    glass: "Hurricane",
    garnish: "Pineapple wedge and a cherry",
    occasions: ["party", "kids"],
    sweetness: 3,
    tang: 2,
    need: ["pineapple-juice", "coconut-milk"],
    optional: ["pineapple", "sugar-syrup", "ice-cream", "cream", "lemon"],
    pour: [
      { label: "Pineapple juice", ml: 120, role: "base" },
      { label: "Coconut milk", ml: 60, role: "creamy" },
      { label: "Sugar syrup", ml: 15, role: "sweet" },
    ],
    add: [{ label: "Crushed ice", qty: 1, unit: "cup", role: "base" }],
    method:
      "Blend everything with the crushed ice for 30 seconds until it is thick enough to hold a straw upright. Use full-fat coconut milk, not coconut water — the fat is what makes it creamy rather than icy. A scoop of vanilla ice cream makes it a dessert.",
  },
  {
    id: "shirley-temple",
    name: "Shirley Temple",
    glass: "Highball",
    garnish: "Cherry and an orange slice",
    occasions: ["kids", "party"],
    sweetness: 3,
    tang: 1,
    need: ["grenadine", "lemon-soda"],
    optional: ["orange", "lemon", "ginger-ale"],
    pour: [
      { label: "Chilled lemon-lime soda", ml: 180, role: "fizz" },
      { label: "Grenadine", ml: 20, role: "sweet" },
    ],
    add: [{ label: "Ice cubes", qty: 6, unit: "cubes", role: "base" }],
    method:
      "Fill the glass with ice and pour the soda first. Trickle the grenadine down the inside wall last and let it sink on its own into a red base. Half ginger ale and half lemon-lime soda gives it a little more bite for adults.",
  },
  {
    id: "virgin-sunrise",
    name: "Virgin Sunrise",
    glass: "Hurricane",
    garnish: "Orange wheel and a cherry",
    occasions: ["party", "kids"],
    sweetness: 3,
    tang: 2,
    need: ["orange-juice", "grenadine"],
    optional: ["lemon", "soda", "orange", "pineapple-juice"],
    pour: [
      { label: "Orange juice", ml: 170, role: "base" },
      { label: "Grenadine", ml: 20, role: "sweet" },
      { label: "Lemon juice", ml: 10, role: "sour" },
    ],
    add: [{ label: "Ice cubes", qty: 8, unit: "cubes", role: "base" }],
    method:
      "Fill the glass with ice, pour in the orange juice and lemon, and stir. Pour the grenadine down the side very slowly and leave it alone — being heavier with sugar, it sinks and bleeds upward into the sunrise. Never stir after the grenadine goes in.",
  },
  {
    id: "cranberry-spritzer",
    name: "Cranberry Spritzer",
    glass: "Highball",
    garnish: "Lime wheel",
    occasions: ["summer", "party"],
    sweetness: 2,
    tang: 3,
    need: ["cranberry-juice", "soda"],
    optional: ["lemon", "mint", "orange", "sugar-syrup"],
    pour: [
      { label: "Cranberry juice", ml: 120, role: "base" },
      { label: "Chilled club soda", ml: 80, role: "fizz" },
      { label: "Lemon juice", ml: 10, role: "sour" },
    ],
    add: [{ label: "Ice cubes", qty: 6, unit: "cubes", role: "base" }],
    method:
      "Pour cranberry juice and lemon over a full glass of ice, then top with soda. The 3:2 juice-to-soda ratio keeps the tartness intact instead of watering it down. Add 10 ml sugar syrup if your cranberry juice is the unsweetened kind.",
  },
  {
    id: "virgin-cosmo",
    name: "Virgin Cosmopolitan",
    glass: "Martini",
    garnish: "Orange twist",
    occasions: ["party"],
    sweetness: 2,
    tang: 3,
    need: ["cranberry-juice", "lemon", "sugar-syrup"],
    optional: ["orange-juice", "litchi-juice", "orange"],
    pour: [
      { label: "Cranberry juice", ml: 90, role: "base" },
      { label: "Orange juice", ml: 30, role: "base" },
      { label: "Lemon juice", ml: 20, role: "sour" },
      { label: "Sugar syrup", ml: 10, role: "sweet" },
    ],
    add: [{ label: "Ice cubes, for shaking", qty: 8, unit: "cubes", role: "base" }],
    method:
      "Shake everything hard with ice for a full 15 seconds — the drink should be painfully cold and the shaker frosted. Double-strain into a chilled martini glass so no ice chips get through. Twist a strip of orange peel over the surface to spray the oils, then drop it in.",
  },
  {
    id: "virgin-sangria",
    name: "Virgin Sangria",
    glass: "Wine glass",
    garnish: "Orange wheel",
    occasions: ["party"],
    sweetness: 2,
    tang: 2,
    need: ["grape-juice", "apple-juice", "orange"],
    optional: ["green-apple", "orange-juice", "soda", "cinnamon", "lemon"],
    pour: [
      { label: "Red grape juice", ml: 120, role: "base" },
      { label: "Apple juice", ml: 50, role: "base" },
      { label: "Chilled club soda", ml: 40, role: "fizz" },
      { label: "Lemon juice", ml: 10, role: "sour" },
    ],
    add: [
      { label: "Orange slices", qty: 2, unit: "slices", role: "flavour" },
      { label: "Green apple cubes", qty: 6, unit: "cubes", role: "flavour" },
      { label: "Cinnamon stick", qty: 1, unit: "stick", role: "flavour" },
    ],
    method:
      "Steep the fruit and cinnamon in the grape and apple juice in the fridge for at least 4 hours — this drink is entirely about the infusion, so making it to order is pointless. Add the soda only when you serve, or the whole jug goes flat.",
  },
  {
    id: "fruit-punch",
    name: "Fruit Punch",
    glass: "Punch cup",
    garnish: "Floating orange wheels",
    occasions: ["party", "kids"],
    sweetness: 3,
    tang: 2,
    need: ["orange-juice", "pineapple-juice", "cranberry-juice", "lemon-soda"],
    optional: ["grenadine", "orange", "strawberry", "mint", "lemon"],
    pour: [
      { label: "Orange juice", ml: 80, role: "base" },
      { label: "Pineapple juice", ml: 60, role: "base" },
      { label: "Cranberry juice", ml: 60, role: "base" },
      { label: "Chilled lemon-lime soda", ml: 60, role: "fizz" },
    ],
    add: [
      { label: "Orange slices", qty: 2, unit: "slices", role: "flavour" },
      { label: "Ice cubes", qty: 8, unit: "cubes", role: "base" },
    ],
    method:
      "Mix all three juices in the jug and chill thoroughly — never build a punch over ice, as it melts and dilutes within minutes. Add the soda and floating fruit right before guests arrive. Freeze some of the juice into cubes to chill it without weakening it.",
  },
  {
    id: "pineapple-punch",
    name: "Pineapple Punch",
    glass: "Hurricane",
    garnish: "Pineapple wedge and a cherry",
    occasions: ["party", "kids"],
    sweetness: 3,
    tang: 2,
    need: ["pineapple-juice", "orange-juice", "lemon"],
    optional: ["grenadine", "soda", "pineapple", "mint"],
    pour: [
      { label: "Pineapple juice", ml: 100, role: "base" },
      { label: "Orange juice", ml: 60, role: "base" },
      { label: "Chilled club soda", ml: 40, role: "fizz" },
      { label: "Lemon juice", ml: 15, role: "sour" },
      { label: "Grenadine", ml: 10, role: "sweet" },
    ],
    add: [{ label: "Ice cubes", qty: 6, unit: "cubes", role: "base" }],
    method:
      "Shake the juices with ice for 10 seconds so the pineapple juice froths up into a head. Pour into a glass of fresh ice, top with soda and drop the grenadine in last. That pineapple foam is the whole point, so do not skip the shake.",
  },
  {
    id: "litchi-cooler",
    name: "Litchi Cooler",
    glass: "Highball",
    garnish: "Litchi on a pick and a mint sprig",
    occasions: ["summer", "party", "kids"],
    sweetness: 3,
    tang: 2,
    need: ["litchi-juice", "lemon", "soda"],
    optional: ["mint", "sugar-syrup", "basil", "lemon-soda"],
    pour: [
      { label: "Litchi juice", ml: 120, role: "base" },
      { label: "Chilled club soda", ml: 70, role: "fizz" },
      { label: "Lemon juice", ml: 15, role: "sour" },
    ],
    add: [
      { label: "Mint leaves", qty: 6, unit: "leaves", role: "flavour" },
      { label: "Ice cubes", qty: 6, unit: "cubes", role: "base" },
    ],
    method:
      "Slap the mint leaves between your palms once and drop them into the glass — that wakes the oils without tearing them. Add litchi juice, lemon and ice, and top with soda. Litchi is very sweet on its own, so the lemon is doing real work here.",
  },
  {
    id: "green-apple-mojito",
    name: "Green Apple Mojito",
    glass: "Highball",
    garnish: "Green apple fan and mint",
    occasions: ["summer", "party"],
    sweetness: 2,
    tang: 3,
    need: ["green-apple", "lemon", "mint", "soda"],
    optional: ["sugar-syrup", "apple-juice", "blue-curacao"],
    pour: [
      { label: "Chilled club soda", ml: 130, role: "fizz" },
      { label: "Apple juice", ml: 40, role: "base" },
      { label: "Lemon juice", ml: 20, role: "sour" },
      { label: "Sugar syrup", ml: 15, role: "sweet" },
    ],
    add: [
      { label: "Mint leaves", qty: 10, unit: "leaves", role: "flavour" },
      { label: "Green apple cubes", qty: 6, unit: "cubes", role: "flavour" },
      { label: "Crushed ice", qty: 1, unit: "cup", role: "base" },
    ],
    method:
      "Muddle the apple cubes and mint gently with the lemon juice and sugar syrup — press, do not pulverise. Fill with crushed ice, add apple juice and top with soda. Toss the cut apple in a little lemon juice first so it does not brown in the glass.",
  },
  {
    id: "pomegranate-fizz",
    name: "Pomegranate Fizz",
    glass: "Highball",
    garnish: "Pomegranate pearls and a mint sprig",
    occasions: ["party", "summer"],
    sweetness: 2,
    tang: 3,
    need: ["pomegranate", "soda", "lemon"],
    optional: ["mint", "sugar-syrup", "black-salt", "grenadine"],
    pour: [
      { label: "Fresh pomegranate juice", ml: 100, role: "base" },
      { label: "Chilled club soda", ml: 90, role: "fizz" },
      { label: "Lemon juice", ml: 15, role: "sour" },
      { label: "Sugar syrup", ml: 10, role: "sweet" },
    ],
    add: [
      { label: "Pomegranate pearls", qty: 2, unit: "tbsp", role: "flavour" },
      { label: "Ice cubes", qty: 6, unit: "cubes", role: "base" },
    ],
    method:
      "Blend the pearls of 1 pomegranate for 10 seconds only and strain — go longer and the crushed seeds make it bitter and astringent. One fruit gives about 100 ml. Add lemon and syrup, ice, and top with soda.",
  },
  {
    id: "kiwi-crush",
    name: "Kiwi Crush",
    glass: "Highball",
    garnish: "Kiwi wheel on the rim",
    occasions: ["summer", "party"],
    sweetness: 2,
    tang: 3,
    need: ["kiwi", "lemon", "sugar-syrup"],
    optional: ["soda", "mint", "lemon-soda", "black-salt"],
    pour: [
      { label: "Chilled lemon-lime soda", ml: 130, role: "fizz" },
      { label: "Sugar syrup", ml: 20, role: "sweet" },
      { label: "Lemon juice", ml: 15, role: "sour" },
    ],
    add: [
      { label: "Kiwi, peeled", qty: 1.5, unit: "pieces", role: "base" },
      { label: "Mint leaves", qty: 6, unit: "leaves", role: "flavour" },
      { label: "Crushed ice", qty: 1, unit: "cup", role: "base" },
    ],
    method:
      "Muddle the kiwi with mint, lemon and sugar syrup at the bottom of the glass into a rough pulp. Pack with crushed ice and top with lemon-lime soda. Leave the black seeds in — they are what make it look like a bar crush.",
  },
  {
    id: "mosambi-soda",
    name: "Mosambi Soda",
    glass: "Tall tumbler",
    garnish: "Lemon wheel",
    occasions: ["summer", "party"],
    sweetness: 1,
    tang: 3,
    need: ["mosambi-juice", "soda", "black-salt"],
    optional: ["lemon", "sugar", "roasted-cumin", "mint"],
    pour: [
      { label: "Fresh mosambi juice", ml: 140, role: "base" },
      { label: "Chilled club soda", ml: 60, role: "fizz" },
      { label: "Lemon juice", ml: 10, role: "sour" },
    ],
    add: [
      { label: "Black salt", qty: 0.25, unit: "tsp", role: "flavour" },
      { label: "Sugar", qty: 1, unit: "tsp", role: "sweet" },
      { label: "Ice cubes", qty: 5, unit: "cubes", role: "base" },
    ],
    method:
      "Squeeze the mosambi gently and stop before you reach the pith — over-pressing is what makes fresh sweet lime juice bitter. Stir in black salt and sugar, add ice and top with soda. Drink it within 10 minutes; it turns bitter as it sits.",
  },
  {
    id: "coconut-lime",
    name: "Coconut Water Lime",
    glass: "Highball",
    garnish: "Lime wheel and a mint sprig",
    occasions: ["summer", "kids"],
    sweetness: 1,
    tang: 2,
    need: ["coconut-water", "lemon"],
    optional: ["mint", "honey", "black-salt", "cucumber"],
    pour: [
      { label: "Chilled tender coconut water", ml: 200, role: "base" },
      { label: "Lemon juice", ml: 15, role: "sour" },
      { label: "Honey", ml: 10, role: "sweet" },
    ],
    add: [
      { label: "Mint leaves", qty: 6, unit: "leaves", role: "flavour" },
      { label: "Ice cubes", qty: 4, unit: "cubes", role: "base" },
    ],
    method:
      "Stir the honey into the lemon juice first — dropped straight into cold coconut water it just sinks and stays there. Add coconut water, mint and ice. Barely-there ice is best; coconut water is delicate and drowns easily.",
  },
  {
    id: "virgin-bloody-mary",
    name: "Virgin Bloody Mary",
    glass: "Highball",
    garnish: "Cucumber spear and a lemon wedge",
    occasions: ["party"],
    sweetness: 1,
    tang: 3,
    need: ["tomato-juice", "lemon", "black-pepper"],
    optional: ["black-salt", "green-chilli", "chaat-masala", "cucumber"],
    pour: [
      { label: "Chilled tomato juice", ml: 180, role: "base" },
      { label: "Lemon juice", ml: 20, role: "sour" },
    ],
    add: [
      { label: "Black pepper", qty: 0.25, unit: "tsp", role: "flavour" },
      { label: "Black salt", qty: 0.25, unit: "tsp", role: "flavour" },
      { label: "Green chilli, slit", qty: 0.5, unit: "pieces", role: "flavour" },
      { label: "Ice cubes", qty: 6, unit: "cubes", role: "base" },
    ],
    method:
      "Roll the drink between two glasses six or seven times instead of shaking it — shaking makes tomato juice froth and go thin. Season heavily with pepper and black salt, and let the slit chilli sit in the glass for two minutes before you serve.",
  },
  {
    id: "masala-cola",
    name: "Masala Cola",
    glass: "Tall tumbler",
    garnish: "Lemon wedge",
    occasions: ["party", "summer"],
    sweetness: 3,
    tang: 2,
    need: ["cola", "lemon", "chaat-masala"],
    optional: ["black-salt", "roasted-cumin", "ginger", "black-pepper"],
    pour: [
      { label: "Chilled cola", ml: 180, role: "fizz" },
      { label: "Lemon juice", ml: 15, role: "sour" },
    ],
    add: [
      { label: "Chaat masala", qty: 0.5, unit: "tsp", role: "flavour" },
      { label: "Roasted cumin powder", qty: 0.25, unit: "tsp", role: "flavour" },
      { label: "Ice cubes", qty: 5, unit: "cubes", role: "base" },
    ],
    method:
      "Put the lemon juice and masala in the glass first and stir them into a paste. Add ice, then pour the cola slowly — tipping masala into full cola triggers an eruption. Stir once from the bottom and serve immediately.",
  },
  {
    id: "ginger-tonic",
    name: "Ginger Cucumber Tonic",
    glass: "Copa balloon",
    garnish: "Cucumber ribbon and a lime wheel",
    occasions: ["party"],
    sweetness: 1,
    tang: 2,
    need: ["tonic-water", "ginger", "lemon"],
    optional: ["mint", "honey", "cucumber", "basil"],
    pour: [
      { label: "Chilled tonic water", ml: 150, role: "fizz" },
      { label: "Lemon juice", ml: 15, role: "sour" },
      { label: "Fresh ginger juice", ml: 15, role: "flavour" },
      { label: "Honey", ml: 10, role: "sweet" },
    ],
    add: [{ label: "Ice cubes", qty: 8, unit: "cubes", role: "base" }],
    method:
      "Fill the balloon glass right to the top with ice — a half-empty glass melts fast and goes watery. Add ginger juice, lemon and honey, stir, then pour the tonic over the back of a spoon to keep the bubbles. Tonic's quinine bitterness is what makes this taste grown-up.",
  },
  {
    id: "virgin-mule",
    name: "Virgin Mule",
    glass: "Copper mug",
    garnish: "Mint bouquet and a lime wedge",
    occasions: ["party", "summer"],
    sweetness: 2,
    tang: 3,
    need: ["ginger-ale", "lemon", "mint"],
    optional: ["cucumber", "sugar-syrup", "ginger"],
    pour: [
      { label: "Chilled ginger ale", ml: 160, role: "fizz" },
      { label: "Lemon juice", ml: 20, role: "sour" },
      { label: "Fresh ginger juice", ml: 10, role: "flavour" },
    ],
    add: [
      { label: "Mint leaves", qty: 8, unit: "leaves", role: "flavour" },
      { label: "Crushed ice", qty: 1, unit: "cup", role: "base" },
    ],
    method:
      "Add lemon juice and fresh ginger juice to the mug, pack it with crushed ice and top with ginger ale. The extra fresh ginger is what saves this from tasting like plain soft drink. A copper mug is not a gimmick — it frosts and keeps it colder for longer.",
  },
  {
    id: "basil-lemonade",
    name: "Basil Lemonade",
    glass: "Highball",
    garnish: "Basil sprig",
    occasions: ["summer", "party"],
    sweetness: 2,
    tang: 3,
    need: ["basil", "lemon", "sugar-syrup"],
    optional: ["soda", "mint", "cucumber", "black-salt"],
    pour: [
      { label: "Chilled water", ml: 140, role: "base" },
      { label: "Chilled club soda", ml: 40, role: "fizz" },
      { label: "Lemon juice", ml: 25, role: "sour" },
      { label: "Sugar syrup", ml: 20, role: "sweet" },
    ],
    add: [
      { label: "Basil leaves", qty: 8, unit: "leaves", role: "flavour" },
      { label: "Ice cubes", qty: 6, unit: "cubes", role: "base" },
    ],
    method:
      "Muddle the basil in the sugar syrup alone for 10 seconds — the sugar crystals scrub the leaves and pull the oils out. Add lemon and water, strain over ice and top with soda. Basil browns quickly once bruised, so make this to order.",
  },
  {
    id: "grape-fizz",
    name: "Grape Fizz",
    glass: "Highball",
    garnish: "Frozen grapes on a pick",
    occasions: ["party", "kids", "summer"],
    sweetness: 2,
    tang: 2,
    need: ["grape-juice", "soda", "lemon"],
    optional: ["mint", "sugar-syrup", "black-salt"],
    pour: [
      { label: "Grape juice", ml: 120, role: "base" },
      { label: "Chilled club soda", ml: 70, role: "fizz" },
      { label: "Lemon juice", ml: 15, role: "sour" },
    ],
    add: [
      { label: "Mint leaves", qty: 5, unit: "leaves", role: "flavour" },
      { label: "Ice cubes", qty: 6, unit: "cubes", role: "base" },
    ],
    method:
      "Use frozen grapes instead of ice cubes and the drink chills without ever thinning out. Pour grape juice and lemon over them, then top with soda. Black grape juice makes a far better-looking drink than green.",
  },
  {
    id: "strawberry-lemonade",
    name: "Strawberry Lemonade",
    glass: "Mason jar",
    garnish: "Strawberry slice and mint",
    occasions: ["summer", "kids", "party"],
    sweetness: 2,
    tang: 3,
    need: ["strawberry", "lemon", "sugar-syrup"],
    optional: ["soda", "mint", "basil", "lemon-soda"],
    pour: [
      { label: "Chilled water", ml: 120, role: "base" },
      { label: "Chilled club soda", ml: 40, role: "fizz" },
      { label: "Lemon juice", ml: 25, role: "sour" },
      { label: "Sugar syrup", ml: 25, role: "sweet" },
    ],
    add: [
      { label: "Strawberries, hulled", qty: 5, unit: "pieces", role: "base" },
      { label: "Mint leaves", qty: 5, unit: "leaves", role: "flavour" },
      { label: "Ice cubes", qty: 6, unit: "cubes", role: "base" },
    ],
    method:
      "Crush the strawberries with the sugar syrup and let them macerate for 10 minutes until they weep out their juice and colour. Add lemon and water, pour over ice and top with soda. Straining is optional — leaving the pulp in makes it taste homemade.",
  },
  {
    id: "muskmelon-cooler",
    name: "Muskmelon Cooler",
    glass: "Highball",
    garnish: "Melon ball on a pick",
    occasions: ["summer", "kids"],
    sweetness: 2,
    tang: 1,
    need: ["muskmelon", "lemon", "sugar-syrup"],
    optional: ["mint", "milk", "soda", "black-salt"],
    pour: [
      { label: "Muskmelon puree", ml: 160, role: "base" },
      { label: "Chilled water", ml: 40, role: "base" },
      { label: "Sugar syrup", ml: 15, role: "sweet" },
      { label: "Lemon juice", ml: 10, role: "sour" },
    ],
    add: [
      { label: "Mint leaves", qty: 5, unit: "leaves", role: "flavour" },
      { label: "Ice cubes", qty: 5, unit: "cubes", role: "base" },
    ],
    method:
      "Blend about 300 g of deseeded muskmelon into a smooth puree — no need to strain, the pulp is what gives it body. Add lemon and syrup, thin with water to taste, and serve very cold. Muskmelon is mild, so it needs the lemon to register at all.",
  },
  {
    id: "spiced-apple-punch",
    name: "Spiced Apple Punch",
    glass: "Wine glass",
    garnish: "Cinnamon stick and an apple fan",
    occasions: ["party"],
    sweetness: 3,
    tang: 1,
    need: ["apple-juice", "cinnamon", "lemon"],
    optional: ["orange", "ginger", "honey", "soda", "green-apple"],
    pour: [
      { label: "Apple juice", ml: 160, role: "base" },
      { label: "Chilled club soda", ml: 40, role: "fizz" },
      { label: "Lemon juice", ml: 10, role: "sour" },
    ],
    add: [
      { label: "Cinnamon stick", qty: 1, unit: "stick", role: "flavour" },
      { label: "Orange slices", qty: 1, unit: "slices", role: "flavour" },
      { label: "Ice cubes", qty: 6, unit: "cubes", role: "base" },
    ],
    method:
      "Warm the apple juice with the cinnamon and orange for 5 minutes to open the spice, then chill it fully — this brief heat is what separates it from plain juice. Add lemon, pour over ice and top with soda.",
  },
  {
    id: "mango-lassi",
    name: "Mango Lassi",
    glass: "Tall tumbler",
    garnish: "Chopped pistachio and a mango cube",
    occasions: ["summer", "kids"],
    sweetness: 3,
    tang: 2,
    need: ["mango-pulp", "curd", "sugar"],
    optional: ["milk", "cardamom", "honey", "ice-cream"],
    pour: [
      { label: "Thick curd", ml: 120, role: "creamy" },
      { label: "Mango pulp", ml: 120, role: "base" },
      { label: "Chilled milk", ml: 40, role: "creamy" },
    ],
    add: [
      { label: "Sugar", qty: 2, unit: "tsp", role: "sweet" },
      { label: "Cardamom powder", qty: 0.25, unit: "tsp", role: "flavour" },
      { label: "Ice cubes", qty: 4, unit: "cubes", role: "base" },
    ],
    method:
      "Blend curd, mango pulp, milk and sugar for 40 seconds until it is completely smooth and slightly aerated. Use hung or Greek-style curd if you have it — thin curd gives you a mango drink, not a lassi. Finish with cardamom and serve cold, not iced.",
  },
  {
    id: "sweet-lassi",
    name: "Sweet Lassi",
    glass: "Kulhad or tall tumbler",
    garnish: "A dollop of cream and crushed pistachio",
    occasions: ["summer", "kids"],
    sweetness: 3,
    tang: 2,
    need: ["curd", "sugar"],
    optional: ["milk", "cardamom", "rose-syrup", "cream"],
    pour: [
      { label: "Thick curd", ml: 150, role: "creamy" },
      { label: "Chilled water", ml: 60, role: "base" },
    ],
    add: [
      { label: "Sugar", qty: 2.5, unit: "tsp", role: "sweet" },
      { label: "Cardamom powder", qty: 0.25, unit: "tsp", role: "flavour" },
      { label: "Ice cubes", qty: 4, unit: "cubes", role: "base" },
    ],
    method:
      "Whisk the curd and sugar hard on their own for a full minute until a light foam forms on top, then thin it with the water. The foam is the whole difference between lassi and sweetened curd. Chill the glass and pour it in tall.",
  },
  {
    id: "masala-chaas",
    name: "Masala Chaas",
    glass: "Tall tumbler",
    garnish: "Mint sprig and a dusting of cumin",
    occasions: ["summer"],
    sweetness: 1,
    tang: 2,
    need: ["curd", "black-salt", "roasted-cumin"],
    optional: ["mint", "ginger", "green-chilli", "black-pepper"],
    pour: [
      { label: "Thin curd", ml: 100, role: "creamy" },
      { label: "Chilled water", ml: 140, role: "base" },
    ],
    add: [
      { label: "Black salt", qty: 0.5, unit: "tsp", role: "flavour" },
      { label: "Roasted cumin powder", qty: 0.5, unit: "tsp", role: "flavour" },
      { label: "Mint leaves", qty: 8, unit: "leaves", role: "flavour" },
      { label: "Green chilli, slit", qty: 0.5, unit: "pieces", role: "flavour" },
    ],
    method:
      "Blend the curd with the water, mint, chilli and ginger for 20 seconds, then strain out the solids. Chaas should be thin enough to drink in gulps, roughly 1 part curd to 1.5 parts water. Season it aggressively — it should taste almost too salty at room temperature and just right when cold.",
  },
  {
    id: "rose-milk",
    name: "Rose Milk",
    glass: "Tall tumbler",
    garnish: "Rose petal and chopped nuts",
    occasions: ["kids", "summer"],
    sweetness: 3,
    tang: 1,
    need: ["rose-syrup", "milk"],
    optional: ["ice-cream", "sugar", "cardamom", "condensed-milk"],
    pour: [
      { label: "Chilled full-fat milk", ml: 180, role: "creamy" },
      { label: "Rose syrup", ml: 30, role: "sweet" },
    ],
    add: [{ label: "Ice cubes", qty: 5, unit: "cubes", role: "base" }],
    method:
      "Pour the rose syrup into the glass first, then add the cold milk in a thin stream from height so it marbles pink through white. Stir only if you want it uniform. The milk must be properly cold — lukewarm milk and rose syrup taste cloying.",
  },
  {
    id: "cold-coffee",
    name: "Cold Coffee",
    glass: "Tall tumbler",
    garnish: "Cocoa dust and a swirl of cream",
    occasions: ["party", "kids"],
    sweetness: 2,
    tang: 1,
    need: ["instant-coffee", "milk", "sugar"],
    optional: ["ice-cream", "chocolate-syrup", "cream", "cocoa"],
    pour: [
      { label: "Chilled full-fat milk", ml: 200, role: "creamy" },
      { label: "Coffee decoction", ml: 30, role: "flavour" },
    ],
    add: [
      { label: "Instant coffee", qty: 1.5, unit: "tsp", role: "flavour" },
      { label: "Sugar", qty: 2, unit: "tsp", role: "sweet" },
      { label: "Vanilla ice cream", qty: 1, unit: "scoop", role: "creamy" },
      { label: "Ice cubes", qty: 5, unit: "cubes", role: "base" },
    ],
    method:
      "Dissolve the instant coffee and sugar in 30 ml of hot water to make a decoction and let it cool — coffee granules never dissolve properly in cold milk. Blend with the milk, ice and ice cream for 45 seconds until a thick collar of froth forms. Pour straight away.",
  },
  {
    id: "chocolate-shake",
    name: "Chocolate Shake",
    glass: "Tall tumbler",
    garnish: "Whipped cream and a chocolate drizzle",
    occasions: ["kids", "party"],
    sweetness: 3,
    tang: 1,
    need: ["milk", "chocolate-syrup"],
    optional: ["ice-cream", "cocoa", "sugar", "cream", "vanilla-essence"],
    pour: [
      { label: "Chilled milk", ml: 200, role: "creamy" },
      { label: "Chocolate syrup", ml: 30, role: "sweet" },
    ],
    add: [
      { label: "Vanilla ice cream", qty: 1, unit: "scoop", role: "creamy" },
      { label: "Cocoa powder", qty: 0.5, unit: "tsp", role: "flavour" },
      { label: "Ice cubes", qty: 4, unit: "cubes", role: "base" },
    ],
    method:
      "Blend the milk, syrup, ice cream and cocoa for 30 seconds — the extra spoon of cocoa is what stops it tasting like sugar and gives it real chocolate depth. Streak the inside of the glass with chocolate syrup before pouring.",
  },
  {
    id: "mango-shake",
    name: "Mango Milkshake",
    glass: "Tall tumbler",
    garnish: "Mango cubes and mint",
    occasions: ["kids", "summer"],
    sweetness: 3,
    tang: 1,
    need: ["mango-pulp", "milk", "sugar"],
    optional: ["ice-cream", "cardamom", "honey", "cream"],
    pour: [
      { label: "Chilled milk", ml: 150, role: "creamy" },
      { label: "Mango pulp", ml: 100, role: "base" },
    ],
    add: [
      { label: "Sugar", qty: 1.5, unit: "tsp", role: "sweet" },
      { label: "Vanilla ice cream", qty: 1, unit: "scoop", role: "creamy" },
      { label: "Ice cubes", qty: 3, unit: "cubes", role: "base" },
    ],
    method:
      "Blend the mango pulp with the sugar first, then add cold milk and pulse briefly — over-blending milk makes it thin and foamy rather than thick. Taste before sweetening further, as ripe mango carries most of the sugar already.",
  },
  {
    id: "banana-shake",
    name: "Banana Milkshake",
    glass: "Tall tumbler",
    garnish: "Banana coin and a dusting of cinnamon",
    occasions: ["kids"],
    sweetness: 3,
    tang: 1,
    need: ["banana", "milk", "sugar"],
    optional: ["ice-cream", "honey", "cardamom", "cocoa"],
    pour: [{ label: "Chilled milk", ml: 180, role: "creamy" }],
    add: [
      { label: "Ripe banana", qty: 1, unit: "pieces", role: "base" },
      { label: "Sugar", qty: 1.5, unit: "tsp", role: "sweet" },
      { label: "Vanilla ice cream", qty: 1, unit: "scoop", role: "creamy" },
      { label: "Ice cubes", qty: 3, unit: "cubes", role: "base" },
    ],
    method:
      "Use a banana with brown-freckled skin — an underripe one tastes chalky no matter how much sugar you add. Blend with cold milk for 20 seconds only. Freeze the banana in chunks beforehand and you can skip the ice entirely.",
  },
  {
    id: "strawberry-shake",
    name: "Strawberry Milkshake",
    glass: "Tall tumbler",
    garnish: "Half a strawberry on the rim",
    occasions: ["kids"],
    sweetness: 3,
    tang: 2,
    need: ["strawberry", "milk", "sugar"],
    optional: ["ice-cream", "cream", "vanilla-essence", "honey"],
    pour: [{ label: "Chilled milk", ml: 170, role: "creamy" }],
    add: [
      { label: "Strawberries, hulled", qty: 6, unit: "pieces", role: "base" },
      { label: "Sugar", qty: 2, unit: "tsp", role: "sweet" },
      { label: "Vanilla ice cream", qty: 1, unit: "scoop", role: "creamy" },
    ],
    method:
      "Blend the strawberries with the sugar and a few drops of vanilla into a puree before the milk goes anywhere near — this draws the colour out and turns the shake properly pink instead of grey. Add cold milk and ice cream and pulse to combine.",
  },
  {
    id: "choco-banana-smoothie",
    name: "Chocolate Banana Smoothie",
    glass: "Tall tumbler",
    garnish: "Cocoa dust",
    occasions: ["kids"],
    sweetness: 3,
    tang: 1,
    need: ["banana", "milk", "cocoa"],
    optional: ["honey", "ice-cream", "chocolate-syrup", "curd"],
    pour: [
      { label: "Chilled milk", ml: 180, role: "creamy" },
      { label: "Honey", ml: 15, role: "sweet" },
    ],
    add: [
      { label: "Ripe banana, frozen", qty: 1, unit: "pieces", role: "base" },
      { label: "Cocoa powder", qty: 1, unit: "tbsp", role: "flavour" },
      { label: "Ice cubes", qty: 4, unit: "cubes", role: "base" },
    ],
    method:
      "Freeze the banana in coins overnight and skip most of the ice — frozen fruit gives a thick smoothie, while ice just gives you a watery one. Blend everything for 40 seconds. Sift the cocoa in, or it will bob around in lumps.",
  },
  {
    id: "fruit-curd-smoothie",
    name: "Fruit & Curd Smoothie",
    glass: "Tall tumbler",
    garnish: "A fruit slice on the rim",
    occasions: ["kids", "summer"],
    sweetness: 2,
    tang: 2,
    need: ["curd", "banana", "honey"],
    optional: ["strawberry", "mango-pulp", "milk", "cardamom"],
    pour: [
      { label: "Thick curd", ml: 120, role: "creamy" },
      { label: "Chilled milk", ml: 60, role: "creamy" },
      { label: "Honey", ml: 15, role: "sweet" },
    ],
    add: [
      { label: "Ripe banana", qty: 1, unit: "pieces", role: "base" },
      { label: "Strawberries", qty: 4, unit: "pieces", role: "base" },
      { label: "Ice cubes", qty: 3, unit: "cubes", role: "base" },
    ],
    method:
      "Blend the curd, fruit and honey for 30 seconds, then loosen with milk until it just falls off a spoon. Add the honey after blending and taste first — curd sweetness varies enormously batch to batch.",
  },
];
