export const COMMON_PASSWORDS = [
  "123456", "password", "123456789", "12345678", "12345", "qwerty", "abc123", "111111",
  "1234567", "iloveyou", "admin", "welcome", "monkey", "login", "dragon", "letmein",
  "princess", "football", "baseball", "sunshine", "master", "shadow", "superman", "batman",
  "trustno1", "666666", "123123", "654321", "7777777", "000000", "qazwsx", "1q2w3e4r",
  "qwertyuiop", "zxcvbnm", "asdfgh", "password1", "password123", "pass1234", "hello123", "charlie",
  "michael", "jordan", "harley", "ranger", "hunter", "thomas", "robert", "george",
  "daniel", "andrew", "joshua", "matthew", "jessica", "ashley", "nicole", "hannah",
  "amanda", "maggie", "summer", "winter", "pepper", "ginger", "cookie", "banana",
  "orange", "purple", "flower", "mustang", "corvette", "ferrari", "yamaha", "soccer",
  "hockey", "tennis", "cricket", "killer", "secret", "freedom", "whatever", "computer",
  "internet", "samsung", "google", "pokemon", "starwars", "merlin", "tigger", "buster",
  "access", "matrix", "silver", "golden", "london", "mercedes", "cheese", "biteme",
  "555555", "121212", "112233", "987654321",
];

export const DICTIONARY_WORDS = [
  "forever", "family", "friend", "mother", "father", "sister", "brother", "house",
  "school", "office", "coffee", "chocolate", "diamond", "crystal", "rainbow", "thunder",
  "lightning", "heaven", "peace", "power", "dream", "smile", "heart", "honey",
  "sweet", "sugar", "candy", "pizza", "burger", "butter", "angel", "happy",
  "lucky", "money", "magic", "music", "guitar", "piano", "dance", "chess",
  "basketball", "tiger", "lion", "eagle", "wolf", "panda", "horse", "rabbit",
  "turtle", "dolphin", "yellow", "black", "white", "green", "spring", "autumn",
  "monsoon", "january", "february", "march", "april", "june", "july", "august",
  "september", "october", "november", "december", "monday", "friday", "sunday", "paris",
  "india", "delhi", "mumbai", "chennai", "kolkata", "jaipur", "punjab", "america",
  "england", "canada", "sydney", "tokyo", "david", "anthony", "harry", "potter",
  "james", "kevin", "spiderman", "ninja", "warrior", "knight", "prince", "queen",
  "king", "captain", "doctor", "teacher", "student", "arjun", "rahul", "rohit",
  "aditya", "ankit", "sanjay", "vijay", "suresh", "ramesh", "krishna", "ganesh",
  "shiva", "lakshmi", "priya", "pooja", "sneha", "kavya", "anjali", "simran",
  "laptop", "mobile", "phone", "facebook", "twitter", "instagram", "youtube", "whatsapp",
  "iphone", "windows", "android", "gamer", "pikachu", "naruto", "goku", "mario",
  "zelda", "minecraft", "roblox", "honda", "toyota", "tesla", "mango", "apple",
  "hello", "ocean", "river", "mountain", "forest", "garden", "star", "moon",
  "cloud", "love", "lover", "sunset", "galaxy", "planet", "rocket", "wizard",
];

export const KEYBOARD_ROWS = [
  "qwertyuiop",
  "asdfghjkl",
  "zxcvbnm",
  "1234567890",
  "abcdefghijklmnopqrstuvwxyz",
  "1qaz2wsx3edc",
  "qazwsxedc",
  "zaq1xsw2cde3",
];

export const PASSPHRASE_WORDS = [
  "amber", "anchor", "apron", "arrow", "atlas", "autumn", "badge", "bagel",
  "bamboo", "banner", "basil", "beacon", "berry", "birch", "bishop", "blanket",
  "breeze", "brick", "bronze", "bucket", "cabin", "cactus", "camel", "candle",
  "canoe", "canyon", "carpet", "castle", "cedar", "cellar", "chalk", "cherry",
  "cinema", "circus", "citrus", "clover", "cobalt", "comet", "copper", "coral",
  "cotton", "cradle", "crater", "crimson", "cypress", "daisy", "donkey", "drum",
  "ember", "engine", "falcon", "fable", "feather", "fern", "fiddle", "flint",
  "fossil", "fountain", "garlic", "geyser", "glacier", "goblet", "granite", "grape",
  "hammock", "harbor", "hazel", "helmet", "hickory", "horizon", "iceberg", "igloo",
  "island", "ivory", "jacket", "jasmine", "jigsaw", "jungle", "juniper", "kayak",
  "kettle", "lagoon", "lantern", "laurel", "lemon", "lilac", "lobster", "locket",
  "magnet", "maple", "marble", "meadow", "mellow", "mirror", "mosaic", "mustard",
  "nectar", "nickel", "nutmeg", "oasis", "olive", "onyx", "orbit", "orchid",
  "otter", "oyster", "parade", "parrot", "pebble", "pigeon", "pillow", "plasma",
  "poplar", "prairie", "prism", "pumpkin", "quartz", "quiver", "raven", "ripple",
  "saffron", "sequoia", "sonnet", "sparrow", "thimble", "tundra", "velvet", "walnut",
];
