import { saveAs } from "file-saver";
import jsPDF from "jspdf";

export function exportPDF(analysisA, analysisB, qualityA, qualityB, recommendationsA, recommendationsB) {
  const doc = new jsPDF();
  let y = 20;
  const m = 20;
  const pw = doc.internal.pageSize.getWidth();

  doc.setFontSize(20);
  doc.setTextColor("#14B8A6");
  doc.text("Image Resolution Compare", pw / 2, y, { align: "center" });
  y += 10;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("All image analysis performed locally. Images never leave your device.", pw / 2, y, { align: "center" });
  y += 8;
  doc.text(`Generated: ${new Date().toLocaleString()}`, pw / 2, y, { align: "center" });
  y += 10;

  const addSection = (title) => {
    if (y > 260) { doc.addPage(); y = 20; }
    doc.setFontSize(12);
    doc.setTextColor("#111827");
    doc.text(title, m, y);
    y += 6;
  };

  const addMetric = (label, valA, valB) => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.setFontSize(8);
    doc.setTextColor(80);
    doc.text(`${label}: A=${valA} | B=${valB}`, m + 3, y);
    y += 4.5;
  };

  addSection("Comparison Table");
  if (analysisA && analysisB) {
    addMetric("Width", `${analysisA.width}px`, `${analysisB.width}px`);
    addMetric("Height", `${analysisA.height}px`, `${analysisB.height}px`);
    addMetric("Megapixels", `${analysisA.megapixels}MP`, `${analysisB.megapixels}MP`);
    addMetric("Aspect Ratio", analysisA.aspectRatio, analysisB.aspectRatio);
    addMetric("File Size", formatBytes(analysisA.fileSize), formatBytes(analysisB.fileSize));
    addMetric("Sharpness", `${analysisA.sharpness.toFixed(1)}%`, `${analysisB.sharpness.toFixed(1)}%`);
    addMetric("Noise", `${analysisA.noise.toFixed(1)}%`, `${analysisB.noise.toFixed(1)}%`);
    addMetric("Brightness", `${analysisA.brightness.toFixed(1)}%`, `${analysisB.brightness.toFixed(1)}%`);
    addMetric("Contrast", `${analysisA.contrast.toFixed(1)}%`, `${analysisB.contrast.toFixed(1)}%`);
  }

  y += 4;
  addSection("Quality Scores");
  if (qualityA) {
    doc.setFontSize(8);
    doc.setTextColor("#14B8A6");
    doc.text(`Image A Overall: ${qualityA.overall}/100`, m, y);
    y += 4;
    doc.setTextColor(80);
    doc.text(`Resolution: ${qualityA.resolution} | Sharpness: ${qualityA.sharpness} | Compression: ${qualityA.compression}`, m + 3, y);
    y += 4;
    doc.text(`Noise: ${qualityA.noise} | Color: ${qualityA.colorQuality} | Brightness: ${qualityA.brightness}`, m + 3, y);
    y += 4;
    doc.text(`Contrast: ${qualityA.contrast} | Dynamic Range: ${qualityA.dynamicRange}`, m + 3, y);
    y += 6;
  }
  if (qualityB) {
    doc.setFontSize(8);
    doc.setTextColor("#14B8A6");
    doc.text(`Image B Overall: ${qualityB.overall}/100`, m, y);
    y += 4;
    doc.setTextColor(80);
    doc.text(`Resolution: ${qualityB.resolution} | Sharpness: ${qualityB.sharpness} | Compression: ${qualityB.compression}`, m + 3, y);
    y += 4;
    doc.text(`Noise: ${qualityB.noise} | Color: ${qualityB.colorQuality} | Brightness: ${qualityB.brightness}`, m + 3, y);
    y += 4;
    doc.text(`Contrast: ${qualityB.contrast} | Dynamic Range: ${qualityB.dynamicRange}`, m + 3, y);
  }

  y += 4;
  doc.setFontSize(6);
  doc.setTextColor(180);
  doc.text("Generated by Image Resolution Compare", pw / 2, doc.internal.pageSize.getHeight() - 8, { align: "center" });

  doc.save("image-resolution-comparison-report.pdf");
}

export function exportCSV(analysisA, analysisB) {
  const rows = [
    ["Metric", "Image A", "Image B"],
    ["Width (px)", analysisA?.width || "N/A", analysisB?.width || "N/A"],
    ["Height (px)", analysisA?.height || "N/A", analysisB?.height || "N/A"],
    ["Megapixels", analysisA?.megapixels || "N/A", analysisB?.megapixels || "N/A"],
    ["Aspect Ratio", analysisA?.aspectRatio || "N/A", analysisB?.aspectRatio || "N/A"],
    ["File Size (KB)", analysisA?.fileSize ? (analysisA.fileSize / 1024).toFixed(1) : "N/A", analysisB?.fileSize ? (analysisB.fileSize / 1024).toFixed(1) : "N/A"],
    ["Sharpness (%)", analysisA?.sharpness?.toFixed(1) || "N/A", analysisB?.sharpness?.toFixed(1) || "N/A"],
    ["Noise (%)", analysisA?.noise?.toFixed(1) || "N/A", analysisB?.noise?.toFixed(1) || "N/A"],
    ["Brightness (%)", analysisA?.brightness?.toFixed(1) || "N/A", analysisB?.brightness?.toFixed(1) || "N/A"],
    ["Contrast (%)", analysisA?.contrast?.toFixed(1) || "N/A", analysisB?.contrast?.toFixed(1) || "N/A"],
    ["Saturation (%)", analysisA?.saturation?.toFixed(1) || "N/A", analysisB?.saturation?.toFixed(1) || "N/A"],
    ["Dynamic Range (%)", analysisA?.dynamicRange?.toFixed(1) || "N/A", analysisB?.dynamicRange?.toFixed(1) || "N/A"],
    ["Edge Density (%)", analysisA?.edgeDensity?.toFixed(1) || "N/A", analysisB?.edgeDensity?.toFixed(1) || "N/A"],
  ];
  const csv = rows.map((r) => r.join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  saveAs(blob, "image-comparison.csv");
}

export function exportJSON(analysisA, analysisB, qualityA, qualityB) {
  const data = {
    exportedAt: new Date().toISOString(),
    imageA: { analysis: analysisA, qualityScore: qualityA },
    imageB: { analysis: analysisB, qualityScore: qualityB },
  };
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  saveAs(blob, "image-comparison.json");
}

function formatBytes(bytes) {
  if (!bytes) return "0 B";
  if (bytes < 1024) return bytes + " B";
  if (bytes < 1048576) return (bytes / 1024).toFixed(1) + " KB";
  return (bytes / 1048576).toFixed(1) + " MB";
}
