/**
 * Data portability request generator.
 *
 * GDPR Art. 20 is narrower than most people assume, and this module encodes the
 * three conditions that have to hold at the same time:
 *
 *   1. The lawful basis is consent (Art. 6(1)(a) or Art. 9(2)(a)) or performance
 *      of a contract (Art. 6(1)(b)). Legitimate interests, legal obligation,
 *      public task and vital interests do NOT give a portability right —
 *      Art. 15 access is the fallback in those cases.
 *   2. The processing is carried out by automated means. Paper files are out.
 *   3. The data was "provided by" the data subject. Article 29 Working Party
 *      Guidelines WP242 rev.01 read that as covering data actively supplied
 *      (forms, uploads) and data observed from the person's activity (search
 *      history, traffic and location data, raw device logs), but NOT data the
 *      controller derived or inferred, such as a credit score, a risk rating or
 *      an advertising interest profile.
 *
 * Other provisions used:
 *   - Art. 20(1): the format must be structured, commonly used and machine-readable.
 *   - Art. 20(2): direct controller-to-controller transmission where technically feasible.
 *   - Art. 20(4): portability must not adversely affect the rights of others.
 *   - Art. 12(3): reply within one calendar month, extendable by two further months.
 *   - Art. 12(5): free of charge.
 *   - Cal. Civ. Code s.1798.100(d): the export must be in a portable and, to the
 *     extent technically feasible, readily useable format that lets the consumer
 *     transmit it to another entity, answered within 45 days under s.1798.130(a)(2).
 *   - India's DPDP Act, 2023 contains a right to access information (s.11) and to
 *     correction and erasure (s.12), but no standalone portability right, so a
 *     request there is framed as an access request in a machine-readable format.
 */

const ISO_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

export const REGIMES = [
  {
    id: "gdpr",
    label: "EU — GDPR Article 20",
    hasPortabilityRight: true,
    deadlineKind: "months",
    deadlineValue: 1,
    extensionKind: "months",
    extensionValue: 2,
    citation: "Article 20 GDPR; Article 12(3) GDPR",
  },
  {
    id: "uk-gdpr",
    label: "UK — UK GDPR Article 20",
    hasPortabilityRight: true,
    deadlineKind: "months",
    deadlineValue: 1,
    extensionKind: "months",
    extensionValue: 2,
    citation: "Article 20 UK GDPR; Article 12(3) UK GDPR",
  },
  {
    id: "ccpa",
    label: "California — CCPA/CPRA",
    hasPortabilityRight: true,
    deadlineKind: "days",
    deadlineValue: 45,
    extensionKind: "days",
    extensionValue: 45,
    citation: "Cal. Civ. Code s.1798.100(d); s.1798.130(a)(2)",
  },
  {
    id: "india-dpdp",
    label: "India — DPDP Act, 2023 (access, not portability)",
    hasPortabilityRight: false,
    deadlineKind: "days",
    deadlineValue: 30,
    extensionKind: "none",
    extensionValue: 0,
    citation: "Section 11, Digital Personal Data Protection Act, 2023",
  },
];

/** Lawful bases, and whether Art. 20 attaches to them. */
export const LEGAL_BASES = [
  { id: "consent", label: "Consent", portable: true, article: "Art. 6(1)(a)" },
  { id: "contract", label: "Performance of a contract", portable: true, article: "Art. 6(1)(b)" },
  { id: "legitimate-interests", label: "Legitimate interests", portable: false, article: "Art. 6(1)(f)" },
  { id: "legal-obligation", label: "Legal obligation", portable: false, article: "Art. 6(1)(c)" },
  { id: "public-task", label: "Public task", portable: false, article: "Art. 6(1)(e)" },
];

/**
 * origin: "provided" = actively supplied, "observed" = generated by using the
 * service, "inferred" = created by the controller. Only the first two are in
 * scope for Art. 20 per WP242 rev.01.
 */
export const DATA_CATEGORIES = [
  { id: "profile", label: "Profile and account details", origin: "provided" },
  { id: "transactions", label: "Orders, payments and transaction history", origin: "provided" },
  { id: "content", label: "Content you uploaded (posts, photos, documents)", origin: "provided" },
  { id: "contacts", label: "Contacts and address book you supplied", origin: "provided" },
  { id: "messages", label: "Messages and support conversations", origin: "provided" },
  { id: "activity", label: "Activity, search and viewing history", origin: "observed" },
  { id: "location", label: "Location history", origin: "observed" },
  { id: "device", label: "Device, connection and session logs", origin: "observed" },
  { id: "scores", label: "Risk, credit or trust scores about you", origin: "inferred" },
  { id: "adprofile", label: "Advertising interest or audience profile", origin: "inferred" },
];

/** Art. 20(1) requires structured, commonly used, machine-readable output. */
export const FORMATS = [
  { id: "json", label: "JSON", machineReadable: true },
  { id: "csv", label: "CSV", machineReadable: true },
  { id: "xml", label: "XML", machineReadable: true },
  { id: "pdf", label: "PDF", machineReadable: false },
];

const REGIME_BY_ID = new Map(REGIMES.map((item) => [item.id, item]));
const BASIS_BY_ID = new Map(LEGAL_BASES.map((item) => [item.id, item]));
const CATEGORY_BY_ID = new Map(DATA_CATEGORIES.map((item) => [item.id, item]));
const FORMAT_BY_ID = new Map(FORMATS.map((item) => [item.id, item]));

const clean = (value) => String(value ?? "").trim();

const parseIso = (iso) => {
  if (!ISO_PATTERN.test(String(iso))) return null;
  const [year, month, day] = String(iso).split("-").map(Number);
  const date = new Date(Date.UTC(year, month - 1, day));
  if (
    date.getUTCFullYear() !== year ||
    date.getUTCMonth() !== month - 1 ||
    date.getUTCDate() !== day
  ) {
    return null;
  }
  return date;
};

const toIso = (date) => date.toISOString().slice(0, 10);

function daysInMonth(year, monthIndex) {
  return new Date(Date.UTC(year, monthIndex + 1, 0)).getUTCDate();
}

/** Add whole calendar months, clamping to the last day of a shorter month. */
export function addCalendarMonths(iso, months) {
  const date = parseIso(iso);
  if (!date || !Number.isInteger(months)) return null;
  const monthIndex = date.getUTCMonth() + months;
  const targetYear = date.getUTCFullYear() + Math.floor(monthIndex / 12);
  const targetMonth = ((monthIndex % 12) + 12) % 12;
  const day = Math.min(date.getUTCDate(), daysInMonth(targetYear, targetMonth));
  return toIso(new Date(Date.UTC(targetYear, targetMonth, day)));
}

/** Add whole calendar days. */
export function addCalendarDays(iso, days) {
  const date = parseIso(iso);
  if (!date || !Number.isInteger(days)) return null;
  return toIso(new Date(date.getTime() + days * 86400000));
}

function applyPeriod(iso, kind, value) {
  if (kind === "months") return addCalendarMonths(iso, value);
  if (kind === "days") return addCalendarDays(iso, value);
  return null;
}

/**
 * @param {object} input
 * @param {string} input.fullName      Person making the request.
 * @param {string} input.email         Reply address.
 * @param {string} input.accountRef    Username or account number.
 * @param {string} input.organisation  Controller the request goes to.
 * @param {string} input.regime        One of REGIMES[].id.
 * @param {string} input.legalBasis    One of LEGAL_BASES[].id.
 * @param {string[]} input.categories  Ids from DATA_CATEGORIES.
 * @param {string} input.format        One of FORMATS[].id.
 * @param {string} input.requestDate   ISO date the request is sent.
 * @param {boolean} input.directTransfer Ask for controller-to-controller transfer.
 * @param {string} input.recipient     Receiving controller, when directTransfer.
 * @returns {object} letter, eligibility and deadlines, or { error }.
 */
export function buildPortabilityRequest({
  fullName = "",
  email = "",
  accountRef = "",
  organisation = "",
  regime = "gdpr",
  legalBasis = "contract",
  categories = [],
  format = "json",
  requestDate = "",
  directTransfer = false,
  recipient = "",
} = {}) {
  const name = clean(fullName);
  if (!name) return { error: "Enter the name of the person making the request." };

  const org = clean(organisation);
  if (!org) return { error: "Enter the organisation you are asking for the export." };

  const law = REGIME_BY_ID.get(regime);
  if (!law) return { error: "Choose one of the supported privacy regimes." };

  const basis = BASIS_BY_ID.get(legalBasis);
  if (!basis) return { error: "Choose the lawful basis the organisation relies on." };

  const chosenFormat = FORMAT_BY_ID.get(format);
  if (!chosenFormat) return { error: "Choose an export format." };

  if (!parseIso(requestDate)) {
    return { error: "Enter the request date as a real calendar date." };
  }

  const selected = categories.map((id) => CATEGORY_BY_ID.get(id)).filter(Boolean);
  if (selected.length === 0) {
    return { error: "Select at least one category of data you want exported." };
  }

  const inScope = selected.filter((item) => item.origin !== "inferred");
  const outOfScope = selected.filter((item) => item.origin === "inferred");

  if (inScope.length === 0) {
    return {
      error: `The categories you selected (${outOfScope.map((item) => item.label).join(", ")}) are data the organisation derived or inferred about you, which falls outside the data portability right (WP242 rev.01). Select at least one category of data you actively provided or that was observed from your use of the service, or use an access request instead.`,
    };
  }

  const deadlineDate = applyPeriod(requestDate, law.deadlineKind, law.deadlineValue);
  const extensionDate =
    law.extensionKind === "none" ? null : applyPeriod(deadlineDate, law.extensionKind, law.extensionValue);
  if (!deadlineDate) return { error: "Could not calculate the response deadline from that date." };

  const deadlineLabel =
    law.deadlineKind === "months"
      ? `${law.deadlineValue} calendar month${law.deadlineValue === 1 ? "" : "s"}`
      : `${law.deadlineValue} calendar days`;

  const gdprFamily = law.id === "gdpr" || law.id === "uk-gdpr";
  const portabilityApplies = law.hasPortabilityRight && (!gdprFamily || basis.portable);

  const rightCited = portabilityApplies
    ? gdprFamily
      ? `Article 20 ${law.id === "uk-gdpr" ? "UK " : ""}GDPR (right to data portability)`
      : "Cal. Civ. Code s.1798.100(d) (right to a portable copy)"
    : gdprFamily
      ? `Article 15 ${law.id === "uk-gdpr" ? "UK " : ""}GDPR (right of access), because Article 20 does not apply to processing based on ${basis.label.toLowerCase()}`
      : "Section 11, Digital Personal Data Protection Act, 2023 (right to access information)";

  const subject = `${portabilityApplies ? "Data portability request" : "Data access request in machine-readable form"} — ${name}${clean(accountRef) ? ` (${clean(accountRef)})` : ""}`;

  const bodyLines = [
    `Dear ${org} Privacy Team,`,
    "",
    `I am exercising my right under ${rightCited}.`,
    `My details: ${name}${clean(email) ? `, ${clean(email)}` : ""}${clean(accountRef) ? `, account reference ${clean(accountRef)}` : ""}.`,
    "",
    `Please supply a copy of the following categories of personal data concerning me, in ${chosenFormat.label} format:`,
    ...inScope.map((item) => `- ${item.label} (${item.origin === "provided" ? "data I supplied" : "data observed from my use of the service"})`),
    "",
    portabilityApplies && gdprFamily
      ? "Article 20(1) requires the copy to be in a structured, commonly used and machine-readable format. A scanned document or a screenshot does not meet that standard."
      : "Please supply the data in a format I can open and re-use, not as images or scans.",
    outOfScope.length > 0
      ? `I understand that data you have derived or inferred about me (${outOfScope.map((item) => item.label.toLowerCase()).join(", ")}) may fall outside the portability right. I am asking for it separately under my right of access, and I ask you to confirm what exists.`
      : "",
    directTransfer && portabilityApplies && gdprFamily
      ? `Where it is technically feasible, Article 20(2) entitles me to have the data transmitted directly to another controller. Please transmit it to ${clean(recipient) || "the controller I will nominate"} and confirm when that is done.`
      : "",
    "",
    `Please respond by ${deadlineDate}, being ${deadlineLabel} from the date of this request.${extensionDate ? ` If you rely on the permitted extension you must tell me the reason before that date; the extended deadline would be ${extensionDate}.` : ""} No fee is payable for this request.`,
    "If you need anything to identify me, tell me within a few days rather than at the end of the period, and say precisely what you need.",
    "",
    "Yours faithfully,",
    name,
    clean(email),
  ].filter((line, index, all) => line !== "" || (all[index - 1] !== "" && all[index - 1] !== undefined));

  const warnings = [];
  if (gdprFamily && !basis.portable) {
    warnings.push(
      `Article 20 does not apply here. Portability attaches only to processing based on consent (${LEGAL_BASES[0].article}) or contract (${LEGAL_BASES[1].article}), and you selected ${basis.label} (${basis.article}). The letter has been rewritten as an Article 15 access request, which still gets you a copy of the data.`,
    );
  }
  if (!law.hasPortabilityRight) {
    warnings.push(
      "The DPDP Act, 2023 gives a right to access a summary of your personal data and the processing activities (s.11), but no standalone portability right, so the organisation is not obliged to hand over a machine-readable export. Ask anyway — many will oblige — but do not cite a right that does not exist.",
    );
  }
  if (!chosenFormat.machineReadable) {
    warnings.push(
      "PDF is not a machine-readable format for the purposes of Article 20(1). Ask for JSON, CSV or XML; a PDF export is a common way of technically complying while making the data useless.",
    );
  }
  if (outOfScope.length > 0) {
    warnings.push(
      `${outOfScope.length} of the categories you selected are data the controller derived rather than data you provided. WP242 rev.01 puts inferred data such as scores and interest profiles outside Article 20, so expect those to come back under the access right instead.`,
    );
  }
  if (directTransfer && !clean(recipient)) {
    warnings.push(
      "You asked for a direct controller-to-controller transfer but did not name the receiving organisation. Article 20(2) only bites where the destination and the technical route are identifiable.",
    );
  }
  if (selected.some((item) => item.id === "messages" || item.id === "contacts")) {
    warnings.push(
      "Messages and contact lists contain other people's personal data. Article 20(4) says portability must not adversely affect the rights of others, so the controller may redact third-party details before sending the export.",
    );
  }
  if (!clean(email)) {
    warnings.push("Give a reply address, or the controller has no way to deliver the export to you.");
  }

  return {
    subject,
    bodyLines,
    letter: bodyLines.join("\n"),
    portabilityApplies,
    rightCited,
    deadlineDate,
    deadlineLabel,
    extensionDate,
    inScope,
    outOfScope,
    warnings,
    regimeLabel: law.label,
    citation: law.citation,
    stats: {
      categoriesRequested: selected.length,
      categoriesInScope: inScope.length,
      categoriesOutOfScope: outOfScope.length,
      machineReadable: chosenFormat.machineReadable,
      warningCount: warnings.length,
    },
  };
}
