/**
 * Indian folk dance reference.
 *
 * A curated dataset plus pure search, filter, grouping and statistics helpers.
 * "Form" separates a social folk dance from a ritual performance (where the
 * dancer is understood to embody a deity), a martial dance and folk theatre,
 * because those are performed under quite different conditions.
 *
 * UNESCO flags refer to inscription on the Representative List of the
 * Intangible Cultural Heritage of Humanity: Chhau and Kalbelia in 2010, and
 * Sankirtana of Manipur in 2013.
 */

export const FORMS = ["Folk", "Ritual", "Martial", "Folk theatre"];
export const PERFORMER_GROUPS = ["Women", "Men", "Mixed"];

export const DANCES = [
  {
    id: "bhangra",
    name: "Bhangra",
    state: "Punjab",
    region: "North",
    form: "Folk",
    performers: "Men",
    occasion: "Baisakhi and the wheat harvest",
    instruments: ["Dhol", "Tumbi", "Chimta"],
    costume: "Bright kurta with a tehmat or lungi, embroidered waistcoat and a turban",
    note: "Built around the dhol beat; leaps and shoulder movements imitate harvesting actions.",
  },
  {
    id: "giddha",
    name: "Giddha",
    state: "Punjab",
    region: "North",
    form: "Folk",
    performers: "Women",
    occasion: "Weddings, Teej and family celebrations",
    instruments: ["Dholki", "Handclaps"],
    costume: "Salwar kameez with a bright dupatta and heavy silver jewellery",
    note: "Couplets called boliyan are sung in turn, often teasing relatives, with clapping keeping time.",
  },
  {
    id: "garba",
    name: "Garba",
    state: "Gujarat",
    region: "West",
    form: "Folk",
    performers: "Mixed",
    occasion: "Navratri",
    instruments: ["Dhol", "Dholak", "Harmonium"],
    costume: "Chaniya choli for women, kediyu and dhoti for men",
    note: "Circles move around a perforated earthen pot, the garbo, holding a lamp that stands for the womb.",
  },
  {
    id: "dandiya-raas",
    name: "Dandiya Raas",
    state: "Gujarat",
    region: "West",
    form: "Folk",
    performers: "Mixed",
    occasion: "Navratri",
    instruments: ["Dhol", "Shehnai"],
    costume: "Chaniya choli and kediyu, often mirror-worked",
    note: "Danced with a pair of sticks; the striking pattern stands for the fight between Durga and Mahishasura.",
  },
  {
    id: "lavani",
    name: "Lavani",
    state: "Maharashtra",
    region: "West",
    form: "Folk",
    performers: "Women",
    occasion: "Temple fairs and stage performance",
    instruments: ["Dholki", "Tuntune", "Manjeera"],
    costume: "Nine-yard nauvari saree worn tightly, with a large bindi and heavy jewellery",
    note: "Fast dholki rhythm and sharp footwork; the lyrics range from devotional to openly satirical.",
  },
  {
    id: "ghoomar",
    name: "Ghoomar",
    state: "Rajasthan",
    region: "North",
    form: "Folk",
    performers: "Women",
    occasion: "Weddings, Teej and Gangaur",
    instruments: ["Dholak", "Sarangi", "Nagara"],
    costume: "Flowing ghagra and choli with an odhni drawn over the face",
    note: "Named from ghoomna, to turn; the swirl of the ghagra is the point of the dance.",
  },
  {
    id: "kalbelia",
    name: "Kalbelia",
    state: "Rajasthan",
    region: "North",
    form: "Folk",
    performers: "Women",
    occasion: "Community gatherings of the Kalbelia people",
    instruments: ["Been (pungi)", "Khanjari", "Dholak"],
    costume: "Black swirling ghagra with silver ribbon, worn with an angrakhi",
    note: "Movements imitate a serpent. Inscribed on the UNESCO Representative List in 2010.",
    unesco: 2010,
  },
  {
    id: "kachhi-ghodi",
    name: "Kachhi Ghodi",
    state: "Rajasthan",
    region: "North",
    form: "Folk",
    performers: "Men",
    occasion: "Wedding processions",
    instruments: ["Dhol", "Fife"],
    costume: "Dummy horse frame worn at the waist, with a turban and a sword",
    note: "Mock cavalry battles are staged to ballads about local bandit heroes.",
  },
  {
    id: "bihu",
    name: "Bihu",
    state: "Assam",
    region: "North East",
    form: "Folk",
    performers: "Mixed",
    occasion: "Rongali Bihu, the Assamese spring new year in April",
    instruments: ["Dhol", "Pepa (buffalo horn pipe)", "Gogona", "Taal"],
    costume: "Mekhela chador in muga silk with red motifs",
    note: "Rapid hip and hand movement; historically a courtship dance held in open fields.",
  },
  {
    id: "bagurumba",
    name: "Bagurumba",
    state: "Assam",
    region: "North East",
    form: "Folk",
    performers: "Women",
    occasion: "Bwisagu, the Bodo spring festival",
    instruments: ["Kham", "Sifung (flute)", "Jotha"],
    costume: "Dokhona and aronai in green and yellow bands",
    note: "Called the butterfly dance for its slow outstretched arm movements.",
  },
  {
    id: "chhau",
    name: "Chhau",
    state: "Jharkhand, Odisha and West Bengal",
    region: "East",
    form: "Martial",
    performers: "Men",
    occasion: "Chaitra Parva in spring",
    instruments: ["Dhol", "Dhumsa", "Shehnai", "Charchari"],
    costume: "Painted masks in the Purulia and Seraikella styles; the Mayurbhanj style uses none",
    note: "Combat training turned into narrative dance from the Ramayana and Mahabharata. UNESCO listed in 2010.",
    unesco: 2010,
  },
  {
    id: "jhumair",
    name: "Jhumair",
    state: "Jharkhand",
    region: "East",
    form: "Folk",
    performers: "Mixed",
    occasion: "Harvest and the agricultural season",
    instruments: ["Mandar", "Dhol", "Nagara"],
    costume: "Cotton saree tied short, with sal leaf and flower ornaments",
    note: "Linked arms in a slow-moving line; the songs track the farming calendar.",
  },
  {
    id: "karma",
    name: "Karma",
    state: "Chhattisgarh, Jharkhand and Madhya Pradesh",
    region: "Central",
    form: "Ritual",
    performers: "Mixed",
    occasion: "Karma Puja in Bhadrapada, worship of the karam tree",
    instruments: ["Mandar", "Timki", "Jhanjh"],
    costume: "Everyday dress with peacock feathers and bead ornaments",
    note: "A branch of the karam tree is planted in the courtyard and danced around all night.",
  },
  {
    id: "panthi",
    name: "Panthi",
    state: "Chhattisgarh",
    region: "Central",
    form: "Folk",
    performers: "Men",
    occasion: "Guru Ghasidas Jayanti in the Satnami community",
    instruments: ["Mandar", "Jhanjh"],
    costume: "White dhoti and a white cloth over the shoulder",
    note: "Starts slowly and accelerates into human pyramids; the songs are on Satnami philosophy.",
  },
  {
    id: "raut-nacha",
    name: "Raut Nacha",
    state: "Chhattisgarh",
    region: "Central",
    form: "Folk",
    performers: "Men",
    occasion: "Dev Udhni Ekadashi, when Vishnu is said to wake",
    instruments: ["Gadwa baja", "Nishan drum"],
    costume: "Peacock feather crowns, cowrie shells and a stick",
    note: "Danced by the Yadav cattle-herding community in memory of Krishna the cowherd.",
  },
  {
    id: "dollu-kunitha",
    name: "Dollu Kunitha",
    state: "Karnataka",
    region: "South",
    form: "Folk",
    performers: "Men",
    occasion: "Temple festivals of the Beereshwara cult",
    instruments: ["Dollu (large barrel drum)"],
    costume: "Bare torso with a dhoti, the drum slung from the neck",
    note: "Drummers play and dance simultaneously, forming and breaking circles at speed.",
  },
  {
    id: "veeragase",
    name: "Veeragase",
    state: "Karnataka",
    region: "South",
    form: "Ritual",
    performers: "Men",
    occasion: "Dasara processions and Shravana",
    instruments: ["Sambal", "Karade", "Shruti"],
    costume: "Rudraksha beads, a large headdress and a sword",
    note: "Enacts Veerabhadra, the fierce form of Shiva; vigorous rather than choreographed.",
  },
  {
    id: "yakshagana",
    name: "Yakshagana",
    state: "Karnataka",
    region: "South",
    form: "Folk theatre",
    performers: "Men",
    occasion: "Night-long performances in the post-monsoon temple season",
    instruments: ["Chande", "Maddale", "Harmonium", "Taala"],
    costume: "Towering headgear, painted faces and heavy wooden ornaments",
    note: "Combines dance, song and improvised dialogue; a single episode can run until dawn.",
  },
  {
    id: "kummi",
    name: "Kummi",
    state: "Tamil Nadu",
    region: "South",
    form: "Folk",
    performers: "Women",
    occasion: "Pongal, temple festivals and village fairs",
    instruments: ["Handclaps", "Sung refrain"],
    costume: "Everyday saree, sometimes with flowers in the hair",
    note: "One of the oldest recorded village dances; the clap replaces any instrument.",
  },
  {
    id: "karagattam",
    name: "Karagattam",
    state: "Tamil Nadu",
    region: "South",
    form: "Ritual",
    performers: "Mixed",
    occasion: "Worship of Mariamman, the rain goddess",
    instruments: ["Naiyandi melam", "Thavil", "Nadaswaram"],
    costume: "Decorated pot balanced on the head, topped with a cone of flowers",
    note: "The pot is never touched with the hands, even during the fastest sequences.",
  },
  {
    id: "oyilattam",
    name: "Oyilattam",
    state: "Tamil Nadu",
    region: "South",
    form: "Folk",
    performers: "Men",
    occasion: "Temple festivals in the southern districts",
    instruments: ["Thavil", "Nadaswaram"],
    costume: "Ankle bells, a coloured cloth in each hand",
    note: "Begins with a single dancer; others join the line one by one until the row is full.",
  },
  {
    id: "kolattam",
    name: "Kolattam",
    state: "Tamil Nadu and Andhra Pradesh",
    region: "South",
    form: "Folk",
    performers: "Mixed",
    occasion: "Village festivals and Navratri",
    instruments: ["Sticks", "Sung rhythm"],
    costume: "Simple saree or dhoti with ankle bells",
    note: "Two concentric circles strike sticks in counter-rhythm; a plaited version weaves ropes overhead.",
  },
  {
    id: "theyyam",
    name: "Theyyam",
    state: "Kerala",
    region: "South",
    form: "Ritual",
    performers: "Men",
    occasion: "Shrine season in north Kerala, roughly October to May",
    instruments: ["Chenda", "Elathalam", "Kurumkuzhal"],
    costume: "Towering headdress, painted face and layered palm-leaf skirts",
    note: "The performer is treated as the deity for the duration, and gives blessings in that role.",
  },
  {
    id: "padayani",
    name: "Padayani",
    state: "Kerala",
    region: "South",
    form: "Ritual",
    performers: "Men",
    occasion: "Bhadrakali temple festivals in central Travancore",
    instruments: ["Thappu", "Chenda", "Kaimani"],
    costume: "Kolams painted on areca palm sheath and worn as masks",
    note: "Each kolam represents a spirit or illness; the dance is understood to appease it.",
  },
  {
    id: "thiruvathirakali",
    name: "Thiruvathirakali",
    state: "Kerala",
    region: "South",
    form: "Folk",
    performers: "Women",
    occasion: "Thiruvathira in Dhanu and during Onam",
    instruments: ["Sung verses", "Handclaps"],
    costume: "Kerala kasavu mundu and neriyathu with jasmine in the hair",
    note: "A slow circle around a lit lamp, with the graceful lasya style of movement.",
  },
  {
    id: "rouf",
    name: "Rouf",
    state: "Jammu and Kashmir",
    region: "North",
    form: "Folk",
    performers: "Women",
    occasion: "Spring, Ramzan evenings and Eid",
    instruments: ["Sung chakri melodies", "Tumbaknari"],
    costume: "Pheran with an embroidered headscarf",
    note: "Two rows face each other, arms linked, stepping forward and back in a chain.",
  },
  {
    id: "kud",
    name: "Kud",
    state: "Jammu and Kashmir",
    region: "North",
    form: "Ritual",
    performers: "Mixed",
    occasion: "Night-long thanksgiving to local guardian deities after harvest",
    instruments: ["Narsingha", "Chhaina", "Flute", "Drums"],
    costume: "Everyday hill dress; the dance is spontaneous rather than staged",
    note: "Performed in the mid-hill villages of the Jammu region, often until sunrise.",
  },
  {
    id: "nati",
    name: "Nati",
    state: "Himachal Pradesh",
    region: "North",
    form: "Folk",
    performers: "Mixed",
    occasion: "Dussehra at Kullu and district fairs",
    instruments: ["Dhol", "Nagara", "Shehnai", "Karnal"],
    costume: "Woollen chola with a Kullu cap and a patti shawl",
    note: "A slow chain dance in long lines; a mass Nati in 2016 entered the Guinness records.",
  },
  {
    id: "chholiya",
    name: "Chholiya",
    state: "Uttarakhand",
    region: "North",
    form: "Martial",
    performers: "Men",
    occasion: "Kumaoni wedding processions",
    instruments: ["Dhol", "Damau", "Turi", "Ransing"],
    costume: "Red and white tunic with a sword and shield",
    note: "A sword dance that once escorted the groom's party as an armed guard.",
  },
  {
    id: "cheraw",
    name: "Cheraw",
    state: "Mizoram",
    region: "North East",
    form: "Folk",
    performers: "Mixed",
    occasion: "Chapchar Kut and community celebrations",
    instruments: ["Bamboo staves", "Gong"],
    costume: "Puanchei skirt with a kawrchei blouse and a headdress",
    note: "Dancers step between bamboo poles clapped together in rhythm by seated players.",
  },
  {
    id: "hojagiri",
    name: "Hojagiri",
    state: "Tripura",
    region: "North East",
    form: "Folk",
    performers: "Women",
    occasion: "Laxmi Puja among the Reang community",
    instruments: ["Kham", "Sumui flute"],
    costume: "Risa and rignai, with a bottle and lamp balanced on the head",
    note: "The lower body stays still while the dancer balances a pitcher, bottle and lit lamp.",
  },
  {
    id: "singhi-chham",
    name: "Singhi Chham",
    state: "Sikkim",
    region: "North East",
    form: "Ritual",
    performers: "Men",
    occasion: "Pang Lhabsol, honouring Mount Khangchendzonga",
    instruments: ["Cymbals", "Long horns", "Drums"],
    costume: "Full snow lion costume worn by two dancers",
    note: "The snow lion stands for the guardian spirit of the mountain.",
  },
  {
    id: "bardo-chham",
    name: "Bardo Chham",
    state: "Arunachal Pradesh",
    region: "North East",
    form: "Ritual",
    performers: "Men",
    occasion: "New year and community purification",
    instruments: ["Drums", "Cymbals"],
    costume: "Masks of the twelve animals of the local zodiac",
    note: "Danced by the Sherdukpen; the masked animals represent evil forces being driven off.",
  },
  {
    id: "lai-haraoba",
    name: "Lai Haraoba",
    state: "Manipur",
    region: "North East",
    form: "Ritual",
    performers: "Mixed",
    occasion: "Meitei festival for the pre-Vaishnavite deities, held in summer",
    instruments: ["Pena (bowed lute)", "Langde"],
    costume: "Phanek and innaphi for women, dhoti and turban for men",
    note: "Re-enacts the creation of the world through hand gestures, in a fixed sequence.",
  },
  {
    id: "sankirtana",
    name: "Sankirtana",
    state: "Manipur",
    region: "North East",
    form: "Ritual",
    performers: "Men",
    occasion: "Vaishnava temple rites and life-cycle ceremonies",
    instruments: ["Pung (drum)", "Kartal cymbals"],
    costume: "White dhoti with a turban; drummers dance while playing",
    note: "Narrates the life of Krishna. Inscribed on the UNESCO Representative List in 2013.",
    unesco: 2013,
  },
  {
    id: "thang-ta",
    name: "Thang Ta",
    state: "Manipur",
    region: "North East",
    form: "Martial",
    performers: "Men",
    occasion: "Festivals and martial demonstrations",
    instruments: ["Drums", "Cymbals"],
    costume: "Black dress with a sword (thang) and spear (ta)",
    note: "A martial art performed as dance; the ritual form is done without weapons.",
  },
  {
    id: "chang-lo",
    name: "Chang Lo",
    state: "Nagaland",
    region: "North East",
    form: "Folk",
    performers: "Mixed",
    occasion: "Poanglem, the three-day Chang harvest festival",
    instruments: ["Log drum", "Chorus"],
    costume: "Warrior headgear with hornbill feathers and shawls",
    note: "Originally a victory dance; now performed to mark the gathered harvest.",
  },
  {
    id: "wangala",
    name: "Wangala",
    state: "Meghalaya",
    region: "North East",
    form: "Folk",
    performers: "Mixed",
    occasion: "Garo harvest thanksgiving to Misi Saljong, in autumn",
    instruments: ["Dama drums", "Rang gongs", "Buffalo horn"],
    costume: "Dakmanda and daksari with feathered headdresses",
    note: "Known as the hundred drums festival; lines of drummers lead the dancers.",
  },
  {
    id: "ghumura",
    name: "Ghumura",
    state: "Odisha",
    region: "East",
    form: "Martial",
    performers: "Men",
    occasion: "Nuakhai and Dussehra in Kalahandi",
    instruments: ["Ghumura (clay pot drum)", "Nishan", "Taal"],
    costume: "The drum tied at the chest, with a warrior's headband",
    note: "Described in local tradition as a war dance; the drum shape gives the form its name.",
  },
  {
    id: "dalkhai",
    name: "Dalkhai",
    state: "Odisha",
    region: "East",
    form: "Folk",
    performers: "Women",
    occasion: "Dussehra and Bhaijiuntia in western Odisha",
    instruments: ["Dhol", "Nishan", "Tasa", "Mahuri"],
    costume: "Sambalpuri saree with a shawl tied at the waist",
    note: "Every verse opens with the call dalkhai bo, addressed to a friend.",
  },
  {
    id: "jhijhiya",
    name: "Jhijhiya",
    state: "Bihar",
    region: "East",
    form: "Ritual",
    performers: "Women",
    occasion: "Dussehra in the Mithila region",
    instruments: ["Sung verses", "Dholak"],
    costume: "Saree with a perforated earthen pot of lit lamps on the head",
    note: "Sung to Durga; the pierced pot is carried without support through the whole dance.",
  },
  {
    id: "jat-jatin",
    name: "Jat-Jatin",
    state: "Bihar",
    region: "East",
    form: "Folk",
    performers: "Mixed",
    occasion: "Monsoon nights in north Bihar",
    instruments: ["Dholak", "Manjeera"],
    costume: "Simple village dress; performed in pairs",
    note: "Acts out the quarrel and reconciliation of a couple separated by migration for work.",
  },
  {
    id: "charkula",
    name: "Charkula",
    state: "Uttar Pradesh",
    region: "North",
    form: "Folk",
    performers: "Women",
    occasion: "The third day after Holi in the Braj region",
    instruments: ["Dholak", "Manjeera", "Rasiya songs"],
    costume: "Ghagra with a veil, and a tiered wooden column of oil lamps on the head",
    note: "The charkula can carry over a hundred lit lamps; the dancer's face stays veiled throughout.",
  },
  {
    id: "raslila",
    name: "Raslila",
    state: "Uttar Pradesh",
    region: "North",
    form: "Folk theatre",
    performers: "Mixed",
    occasion: "Janmashtami and the Braj festival season",
    instruments: ["Harmonium", "Dholak", "Manjeera"],
    costume: "Krishna in peacock crown and yellow dhoti, gopis in ghagra choli",
    note: "Boys usually play both Krishna and Radha; song, dialogue and dance alternate.",
  },
  {
    id: "khoria",
    name: "Khoria",
    state: "Haryana",
    region: "North",
    form: "Folk",
    performers: "Women",
    occasion: "The days before a wedding in the groom's house",
    instruments: ["Dholak", "Thali", "Chimta"],
    costume: "Ghagra and kurti with an odhni",
    note: "Performed only among women, with songs that satirise the men of the family.",
  },
  {
    id: "perini",
    name: "Perini Shivatandavam",
    state: "Telangana",
    region: "South",
    form: "Martial",
    performers: "Men",
    occasion: "Revived temple performance; historically danced before battle",
    instruments: ["Mridangam", "Cymbals", "Drums"],
    costume: "Bare torso with rudraksha, ankle bells and a headband",
    note: "Recorded in the Kakatiya period and reconstructed in the twentieth century from temple sculpture.",
  },
  {
    id: "dhimsa",
    name: "Dhimsa",
    state: "Andhra Pradesh",
    region: "South",
    form: "Folk",
    performers: "Mixed",
    occasion: "Spring festivals in the Araku valley",
    instruments: ["Tudumu", "Mori", "Kiridi"],
    costume: "Tribal jewellery of beads and brass, with a plain saree",
    note: "Danced by tribal communities of the Eastern Ghats in a linked open circle.",
  },
  {
    id: "matki",
    name: "Matki",
    state: "Madhya Pradesh",
    region: "Central",
    form: "Folk",
    performers: "Women",
    occasion: "Weddings and births in the Malwa region",
    instruments: ["Dhol", "Matki (pot) percussion"],
    costume: "Ghagra with a veil, and an earthen pot carried on the head",
    note: "Begins as a solo, with others joining once the first dancer sets the pace.",
  },
  {
    id: "gambhira",
    name: "Gambhira",
    state: "West Bengal",
    region: "East",
    form: "Folk theatre",
    performers: "Men",
    occasion: "Chaitra Sankranti in the Malda region",
    instruments: ["Dhol", "Harmonium", "Judi"],
    costume: "Everyday dress, sometimes with masks of Shiva",
    note: "A grandfather and grandson exchange verses about the year's events, often as political satire.",
  },
  {
    id: "fugdi",
    name: "Fugdi",
    state: "Goa",
    region: "West",
    form: "Folk",
    performers: "Women",
    occasion: "Ganesh Chaturthi and the month of Bhadrapada",
    instruments: ["Sung refrain", "Clapping"],
    costume: "Nine-yard saree tied in the Goan style",
    note: "Circles spin faster and faster until the dancers are breathless, which gives the form its name.",
  },
  {
    id: "ghode-modni",
    name: "Ghode Modni",
    state: "Goa",
    region: "West",
    form: "Folk",
    performers: "Men",
    occasion: "Shigmo, the Goan spring festival",
    instruments: ["Dhol", "Tasha", "Cymbals"],
    costume: "Dummy horse at the waist, with a sword and a plumed headdress",
    note: "Commemorates Maratha cavalry; the sword movements are drilled in formation.",
  },
];

/* ------------------------------------------------------------------ */

const normalise = (value) => String(value == null ? "" : value).toLowerCase().trim();

/** Every state or state group that appears, alphabetically. */
export function statesIn(dances = DANCES) {
  return [...new Set(dances.map((dance) => dance.state))].sort((a, b) => a.localeCompare(b));
}

/** Every region that appears, in a fixed geographic order. */
export const REGIONS = ["North", "West", "Central", "East", "South", "North East"];

/**
 * Filter the dataset.
 * @param {object} filters
 * @returns {object[]}
 */
export function filterDances({ query = "", state = "All", region = "All", form = "All", performers = "All" } = {}) {
  const q = normalise(query);
  return DANCES.filter((dance) => {
    if (state !== "All" && dance.state !== state) return false;
    if (region !== "All" && dance.region !== region) return false;
    if (form !== "All" && dance.form !== form) return false;
    if (performers !== "All" && dance.performers !== performers) return false;
    if (!q) return true;
    const haystack = normalise(
      [dance.name, dance.state, dance.occasion, dance.costume, dance.note, dance.instruments.join(" ")].join(" "),
    );
    return haystack.includes(q);
  });
}

/** Group a list of dances by state, sorted. */
export function groupByState(dances) {
  const map = new Map();
  for (const dance of dances) {
    if (!map.has(dance.state)) map.set(dance.state, []);
    map.get(dance.state).push(dance);
  }
  return [...map.entries()]
    .map(([state, list]) => ({ state, dances: list.sort((a, b) => a.name.localeCompare(b.name)) }))
    .sort((a, b) => a.state.localeCompare(b.state));
}

/**
 * Counts for the current selection.
 * @returns {{total:number,states:number,byForm:Array,byPerformers:Array,unesco:number,instruments:number}}
 */
export function statsFor(dances) {
  const list = Array.isArray(dances) ? dances : [];
  const tally = (key) => {
    const map = new Map();
    for (const dance of list) map.set(dance[key], (map.get(dance[key]) || 0) + 1);
    return [...map.entries()].map(([label, count]) => ({ label, count })).sort((a, b) => b.count - a.count);
  };
  const instruments = new Set();
  for (const dance of list) for (const item of dance.instruments) instruments.add(item);

  return {
    total: list.length,
    states: new Set(list.map((dance) => dance.state)).size,
    byForm: tally("form"),
    byPerformers: tally("performers"),
    unesco: list.filter((dance) => dance.unesco).length,
    instruments: instruments.size,
  };
}

/** Deterministic pick, so the same seed always shows the same dance. */
export function danceOfTheDay(seed = 1, dances = DANCES) {
  const list = Array.isArray(dances) && dances.length ? dances : DANCES;
  const index = Math.abs(Math.trunc(Number(seed)) || 0) % list.length;
  return list[index];
}
