export const ingredients = [
  {
    id: "flour-ap",
    name: "All-purpose flour (maida)",
    group: "Flours & starches",
    gramsPerCup: 120,
    scoopedGramsPerCup: 145,
    note: "Spoon into the cup and level with a knife. Dipping the cup straight into the bag compacts the flour.",
  },
  {
    id: "flour-atta",
    name: "Whole wheat flour (atta)",
    group: "Flours & starches",
    gramsPerCup: 120,
    scoopedGramsPerCup: 143,
    note: "Atta is milled finer than Western whole wheat, so it packs a little denser in the cup.",
  },
  {
    id: "flour-bread",
    name: "Bread flour",
    group: "Flours & starches",
    gramsPerCup: 127,
    scoopedGramsPerCup: 150,
    note: "Higher protein and slightly coarser than maida, so a cup weighs a touch more.",
  },
  {
    id: "flour-cake",
    name: "Cake flour",
    group: "Flours & starches",
    gramsPerCup: 114,
    scoopedGramsPerCup: 136,
    note: "The softest, lightest flour. Always sift before measuring by volume.",
  },
  {
    id: "flour-almond",
    name: "Almond flour",
    group: "Flours & starches",
    gramsPerCup: 96,
    scoopedGramsPerCup: 112,
    note: "Oily and clumpy. Break up lumps before measuring or you will overshoot badly.",
  },
  {
    id: "flour-besan",
    name: "Besan (gram flour)",
    group: "Flours & starches",
    gramsPerCup: 95,
    scoopedGramsPerCup: 114,
    note: "Besan compacts and cakes in storage. Sift it, then spoon it into the cup.",
  },
  {
    id: "flour-rice",
    name: "Rice flour",
    group: "Flours & starches",
    gramsPerCup: 158,
    scoopedGramsPerCup: 178,
    note: "Fine, heavy and free-flowing, so a cup is much heavier than maida.",
  },
  {
    id: "cornstarch",
    name: "Cornstarch (cornflour)",
    group: "Flours & starches",
    gramsPerCup: 120,
    scoopedGramsPerCup: 140,
  },
  {
    id: "semolina",
    name: "Semolina (sooji / rava)",
    group: "Flours & starches",
    gramsPerCup: 167,
  },
  {
    id: "cornmeal",
    name: "Cornmeal (makki ka atta)",
    group: "Flours & starches",
    gramsPerCup: 138,
  },
  {
    id: "breadcrumbs",
    name: "Breadcrumbs (dry)",
    group: "Flours & starches",
    gramsPerCup: 108,
  },
  {
    id: "oats",
    name: "Rolled oats",
    group: "Flours & starches",
    gramsPerCup: 90,
    note: "Rolled oats trap a lot of air. Weighing is far more reliable than scooping.",
  },

  {
    id: "sugar-granulated",
    name: "Granulated white sugar",
    group: "Sugars & syrups",
    gramsPerCup: 200,
  },
  {
    id: "sugar-caster",
    name: "Caster (superfine) sugar",
    group: "Sugars & syrups",
    gramsPerCup: 225,
    note: "Finer crystals nest together, so caster sugar is denser than granulated.",
  },
  {
    id: "sugar-brown",
    name: "Brown sugar (packed)",
    group: "Sugars & syrups",
    gramsPerCup: 220,
    note: "Brown sugar is measured firmly packed. Loosely spooned it drops to roughly 145 g per cup.",
  },
  {
    id: "sugar-powdered",
    name: "Powdered / icing sugar",
    group: "Sugars & syrups",
    gramsPerCup: 120,
    scoopedGramsPerCup: 140,
    note: "Unsifted. Icing sugar clumps, so sift it before measuring by volume.",
  },
  {
    id: "jaggery",
    name: "Jaggery (grated gur)",
    group: "Sugars & syrups",
    gramsPerCup: 190,
  },
  {
    id: "honey",
    name: "Honey",
    group: "Sugars & syrups",
    gramsPerCup: 340,
    note: "Honey is heavier than water. Oil the cup or spoon first and it slides right out.",
  },
  {
    id: "maple-syrup",
    name: "Maple syrup",
    group: "Sugars & syrups",
    gramsPerCup: 322,
  },
  {
    id: "golden-syrup",
    name: "Golden / corn syrup",
    group: "Sugars & syrups",
    gramsPerCup: 328,
  },

  {
    id: "butter",
    name: "Butter",
    group: "Fats & oils",
    gramsPerCup: 227,
    note: "1 cup = 2 US sticks = 227 g. Indian butter blocks are usually 100 g or 500 g.",
  },
  {
    id: "ghee",
    name: "Ghee",
    group: "Fats & oils",
    gramsPerCup: 215,
    note: "Measure ghee melted for accuracy. Solid ghee traps air pockets in the cup.",
  },
  {
    id: "oil-vegetable",
    name: "Vegetable / sunflower oil",
    group: "Fats & oils",
    gramsPerCup: 220,
    note: "Oil is lighter than water, so 1 cup of oil is about 220 g, not 240 g.",
  },
  {
    id: "oil-olive",
    name: "Olive oil",
    group: "Fats & oils",
    gramsPerCup: 216,
  },
  {
    id: "peanut-butter",
    name: "Peanut butter",
    group: "Fats & oils",
    gramsPerCup: 258,
  },

  {
    id: "water",
    name: "Water",
    group: "Liquids & dairy",
    gramsPerCup: 240,
    note: "The only ingredient where 1 ml really does equal 1 g. Everything else has its own density.",
  },
  {
    id: "milk",
    name: "Milk (whole)",
    group: "Liquids & dairy",
    gramsPerCup: 245,
  },
  {
    id: "buttermilk",
    name: "Buttermilk (chaas)",
    group: "Liquids & dairy",
    gramsPerCup: 245,
  },
  {
    id: "curd",
    name: "Curd / plain yogurt",
    group: "Liquids & dairy",
    gramsPerCup: 245,
    note: "Thick set curd traps air. Whisk it smooth before measuring by volume.",
  },
  {
    id: "cream",
    name: "Heavy / whipping cream",
    group: "Liquids & dairy",
    gramsPerCup: 238,
  },
  {
    id: "condensed-milk",
    name: "Condensed milk",
    group: "Liquids & dairy",
    gramsPerCup: 306,
    note: "Very dense and very sticky. Weighing it saves you scraping the cup.",
  },
  {
    id: "cream-cheese",
    name: "Cream cheese",
    group: "Liquids & dairy",
    gramsPerCup: 227,
  },
  {
    id: "milk-powder",
    name: "Milk powder",
    group: "Liquids & dairy",
    gramsPerCup: 128,
  },

  {
    id: "cocoa",
    name: "Cocoa powder (unsweetened)",
    group: "Chocolate, nuts & mix-ins",
    gramsPerCup: 85,
    scoopedGramsPerCup: 102,
    note: "Cocoa is extremely light and clumps hard. Sift, then spoon and level.",
  },
  {
    id: "chocolate-chips",
    name: "Chocolate chips",
    group: "Chocolate, nuts & mix-ins",
    gramsPerCup: 170,
  },
  {
    id: "almonds",
    name: "Almonds (whole)",
    group: "Chocolate, nuts & mix-ins",
    gramsPerCup: 143,
  },
  {
    id: "cashews",
    name: "Cashews (whole)",
    group: "Chocolate, nuts & mix-ins",
    gramsPerCup: 137,
  },
  {
    id: "walnuts",
    name: "Walnuts (chopped)",
    group: "Chocolate, nuts & mix-ins",
    gramsPerCup: 117,
  },
  {
    id: "coconut",
    name: "Desiccated coconut",
    group: "Chocolate, nuts & mix-ins",
    gramsPerCup: 85,
  },
  {
    id: "raisins",
    name: "Raisins (kishmish)",
    group: "Chocolate, nuts & mix-ins",
    gramsPerCup: 145,
  },
  {
    id: "rice",
    name: "Rice (uncooked, long grain)",
    group: "Chocolate, nuts & mix-ins",
    gramsPerCup: 185,
  },

  {
    id: "salt",
    name: "Table salt",
    group: "Salt & leaveners",
    gramsPerCup: 288,
    note: "1 tsp = 6 g. Kosher and rock salt are far lighter by volume — swap by weight, not by spoon.",
  },
  {
    id: "baking-powder",
    name: "Baking powder",
    group: "Salt & leaveners",
    gramsPerCup: 192,
    note: "1 tsp = 4 g. Leaveners are the one place a spoon really is good enough.",
  },
  {
    id: "baking-soda",
    name: "Baking soda",
    group: "Salt & leaveners",
    gramsPerCup: 220,
    note: "1 tsp = 4.6 g. Measure this one carefully — too much tastes soapy.",
  },
];

export const popularIds = [
  "flour-ap",
  "sugar-granulated",
  "butter",
  "milk",
  "cocoa",
  "water",
];

export const ingredientGroups = [
  "Flours & starches",
  "Sugars & syrups",
  "Fats & oils",
  "Liquids & dairy",
  "Chocolate, nuts & mix-ins",
  "Salt & leaveners",
];
