export const spiritAnimals = [
  {
    id: "wolf",
    name: "Wolf",
    emoji: "Wolf",
    element: "Air",
    traits: ["Loyalty", "Intelligence", "Freedom", "Community"],
    description: "The Wolf is a powerful symbol of loyalty, family, and deep intuition. Wolves are fiercely protective of their pack and possess incredible intelligence and communication skills.",
    strengths: "Deeply loyal, intuitive, protective, strong community bonds, excellent communicator",
    weaknesses: "Can be overly trusting, sometimes stubborn, may isolate when hurt",
    careerPaths: "Leader, counselor, team manager, social worker, wildlife biologist",
    loveStyle: "Devoted and passionate. Wolves mate for life and prioritize their partner above all else.",
    lifeLesson: "Learn to balance independence with the need for community and connection.",
  },
  {
    id: "eagle",
    name: "Eagle",
    emoji: "Eagle",
    element: "Air",
    traits: ["Vision", "Freedom", "Courage", "Spirituality"],
    description: "The Eagle represents visionary thinking, spiritual connection, and the courage to rise above challenges. Eagles see the bigger picture that others miss.",
    strengths: "Visionary, spiritually connected, courageous, free-spirited, inspirational",
    weaknesses: "Can be impatient, may seem distant, tendency to avoid details",
    careerPaths: "Pilot, philosopher, spiritual guide, CEO, adventurer",
    loveStyle: "Needs a partner who respects freedom and shares high ideals. Loves deeply but on their own terms.",
    lifeLesson: "Learn to come down from the heights and connect with everyday life.",
  },
  {
    id: "bear",
    name: "Bear",
    emoji: "Bear",
    element: "Earth",
    traits: ["Strength", "Protection", "Wisdom", "Healing"],
    description: "The Bear embodies quiet strength, maternal protection, and deep healing wisdom. Bears teach us the power of solitude and introspection.",
    strengths: "Quietly powerful, deeply nurturing, wise, patient, excellent healer",
    weaknesses: "Can be slow to act, tendency to hibernate (avoid problems), overly protective",
    careerPaths: "Healer, therapist, counselor, farmer, yoga instructor",
    loveStyle: "Warm, protective, and deeply caring. Creates a safe and loving home for their partner.",
    lifeLesson: "Learn that vulnerability is not weakness — it takes courage to be open.",
  },
  {
    id: "owl",
    name: "Owl",
    emoji: "Owl",
    element: "Air",
    traits: ["Wisdom", "Mystery", "Intuition", "Truth"],
    description: "The Owl is the keeper of wisdom and truth. Owls see through deception and darkness, revealing hidden knowledge and spiritual insights.",
    strengths: "Wise, perceptive, intuitive, mysterious, sees truth clearly",
    weaknesses: "Can be secretive, nocturnal tendencies (avoid social situations), overthinker",
    careerPaths: "Researcher, detective, professor, astrologer, psychiatrist",
    loveStyle: "Needs intellectual and spiritual depth in a relationship. Values honest conversation over superficial connection.",
    lifeLesson: "Learn to share your wisdom with others instead of keeping it hidden.",
  },
  {
    id: "dolphin",
    name: "Dolphin",
    emoji: "Dolphin",
    element: "Water",
    traits: ["Joy", "Harmony", "Playfulness", "Intelligence"],
    description: "The Dolphin radiates joy, playfulness, and emotional intelligence. Dolphins navigate life with grace and bring lightness wherever they go.",
    strengths: "Joyful, emotionally intelligent, social, playful, healer of others",
    weaknesses: "Can be overly sensitive, tendency to avoid conflict, may suppress own needs",
    careerPaths: "Entertainer, marine biologist, therapist, artist, humanitarian",
    loveStyle: "Playful, romantic, and deeply emotional. Creates a joyful and harmonious relationship.",
    lifeLesson: "Learn that it's okay to be serious sometimes and face difficult emotions.",
  },
  {
    id: "tiger",
    name: "Tiger",
    emoji: "Tiger",
    element: "Fire",
    traits: ["Courage", "Power", "Passion", "Independence"],
    description: "The Tiger embodies raw power, courage, and fierce independence. Tigers walk their own path with unmatched confidence and passion.",
    strengths: "Brave, powerful, passionate, independent, magnetic presence",
    weaknesses: "Can be impulsive, overly competitive, difficulty showing vulnerability",
    careerPaths: "Entrepreneur, athlete, performer, activist, military leader",
    loveStyle: "Intense and passionate. Loves deeply but needs space and freedom to be themselves.",
    lifeLesson: "Learn that true strength includes knowing when to ask for help.",
  },
  {
    id: "fox",
    name: "Fox",
    emoji: "Fox",
    element: "Fire",
    traits: ["Cleverness", "Adaptability", "Wit", "Resourcefulness"],
    description: "The Fox represents quick thinking, adaptability, and cunning intelligence. Foxes thrive in any environment by using their sharp wits.",
    strengths: "Clever, adaptable, resourceful, charming, excellent problem solver",
    weaknesses: "Can be sly, tendency to manipulate, difficulty trusting others fully",
    careerPaths: "Strategist, diplomat, inventor, journalist, detective",
    loveStyle: "Witty and charming in love. Needs a partner who appreciates their intelligence and doesn't try to cage them.",
    lifeLesson: "Learn that honesty and directness are more valuable than cleverness.",
  },
  {
    id: "elephant",
    name: "Elephant",
    emoji: "Elephant",
    element: "Earth",
    traits: ["Memory", "Loyalty", "Patience", "Leadership"],
    description: "The Elephant embodies deep memory, unwavering loyalty, and gentle leadership. Elephants carry ancient wisdom and never forget.",
    strengths: "Incredible memory, deeply loyal, patient, natural leader, strong family bonds",
    weaknesses: "Can hold grudges, slow to forgive, tendency to carry too much responsibility",
    careerPaths: "Historian, family therapist, political leader, archivist, community organizer",
    loveStyle: "Deeply committed and romantic. Remembers every detail about their partner and creates lasting traditions.",
    lifeLesson: "Learn to let go of past hurts and embrace the present moment.",
  },
  {
    id: "butterfly",
    name: "Butterfly",
    emoji: "Butterfly",
    element: "Air",
    traits: ["Transformation", "Beauty", "Freedom", "Joy"],
    description: "The Butterfly represents transformation, beauty, and the magic of change. Butterflies remind us that growth comes through metamorphosis.",
    strengths: "Transformative, beautiful spirit, free, joyful, inspires change in others",
    weaknesses: "Can be restless, difficulty committing, may avoid depth for beauty",
    careerPaths: "Artist, designer, life coach, travel writer, motivational speaker",
    loveStyle: "Romantic and free-spirited. Brings beauty and excitement to relationships.",
    lifeLesson: "Learn that true beauty comes from within, and transformation is a lifelong journey.",
  },
  {
    id: "snake",
    name: "Snake",
    emoji: "Snake",
    element: "Water",
    traits: ["Healing", "Transformation", "Mystery", "Intuition"],
    description: "The Snake embodies healing, deep transformation, and powerful intuition. Snakes shed their skin to be reborn, symbolizing renewal.",
    strengths: "Powerful healer, deeply intuitive, transformative, mysterious, wise",
    weaknesses: "Can be secretive, tendency to be misunderstood, may be vengeful",
    careerPaths: "Healer, doctor, alchemist, researcher, spiritual teacher",
    loveStyle: "Intense and transformative. Loves deeply and heals through connection.",
    lifeLesson: "Learn to shed old patterns and embrace your own transformation.",
  },
  {
    id: "raven",
    name: "Raven",
    emoji: "Raven",
    element: "Air",
    traits: ["Mystery", "Magic", "Intelligence", "Transformation"],
    description: "The Raven represents magic, mystery, and profound intelligence. Ravens are messengers between worlds and keepers of ancient secrets.",
    strengths: "Magical, deeply intelligent, transformative, creative, prophetic",
    weaknesses: "Can be dark or brooding, tendency to isolate, may be misunderstood",
    careerPaths: "Writer, magician, musician, philosopher, shaman",
    loveStyle: "Deeply passionate and mysterious. Loves with intensity and seeks a soul-level connection.",
    lifeLesson: "Learn to bring light to darkness and share your gifts with the world.",
  },
  {
    id: "lion",
    name: "Lion",
    emoji: "Lion",
    element: "Fire",
    traits: ["Courage", "Leadership", "Nobility", "Generosity"],
    description: "The Lion embodies royalty, courage, and generous leadership. Lions inspire others through their natural authority and warm heart.",
    strengths: "Natural leader, courageous, generous, noble, inspiring",
    weaknesses: "Can be prideful, domineering, difficulty admitting mistakes",
    careerPaths: "Executive, royalty, teacher, judge, non-profit leader",
    loveStyle: "Protective and generous. Treats their partner like royalty and expects loyalty in return.",
    lifeLesson: "Learn that true leadership means serving others, not commanding them.",
  },
  {
    id: "hummingbird",
    name: "Hummingbird",
    emoji: "Hummingbird",
    element: "Air",
    traits: ["Joy", "Energy", "Adaptability", "Beauty"],
    description: "The Hummingbird radiates joy, boundless energy, and the ability to find sweetness in life. They remind us to enjoy every moment.",
    strengths: "Energetic, joyful, adaptable, brings happiness, finds beauty everywhere",
    weaknesses: "Can be restless, difficulty settling down, may avoid deeper issues",
    careerPaths: "Dancer, athlete, social media influencer, florist, travel blogger",
    loveStyle: "Energetic and romantic. Keeps the spark alive and brings constant excitement.",
    lifeLesson: "Learn to slow down and find peace in stillness.",
  },
  {
    id: "turtle",
    name: "Turtle",
    emoji: "Turtle",
    element: "Water",
    traits: ["Patience", "Wisdom", "Protection", "Endurance"],
    description: "The Turtle embodies patience, ancient wisdom, and steady endurance. Turtles carry their home on their back, symbolizing groundedness.",
    strengths: "Patient, wise, enduring, protective, deeply grounded",
    weaknesses: "Can be slow to change, overly cautious, tendency to withdraw into shell",
    careerPaths: "Philosopher, historian, gardener, counselor, monk",
    loveStyle: "Steady and devoted. Creates a safe and comfortable home for their loved ones.",
    lifeLesson: "Learn that slow and steady wins the race, but don't forget to enjoy the journey.",
  },
  {
    id: "hawk",
    name: "Hawk",
    emoji: "Hawk",
    element: "Air",
    traits: ["Vision", "Focus", "Courage", "Awareness"],
    description: "The Hawk represents sharp vision, laser focus, and heightened awareness. Hawks see what others miss and act with precision.",
    strengths: "Sharp vision, focused, courageous, highly aware, decisive",
    weaknesses: "Can be overly intense, difficulty relaxing, may be too focused on goals",
    careerPaths: "Pilot, surgeon, sniper, detective, business analyst",
    loveStyle: "Focused and passionate. Once they choose a partner, they are devoted and protective.",
    lifeLesson: "Learn to broaden your vision beyond the immediate target.",
  },
  {
    id: "deer",
    name: "Deer",
    emoji: "Deer",
    element: "Earth",
    traits: ["Gentleness", "Grace", "Intuition", "Peace"],
    description: "The Deer embodies gentleness, grace, and deep intuition. Deers navigate life with softness and bring peace wherever they roam.",
    strengths: "Gentle, graceful, intuitive, peaceful, deeply compassionate",
    weaknesses: "Can be timid, overly sensitive, difficulty standing up for themselves",
    careerPaths: "Nurse, veterinarian, artist, counselor, yoga teacher",
    loveStyle: "Tender and romantic. Creates a gentle and harmonious relationship full of care.",
    lifeLesson: "Learn that gentleness is a form of strength, and boundaries protect peace.",
  },
];

export const quizQuestions = [
  {
    id: 1,
    question: "You're walking through a forest at dawn. What catches your attention first?",
    options: [
      { text: "The distant call of a bird soaring above", animals: ["eagle", "hawk", "raven"] },
      { text: "A family of animals moving together", animals: ["wolf", "elephant", "deer"] },
      { text: "A flash of color among the green", animals: ["butterfly", "hummingbird", "fox"] },
      { text: "The deep silence and stillness of the woods", animals: ["owl", "bear", "turtle"] },
    ],
  },
  {
    id: 2,
    question: "How do you recharge after a long, draining day?",
    options: [
      { text: "Retreat to a quiet space and reflect alone", animals: ["owl", "snake", "raven"] },
      { text: "Spend time with close friends or family", animals: ["wolf", "elephant", "dolphin"] },
      { text: "Go for a run, dance, or do something active", animals: ["tiger", "hummingbird", "hawk"] },
      { text: "Wrap up in something cozy and just rest", animals: ["bear", "turtle", "deer"] },
    ],
  },
  {
    id: 3,
    question: "What role do you naturally take in a group?",
    options: [
      { text: "The leader who directs and inspires", animals: ["lion", "eagle", "tiger"] },
      { text: "The mediator who keeps peace", animals: ["dolphin", "deer", "turtle"] },
      { text: "The strategist who plans every move", animals: ["fox", "owl", "hawk"] },
      { text: "The heart who supports everyone emotionally", animals: ["bear", "wolf", "elephant"] },
    ],
  },
  {
    id: 4,
    question: "What element resonates with you the most?",
    options: [
      { text: "Fire — Passionate, bold, transformative", animals: ["tiger", "lion", "fox"] },
      { text: "Water — Intuitive, flowing, deep", animals: ["dolphin", "snake", "turtle"] },
      { text: "Air — Free, visionary, intellectual", animals: ["eagle", "owl", "raven"] },
      { text: "Earth — Grounded, nurturing, patient", animals: ["bear", "elephant", "deer"] },
    ],
  },
  {
    id: 5,
    question: "Which scenario excites you the most?",
    options: [
      { text: "Exploring an uncharted territory", animals: ["eagle", "fox", "hummingbird"] },
      { text: "Deep conversation about life's mysteries", animals: ["owl", "raven", "snake"] },
      { text: "A big celebration with everyone you love", animals: ["wolf", "lion", "dolphin"] },
      { text: "A peaceful day in nature, just being", animals: ["turtle", "deer", "bear"] },
    ],
  },
  {
    id: 6,
    question: "What's your biggest strength?",
    options: [
      { text: "Unwavering loyalty and protectiveness", animals: ["wolf", "elephant", "bear"] },
      { text: "Sharp mind and quick thinking", animals: ["fox", "owl", "hawk"] },
      { text: "Ability to inspire and lead others", animals: ["lion", "eagle", "tiger"] },
      { text: "Deep empathy and healing energy", animals: ["dolphin", "deer", "snake"] },
    ],
  },
  {
    id: 7,
    question: "How do others typically describe you?",
    options: [
      { text: "Mysterious and hard to figure out", animals: ["raven", "owl", "snake"] },
      { text: "Fun, energetic, and always on the move", animals: ["hummingbird", "fox", "butterfly"] },
      { text: "Strong, reliable, and calm under pressure", animals: ["bear", "elephant", "turtle"] },
      { text: "Brave, confident, and inspiring", animals: ["lion", "tiger", "eagle"] },
    ],
  },
  {
    id: 8,
    question: "What environment makes you feel most alive?",
    options: [
      { text: "Mountains — above the clouds, close to the sky", animals: ["eagle", "hawk", "mountain lion"] },
      { text: "Ocean — deep, mysterious, full of life", animals: ["dolphin", "turtle", "snake"] },
      { text: "Dense forest — hidden, magical, alive", animals: ["fox", "owl", "deer"] },
      { text: "Open savanna — vast, free, powerful", animals: ["lion", "wolf", "tiger"] },
    ],
  },
  {
    id: 9,
    question: "What legacy do you want to leave behind?",
    options: [
      { text: "That I was a devoted friend and family member", animals: ["wolf", "elephant", "bear"] },
      { text: "That I made the world a better, more beautiful place", animals: ["butterfly", "hummingbird", "deer"] },
      { text: "That I achieved great things and inspired others", animals: ["lion", "eagle", "tiger"] },
      { text: "That I uncovered deep truths and shared wisdom", animals: ["owl", "raven", "snake"] },
    ],
  },
  {
    id: 10,
    question: "Pick the feeling that comes most naturally to you:",
    options: [
      { text: "Curiosity — always wanting to learn more", animals: ["owl", "fox", "raven"] },
      { text: "Compassion — feeling others' pain deeply", animals: ["dolphin", "deer", "bear"] },
      { text: "Determination — never giving up on goals", animals: ["tiger", "lion", "hawk"] },
      { text: "Joy — finding happiness in small things", animals: ["hummingbird", "butterfly", "dolphin"] },
    ],
  },
];
