export const QUESTIONS = [
  {
    id: "budget",
    label: "What's your budget?",
    options: [
      { value: "budget", label: "Budget-friendly", icon: "wallet" },
      { value: "moderate", label: "Moderate", icon: "credit-card" },
      { value: "luxury", label: "Luxury", icon: "crown" },
    ],
  },
  {
    id: "climate",
    label: "Preferred climate?",
    options: [
      { value: "tropical", label: "Tropical", icon: "sun" },
      { value: "temperate", label: "Mild / Temperate", icon: "cloud-sun" },
      { value: "cold", label: "Cold / Alpine", icon: "snowflake" },
      { value: "arid", label: "Dry / Desert", icon: "sun" },
    ],
  },
  {
    id: "activity",
    label: "What kind of trip?",
    options: [
      { value: "beach", label: "Beach & Relaxation", icon: "umbrella-beach" },
      { value: "adventure", label: "Adventure & Outdoors", icon: "mountain" },
      { value: "culture", label: "Culture & History", icon: "landmark" },
      { value: "nature", label: "Nature & Wildlife", icon: "tree" },
      { value: "urban", label: "City & Nightlife", icon: "building" },
      { value: "food", label: "Food & Culinary", icon: "utensils" },
    ],
  },
  {
    id: "travelStyle",
    label: "Travel style?",
    options: [
      { value: "solo", label: "Solo Adventure", icon: "user" },
      { value: "couple", label: "Romantic Getaway", icon: "heart" },
      { value: "family", label: "Family Trip", icon: "users" },
      { value: "group", label: "Group Trip", icon: "users" },
    ],
  },
  {
    id: "season",
    label: "Preferred season?",
    options: [
      { value: "spring", label: "Spring", icon: "flower" },
      { value: "summer", label: "Summer", icon: "sun" },
      { value: "fall", label: "Fall", icon: "leaf" },
      { value: "winter", label: "Winter", icon: "snowflake" },
    ],
  },
  {
    id: "duration",
    label: "Trip duration?",
    options: [
      { value: "weekend", label: "Weekend (2-3 days)", icon: "calendar" },
      { value: "week", label: "One Week", icon: "calendar" },
      { value: "twoWeeks", label: "Two Weeks", icon: "calendar" },
      { value: "month", label: "Month+", icon: "calendar" },
    ],
  },
  {
    id: "continent",
    label: "Preferred continent?",
    options: [
      { value: "any", label: "No preference", icon: "globe" },
      { value: "europe", label: "Europe", icon: "globe" },
      { value: "asia", label: "Asia", icon: "globe" },
      { value: "northAmerica", label: "North America", icon: "globe" },
      { value: "southAmerica", label: "South America", icon: "globe" },
      { value: "africa", label: "Africa", icon: "globe" },
      { value: "oceania", label: "Oceania", icon: "globe" },
    ],
  },
];

const DESTINATIONS = [
  {
    name: "Bali",
    country: "Indonesia",
    continent: "asia",
    budget: ["budget", "moderate"],
    climate: ["tropical"],
    activity: ["beach", "nature", "culture", "food"],
    travelStyle: ["solo", "couple", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["week", "twoWeeks", "month"],
    bestTime: "April to October",
    description:
      "The Island of the Gods offers lush rice terraces, ancient temples, vibrant coral reefs, and a world-famous wellness scene. Ubud's arts and culture blend perfectly with Seminyak's beach clubs and Uluwatu's surf breaks.",
    highlights: [
      "Sacred Monkey Forest",
      "Tegallalang Rice Terraces",
      "Uluwatu Temple",
      "Mount Batur sunrise trek",
      "Tirta Empul holy water temple",
    ],
    cuisine: "Nasi Goreng, Babi Guling, Satay, Lawar, Mie Goreng",
    costEstimate: "$40-120/day",
    funFact: "Bali has its own calendar system called the Pawukon, which is 210 days long.",
    rating: 4.7,
  },
  {
    name: "Santorini",
    country: "Greece",
    continent: "europe",
    budget: ["moderate", "luxury"],
    climate: ["temperate"],
    activity: ["beach", "culture", "food", "urban"],
    travelStyle: ["couple", "solo", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["weekend", "week", "twoWeeks"],
    bestTime: "June to September",
    description:
      "Famous for its stunning sunsets, whitewashed buildings with blue domes, and dramatic caldera views. Santorini offers exceptional wine, volcanic beaches, and Minoan archaeological sites.",
    highlights: [
      "Oia sunset viewpoint",
      "Red Beach",
      "Akrotiri archaeological site",
      "Fira to Oia hiking trail",
      "Wine tasting at local vineyards",
    ],
    cuisine: "Fava, Tomatokeftedes, Souvlaki, Fresh seafood, Vinsanto wine",
    costEstimate: "$120-300/day",
    funFact: "Santorini's iconic blue-domed churches were painted blue and white to match the Greek flag.",
    rating: 4.6,
  },
  {
    name: "Kyoto",
    country: "Japan",
    continent: "asia",
    budget: ["moderate", "luxury"],
    climate: ["temperate"],
    activity: ["culture", "food", "urban", "nature"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "fall"],
    duration: ["weekend", "week", "twoWeeks"],
    bestTime: "March to May & October to November",
    description:
      "Japan's cultural heart, Kyoto is home to over 2,000 temples and shrines, serene bamboo groves, traditional tea houses, and exquisite kaiseki cuisine. Cherry blossom season is truly magical.",
    highlights: [
      "Fushimi Inari Shrine",
      "Arashiyama Bamboo Grove",
      "Kinkaku-ji (Golden Pavilion)",
      "Nishiki Market",
      "Geisha district of Gion",
    ],
    cuisine: "Kaiseki, Yudofu, Matcha desserts, Soba, Kyo-ryori",
    costEstimate: "$100-250/day",
    funFact: "Kyoto was the capital of Japan for over 1,000 years before Tokyo took over in 1868.",
    rating: 4.8,
  },
  {
    name: "Machu Picchu & Cusco",
    country: "Peru",
    continent: "southAmerica",
    budget: ["budget", "moderate"],
    climate: ["temperate", "cold"],
    activity: ["adventure", "culture", "nature"],
    travelStyle: ["solo", "couple", "group", "family"],
    season: ["spring", "summer", "fall"],
    duration: ["week", "twoWeeks"],
    bestTime: "May to September",
    description:
      "Explore the ancient Inca citadel of Machu Picchu, wander through Cusco's cobblestone streets, and trek the Sacred Valley. A bucket-list destination blending history, adventure, and stunning Andean scenery.",
    highlights: [
      "Machu Picchu sunrise",
      "Inca Trail trek",
      "Sacred Valley",
      "Cusco's Plaza de Armas",
      "Rainbow Mountain",
    ],
    cuisine: "Ceviche, Lomo Saltado, Quinoa soup, Alpaca steak, Pisco Sour",
    costEstimate: "$40-100/day",
    funFact: "Machu Picchu was never discovered by the Spanish conquistadors and remained unknown to the outside world until 1911.",
    rating: 4.7,
  },
  {
    name: "Maldives",
    country: "Maldives",
    continent: "asia",
    budget: ["luxury"],
    climate: ["tropical"],
    activity: ["beach", "nature"],
    travelStyle: ["couple", "solo", "family"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["weekend", "week", "twoWeeks"],
    bestTime: "November to April",
    description:
      "The ultimate tropical paradise — overwater bungalows, crystal-clear turquoise waters, vibrant coral reefs, and pristine white-sand beaches. Perfect for honeymoons and luxury escapes.",
    highlights: [
      "Overwater bungalow stay",
      "Snorkeling with manta rays",
      "Underwater restaurant dining",
      "Sunset dolphin cruise",
      "Private sandbank picnics",
    ],
    cuisine: "Mas Huni, Garudhiya, Fresh tuna, Coconut-based curries",
    costEstimate: "$300-800/day",
    funFact: "The Maldives is the flattest country on Earth, with an average elevation of just 1.5 meters above sea level.",
    rating: 4.8,
  },
  {
    name: "Amalfi Coast",
    country: "Italy",
    continent: "europe",
    budget: ["moderate", "luxury"],
    climate: ["temperate"],
    activity: ["beach", "culture", "food", "urban"],
    travelStyle: ["couple", "family", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["weekend", "week", "twoWeeks"],
    bestTime: "May to September",
    description:
      "A dramatic stretch of coastline dotted with pastel-coloured villages clinging to cliffs above the Mediterranean. Positano, Amalfi, and Ravello offer breathtaking views, limoncello, and incredible Italian cuisine.",
    highlights: [
      "Positano's colourful houses",
      "Path of the Gods hike",
      "Amalfi Cathedral",
      "Ravello's Villa Rufolo gardens",
      "Capri boat trip",
    ],
    cuisine: "Limoncello, Fresh seafood, Scialatielli pasta, Mozzarella di Bufala",
    costEstimate: "$150-350/day",
    funFact: "The Amalfi Coast was a maritime superpower in the 11th century, rivaling Venice and Genoa.",
    rating: 4.7,
  },
  {
    name: "Queenstown",
    country: "New Zealand",
    continent: "oceania",
    budget: ["moderate", "luxury"],
    climate: ["temperate", "cold"],
    activity: ["adventure", "nature", "beach"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["weekend", "week", "twoWeeks"],
    bestTime: "December to March (summer), June to August (ski)",
    description:
      "The adventure capital of the world, nestled on Lake Wakatipu with the Remarkables mountain range as backdrop. Bungee jumping, skiing, Milford Sound, and Hobbiton are just the beginning.",
    highlights: [
      "Bungee jumping (original AJ Hackett site)",
      "Milford Sound cruise",
      "Skiing at The Remarkables",
      "Shotover River jet boating",
      "Glenorchy (Lothlórien from LOTR)",
    ],
    cuisine: "Paua, Lamb dishes, Green-lipped mussels, Sauvignon Blanc",
    costEstimate: "$100-250/day",
    funFact: "Queenstown was named after Queen Victoria and is often called the 'Adventure Capital of the World'.",
    rating: 4.6,
  },
  {
    name: "Reykjavík & the Golden Circle",
    country: "Iceland",
    continent: "europe",
    budget: ["moderate", "luxury"],
    climate: ["cold"],
    activity: ["adventure", "nature", "culture"],
    travelStyle: ["solo", "couple", "group", "family"],
    season: ["summer", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "June to August for midnight sun, September to March for Northern Lights",
    description:
      "A land of fire and ice — geothermal hot springs, majestic waterfalls, otherworldly lava fields, and the chance to see the Northern Lights. Iceland offers one of the most unique travel experiences on Earth.",
    highlights: [
      "Blue Lagoon or Sky Lagoon",
      "Northern Lights hunting",
      "Gullfoss & Geysir",
      "Thingvellir National Park",
      "Ice cave tours on Vatnajökull",
    ],
    cuisine: "Skyr, Lamb soup, Hot dogs (Bæjarins Beztu), Rye bread, Fermented shark",
    costEstimate: "$150-400/day",
    funFact: "Iceland has no standing army, navy, or air force. It's also one of the most peaceful countries in the world.",
    rating: 4.7,
  },
  {
    name: "Marrakech",
    country: "Morocco",
    continent: "africa",
    budget: ["budget", "moderate"],
    climate: ["arid"],
    activity: ["culture", "food", "urban", "adventure"],
    travelStyle: ["solo", "couple", "group", "family"],
    season: ["spring", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "March to May & September to November",
    description:
      "A sensory explosion — vibrant souks, ornate palaces, fragrant spice markets, and the bustling Jemaa el-Fnaa square. The Atlas Mountains and Sahara Desert are just a day trip away.",
    highlights: [
      "Jemaa el-Fnaa square",
      "Bahia Palace",
      "Majorelle Garden",
      "Sahara Desert camel trek",
      "Atlas Mountains day trip",
    ],
    cuisine: "Tagine, Couscous, Pastilla, Mint tea, Harira soup",
    costEstimate: "$30-100/day",
    funFact: "Marrakech's medina (old city) is a UNESCO World Heritage site and one of the most densely populated areas in Africa.",
    rating: 4.5,
  },
  {
    name: "Banff National Park",
    country: "Canada",
    continent: "northAmerica",
    budget: ["moderate", "luxury"],
    climate: ["cold", "temperate"],
    activity: ["adventure", "nature", "beach"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["weekend", "week", "twoWeeks"],
    bestTime: "June to August (hiking), December to March (skiing)",
    description:
      "Canada's oldest national park is a wilderness wonderland of turquoise glacial lakes, towering peaks, and abundant wildlife. Lake Louise and Moraine Lake are among the most photographed places on Earth.",
    highlights: [
      "Lake Louise",
      "Moraine Lake",
      "Icefields Parkway",
      "Banff Upper Hot Springs",
      "Skiing at Sunshine Village",
    ],
    cuisine: "Poutine, Alberta beef, Maple syrup treats, Wild berries",
    costEstimate: "$100-250/day",
    funFact: "Banff National Park was established in 1885, making it Canada's first national park and the third oldest in the world.",
    rating: 4.8,
  },
  {
    name: "Barcelona",
    country: "Spain",
    continent: "europe",
    budget: ["budget", "moderate", "luxury"],
    climate: ["temperate"],
    activity: ["urban", "culture", "food", "beach"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["weekend", "week"],
    bestTime: "May to October",
    description:
      "A Mediterranean gem blending Gaudí's whimsical architecture, world-class tapas, vibrant street life, and sandy beaches. From the Gothic Quarter to Park Güell, Barcelona captivates every visitor.",
    highlights: [
      "Sagrada Familia",
      "Park Güell",
      "Gothic Quarter",
      "La Boqueria market",
      "Barceloneta Beach",
    ],
    cuisine: "Paella, Tapas, Jamón ibérico, Crema catalana, Cava",
    costEstimate: "$60-200/day",
    funFact: "Barcelona's famous La Sagrada Familia has been under construction since 1882 and is expected to be completed in 2026.",
    rating: 4.6,
  },
  {
    name: "Zanzibar",
    country: "Tanzania",
    continent: "africa",
    budget: ["budget", "moderate"],
    climate: ["tropical"],
    activity: ["beach", "culture", "food", "nature"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["week", "twoWeeks"],
    bestTime: "June to October",
    description:
      "The Spice Island — turquoise waters, white-sand beaches, historic Stone Town, and spice plantations. Zanzibar offers a perfect blend of Swahili culture, beach relaxation, and rich history.",
    highlights: [
      "Stone Town labyrinth",
      "Prison Island giant tortoises",
      "Spice plantation tours",
      "Nungwi Beach sunsets",
      "Jozani Forest red colobus monkeys",
    ],
    cuisine: "Zanzibar pizza, Octopus curry, Pilau, Fresh mango, Spice tea",
    costEstimate: "$40-120/day",
    funFact: "Zanzibar is known as the 'Spice Island' because it produces most of the world's cloves.",
    rating: 4.5,
  },
  {
    name: "Tokyo",
    country: "Japan",
    continent: "asia",
    budget: ["budget", "moderate", "luxury"],
    climate: ["temperate"],
    activity: ["urban", "culture", "food", "adventure"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "fall", "winter"],
    duration: ["weekend", "week", "twoWeeks"],
    bestTime: "March to May & October to December",
    description:
      "A dazzling blend of ultramodern and traditional — neon-lit skyscrapers, serene temples, world-class sushi, and an unmatched pop culture scene. Tokyo is a city that never stops surprising.",
    highlights: [
      "Shibuya Crossing",
      "Senso-ji Temple",
      "Akihabara Electric Town",
      "Tsukiji Outer Market",
      "Shinjuku Gyoen gardens",
    ],
    cuisine: "Sushi, Ramen, Tempura, Okonomiyaki, Matcha sweets",
    costEstimate: "$80-250/day",
    funFact: "Tokyo was originally a small fishing village called Edo before becoming the capital of Japan in 1868.",
    rating: 4.8,
  },
  {
    name: "Cape Town",
    country: "South Africa",
    continent: "africa",
    budget: ["budget", "moderate", "luxury"],
    climate: ["temperate"],
    activity: ["nature", "adventure", "beach", "urban", "food"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["week", "twoWeeks"],
    bestTime: "November to March",
    description:
      "Where the Atlantic meets Table Mountain — stunning beaches, a world-class food and wine scene, penguins at Boulders Beach, and the dramatic Cape Peninsula. One of the most beautiful cities on Earth.",
    highlights: [
      "Table Mountain hike or cable car",
      "Boulders Beach penguins",
      "Cape of Good Hope",
      "V&A Waterfront",
      "Stellenbosch wine tour",
    ],
    cuisine: "Bobotie, Braai (BBQ), Biltong, Cape Malay curry, Local wines",
    costEstimate: "$50-180/day",
    funFact: "Cape Town is the oldest city in South Africa and was founded in 1652 by the Dutch East India Company.",
    rating: 4.7,
  },
  {
    name: "Paris",
    country: "France",
    continent: "europe",
    budget: ["moderate", "luxury"],
    climate: ["temperate"],
    activity: ["culture", "urban", "food"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["weekend", "week"],
    bestTime: "April to October",
    description:
      "The City of Light — iconic landmarks, world-class museums, charming sidewalk cafés, and unparalleled cuisine. From the Eiffel Tower to Montmartre, Paris is the epitome of romance and culture.",
    highlights: [
      "Eiffel Tower",
      "Louvre Museum",
      "Notre-Dame Cathedral",
      "Montmartre & Sacré-Cœur",
      "Seine river cruise",
    ],
    cuisine: "Croissants, Baguettes, Cheese, Escargots, Crème brûlée",
    costEstimate: "$150-400/day",
    funFact: "The Eiffel Tower was originally built as a temporary structure for the 1889 World's Fair and was nearly torn down in 1909.",
    rating: 4.6,
  },
  {
    name: "Raja Ampat",
    country: "Indonesia",
    continent: "asia",
    budget: ["moderate", "luxury"],
    climate: ["tropical"],
    activity: ["nature", "beach"],
    travelStyle: ["solo", "couple", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["week", "twoWeeks"],
    bestTime: "October to April",
    description:
      "The world's most biodiverse marine environment — remote islands, pristine coral reefs, and crystal-clear waters. A paradise for divers and nature lovers seeking untouched beauty.",
    highlights: [
      "Diving at Cape Kri",
      "Wayag Islands viewpoint",
      "Pianemo Lagoon",
      "Manta ray snorkeling",
      "Sunset at Piaynemo",
    ],
    cuisine: "Fresh grilled fish, Papuan sago, Coconut rice, Exotic fruits",
    costEstimate: "$80-200/day",
    funFact: "Raja Ampat's marine ecosystem contains over 75% of all known coral species in the world.",
    rating: 4.9,
  },
  {
    name: "Dubai",
    country: "UAE",
    continent: "asia",
    budget: ["luxury", "moderate"],
    climate: ["arid"],
    activity: ["urban", "adventure", "luxury", "beach"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "November to March",
    description:
      "A city of superlatives — the world's tallest building, largest mall, indoor ski slope, and man-made islands. Dubai blends ultra-luxury with desert adventures and futuristic architecture.",
    highlights: [
      "Burj Khalifa observation deck",
      "Dubai Mall & souks",
      "Desert safari dune bashing",
      "Palm Jumeirah",
      "Dubai Marina walk",
    ],
    cuisine: "Shawarma, Hummus, Camel meat, Arabic coffee, Dates",
    costEstimate: "$200-600/day",
    funFact: "Dubai has the world's first 7-star hotel (Burj Al Arab) and the tallest building (Burj Khalifa at 828m).",
    rating: 4.5,
  },
  {
    name: "Patagonia",
    country: "Chile & Argentina",
    continent: "southAmerica",
    budget: ["moderate", "luxury"],
    climate: ["cold", "temperate"],
    activity: ["adventure", "nature"],
    travelStyle: ["solo", "couple", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["twoWeeks", "month"],
    bestTime: "October to March",
    description:
      "One of the most spectacular wilderness regions on Earth — massive glaciers, towering granite peaks, pristine lakes, and vast steppe. Torres del Paine and Perito Moreno Glacier are must-sees.",
    highlights: [
      "Torres del Paine W Trek",
      "Perito Moreno Glacier",
      "Grey Glacier kayaking",
      "Ushuaia (End of the World)",
      "Cape Horn",
    ],
    cuisine: "Patagonian lamb, King crab, Calafate berries, Argentine beef, Malbec wine",
    costEstimate: "$80-200/day",
    funFact: "Patagonia spans two countries (Chile and Argentina) and covers an area roughly the size of Germany.",
    rating: 4.8,
  },
  {
    name: "Tulum",
    country: "Mexico",
    continent: "northAmerica",
    budget: ["budget", "moderate"],
    climate: ["tropical"],
    activity: ["beach", "culture", "nature", "food"],
    travelStyle: ["solo", "couple", "group"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "December to April",
    description:
      "Bohemian beach town meets ancient Mayan ruins — clifftop temples overlooking turquoise Caribbean waters, crystal-clear cenotes, and a vibrant eco-chic vibe. Perfect for mindful travelers.",
    highlights: [
      "Tulum ruins cliffside",
      "Gran Cenote swimming",
      "Cenote Dos Ojos",
      "Sian Ka'an Biosphere Reserve",
      "Akumal turtle snorkeling",
    ],
    cuisine: "Tacos al pastor, Ceviche, Sopes, Churros, Mezcal",
    costEstimate: "$40-150/day",
    funFact: "Tulum was one of the last cities built by the Maya civilization and was still inhabited when the Spanish arrived.",
    rating: 4.5,
  },
  {
    name: "Halong Bay",
    country: "Vietnam",
    continent: "asia",
    budget: ["budget", "moderate"],
    climate: ["tropical"],
    activity: ["nature", "adventure", "beach"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "October to December & March to May",
    description:
      "Thousands of limestone karsts and islets rising from emerald waters — a mystical seascape of towering pillars, hidden caves, and floating villages. An overnight cruise is a must.",
    highlights: [
      "Overnight junk boat cruise",
      "Sung Sot Cave",
      "Ti Top Island viewpoint",
      "Kayaking through karsts",
      "Floating village visit",
    ],
    cuisine: "Fresh spring rolls, Pho, Seafood, Banh Mi, Vietnamese coffee",
    costEstimate: "$25-80/day",
    funFact: "Halong Bay means 'Descending Dragon Bay' in Vietnamese, named after a legendary dragon that descended to protect the land.",
    rating: 4.6,
  },
  {
    name: "Scottish Highlands",
    country: "Scotland",
    continent: "europe",
    budget: ["budget", "moderate"],
    climate: ["cold", "temperate"],
    activity: ["nature", "adventure", "culture"],
    travelStyle: ["solo", "couple", "group", "family"],
    season: ["spring", "summer", "fall"],
    duration: ["weekend", "week"],
    bestTime: "May to September",
    description:
      "Misty mountains, ancient castles, shimmering lochs, and legendary battlefields. The Highlands offer dramatic landscapes, whisky distilleries, and the enduring spirit of Scottish clan culture.",
    highlights: [
      "Loch Ness cruise",
      "Eilean Donan Castle",
      "Isle of Skye fairy pools",
      "Glenfinnan Viaduct (Harry Potter train)",
      "Ben Nevis hike",
    ],
    cuisine: "Haggis, Scotch whisky, Shortbread, Salmon, Cranachan dessert",
    costEstimate: "$50-150/day",
    funFact: "The Scottish Highlands are home to the UK's highest mountain (Ben Nevis) and the legendary Loch Ness monster.",
    rating: 4.6,
  },
  {
    name: "Cartagena",
    country: "Colombia",
    continent: "southAmerica",
    budget: ["budget", "moderate"],
    climate: ["tropical"],
    activity: ["culture", "beach", "urban", "food"],
    travelStyle: ["solo", "couple", "group"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "December to April",
    description:
      "A jewel of the Caribbean — colourful colonial architecture, vibrant salsa music, cobblestone streets, and stunning Rosario Islands. Cartagena's Old Town is a UNESCO masterpiece.",
    highlights: [
      "Old Town colonial walk",
      "Castillo de San Felipe",
      "Rosario Islands day trip",
      "Getsemani street art",
      "Sunset from the city walls",
    ],
    cuisine: "Arepas, Ceviche, Bandeja Paisa, Coconut rice, Fresh fruit juices",
    costEstimate: "$30-100/day",
    funFact: "Cartagena's old town walls were built over 200 years of Spanish colonial rule and remain largely intact today.",
    rating: 4.5,
  },
  {
    name: "Swiss Alps (Interlaken)",
    country: "Switzerland",
    continent: "europe",
    budget: ["moderate", "luxury"],
    climate: ["cold", "temperate"],
    activity: ["adventure", "nature"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "June to August (summer), December to March (ski)",
    description:
      "Nestled between Lake Thun and Lake Brienz, Interlaken is the adventure capital of the Swiss Alps — paragliding, skiing, Jungfrau railway, and some of the most breathtaking mountain scenery on Earth.",
    highlights: [
      "Jungfraujoch — Top of Europe",
      "Paragliding over Interlaken",
      "Grindelwald First cliff walk",
      "Lake Brienz cruise",
      "Skiing in the Jungfrau region",
    ],
    cuisine: "Fondue, Raclette, Rösti, Swiss chocolate, Zürcher Geschnetzeltes",
    costEstimate: "$200-500/day",
    funFact: "Switzerland has over 1,500 lakes and the Swiss Alps cover about 60% of the country's total area.",
    rating: 4.8,
  },
  {
    name: "Angkor Wat",
    country: "Cambodia",
    continent: "asia",
    budget: ["budget"],
    climate: ["tropical"],
    activity: ["culture", "adventure"],
    travelStyle: ["solo", "couple", "group", "family"],
    season: ["spring", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "November to March",
    description:
      "The world's largest religious monument — a sprawling temple complex from the Khmer Empire, with intricate carvings, tree-root-wrapped ruins, and stunning sunrise views over the iconic lotus-shaped towers.",
    highlights: [
      "Angkor Wat sunrise",
      "Bayon's stone faces",
      "Ta Prohm (Tomb Raider temple)",
      "Angkor Thom",
      "Floating village on Tonle Sap",
    ],
    cuisine: "Fish Amok, Khmer curry, Lok Lak, Fresh spring rolls, Palm sugar sweets",
    costEstimate: "$20-60/day",
    funFact: "Angkor Wat is featured on Cambodia's national flag — the only flag in the world to feature a building.",
    rating: 4.7,
  },
  {
    name: "Costa Rica",
    country: "Costa Rica",
    continent: "northAmerica",
    budget: ["budget", "moderate"],
    climate: ["tropical"],
    activity: ["nature", "adventure", "beach"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["week", "twoWeeks"],
    bestTime: "December to April",
    description:
      "Pura Vida! Cloud forests, active volcanoes, pristine beaches on two coasts, and incredible biodiversity. Costa Rica is a paradise for eco-tourists and adventure seekers.",
    highlights: [
      "Arenal Volcano hot springs",
      "Monteverde Cloud Forest",
      "Manuel Antonio Beach",
      "Sloth spotting in the wild",
      "White-water rafting on Pacuare",
    ],
    cuisine: "Gallo pinto, Casado, Ceviche, Plantains, Fresh tropical fruits",
    costEstimate: "$50-150/day",
    funFact: "Costa Rica has no standing army — it was abolished in 1949, and the country invests heavily in education and conservation instead.",
    rating: 4.6,
  },
  {
    name: "Lisbon",
    country: "Portugal",
    continent: "europe",
    budget: ["budget", "moderate"],
    climate: ["temperate"],
    activity: ["urban", "culture", "food", "beach"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["weekend", "week"],
    bestTime: "March to October",
    description:
      "Sun-drenched hills, tiled facades, melancholic Fado music, and pasteléis de nata. Lisbon is Europe's rising star — affordable, beautiful, and brimming with character.",
    highlights: [
      "Belém Tower & Jerónimos Monastery",
      "Alfama district",
      "Tram 28",
      "Sintra day trip",
      "Pastel de Belém tasting",
    ],
    cuisine: "Pastel de nata, Bacalhau, Sardinhas, Caldo verde, Port wine",
    costEstimate: "$50-150/day",
    funFact: "Lisbon is older than Rome by about 400 years, making it the second-oldest capital city in Europe after Athens.",
    rating: 4.6,
  },
  {
    name: "Great Barrier Reef",
    country: "Australia",
    continent: "oceania",
    budget: ["moderate", "luxury"],
    climate: ["tropical"],
    activity: ["beach", "nature", "adventure"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["week", "twoWeeks"],
    bestTime: "June to October",
    description:
      "The world's largest coral reef system — a kaleidoscope of marine life, white sandy islands, and crystal-clear waters visible from space. Snorkel, dive, or fly over this natural wonder.",
    highlights: [
      "Snorkeling at Heart Reef",
      "Whitehaven Beach",
      "Scuba diving on the outer reef",
      "Hamilton Island",
      "Seaplane scenic flight",
    ],
    cuisine: "Barramundi, Prawns, Moreton Bay bugs, Vegemite, Lamingtons",
    costEstimate: "$100-300/day",
    funFact: "The Great Barrier Reef is so large it can be seen from outer space and is the only living structure visible from orbit.",
    rating: 4.8,
  },
  {
    name: "Petra",
    country: "Jordan",
    continent: "asia",
    budget: ["moderate", "luxury"],
    climate: ["arid"],
    activity: ["culture", "adventure"],
    travelStyle: ["solo", "couple", "group"],
    season: ["spring", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "March to May & September to November",
    description:
      "The ancient Nabataean city carved into rose-red cliffs — a breathtaking archaeological wonder that reveals itself through a narrow canyon. Wadi Rum's Martian landscapes are nearby.",
    highlights: [
      "Treasury (Al-Khazneh)",
      "Monastery (Ad-Deir)",
      "Siq canyon walk",
      "Wadi Rum desert camp",
      "Dead Sea float",
    ],
    cuisine: "Mansaf, Falafel, Hummus, Kebabs, Sweet tea with sage",
    costEstimate: "$60-200/day",
    funFact: "Petra was named one of the New 7 Wonders of the World in 2007 and was featured in Indiana Jones and the Last Crusade.",
    rating: 4.7,
  },
  {
    name: "Santorini",
    country: "Greece",
    continent: "europe",
    budget: ["moderate", "luxury"],
    climate: ["temperate"],
    activity: ["beach", "culture", "food", "urban"],
    travelStyle: ["couple", "solo", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["weekend", "week", "twoWeeks"],
    bestTime: "June to September",
    description:
      "Famous for its stunning sunsets, whitewashed buildings with blue domes, and dramatic caldera views. Santorini offers exceptional wine, volcanic beaches, and Minoan archaeological sites.",
    highlights: [
      "Oia sunset viewpoint",
      "Red Beach",
      "Akrotiri archaeological site",
      "Fira to Oia hiking trail",
      "Wine tasting at local vineyards",
    ],
    cuisine: "Fava, Tomatokeftedes, Souvlaki, Fresh seafood, Vinsanto wine",
    costEstimate: "$120-300/day",
    funFact: "Santorini's iconic blue-domed churches were painted blue and white to match the Greek flag.",
    rating: 4.6,
  },
  {
    name: "Safari — Serengeti & Ngorongoro",
    country: "Tanzania",
    continent: "africa",
    budget: ["moderate", "luxury"],
    climate: ["tropical", "arid"],
    activity: ["nature", "adventure"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["week", "twoWeeks"],
    bestTime: "June to October (dry season)",
    description:
      "Witness the Great Migration — millions of wildebeest and zebras crossing crocodile-filled rivers. The Serengeti and Ngorongoro Crater offer the most spectacular wildlife viewing on Earth.",
    highlights: [
      "Great Migration river crossing",
      "Ngorongoro Crater safari",
      "Big Five game drives",
      "Hot air balloon over Serengeti",
      "Visit a Maasai village",
    ],
    cuisine: "Nyama choma (BBQ), Ugali, Pilau, Fresh tropical fruits",
    costEstimate: "$200-500/day",
    funFact: "The Serengeti ecosystem is one of the oldest on Earth, with the same climate and conditions for over a million years.",
    rating: 4.9,
  },
  {
    name: "Bora Bora",
    country: "French Polynesia",
    continent: "oceania",
    budget: ["luxury"],
    climate: ["tropical"],
    activity: ["beach", "nature"],
    travelStyle: ["couple", "solo"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["week", "twoWeeks"],
    bestTime: "May to October",
    description:
      "The quintessential South Pacific paradise — an extinct volcano surrounded by a turquoise lagoon and coral motus. Overwater bungalows here defined luxury tropical travel.",
    highlights: [
      "Overwater bungalow stay",
      "Lagoon shark and ray feeding",
      "Mount Otemanu hike",
      "4x4 island safari",
      "Sunset catamaran cruise",
    ],
    cuisine: "Poisson cru (raw fish in coconut milk), Breadfruit, Fresh seafood, Vanilla",
    costEstimate: "$400-1000/day",
    funFact: "Bora Bora was an important World War II supply base for the US, and old cannons still dot the island's hills.",
    rating: 4.8,
  },
  {
    name: "Havana",
    country: "Cuba",
    continent: "northAmerica",
    budget: ["budget"],
    climate: ["tropical"],
    activity: ["culture", "urban", "food"],
    travelStyle: ["solo", "couple", "group"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "December to April",
    description:
      "A city frozen in time — vintage American cars, colourful colonial architecture, salsa rhythms, and classic mojitos. Havana is a living museum with an irresistible energy.",
    highlights: [
      "Old Havana walking tour",
      "Classic car tour",
      "El Malecón sunset",
      "Fábrica de Arte Cubano",
      "Viñales tobacco valley",
    ],
    cuisine: "Ropa vieja, Moros y cristianos, Tostones, Cuban sandwich, Mojito",
    costEstimate: "$30-80/day",
    funFact: "Cuba has one of the highest literacy rates in the world (over 99%) despite economic challenges.",
    rating: 4.4,
  },
  {
    name: "Inca Trail to Machu Picchu",
    country: "Peru",
    continent: "southAmerica",
    budget: ["moderate"],
    climate: ["cold", "temperate"],
    activity: ["adventure", "culture", "nature"],
    travelStyle: ["solo", "couple", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["week", "twoWeeks"],
    bestTime: "May to September",
    description:
      "The classic 4-day trek along ancient Inca pathways through cloud forests and mountain passes, culminating in the Sun Gate overlooking Machu Picchu at sunrise. A life-changing journey.",
    highlights: [
      "Sun Gate arrival at Machu Picchu",
      "Dead Woman's Pass",
      "Wiñay Wayna ruins",
      "Cloud forest bird watching",
      "Hot Springs in Aguas Calientes",
    ],
    cuisine: "Quinoa soup, Cuy (guinea pig), Coca tea, Andean potatoes",
    costEstimate: "$50-120/day",
    funFact: "The Inca Trail was part of the Qhapaq Ñan, a 40,000 km road network spanning the entire Inca Empire.",
    rating: 4.8,
  },
  {
    name: "Bangkok",
    country: "Thailand",
    continent: "asia",
    budget: ["budget", "moderate"],
    climate: ["tropical"],
    activity: ["urban", "culture", "food", "adventure"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "November to February",
    description:
      "A sensory overload in the best way — golden temples, floating markets, fiery street food, and legendary nightlife. Bangkok is the gateway to Southeast Asia with an energy all its own.",
    highlights: [
      "Grand Palace & Wat Phra Kaew",
      "Wat Pho reclining Buddha",
      "Floating markets (Damnoen Saduak)",
      "Khao San Road",
      "Chinatown food crawl",
    ],
    cuisine: "Pad Thai, Tom Yum Goong, Green curry, Mango sticky rice, Street food",
    costEstimate: "$20-80/day",
    funFact: "Bangkok's full ceremonial name is the longest city name in the world at 168 characters.",
    rating: 4.5,
  },
  {
    name: "Lake Como",
    country: "Italy",
    continent: "europe",
    budget: ["luxury", "moderate"],
    climate: ["temperate"],
    activity: ["beach", "culture", "food", "nature"],
    travelStyle: ["couple", "family", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["weekend", "week"],
    bestTime: "May to September",
    description:
      "An inverted Y-shaped lake surrounded by Alps, dotted with elegant villas, lush gardens, and charming villages. Bellagio, Varenna, and Menaggio are timelessly beautiful.",
    highlights: [
      "Bellagio waterfront",
      "Villa Carlotta gardens",
      "Ferry ride across the lake",
      "Como old town",
      "Brunate funicular viewpoint",
    ],
    cuisine: "Risotto, Fresh lake fish, Ossobuco, Gelato, Lombard wines",
    costEstimate: "$150-400/day",
    funFact: "Lake Como has been a celebrity retreat for centuries — ancient Roman writers like Pliny the Younger had villas here.",
    rating: 4.7,
  },
  {
    name: "Chiang Mai",
    country: "Thailand",
    continent: "asia",
    budget: ["budget"],
    climate: ["tropical"],
    activity: ["culture", "nature", "food", "adventure"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "fall", "winter"],
    duration: ["weekend", "week", "twoWeeks"],
    bestTime: "November to February",
    description:
      "The Rose of the North — ancient temples, a vibrant night bazaar, ethical elephant sanctuaries, and lush mountain scenery. Chiang Mai is Thailand's cultural and wellness capital.",
    highlights: [
      "Doi Suthep temple",
      "Elephant Nature Park",
      "Sunday Walking Market",
      "Thai cooking class",
      "Doi Inthanon National Park",
    ],
    cuisine: "Khao Soi, Pad Thai, Som Tam, Mango sticky rice, Thai iced tea",
    costEstimate: "$15-50/day",
    funFact: "Chiang Mai has over 300 Buddhist temples (wats), more than any other city in Thailand.",
    rating: 4.6,
  },
  {
    name: "New York City",
    country: "USA",
    continent: "northAmerica",
    budget: ["moderate", "luxury"],
    climate: ["temperate", "cold"],
    activity: ["urban", "culture", "food", "adventure"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["weekend", "week"],
    bestTime: "April to June & September to November",
    description:
      "The city that never sleeps — world-class museums, Broadway shows, iconic skyline, diverse cuisine, and an energy unmatched anywhere else. NYC is the ultimate urban destination.",
    highlights: [
      "Statue of Liberty & Ellis Island",
      "Central Park",
      "Times Square & Broadway",
      "Metropolitan Museum of Art",
      "Brooklyn Bridge walk",
    ],
    cuisine: "Pizza, Bagels, Cheesecake, Deli sandwiches, International food",
    costEstimate: "$200-500/day",
    funFact: "New York City has over 800 languages spoken, making it the most linguistically diverse city in the world.",
    rating: 4.7,
  },
  {
    name: "The Azores",
    country: "Portugal",
    continent: "europe",
    budget: ["budget", "moderate"],
    climate: ["temperate"],
    activity: ["nature", "adventure", "culture"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["weekend", "week"],
    bestTime: "June to September",
    description:
      "Europe's best-kept secret — a volcanic archipelago in the mid-Atlantic with crater lakes, thermal hot springs, lush green landscapes, and world-class whale watching.",
    highlights: [
      "Sete Cidades twin lakes",
      "Hot springs in Furnas",
      "Whale watching tours",
      "Lagoa do Fogo",
      "Pico Mountain hike",
    ],
    cuisine: "Cozido das Furnas (volcanic stew), Fresh tuna, Pineapple, Queijadas",
    costEstimate: "$40-120/day",
    funFact: "The Azores are closer to North America than to mainland Europe, sitting about 1,400 km west of Portugal.",
    rating: 4.6,
  },
  {
    name: "Dubrovnik",
    country: "Croatia",
    continent: "europe",
    budget: ["moderate", "luxury"],
    climate: ["temperate"],
    activity: ["culture", "beach", "urban", "food"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["weekend", "week"],
    bestTime: "May to September",
    description:
      "The Pearl of the Adriatic — stunning medieval walled city overlooking the crystal-clear Adriatic Sea. Game of Thrones fans will recognize King's Landing around every corner.",
    highlights: [
      "City walls walk",
      "Old Town & Stradun",
      "Lokrum Island",
      "Cable car to Mount Srđ",
      "Game of Thrones tour",
    ],
    cuisine: "Black risotto, Dalmatian prosciutto, Fresh seafood, Grilled fish",
    costEstimate: "$80-250/day",
    funFact: "Dubrovnik's city walls are the most complete medieval fortification system in the world, stretching nearly 2 km.",
    rating: 4.6,
  },
  {
    name: "Socotra Island",
    country: "Yemen",
    continent: "asia",
    budget: ["moderate"],
    climate: ["tropical", "arid"],
    activity: ["nature", "adventure"],
    travelStyle: ["solo", "group"],
    season: ["spring", "fall", "winter"],
    duration: ["week", "twoWeeks"],
    bestTime: "September to June",
    description:
      "The Galápagos of the Indian Ocean — home to the otherworldly Dragon's Blood Tree and alien-like landscapes found nowhere else on Earth. The most unique island on the planet.",
    highlights: [
      "Dragon's Blood Tree forest",
      "Detwah Lagoon",
      "Homhil Plateau",
      "Qalansiyah Beach (white sand)",
      "Shoab Beach sand dunes",
    ],
    cuisine: "Fresh fish, Rice, Camel meat, Dates, Spiced tea",
    costEstimate: "$80-200/day",
    funFact: "Socotra has over 700 species of plants found nowhere else on Earth, making it a UNESCO World Heritage site.",
    rating: 4.7,
  },
  {
    name: "Rapa Nui (Easter Island)",
    country: "Chile",
    continent: "southAmerica",
    budget: ["moderate", "luxury"],
    climate: ["temperate"],
    activity: ["culture", "nature", "adventure"],
    travelStyle: ["solo", "couple", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["weekend", "week"],
    bestTime: "October to April",
    description:
      "The most remote inhabited island in the world — mysterious moai statues, volcanic craters, and Polynesian culture. A profound journey to the edge of the world.",
    highlights: [
      "Moai statues at Ahu Tongariki",
      "Rano Raraku quarry",
      "Orongo ceremonial village",
      "Anakena Beach",
      "Sunset at Ahu Tahai",
    ],
    cuisine: "Tuna empanadas, Ceviche, Po'e (banana pudding), Fresh fish",
    costEstimate: "$100-300/day",
    funFact: "Easter Island has nearly 1,000 moai statues, each carved from volcanic rock, with the largest weighing 82 tons.",
    rating: 4.6,
  },
  {
    name: "Queenstown",
    country: "New Zealand",
    continent: "oceania",
    budget: ["moderate", "luxury"],
    climate: ["temperate", "cold"],
    activity: ["adventure", "nature", "beach"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["weekend", "week", "twoWeeks"],
    bestTime: "December to March (summer), June to August (ski)",
    description:
      "The adventure capital of the world, nestled on Lake Wakatipu with the Remarkables mountain range as backdrop. Bungee jumping, skiing, Milford Sound, and Hobbiton are just the beginning.",
    highlights: [
      "Bungee jumping (original AJ Hackett site)",
      "Milford Sound cruise",
      "Skiing at The Remarkables",
      "Shotover River jet boating",
      "Glenorchy (Lothlórien from LOTR)",
    ],
    cuisine: "Paua, Lamb dishes, Green-lipped mussels, Sauvignon Blanc",
    costEstimate: "$100-250/day",
    funFact: "Queenstown was named after Queen Victoria and is often called the 'Adventure Capital of the World'.",
    rating: 4.6,
  },
  {
    name: "Tromsø",
    country: "Norway",
    continent: "europe",
    budget: ["moderate", "luxury"],
    climate: ["cold"],
    activity: ["nature", "adventure", "urban"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["winter", "fall"],
    duration: ["weekend", "week"],
    bestTime: "September to March for Northern Lights, May to July for midnight sun",
    description:
      "The Arctic capital — one of the best places on Earth to see the Northern Lights, with stunning fjords, dog sledding, and the fascinating Polaria experience above the Arctic Circle.",
    highlights: [
      "Northern Lights chase",
      "Dog sledding adventure",
      "Polaria Arctic museum",
      "Fjellheisen cable car view",
      "Whale watching",
    ],
    cuisine: "Arctic cod, Reindeer stew, King crab, Cloudberries, Aquavit",
    costEstimate: "$150-400/day",
    funFact: "Tromsø is located 350 km north of the Arctic Circle and experiences polar night from November to January.",
    rating: 4.6,
  },
  {
    name: "Kerala Backwaters",
    country: "India",
    continent: "asia",
    budget: ["budget", "moderate"],
    climate: ["tropical"],
    activity: ["nature", "beach", "food", "culture"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "November to March",
    description:
      "A network of serene lagoons, canals, and lakes lined with palm trees and rice paddies. A traditional houseboat (kettuvallam) cruise through God's Own Country is unforgettable.",
    highlights: [
      "Houseboat cruise on Vembanad Lake",
      "Munnar tea plantations",
      "Kochi's Chinese fishing nets",
      "Kerala Ayurvedic treatments",
      "Periyar Wildlife Sanctuary",
    ],
    cuisine: "Kerala sadya, Fish curry, Appam, Puttu, Banana fritters",
    costEstimate: "$20-80/day",
    funFact: "Kerala has the highest literacy rate in India at over 96% and is one of the healthiest states in the country.",
    rating: 4.6,
  },
  {
    name: "The Galápagos Islands",
    country: "Ecuador",
    continent: "southAmerica",
    budget: ["moderate", "luxury"],
    climate: ["tropical", "temperate"],
    activity: ["nature", "beach", "adventure"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["week", "twoWeeks"],
    bestTime: "December to May (warm), June to November (cool)",
    description:
      "Darwin's living laboratory — fearless wildlife, unique species found nowhere else on Earth, and pristine volcanic landscapes. The closest you'll feel to another planet.",
    highlights: [
      "Giant tortoise encounter",
      "Snorkeling with sea lions",
      "Darwin's finches observation",
      "Sierra Negra volcano hike",
      "Blue-footed boobies mating dance",
    ],
    cuisine: "Ceviche, Fresh tuna, Plantain chips, Exotic fruits",
    costEstimate: "$200-500/day",
    funFact: "The Galápagos Islands have over 9,000 species, with about 80% of the land birds and 97% of the reptiles found nowhere else on Earth.",
    rating: 4.9,
  },
  {
    name: "Antelope Canyon",
    country: "USA",
    continent: "northAmerica",
    budget: ["moderate"],
    climate: ["arid"],
    activity: ["nature", "adventure"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["weekend", "week"],
    bestTime: "March to October",
    description:
      "One of the most photographed slot canyons in the world — swirling sandstone walls, light beams piercing the narrow passages, and colours that shift from orange to purple.",
    highlights: [
      "Upper Antelope Canyon light beams",
      "Lower Antelope Canyon ladder adventure",
      "Horseshoe Bend overlook",
      "Lake Powell kayaking",
      "Grand Canyon day trip",
    ],
    cuisine: "Navajo tacos, Fry bread, Southwestern BBQ, Prickly pear margaritas",
    costEstimate: "$80-200/day",
    funFact: "Antelope Canyon was formed by flash flood erosion over thousands of years, and flash floods still occur here.",
    rating: 4.7,
  },
  {
    name: "Siem Reap & Angkor Wat",
    country: "Cambodia",
    continent: "asia",
    budget: ["budget"],
    climate: ["tropical"],
    activity: ["culture", "adventure"],
    travelStyle: ["solo", "couple", "group", "family"],
    season: ["spring", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "November to March",
    description:
      "The world's largest religious monument — a sprawling temple complex from the Khmer Empire, with intricate carvings, tree-root-wrapped ruins, and stunning sunrise views over the iconic lotus-shaped towers.",
    highlights: [
      "Angkor Wat sunrise",
      "Bayon's stone faces",
      "Ta Prohm (Tomb Raider temple)",
      "Angkor Thom",
      "Floating village on Tonle Sap",
    ],
    cuisine: "Fish Amok, Khmer curry, Lok Lak, Fresh spring rolls, Palm sugar sweets",
    costEstimate: "$20-60/day",
    funFact: "Angkor Wat is featured on Cambodia's national flag — the only flag in the world to feature a building.",
    rating: 4.7,
  },
  {
    name: "Madeira",
    country: "Portugal",
    continent: "europe",
    budget: ["budget", "moderate"],
    climate: ["temperate"],
    activity: ["nature", "adventure", "food", "culture"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "May to October",
    description:
      "The floating garden of the Atlantic — dramatic cliffs, lush levada trails, black sand beaches, world-class Madeira wine, and the spectacular New Year's Eve fireworks display.",
    highlights: [
      "Pico do Arieiro to Pico Ruivo hike",
      "Funchal Old Town",
      "Cabo Girão skywalk",
      "Madeira wine tasting",
      "Porto Moniz natural pools",
    ],
    cuisine: "Espetada (beef skewers), Madeira wine, Swordfish, Bolo do caco, Passion fruit pudding",
    costEstimate: "$40-120/day",
    funFact: "Madeira's New Year's Eve fireworks display holds the Guinness World Record for the largest fireworks show in the world.",
    rating: 4.6,
  },
  {
    name: "Marrakech & Sahara Desert",
    country: "Morocco",
    continent: "africa",
    budget: ["budget", "moderate"],
    climate: ["arid"],
    activity: ["culture", "food", "urban", "adventure"],
    travelStyle: ["solo", "couple", "group", "family"],
    season: ["spring", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "March to May & September to November",
    description:
      "A sensory explosion — vibrant souks, ornate palaces, fragrant spice markets, and the bustling Jemaa el-Fnaa square. The Atlas Mountains and Sahara Desert are just a day trip away.",
    highlights: [
      "Jemaa el-Fnaa square",
      "Bahia Palace",
      "Majorelle Garden",
      "Sahara Desert camel trek",
      "Atlas Mountains day trip",
    ],
    cuisine: "Tagine, Couscous, Pastilla, Mint tea, Harira soup",
    costEstimate: "$30-100/day",
    funFact: "Marrakech's medina (old city) is a UNESCO World Heritage site and one of the most densely populated areas in Africa.",
    rating: 4.5,
  },
  {
    name: "Cappadocia",
    country: "Turkey",
    continent: "asia",
    budget: ["budget", "moderate"],
    climate: ["temperate", "arid"],
    activity: ["culture", "nature", "adventure"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "April to June & September to November",
    description:
      "A fairy-tale landscape of cave dwellings, underground cities, and surreal rock formations. Hot air ballooning over the valleys at sunrise is one of the most magical experiences on Earth.",
    highlights: [
      "Hot air balloon sunrise flight",
      "Göreme Open Air Museum",
      "Kaymaklı underground city",
      "Uçhisar Castle viewpoint",
      "Pottery making in Avanos",
    ],
    cuisine: "Testi kebab, Manti, Gözleme, Baklava, Turkish tea & coffee",
    costEstimate: "$30-100/day",
    funFact: "Cappadocia's underground cities could shelter up to 20,000 people and include ventilation shafts, wine cellars, and churches.",
    rating: 4.7,
  },
  {
    name: "Tahiti",
    country: "French Polynesia",
    continent: "oceania",
    budget: ["luxury"],
    climate: ["tropical"],
    activity: ["beach", "nature", "culture"],
    travelStyle: ["couple", "solo"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["week", "twoWeeks"],
    bestTime: "May to October",
    description:
      "The heart of French Polynesia — lush volcanic peaks, black sand beaches, vibrant coral gardens, and the warmest hospitality in the South Pacific. Tahiti is the gateway to paradise.",
    highlights: [
      "Point Venus black sand beach",
      "Fautaua Valley waterfall hike",
      "Papeete Market",
      "Island ferry to Moorea",
      "Lagoon excursions",
    ],
    cuisine: "Poisson cru, Vanilla, Fresh tropical fruits, French-Polynesian fusion",
    costEstimate: "$300-800/day",
    funFact: "Tahiti is the largest island in French Polynesia but only accounts for about 10% of the territory's total land area.",
    rating: 4.6,
  },
  {
    name: "Yosemite National Park",
    country: "USA",
    continent: "northAmerica",
    budget: ["budget", "moderate"],
    climate: ["temperate", "cold"],
    activity: ["nature", "adventure"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["weekend", "week"],
    bestTime: "May to October",
    description:
      "Towering granite cliffs, ancient sequoias, thunderous waterfalls, and pristine wilderness. Yosemite Valley is the crown jewel of America's national parks, inspiring awe in every visitor.",
    highlights: [
      "Half Dome & El Capitan views",
      "Yosemite Falls",
      "Glacier Point overlook",
      "Mariposa Grove sequoias",
      "Tuolumne Meadows hike",
    ],
    cuisine: "Campfire cooking, Local craft beer, Farm-to-table in nearby towns",
    costEstimate: "$30-100/day (camping), $100-250/day (lodging)",
    funFact: "El Capitan's vertical face is over 900 meters tall, making it one of the largest granite monoliths in the world.",
    rating: 4.8,
  },
  {
    name: "Colombo & Cultural Triangle",
    country: "Sri Lanka",
    continent: "asia",
    budget: ["budget"],
    climate: ["tropical"],
    activity: ["culture", "nature", "beach", "food"],
    travelStyle: ["solo", "couple", "family", "group"],
    season: ["spring", "fall", "winter"],
    duration: ["week", "twoWeeks"],
    bestTime: "January to March",
    description:
      "Pearl of the Indian Ocean — ancient rock fortresses, elephant safaris, tea plantations, and palm-fringed beaches. Sri Lanka packs incredible diversity into a small island.",
    highlights: [
      "Sigiriya Rock Fortress",
      "Temple of the Tooth (Kandy)",
      "Elephant safari in Minneriya",
      "Tea country in Nuwara Eliya",
      "Galle Fort",
    ],
    cuisine: "Rice and curry, Hoppers, Kottu roti, Fresh seafood, Ceylon tea",
    costEstimate: "$20-60/day",
    funFact: "Sri Lanka was the first country in the world to have a female Prime Minister, Sirimavo Bandaranaike, in 1960.",
    rating: 4.6,
  },
  {
    name: "Reykjavík",
    country: "Iceland",
    continent: "europe",
    budget: ["moderate", "luxury"],
    climate: ["cold"],
    activity: ["nature", "adventure", "culture"],
    travelStyle: ["solo", "couple", "group", "family"],
    season: ["summer", "fall", "winter"],
    duration: ["weekend", "week"],
    bestTime: "June to August for midnight sun, September to March for Northern Lights",
    description:
      "The world's northernmost capital — a launchpad for otherworldly landscapes, geothermal hot springs, and the Northern Lights. Reykjavík itself is a cosy hub of Nordic culture and creativity.",
    highlights: [
      "Blue Lagoon",
      "Golden Circle tour",
      "Northern Lights hunt",
      "Hallgrímskirkja church",
      "Harpa Concert Hall",
    ],
    cuisine: "Skyr, Lamb, Seafood, Hot dogs, Rye bread ice cream",
    costEstimate: "$150-400/day",
    funFact: "Reykjavík is the only capital city in the world with a population of puffins nearby in the summer months.",
    rating: 4.6,
  },
  {
    name: "Zhangjiajie",
    country: "China",
    continent: "asia",
    budget: ["budget", "moderate"],
    climate: ["temperate"],
    activity: ["nature", "adventure"],
    travelStyle: ["solo", "couple", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["weekend", "week"],
    bestTime: "March to November",
    description:
      "The inspiration for the floating mountains in Avatar — towering sandstone pillars covered in vegetation, glass-bottom bridges, and the world's tallest outdoor elevator.",
    highlights: [
      "Zhangjiajie National Forest Park",
      "Avatar Hallelujah Mountain",
      "Bailong Elevator (world's tallest outdoor elevator)",
      "Glass Skywalk on Tianmen Mountain",
      "Tianmen Cave (Heaven's Gate)",
    ],
    cuisine: "Hunan spicy cuisine, Stinky tofu, Rice noodles, Mao's braised pork",
    costEstimate: "$30-100/day",
    funFact: "The quartz-sandstone pillars in Zhangjiajie were formed over 300 million years of geological activity.",
    rating: 4.7,
  },
  {
    name: "Valparaíso",
    country: "Chile",
    continent: "southAmerica",
    budget: ["budget", "moderate"],
    climate: ["temperate"],
    activity: ["culture", "urban", "food"],
    travelStyle: ["solo", "couple", "group"],
    season: ["spring", "summer", "fall"],
    duration: ["weekend", "week"],
    bestTime: "October to April",
    description:
      "A bohemian port city of colourful hillside houses, funiculars, street art, and Pablo Neruda's beloved home. Valparaíso is Chile's most creative and photogenic city.",
    highlights: [
      "Cerro Alegre & Concepción street art",
      "Funicular rides",
      "La Sebastiana (Neruda's house)",
      "Port walk & seafood market",
      "Viña del Mar beach nearby",
    ],
    cuisine: "Completo (Chilean hot dog), Ceviche, Chorrillana, Pisco Sour, Seafood",
    costEstimate: "$30-80/day",
    funFact: "Valparaíso's port was a crucial stopover for ships travelling between the Atlantic and Pacific via Cape Horn.",
    rating: 4.5,
  },
  {
    name: "Seychelles",
    country: "Seychelles",
    continent: "africa",
    budget: ["luxury", "moderate"],
    climate: ["tropical"],
    activity: ["beach", "nature", "culture"],
    travelStyle: ["couple", "solo", "family"],
    season: ["spring", "summer", "fall", "winter"],
    duration: ["week", "twoWeeks"],
    bestTime: "April to October",
    description:
      "115 granite and coral islands scattered across the Indian Ocean — some of the most beautiful beaches on Earth, giant tortoises, and unique Coco de Mer palms.",
    highlights: [
      "Anse Source d'Argent beach (La Digue)",
      "Vallée de Mai Nature Reserve",
      "Morne Seychellois National Park",
      "Aldabra giant tortoises",
      "Snorkeling at Sainte Anne Marine Park",
    ],
    cuisine: "Fish curry, Coconut milk-based dishes, Fresh seafood, Tropical fruits",
    costEstimate: "$200-600/day",
    funFact: "Seychelles is home to the world's largest seed — the Coco de Mer, which can weigh up to 30 kg.",
    rating: 4.7,
  },
];

export default DESTINATIONS;
