export const THESAURUS = [
  { word: "abandon", pos: "verb", syn: ["desert", "forsake", "leave", "relinquish", "surrender", "vacate"], ant: ["keep", "retain", "stay"] },
  { word: "abbreviate", pos: "verb", syn: ["shorten", "condense", "truncate", "summarize", "abridge"], ant: ["lengthen", "extend", "expand"] },
  { word: "abhor", pos: "verb", syn: ["detest", "loathe", "despise", "abominate", "execrate"], ant: ["love", "adore", "cherish"] },
  { word: "ability", pos: "noun", syn: ["capability", "capacity", "competence", "aptitude", "talent"], ant: ["inability", "incompetence"] },
  { word: "abundant", pos: "adj", syn: ["plentiful", "ample", "copious", "profuse", "bountiful"], ant: ["scarce", "meager", "sparse"] },
  { word: "accelerate", pos: "verb", syn: ["hasten", "expedite", "quicken", "speed", "hurry"], ant: ["decelerate", "slow", "delay"] },
  { word: "accept", pos: "verb", syn: ["receive", "admit", "embrace", "acknowledge", "agree"], ant: ["reject", "refuse", "decline"] },
  { word: "accomplish", pos: "verb", syn: ["achieve", "attain", "complete", "execute", "fulfill"], ant: ["fail", "abandon", "neglect"] },
  { word: "accurate", pos: "adj", syn: ["precise", "exact", "correct", "truthful", "meticulous"], ant: ["inaccurate", "wrong", "imprecise"] },
  { word: "achieve", pos: "verb", syn: ["accomplish", "attain", "reach", "realize", "win"], ant: ["fail", "miss", "surrender"] },
  { word: "acknowledge", pos: "verb", syn: ["admit", "accept", "recognize", "concede", "confess"], ant: ["deny", "disavow", "reject"] },
  { word: "active", pos: "adj", syn: ["energetic", "lively", "vigorous", "dynamic", "animated"], ant: ["inactive", "passive", "sluggish"] },
  { word: "adapt", pos: "verb", syn: ["adjust", "accommodate", "modify", "alter", "conform"], ant: ["resist", "oppose", "stubborn"] },
  { word: "admire", pos: "verb", syn: ["respect", "appreciate", "esteem", "adore", "revere"], ant: ["despise", "disdain", "scorn"] },
  { word: "admit", pos: "verb", syn: ["confess", "acknowledge", "concede", "allow", "grant"], ant: ["deny", "reject", "dispute"] },
  { word: "adopt", pos: "verb", syn: ["embrace", "assume", "take up", "espouse", "follow"], ant: ["reject", "discard", "abandon"] },
  { word: "adversary", pos: "noun", syn: ["opponent", "enemy", "rival", "antagonist", "foe"], ant: ["ally", "friend", "supporter"] },
  { word: "advocate", pos: "verb", syn: ["promote", "endorse", "champion", "support", "encourage"], ant: ["oppose", "protest", "resist"] },
  { word: "affect", pos: "verb", syn: ["influence", "impact", "alter", "modify", "sway"], ant: ["leave alone", "unaffected"] },
  { word: "aggressive", pos: "adj", syn: ["assertive", "forceful", "hostile", "belligerent", "militant"], ant: ["passive", "gentle", "timid"] },
  { word: "aid", pos: "verb", syn: ["assist", "help", "support", "facilitate", "succor"], ant: ["hinder", "obstruct", "harm"] },
  { word: "alter", pos: "verb", syn: ["change", "modify", "adjust", "transform", "revise"], ant: ["preserve", "maintain", "keep"] },
  { word: "amaze", pos: "verb", syn: ["astonish", "astound", "stun", "dumbfound", "bewilder"], ant: ["bore", "tire", "predict"] },
  { word: "ambiguous", pos: "adj", syn: ["vague", "unclear", "equivocal", "uncertain", "cryptic"], ant: ["clear", "explicit", "definite"] },
  { word: "amplify", pos: "verb", syn: ["magnify", "expand", "increase", "intensify", "augment"], ant: ["reduce", "diminish", "lessen"] },
  { word: "analyze", pos: "verb", syn: ["examine", "study", "evaluate", "dissect", "scrutinize"], ant: ["ignore", "overlook", "synthesize"] },
  { word: "ancient", pos: "adj", syn: ["old", "antique", "archaic", "primitive", "antiquated"], ant: ["modern", "new", "contemporary"] },
  { word: "announce", pos: "verb", syn: ["declare", "proclaim", "reveal", "disclose", "broadcast"], ant: ["conceal", "hide", "suppress"] },
  { word: "annoy", pos: "verb", syn: ["irritate", "bother", "pester", "vex", "aggravate"], ant: ["please", "soothe", "comfort"] },
  { word: "anxious", pos: "adj", syn: ["worried", "nervous", "uneasy", "apprehensive", "tense"], ant: ["calm", "relaxed", "composed"] },
  { word: "apathy", pos: "noun", syn: ["indifference", "unconcern", "detachment", "passivity"], ant: ["interest", "passion", "enthusiasm"] },
  { word: "apparent", pos: "adj", syn: ["obvious", "evident", "clear", "plain", "manifest"], ant: ["obscure", "unclear", "hidden"] },
  { word: "appreciate", pos: "verb", syn: ["value", "cherish", "admire", "treasure", "esteem"], ant: ["disparage", "undervalue", "scorn"] },
  { word: "approve", pos: "verb", syn: ["endorse", "sanction", "ratify", "authorize", "support"], ant: ["reject", "veto", "disapprove"] },
  { word: "ardent", pos: "adj", syn: ["passionate", "fervent", "zealous", "enthusiastic", "intense"], ant: ["indifferent", "apathetic", "cool"] },
  { word: "argue", pos: "verb", syn: ["debate", "dispute", "contend", "quarrel", "reason"], ant: ["agree", "concur", "harmonize"] },
  { word: "artificial", pos: "adj", syn: ["synthetic", "fake", "man-made", "imitation", "simulated"], ant: ["natural", "genuine", "authentic"] },
  { word: "assert", pos: "verb", syn: ["state", "declare", "affirm", "maintain", "contend"], ant: ["deny", "disclaim", "refute"] },
  { word: "assess", pos: "verb", syn: ["evaluate", "appraise", "judge", "estimate", "gauge"], ant: ["guess", "neglect"] },
  { word: "assist", pos: "verb", syn: ["help", "aid", "support", "facilitate", "abet"], ant: ["hinder", "obstruct", "impede"] },
  { word: "assume", pos: "verb", syn: ["presume", "suppose", "take for granted", "presuppose"], ant: ["know", "verify", "confirm"] },
  { word: "astonish", pos: "verb", syn: ["amaze", "astound", "stun", "shock", "dumbfound"], ant: ["bore", "tire"] },
  { word: "authentic", pos: "adj", syn: ["genuine", "real", "legitimate", "original", "bona fide"], ant: ["fake", "counterfeit", "false"] },
  { word: "avoid", pos: "verb", syn: ["evade", "dodge", "shun", "elude", "eschew"], ant: ["confront", "approach", "face"] },
  { word: "aware", pos: "adj", syn: ["conscious", "mindful", "cognizant", "informed", "alert"], ant: ["unaware", "oblivious", "ignorant"] },
  { word: "barrier", pos: "noun", syn: ["obstacle", "hindrance", "obstruction", "impediment", "block"], ant: ["aid", "help", "assistance"] },
  { word: "beautiful", pos: "adj", syn: ["gorgeous", "stunning", "lovely", "exquisite", "breathtaking"], ant: ["ugly", "hideous", "plain"] },
  { word: "begin", pos: "verb", syn: ["start", "commence", "initiate", "launch", "embark"], ant: ["end", "finish", "conclude"] },
  { word: "believe", pos: "verb", syn: ["trust", "accept", "hold", "credit", "have faith"], ant: ["doubt", "disbelieve", "question"] },
  { word: "benefit", pos: "noun", syn: ["advantage", "gain", "profit", "boon", "asset"], ant: ["drawback", "disadvantage", "loss"] },
  { word: "betray", pos: "verb", syn: ["deceive", "double-cross", "expose", "inform on", "sell out"], ant: ["protect", "defend", "support"] },
  { word: "big", pos: "adj", syn: ["large", "huge", "enormous", "massive", "gigantic"], ant: ["small", "tiny", "little"] },
  { word: "bitter", pos: "adj", syn: ["acrid", "sour", "sharp", "harsh", "resentful"], ant: ["sweet", "pleasant", "mild"] },
  { word: "blame", pos: "verb", syn: ["accuse", "censure", "reprimand", "criticize", "fault"], ant: ["praise", "commend", "credit"] },
  { word: "brave", pos: "adj", syn: ["courageous", "fearless", "bold", "valiant", "heroic"], ant: ["cowardly", "timid", "afraid"] },
  { word: "break", pos: "verb", syn: ["shatter", "smash", "fracture", "crack", "splinter"], ant: ["repair", "mend", "fix"] },
  { word: "bright", pos: "adj", syn: ["brilliant", "luminous", "radiant", "vivid", "shining"], ant: ["dim", "dull", "dark"] },
  { word: "busy", pos: "adj", syn: ["occupied", "engaged", "industrious", "active", "diligent"], ant: ["idle", "inactive", "lazy"] },
  { word: "calm", pos: "adj", syn: ["serene", "peaceful", "tranquil", "composed", "placid"], ant: ["agitated", "stormy", "frantic"] },
  { word: "capable", pos: "adj", syn: ["competent", "able", "qualified", "adept", "proficient"], ant: ["incompetent", "incapable"] },
  { word: "capture", pos: "verb", syn: ["seize", "apprehend", "arrest", "catch", "grasp"], ant: ["release", "free", "liberate"] },
  { word: "careful", pos: "adj", syn: ["cautious", "wary", "prudent", "attentive", "vigilant"], ant: ["careless", "reckless", "negligent"] },
  { word: "certain", pos: "adj", syn: ["sure", "confident", "positive", "assured", "convinced"], ant: ["uncertain", "doubtful", "unsure"] },
  { word: "change", pos: "verb", syn: ["alter", "modify", "transform", "convert", "revise"], ant: ["preserve", "maintain", "stagnate"] },
  { word: "chaos", pos: "noun", syn: ["disorder", "confusion", "turmoil", "pandemonium", "anarchy"], ant: ["order", "peace", "harmony"] },
  { word: "charity", pos: "noun", syn: ["generosity", "benevolence", "philanthropy", "altruism"], ant: ["selfishness", "greed", "miserliness"] },
  { word: "cheerful", pos: "adj", syn: ["joyful", "happy", "buoyant", "exuberant", "jovial"], ant: ["sad", "gloomy", "morose"] },
  { word: "choose", pos: "verb", syn: ["select", "pick", "opt", "elect", "decide"], ant: ["reject", "decline", "refuse"] },
  { word: "clear", pos: "adj", syn: ["transparent", "obvious", "distinct", "lucid", "evident"], ant: ["murky", "confused", "obscure"] },
  { word: "clever", pos: "adj", syn: ["intelligent", "smart", "bright", "sharp", "ingenious"], ant: ["stupid", "dull", "dim"] },
  { word: "combine", pos: "verb", syn: ["merge", "unite", "blend", "fuse", "integrate"], ant: ["separate", "divide", "split"] },
  { word: "comfort", pos: "verb", syn: ["console", "soothe", "ease", "relieve", "solace"], ant: ["distress", "agitate", "trouble"] },
  { word: "commit", pos: "verb", syn: ["dedicate", "devote", "pledge", "promise", "undertake"], ant: ["neglect", "abandon", "waiver"] },
  { word: "common", pos: "adj", syn: ["ordinary", "typical", "usual", "prevalent", "mundane"], ant: ["rare", "uncommon", "unique"] },
  { word: "compare", pos: "verb", syn: ["contrast", "liken", "equate", "juxtapose", "measure"], ant: ["distinguish", "differentiate"] },
  { word: "compel", pos: "verb", syn: ["force", "oblige", "coerce", "drive", "constrain"], ant: ["persuade", "encourage", "volunteer"] },
  { word: "competent", pos: "adj", syn: ["capable", "qualified", "adept", "skilled", "proficient"], ant: ["incompetent", "unskilled"] },
  { word: "complain", pos: "verb", syn: ["protest", "grumble", "whine", "object", "lament"], ant: ["praise", "commend", "approve"] },
  { word: "complete", pos: "adj", syn: ["entire", "whole", "total", "full", "thorough"], ant: ["incomplete", "partial", "lacking"] },
  { word: "complex", pos: "adj", syn: ["complicated", "intricate", "involved", "elaborate", "sophisticated"], ant: ["simple", "basic", "straightforward"] },
  { word: "comprehend", pos: "verb", syn: ["understand", "grasp", "perceive", "discern", "fathom"], ant: ["misunderstand", "confuse"] },
  { word: "concentrate", pos: "verb", syn: ["focus", "attend", "fixate", "center", "deliberate"], ant: ["distract", "wander", "disperse"] },
  { word: "confirm", pos: "verb", syn: ["verify", "validate", "corroborate", "substantiate", "certify"], ant: ["deny", "disprove", "refute"] },
  { word: "conflict", pos: "noun", syn: ["dispute", "clash", "struggle", "friction", "discord"], ant: ["harmony", "accord", "agreement"] },
  { word: "confuse", pos: "verb", syn: ["bewilder", "perplex", "baffle", "muddle", "disorient"], ant: ["clarify", "enlighten", "inform"] },
  { word: "connect", pos: "verb", syn: ["link", "attach", "join", "couple", "unite"], ant: ["disconnect", "separate", "detach"] },
  { word: "conquer", pos: "verb", syn: ["defeat", "overcome", "subdue", "vanquish", "triumph"], ant: ["surrender", "yield", "lose"] },
  { word: "conscious", pos: "adj", syn: ["aware", "mindful", "alert", "awake", "cognizant"], ant: ["unconscious", "unaware", "oblivious"] },
  { word: "consider", pos: "verb", syn: ["ponder", "contemplate", "deliberate", "weigh", "reflect"], ant: ["ignore", "dismiss", "disregard"] },
  { word: "constant", pos: "adj", syn: ["steady", "unwavering", "persistent", "continual", "unchanging"], ant: ["variable", "inconsistent", "fickle"] },
  { word: "construct", pos: "verb", syn: ["build", "erect", "assemble", "create", "fabricate"], ant: ["destroy", "demolish", "dismantle"] },
  { word: "contrary", pos: "adj", syn: ["opposite", "opposing", "contradictory", "adverse", "antagonistic"], ant: ["similar", "same", "consistent"] },
  { word: "convince", pos: "verb", syn: ["persuade", "assure", "win over", "induce", "satisfy"], ant: ["dissuade", "deter", "discourage"] },
  { word: "cooperate", pos: "verb", syn: ["collaborate", "unite", "work together", "team up", "ally"], ant: ["compete", "oppose", "hinder"] },
  { word: "correct", pos: "adj", syn: ["right", "accurate", "precise", "true", "faultless"], ant: ["incorrect", "wrong", "flawed"] },
  { word: "courage", pos: "noun", syn: ["bravery", "valor", "nerve", "audacity", "fortitude"], ant: ["cowardice", "timidity", "fear"] },
  { word: "crazy", pos: "adj", syn: ["insane", "mad", "deranged", "unhinged", "lunatic"], ant: ["sane", "rational", "sensible"] },
  { word: "create", pos: "verb", syn: ["invent", "produce", "generate", "devise", "form"], ant: ["destroy", "annihilate", "demolish"] },
  { word: "crime", pos: "noun", syn: ["offense", "violation", "felony", "misdemeanor", "wrongdoing"], ant: ["virtue", "good deed"] },
  { word: "crisis", pos: "noun", syn: ["emergency", "catastrophe", "disaster", "calamity", "turmoil"], ant: ["calm", "stability", "peace"] },
  { word: "critical", pos: "adj", syn: ["crucial", "essential", "vital", "paramount", "urgent"], ant: ["unimportant", "trivial", "minor"] },
  { word: "crude", pos: "adj", syn: ["raw", "unrefined", "coarse", "rough", "primitive"], ant: ["refined", "polished", "sophisticated"] },
  { word: "cruel", pos: "adj", syn: ["ruthless", "brutal", "savage", "vicious", "inhumane"], ant: ["kind", "compassionate", "merciful"] },
  { word: "curious", pos: "adj", syn: ["inquisitive", "inquiring", "interested", "nosy", "probing"], ant: ["indifferent", "uninterested", "bored"] },
  { word: "danger", pos: "noun", syn: ["peril", "hazard", "risk", "threat", "jeopardy"], ant: ["safety", "security", "protection"] },
  { word: "daring", pos: "adj", syn: ["bold", "audacious", "adventurous", "fearless", "venturesome"], ant: ["timid", "cautious", "cowardly"] },
  { word: "dear", pos: "adj", syn: ["beloved", "precious", "cherished", "treasured", "darling"], ant: ["hated", "despised", "loathed"] },
  { word: "debate", pos: "noun", syn: ["discussion", "argument", "dispute", "deliberation", "discourse"], ant: ["agreement", "consensus"] },
  { word: "deceive", pos: "verb", syn: ["trick", "mislead", "fool", "dupe", "con"], ant: ["enlighten", "inform", "guide"] },
  { word: "declare", pos: "verb", syn: ["announce", "proclaim", "state", "assert", "avow"], ant: ["conceal", "suppress", "withhold"] },
  { word: "decrease", pos: "verb", syn: ["reduce", "diminish", "lessen", "decline", "abate"], ant: ["increase", "grow", "expand"] },
  { word: "dedicate", pos: "verb", syn: ["devote", "commit", "consecrate", "pledge", "surrender"], ant: ["neglect", "ignore", "abandon"] },
  { word: "defeat", pos: "verb", syn: ["conquer", "vanquish", "overcome", "beat", "subdue"], ant: ["surrender", "yield", "lose"] },
  { word: "defend", pos: "verb", syn: ["protect", "guard", "shield", "safeguard", "preserve"], ant: ["attack", "assault", "abandon"] },
  { word: "definite", pos: "adj", syn: ["certain", "clear", "fixed", "explicit", "unambiguous"], ant: ["indefinite", "vague", "uncertain"] },
  { word: "delay", pos: "verb", syn: ["postpone", "defer", "put off", "procrastinate", "suspend"], ant: ["hasten", "expedite", "advance"] },
  { word: "delicate", pos: "adj", syn: ["fragile", "frail", "dainty", "faint", "sensitive"], ant: ["coarse", "rough", "sturdy"] },
  { word: "delight", pos: "noun", syn: ["pleasure", "joy", "bliss", "rapture", "ecstasy"], ant: ["disgust", "displeasure", "sorrow"] },
  { word: "demonstrate", pos: "verb", syn: ["show", "display", "exhibit", "prove", "illustrate"], ant: ["conceal", "hide", "disguise"] },
  { word: "depart", pos: "verb", syn: ["leave", "exit", "withdraw", "retreat", "go"], ant: ["arrive", "stay", "remain"] },
  { word: "depend", pos: "verb", syn: ["rely", "count", "trust", "lean", "bank"], ant: ["distrust", "doubt", "ignore"] },
  { word: "depress", pos: "verb", syn: ["sadden", "discourage", "dishearten", "demoralize", "dampen"], ant: ["cheer", "uplift", "encourage"] },
  { word: "describe", pos: "verb", syn: ["depict", "portray", "characterize", "detail", "narrate"], ant: ["conceal", "misrepresent"] },
  { word: "desire", pos: "noun", syn: ["longing", "yearning", "craving", "urge", "appetite"], ant: ["aversion", "dislike", "hatred"] },
  { word: "destroy", pos: "verb", syn: ["demolish", "annihilate", "ruin", "devastate", "ravage"], ant: ["build", "create", "construct"] },
  { word: "determine", pos: "verb", syn: ["decide", "resolve", "ascertain", "establish", "conclude"], ant: ["waver", "hesitate", "vacillate"] },
  { word: "develop", pos: "verb", syn: ["evolve", "grow", "mature", "progress", "advance"], ant: ["regress", "decline", "stagnate"] },
  { word: "devote", pos: "verb", syn: ["dedicate", "commit", "pledge", "consecrate", "surrender"], ant: ["withhold", "neglect", "withdraw"] },
  { word: "different", pos: "adj", syn: ["distinct", "dissimilar", "divergent", "contrasting", "variant"], ant: ["same", "similar", "identical"] },
  { word: "difficult", pos: "adj", syn: ["hard", "challenging", "arduous", "laborious", "demanding"], ant: ["easy", "simple", "effortless"] },
  { word: "digest", pos: "verb", syn: ["absorb", "assimilate", "comprehend", "grasp", "process"], ant: ["expel", "reject", "misunderstand"] },
  { word: "diligent", pos: "adj", syn: ["industrious", "assiduous", "hardworking", "persevering", "sedulous"], ant: ["lazy", "negligent", "idle"] },
  { word: "diminish", pos: "verb", syn: ["decrease", "lessen", "reduce", "wane", "subside"], ant: ["increase", "enlarge", "amplify"] },
  { word: "discover", pos: "verb", syn: ["find", "unearth", "detect", "reveal", "uncover"], ant: ["conceal", "hide", "lose"] },
  { word: "distinct", pos: "adj", syn: ["clear", "different", "unique", "unmistakable", "definite"], ant: ["indistinct", "vague", "similar"] },
  { word: "distribute", pos: "verb", syn: ["disperse", "allocate", "apportion", "spread", "allot"], ant: ["collect", "gather", "centralize"] },
  { word: "diverse", pos: "adj", syn: ["varied", "assorted", "heterogeneous", "multifarious", "sundry"], ant: ["uniform", "identical", "homogeneous"] },
  { word: "domestic", pos: "adj", syn: ["household", "home", "familial", "internal", "native"], ant: ["foreign", "international", "wild"] },
  { word: "dominant", pos: "adj", syn: ["prevailing", "prevalent", "predominant", "principal", "sovereign"], ant: ["subordinate", "secondary", "inferior"] },
  { word: "doubt", pos: "noun", syn: ["uncertainty", "skepticism", "distrust", "misgiving", "qualms"], ant: ["certainty", "trust", "confidence"] },
  { word: "drastic", pos: "adj", syn: ["extreme", "radical", "severe", "sweeping", "dramatic"], ant: ["mild", "moderate", "gradual"] },
  { word: "dreadful", pos: "adj", syn: ["terrible", "awful", "horrible", "appalling", "grim"], ant: ["wonderful", "pleasant", "delightful"] },
  { word: "durable", pos: "adj", syn: ["long-lasting", "sturdy", "tough", "resilient", "enduring"], ant: ["fragile", "flimsy", "temporary"] },
  { word: "eager", pos: "adj", syn: ["keen", "enthusiastic", "avid", "ardent", "impatient"], ant: ["reluctant", "indifferent", "apathetic"] },
  { word: "efficient", pos: "adj", syn: ["productive", "effective", "competent", "adept", "streamlined"], ant: ["inefficient", "wasteful", "inept"] },
  { word: "eliminate", pos: "verb", syn: ["remove", "eradicate", "wipe out", "abolish", "annihilate"], ant: ["add", "include", "preserve"] },
  { word: "embrace", pos: "verb", syn: ["hug", "accept", "adopt", "welcome", "espouse"], ant: ["reject", "shun", "avoid"] },
  { word: "emergency", pos: "noun", syn: ["crisis", "urgent", "disaster", "calamity", "catastrophe"], ant: ["routine", "normality"] },
  { word: "emotion", pos: "noun", syn: ["feeling", "sentiment", "passion", "affect", "sensation"], ant: ["reason", "logic", "intellect"] },
  { word: "encourage", pos: "verb", syn: ["motivate", "inspire", "urge", "hearten", "embolden"], ant: ["discourage", "dissuade", "daunt"] },
  { word: "enormous", pos: "adj", syn: ["huge", "immense", "colossal", "gigantic", "vast"], ant: ["tiny", "minute", "insignificant"] },
  { word: "enthusiasm", pos: "noun", syn: ["passion", "zeal", "eagerness", "fervor", "ardor"], ant: ["apathy", "indifference", "boredom"] },
  { word: "essential", pos: "adj", syn: ["necessary", "crucial", "vital", "indispensable", "fundamental"], ant: ["optional", "dispensable", "trivial"] },
  { word: "establish", pos: "verb", syn: ["found", "set up", "institute", "create", "organize"], ant: ["dismantle", "abolish", "dissolve"] },
  { word: "estimate", pos: "verb", syn: ["approximate", "gauge", "assess", "evaluate", "reckon"], ant: ["measure", "calculate", "verify"] },
  { word: "evaluate", pos: "verb", syn: ["assess", "appraise", "judge", "rate", "weigh"], ant: ["guess", "ignore", "neglect"] },
  { word: "evident", pos: "adj", syn: ["obvious", "apparent", "clear", "manifest", "palpable"], ant: ["obscure", "hidden", "doubtful"] },
  { word: "evil", pos: "adj", syn: ["wicked", "malevolent", "sinister", "vicious", "nefarious"], ant: ["good", "virtuous", "benevolent"] },
  { word: "exact", pos: "adj", syn: ["precise", "accurate", "correct", "specific", "meticulous"], ant: ["inexact", "approximate", "vague"] },
  { word: "examine", pos: "verb", syn: ["inspect", "scrutinize", "study", "analyze", "investigate"], ant: ["overlook", "ignore", "neglect"] },
  { word: "example", pos: "noun", syn: ["instance", "sample", "illustration", "specimen", "case"], ant: ["exception", "anomaly"] },
  { word: "excellent", pos: "adj", syn: ["superb", "outstanding", "exceptional", "splendid", "magnificent"], ant: ["poor", "inferior", "mediocre"] },
  { word: "exclude", pos: "verb", syn: ["omit", "leave out", "bar", "eliminate", "reject"], ant: ["include", "admit", "accept"] },
  { word: "execute", pos: "verb", syn: ["perform", "carry out", "implement", "accomplish", "administer"], ant: ["neglect", "abandon", "cancel"] },
  { word: "exhaust", pos: "verb", syn: ["tire", "drain", "fatigue", "deplete", "sap"], ant: ["energize", "invigorate", "refresh"] },
  { word: "exhibit", pos: "verb", syn: ["display", "show", "demonstrate", "present", "parade"], ant: ["conceal", "hide", "suppress"] },
  { word: "expand", pos: "verb", syn: ["enlarge", "extend", "swell", "broaden", "dilate"], ant: ["contract", "shrink", "compress"] },
  { word: "explore", pos: "verb", syn: ["investigate", "examine", "probe", "survey", "scout"], ant: ["ignore", "neglect", "avoid"] },
  { word: "expose", pos: "verb", syn: ["reveal", "uncover", "disclose", "unveil", "unmask"], ant: ["conceal", "cover", "protect"] },
  { word: "extend", pos: "verb", syn: ["lengthen", "prolong", "lengthen", "stretch", "elongate"], ant: ["shorten", "contract", "curtail"] },
  { word: "extraordinary", pos: "adj", syn: ["remarkable", "incredible", "phenomenal", "exceptional", "unusual"], ant: ["ordinary", "common", "mundane"] },
  { word: "extreme", pos: "adj", syn: ["excessive", "intense", "severe", "drastic", "utmost"], ant: ["moderate", "mild", "temperate"] },
  { word: "fabulous", pos: "adj", syn: ["amazing", "incredible", "fantastic", "marvelous", "phenomenal"], ant: ["terrible", "awful", "ordinary"] },
  { word: "facilitate", pos: "verb", syn: ["expedite", "ease", "enable", "assist", "promote"], ant: ["hinder", "impede", "complicate"] },
  { word: "familiar", pos: "adj", syn: ["acquainted", "accustomed", "comfortable", "conversant", "versed"], ant: ["unfamiliar", "unaccustomed", "strange"] },
  { word: "fantastic", pos: "adj", syn: ["wonderful", "terrific", "superb", "amazing", "phenomenal"], ant: ["awful", "terrible", "dreadful"] },
  { word: "fascinate", pos: "verb", syn: ["captivate", "enchant", "enthrall", "mesmerize", "beguile"], ant: ["bore", "repel", "disgust"] },
  { word: "fatal", pos: "adj", syn: ["deadly", "lethal", "mortal", "pernicious", "devastating"], ant: ["harmless", "benign", "salutary"] },
  { word: "fatigue", pos: "noun", syn: ["exhaustion", "tiredness", "weariness", "lassitude", "lethargy"], ant: ["energy", "vigor", "vitality"] },
  { word: "fearless", pos: "adj", syn: ["brave", "courageous", "valiant", "dauntless", "intrepid"], ant: ["timid", "fearful", "cowardly"] },
  { word: "fertile", pos: "adj", syn: ["productive", "fruitful", "rich", "abundant", "fecund"], ant: ["barren", "infertile", "sterile"] },
  { word: "fierce", pos: "adj", syn: ["savage", "ferocious", "intense", "vehement", "violent"], ant: ["gentle", "mild", "tame"] },
  { word: "flourish", pos: "verb", syn: ["thrive", "prosper", "bloom", "boom", "succeed"], ant: ["decline", "wither", "struggle"] },
  { word: "foolish", pos: "adj", syn: ["silly", "absurd", "ridiculous", "unwise", "senseless"], ant: ["wise", "sensible", "prudent"] },
  { word: "forbid", pos: "verb", syn: ["prohibit", "ban", "prevent", "outlaw", "disallow"], ant: ["allow", "permit", "sanction"] },
  { word: "foreign", pos: "adj", syn: ["alien", "exotic", "overseas", "external", "imported"], ant: ["domestic", "native", "local"] },
  { word: "forsake", pos: "verb", syn: ["abandon", "desert", "renounce", "relinquish", "disown"], ant: ["support", "cherish", "cling"] },
  { word: "fragile", pos: "adj", syn: ["delicate", "brittle", "frail", "breakable", "feeble"], ant: ["sturdy", "strong", "resilient"] },
  { word: "frank", pos: "adj", syn: ["candid", "honest", "sincere", "blunt", "forthright"], ant: ["evasive", "deceitful", "insincere"] },
  { word: "freedom", pos: "noun", syn: ["liberty", "independence", "autonomy", "sovereignty", "emancipation"], ant: ["captivity", "restraint", "bondage"] },
  { word: "frequent", pos: "adj", syn: ["common", "recurring", "repeated", "regular", "habitual"], ant: ["rare", "infrequent", "sporadic"] },
  { word: "friendly", pos: "adj", syn: ["amiable", "affable", "cordial", "genial", "warm"], ant: ["hostile", "unfriendly", "cold"] },
  { word: "frighten", pos: "verb", syn: ["scare", "terrify", "alarm", "startle", "spook"], ant: ["calm", "reassure", "comfort"] },
  { word: "frugal", pos: "adj", syn: ["economical", "thrifty", "sparing", "miserly", "frugal"], ant: ["extravagant", "wasteful", "lavish"] },
  { word: "frustrate", pos: "verb", syn: ["thwart", "foil", "balk", "stymie", "dishearten"], ant: ["facilitate", "encourage", "aid"] },
  { word: "fulfill", pos: "verb", syn: ["accomplish", "satisfy", "meet", "realize", "actualize"], ant: ["fail", "disappoint", "neglect"] },
  { word: "genuine", pos: "adj", syn: ["authentic", "real", "sincere", "true", "legitimate"], ant: ["false", "fake", "counterfeit"] },
  { word: "gloomy", pos: "adj", syn: ["dark", "dreary", "dismal", "somber", "melancholy"], ant: ["bright", "cheerful", "sunny"] },
  { word: "grateful", pos: "adj", syn: ["thankful", "appreciative", "indebted", "obliged"], ant: ["ungrateful", "thankless"] },
  { word: "grief", pos: "noun", syn: ["sorrow", "mourning", "anguish", "heartache", "despair"], ant: ["joy", "happiness", "delight"] },
  { word: "guarantee", pos: "verb", syn: ["warrant", "assure", "pledge", "promise", "ensure"], ant: ["doubt", "question", "distrust"] },
  { word: "guilty", pos: "adj", syn: ["culpable", "blameworthy", "responsible", "liable", "indictable"], ant: ["innocent", "blameless", "virtuous"] },
  { word: "handicap", pos: "noun", syn: ["disability", "impairment", "disadvantage", "hindrance", "obstacle"], ant: ["asset", "advantage", "benefit"] },
  { word: "harsh", pos: "adj", syn: ["rough", "severe", "hard", "strict", "austere"], ant: ["gentle", "mild", "kind"] },
  { word: "hasten", pos: "verb", syn: ["hurry", "rush", "speed", "accelerate", "expedite"], ant: ["delay", "loiter", "procrastinate"] },
  { word: "hate", pos: "verb", syn: ["detest", "loathe", "despise", "abhor", "execrate"], ant: ["love", "adore", "cherish"] },
  { word: "hazard", pos: "noun", syn: ["danger", "risk", "peril", "threat", "jeopardy"], ant: ["safety", "security", "protection"] },
  { word: "hesitate", pos: "verb", syn: ["waver", "falter", "pause", "vacillate", "dither"], ant: ["decide", "act", "proceed"] },
  { word: "hinder", pos: "verb", syn: ["obstruct", "impede", "hamper", "thwart", "block"], ant: ["help", "assist", "facilitate"] },
  { word: "honest", pos: "adj", syn: ["truthful", "sincere", "candid", "frank", "upright"], ant: ["dishonest", "deceitful", "corrupt"] },
  { word: "humble", pos: "adj", syn: ["modest", "meek", "unassuming", "lowly", "deferential"], ant: ["arrogant", "proud", "conceited"] },
  { word: "humor", pos: "noun", syn: ["wit", "comedy", "amusement", "jocularity", "whimsy"], ant: ["seriousness", "gravity", "solemnity"] },
  { word: "idea", pos: "noun", syn: ["concept", "notion", "thought", "impression", "inkling"], ant: ["reality", "actuality", "truth"] },
  { word: "ignorant", pos: "adj", syn: ["unaware", "uninformed", "illiterate", "uneducated", "naive"], ant: ["knowledgeable", "aware", "educated"] },
  { word: "imagine", pos: "verb", syn: ["envision", "conceive", "envisage", "picture", "visualize"], ant: ["know", "experience"] },
  { word: "immediate", pos: "adj", syn: ["instant", "prompt", "urgent", "pressing", "direct"], ant: ["delayed", "deferred", "gradual"] },
  { word: "impatient", pos: "adj", syn: ["restless", "agitated", "eager", "anxious", "edgy"], ant: ["patient", "tolerant", "composed"] },
  { word: "implement", pos: "verb", syn: ["execute", "enforce", "apply", "carry out", "realize"], ant: ["neglect", "abandon", "ignore"] },
  { word: "important", pos: "adj", syn: ["significant", "crucial", "vital", "essential", "paramount"], ant: ["unimportant", "trivial", "insignificant"] },
  { word: "improve", pos: "verb", syn: ["enhance", "upgrade", "advance", "better", "refine"], ant: ["worsen", "decline", "diminish"] },
  { word: "include", pos: "verb", syn: ["incorporate", "encompass", "comprise", "contain", "embody"], ant: ["exclude", "omit", "leave out"] },
  { word: "increase", pos: "verb", syn: ["expand", "augment", "multiply", "enlarge", "proliferate"], ant: ["decrease", "reduce", "contract"] },
  { word: "indicate", pos: "verb", syn: ["show", "suggest", "imply", "demonstrate", "signal"], ant: ["hide", "conceal", "mask"] },
  { word: "inevitable", pos: "adj", syn: ["unavoidable", "inescapable", "certain", "destined", "fated"], ant: ["avoidable", "uncertain", "preventable"] },
  { word: "influence", pos: "noun", syn: ["sway", "impact", "power", "authority", "leverage"], ant: ["powerlessness", "impotence"] },
  { word: "initiate", pos: "verb", syn: ["begin", "commence", "start", "inaugurate", "instigate"], ant: ["end", "conclude", "terminate"] },
  { word: "innocent", pos: "adj", syn: ["blameless", "guiltless", "pure", "virtuous", "sinless"], ant: ["guilty", "culpable", "corrupt"] },
  { word: "inspect", pos: "verb", syn: ["examine", "scrutinize", "survey", "monitor", "check"], ant: ["overlook", "neglect"] },
  { word: "integrate", pos: "verb", syn: ["unite", "merge", "blend", "combine", "amalgamate"], ant: ["separate", "divide", "segregate"] },
  { word: "intelligent", pos: "adj", syn: ["bright", "clever", "sharp", "smart", "brilliant"], ant: ["stupid", "unintelligent", "dull"] },
  { word: "interrupt", pos: "verb", syn: ["disrupt", "break in", "intrude", "interfere", "cut off"], ant: ["continue", "allow", "let be"] },
  { word: "introduce", pos: "verb", syn: ["present", "acquaint", "inaugurate", "launch", "usher"], ant: ["withdraw", "remove"] },
  { word: "investigate", pos: "verb", syn: ["probe", "explore", "examine", "inquiry", "scrutinize"], ant: ["ignore", "overlook"] },
  { word: "isolate", pos: "verb", syn: ["seclude", "separate", "sequester", "quarantine", "detach"], ant: ["integrate", "unite", "mingle"] },
  { word: "join", pos: "verb", syn: ["connect", "unite", "attach", "link", "merge"], ant: ["separate", "disconnect", "split"] },
  { word: "jubilant", pos: "adj", syn: ["ecstatic", "elated", "thrilled", "exuberant", "exultant"], ant: ["despondent", "gloomy", "downcast"] },
  { word: "keen", pos: "adj", syn: ["eager", "enthusiastic", "sharp", "acute", "fervent"], ant: ["indifferent", "dull", "apathetic"] },
  { word: "kind", pos: "adj", syn: ["benevolent", "compassionate", "merciful", "gentle", "generous"], ant: ["cruel", "mean", "unkind"] },
  { word: "knowledge", pos: "noun", syn: ["understanding", "wisdom", "expertise", "erudition", "savvy"], ant: ["ignorance", "inexperience"] },
  { word: "labor", pos: "noun", syn: ["work", "toil", "effort", "exertion", "industry"], ant: ["leisure", "rest", "idleness"] },
  { word: "lament", pos: "verb", syn: ["mourn", "grieve", "bemoan", "sorrow", "wail"], ant: ["rejoice", "celebrate", "exult"] },
  { word: "large", pos: "adj", syn: ["big", "huge", "vast", "massive", "enormous"], ant: ["small", "tiny", "compact"] },
  { word: "latent", pos: "adj", syn: ["dormant", "hidden", "potential", "inactive", "quiescent"], ant: ["active", "manifest", "obvious"] },
  { word: "laudable", pos: "adj", syn: ["praiseworthy", "commendable", "admirable", "worthy", "meritorious"], ant: ["blameworthy", "reprehensible"] },
  { word: "lenient", pos: "adj", syn: ["permissive", "tolerant", "easygoing", "indulgent", "forgiving"], ant: ["strict", "severe", "harsh"] },
  { word: "liable", pos: "adj", syn: ["responsible", "accountable", "answerable", "subject", "prone"], ant: ["immune", "exempt", "unaccountable"] },
  { word: "liberal", pos: "adj", syn: ["generous", "progressive", "open", "broad-minded", "tolerant"], ant: ["conservative", "stingy", "narrow-minded"] },
  { word: "limit", pos: "verb", syn: ["restrict", "confine", "curb", "cap", "bound"], ant: ["expand", "unrestrict", "free"] },
  { word: "logical", pos: "adj", syn: ["rational", "sound", "coherent", "reasonable", "sensible"], ant: ["illogical", "absurd", "irrational"] },
  { word: "lonely", pos: "adj", syn: ["solitary", "isolated", "forlorn", "desolate", "lonesome"], ant: ["accompanied", "popular", "sociable"] },
  { word: "lucid", pos: "adj", syn: ["clear", "transparent", "coherent", "intelligible", "comprehensible"], ant: ["obscure", "ambiguous", "confused"] },
  { word: "lucky", pos: "adj", syn: ["fortunate", "blessed", "auspicious", "favored", "serendipitous"], ant: ["unlucky", "hapless", "cursed"] },
  { word: "magnificent", pos: "adj", syn: ["grand", "splendid", "glorious", "imposing", "majestic"], ant: ["inferior", "modest", "unimpressive"] },
  { word: "maintain", pos: "verb", syn: ["preserve", "sustain", "uphold", "keep", "retain"], ant: ["abandon", "neglect", "discontinue"] },
  { word: "massive", pos: "adj", syn: ["huge", "immense", "colossal", "gigantic", "vast"], ant: ["tiny", "minute", "compact"] },
  { word: "mature", pos: "adj", syn: ["grown", "adult", "ripen", "developed", "seasoned"], ant: ["immature", "juvenile", "childish"] },
  { word: "meager", pos: "adj", syn: ["scanty", "sparse", "insufficient", "meager", "inadequate"], ant: ["abundant", "plentiful", "ample"] },
  { word: "meditate", pos: "verb", syn: ["contemplate", "reflect", "ponder", "ruminate", "deliberate"], ant: ["distract", "agitate", "ignore"] },
  { word: "mend", pos: "verb", syn: ["repair", "fix", "restore", "remedy", "rectify"], ant: ["break", "damage", "worsen"] },
  { word: "meticulous", pos: "adj", syn: ["thorough", "careful", "precise", "scrupulous", "fastidious"], ant: ["careless", "sloppy", "negligent"] },
  { word: "mild", pos: "adj", syn: ["gentle", "temperate", "soft", "placid", "moderate"], ant: ["strong", "fierce", "intense"] },
  { word: "minimum", pos: "noun", syn: ["least", "lowest", "smallest", "minimal", "bottom"], ant: ["maximum", "highest", "peak"] },
  { word: "minute", pos: "adj", syn: ["tiny", "minuscule", "microscopic", "diminutive", "negligible"], ant: ["vast", "enormous", "immense"] },
  { word: "modify", pos: "verb", syn: ["alter", "change", "adjust", "revise", "adapt"], ant: ["preserve", "maintain", "fix"] },
  { word: "monotonous", pos: "adj", syn: ["tedious", "dull", "boring", "repetitive", "humdrum"], ant: ["exciting", "varied", "engaging"] },
  { word: "moral", pos: "adj", syn: ["ethical", "virtuous", "upright", "righteous", "principled"], ant: ["immoral", "corrupt", "unethical"] },
  { word: "naive", pos: "adj", syn: ["innocent", "gullible", "ingenuous", "unsophisticated", "credulous"], ant: ["worldly", "sophisticated", "suspicious"] },
  { word: "narrow", pos: "adj", syn: ["slender", "tight", "constricted", "limited", "restricted"], ant: ["wide", "broad", "spacious"] },
  { word: "neglect", pos: "verb", syn: ["disregard", "ignore", "abandon", "overlook", "shirk"], ant: ["attend", "care for", "nurture"] },
  { word: "noble", pos: "adj", syn: ["dignified", "exalted", "respected", "honorable", "majestic"], ant: ["ignoble", "base", "dishonorable"] },
  { word: "notable", pos: "adj", syn: ["noteworthy", "remarkable", "prominent", "distinguished", "outstanding"], ant: ["unremarkable", "ordinary", "common"] },
  { word: "novel", pos: "adj", syn: ["original", "innovative", "new", "fresh", "unprecedented"], ant: ["old", "traditional", "stale"] },
  { word: "nurture", pos: "verb", syn: ["foster", "cultivate", "nourish", "support", "tend"], ant: ["neglect", "abandon", "stifle"] },
  { word: "obey", pos: "verb", syn: ["comply", "submit", "conform", "follow", "respect"], ant: ["defy", "disobey", "rebel"] },
  { word: "obscure", pos: "adj", syn: ["unclear", "vague", "ambiguous", "cryptic", "enigmatic"], ant: ["clear", "obvious", "apparent"] },
  { word: "obstacle", pos: "noun", syn: ["barrier", "hindrance", "impediment", "obstruction", "block"], ant: ["advantage", "help", "aid"] },
  { word: "obtain", pos: "verb", syn: ["acquire", "secure", "procure", "gain", "attain"], ant: ["lose", "forfeit", "surrender"] },
  { word: "obvious", pos: "adj", syn: ["evident", "clear", "apparent", "conspicuous", "blatant"], ant: ["obscure", "subtle", "hidden"] },
  { word: "occupy", pos: "verb", syn: ["inhabit", "fill", "engage", "busy", "possess"], ant: ["vacate", "empty", "leave"] },
  { word: "offend", pos: "verb", syn: ["insult", "affront", "anger", "provoke", "vex"], ant: ["please", "compliment", "appease"] },
  { word: "operate", pos: "verb", syn: ["function", "run", "manage", "work", "perform"], ant: ["idle", "halt", "cease"] },
  { word: "opinion", pos: "noun", syn: ["view", "perspective", "belief", "judgment", "sentiment"], ant: ["fact", "truth", "certainty"] },
  { word: "oppose", pos: "verb", syn: ["resist", "defy", "protest", "contradict", "combat"], ant: ["support", "back", "assist"] },
  { word: "optimistic", pos: "adj", syn: ["hopeful", "positive", "upbeat", "encouraging", "cheerful"], ant: ["pessimistic", "cynical", "gloomy"] },
  { word: "origin", pos: "noun", syn: ["source", "beginning", "root", "start", "genesis"], ant: ["end", "conclusion", "termination"] },
  { word: "outstanding", pos: "adj", syn: ["exceptional", "superb", "remarkable", "notable", "excellent"], ant: ["ordinary", "unremarkable", "mediocre"] },
  { word: "overcome", pos: "verb", syn: ["conquer", "surmount", "vanquish", "beat", "defeat"], ant: ["surrender", "succumb", "yield"] },
  { word: "passion", pos: "noun", syn: ["enthusiasm", "fervor", "zeal", "ardor", "excitement"], ant: ["apathy", "indifference", "calm"] },
  { word: "passive", pos: "adj", syn: ["inactive", "submissive", "compliant", "inert", "unresponsive"], ant: ["active", "assertive", "aggressive"] },
  { word: "patience", pos: "noun", syn: ["tolerance", "forbearance", "perseverance", "endurance", "calmness"], ant: ["impatience", "restlessness"] },
  { word: "peculiar", pos: "adj", syn: ["strange", "odd", "unusual", "bizarre", "eccentric"], ant: ["normal", "ordinary", "typical"] },
  { word: "permanent", pos: "adj", syn: ["lasting", "enduring", "eternal", "perpetual", "everlasting"], ant: ["temporary", "transient", "fleeting"] },
  { word: "permit", pos: "verb", syn: ["allow", "authorize", "grant", "sanction", "consent"], ant: ["forbid", "prohibit", "ban"] },
  { word: "persist", pos: "verb", syn: ["continue", "persevere", "endure", "last", "keep on"], ant: ["stop", "cease", "give up"] },
  { word: "persuade", pos: "verb", syn: ["convince", "induce", "prevail upon", "prompt", "influence"], ant: ["dissuade", "deter", "discourage"] },
  { word: "polite", pos: "adj", syn: ["courteous", "respectful", "civil", "gracious", "well-mannered"], ant: ["rude", "impolite", "discourteous"] },
  { word: "poor", pos: "adj", syn: ["destitute", "impoverished", "needy", "indigent", "penniless"], ant: ["rich", "wealthy", "affluent"] },
  { word: "popular", pos: "adj", syn: ["famous", "well-liked", "trending", "fashionable", "predominant"], ant: ["unpopular", "unknown", "obscure"] },
  { word: "portion", pos: "noun", syn: ["part", "segment", "share", "piece", "fraction"], ant: ["whole", "entirety", "total"] },
  { word: "poverty", pos: "noun", syn: ["destitution", "indigence", "neediness", "penury", "impoverishment"], ant: ["wealth", "affluence", "prosperity"] },
  { word: "praise", pos: "verb", syn: ["commend", "acclaim", "applaud", "extol", "laud"], ant: ["criticize", "blame", "censure"] },
  { word: "precarious", pos: "adj", syn: ["unstable", "risky", "hazardous", "insecure", "perilous"], ant: ["stable", "safe", "secure"] },
  { word: "precious", pos: "adj", syn: ["valuable", "cherished", "dear", "prized", "beloved"], ant: ["worthless", "cheap", "common"] },
  { word: "precise", pos: "adj", syn: ["exact", "accurate", "meticulous", "specific", "detailed"], ant: ["vague", "imprecise", "approximate"] },
  { word: "predict", pos: "verb", syn: ["forecast", "foresee", "prophesy", "project", "anticipate"], ant: ["surprise", "retrospect"] },
  { word: "prefer", pos: "verb", syn: ["favor", "like better", "choose", "opt for", "elect"], ant: ["dislike", "reject", "avoid"] },
  { word: "prejudice", pos: "noun", syn: ["bias", "discrimination", "partiality", "bigotry", "intolerance"], ant: ["fairness", "objectivity", "tolerance"] },
  { word: "prepare", pos: "verb", syn: ["ready", "arrange", "organize", "plan", "set up"], ant: ["neglect", "improvise", "ignore"] },
  { word: "preserve", pos: "verb", syn: ["conserve", "maintain", "protect", "save", "retain"], ant: ["destroy", "discard", "waste"] },
  { word: "prevent", pos: "verb", syn: ["stop", "avert", "hinder", "thwart", "obstruct"], ant: ["allow", "encourage", "permit"] },
  { word: "previous", pos: "adj", syn: ["prior", "former", "past", "preceding", "earlier"], ant: ["next", "following", "later"] },
  { word: "privilege", pos: "noun", syn: ["advantage", "benefit", "entitlement", "favor", "right"], ant: ["disadvantage", "disability"] },
  { word: "proceed", pos: "verb", syn: ["continue", "advance", "go on", "carry on", "press on"], ant: ["stop", "pause", "cease"] },
  { word: "produce", pos: "verb", syn: ["create", "generate", "manufacture", "make", "yield"], ant: ["destroy", "consume", "use up"] },
  { word: "profit", pos: "noun", syn: ["gain", "benefit", "advantage", "return", "dividends"], ant: ["loss", "deficit", "liability"] },
  { word: "progress", pos: "noun", syn: ["advancement", "headway", "development", "growth", "improvement"], ant: ["regression", "decline", "stagnation"] },
  { word: "prohibit", pos: "verb", syn: ["forbid", "ban", "outlaw", "bar", "disallow"], ant: ["allow", "permit", "authorize"] },
  { word: "prominent", pos: "adj", syn: ["eminent", "distinguished", "notable", "preeminent", "conspicuous"], ant: ["unknown", "obscure", "insignificant"] },
  { word: "promote", pos: "verb", syn: ["advance", "boost", "encourage", "encourage", "further"], ant: ["demote", "discourage", "hinder"] },
  { word: "prompt", pos: "adj", syn: ["quick", "immediate", "swift", "rapid", "punctual"], ant: ["slow", "dilatory", "tardy"] },
  { word: "proper", pos: "adj", syn: ["correct", "appropriate", "suitable", "fitting", "right"], ant: ["improper", "inappropriate", "wrong"] },
  { word: "prosper", pos: "verb", syn: ["thrive", "flourish", "succeed", "bloom", "boom"], ant: ["fail", "decline", "founder"] },
  { word: "protect", pos: "verb", syn: ["defend", "guard", "shield", "safeguard", "preserve"], ant: ["attack", "endanger", "expose"] },
  { word: "proud", pos: "adj", syn: ["arrogant", "conceited", "haughty", "vain", "self-important"], ant: ["humble", "modest", "meek"] },
  { word: "prove", pos: "verb", syn: ["demonstrate", "confirm", "verify", "substantiate", "validate"], ant: ["disprove", "refute", "discredit"] },
  { word: "provoke", pos: "verb", syn: ["incite", "provoke", "rouse", "goad", "stir up"], ant: ["calm", "pacify", "soothe"] },
  { word: "prudent", pos: "adj", syn: ["cautious", "careful", "judicious", "wise", "discerning"], ant: ["foolish", "imprudent", "rash"] },
  { word: "purchase", pos: "verb", syn: ["buy", "acquire", "obtain", "procure", "pay for"], ant: ["sell", "vend", "dispose"] },
  { word: "purpose", pos: "noun", syn: ["intention", "aim", "goal", "objective", "motive"], ant: ["chance", "accident", "randomness"] },
  { word: "pursue", pos: "verb", syn: ["chase", "follow", "seek", "strive for", "go after"], ant: ["flee", "avoid", "shun"] },
  { word: "qualified", pos: "adj", syn: ["competent", "capable", "skilled", "trained", "proficient"], ant: ["unqualified", "incompetent", "inept"] },
  { word: "quarrel", pos: "noun", syn: ["argument", "dispute", "feud", "squabble", "altercation"], ant: ["agreement", "harmony", "accord"] },
  { word: "queer", pos: "adj", syn: ["odd", "eccentric", "unusual", "peculiar", "strange"], ant: ["normal", "ordinary", "conventional"] },
  { word: "question", pos: "noun", syn: ["inquiry", "query", "interrogation", "doubt", "issue"], ant: ["answer", "response", "solution"] },
  { word: "quick", pos: "adj", syn: ["fast", "swift", "rapid", "speedy", "brisk"], ant: ["slow", "leisurely", "gradual"] },
  { word: "quiet", pos: "adj", syn: ["silent", "still", "calm", "peaceful", "noiseless"], ant: ["loud", "noisy", "chaotic"] },
  { word: "quit", pos: "verb", syn: ["resign", "abandon", "withdraw", "cease", "stop"], ant: ["begin", "continue", "persist"] },
  { word: "random", pos: "adj", syn: ["arbitrary", "chance", "haphazard", "incidental", "unpredictable"], ant: ["intentional", "systematic", "deliberate"] },
  { word: "rare", pos: "adj", syn: ["uncommon", "scarce", "infrequent", "sporadic", "unusual"], ant: ["common", "frequent", "ordinary"] },
  { word: "rational", pos: "adj", syn: ["reasonable", "sensible", "logical", "sound", "judicious"], ant: ["irrational", "illogical", "absurd"] },
  { word: "raw", pos: "adj", syn: ["uncooked", "unprocessed", "crude", "natural", "rough"], ant: ["cooked", "refined", "processed"] },
  { word: "ready", pos: "adj", syn: ["prepared", "set", "available", "primed", "willing"], ant: ["unprepared", "unwilling", "hesitant"] },
  { word: "real", pos: "adj", syn: ["actual", "true", "authentic", "genuine", "tangible"], ant: ["unreal", "fake", "imaginary"] },
  { word: "reasonable", pos: "adj", syn: ["sensible", "fair", "moderate", "logical", "plausible"], ant: ["unreasonable", "excessive", "absurd"] },
  { word: "rebel", pos: "verb", syn: ["revolt", "mutiny", "defy", "resist", "rise up"], ant: ["submit", "obey", "comply"] },
  { word: "receive", pos: "verb", syn: ["accept", "acquire", "obtain", "get", "collect"], ant: ["give", "donate", "offer"] },
  { word: "reckless", pos: "adj", syn: ["careless", "rash", "impulsive", "foolhardy", "daring"], ant: ["cautious", "careful", "prudent"] },
  { word: "recognize", pos: "verb", syn: ["identify", "acknowledge", "discern", "distinguish", "realize"], ant: ["ignore", "overlook", "miss"] },
  { word: "recommend", pos: "verb", syn: ["advise", "endorse", "advocate", "suggest", "propose"], ant: ["discourage", "caution against"] },
  { word: "reduce", pos: "verb", syn: ["lessen", "decrease", "diminish", "cut", "curtail"], ant: ["increase", "augment", "expand"] },
  { word: "reflect", pos: "verb", syn: ["mirror", "consider", "contemplate", "ponder", "deliberate"], ant: ["ignore", "disregard"] },
  { word: "reform", pos: "verb", syn: ["improve", "rectify", "correct", "amend", "overhaul"], ant: ["corrupt", "worsen", "degrade"] },
  { word: "refuse", pos: "verb", syn: ["decline", "reject", "deny", "withhold", "spurn"], ant: ["accept", "agree", "consent"] },
  { word: "regret", pos: "verb", syn: ["rue", "lament", "bemoan", "mourn", "deplore"], ant: ["rejoice", "celebrate", "satisfy"] },
  { word: "regular", pos: "adj", syn: ["routine", "habitual", "normal", "standard", "typical"], ant: ["irregular", "unusual", "exceptional"] },
  { word: "reject", pos: "verb", syn: ["refuse", "decline", "spurn", "rebuff", "dismiss"], ant: ["accept", "embrace", "welcome"] },
  { word: "relax", pos: "verb", syn: ["unwind", "decompress", "rest", "loosen", "unwind"], ant: ["tense up", "strain", "work"] },
  { word: "release", pos: "verb", syn: ["free", "liberate", "unleash", "let go", "discharge"], ant: ["capture", "confine", "detain"] },
  { word: "reliable", pos: "adj", syn: ["dependable", "trustworthy", "consistent", "responsible", "solid"], ant: ["unreliable", "undependable", "fickle"] },
  { word: "reluctant", pos: "adj", syn: ["hesitant", "unwilling", "loath", "averse", "dubious"], ant: ["eager", "willing", "ready"] },
  { word: "remain", pos: "verb", syn: ["stay", "abide", "persist", "endure", "linger"], ant: ["leave", "depart", "go"] },
  { word: "remarkable", pos: "adj", syn: ["noteworthy", "striking", "exceptional", "outstanding", "extraordinary"], ant: ["ordinary", "average", "unremarkable"] },
  { word: "remedy", pos: "noun", syn: ["cure", "treatment", "solution", "antidote", "corrective"], ant: ["cause", "aggravation", "ailment"] },
  { word: "remote", pos: "adj", syn: ["distant", "far", "isolated", "secluded", "secluded"], ant: ["near", "close", "accessible"] },
  { word: "remove", pos: "verb", syn: ["delete", "eliminate", "erase", "extract", "abolish"], ant: ["add", "insert", "include"] },
  { word: "renew", pos: "verb", syn: ["refresh", "restore", "revive", "rejuvenate", "replenish"], ant: ["exhaust", "deplete", "stale"] },
  { word: "repair", pos: "verb", syn: ["fix", "mend", "restore", "rectify", "overhaul"], ant: ["break", "damage", "wreck"] },
  { word: "replace", pos: "verb", syn: ["substitute", "swap", "exchange", "supplant", "supersede"], ant: ["retain", "keep", "preserve"] },
  { word: "represent", pos: "verb", syn: ["symbolize", "stand for", "depict", "portray", "embody"], ant: ["distort", "misrepresent"] },
  { word: "reproach", pos: "verb", syn: ["blame", "censure", "criticize", "reprimand", "rebuke"], ant: ["praise", "commend", "approve"] },
  { word: "repulsive", pos: "adj", syn: ["disgusting", "revolting", "loathsome", "offensive", "abhorrent"], ant: ["attractive", "appealing", "pleasant"] },
  { word: "rescue", pos: "verb", syn: ["save", "deliver", "extricate", "liberate", "reclaim"], ant: ["capture", "endanger", "abandon"] },
  { word: "resist", pos: "verb", syn: ["withstand", "oppose", "defy", "fight", "rebel"], ant: ["yield", "surrender", "submit"] },
  { word: "resolute", pos: "adj", syn: ["determined", "firm", "steadfast", "unyielding", "tenacious"], ant: ["irresolute", "wavering", "indecisive"] },
  { word: "resolve", pos: "verb", syn: ["settle", "solve", "decide", "determine", "remedy"], ant: ["waver", "vacillate", "prolong"] },
  { word: "respect", pos: "verb", syn: ["admire", "esteem", "venerate", "honor", "revere"], ant: ["despise", "scorn", "disdain"] },
  { word: "responsible", pos: "adj", syn: ["accountable", "answerable", "liable", "dependable", "reliable"], ant: ["irresponsible", "unreliable", "negligent"] },
  { word: "restore", pos: "verb", syn: ["revive", "renew", "reestablish", "rehabilitate", "bring back"], ant: ["damage", "destroy", "remove"] },
  { word: "restrict", pos: "verb", syn: ["limit", "confine", "curb", "constrain", "control"], ant: ["free", "release", "liberate"] },
  { word: "retain", pos: "verb", syn: ["keep", "hold", "maintain", "preserve", "reserve"], ant: ["release", "relinquish", "lose"] },
  { word: "reveal", pos: "verb", syn: ["disclose", "expose", "divulge", "unveil", "unmask"], ant: ["conceal", "hide", "suppress"] },
  { word: "revenge", pos: "noun", syn: ["vengeance", "retaliation", "reprisal", "retribution", "avengement"], ant: ["forgiveness", "pardon", "mercy"] },
  { word: "revere", pos: "verb", syn: ["venerate", "adore", "worship", "respect", "cherish"], ant: ["despise", "scorn", "disrespect"] },
  { word: "revise", pos: "verb", syn: ["amend", "correct", "update", "edit", "reconsider"], ant: ["preserve", "keep", "maintain"] },
  { word: "revive", pos: "verb", syn: ["resuscitate", "reanimate", "rejuvenate", "restore", "renew"], ant: ["kill", "extinguish", "suppress"] },
  { word: "rich", pos: "adj", syn: ["wealthy", "affluent", "prosperous", "opulent", "well-off"], ant: ["poor", "destitute", "impoverished"] },
  { word: "ridicule", pos: "verb", syn: ["mock", "deride", "taunt", "tease", "scorn"], ant: ["praise", "admire", "honor"] },
  { word: "rigid", pos: "adj", syn: ["stiff", "inflexible", "unyielding", "stubborn", "adamant"], ant: ["flexible", "pliable", "adaptable"] },
  { word: "rigorous", pos: "adj", syn: ["thorough", "strict", "exacting", "demanding", "stringent"], ant: ["superficial", "lenient", "slack"] },
  { word: "rival", pos: "noun", syn: ["competitor", "adversary", "opponent", "contender", "challenger"], ant: ["ally", "partner", "associate"] },
  { word: "robust", pos: "adj", syn: ["strong", "vigorous", "sturdy", "hearty", "powerful"], ant: ["weak", "fragile", "feeble"] },
  { word: "rough", pos: "adj", syn: ["uneven", "coarse", "bumpy", "rugged", "jagged"], ant: ["smooth", "even", "polished"] },
  { word: "routine", pos: "noun", syn: ["habit", "custom", "practice", "regimen", "protocol"], ant: ["exception", "change", "spontaneity"] },
  { word: "rude", pos: "adj", syn: ["discourteous", "impolite", "ill-mannered", "uncivil", "blunt"], ant: ["polite", "courteous", "civil"] },
  { word: "ruin", pos: "verb", syn: ["destroy", "devastate", "wreck", "sabotage", "demolish"], ant: ["build", "restore", "preserve"] },
  { word: "sacred", pos: "adj", syn: ["holy", "divine", "consecrated", "sanctified", "venerated"], ant: ["profane", "secular", "unholy"] },
  { word: "sacrifice", pos: "verb", syn: ["relinquish", "surrender", "forgo", "offer", "forfeit"], ant: ["keep", "retain", "hold"] },
  { word: "sad", pos: "adj", syn: ["unhappy", "sorrowful", "dejected", "melancholy", "mournful"], ant: ["happy", "joyful", "elated"] },
  { word: "safe", pos: "adj", syn: ["secure", "protected", "shielded", "invulnerable", "risk-free"], ant: ["dangerous", "risky", "precarious"] },
  { word: "satisfy", pos: "verb", syn: ["gratify", "fulfill", "appease", "pleasure", "content"], ant: ["dissatisfy", "displease", "frustrate"] },
  { word: "scatter", pos: "verb", syn: ["disperse", "sprinkle", "spread", "distribute", "strew"], ant: ["gather", "collect", "assemble"] },
  { word: "scent", pos: "noun", syn: ["fragrance", "aroma", "perfume", "odor", "smell"], ant: ["stench", "stink", "reek"] },
  { word: "sceptical", pos: "adj", syn: ["doubtful", "cynical", "unconvinced", "dubious", "incredulous"], ant: ["trusting", "gullible", "convinced"] },
  { word: "search", pos: "verb", syn: ["seek", "hunt", "scour", "explore", "comb"], ant: ["ignore", "neglect", "overlook"] },
  { word: "seasoned", pos: "adj", syn: ["experienced", "veteran", "practiced", "expert", "established"], ant: ["novice", "beginner", "green"] },
  { word: "secret", pos: "adj", syn: ["confidential", "covert", "clandestine", "stealthy", "private"], ant: ["open", "public", "transparent"] },
  { word: "secure", pos: "adj", syn: ["safe", "protected", "shielded", "impregnable", "inviolable"], ant: ["vulnerable", "insecure", "exposed"] },
  { word: "sensible", pos: "adj", syn: ["reasonable", "practical", "logical", "rational", "sound"], ant: ["foolish", "impractical", "senseless"] },
  { word: "sensitive", pos: "adj", syn: ["delicate", "touchy", "vulnerable", "receptive", "responsive"], ant: ["insensitive", "tough", "callous"] },
  { word: "severe", pos: "adj", syn: ["strict", "harsh", "serious", "intense", "drastic"], ant: ["mild", "lenient", "gentle"] },
  { word: "shallow", pos: "adj", syn: ["superficial", "surface", "empty", "trivial", "cursory"], ant: ["deep", "profound", "thorough"] },
  { word: "shame", pos: "noun", syn: ["embarrassment", "humiliation", "disgrace", "ignominy", "chagrin"], ant: ["pride", "honor", "glory"] },
  { word: "short", pos: "adj", syn: ["brief", "concise", "limited", "abbreviated", "fleeting"], ant: ["long", "extended", "prolonged"] },
  { word: "show", pos: "verb", syn: ["display", "demonstrate", "exhibit", "reveal", "present"], ant: ["hide", "conceal", "mask"] },
  { word: "shrewd", pos: "adj", syn: ["astute", "sharp", "clever", "perceptive", "discerning"], ant: ["naive", "dull", "obtuse"] },
  { word: "shy", pos: "adj", syn: ["timid", "bashful", "reserved", "reticent", "introverted"], ant: ["outgoing", "bold", "confident"] },
  { word: "significant", pos: "adj", syn: ["important", "consequential", "meaningful", "notable", "substantial"], ant: ["insignificant", "trivial", "minor"] },
  { word: "silent", pos: "adj", syn: ["quiet", "still", "noiseless", "mute", "speechless"], ant: ["noisy", "loud", "vociferous"] },
  { word: "similar", pos: "adj", syn: ["alike", "comparable", "analogous", "akin", "equivalent"], ant: ["different", "dissimilar", "divergent"] },
  { word: "simple", pos: "adj", syn: ["easy", "plain", "uncomplicated", "effortless", "straightforward"], ant: ["complex", "complicated", "difficult"] },
  { word: "sincere", pos: "adj", syn: ["honest", "genuine", "true", "candid", "authentic"], ant: ["insincere", "false", "hypocritical"] },
  { word: "skill", pos: "noun", syn: ["expertise", "proficiency", "mastery", "dexterity", "competence"], ant: ["ineptitude", "incompetence"] },
  { word: "slander", pos: "verb", syn: ["defame", "vilify", "malign", "smear", "disparage"], ant: ["praise", "extol", "acclaim"] },
  { word: "slight", pos: "adj", syn: ["small", "minor", "trivial", "insignificant", "negligible"], ant: ["large", "significant", "major"] },
  { word: "slogan", pos: "noun", syn: ["motto", "catchphrase", "banner", "maxim", "creed"], ant: ["silence", "muteness"] },
  { word: "smooth", pos: "adj", syn: ["even", "flat", "polished", "sleek", "silky"], ant: ["rough", "uneven", "coarse"] },
  { word: "sociable", pos: "adj", syn: ["friendly", "outgoing", "gregarious", "affable", "companionable"], ant: ["unsociable", "aloof", "reclusive"] },
  { word: "soft", pos: "adj", syn: ["gentle", "mild", "tender", "delicate", "yielding"], ant: ["hard", "firm", "stiff"] },
  { word: "solemn", pos: "adj", syn: ["serious", "grave", "somber", "dignified", "ceremonious"], ant: ["cheerful", "jovial", "frivolous"] },
  { word: "solid", pos: "adj", syn: ["firm", "hard", "strong", "substantial", "sturdy"], ant: ["liquid", "gaseous", "insubstantial"] },
  { word: "sophisticated", pos: "adj", syn: ["refined", "cultured", "worldly", "polished", "cosmopolitan"], ant: ["unsophisticated", "naive", "crude"] },
  { word: "sorrow", pos: "noun", syn: ["grief", "sadness", "anguish", "woe", "heartache"], ant: ["joy", "happiness", "delight"] },
  { word: "spare", pos: "verb", syn: ["save", "reserve", "refrain", "forbear", "withhold"], ant: ["spend", "waste", "consume"] },
  { word: "spark", pos: "noun", syn: ["flash", "gleam", "glint", "glitter", "flicker"], ant: ["darkness", "extinguish", "quench"] },
  { word: "special", pos: "adj", syn: ["unique", "exceptional", "notable", "distinctive", "particular"], ant: ["ordinary", "common", "general"] },
  { word: "specific", pos: "adj", syn: ["particular", "definite", "explicit", "precise", "concrete"], ant: ["general", "vague", "ambiguous"] },
  { word: "splendid", pos: "adj", syn: ["magnificent", "glorious", "superb", "resplendent", "grand"], ant: ["inferior", "mediocre", "shabby"] },
  { word: "spontaneous", pos: "adj", syn: ["impulsive", "natural", "unprompted", "instinctive", "automatic"], ant: ["planned", "deliberate", "rehearsed"] },
  { word: "stable", pos: "adj", syn: ["steady", "secure", "firm", "balanced", "constant"], ant: ["unstable", "precarious", "volatile"] },
  { word: "start", pos: "verb", syn: ["begin", "commence", "initiate", "launch", "originate"], ant: ["stop", "finish", "cease"] },
  { word: "stern", pos: "adj", syn: ["strict", "severe", "firm", "austere", "adamant"], ant: ["lenient", "gentle", "permissive"] },
  { word: "stiff", pos: "adj", syn: ["rigid", "inflexible", "unyielding", "hard", "taut"], ant: ["flexible", "limber", "loose"] },
  { word: "still", pos: "adj", syn: ["motionless", "stationary", "calm", "tranquil", "serene"], ant: ["moving", "agitated", "active"] },
  { word: "stimulate", pos: "verb", syn: ["invigorate", "motivate", "inspire", "energize", "encourage"], ant: ["dampen", "discourage", "subdue"] },
  { word: "stingy", pos: "adj", syn: ["miserly", "tight", "parsimonious", "niggardly", "penny-pinching"], ant: ["generous", "liberal", "open-handed"] },
  { word: "strange", pos: "adj", syn: ["odd", "peculiar", "unusual", "bizarre", "eccentric"], ant: ["normal", "ordinary", "familiar"] },
  { word: "strict", pos: "adj", syn: ["stern", "rigorous", "stringent", "severe", "exacting"], ant: ["lenient", "permissive", "easygoing"] },
  { word: "stubborn", pos: "adj", syn: ["obstinate", "headstrong", "unyielding", "intransigent", "inflexible"], ant: ["flexible", "compliant", "submissive"] },
  { word: "study", pos: "verb", syn: ["learn", "examine", "analyze", "review", "scrutinize"], ant: ["neglect", "ignore", "overlook"] },
  { word: "sturdy", pos: "adj", syn: ["robust", "strong", "durable", "stout", "substantial"], ant: ["weak", "fragile", "filmsy"] },
  { word: "submit", pos: "verb", syn: ["yield", "surrender", "comply", "capitulate", "acquiesce"], ant: ["resist", "defy", "rebel"] },
  { word: "subtle", pos: "adj", syn: ["delicate", "faint", "fine", "nuanced", "understated"], ant: ["obvious", "blatant", "crude"] },
  { word: "succeed", pos: "verb", syn: ["prosper", "thrive", "flourish", "triumph", "make it"], ant: ["fail", "flounder", "collapse"] },
  { word: "sufficient", pos: "adj", syn: ["enough", "adequate", "ample", "abundant", "satisfactory"], ant: ["insufficient", "inadequate", "meager"] },
  { word: "suggest", pos: "verb", syn: ["propose", "recommend", "advise", "advocate", "hint"], ant: ["demand", "insist", "order"] },
  { word: "suitable", pos: "adj", syn: ["appropriate", "fitting", "proper", "apt", "befitting"], ant: ["unsuitable", "inappropriate", "unfit"] },
  { word: "summary", pos: "noun", syn: ["synopsis", "abstract", "precis", "outline", "digest"], ant: ["full text", "original", "elaboration"] },
  { word: "superb", pos: "adj", syn: ["excellent", "magnificent", "splendid", "outstanding", "first-rate"], ant: ["poor", "inferior", "mediocre"] },
  { word: "superficial", pos: "adj", syn: ["shallow", "cursory", "surface", "trivial", "skin-deep"], ant: ["deep", "thorough", "profound"] },
  { word: "supply", pos: "verb", syn: ["provide", "furnish", "deliver", "stock", "equip"], ant: ["withhold", "deprive", "deplete"] },
  { word: "support", pos: "verb", syn: ["uphold", "sustain", "back", "assist", "encourage"], ant: ["oppose", "undermine", "sabotage"] },
  { word: "suppose", pos: "verb", syn: ["assume", "presume", "presuppose", "postulate", "infer"], ant: ["know", "confirm", "prove"] },
  { word: "suppress", pos: "verb", syn: ["subdue", "quash", "quell", "repress", "crush"], ant: ["express", "release", "encourage"] },
  { word: "sure", pos: "adj", syn: ["certain", "confident", "positive", "assured", "convinced"], ant: ["uncertain", "doubtful", "unsure"] },
  { word: "surplus", pos: "noun", syn: ["excess", "oversupply", "glut", "abundance", "surfeit"], ant: ["deficit", "shortage", "scarcity"] },
  { word: "surprise", pos: "verb", syn: ["astonish", "amaze", "startle", "astound", "stun"], ant: ["expect", "anticipate", "predict"] },
  { word: "surrender", pos: "verb", syn: ["capitulate", "submit", "yield", "relinquish", "give in"], ant: ["resist", "fight", "defy"] },
  { word: "surround", pos: "verb", syn: ["encircle", "encompass", "envelop", "encompass", "circle"], ant: ["expose", "open"] },
  { word: "survive", pos: "verb", syn: ["endure", "last", "persist", "continue", "prevail"], ant: ["perish", "die", "succumb"] },
  { word: "suspect", pos: "verb", syn: ["distrust", "mistrust", "doubt", "question", "challenge"], ant: ["trust", "believe", "credit"] },
  { word: "suspend", pos: "verb", syn: ["hang", "defer", "postpone", "halt", "interrupt"], ant: ["continue", "resume", "allow"] },
  { word: "suspicious", pos: "adj", syn: ["distrustful", "doubtful", "skeptical", "leery", "wary"], ant: ["trusting", "confident", "credulous"] },
  { word: "sustain", pos: "verb", syn: ["maintain", "support", "uphold", "prolong", "preserve"], ant: ["abandon", "exhaust", "weaken"] },
  { word: "swift", pos: "adj", syn: ["fast", "rapid", "quick", "speedy", "brisk"], ant: ["slow", "gradual", "leisurely"] },
  { word: "symbol", pos: "noun", syn: ["emblem", "token", "representative", "icon", "badge"], ant: ["literal", "reality"] },
  { word: "sympathy", pos: "noun", syn: ["compassion", "pity", "empathy", "understanding", "kindness"], ant: ["apathy", "callousness", "disdain"] },
  { word: "talent", pos: "noun", syn: ["gift", "aptitude", "faculty", "genius", "flair"], ant: ["ineptitude", "clumsiness"] },
  { word: "tame", pos: "adj", syn: ["domesticated", "docile", "gentle", "subdued", "obedient"], ant: ["wild", "savage", "untamed"] },
  { word: "tangle", pos: "verb", syn: ["entangle", "snarl", "knot", "ravel", "complicate"], ant: ["untangle", "disentangle", "solve"] },
  { word: "tardy", pos: "adj", syn: ["late", "overdue", "belated", "delayed", "unpunctual"], ant: ["early", "prompt", "punctual"] },
  { word: "tedious", pos: "adj", syn: ["boring", "monotonous", "dreary", "humdrum", "tiresome"], ant: ["exciting", "stimulating", "engaging"] },
  { word: "temporary", pos: "adj", syn: ["provisional", "interim", "transient", "short-lived", "impermanent"], ant: ["permanent", "lasting", "eternal"] },
  { word: "tempt", pos: "verb", syn: ["entice", "lure", "seduce", "attract", "beguile"], ant: ["repel", "deter", "discourage"] },
  { word: "tender", pos: "adj", syn: ["gentle", "soft", "delicate", "sensitive", "affectionate"], ant: ["tough", "hard", "callous"] },
  { word: "tense", pos: "adj", syn: ["strained", "taut", "anxious", "nervous", "wound up"], ant: ["relaxed", "calm", "loose"] },
  { word: "terminate", pos: "verb", syn: ["end", "conclude", "cease", "finish", "discontinue"], ant: ["begin", "start", "commence"] },
  { word: "terrible", pos: "adj", syn: ["awful", "dreadful", "horrible", "appalling", "atrocious"], ant: ["wonderful", "excellent", "great"] },
  { word: "terrify", pos: "verb", syn: ["frighten", "scare", "horrify", "petrify", "alarm"], ant: ["calm", "reassure", "comfort"] },
  { word: "thankful", pos: "adj", syn: ["grateful", "appreciative", "indebted", "obliged", "relieved"], ant: ["ungrateful", "thankless"] },
  { word: "thick", pos: "adj", syn: ["dense", "viscous", "heavy", "solid", "chunky"], ant: ["thin", "thin", "watery"] },
  { word: "thorough", pos: "adj", syn: ["exhaustive", "meticulous", "painstaking", "complete", "comprehensive"], ant: ["superficial", "cursory", "sloppy"] },
  { word: "thoughtful", pos: "adj", syn: ["considerate", "reflective", "pensive", "contemplative", "attentive"], ant: ["thoughtless", "inconsiderate", "rash"] },
  { word: "threaten", pos: "verb", syn: ["intimidate", "menace", "coerce", "bully", "terrorize"], ant: ["protect", "defend", "reassure"] },
  { word: "thrive", pos: "verb", syn: ["prosper", "flourish", "bloom", "boom", "succeed"], ant: ["decline", "wither", "struggle"] },
  { word: "timid", pos: "adj", syn: ["shy", "bashful", "timorous", "diffident", "apprehensive"], ant: ["bold", "confident", "daring"] },
  { word: "tolerate", pos: "verb", syn: ["endure", "bear", "stand", "abide", "suffer"], ant: ["reject", "oppose", "resist"] },
  { word: "tough", pos: "adj", syn: ["strong", "durable", "sturdy", "resilient", "hardy"], ant: ["weak", "tender", "fragile"] },
  { word: "tragic", pos: "adj", syn: ["disastrous", "calamitous", "catastrophic", "devastating", "appalling"], ant: ["fortunate", "auspicious", "happy"] },
  { word: "tranquil", pos: "adj", syn: ["calm", "peaceful", "serene", "placid", "composed"], ant: ["agitated", "turbulent", "stormy"] },
  { word: "transform", pos: "verb", syn: ["convert", "change", "metamorphose", "transmute", "revolutionize"], ant: ["preserve", "maintain", "stagnate"] },
  { word: "transparent", pos: "adj", syn: ["clear", "translucent", "see-through", "crystalline", "limpid"], ant: ["opaque", "cloudy", "obscure"] },
  { word: "tremendous", pos: "adj", syn: ["enormous", "immense", "colossal", "prodigious", "massive"], ant: ["tiny", "minute", "insignificant"] },
  { word: "trivial", pos: "adj", syn: ["unimportant", "insignificant", "minor", "superficial", "petty"], ant: ["important", "significant", "vital"] },
  { word: "trouble", pos: "noun", syn: ["difficulty", "worry", "distress", "bother", "hassle"], ant: ["peace", "ease", "calm"] },
  { word: "true", pos: "adj", syn: ["real", "genuine", "accurate", "authentic", "factual"], ant: ["false", "fake", "untrue"] },
  { word: "trust", pos: "noun", syn: ["confidence", "faith", "belief", "reliance", "credence"], ant: ["distrust", "doubt", "suspicion"] },
  { word: "turbulent", pos: "adj", syn: ["chaotic", "stormy", "volatile", "unstable", "tempestuous"], ant: ["calm", "peaceful", "stable"] },
  { word: "ugly", pos: "adj", syn: ["hideous", "unsightly", "grotesque", "repulsive", "unattractive"], ant: ["beautiful", "gorgeous", "lovely"] },
  { word: "ultimate", pos: "adj", syn: ["final", "definitive", "paramount", "supreme", "utmost"], ant: ["interim", "preliminary", "initial"] },
  { word: "unanimous", pos: "adj", syn: ["united", "consensual", "harmonious", "agreeing", "solid"], ant: ["divided", "disagreeing", "split"] },
  { word: "unbiased", pos: "adj", syn: ["impartial", "unprejudiced", "fair", "neutral", "objective"], ant: ["biased", "partial", "subjective"] },
  { word: "uncertain", pos: "adj", syn: ["unsure", "doubtful", "ambiguous", "unclear", "indefinite"], ant: ["certain", "sure", "definite"] },
  { word: "uncommon", pos: "adj", syn: ["rare", "unusual", "scant", "infrequent", "extraordinary"], ant: ["common", "ordinary", "prevalent"] },
  { word: "understand", pos: "verb", syn: ["comprehend", "grasp", "apprehend", "fathom", "perceive"], ant: ["misunderstand", "confuse", "miss"] },
  { word: "unexpected", pos: "adj", syn: ["unforeseen", "surprising", "unanticipated", "unpredicted", "sudden"], ant: ["expected", "predictable", "routine"] },
  { word: "unfair", pos: "adj", syn: ["unjust", "inequitable", "biased", "discriminatory", "partial"], ant: ["fair", "just", "impartial"] },
  { word: "unique", pos: "adj", syn: ["distinctive", "singular", "unparalleled", "incomparable", "unmatched"], ant: ["common", "ordinary", "generic"] },
  { word: "unite", pos: "verb", syn: ["merge", "combine", "join", "fuse", "amalgamate"], ant: ["divide", "separate", "split"] },
  { word: "universal", pos: "adj", syn: ["global", "comprehensive", "all-encompassing", "general", "worldwide"], ant: ["local", "specific", "limited"] },
  { word: "unpleasant", pos: "adj", syn: ["disagreeable", "distasteful", "offensive", "objectionable", "nasty"], ant: ["pleasant", "agreeable", "nice"] },
  { word: "unusual", pos: "adj", syn: ["uncommon", "rare", "extraordinary", "exceptional", "unique"], ant: ["usual", "ordinary", "common"] },
  { word: "uphold", pos: "verb", syn: ["support", "maintain", "defend", "sustain", "preserve"], ant: ["oppose", "subvert", "undermine"] },
  { word: "upright", pos: "adj", syn: ["honest", "moral", "righteous", "virtuous", "ethical"], ant: ["corrupt", "dishonest", "unprincipled"] },
  { word: "urgent", pos: "adj", syn: ["pressing", "critical", "imperative", "essential", "immediate"], ant: ["unimportant", "non-urgent", "optional"] },
  { word: "useless", pos: "adj", syn: ["futile", "pointless", "ineffective", "unproductive", "vain"], ant: ["useful", "effective", "helpful"] },
  { word: "vacant", pos: "adj", syn: ["empty", "unoccupied", "deserted", "bare", "blank"], ant: ["occupied", "full", "crowded"] },
  { word: "vague", pos: "adj", syn: ["ambiguous", "unclear", "indistinct", "hazy", "obscure"], ant: ["clear", "definite", "distinct"] },
  { word: "vain", pos: "adj", syn: ["conceited", "arrogant", "proud", "vainglorious", "egotistical"], ant: ["humble", "modest", "selfless"] },
  { word: "valid", pos: "adj", syn: ["legitimate", "acceptable", "authoritative", "sound", "binding"], ant: ["invalid", "void", "illegitimate"] },
  { word: "valuable", pos: "adj", syn: ["precious", "costly", "priceless", "invaluable", "esteemed"], ant: ["worthless", "cheap", "valueless"] },
  { word: "vanish", pos: "verb", syn: ["disappear", "fade", "evaporate", "dissolve", "dematerialize"], ant: ["appear", "materialize", "emerge"] },
  { word: "variety", pos: "noun", syn: ["diversity", "assortment", "range", "array", "multitude"], ant: ["uniformity", "sameness", "monotony"] },
  { word: "vast", pos: "adj", syn: ["immense", "boundless", "infinite", "extensive", "limitless"], ant: ["small", "limited", "confined"] },
  { word: "verify", pos: "verb", syn: ["confirm", "validate", "corroborate", "substantiate", "authenticate"], ant: ["disprove", "refute", "invalidate"] },
  { word: "versatile", pos: "adj", syn: ["adaptable", "flexible", "all-round", "resourceful", "multifaceted"], ant: ["limited", "specialized", "narrow"] },
  { word: "vibrant", pos: "adj", syn: ["lively", "energetic", "dynamic", "animated", "vivid"], ant: ["drab", "dull", "lifeless"] },
  { word: "vicious", pos: "adj", syn: ["spiteful", "cruel", "malevolent", "malicious", "savage"], ant: ["kind", "gentle", "benevolent"] },
  { word: "victim", pos: "noun", syn: ["casualty", "sufferer", "prey", "target", "martyr"], ant: ["perpetrator", "aggressor", "attacker"] },
  { word: "victory", pos: "noun", syn: ["triumph", "win", "conquest", "success", "achievement"], ant: ["defeat", "loss", "failure"] },
  { word: "vigorous", pos: "adj", syn: ["energetic", "lively", "robust", "vibrant", "dynamic"], ant: ["weak", "feeble", "lethargic"] },
  { word: "violate", pos: "verb", syn: ["breach", "break", "infringe", "transgress", "defy"], ant: ["obey", "honor", "respect"] },
  { word: "violent", pos: "adj", syn: ["forceful", "brutal", "ferocious", "savage", "tempestuous"], ant: ["gentle", "peaceful", "mild"] },
  { word: "virtual", pos: "adj", syn: ["simulated", "artificial", "digital", "online", "cyber"], ant: ["actual", "physical", "real"] },
  { word: "virtue", pos: "noun", syn: ["goodness", "morality", "righteousness", "integrity", "rectitude"], ant: ["vice", "immorality", "corruption"] },
  { word: "visible", pos: "adj", syn: ["noticeable", "observable", "apparent", "evident", "conspicuous"], ant: ["invisible", "hidden", "concealed"] },
  { word: "vision", pos: "noun", syn: ["sight", "foresight", "perception", "insight", "awareness"], ant: ["blindness", "oblivion"] },
  { word: "vital", pos: "adj", syn: ["essential", "crucial", "critical", "indispensable", "life-giving"], ant: ["trivial", "optional", "unimportant"] },
  { word: "vivid", pos: "adj", syn: ["bright", "vibrant", "intense", "striking", "luminous"], ant: ["dull", "faded", "pale"] },
  { word: "volume", pos: "noun", syn: ["capacity", "quantity", "bulk", "size", "magnitude"], ant: ["lack", "emptiness"] },
  { word: "voluntary", pos: "adj", syn: ["optional", "discretionary", "elective", "chosen", "willing"], ant: ["mandatory", "compulsory", "forced"] },
  { word: "vouch", pos: "verb", syn: ["guarantee", "certify", "attest", "warrant", "confirm"], ant: ["doubt", "discredit", "disavow"] },
  { word: "vulgar", pos: "adj", syn: ["crude", "coarse", "obscene", "offensive", "profane"], ant: ["refined", "polite", "cultured"] },
  { word: "vulnerable", pos: "adj", syn: ["exposed", "susceptible", "defenseless", "helpless", "unprotected"], ant: ["protected", "invulnerable", "secure"] },
  { word: "wander", pos: "verb", syn: ["roam", "stroll", "ramble", "meander", "dawdle"], ant: ["stay", "settle", "remain"] },
  { word: "wane", pos: "verb", syn: ["decline", "diminish", "fade", "ebb", "recede"], ant: ["wax", "increase", "grow"] },
  { word: "wary", pos: "adj", syn: ["cautious", "careful", "leery", "vigilant", "watchful"], ant: ["reckless", "careless", "heedless"] },
  { word: "waste", pos: "verb", syn: ["squander", "fritter", "misuse", "dissipate", "lavish"], ant: ["conserve", "save", "economize"] },
  { word: "wealthy", pos: "adj", syn: ["rich", "affluent", "prosperous", "opulent", "well-to-do"], ant: ["poor", "destitute", "impoverished"] },
  { word: "weary", pos: "adj", syn: ["tired", "fatigued", "exhausted", "drained", "worn out"], ant: ["energetic", "fresh", "vigorous"] },
  { word: "welcome", pos: "verb", syn: ["greet", "receive", "embrace", "usher", "accept"], ant: ["rebuff", "reject", "shun"] },
  { word: "wholesome", pos: "adj", syn: ["healthy", "nutritious", "beneficial", "good", "pure"], ant: ["harmful", "unhealthy", "noxious"] },
  { word: "wicked", pos: "adj", syn: ["evil", "sinful", "malevolent", "corrupt", "immoral"], ant: ["good", "virtuous", "righteous"] },
  { word: "widespread", pos: "adj", syn: ["extensive", "prevalent", "rampant", "global", "rife"], ant: ["limited", "localized", "rare"] },
  { word: "willing", pos: "adj", syn: ["ready", "prepared", "inclined", "disposed", "happy"], ant: ["unwilling", "reluctant", "averse"] },
  { word: "wise", pos: "adj", syn: ["sage", "astute", "prudent", "sensible", "perceptive"], ant: ["foolish", "unwise", "naive"] },
  { word: "withdraw", pos: "verb", syn: ["retract", "remove", "pull out", "extract", "retreat"], ant: ["advance", "proceed", "enter"] },
  { word: "witness", pos: "verb", syn: ["observe", "see", "watch", "view", "testify"], ant: ["overlook", "miss", "ignore"] },
  { word: "wonder", pos: "noun", syn: ["awe", "amazement", "fascination", "astonishment", "curiosity"], ant: ["indifference", "disinterest"] },
  { word: "worry", pos: "verb", syn: ["fret", "fuss", "agonize", "brood", "fear"], ant: ["calm", "relax", "trust"] },
  { word: "worship", pos: "verb", syn: ["adore", "venerate", "revere", "glorify", "exalt"], ant: ["desecrate", "profane", "blaspheme"] },
  { word: "worthless", pos: "adj", syn: ["valueless", "useless", "pointless", "insignificant", "trivial"], ant: ["valuable", "worthwhile", "precious"] },
  { word: "wound", pos: "noun", syn: ["injury", "hurt", "gash", "lesion", "trauma"], ant: ["healing", "cure", "remedy"] },
  { word: "wrath", pos: "noun", syn: ["anger", "fury", "rage", "indignation", "outrage"], ant: ["calm", "forgiveness", "peace"] },
  { word: "wretched", pos: "adj", syn: ["miserable", "pitiful", "pathetic", "misfortunate", "woeful"], ant: ["happy", "fortunate", "blessed"] },
  { word: "yell", pos: "verb", syn: ["shout", "cry", "scream", "howl", "bellow"], ant: ["whisper", "murmur", "mutter"] },
  { word: "yield", pos: "verb", syn: ["submit", "surrender", "capitulate", "succumb", "relinquish"], ant: ["resist", "defy", "withstand"] },
  { word: "youthful", pos: "adj", syn: ["young", "juvenile", "fresh", "vigorous", "spry"], ant: ["aged", "elderly", "decrepit"] },
  { word: "zeal", pos: "noun", syn: ["passion", "enthusiasm", "fervor", "ardor", "eagerness"], ant: ["apathy", "indifference", "lethargy"] },
  { word: "zenith", pos: "noun", syn: ["pinnacle", "summit", "peak", "apex", "acme"], ant: ["nadir", "bottom", "depths"] },
  { word: "zone", pos: "noun", syn: ["area", "region", "district", "sector", "territory"], ant: ["whole", "entirety"] },
];

export const POS_OPTIONS = ["adj", "verb", "noun", "adverb", "preposition"];

export const POS_LABELS = {
  adj: "Adjective", verb: "Verb", noun: "Noun",
  adverb: "Adverb", preposition: "Preposition",
};
