/** Calm audio, open libraries, linked reference warrens, and the kind internet. */
const sites = [
  // ---------------------------------------------------------------------------
  // The Calm Corner
  // ---------------------------------------------------------------------------
  {
    slug: "pixel-thoughts",
    name: "Pixel Thoughts",
    url: "https://www.pixelthoughts.co/",
    category: "calm-corner",
    blurb: "Type what is bothering you, watch it shrink into space",
    description:
      "A sixty-second exercise with one instruction: type the thought that is bothering you into the glowing star at the centre of the screen. The star then drifts away into a field of galaxies while short prompts about perspective fade in and out, taking the sentence with it.",
    whyItsGood:
      "The timing is the whole trick. You cannot rush it, skip it or click anything else, so the only remaining option is to sit still for the full minute.",
    timeToJoy: "one-minute",
    vibes: ["calming", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: "pixel-thought",
    source: "listicle",
  },
  {
    slug: "a-soft-murmur",
    name: "A Soft Murmur",
    url: "https://asoftmurmur.com/",
    category: "calm-corner",
    blurb: "Build your own weather out of ten ambient sliders",
    description:
      "Ten looping ambient sources — rain, thunder, waves, wind, fire, birds, coffee shop and a few more, each with an independent volume slider, so you mix the background you want rather than picking a preset. Mixes can be saved to a link and shared.",
    whyItsGood:
      "The thunder track is on a long irregular loop, so the mix never develops the obvious repeating tell that ruins most rain generators.",
    timeToJoy: "instant",
    vibes: ["calming", "cosy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2012,
    altfAlternative: "soft-murmur",
    source: "listicle",
  },
  {
    slug: "rainy-mood",
    name: "Rainy Mood",
    url: "https://rainymood.com/",
    category: "calm-corner",
    blurb: "Two decades of rain, still the reference recording",
    description:
      "One long rain recording with rolling thunder, running since the earliest days of ambient audio on the web. Controls adjust the rain and the thunder independently, and a sleep timer fades the whole thing out after however many minutes you set.",
    whyItsGood:
      "The loop runs long enough that thunder never lands where your ear has learned to expect it, which is why people still recommend it over newer, glossier rain sites.",
    timeToJoy: "instant",
    vibes: ["calming", "cosy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2004,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "mynoise",
    name: "myNoise",
    url: "https://mynoise.net/",
    category: "calm-corner",
    blurb: "Calibrate the noise to the exact shape of your hearing",
    description:
      "Stéphane Pigeon's library runs to hundreds of soundscapes, each built as a ten-band audio equaliser rather than a single fixed file. Push a band up and that frequency range gets louder, so a rain generator can be steered towards its low rumble or its high hiss depending on what you are trying to mask.",
    whyItsGood:
      "A calibration page plays each frequency band in turn and asks you to level it by ear, then applies your personal hearing curve to every generator on the site.",
    timeToJoy: "one-minute",
    vibes: ["calming", "useful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: "soft-murmur",
    source: "altf-curated",
  },
  {
    slug: "noisli",
    name: "Noisli",
    url: "https://www.noisli.com/",
    category: "calm-corner",
    blurb: "Colour-shifting background noise with a plain writing pad",
    description:
      "Sound tiles cover rain, wind, leaves, fire, a coffee shop and several flavours of white noise, all combinable and saveable as a named combo. The background colour drifts slowly through soft tones while the audio plays, and a distraction-free text editor is built into the same page.",
    whyItsGood:
      "That slowly cycling background colour does more work than it should. After a few minutes the screen stops reading as a screen and starts reading as a room.",
    timeToJoy: "instant",
    vibes: ["calming", "cosy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: "soft-murmur",
    source: "altf-curated",
  },
  {
    slug: "defonic",
    name: "Defonic",
    url: "https://defonic.com/",
    category: "calm-corner",
    blurb: "Two dozen ambience layers, mixed on one dark screen",
    description:
      "Around two dozen loops sit as icons on a dark grid: waves, rain, forest, café, train, library, fireplace and a few stranger ones such as spaceship hum. Clicking an icon adds it to the mix at an adjustable level, and most people settle on three or four running together.",
    whyItsGood:
      "The train carriage and library loops are unusually well recorded, and layering the two produces a convincing studying-on-a-long-journey room that no preset app offers.",
    timeToJoy: "instant",
    vibes: ["calming", "cosy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: "soft-murmur",
    source: "altf-curated",
  },
  {
    slug: "moodist",
    name: "Moodist",
    url: "https://moodist.mvze.net/",
    category: "calm-corner",
    blurb: "Open-source ambience with no ads and no upsell anywhere",
    description:
      "An open-source sound mixer grouped into nature, urban, transport, places, things and noise, with per-sound volume and a set of shareable presets. A pomodoro timer, a breathing exercise and a simple notepad sit next to the mixer for people who use ambience to get work done.",
    whyItsGood:
      "Nothing is gated. Every sound, preset and timer works on first load with no banner asking you to upgrade, which has become genuinely rare in this genre.",
    timeToJoy: "instant",
    vibes: ["calming", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2023,
    altfAlternative: "soft-murmur",
    source: "altf-curated",
  },
  {
    slug: "ambient-mixer",
    name: "Ambient Mixer",
    url: "https://www.ambient-mixer.com/",
    category: "calm-corner",
    blurb: "Fan-made soundscapes of fictional rooms you can sit in",
    description:
      "Users build eight-channel ambient scenes and publish them, which has produced thousands of oddly specific rooms: a wizarding school common room, a Victorian study, a starship corridor, a tavern during a downpour. Each channel carries its own volume and repeat interval, so you can retune somebody else's scene.",
    whyItsGood:
      "The per-channel repeat setting is what sells it. A creaking floorboard set to fire every four minutes stops a room sounding like a loop and starts it sounding inhabited.",
    timeToJoy: "coffee-break",
    vibes: ["cosy", "calming"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2010,
    altfAlternative: "soft-murmur",
    source: "altf-curated",
  },
  {
    slug: "rainy-cafe",
    name: "Rainy Cafe",
    url: "https://rainycafe.com/",
    category: "calm-corner",
    blurb: "Two sliders, one café, endless rain outside the window",
    description:
      "Deliberately tiny: a rain track and a café track, each with its own volume slider, and nothing else on the page at all. Turn the café down and the rain up for a quiet flat during a downpour, or reverse the two for a busy room on a wet afternoon.",
    whyItsGood:
      "Restraint is the feature. Two sliders means no decisions to make, which matters when the reason you opened an ambience site was that you could not concentrate.",
    timeToJoy: "instant",
    vibes: ["calming", "cosy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: "soft-murmur",
    source: "altf-curated",
  },
  {
    slug: "coffitivity",
    name: "Coffitivity",
    url: "https://coffitivity.com/",
    category: "calm-corner",
    blurb: "The specific hum of a café, minus the queue and the cost",
    description:
      "Three recorded café rooms play as continuous background: a morning murmur, a lunchtime lull and a university undertone, each with a volume dial and nothing else to configure. Every recording sits at the level of speech you cannot quite make out.",
    whyItsGood:
      "It was built around research suggesting moderate ambient chatter helps creative work, and the recordings are pitched at precisely that level rather than at busy-restaurant volume.",
    timeToJoy: "instant",
    vibes: ["calming", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: "soft-murmur",
    source: "altf-curated",
  },
  {
    slug: "i-miss-my-cafe",
    name: "I Miss My Cafe",
    url: "https://imissmycafe.com/",
    category: "calm-corner",
    blurb: "Rebuild your old coffee shop from its component noises",
    description:
      "Made in 2020 for people missing the room they used to work in, this splits a café into separate layers: chatter, the espresso machine, cups and cutlery, street noise outside, and rain. Each gets a slider, and the site pairs the mix with a suggested playlist to run underneath it.",
    whyItsGood:
      "Putting the espresso machine on its own channel is the detail that makes it land, because that hiss and clunk is what a memory of a café actually hangs on.",
    timeToJoy: "instant",
    vibes: ["cosy", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2020,
    altfAlternative: "soft-murmur",
    source: "altf-curated",
  },
  {
    slug: "purrli",
    name: "Purrli",
    url: "https://purrli.com/",
    category: "calm-corner",
    blurb: "A cat purr you can tune, built by a signal-processing PhD",
    description:
      "Not a recording but a synthesiser modelled on real purrs, with sliders moving the sound between sleepy and lively, close and distant, steady and irregular. Occasional meows can be dialled in or out, and a timer fades the cat away after however long you need it.",
    whyItsGood:
      "Because the purr is generated rather than looped, it breaks off and restarts at uneven intervals the way a real cat does, which is the thing recordings never manage.",
    timeToJoy: "instant",
    vibes: ["cosy", "calming"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "tree-fm",
    name: "tree.fm",
    url: "https://www.tree.fm/",
    category: "calm-corner",
    blurb: "Press one button, hear a forest somewhere else on Earth",
    description:
      "One button drops you into a field recording made in a forest somewhere in the world, with the location, the contributor and a photograph shown while it plays. Recordings come from the crowdsourced Sounds of the Forest project and the aporee sound map, and another press moves you somewhere new.",
    whyItsGood:
      "Half the pleasure is the caption. You realise you are listening to insects in a Sri Lankan rainforest because somebody stood in it and pressed record.",
    timeToJoy: "instant",
    vibes: ["calming", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2020,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "earth-fm",
    name: "Earth.fm",
    url: "https://earth.fm/",
    category: "calm-corner",
    blurb: "Twelve hundred nature recordings, kept free by a charity",
    description:
      "A non-profit archive of more than 1,200 natural soundscapes, captured by professional field recordists in places most people will never stand in. Entries name the recordist and the habitat, often with a note on what you are hearing, and long unbroken tracks are the norm rather than short loops.",
    whyItsGood:
      "These are proper field recordings rather than stock loops, so you get the awkward realism of a bird flying off mid-song or wind arriving in the canopy.",
    timeToJoy: "coffee-break",
    vibes: ["calming", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2021,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "sounds-of-the-forest",
    name: "Sounds of the Forest",
    url: "https://timberfestival.org.uk/soundsoftheforest-soundmap/",
    category: "calm-corner",
    blurb: "A world map where every pin is a woodland recording",
    description:
      "Timber Festival asked people to record a minute of their local woodland and send it in, then pinned every submission to a world map. Clicking a pin plays that minute, so you can travel from a Derbyshire copse to a Finnish pine stand by dragging across the map.",
    whyItsGood:
      "Recordings are unpolished phone captures, so you occasionally get a dog, a distant motorway or the recordist breathing, which turns the map into a record of people as much as places.",
    timeToJoy: "coffee-break",
    vibes: ["calming", "wholesome"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2020,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "window-swap",
    name: "WindowSwap",
    url: "https://www.window-swap.com/",
    category: "calm-corner",
    blurb: "Look out of a stranger's window for as long as you like",
    description:
      "Someone in Osaka or Tromsø points a camera at their window and records ten minutes of whatever happens outside it. Press a button and one of those views fills the screen, captioned only with a first name and a city, then press again for the next one.",
    whyItsGood:
      "Nothing happens in most of them, and that is the appeal: rain on a balcony, a cat crossing a courtyard, laundry moving in the wind for ten uninterrupted minutes.",
    timeToJoy: "instant",
    vibes: ["calming", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2020,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "one-minute-park",
    name: "One Minute Park",
    url: "https://oneminutepark.tv/",
    category: "calm-corner",
    blurb: "Sixty seconds in a park, filmed by whoever was there",
    description:
      "The project aims to fill all 1,440 minutes of a day with one-minute videos of parks, each filmed and submitted by a visitor. What you get is a single unedited minute of a bench, a path or a lawn somewhere in the world, labelled with the park and the time of day it stands for.",
    whyItsGood:
      "Every clip runs exactly one minute with no cut, so you watch a small green place at ordinary speed instead of the sped-up, music-backed version social video would hand you.",
    timeToJoy: "one-minute",
    vibes: ["calming", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2021,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "exhaler",
    name: "eXHALeR",
    url: "https://xhalr.com/",
    category: "calm-corner",
    blurb: "A breathing pacer that gets out of the way immediately",
    description:
      "An expanding and contracting shape paces your breath through inhale, hold, exhale and hold, with named patterns including square breathing and ujjayi. Each phase length can be set by hand, and a full-screen dark mode strips the page back to the moving shape and nothing else.",
    whyItsGood:
      "Setting the four phase timings individually lets you copy whatever pattern a therapist or a class gave you, rather than accepting the single ratio most breathing apps hard-code.",
    timeToJoy: "one-minute",
    vibes: ["calming", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: null,
    altfAlternative: null,
    source: "altf-curated",
  },

  // ---------------------------------------------------------------------------
  // Deep Archives
  // ---------------------------------------------------------------------------
  {
    slug: "nautilus",
    name: "Nautilus",
    url: "https://nautil.us/",
    category: "deep-archives",
    blurb: "Science writing that reads like a long magazine essay",
    description:
      "A science magazine that runs one theme at a time and commissions essays rather than news, covering physics, biology, philosophy of mind and the places where they overlap. Pieces are long, illustrated, and written by working scientists as often as by journalists.",
    whyItsGood:
      "Themed issues mean the biology piece and the philosophy piece are quietly arguing with each other, so reading a whole issue leaves you with a question rather than a fact.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "world-history-encyclopedia",
    name: "World History Encyclopedia",
    url: "https://www.worldhistory.org/",
    category: "deep-archives",
    blurb: "Peer-reviewed world history, free and properly illustrated",
    description:
      "Founded as the Ancient History Encyclopedia and renamed once its coverage grew well past antiquity, this non-profit publishes fact-checked articles alongside close to twenty thousand illustrations, plus videos, maps, timelines and 3D models. Historians write the entries and reviewers check them before publication.",
    whyItsGood:
      "Articles close with their sources and the name of the reviewer, so the site holds up as a citation in a way that a general-purpose wiki does not.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2009,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "project-gutenberg",
    name: "Project Gutenberg",
    url: "https://www.gutenberg.org/",
    category: "deep-archives",
    blurb: "The first digital library, and still the largest free one",
    description:
      "Volunteers have been typing and proofreading out-of-copyright books since 1971, which makes this the oldest digital library in existence. Seventy thousand-odd titles download as plain text, EPUB or Kindle files with no payment, registration or reader app standing in the way.",
    whyItsGood:
      "The plain-text editions are the quiet advantage: they open in anything, survive any device change, and will still be readable long after whichever ereader you own stops being supported.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 1971,
    altfAlternative: "wattpad",
    source: "altf-curated",
  },
  {
    slug: "standard-ebooks",
    name: "Standard Ebooks",
    url: "https://standardebooks.org/",
    category: "deep-archives",
    blurb: "Public-domain classics, typeset like they cost money",
    description:
      "Volunteers take public-domain texts, mostly from Project Gutenberg, then proofread them against the original scans, correct the punctuation, apply a full style manual and commission a cover from public-domain art. The catalogue is far smaller than Gutenberg's and produced to a much higher standard.",
    whyItsGood:
      "Popup footnotes, correctly nested quotation marks and real typographic dashes make a nineteenth-century novel read on a phone the way it read in print.",
    timeToJoy: "coffee-break",
    vibes: ["beautiful", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: "wattpad",
    source: "altf-curated",
  },
  {
    slug: "public-domain-review",
    name: "The Public Domain Review",
    url: "https://publicdomainreview.org/",
    category: "deep-archives",
    blurb: "The strangest things that ever fell out of copyright",
    description:
      "An editorial project that goes digging through open archives and returns with essays on eighteenth-century colour theory, medieval illustrations of elephants drawn by people who had never seen one, or early photographs staged to look like ghosts. Every image it publishes is free to reuse.",
    whyItsGood:
      "Essays are properly researched but the selection is unashamedly odd, so within forty seconds you are learning the history of something you did not know existed.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "weird", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "open-library",
    name: "Open Library",
    url: "https://openlibrary.org/",
    category: "deep-archives",
    blurb: "One catalogue page for every book ever published",
    description:
      "The stated aim is a web page per book, which at present means tens of millions of records with covers, editions, subjects and author pages linked to one another. A large slice can also be borrowed as a scanned copy, which needs a free account, though browsing the catalogue needs nothing at all.",
    whyItsGood:
      "Following a subject heading is the move here, because it surfaces the four obscure books published on your niche in the 1950s that no shop would ever show you.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2006,
    altfAlternative: "wattpad",
    source: "altf-curated",
  },
  {
    slug: "internet-archive-texts",
    name: "Internet Archive Texts",
    url: "https://archive.org/details/texts",
    category: "deep-archives",
    blurb: "Millions of scanned books, magazines and old manuals",
    description:
      "The text side of the Internet Archive holds scanned books, periodicals, government reports, zines, technical manuals and school textbooks, searchable by their full contents rather than by title alone. A great many items were digitised straight from library shelves and exist nowhere else online.",
    whyItsGood:
      "Full-text search across millions of scans means you can locate a phrase buried inside a 1937 trade catalogue, which is how a ten-minute lookup becomes an afternoon.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "nostalgic"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2005,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "jstor-open-and-free",
    name: "JSTOR Open and Free",
    url: "https://about.jstor.org/oa-and-free/",
    category: "deep-archives",
    blurb: "The open half of the library everyone else pays for",
    description:
      "JSTOR's open collections take in thousands of open-access journals and ebooks, early journal content published more than ninety-five years ago, research reports from well over a hundred think tanks, and close to a million images from museums and archives. A free personal account adds another hundred articles every thirty days.",
    whyItsGood:
      "The early journal content is the sleeper: century-old papers in which scientists argue with each other at length and often in magnificently bad-tempered prose.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 1995,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "arxiv",
    name: "arXiv",
    url: "https://arxiv.org/",
    category: "deep-archives",
    blurb: "Read tomorrow's physics papers before they're published",
    description:
      "Researchers in physics, mathematics, computer science, quantitative biology and economics post papers here before, or instead of, formal journal publication. Everything stays free permanently, and the daily listings let you watch a field move in close to real time.",
    whyItsGood:
      "Papers routinely appear months ahead of any journal version, so the arXiv listing is the moment a result genuinely enters the world.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 1991,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "aeon",
    name: "Aeon",
    url: "https://aeon.co/",
    category: "deep-archives",
    blurb: "One long essay a day, on the questions without answers",
    description:
      "Aeon commissions essays from philosophers, scientists and historians on consciousness, ethics, ecology and how a person ought to live, publishing a new one most days. Companion sites cover psychology and short documentary film, and none of it sits behind a paywall.",
    whyItsGood:
      "Essays run to several thousand words and are edited hard, so an argument develops properly instead of stopping where a magazine would run out of column inches.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "calming"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2012,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "longreads",
    name: "Longreads",
    url: "https://longreads.com/",
    category: "deep-archives",
    blurb: "Curated long-form journalism, sorted by how long it takes",
    description:
      "Part original commissioning and part editorial pointer to the best long-form journalism published elsewhere, with an estimated reading time attached to every recommendation. Coverage runs from investigative reporting to personal essays and criticism, updated daily and free.",
    whyItsGood:
      "That reading-time label sounds trivial until you use it, because matching a thirty-minute story to a thirty-minute train journey beats guessing every time.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2009,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "the-marginalian",
    name: "The Marginalian",
    url: "https://www.themarginalian.org/",
    category: "deep-archives",
    blurb: "Two decades of one person reading and taking notes",
    description:
      "Maria Popova has written about books, science, art and letters here since 2006, back when it was called Brain Pickings. Each piece braids long quotations from an old book together with her own commentary, and the archive now holds thousands of essays sorted by author and by theme.",
    whyItsGood:
      "The quoting is generous enough that one essay works as a full introduction to a writer you would otherwise never have opened.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "calming", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2006,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "biodiversity-heritage-library",
    name: "Biodiversity Heritage Library",
    url: "https://www.biodiversitylibrary.org/",
    category: "deep-archives",
    blurb: "Every natural history book, scanned by the world's museums",
    description:
      "A consortium of natural history libraries has scanned centuries of taxonomic literature, field notebooks and illustrated volumes of flora and fauna into a single searchable archive. Millions of pages sit open, including hand-coloured plates from books far too fragile to be handled.",
    whyItsGood:
      "Their released illustration sets let you page through a Victorian monograph on hummingbirds plate by plate, at a resolution its original owner could never have seen.",
    timeToJoy: "rabbit-hole",
    vibes: ["beautiful", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2006,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "david-rumsey-map-collection",
    name: "David Rumsey Map Collection",
    url: "https://www.davidrumsey.com/",
    category: "deep-archives",
    blurb: "A hundred thousand old maps, zoomable to the street",
    description:
      "One collector's lifetime of historical maps, atlases, globes and city views, digitised at very high resolution and free to browse. Built-in tools lay a nineteenth-century map over a modern one, spin a scanned globe, or set two sheets of the same city decades apart side by side.",
    whyItsGood:
      "The overlay tool is the reason to visit. Dropping an 1870 survey onto present-day satellite imagery shows exactly which streets survived and which were built straight over.",
    timeToJoy: "rabbit-hole",
    vibes: ["beautiful", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 1996,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "rijksstudio",
    name: "Rijksstudio",
    url: "https://www.rijksmuseum.nl/en/rijksstudio",
    category: "deep-archives",
    blurb: "Download a Vermeer at a resolution you can actually print",
    description:
      "The Rijksmuseum put its collection online at very high resolution and released the out-of-copyright works for anyone to download, crop and reuse without asking permission. Rijksstudio lets you assemble your own sets from Rembrandt etchings, Delftware, dolls' houses and ship models.",
    whyItsGood:
      "Zooming into The Night Watch until individual cracks in the varnish are visible is something the actual gallery, with its crowd and its rope, will never let you do.",
    timeToJoy: "rabbit-hole",
    vibes: ["beautiful", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2012,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "smithsonian-open-access",
    name: "Smithsonian Open Access",
    url: "https://www.si.edu/openaccess",
    category: "deep-archives",
    blurb: "Millions of museum objects, released with no restrictions",
    description:
      "The Smithsonian released millions of images and 3D scans from its museums, research centres and the National Zoo into the public domain, covering dinosaur bones, Apollo hardware, insect specimens and portraiture alike. All of it is searchable in one place and usable without permission.",
    whyItsGood:
      "The 3D scans are the surprise: an Apollo command module or a whale skull can be rotated in the browser and the mesh downloaded if you fancy printing it.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2020,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "rekhta",
    name: "Rekhta",
    url: "https://www.rekhta.org/",
    category: "deep-archives",
    blurb: "The largest Urdu poetry archive, readable in three scripts",
    description:
      "Tens of thousands of ghazals, nazms and couplets by classical and contemporary Urdu poets, each readable in Nastaliq, Devanagari or Roman transliteration at the tap of a toggle. Poet pages gather biography, audio recitations and video performances alongside the written text.",
    whyItsGood:
      "That script toggle quietly solves a real problem, letting a reader who knows the language by ear but not the alphabet read Ghalib without a translation in the way.",
    timeToJoy: "rabbit-hole",
    vibes: ["beautiful", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: "bharat-virasat",
    source: "altf-curated",
  },
  {
    slug: "indian-culture-portal",
    name: "Indian Culture Portal",
    url: "https://indianculture.gov.in/",
    category: "deep-archives",
    blurb: "India's national collections, digitised into one place",
    description:
      "Run by the Ministry of Culture, this pulls holdings from national museums, archives and libraries into a single site: rare books, manuscripts, photograph archives, textiles, musical instruments, historic gazetteers and regional recipes. Material is grouped by theme and by state rather than by which institution happens to hold it.",
    whyItsGood:
      "Organising objects by region instead of by owning institution means the textiles, food and architecture of one state can be followed in a single sitting.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: "bharat-virasat",
    source: "altf-curated",
  },

  // ---------------------------------------------------------------------------
  // Wiki Dives
  // ---------------------------------------------------------------------------
  {
    slug: "wikipedia-random-article",
    name: "Wikipedia: Random Article",
    url: "https://en.wikipedia.org/wiki/Special:Random",
    category: "wiki-dives",
    blurb: "One click, one article, chosen from millions at random",
    description:
      "Wikipedia's own random page link drops you into any article in the encyclopaedia with no filtering applied, which is why it lands so often on a Romanian village, a species of beetle or a defunct Scottish football club. Refresh and it hands you another, indefinitely.",
    whyItsGood:
      "The randomness is genuinely uniform, so most results are obscure stubs and stumbling onto a well-written article about something you had never heard of feels earned.",
    timeToJoy: "instant",
    vibes: ["brainy", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2001,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "wikipedia-unusual-articles",
    name: "Wikipedia: Unusual Articles",
    url: "https://en.wikipedia.org/wiki/Wikipedia:Unusual_articles",
    category: "wiki-dives",
    blurb: "Wikipedia's own index of its most peculiar entries",
    description:
      "Editors maintain a curated list of the encyclopaedia's oddest articles, sorted into places, people, events, food, language and mathematics. To be included an entry has to be genuinely unusual rather than merely obscure, and the list still runs to several hundred of them.",
    whyItsGood:
      "Because Wikipedians nominate and then argue over each inclusion, the hit rate is far better than random browsing and almost every link pays off.",
    timeToJoy: "rabbit-hole",
    vibes: ["weird", "funny", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2003,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "tv-tropes",
    name: "TV Tropes",
    url: "https://tvtropes.org/",
    category: "wiki-dives",
    blurb: "Names for the storytelling tricks you noticed but never named",
    description:
      "A wiki cataloguing the recurring devices of fiction, giving each one a name and a page listing every film, book, game and advert that has used it. Pages link out to other tropes several times per paragraph, and individual works get their own pages listing what they contain.",
    whyItsGood:
      "Once you have read the page for a device you half-noticed for years you cannot unsee it, and the site knows this well enough to warn you about the time sink itself.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "funny"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2004,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "atlas-obscura",
    name: "Atlas Obscura",
    url: "https://www.atlasobscura.com/",
    category: "wiki-dives",
    blurb: "A guidebook to the places no guidebook mentions",
    description:
      "A crowd-built atlas of unusual places: a museum of failed products, an underground pigeon-post station, a tree grafted to bear forty kinds of fruit. Every entry carries photographs, directions, notes on access, and a short piece explaining how on earth the place came to exist.",
    whyItsGood:
      "Filtering by what is near you turns up two or three genuinely strange things within an hour of wherever you live, and they are usually still open.",
    timeToJoy: "rabbit-hole",
    vibes: ["weird", "beautiful", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2009,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "know-your-meme",
    name: "Know Your Meme",
    url: "https://knowyourmeme.com/",
    category: "wiki-dives",
    blurb: "The footnoted origin story of every image you have seen",
    description:
      "A research wiki that traces internet phenomena back to their first appearance, recording dates, original posts, spread timelines and examples. Entries are reviewed and marked either confirmed or still under research, which makes the site a reference rather than a joke repository.",
    whyItsGood:
      "Entries cite the original forum post and its exact date, so you can watch a joke travel from one obscure thread to a national advertising campaign in about four years.",
    timeToJoy: "rabbit-hole",
    vibes: ["funny", "nostalgic", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2007,
    altfAlternative: "kym",
    source: "altf-curated",
  },
  {
    slug: "scp-foundation",
    name: "SCP Foundation",
    url: "https://scp-wiki.wikidot.com/",
    category: "wiki-dives",
    blurb: "A fictional agency's files on things that should not exist",
    description:
      "Thousands of collaboratively written entries, each formatted as a clinical containment report on an anomalous object, creature or location, complete with redactions and handling procedures. Anyone can submit, entries are voted on, and a loose shared canon has grown out of the cross-references.",
    whyItsGood:
      "The deadpan bureaucratic format does all the work, since the horror arrives through a blacked-out line in a safety procedure rather than through anything described outright.",
    timeToJoy: "rabbit-hole",
    vibes: ["unsettling", "weird", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2008,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "the-wiki-game",
    name: "The Wiki Game",
    url: "https://www.thewikigame.com/",
    category: "wiki-dives",
    blurb: "Race strangers from one Wikipedia article to another",
    description:
      "You are given a starting article and a target, then have to reach the target using only the links inside the pages themselves. Rounds run against other players in real time with everyone's current article on display, and several modes change the constraints, such as fewest clicks or a hard time limit.",
    whyItsGood:
      "Watching a rival's position update live changes how you play, because seeing someone land on a country page reveals a route you had not thought of.",
    timeToJoy: "coffee-break",
    vibes: ["competitive", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2008,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "six-degrees-of-wikipedia",
    name: "Six Degrees of Wikipedia",
    url: "https://www.sixdegreesofwikipedia.com/",
    category: "wiki-dives",
    blurb: "Find the shortest link path between any two articles",
    description:
      "Enter two Wikipedia pages and it computes every shortest chain of links running between them, then draws the result as a graph you can drag around. Most pairs turn out to be three or four hops apart, however unrelated the two subjects look on paper.",
    whyItsGood:
      "Seeing the graph makes it obvious which hub articles the encyclopaedia routes everything through, and those hubs are rarely the ones you would have guessed.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "mesmerising"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "wikivoyage",
    name: "Wikivoyage",
    url: "https://en.wikivoyage.org/",
    category: "wiki-dives",
    blurb: "A travel guide anyone can edit, with no paid listings",
    description:
      "Volunteer-written travel guides covering countries, cities, regions and themed itineraries, forked from an earlier commercial site so that the content stays free and advert-free. Articles carry practical detail on transport, food and safety alongside advice on where residents actually go.",
    whyItsGood:
      "With no hotel paying for placement, the recommendations are unusually blunt about which famous sights are not worth the entry fee.",
    timeToJoy: "rabbit-hole",
    vibes: ["useful", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2012,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "wookieepedia",
    name: "Wookieepedia",
    url: "https://starwars.fandom.com/",
    category: "wiki-dives",
    blurb: "A couple of hundred thousand articles about one film series",
    description:
      "The Star Wars wiki documents every character, planet, ship, battle and background extra across the films, series, novels, comics and games, citing the source that established each fact. Articles carefully separate current canon from older material that has since been superseded.",
    whyItsGood:
      "Pages exist for characters who appear on screen for under a second, sourced to a novel published twenty years later, which is completeness as a form of devotion.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2005,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "memory-alpha",
    name: "Memory Alpha",
    url: "https://memory-alpha.fandom.com/",
    category: "wiki-dives",
    blurb: "Star Trek documented as though it were actual history",
    description:
      "Every Star Trek episode, character, species and starship is covered here from an in-universe perspective so that entries read as historical record rather than as television criticism. Production notes and continuity errors are kept in clearly separate sections at the foot of each page.",
    whyItsGood:
      "That in-universe voice is maintained so rigorously that a page about a shuttlecraft reads like a Federation registry entry, which makes the cross-linking pleasantly disorienting.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2003,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "lost-media-wiki",
    name: "The Lost Media Wiki",
    url: "https://lostmediawiki.com/",
    category: "wiki-dives",
    blurb: "A register of films, tapes and games nobody can find",
    description:
      "Volunteers document media known to have existed but currently unlocatable: wiped television episodes, unreleased films, cancelled games, deleted internet videos. Each article records the evidence that it existed, everything already searched, and whether anything has since resurfaced.",
    whyItsGood:
      "Articles get reclassified as found when a search finally succeeds, so the wiki doubles as a running scoreboard for a slow, distributed and entirely voluntary hunt.",
    timeToJoy: "rabbit-hole",
    vibes: ["nostalgic", "unsettling", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2012,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "everything2",
    name: "Everything2",
    url: "https://everything2.com/",
    category: "wiki-dives",
    blurb: "A pre-Wikipedia wiki where the writing is the point",
    description:
      "Started in 1999, this collects user-written pieces under shared titles, so a single heading might hold a definition, a poem, a memoir and an argument, each by a different person. Nothing gets merged into one neutral summary, which is precisely the opposite of how an encyclopaedia works.",
    whyItsGood:
      "Reading four contradictory takes stacked under one title is a format the modern web abandoned, and the best nodes read closer to essays than to reference entries.",
    timeToJoy: "rabbit-hole",
    vibes: ["nostalgic", "weird", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 1999,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "stanford-encyclopedia-of-philosophy",
    name: "Stanford Encyclopedia of Philosophy",
    url: "https://plato.stanford.edu/",
    category: "wiki-dives",
    blurb: "Every entry written and updated by an actual specialist",
    description:
      "Each article is commissioned from an academic working in that area, refereed by an editorial board, and revised as the field moves rather than left to rot. Coverage runs from ancient logic through to contemporary ethics of technology, and every entry is free with no advertising anywhere.",
    whyItsGood:
      "Entries are dated and versioned, so you can see when a specialist last revisited the argument, which no other free reference work bothers to tell you.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 1995,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "etymonline",
    name: "Online Etymology Dictionary",
    url: "https://www.etymonline.com/",
    category: "wiki-dives",
    blurb: "Where words came from, traced as far back as evidence goes",
    description:
      "Douglas Harper's etymology dictionary gives the recorded history of English words: the date each was first attested, the languages it travelled through, and how its meaning shifted along the way. Entries link straight to their root words, which is where the afternoon goes.",
    whyItsGood:
      "Notes on meaning drift are the good part, showing how nice meant foolish, then precise, then pleasant, with a date attached to every turn.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2001,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "behind-the-name",
    name: "Behind the Name",
    url: "https://www.behindthename.com/",
    category: "wiki-dives",
    blurb: "The etymology and history of first names, worldwide",
    description:
      "A reference for given names covering origin, meaning, the language each came from and how its popularity has moved by country and by decade. Entries link between related forms, so one name leads you to its Latin root, its Polish variant and every saint who ever carried it.",
    whyItsGood:
      "Popularity charts reaching back over a century let you date a name to a decade, which explains why every third woman born in a particular year shares one.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 1996,
    altfAlternative: "ancestory",
    source: "altf-curated",
  },
  {
    slug: "snopes",
    name: "Snopes",
    url: "https://www.snopes.com/",
    category: "wiki-dives",
    blurb: "The claim, the evidence, and where the story really began",
    description:
      "Running since the mid-1990s, Snopes investigates rumours, viral claims and urban legends, publishing a rating alongside its sourcing and a history of how the story spread. An older folklore archive covers legends that were circulating for decades before social media existed.",
    whyItsGood:
      "The origin tracing is more interesting than the verdict, because most legends turn out to be considerably older than whichever version is currently going round.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 1994,
    altfAlternative: "fact-net",
    source: "altf-curated",
  },
  {
    slug: "sahapedia",
    name: "Sahapedia",
    url: "https://www.sahapedia.org/",
    category: "wiki-dives",
    blurb: "India's arts and heritage, mapped across ten domains",
    description:
      "Indian arts, culture and heritage set out as a non-profit open encyclopaedia, organised into ten domains including performing arts, knowledge traditions, built spaces and rituals. Formats reach well past text, taking in photo essays, recorded interviews, timelines, virtual tours and an interactive map.",
    whyItsGood:
      "Articles are commissioned from practitioners and scholars inside the specific tradition, so a piece on a regional puppetry form comes from someone who has watched the puppeteers work.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: "bharat-virasat",
    source: "altf-curated",
  },

  // ---------------------------------------------------------------------------
  // The Wholesome Web
  // ---------------------------------------------------------------------------
  {
    slug: "open-puppies",
    name: "Open Puppies",
    url: "https://openpuppies.com/",
    category: "wholesome-web",
    blurb: "One puppy, one button, no obvious way to stop",
    description:
      "Full-screen looping video of a puppy, with a single button that swaps it for a different puppy. There is no feed, no comment section, no captions and no sign-up, which leaves precisely one thing to do on the page and one reason to stay on it.",
    whyItsGood:
      "Clips are silent and loop seamlessly, so the whole thing works with the sound off in a meeting, which is presumably not what the internet needed but is what it got.",
    timeToJoy: "instant",
    vibes: ["wholesome", "funny"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "lego-kids",
    name: "LEGO Kids",
    url: "https://www.lego.com/en-us/kids",
    category: "wholesome-web",
    blurb: "The LEGO site built for the people who play with LEGO",
    description:
      "LEGO's children's area gathers short videos, browser games, building challenges and downloadable instructions for models made from bricks you already own. It runs separately from the shop, with everything organised by theme rather than by whatever is currently for sale.",
    whyItsGood:
      "The alternative-build instructions are the genuinely useful part, since they show what else a set you finished two years ago can become without buying a single new brick.",
    timeToJoy: "coffee-break",
    vibes: ["wholesome", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: null,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "the-dodo",
    name: "The Dodo",
    url: "https://www.thedodo.com/",
    category: "wholesome-web",
    blurb: "Animal rescue stories, told with the ending you want",
    description:
      "Short video documentaries about animals: rescues, unlikely friendships across species, dogs reunited with their owners, wildlife rehabilitated and released. Stories run a few minutes each, follow one animal throughout, and make the outcome clear before you commit to watching.",
    whyItsGood:
      "Each story stays with a single animal from bad situation to good one, which is exactly why the format still works when the rest of a news feed does not.",
    timeToJoy: "coffee-break",
    vibes: ["wholesome", "cosy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "good-news-network",
    name: "Good News Network",
    url: "https://www.goodnewsnetwork.org/",
    category: "wholesome-web",
    blurb: "Twenty-five years of only the good half of the news",
    description:
      "A daily news site running since 1997 on one editorial rule: publish only positive stories. Coverage spans science breakthroughs, conservation wins, community projects and ordinary acts of decency, reported and sourced rather than scraped off social media.",
    whyItsGood:
      "It predates the wellness-content boom by a decade, so the tone is plain reporting rather than the performed uplift its later imitators go in for.",
    timeToJoy: "coffee-break",
    vibes: ["wholesome", "calming"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 1997,
    altfAlternative: "buzzfeed",
    source: "altf-curated",
  },
  {
    slug: "positive-news",
    name: "Positive News",
    url: "https://www.positive.news/",
    category: "wholesome-web",
    blurb: "Constructive journalism with real reporting behind it",
    description:
      "A British magazine and website built on constructive journalism, which means covering problems but reporting on the responses to them and on whether those responses actually worked. Long features sit beside a running feed of good news, and the print quarterly is well designed.",
    whyItsGood:
      "Stories follow up on whether a solution held, which is the part conventional reporting drops as soon as the announcement has been made.",
    timeToJoy: "coffee-break",
    vibes: ["wholesome", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 1993,
    altfAlternative: "buzzfeed",
    source: "altf-curated",
  },
  {
    slug: "reasons-to-be-cheerful",
    name: "Reasons to be Cheerful",
    url: "https://reasonstobecheerful.world/",
    category: "wholesome-web",
    blurb: "David Byrne's magazine about things that are working",
    description:
      "Founded by the musician David Byrne, this reports on ideas that have demonstrably worked somewhere: a city that cut road deaths, a country that fixed a housing shortage, a scheme that got people back into work. Every piece explains the mechanism, not merely the result.",
    whyItsGood:
      "Each story is written so the approach could be copied elsewhere, which turns pleasant reading into something closer to a catalogue of things that transfer.",
    timeToJoy: "coffee-break",
    vibes: ["wholesome", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "fix-the-news",
    name: "Fix The News",
    url: "https://fixthenews.com/",
    category: "wholesome-web",
    blurb: "A briefing of progress you almost certainly missed",
    description:
      "Formerly Future Crunch, this gathers under-reported good news into regular editions: diseases eliminated, species recovering, energy milestones passed, rights extended. Every claim links out to its source, so it reads as a briefing rather than as a mood board.",
    whyItsGood:
      "Items are grouped by region and topic with the numbers attached, which makes the scale of quiet progress legible in a way individual headlines never manage.",
    timeToJoy: "coffee-break",
    vibes: ["wholesome", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: "buzzfeed",
    source: "altf-curated",
  },
  {
    slug: "the-happy-broadcast",
    name: "The Happy Broadcast",
    url: "https://www.thehappybroadcast.com/",
    category: "wholesome-web",
    blurb: "Good news redrawn as bright, very simple illustrations",
    description:
      "An illustrator turns positive news stories into single-panel drawings, each with a short caption and a link to the original report. The visual format is the delivery mechanism, presenting a reforestation scheme or a medical advance as something closer to a postcard.",
    whyItsGood:
      "Reducing each story to one drawing and one line makes good news genuinely scannable, which is the trick most positive-news sites miss entirely.",
    timeToJoy: "coffee-break",
    vibes: ["wholesome", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "explore-live-cams",
    name: "Explore.org Live Cams",
    url: "https://explore.org/livecams",
    category: "wholesome-web",
    blurb: "Hundreds of live animal cams, from bear falls to puppy rooms",
    description:
      "A philanthropic project running live cameras on wildlife and sanctuaries worldwide: brown bears fishing a waterfall, osprey nests, African waterholes, service-dog puppy rooms and coral reefs. Highlights get clipped and saved, so there is something to watch when the animals are asleep.",
    whyItsGood:
      "The Alaskan bear cam during salmon season is appointment viewing, complete with an annual public vote on which bear has put on the most weight.",
    timeToJoy: "instant",
    vibes: ["wholesome", "calming", "mesmerising"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "monterey-bay-aquarium-cams",
    name: "Monterey Bay Aquarium Live Cams",
    url: "https://www.montereybayaquarium.org/animals/live-cams",
    category: "wholesome-web",
    blurb: "Jellyfish, sea otters and a kelp forest, streaming live",
    description:
      "The aquarium points cameras at its jellyfish gallery, sea otter enclosure, penguin colony, shark exhibit and the kelp forest that runs the full height of the building. Streams carry ambient audio, and divers occasionally swim through with a live commentary session.",
    whyItsGood:
      "The jellyfish cam is the one to leave open: a slow drift of moon jellies against blue that works better as a background than any screensaver.",
    timeToJoy: "instant",
    vibes: ["calming", "mesmerising", "wholesome"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: null,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "cornell-bird-cams",
    name: "Cornell Lab Bird Cams",
    url: "https://www.allaboutbirds.org/cams/",
    category: "wholesome-web",
    blurb: "Watch one nest from first egg to first flight",
    description:
      "Cornell's ornithology lab runs cameras on nests and feeders: bald eagles, barn owls, albatrosses in Hawaii, hummingbirds and a permanently busy Ontario feeder. Seasons are followed from nest building through hatching to fledging, with researchers annotating what is happening and why.",
    whyItsGood:
      "Following one nest across a season becomes a real commitment, and lab staff answer questions in the chat when something goes wrong on camera.",
    timeToJoy: "coffee-break",
    vibes: ["wholesome", "calming", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2012,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "elephant-sanctuary-elecam",
    name: "The Elephant Sanctuary EleCam",
    url: "https://www.elephants.com/elecam",
    category: "wholesome-web",
    blurb: "Retired circus elephants, doing nothing in particular",
    description:
      "A Tennessee sanctuary for elephants retired from circuses and zoos runs solar-powered cameras across its habitats and barns, streaming whatever the herd happens to be doing. There is no schedule and no performance: an elephant may be out of shot for an hour, then wander through for a dust bath.",
    whyItsGood:
      "Each animal has a history published on the sanctuary's own pages, so watching stops being an animal cam and becomes something closer to a retirement update.",
    timeToJoy: "coffee-break",
    vibes: ["wholesome", "calming"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: null,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "zooborns",
    name: "ZooBorns",
    url: "https://zooborns.com/",
    category: "wholesome-web",
    blurb: "Newborn zoo animals, announced as they arrive",
    description:
      "A running feed of births at zoos and aquariums worldwide, with photographs, the species, the institution and usually a note on conservation status. Because it draws on official announcements, the pictures are the ones the keepers took rather than reposts of reposts.",
    whyItsGood:
      "Rare-species births arrive with an explanation of why that particular calf matters to a breeding programme, so the cuteness comes with context attached.",
    timeToJoy: "coffee-break",
    vibes: ["wholesome", "cosy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2008,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "random-dog",
    name: "random.dog",
    url: "https://random.dog/",
    category: "wholesome-web",
    blurb: "A dog. Press the button. Another dog.",
    description:
      "A photograph or short video of a dog fills the page, and clicking anywhere loads a different one. Submissions come from the public, so the collection skews heavily towards ordinary pets photographed badly rather than towards professional stock imagery.",
    whyItsGood:
      "The amateur photography is the charm, given that half the pictures are blurred, mid-yawn, or taken from an angle that flatters no animal alive.",
    timeToJoy: "instant",
    vibes: ["wholesome", "funny"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "freerice",
    name: "Freerice",
    url: "https://freerice.com/",
    category: "wholesome-web",
    blurb: "Answer a question, fund ten grains of rice",
    description:
      "A quiz run by the UN World Food Programme in which each correct answer earns a small donation of rice, funded by the advert shown beside the question. Subjects include vocabulary, geography, maths, chemistry and languages, and the difficulty adapts as you play.",
    whyItsGood:
      "The running total of grains earned is oddly motivating, and the vocabulary levels get hard enough that adults quietly stop showing off around level forty.",
    timeToJoy: "coffee-break",
    vibes: ["wholesome", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2007,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "postcrossing",
    name: "Postcrossing",
    url: "https://www.postcrossing.com/",
    category: "wholesome-web",
    blurb: "Post a card to a stranger, get one back from elsewhere",
    description:
      "Request an address and the site hands you a random member somewhere in the world to send a physical postcard to. Once yours is registered as arrived, your own address enters the pool and a card comes back to you from an entirely different country.",
    whyItsGood:
      "The exchange is deliberately not reciprocal, so the card you receive comes from someone you never wrote to, which is what stops the whole thing becoming an obligation.",
    timeToJoy: "rabbit-hole",
    vibes: ["wholesome", "cosy"],
    bestOn: "both",
    needsAccount: true,
    free: true,
    year: 2005,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "storycorps",
    name: "StoryCorps",
    url: "https://storycorps.org/",
    category: "wholesome-web",
    blurb: "Ordinary people interviewing the people they love",
    description:
      "An oral history project that records conversations between two people who already know each other well, then archives them, with a large share preserved at the Library of Congress. Recordings run around forty minutes, and animated shorts adapt some of the best ones.",
    whyItsGood:
      "Because the interviewer is a relative rather than a journalist, questions get asked that no professional would risk, and the answers are correspondingly unguarded.",
    timeToJoy: "coffee-break",
    vibes: ["wholesome", "calming"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2003,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "random-acts-of-kindness",
    name: "Random Acts of Kindness Foundation",
    url: "https://www.randomactsofkindness.org/",
    category: "wholesome-web",
    blurb: "A library of small, specific things to do for someone",
    description:
      "A foundation publishing kindness ideas, printable cards and complete lesson plans for classrooms, all free to download. Suggestions stay deliberately concrete, from paying a compliment properly to writing to a teacher who mattered, rather than drifting into general encouragement.",
    whyItsGood:
      "The classroom material is the substantial part, with sequenced lessons that schools genuinely use, putting it well past the usual list of nice thoughts.",
    timeToJoy: "coffee-break",
    vibes: ["wholesome", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 1995,
    altfAlternative: null,
    source: "altf-curated",
  },
];

export default sites;
