/** Satire and comics, unreasonably good free tools, AI demos, and data made legible. */
const sites = [
  // ── comedy-department ──────────────────────────────────────────────────────
  {
    slug: "the-oatmeal",
    name: "The Oatmeal",
    url: "https://theoatmeal.com/",
    category: "comedy-department",
    blurb: "Long comic essays about grammar, grief and running",
    description:
      "Matthew Inman draws sprawling comic essays that swing between semicolon pedantry, endurance running, and unexpectedly raw pieces about anxiety or losing a pet. Older strips sit in a browsable archive, and the card games he is now better known for grew out of the same drawings.",
    whyItsGood:
      "The tonal range is the trick. You arrive for a joke about apostrophes and get ambushed by the strip about his dog.",
    timeToJoy: "coffee-break",
    vibes: ["funny", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2009,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "the-onion",
    name: "The Onion",
    url: "https://www.theonion.com/",
    category: "comedy-department",
    blurb: "Fake news headlines that outlived the real ones",
    description:
      "Satire dressed in the flat register of wire copy, complete with stock photos, invented experts and correspondent quotes. Nothing reported here is real, and the joke usually lands entirely in the headline. Three decades of archive sit behind the front page.",
    whyItsGood:
      "Headline craft is the whole discipline. A good one does its work in eleven words before you have clicked anything.",
    timeToJoy: "one-minute",
    vibes: ["funny"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 1996,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "i-waste-so-much-time",
    name: "I Waste So Much Time",
    url: "https://iwastesomuchtime.com/",
    category: "comedy-department",
    blurb: "A meme feed built for exactly one idle scroll",
    description:
      "Reaction images, screenshots and short comic panels posted into a plain grid, each carrying a vote count. The format has barely changed since 2011, so it reads like a snapshot of the pre-algorithm meme web, and a submission queue plus a forum are still attached.",
    whyItsGood:
      "The vote counts are the useful part, because they sort a very large pile down to the handful that actually landed.",
    timeToJoy: "instant",
    vibes: ["funny", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: "kym",
    source: "listicle",
  },
  {
    slug: "xkcd",
    name: "xkcd",
    url: "https://xkcd.com/",
    category: "comedy-department",
    blurb: "Stick figures doing maths, romance and language jokes",
    description:
      "Randall Munroe posts three drawings a week covering physics, dating, statistics and the occasional enormous interactive panel. Hovering over the comic reveals a second punchline hidden in the title text. Several strips have become permanent internet shorthand.",
    whyItsGood:
      "The alt text behind the mouse hover is a whole second comic, and skipping it means reading half of what was drawn.",
    timeToJoy: "rabbit-hole",
    vibes: ["funny", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2005,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "smbc-comics",
    name: "Saturday Morning Breakfast Cereal",
    url: "https://www.smbc-comics.com/",
    category: "comedy-department",
    blurb: "Philosophy and biology jokes, with a red button under each",
    description:
      "Zach Weinersmith draws single-page strips that move between economics, evolutionary biology, parenting and moral philosophy. Below each comic sits a red button that opens a bonus panel, usually a darker or sillier extension of the same idea. New strips appear most days.",
    whyItsGood:
      "That red votey button is the reward for scrolling, and the bonus panel it opens is frequently funnier than the comic above it.",
    timeToJoy: "rabbit-hole",
    vibes: ["funny", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2002,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "the-far-side",
    name: "The Far Side",
    url: "https://www.thefarside.com/",
    category: "comedy-department",
    blurb: "Gary Larson's cows and scientists, officially online",
    description:
      "The official home of Gary Larson's single-panel newspaper cartoons, which he kept off the web for decades before opening this site himself. A rotating daily selection sits on the front page, alongside occasional new drawings and Larson's own written notes on old panels.",
    whyItsGood:
      "Larson explaining which of his own cartoons confused readers, and why, is material that exists nowhere else.",
    timeToJoy: "one-minute",
    vibes: ["funny", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "perry-bible-fellowship",
    name: "The Perry Bible Fellowship",
    url: "https://pbfcomics.com/",
    category: "comedy-department",
    blurb: "Beautifully drawn strips with a very bad ending",
    description:
      "Nicholas Gurewitch changes art style completely from strip to strip, moving between children's-book watercolour, woodcut and clean vector. The joke is almost always a sharp turn in the final panel, and the distance between how gentle a strip looks and where it goes is the point.",
    whyItsGood:
      "Each strip is drawn in whatever style will make the last panel hurt most, which is a level of effort no gag comic actually needs.",
    timeToJoy: "coffee-break",
    vibes: ["funny", "beautiful", "unsettling"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2001,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "dinosaur-comics",
    name: "Dinosaur Comics",
    url: "https://qwantz.com/",
    category: "comedy-department",
    blurb: "Same six panels every time, different conversation",
    description:
      "Ryan North has used one identical set of clip-art dinosaur panels since 2003 and changes only the dialogue. T-Rex talks himself into a position, Dromiceiomimus and Utahraptor puncture it, and the argument covers language, ethics or time travel. Constraint does all the work.",
    whyItsGood:
      "Knowing the artwork can never change forces you to read the words properly, which is presumably the entire reason for the format.",
    timeToJoy: "coffee-break",
    vibes: ["funny", "brainy", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2003,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "cyanide-and-happiness",
    name: "Cyanide & Happiness",
    url: "https://explosm.net/",
    category: "comedy-department",
    blurb: "Crude stick figures, consistently indefensible punchlines",
    description:
      "A rotating group of artists posts short strips built on deliberately basic drawings and endings that go somewhere grim or absurd. Animated shorts sit alongside a long archive reaching back to the mid-2000s. Humour here is broad and frequently tasteless by design.",
    whyItsGood:
      "The flat, almost lazy art style is a setup in itself, because nothing in the drawing warns you where the last panel is heading.",
    timeToJoy: "one-minute",
    vibes: ["funny", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2004,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "false-knees",
    name: "False Knees",
    url: "https://falseknees.com/",
    category: "comedy-department",
    blurb: "Birds saying what birds would obviously say",
    description:
      "Joshua Barkman draws carefully observed wildlife and hands it plain, slightly anxious dialogue. Chickadees complain, herons pose, crows are rude. The illustration is genuine natural-history work, which makes the mundane conversations funnier than a cruder drawing would.",
    whyItsGood:
      "The birds are painted accurately enough to identify by species, then given lines about social awkwardness and low-grade resentment.",
    timeToJoy: "one-minute",
    vibes: ["funny", "wholesome", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "war-and-peas",
    name: "War and Peas",
    url: "https://warandpeas.com/",
    category: "comedy-department",
    blurb: "Four panels, one dark twist, drawn very cleanly",
    description:
      "Elizabeth Pich and Jonathan Kunz work with a recurring cast that includes a witch, a robot and Death, all rendered in a soft pastel style. Strips run four panels and end on something bleak, tender or both at once. The archive is long and the pacing never wobbles.",
    whyItsGood:
      "The witch and the robot carry real continuity between strips, so reading the archive slowly turns into a story you did not sign up for.",
    timeToJoy: "coffee-break",
    vibes: ["funny", "cosy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "garfield-minus-garfield",
    name: "Garfield Minus Garfield",
    url: "https://garfieldminusgarfield.net/",
    category: "comedy-department",
    blurb: "Jon Arbuckle, alone, talking to nobody at all",
    description:
      "Somebody removed Garfield from the Garfield strips, leaving only Jon talking to an empty room. The otherwise unchanged artwork suddenly reads as a portrait of a man losing his grip. Dan Walsh has been running the edit since 2008, and Jim Davis eventually endorsed it.",
    whyItsGood:
      "Deleting one character with no other edits turns a newspaper gag strip into something quietly devastating, and it works every single time.",
    timeToJoy: "one-minute",
    vibes: ["funny", "unsettling"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2008,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "the-daily-mash",
    name: "The Daily Mash",
    url: "https://www.thedailymash.co.uk/",
    category: "comedy-department",
    blurb: "British satire aimed at the middle classes",
    description:
      "Satirical UK news made up of short invented items about commuting, pub arguments, parenting and whichever politician is currently in trouble. Nothing described here happened. The register sits closer to overheard complaint than to press release, and columns run under fictional bylines.",
    whyItsGood:
      "The invented reader letters and vox pops are the sharpest part, since the joke lands on the person complaining rather than the news.",
    timeToJoy: "one-minute",
    vibes: ["funny"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2007,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "newsthump",
    name: "NewsThump",
    url: "https://newsthump.com/",
    category: "comedy-department",
    blurb: "Made-up UK news stories, published at speed",
    description:
      "A satirical outlet posting fictional stories within hours of whatever is dominating British headlines. Everything is invented, and the site says so plainly. Volume is the strategy, with several pieces a day and a large searchable back catalogue behind them.",
    whyItsGood:
      "Turnaround is the trick. A piece usually appears while the real story it is mocking is still sitting on the front page.",
    timeToJoy: "one-minute",
    vibes: ["funny"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2008,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "waterford-whispers-news",
    name: "Waterford Whispers News",
    url: "https://waterfordwhispersnews.com/",
    category: "comedy-department",
    blurb: "Irish satire with a very specific local accent",
    description:
      "Fictional news written from an Irish perspective, covering national politics, the church, housing and small-town life. None of the stories are real. Local specificity is the engine, though pieces about universal irritations travel well enough for anyone to follow.",
    whyItsGood:
      "Parish-level detail is what sells it, right down to invented county councillors with entirely plausible names.",
    timeToJoy: "one-minute",
    vibes: ["funny"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2009,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "reductress",
    name: "Reductress",
    url: "https://reductress.com/",
    category: "comedy-department",
    blurb: "Satirical women's magazine headlines, played straight",
    description:
      "Parody lifestyle and wellness journalism, written in the exact voice of the magazines it is mocking. Every article is invented. The target is usually the advice industry rather than any individual, and pieces rarely run long because the headline has done the work already.",
    whyItsGood:
      "The register is copied so precisely that a headline can sit in a feed for a second before you register that it is satire.",
    timeToJoy: "one-minute",
    vibes: ["funny"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "mcsweeneys-internet-tendency",
    name: "McSweeney's Internet Tendency",
    url: "https://www.mcsweeneys.net/",
    category: "comedy-department",
    blurb: "Short comic lists and monologues, published daily",
    description:
      "A daily humour column running very short pieces: open letters, lists, monologues and premises stretched to breaking point. Titles are often longer than the articles beneath them. A great many well-known comedy writers published here first, and the archive reaches back to 1998.",
    whyItsGood:
      "Pieces are short enough to finish in a lift, and the titles alone are frequently the funniest thing you will read all day.",
    timeToJoy: "coffee-break",
    vibes: ["funny", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 1998,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "clickhole",
    name: "ClickHole",
    url: "https://clickhole.com/",
    category: "comedy-department",
    blurb: "Parody of viral listicles, taken far past reason",
    description:
      "Satire aimed squarely at the mechanics of viral content: quizzes with no correct answers, listicles that collapse partway through, and personal essays that escalate into nonsense. Originally an Onion project, now independent and employee-owned. Everything on it is fictional.",
    whyItsGood:
      "The quizzes commit hardest, running the full interactive format for eight questions before telling you the result means nothing.",
    timeToJoy: "coffee-break",
    vibes: ["funny", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: "buzzfeed",
    source: "altf-curated",
  },

  // ── practical-magic ────────────────────────────────────────────────────────
  {
    slug: "supercook",
    name: "SuperCook",
    url: "https://www.supercook.com/",
    category: "practical-magic",
    blurb: "Tick what is in your kitchen, get things you can cook now",
    description:
      "Rather than searching for a recipe and shopping for it, you tick off the ingredients you already have and the site filters a large recipe index down to what those items can actually make. Results are ranked by how few extra items you would need.",
    whyItsGood:
      "The 'you are one ingredient away' section is the genuinely useful part, because it turns a no into a short shopping list.",
    timeToJoy: "one-minute",
    vibes: ["useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2008,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "hotspot-3d",
    name: "Hotspot 3D",
    url: "https://www.hotspot3d.com/",
    category: "practical-magic",
    blurb: "Two products, side by side, in 3D at true size",
    description:
      "An embeddable comparison widget, shown here as a working demo, that places two products next to each other as rotatable 3D models at correct relative scale. The sample pits one phone against another, answering the question a spec sheet never does. Still labelled beta.",
    whyItsGood:
      "Seeing two devices at accurate relative size settles a decision that millimetre dimensions never do, because almost nobody can picture 6.7 inches.",
    timeToJoy: "one-minute",
    vibes: ["useful", "mesmerising"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: null,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "photopea",
    name: "Photopea",
    url: "https://www.photopea.com/",
    category: "practical-magic",
    blurb: "Photoshop, running in a tab, opening your PSD files",
    description:
      "A raster and vector editor that loads PSD, XCF, Sketch and AI files with layers intact, and runs entirely in the browser with nothing to install. Layer masks, adjustment layers, blend modes and smart objects behave the way their desktop equivalents do. One developer maintains it.",
    whyItsGood:
      "Opening a client's layered PSD on a borrowed laptop with nothing installed is the exact moment this earns its reputation.",
    timeToJoy: "coffee-break",
    vibes: ["useful", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "squoosh",
    name: "Squoosh",
    url: "https://squoosh.app/",
    category: "practical-magic",
    blurb: "Shrink an image and watch the quality drop live",
    description:
      "Google's image compressor shows the original and the compressed version either side of a draggable divider, so you can see precisely what a quality setting costs. Codecs include MozJPEG, WebP, AVIF and OxiPNG, and the work happens locally without uploading the file anywhere.",
    whyItsGood:
      "The split-screen slider turns compression from guesswork into something visible, which is why you end up picking a lower setting than you planned to.",
    timeToJoy: "one-minute",
    vibes: ["useful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "remove-bg",
    name: "remove.bg",
    url: "https://www.remove.bg/",
    category: "practical-magic",
    blurb: "Cut a subject out of a photo in about five seconds",
    description:
      "Upload a picture containing a person, product or animal and the background disappears automatically, including a decent attempt at hair edges. Free downloads arrive at preview resolution, with full-size files priced per image. No selection tool or editing skill is involved.",
    whyItsGood:
      "Hair and fur are the part every manual selection tool fails at, and this handles them well enough that you stop checking the edges.",
    timeToJoy: "instant",
    vibes: ["useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "pdf24-tools",
    name: "PDF24 Tools",
    url: "https://tools.pdf24.org/en/",
    category: "practical-magic",
    blurb: "Thirty PDF jobs, no file cap, no sign-up wall",
    description:
      "Merge, split, compress, rotate, sign, unlock, convert and OCR PDFs from a single index page. Most operations run without an account or a size limit, and several process locally in the browser rather than on a server. Output holds up for anything short of print production.",
    whyItsGood:
      "It does the awkward jobs the better-known PDF sites keep behind a subscription, notably OCR and password removal.",
    timeToJoy: "one-minute",
    vibes: ["useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "print-friendly",
    name: "PrintFriendly",
    url: "https://www.printfriendly.com/",
    category: "practical-magic",
    blurb: "Strip an article down to the words, then save it",
    description:
      "Paste any article URL and the page comes back without ads, navigation, comments or sidebars. Before saving you can click individual paragraphs and images out of the layout, then export as PDF or send it to a printer. It copes with most news sites and long-form blogs.",
    whyItsGood:
      "Being able to delete paragraphs by clicking them means the saved PDF holds the article and genuinely nothing else.",
    timeToJoy: "one-minute",
    vibes: ["useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2009,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "wolfram-alpha",
    name: "Wolfram Alpha",
    url: "https://www.wolframalpha.com/",
    category: "practical-magic",
    blurb: "Ask a question with numbers in it, get worked steps",
    description:
      "A computational engine rather than a search box, answering maths, physics, chemistry, finance and unit questions by calculating instead of retrieving pages. Type an integral, a chemical formula, a date range or two city names and structured results come back with charts attached.",
    whyItsGood:
      "Typing a plain-English question such as the mass of the Moon in double-decker buses returns an actual figure, which no search engine will do.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2009,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "desmos",
    name: "Desmos Graphing Calculator",
    url: "https://www.desmos.com/calculator",
    category: "practical-magic",
    blurb: "A graphing calculator that keeps up with your typing",
    description:
      "Type an equation and the curve appears immediately, with a slider generated automatically for any variable you introduce. It handles inequalities, regressions, parametrics and tables, and renders smoothly enough to drag a parameter and watch the shape move in real time.",
    whyItsGood:
      "Adding a stray letter to an equation spawns a slider for it without being asked, which turns a static plot into something you can push around.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "useful", "mesmerising"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "excalidraw",
    name: "Excalidraw",
    url: "https://excalidraw.com/",
    category: "practical-magic",
    blurb: "Diagrams that look hand-drawn, shared by one link",
    description:
      "An infinite canvas for boxes, arrows and rough sketches, rendered in a deliberately wobbly hand-drawn style. Live collaboration works from a shared link with no account, drawings stay in the browser unless exported, and shape libraries cover most system-diagram needs.",
    whyItsGood:
      "The sketchy rendering signals that a diagram is a draft, so colleagues argue with the idea instead of with your box alignment.",
    timeToJoy: "one-minute",
    vibes: ["useful", "cosy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2020,
    altfAlternative: "sketchflow",
    source: "altf-curated",
  },
  {
    slug: "it-tools",
    name: "IT Tools",
    url: "https://it-tools.tech/",
    category: "practical-magic",
    blurb: "A hundred small developer utilities on one page",
    description:
      "One open-source page collecting the fiddly conversions people otherwise search for individually: hash generators, token decoders, cron parsers, colour converters, QR builders, case changers and date maths. Everything runs client-side, and the search box reaches a tool in a keystroke.",
    whyItsGood:
      "It replaces the pile of advert-covered single-purpose sites you would otherwise land on from a search result.",
    timeToJoy: "instant",
    vibes: ["useful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2022,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "have-i-been-pwned",
    name: "Have I Been Pwned",
    url: "https://haveibeenpwned.com/",
    category: "practical-magic",
    blurb: "Type your email, find out which breaches you are in",
    description:
      "Troy Hunt's index of leaked credentials, searchable by email address or phone number. Results name the company breached, the date, and which fields were exposed. A separate checker tells you whether a specific password has appeared in a dump, without ever receiving that password.",
    whyItsGood:
      "The password check uses a partial-hash trick so the site never learns what you typed, which is a rare piece of honest engineering.",
    timeToJoy: "instant",
    vibes: ["useful", "unsettling"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "tineye",
    name: "TinEye",
    url: "https://tineye.com/",
    category: "practical-magic",
    blurb: "Find where an image came from, not what it shows",
    description:
      "Reverse image search built on matching the picture itself rather than guessing at its subject. Upload a file or paste a URL and it returns pages carrying that same image, sortable by oldest first. Useful for tracing an unattributed photo back to its original posting.",
    whyItsGood:
      "Sorting matches by oldest is the feature that settles arguments, because it points at where a viral image actually started.",
    timeToJoy: "one-minute",
    vibes: ["useful", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2008,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "wormhole",
    name: "Wormhole",
    url: "https://wormhole.app/",
    category: "practical-magic",
    blurb: "Send a 10GB file with a link that expires itself",
    description:
      "Drop in a file, get a link, hand it over. Transfers are encrypted in the browser before upload so the service cannot read what passes through it, and links expire after a set time or download count. Smaller files travel peer to peer without touching storage at all.",
    whyItsGood:
      "The link expiring on its own is the whole point, since you never have to remember to go back and delete anything.",
    timeToJoy: "instant",
    vibes: ["useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2021,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "audiomass",
    name: "AudioMass",
    url: "https://audiomass.co/",
    category: "practical-magic",
    blurb: "Trim and edit audio without installing anything",
    description:
      "A waveform editor running entirely in the browser: cut, fade, normalise, apply compression or reverb, then export to MP3 or WAV. Files never leave the machine. It covers the jobs most people actually open a desktop audio editor for, which is trimming silence and fixing levels.",
    whyItsGood:
      "It loads in the time a desktop audio editor takes to draw its splash screen, which matters when the task is a ten-second trim.",
    timeToJoy: "one-minute",
    vibes: ["useful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "vocal-remover",
    name: "Vocal Remover and Isolation",
    url: "https://vocalremover.org/",
    category: "practical-magic",
    blurb: "Split a song into vocals and instrumental, free",
    description:
      "Feed it a track and a machine-learning model separates that recording into a vocal stem and a backing stem, both downloadable. The same site carries a pitch shifter, a key and tempo finder, a joiner and a karaoke maker. Results are clean enough for practice tracks and rough remixes.",
    whyItsGood:
      "Isolating a vocal used to require paid stem-separation software, and hearing a familiar record with the band removed is genuinely disorienting.",
    timeToJoy: "coffee-break",
    vibes: ["useful", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "otranscribe",
    name: "oTranscribe",
    url: "https://otranscribe.com/",
    category: "practical-magic",
    blurb: "Type up an interview without touching the mouse",
    description:
      "A transcription workspace putting the audio player and the text field on one screen, with keyboard shortcuts for pause and rewind so your hands never leave the keys. Timestamps insert with a single key. Nothing uploads, and the draft saves into the browser as you type.",
    whyItsGood:
      "Escape pauses playback and rewinds a couple of seconds automatically, which removes the single most irritating part of transcribing.",
    timeToJoy: "coffee-break",
    vibes: ["useful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "svgcode",
    name: "SVGcode",
    url: "https://svgco.de/",
    category: "practical-magic",
    blurb: "Turn a blurry logo into clean scalable vectors",
    description:
      "Hand it a raster image and the picture is traced into SVG paths you can then scale to any size without blurring. Controls cover colour count, path smoothing and how much detail survives. It installs as an offline web app, and the tracing happens on your own machine.",
    whyItsGood:
      "Rescuing a company logo that only survives as a small murky PNG is the specific job this quietly solves for nothing.",
    timeToJoy: "one-minute",
    vibes: ["useful", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2021,
    altfAlternative: null,
    source: "altf-curated",
  },

  // ── ai-playground ──────────────────────────────────────────────────────────
  {
    slug: "chatgpt",
    name: "ChatGPT",
    url: "https://chatgpt.com/",
    category: "ai-playground",
    blurb: "The chatbot that made everyone else build a chatbot",
    description:
      "OpenAI's assistant handles writing, code, analysis, images and voice from a single text box. The free tier covers general questions and file uploads with usage caps, while paid plans open up the larger models. An account is required before the first message goes through.",
    whyItsGood:
      "Pasting in a messy spreadsheet or a photograph of a handwritten note and getting structured text back is still the demonstration that lands with people.",
    timeToJoy: "instant",
    vibes: ["brainy", "useful"],
    bestOn: "both",
    needsAccount: true,
    free: true,
    year: 2022,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "this-person-does-not-exist",
    name: "This Person Does Not Exist",
    url: "https://thispersondoesnotexist.com/",
    category: "ai-playground",
    blurb: "Every refresh invents a face that never existed",
    description:
      "One full-screen portrait, produced by a StyleGAN model, replaced by a new one each time you reload. Nobody shown has ever lived. Stare for a few seconds and the artefacts surface: melted earrings, backgrounds that dissolve, teeth that do not agree with one another.",
    whyItsGood:
      "The unsettling part arrives around the fifth refresh, when you notice you have started checking ears and jewellery for mistakes.",
    timeToJoy: "instant",
    vibes: ["unsettling", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "this-x-does-not-exist",
    name: "This X Does Not Exist",
    url: "https://thisxdoesnotexist.com/",
    category: "ai-playground",
    blurb: "An index of everything the machines are inventing",
    description:
      "A directory of generative demos in the same family as the face generator: cats, cities, chairs, artwork, rental listings and considerably more. Each card links through to a working generator with a short note on the model behind it. Quality varies wildly, which is half the point.",
    whyItsGood:
      "The failures beat the successes, and the cat generator in particular keeps producing animals with an unresolved number of legs.",
    timeToJoy: "coffee-break",
    vibes: ["weird", "funny"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "claude-ai",
    name: "Claude",
    url: "https://claude.ai/",
    category: "ai-playground",
    blurb: "Anthropic's assistant, strongest on long documents",
    description:
      "A chat assistant that accepts long files, writes and runs code, and builds shareable artifacts inside the conversation itself. The free tier carries daily message limits. People tend to reach for it when the task is careful writing or reasoning across documents.",
    whyItsGood:
      "Dropping in a hundred-page PDF and asking what changed between two versions is the task where the long context earns its keep.",
    timeToJoy: "instant",
    vibes: ["brainy", "useful"],
    bestOn: "both",
    needsAccount: true,
    free: true,
    year: 2023,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "google-gemini",
    name: "Google Gemini",
    url: "https://gemini.google.com/",
    category: "ai-playground",
    blurb: "Google's model, wired into search and your files",
    description:
      "Gemini answers in chat, generates and edits images, and connects to Google's own services so it can reach documents and mail once you grant permission. Free access covers the standard model with limits attached. Signing in uses an existing Google account.",
    whyItsGood:
      "Asking it to pull one figure out of a named document in your own Drive removes the copy-and-paste step every other assistant still needs.",
    timeToJoy: "instant",
    vibes: ["useful", "brainy"],
    bestOn: "both",
    needsAccount: true,
    free: true,
    year: 2023,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "perplexity",
    name: "Perplexity",
    url: "https://www.perplexity.ai/",
    category: "ai-playground",
    blurb: "Answers with the sources listed underneath",
    description:
      "A search-shaped assistant that runs a live web query, writes a short answer, and footnotes each claim with the page it came from. Follow-up questions keep the thread going. The citation list is really the product, because it lets you check the answer rather than trust it.",
    whyItsGood:
      "Every sentence carries a numbered source you can open, which makes the failure mode visible instead of hidden.",
    timeToJoy: "instant",
    vibes: ["useful", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2022,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "hugging-face-spaces",
    name: "Hugging Face Spaces",
    url: "https://huggingface.co/spaces",
    category: "ai-playground",
    blurb: "Thousands of live model demos, most free to try",
    description:
      "A hosting platform where researchers publish runnable demos of their models, so image generators, speech recognisers, background removers and 3D reconstructors all sit behind a plain web form. Many run free on shared hardware, though the popular ones queue at busy times.",
    whyItsGood:
      "New research demos land here within days of the paper, so it is where you try a technique months before it turns up in a product.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "weird"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2021,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "quick-draw",
    name: "Quick, Draw!",
    url: "https://quickdraw.withgoogle.com/",
    category: "ai-playground",
    blurb: "Doodle six things while a model shouts guesses",
    description:
      "You get twenty seconds per prompt to draw an object while a neural network calls out what it thinks is appearing. Six rounds make a game. Afterwards you can browse the training set, which now holds tens of millions of doodles contributed by other players.",
    whyItsGood:
      "The post-game archive is the real prize, because you can see fifty thousand strangers' attempts at drawing a lobster all at once.",
    timeToJoy: "one-minute",
    vibes: ["funny", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "teachable-machine",
    name: "Teachable Machine",
    url: "https://teachablemachine.withgoogle.com/",
    category: "ai-playground",
    blurb: "Train an image classifier in about four minutes",
    description:
      "Point a webcam at yourself, record a few seconds for each category you want to teach, press train, and the model starts classifying live. No code is involved at any stage. The finished model exports and drops into a website or a small hardware project.",
    whyItsGood:
      "Watching a classifier learn to tell your left hand from your right inside a minute makes machine learning feel like a mechanism rather than magic.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "useful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2017,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "semantris",
    name: "Semantris",
    url: "https://research.google.com/semantris/",
    category: "ai-playground",
    blurb: "A word game where the scoring is done by meaning",
    description:
      "Type a word and the machine ranks the blocks on screen by how closely each relates to what you wrote, then clears whichever it picks. There is no dictionary of correct answers, only associations the model has learned. Two modes, one arcade-paced and one that stacks blocks.",
    whyItsGood:
      "Working out which sideways association the model will accept is the actual game, and it fails in ways that reveal how it thinks.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "competitive"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "arena-ai",
    name: "Arena",
    url: "https://arena.ai/",
    category: "ai-playground",
    blurb: "Two anonymous models answer, you pick the winner",
    description:
      "Send one prompt and two unnamed models reply side by side. You vote for the better answer, the names are revealed afterwards, and aggregated votes feed a public leaderboard. Formerly LMArena, it stays the least gameable ranking around because the judging is blind.",
    whyItsGood:
      "Voting blind and then seeing which model you actually preferred tends to contradict whatever you assumed from the leaderboard.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "competitive"],
    bestOn: "both",
    needsAccount: true,
    free: true,
    year: 2023,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "tensorflow-playground",
    name: "TensorFlow Playground",
    url: "https://playground.tensorflow.org/",
    category: "ai-playground",
    blurb: "Watch a neural network learn, one neuron at a time",
    description:
      "A neural network rendered as a diagram you can edit: add layers, swap activation functions, adjust learning rate and noise, then press play and watch the decision boundary bend itself around the data. Every connection is drawn, and thickens as its weight grows.",
    whyItsGood:
      "Removing one hidden layer and seeing the spiral dataset become instantly unlearnable teaches more than a chapter of notation.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "mesmerising"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "which-face-is-real",
    name: "Which Face Is Real",
    url: "https://www.whichfaceisreal.com/",
    category: "ai-playground",
    blurb: "Two portraits. One is a real person. Choose.",
    description:
      "A test built by University of Washington researchers: two faces appear, one photographed and one generated, and you pick the real one. It scores you immediately and explains the giveaway you missed. Accuracy across many rounds is usually worse than people expect it to be.",
    whyItsGood:
      "The explanation after each round trains you to spot the tells, and watching your own accuracy climb is oddly reassuring.",
    timeToJoy: "one-minute",
    vibes: ["unsettling", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "webllm-chat",
    name: "WebLLM Chat",
    url: "https://chat.webllm.ai/",
    category: "ai-playground",
    blurb: "A language model running on your own graphics card",
    description:
      "Chat with an open-weights model that downloads once and then runs entirely inside the browser through WebGPU. Nothing is sent to a server, so it carries on working with the network switched off. The first load is a large download, after which replies generate locally.",
    whyItsGood:
      "Disconnecting from the internet mid-conversation and watching it keep answering is the moment local inference stops being an abstract claim.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "weird"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2024,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "whisper-web",
    name: "Whisper WebGPU",
    url: "https://huggingface.co/spaces/Xenova/whisper-webgpu",
    category: "ai-playground",
    blurb: "Transcribe audio locally, with no upload anywhere",
    description:
      "A demo of OpenAI's Whisper speech model compiled to run inside the browser via WebGPU. Load a file or record straight from the microphone and the transcript appears without the audio ever leaving your machine. Many languages are supported and the model downloads once.",
    whyItsGood:
      "Getting a usable transcript of a recorded meeting while completely offline is something that used to require a paid subscription.",
    timeToJoy: "coffee-break",
    vibes: ["useful", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2024,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "craiyon",
    name: "Craiyon",
    url: "https://www.craiyon.com/",
    category: "ai-playground",
    blurb: "The scrappy image generator that got there first",
    description:
      "Previously DALL-E Mini, this text-to-image generator went viral in 2022 for producing recognisable but distorted results quickly and for free. It still runs without an account, returning a grid of images per prompt. Quality sits well behind current paid models, which is much of the charm.",
    whyItsGood:
      "Those characteristic smeared faces became a meme format in their own right, and the model still reliably produces them on request.",
    timeToJoy: "one-minute",
    vibes: ["funny", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2022,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "notebooklm",
    name: "NotebookLM",
    url: "https://notebooklm.google.com/",
    category: "ai-playground",
    blurb: "Upload your sources, get a podcast about them",
    description:
      "A research assistant restricted to documents you supply, so every answer cites your own PDFs, slides and links rather than the open web. Its audio overview feature generates a two-host conversation discussing your material, complete with interruptions and tangents.",
    whyItsGood:
      "Feeding it a dense technical paper and getting back two synthetic voices arguing about it is a genuinely new way to review material.",
    timeToJoy: "coffee-break",
    vibes: ["useful", "unsettling", "brainy"],
    bestOn: "both",
    needsAccount: true,
    free: true,
    year: 2023,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "pollinations",
    name: "Pollinations",
    url: "https://pollinations.ai/",
    category: "ai-playground",
    blurb: "Type a prompt into a URL and get an image back",
    description:
      "A free image and text generation service with no account and no API key. Images can be requested straight from a URL pattern, so a prompt typed into the address bar returns a picture, which makes it trivial to wire into a small project or even a spreadsheet cell.",
    whyItsGood:
      "Generating an image by editing a web address is a lower barrier than any sign-up form, and it works from anything that can fetch a URL.",
    timeToJoy: "instant",
    vibes: ["useful", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2022,
    altfAlternative: null,
    source: "altf-curated",
  },

  // ── data-made-visible ──────────────────────────────────────────────────────
  {
    slug: "our-world-in-data",
    name: "Our World in Data",
    url: "https://ourworldindata.org/",
    category: "data-made-visible",
    blurb: "Long-run charts on almost every global problem",
    description:
      "Researchers based in Oxford assemble long time series on poverty, health, energy, food and emissions, then publish each one as an interactive chart with the underlying figures downloadable. Charts switch between map, line and table views, and every source is named.",
    whyItsGood:
      "The download button sitting on every single chart is the quiet promise here: you can check the claim rather than take the picture on trust.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "information-is-beautiful",
    name: "Information is Beautiful",
    url: "https://informationisbeautiful.net/",
    category: "data-made-visible",
    blurb: "Design-led charts answering questions tables cannot",
    description:
      "David McCandless and his studio publish visualisations on subjects that resist a spreadsheet: what colours signify in different cultures, which health supplements have evidence behind them, how large a billion actually is. Source data is linked for most graphics.",
    whyItsGood:
      "The balloon race ranking supplements by evidence strength against popularity remains the clearest thing anyone has made on that subject.",
    timeToJoy: "coffee-break",
    vibes: ["beautiful", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2009,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "flowing-data",
    name: "FlowingData",
    url: "https://flowingdata.com/",
    category: "data-made-visible",
    blurb: "Nathan Yau on what the numbers are doing to us",
    description:
      "A long-running visualisation blog alternating between critique of other people's charts and original projects about American life: how people spend their days, when couples meet, how careers end. Tutorials cover the R and D3 work behind each piece.",
    whyItsGood:
      "The day-in-the-life simulations, where thousands of dots move between activities hour by hour, make time-use survey data legible in a way no bar chart manages.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "mesmerising"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2007,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "observable",
    name: "Observable",
    url: "https://observablehq.com/",
    category: "data-made-visible",
    blurb: "Notebooks where the charts recompute as you edit",
    description:
      "A JavaScript notebook environment in which every cell reruns automatically when something it depends on changes, so dragging a slider rebuilds the chart underneath it. Thousands of published notebooks are forkable, covering mapping, statistics and D3 technique.",
    whyItsGood:
      "Forking somebody's published chart and editing their data in the same page collapses the gap between reading a visualisation and making one.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "useful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "gapminder",
    name: "Gapminder",
    url: "https://www.gapminder.org/",
    category: "data-made-visible",
    blurb: "Hans Rosling's bubble chart, still worth an hour",
    description:
      "The animated scatter plot of income against life expectancy, country by country, playable from 1800 to the present. Bubbles are sized by population and drift as the years run. Teaching materials sit alongside it, plus a quiz showing how badly most people estimate global trends.",
    whyItsGood:
      "Pressing play and watching every country climb up and right, then spotting the dips where wars and epidemics hit, makes the argument in fifteen seconds.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "mesmerising"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2005,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "reuters-graphics",
    name: "Reuters Graphics",
    url: "https://www.reuters.com/graphics/",
    category: "data-made-visible",
    blurb: "News stories where the graphic is the reporting",
    description:
      "Reuters' visual team publishes standalone interactive pieces on conflict, shipping, climate and elections, often reconstructing an event in 3D from satellite imagery. The pieces are free to read, and methodology notes set out where each dataset came from.",
    whyItsGood:
      "The reconstructions that rebuild a single incident from satellite passes and ship transponder logs show their working in a way prose cannot.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "data-is-plural",
    name: "Data Is Plural",
    url: "https://www.data-is-plural.com/",
    category: "data-made-visible",
    blurb: "A weekly note listing five datasets you can have",
    description:
      "Jeremy Singer-Vine has published a short newsletter of interesting datasets nearly every week since 2015, now past four hundred editions. Each entry says what the data covers, who assembled it and where to download it. The complete archive is free and searchable.",
    whyItsGood:
      "Entries are picked for being unexpectedly available, so you keep discovering that someone has quietly published the thing you assumed nobody tracked.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "world-bank-open-data",
    name: "World Bank Open Data",
    url: "https://data.worldbank.org/",
    category: "data-made-visible",
    blurb: "Free indicators for every country, back to 1960",
    description:
      "Thousands of development indicators covering economies, population, health, energy and education, each charted per country and downloadable as CSV. Series generally begin in 1960, and the open API behind the site pulls the same numbers straight into a script.",
    whyItsGood:
      "Comparing two countries on the same indicator takes about three clicks, and the CSV that falls out is clean enough to use immediately.",
    timeToJoy: "coffee-break",
    vibes: ["useful", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2010,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "data-census-gov",
    name: "Census Bureau Data Explorer",
    url: "https://data.census.gov/",
    category: "data-made-visible",
    blurb: "The American statistical record, queryable directly",
    description:
      "The United States Census Bureau's public front end, covering population, housing, income, commuting and industry right down to individual census tracts. Filter by geography and topic, then read the table or export it. Margins of error sit beside every published figure.",
    whyItsGood:
      "Pulling median income for one neighbourhood with its margin of error attached is the level of detail most data journalism actually starts from.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "useful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "population-pyramid",
    name: "PopulationPyramid.net",
    url: "https://www.populationpyramid.net/",
    category: "data-made-visible",
    blurb: "Every country's age structure, 1950 to 2100",
    description:
      "One chart per country showing population split by age band and sex, animated across the decades and projected forward to 2100. Countries can be placed side by side for comparison, and the underlying United Nations figures are downloadable.",
    whyItsGood:
      "Running Japan and Nigeria forward together on one axis explains the phrase demographic transition faster than any paragraph about it.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "mesmerising"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "gbd-compare",
    name: "GBD Compare",
    url: "https://vizhub.healthdata.org/gbd-compare/",
    category: "data-made-visible",
    blurb: "A treemap of what people die of, by country and year",
    description:
      "The Institute for Health Metrics publishes its Global Burden of Disease results as an interactive treemap and arrow diagram, broken down by country, age, sex and year. You can watch causes of death and disability trade places as a country's income rises.",
    whyItsGood:
      "The arrow diagram showing which causes climbed the rankings over twenty years is the clearest picture of an epidemiological shift available outside a journal.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "unsettling"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "worldmapper",
    name: "Worldmapper",
    url: "https://worldmapper.org/",
    category: "data-made-visible",
    blurb: "Maps where country size means the actual quantity",
    description:
      "Cartograms that resize each territory according to whatever is being measured, so a map of emissions or olive production looks nothing like a normal atlas. The collection is still growing, with recent additions covering elections, natural disasters and sport.",
    whyItsGood:
      "Watching a familiar continent swell or shrivel depending on the variable makes the geographic argument before you have read a single label.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2006,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "usafacts",
    name: "USAFacts",
    url: "https://usafacts.org/",
    category: "data-made-visible",
    blurb: "US government numbers, assembled without a slant",
    description:
      "A non-partisan project pulling together federal, state and local government data on spending, crime, population and the economy, then presenting each metric as a plain chart with its source cited. Reports state what the numbers show and then stop.",
    whyItsGood:
      "The deliberate absence of commentary is the feature, because it leaves you arguing with the figure rather than with somebody's framing of it.",
    timeToJoy: "coffee-break",
    vibes: ["useful", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2017,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "visual-capitalist",
    name: "Visual Capitalist",
    url: "https://www.visualcapitalist.com/",
    category: "data-made-visible",
    blurb: "One big chart a day, usually about money",
    description:
      "Infographics arrive daily, covering markets, commodities, energy and demographics, generally built as a single tall image you read from top to bottom. Sources are listed beneath each graphic, and the archive is organised by subject rather than by date.",
    whyItsGood:
      "The recurring charts on where the world's metals and money physically sit hand you a mental map that news coverage assumes you already have.",
    timeToJoy: "one-minute",
    vibes: ["useful", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "rawgraphs",
    name: "RAWGraphs",
    url: "https://rawgraphs.io/",
    category: "data-made-visible",
    blurb: "Paste a spreadsheet, drag it into a real chart",
    description:
      "An open-source chart builder that takes pasted or uploaded tabular data and maps columns onto visual properties by dragging. It covers the formats mainstream tools skip, including alluvial diagrams, bump charts, treemaps and beeswarm plots, and exports editable SVG.",
    whyItsGood:
      "The SVG export opens in Illustrator or Figma with every shape still editable, which is why designers treat it as a first step rather than a finished tool.",
    timeToJoy: "coffee-break",
    vibes: ["useful", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "google-dataset-search",
    name: "Google Dataset Search",
    url: "https://datasetsearch.research.google.com/",
    category: "data-made-visible",
    blurb: "A search engine that only returns actual datasets",
    description:
      "An index of datasets published across government portals, universities and research repositories, searchable in plain language. Results display the licence, the last update date and the provider, then link out to wherever the data itself lives.",
    whyItsGood:
      "Filtering by whether the licence permits commercial use saves the hour you would otherwise spend reading terms on a dozen separate portals.",
    timeToJoy: "one-minute",
    vibes: ["useful", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "pew-research",
    name: "Pew Research Center",
    url: "https://www.pewresearch.org/",
    category: "data-made-visible",
    blurb: "Survey findings with all the tables still attached",
    description:
      "Independent, non-partisan survey work on religion, technology, media and demographics, published with the questionnaire, sample sizes and full topline results attached to every report. Charts stay clean, and the methodology section is never buried at the bottom.",
    whyItsGood:
      "Publishing the exact question wording next to the headline number lets you judge whether a finding means what the summary claims it does.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2004,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "poorly-drawn-lines",
    name: "Poorly Drawn Lines",
    url: "https://poorlydrawnlines.com/",
    category: "comedy-department",
    blurb: "Deadpan comics about bears having a difficult week",
    description:
      "Reza Farazmand has been publishing three-panel comics since 2008, usually featuring an animal delivering something bleak in an extremely calm voice. The drawing is deliberately plain, which is what lets the last panel land as hard as it does.",
    whyItsGood:
      "The archive rewards a long scroll: the jokes are short enough that you keep going, and roughly every fifth one is unexpectedly sad.",
    timeToJoy: "one-minute",
    vibes: ["funny", "cosy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2008,
    altfAlternative: null,
    source: "altf-curated",
  },
];

export default sites;
