// packages/core/src/rabbithole/sites/part-1.js
/** Time machines, beautifully useless pages, generative toys, retro revivals. */
const sites = [
  // ---------------------------------------------------------------------------
  // time-machines
  // ---------------------------------------------------------------------------
  {
    slug: "wayback-machine",
    name: "Wayback Machine",
    url: "https://web.archive.org/",
    category: "time-machines",
    blurb: "Type any URL, pick a year, and the old web loads",
    description:
      "The Internet Archive's crawler has been photographing the public web since 1996, and this is the front door to the result. Paste an address, choose a date from the calendar of captures, and the site loads as it stood on that day, with links and images mostly intact.",
    whyItsGood:
      "The calendar view is the real hook: watching a company's homepage redesign itself across twenty years of blue dots is oddly moving.",
    timeToJoy: "one-minute",
    vibes: ["nostalgic", "useful", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2001,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "neocities",
    name: "Neocities",
    url: "https://neocities.org/",
    category: "time-machines",
    blurb: "Free hosting for hand-made pages, GeoCities style",
    description:
      "Kyle Drake rebuilt the old free-hosting model in 2013, handing everyone a slice of space and a plain text editor instead of a template. What grew out of it is a sprawl of hand-coded personal sites with tiled backgrounds, guestbooks and webrings, all browsable from the front page.",
    whyItsGood:
      "Hitting the random-site button lands you on somebody's fan shrine or dream journal that no recommendation algorithm would ever have surfaced.",
    timeToJoy: "rabbit-hole",
    vibes: ["nostalgic", "cosy", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "geocities-gallery",
    name: "GeoCities Gallery",
    url: "https://geocities.restorativland.org/",
    category: "time-machines",
    blurb: "Wander the old GeoCities neighbourhoods, street by street",
    description:
      "GeoCities sorted its users into themed neighbourhoods such as Area51, SiliconValley and Heartland, each with numbered street addresses. This mirror keeps that structure alive, so you pick a neighbourhood and open pages built by strangers in 1998 exactly where they used to live.",
    whyItsGood:
      "Browsing by street address rather than search drops you into the same unpredictable order the original visitors met.",
    timeToJoy: "rabbit-hole",
    vibes: ["nostalgic", "weird"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: null,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "one-terabyte-of-kilobyte-age",
    name: "One Terabyte of Kilobyte Age",
    url: "https://blog.geocities.institute/",
    category: "time-machines",
    blurb: "A bot posts one dead GeoCities page every twenty minutes",
    description:
      "Olia Lialina and Dragan Espenschied screenshot pages from the rescued GeoCities backup and publish them on a timer, background tiles and animated dividers included. Sitting alongside the images are essays picking apart what amateur web design of the period actually meant.",
    whyItsGood:
      "Each screenshot is rendered in a period-correct browser, so the broken layouts break in exactly the way they broke in 1999.",
    timeToJoy: "coffee-break",
    vibes: ["nostalgic", "brainy", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "camerons-world",
    name: "Cameron's World",
    url: "https://www.cameronsworld.net/",
    category: "time-machines",
    blurb: "A collage built entirely from salvaged GeoCities parts",
    description:
      "Cameron Askin cut thousands of images and animated GIFs out of archived GeoCities pages, then reassembled them into one long scrolling collage backed by MIDI. Every under-construction sign, spinning envelope and dancing baby is a genuine salvaged artefact rather than a pastiche.",
    whyItsGood:
      "Clicking the small speaker icon starts the MIDI soundtrack, which turns the whole thing from an art piece into a séance.",
    timeToJoy: "one-minute",
    vibes: ["nostalgic", "beautiful", "weird"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "web-design-museum",
    name: "Web Design Museum",
    url: "https://www.webdesignmuseum.org/",
    category: "time-machines",
    blurb: "Screenshots of the web's biggest sites, year by year",
    description:
      "This Czech project keeps thousands of full-page screenshots of well-known websites from the mid-1990s onward, filed by year and by brand. Curated exhibitions trace particular themes, such as the rise of the skeuomorphic button or how every airline homepage looked in 2003.",
    whyItsGood:
      "Lining up Amazon's homepage from 1999, 2004 and 2011 shows the exact moment the web stopped being a page and became a product.",
    timeToJoy: "coffee-break",
    vibes: ["nostalgic", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2017,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "version-museum",
    name: "Version Museum",
    url: "https://www.versionmuseum.com/",
    category: "time-machines",
    blurb: "Step through a famous site as it redesigns itself",
    description:
      "Version Museum lines up the visual history of software and websites, from early Google through successive releases of macOS and Photoshop. Each entry is a set of clean, annotated screenshots you step through in order, with notes on what changed and roughly when it happened.",
    whyItsGood:
      "The side-by-side layout catches details nobody noticed at the time, such as how long Facebook clung to that thin blue bar.",
    timeToJoy: "coffee-break",
    vibes: ["nostalgic", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "gifcities",
    name: "GifCities",
    url: "https://gifcities.org/",
    category: "time-machines",
    blurb: "Search every animated GIF GeoCities ever hosted",
    description:
      "Built by the Internet Archive for its twentieth birthday, GifCities indexes the animated GIFs recovered from GeoCities user pages. Type a word and back comes a grid of jittering, dithered, 216-colour results, each one linking to the archived page it was pulled from.",
    whyItsGood:
      "Searching something mundane like 'email' returns forty different spinning envelopes, which is a fair summary of the entire era.",
    timeToJoy: "instant",
    vibes: ["nostalgic", "funny", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "the-old-net",
    name: "TheOldNet",
    url: "https://theoldnet.com/",
    category: "time-machines",
    blurb: "Surf archived pages inside a fake 1990s browser window",
    description:
      "TheOldNet wraps the Internet Archive in period browser chrome and strips modern markup, so old captures render roughly the way they were meant to. There is a pick-a-year address bar, a directory of era-appropriate links, and a setting that throttles you back to dial-up speed.",
    whyItsGood:
      "The optional 14.4k throttle is the detail that lands: images paint downward in strips while you sit and wait for them.",
    timeToJoy: "one-minute",
    vibes: ["nostalgic", "weird"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "oldweb-today",
    name: "oldweb.today",
    url: "https://oldweb.today/",
    category: "time-machines",
    blurb: "Load archived pages in a real, emulated Netscape",
    description:
      "Rather than approximating a vintage browser, oldweb.today boots an actual one, whether Netscape, Mosaic or an early Internet Explorer, inside a container and points it at archived captures. You get the genuine chrome, the genuine bugs and the genuine rendering engine.",
    whyItsGood:
      "Watching Mosaic choke on a table layout is a far more honest history lesson than any screenshot could manage.",
    timeToJoy: "one-minute",
    vibes: ["nostalgic", "brainy", "weird"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "space-jam-1996",
    name: "Space Jam (1996)",
    url: "https://www.spacejam.com/1996/",
    category: "time-machines",
    blurb: "The original 1996 film site, never taken down",
    description:
      "Warner Bros left the promotional site for the first Space Jam online and untouched for a quarter of a century, and when the sequel arrived it was moved into a subfolder rather than deleted. Star-field background, tiny orbiting nav buttons and a press box of 1996 HTML all survive.",
    whyItsGood:
      "The Junior Jam section still offers to teach you how to build a Space Jam screensaver for Windows 95.",
    timeToJoy: "instant",
    vibes: ["nostalgic", "funny"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 1996,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "dole-kemp-96",
    name: "Dole Kemp '96",
    url: "https://www.dolekemp96.org/",
    category: "time-machines",
    blurb: "A 1996 US campaign website, preserved exactly as it was",
    description:
      "The Dole and Kemp campaign site has been kept online in its original form since the 1996 election, hosted deliberately as a historical record rather than by accident. Frames, low-resolution photographs and pages inviting you to download position papers are all still in place.",
    whyItsGood:
      "One page patiently explains what the internet is and why a campaign might want a website, which dates it better than the design does.",
    timeToJoy: "instant",
    vibes: ["nostalgic", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 1996,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "wiby",
    name: "Wiby",
    url: "https://wiby.me/",
    category: "time-machines",
    blurb: "A search engine that only indexes small, simple pages",
    description:
      "Wiby crawls a hand-tended set of lightweight, mostly personal websites and deliberately leaves the commercial web out. Searches return plain HTML pages about ham radio, cooking or obscure hardware, and a surprise button throws you at a random one of them.",
    whyItsGood:
      "That surprise button is the whole point: it reliably finds a 2003 page by a retired engineer about restoring one specific lathe.",
    timeToJoy: "instant",
    vibes: ["nostalgic", "cosy", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "internet-artifacts",
    name: "Internet Artifacts",
    url: "https://neal.fun/internet-artifacts/",
    category: "time-machines",
    blurb: "Scroll the internet's objects, from 1977 to 2007",
    description:
      "Neal Agarwal laid out internet history as a museum of clickable objects, opening with an ARPANET map and closing in the early social era. Each artefact expands into a working fragment, whether that is the first webcam feed, an early banner advert or a Napster window mid-download.",
    whyItsGood:
      "Several exhibits are interactive rather than photographs, so you can poke at the first web page and trigger the original ICQ noise.",
    timeToJoy: "coffee-break",
    vibes: ["nostalgic", "brainy", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2024,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "million-dollar-homepage",
    name: "The Million Dollar Homepage",
    url: "https://www.milliondollarhomepage.com/",
    category: "time-machines",
    blurb: "A million pixels sold in 2005, still hanging there",
    description:
      "Alex Tew sold advertising space on a single page at a dollar per pixel and cleared a million dollars in four months. Nothing has been touched since, so the grid now works as a map of 2005 web commerce in which most of the tiny logos point at domains that no longer resolve.",
    whyItsGood:
      "Hovering across the blocks turns it into an accidental link-rot experiment, with roughly half of 2005's startups quietly gone.",
    timeToJoy: "one-minute",
    vibes: ["nostalgic", "weird", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2005,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "discmaster",
    name: "Discmaster",
    url: "https://discmaster.textfiles.com/",
    category: "time-machines",
    blurb: "Full-text search across thousands of old shareware discs",
    description:
      "Discmaster indexes the contents of vintage CD-ROMs and floppy collections held by the Internet Archive, converting what it finds so that it opens in a browser. Search a filename, a MIDI, a 1994 clip-art bundle or a shareware game and play it without touching an emulator.",
    whyItsGood:
      "Searching by file type alone, say every WAV on every 1996 disc, surfaces sound effects nobody has heard in thirty years.",
    timeToJoy: "rabbit-hole",
    vibes: ["nostalgic", "brainy", "weird"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2022,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "museum-of-endangered-sounds",
    name: "Museum of Endangered Sounds",
    url: "https://savethesounds.info/",
    category: "time-machines",
    blurb: "Click the old hardware to hear it one more time",
    description:
      "Brendan Chilcutt's collection gathers noises that specific machines used to make: the dial-up handshake, a Nokia ringtone, a Tamagotchi, the clunk of a VHS tape seating itself. Each device sits on the page as an icon and plays on click, loops and all.",
    whyItsGood:
      "Starting the Windows 95 chime and the dial-up handshake at the same time produces a very particular memory ambush.",
    timeToJoy: "one-minute",
    vibes: ["nostalgic", "cosy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2012,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "spacehey",
    name: "SpaceHey",
    url: "https://spacehey.com/",
    category: "time-machines",
    blurb: "MySpace rebuilt from scratch, top eight friends included",
    description:
      "A German teenager rebuilt the 2006 MySpace experience as a working social network, with profile HTML you edit yourself, a top-friends list and layouts held together by glitter graphics. Browsing profiles and the layout gallery is open to anyone, though posting needs a free account.",
    whyItsGood:
      "Custom CSS is left unrestricted, so profiles genuinely look like 2006 again, cursor trails and autoplaying songs included.",
    timeToJoy: "coffee-break",
    vibes: ["nostalgic", "cosy", "wholesome"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2020,
    altfAlternative: null,
    source: "altf-curated",
  },

  // ---------------------------------------------------------------------------
  // beautiful-useless
  // ---------------------------------------------------------------------------
  {
    slug: "zoomquilt",
    name: "Zoomquilt",
    url: "https://zoomquilt.org/",
    category: "beautiful-useless",
    blurb: "A painting that falls forever into itself",
    description:
      "A collaborative artwork stitched into an infinite loop: scroll in and the canvas keeps descending through forest, ruins and sky, seamlessly returning to where it started. There is no interface beyond the scroll wheel and no end to reach.",
    whyItsGood:
      "The seams are genuinely invisible. You can watch for the join for several minutes and never catch it.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2004,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "the-useless-web",
    name: "The Useless Web",
    url: "https://theuselessweb.com/",
    category: "beautiful-useless",
    blurb: "One button, one random pointless website, forever",
    description:
      "Tim Holman's page holds a single button that fires you at a randomly chosen useless website, then offers another button to do it all again. The list behind it is hand-picked, so results skew towards genuinely odd one-page projects rather than spam.",
    whyItsGood:
      "Because the pool is curated instead of scraped, the third or fourth click usually lands somewhere you would never have found deliberately.",
    timeToJoy: "instant",
    vibes: ["funny", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "zombo",
    name: "Zombo.com",
    url: "https://zombo.com/",
    category: "beautiful-useless",
    blurb: "You can do anything at Zombo.com. Anything at all",
    description:
      "A voice over a swirling gradient explains, at length and with total sincerity, that the only limit here is yourself. The site has been making this promise since 1999 without ever shipping a feature, and it survived the death of Flash by being rebuilt in HTML5.",
    whyItsGood:
      "The monologue keeps going if you leave it running, drifting into improvised reassurances most visitors never stay long enough to hear.",
    timeToJoy: "instant",
    vibes: ["funny", "weird"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 1999,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "pointer-pointer",
    name: "Pointer Pointer",
    url: "https://pointerpointer.com/",
    category: "beautiful-useless",
    blurb: "Put your cursor anywhere and someone points at it",
    description:
      "Move the mouse, wait a beat, and up comes a photograph of a real person pointing directly at your cursor position. The studio behind it shot hundreds of images of people pointing at every part of a grid, so the match is close to exact wherever you leave it.",
    whyItsGood:
      "The delight is in testing the corners, where the photographs get increasingly contorted to reach the spot you chose.",
    timeToJoy: "instant",
    vibes: ["funny", "weird"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2012,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "lings-cars",
    name: "Ling's Cars",
    url: "https://www.lingscars.com/",
    category: "beautiful-useless",
    blurb: "A real car leasing firm behind the loudest site online",
    description:
      "Ling Valentine runs a genuine UK vehicle leasing business, and her website is a deliberate assault of animated GIFs, autoplaying MIDI, tiled dragons and flashing tables. Underneath the chaos sits a working quote system that has moved a very large number of cars.",
    whyItsGood:
      "Knowing it functions as a real business is what makes it art rather than parody: the noise is a customer filter, not an accident.",
    timeToJoy: "instant",
    vibes: ["funny", "weird", "nostalgic"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2000,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "koalas-to-the-max",
    name: "Koalas to the Max",
    url: "https://www.koalastothemax.com/",
    category: "beautiful-useless",
    blurb: "Split circles into smaller circles until an image appears",
    description:
      "You begin with one enormous dot. Sweeping the cursor over it splits it into four, then sixteen, then sixty-four, and after a few thousand subdivisions the colours resolve into a hidden picture. Feed it your own image through the address bar if you like.",
    whyItsGood:
      "The moment the pattern stops reading as abstract colour and snaps into a recognisable koala is satisfying every single time.",
    timeToJoy: "one-minute",
    vibes: ["mesmerising", "calming", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "hacker-typer",
    name: "Hacker Typer",
    url: "https://hackertyper.net/",
    category: "beautiful-useless",
    blurb: "Mash the keyboard, produce convincing green code",
    description:
      "Type any nonsense at all and the screen fills with plausible-looking source code at a steady rate, regardless of which keys you actually pressed. Hit Alt or Caps Lock three times and an ACCESS GRANTED or ACCESS DENIED panel slams over the top of it.",
    whyItsGood:
      "Typing speed is deliberately decoupled from your input, so even two fingers produce the frantic cadence of a film hacker.",
    timeToJoy: "instant",
    vibes: ["funny", "nostalgic"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: "geektyper",
    source: "altf-curated",
  },
  {
    slug: "paper-toilet",
    name: "Paper Toilet",
    url: "https://papertoilet.com/",
    category: "beautiful-useless",
    blurb: "Scroll a roll of toilet paper. That is the whole site",
    description:
      "A roll hangs at the top of the page and unspools as you scroll, sheet after perforated sheet, rendered convincingly enough that you keep going. Scroll back up and it rewinds itself onto the roll. Nothing waits for you at the bottom.",
    whyItsGood:
      "The perforation lines and the slight flutter of the paper as it unrolls are modelled far more carefully than the joke requires.",
    timeToJoy: "instant",
    vibes: ["funny", "calming", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "has-the-lhc-destroyed-the-world-yet",
    name: "Has the Large Hadron Collider Destroyed the World Yet?",
    url: "https://hasthelargehadroncolliderdestroyedtheworldyet.com/",
    category: "beautiful-useless",
    blurb: "One word answers physics' most alarming question",
    description:
      "The page answers its own domain name with a single word, NOPE, set in enormous type, and has done so continuously since the collider was switched on in 2008. Viewing the page source turns up a comment explaining what the site would say if the answer ever changed.",
    whyItsGood:
      "There is contingency copy for the end of the world hidden in the markup, which is a level of commitment few one-joke sites reach.",
    timeToJoy: "instant",
    vibes: ["funny", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2008,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "pixels-fighting",
    name: "Pixels Fighting",
    url: "https://pixelsfighting.com/",
    category: "beautiful-useless",
    blurb: "Two colours wage war across a grid until one wins",
    description:
      "The screen splits into thousands of squares, half one colour and half another, and every square flips to match its neighbours. Territories advance, retreat and fracture into islands, and because it starts from a random split the outcome differs on every reload.",
    whyItsGood:
      "Neither side ever wins cleanly, and watching a doomed pocket of blue hold out in one corner is unreasonably tense.",
    timeToJoy: "one-minute",
    vibes: ["mesmerising", "competitive", "weird"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "falling-falling",
    name: "Falling Falling",
    url: "https://www.fallingfalling.com/",
    category: "beautiful-useless",
    blurb: "An endless descent through shifting bands of colour",
    description:
      "Three layers of coloured stripes fall past each other at different speeds beneath a low drone, and never arrive anywhere at all. Clicking cycles the palette between harsh neon and softer washes, and the whole thing is built to be left running in the background.",
    whyItsGood:
      "Put it full screen and look away for a minute: the room genuinely feels like it has started moving, which no static wallpaper manages.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "unsettling", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "make-everything-ok",
    name: "Make Everything OK",
    url: "https://make-everything-ok.com/",
    category: "beautiful-useless",
    blurb: "One button. Press it and everything is made OK",
    description:
      "One button sits in the middle of an otherwise empty page, under a promise. Press it and a progress bar works through tasks such as fixing the past and adjusting the future, then reports that everything is now OK and disables the button so you cannot ask a second time.",
    whyItsGood:
      "The button greys out afterwards on the reasoning that everything is already OK, and asking again would simply be greedy.",
    timeToJoy: "instant",
    vibes: ["funny", "calming", "wholesome"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "zoomquilt-two",
    name: "Zoomquilt II",
    url: "https://zoomquilt2.com/",
    category: "beautiful-useless",
    blurb: "The sequel loop: colder, stranger, equally seamless",
    description:
      "A second collaborative infinite zoom from a different group of painters, running the same trick as the original but through caverns, machinery and drifting figures in a much colder palette. It will also run on a timer if you would rather not scroll.",
    whyItsGood:
      "Its transitions hide inside architecture rather than foliage, which makes the joins even harder to catch than in the first one.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "unsettling", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2007,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "cachemonet",
    name: "CacheMonet",
    url: "https://cachemonet.com/",
    category: "beautiful-useless",
    blurb: "Every GIF at once, with a soundtrack, on purpose",
    description:
      "Layers of animated GIFs stack over each other in constant motion, sunsets and dolphins and wireframe grids and cats, while a chiptune track plays underneath. Nothing is clickable, nothing is explained, and reloading gives you a different pile of it.",
    whyItsGood:
      "It is the closest anyone has come to rendering the whole of 2013 Tumblr as a single page you can stand and stare at.",
    timeToJoy: "instant",
    vibes: ["weird", "mesmerising", "nostalgic"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "passive-aggressive-password-machine",
    name: "The Passive Aggressive Password Machine",
    url: "https://trypap.com/",
    category: "beautiful-useless",
    blurb: "A password field that quietly judges you as you type",
    description:
      "Type a password into the box and a cartoon face reacts in real time, sighing at anything short and brightening very slightly when you finally add a symbol. Nothing is stored or sent anywhere, and nothing you enter will make it fully approve of you.",
    whyItsGood:
      "The face manages genuine visible disappointment at 'password1', which lands harder than any strength meter ever has.",
    timeToJoy: "instant",
    vibes: ["funny", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "hampsterdance",
    name: "The Hampster Dance",
    url: "https://www.hampsterdance.com/",
    category: "beautiful-useless",
    blurb: "The 1998 meme that outlived the entire early web",
    description:
      "Rows of animated hamsters bounce in time to a sped-up sample from Disney's Robin Hood, exactly as they did when this became one of the first pages to properly go viral. Ownership and hosting have changed several times, but the loop itself is unchanged.",
    whyItsGood:
      "The audio still starts on its own the moment the page loads, which in 2026 reads as an act of defiance.",
    timeToJoy: "instant",
    vibes: ["funny", "nostalgic", "wholesome"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 1998,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "fodey-newspaper-generator",
    name: "Fodey Newspaper Generator",
    url: "https://www.fodey.com/generators/newspaper/snippet.asp",
    category: "beautiful-useless",
    blurb: "Type a headline, get a passable newspaper clipping",
    description:
      "Fill in a masthead, a headline and a couple of paragraphs, and the page hands back an image of a folded newspaper cutting with your text set into it. The rest of the site does the same trick for talking animals, ticker tapes and cinema marquees.",
    whyItsGood:
      "The paper grain and the soft fold shadow are convincing enough that these clippings have been fooling people for two decades.",
    timeToJoy: "one-minute",
    vibes: ["funny", "nostalgic"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2006,
    altfAlternative: "fodey-new",
    source: "altf-curated",
  },
  {
    slug: "google-gravity",
    name: "Google Gravity",
    url: "https://mrdoob.com/projects/chromeexperiments/google-gravity/",
    category: "beautiful-useless",
    blurb: "The Google homepage collapses into a heap on load",
    description:
      "Ricardo Cabello's experiment gives every element of a 2009 Google homepage physical mass, so the logo, buttons and search box tumble to the bottom of the window on arrival. You can still type a query, then drag the wreckage around and throw it at the walls.",
    whyItsGood:
      "Search genuinely still works from inside the pile, and the results page falls over as soon as it appears.",
    timeToJoy: "instant",
    vibes: ["funny", "nostalgic", "weird"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2009,
    altfAlternative: null,
    source: "altf-curated",
  },

  // ---------------------------------------------------------------------------
  // generative-toys
  // ---------------------------------------------------------------------------
  {
    slug: "patatap",
    name: "Patatap",
    url: "https://www.patatap.com/",
    category: "generative-toys",
    blurb: "Every key on your keyboard is a sound and a shape",
    description:
      "Jono Brandel and Lullatone mapped each letter key to a percussive sound and a matching burst of animation on a plain coloured field. Tapping the space bar shifts the whole palette and swaps the sound kit, so the same keys become an entirely different instrument.",
    whyItsGood:
      "Each animation is timed to the attack of its sample, so drumming out a rhythm reads as choreography rather than decoration.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: "patatap",
    source: "listicle",
  },
  {
    slug: "neon-flames",
    name: "Neon Flames",
    url: "https://29a.ch/sandbox/2011/neonflames/",
    category: "generative-toys",
    blurb: "Paint with fire that keeps burning after you stop",
    description:
      "Jonas Wagner's particle sandbox turns cursor movement into a stream of glowing embers that drift, cool and fade out against black. Sliders control the colour range, particle count and gravity, and a save button drops whatever you made out as an image.",
    whyItsGood:
      "Trails keep evolving for several seconds after you lift the mouse, so a quick flick leaves a shape you did not quite draw yourself.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "beautiful", "calming"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "gravity-points",
    name: "Gravity Points",
    url: "https://codepen.io/akm2/full/AGgarW",
    category: "generative-toys",
    blurb: "Click to drop a star and watch particles fall in",
    description:
      "Each click places a point of gravity on the canvas, and thousands of small particles bend towards it in long trailing arcs. Place several and they compete for the same material, forming orbits and streams that collapse the moment one point starts to win.",
    whyItsGood:
      "Two points set at the right distance produce a stable figure-of-eight that holds for a surprisingly long time before it tears apart.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "this-is-sand",
    name: "This Is Sand",
    url: "https://thisissand.com/",
    category: "generative-toys",
    blurb: "Pour coloured sand and let it pile up in drifts",
    description:
      "Hold the mouse down and grains stream onto the canvas, settling into slopes at a believable angle of repose. Colour shifts gradually as you pour, so long strokes come out as gradients, and a public gallery collects what other people have built.",
    whyItsGood:
      "Burying an old layer and then eroding it away again reveals the earlier colours underneath in bands, like a cliff face.",
    timeToJoy: "one-minute",
    vibes: ["calming", "mesmerising", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2012,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "chrome-music-lab-song-maker",
    name: "Chrome Music Lab: Song Maker",
    url: "https://musiclab.chromeexperiments.com/Song-Maker/",
    category: "generative-toys",
    blurb: "Click a grid of squares and it becomes a melody",
    description:
      "A pitch grid sits above a rhythm grid, and clicking cells builds a loop that plays back straight away with no theory required. Scale, tempo and instrument are all adjustable, and finished songs encode into a URL that reopens with your work intact.",
    whyItsGood:
      "Restricting the grid to a pentatonic scale by default means almost anything you click sounds deliberate.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "wholesome", "calming"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2017,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "bomomo",
    name: "Bomomo",
    url: "https://bomomo.com/",
    category: "generative-toys",
    blurb: "Sixteen strange brushes and almost no control",
    description:
      "Bomomo swaps normal painting tools for a row of unpredictable ones: swarms of dots that chase the cursor, elastic ribbons, sprays that pulse in and out. You drag, the brush misbehaves in its own particular way, and the result saves out as a PNG.",
    whyItsGood:
      "Every brush has its own physics, so working out what the wobbling tentacle one does takes ten seconds and is immediately worth it.",
    timeToJoy: "instant",
    vibes: ["beautiful", "weird", "calming"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2008,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "webgl-fluid-simulation",
    name: "WebGL Fluid Simulation",
    url: "https://paveldogreat.github.io/WebGL-Fluid-Simulation/",
    category: "generative-toys",
    blurb: "Drag your cursor through coloured smoke that swirls back",
    description:
      "Pavel Dobryakov's shader runs a real fluid solver at full frame rate, so dragging the pointer injects both dye and momentum that curl away into vortices. A hidden settings panel exposes dissipation, vorticity and bloom for anyone who wants to push it further.",
    whyItsGood:
      "Flicking the cursor quickly and then stopping leaves a genuine vortex spinning on, slowly eating its own dye.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "beautiful", "calming"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2017,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "tonematrix",
    name: "ToneMatrix",
    url: "https://tonematrix.audiotool.com/",
    category: "generative-toys",
    blurb: "A grid of squares where nothing you play sounds wrong",
    description:
      "Audiotool's sequencer is a sixteen-by-sixteen grid tuned to a pentatonic scale, with a playhead sweeping steadily from left to right. Lighting up a cell makes it chime and sends a ripple outwards across the surrounding squares, so the grid behaves like water.",
    whyItsGood:
      "The ripple animation lets you see the rhythm as interference patterns a moment before you hear it.",
    timeToJoy: "instant",
    vibes: ["calming", "mesmerising"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2009,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "typatone",
    name: "Typatone",
    url: "https://www.typatone.com/",
    category: "generative-toys",
    blurb: "Write a sentence and hear the note each letter makes",
    description:
      "From the people behind Patatap, this turns typing into composition: every character triggers a tone from a chosen key, so writing a paragraph produces a melody shaped by your rhythm and your pauses. Finished pieces can be saved and shared as a link.",
    whyItsGood:
      "Notes follow your typing speed exactly, so a message you are struggling to write sounds audibly more hesitant than one you are not.",
    timeToJoy: "instant",
    vibes: ["calming", "beautiful", "mesmerising"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: "patatap",
    source: "altf-curated",
  },
  {
    slug: "incredibox",
    name: "Incredibox",
    url: "https://www.incredibox.com/demo/",
    category: "generative-toys",
    blurb: "Drag sounds onto beatboxers and build a track",
    description:
      "A row of hooded characters waits on stage, and dragging an icon onto one gives them a beat, a bassline, an effect or a vocal line. Layers lock to the same tempo automatically, and finding the right combination unlocks an animated chorus sequence.",
    whyItsGood:
      "The bonus animations are hidden behind specific combinations, which quietly turns idle mixing into a hunt.",
    timeToJoy: "one-minute",
    vibes: ["wholesome", "funny", "mesmerising"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2009,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "line-rider",
    name: "Line Rider",
    url: "https://www.linerider.com/",
    category: "generative-toys",
    blurb: "Draw a hill and a small sledder rides whatever you drew",
    description:
      "Sketch lines with the pencil, press play, and a figure on a toboggan follows them under gravity with no way to steer. Accelerator lines and decorative scenery lines let you build long courses, and any track can be exported and handed to somebody else.",
    whyItsGood:
      "The rider comes off at the slightest bad angle, so a track that actually works feels earned rather than merely drawn.",
    timeToJoy: "coffee-break",
    vibes: ["mesmerising", "competitive", "nostalgic"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2006,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "zen-photon-garden",
    name: "Zen Photon Garden",
    url: "https://zenphoton.com/",
    category: "generative-toys",
    blurb: "Draw walls and let a million photons find their way",
    description:
      "Micah Scott's ray tracer opens with a single light source in total darkness. Every line you draw becomes a mirror, a diffuse wall or a transparent pane, and the renderer keeps firing photons until the caustics and shadows resolve into something photographic.",
    whyItsGood:
      "Leaving it alone for a minute after you stop drawing is when the soft bounced light settles and the image turns beautiful.",
    timeToJoy: "one-minute",
    vibes: ["calming", "beautiful", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "bongo-cat",
    name: "Bongo Cat",
    url: "https://bongo.cat/",
    category: "generative-toys",
    blurb: "A cat plays whatever instrument you hit keys for",
    description:
      "The meme cat sits behind a pair of bongos, and each key on your keyboard maps to a drum, a cymbal or a note. Swap the kit for a keyboard, a guitar or a saxophone, and there is a shared room where several people can play the same cat at once.",
    whyItsGood:
      "Paws are animated per key rather than on a loop, so fast playing produces genuinely frantic limb movement in time with you.",
    timeToJoy: "instant",
    vibes: ["funny", "wholesome"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: "patatap",
    source: "altf-curated",
  },
  {
    slug: "harmony-drawing-tool",
    name: "Harmony",
    url: "https://mrdoob.com/projects/harmony/",
    category: "generative-toys",
    blurb: "A sketch tool whose brushes join up your strokes",
    description:
      "Brushes here behave like nothing in a normal paint program: sketchy ones that link nearby strokes with fine hairlines, plus ribbons, fur and a shaded pencil. Built by the developer known as Mr.doob, it makes output look hand-drawn even when you cannot draw at all.",
    whyItsGood:
      "The sketchy brush connects your strokes to each other automatically, which turns a wobbly circle into a deliberate architectural study.",
    timeToJoy: "instant",
    vibes: ["beautiful", "calming"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2009,
    altfAlternative: "sketchflow",
    source: "altf-curated",
  },
  {
    slug: "fluid-paint",
    name: "Fluid Paint",
    url: "https://david.li/paint/",
    category: "generative-toys",
    blurb: "Thick oil paint that smears and mixes like the real thing",
    description:
      "David Li simulates wet paint on canvas, complete with height, sheen and proper pigment mixing. Loading the brush and dragging leaves ridges that catch the light, and running dry mid-stroke thins the line exactly the way a real brush would.",
    whyItsGood:
      "Pulling a clean brush through two wet colours produces genuine marbling rather than a flat blend of two RGB values.",
    timeToJoy: "one-minute",
    vibes: ["beautiful", "calming", "mesmerising"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "jackson-pollock-org",
    name: "JacksonPollock.org",
    url: "https://www.jacksonpollock.org/",
    category: "generative-toys",
    blurb: "Fling paint across a white wall with your mouse",
    description:
      "Miltos Manetas turned drip painting into a browser toy: moving the cursor trails paint, and moving it fast throws splatters right across the canvas. Clicking changes colour at random, and there is no menu, no undo and no way to save what you did.",
    whyItsGood:
      "Speed controls the line weight, so a slow sweep leaves a thin thread and a sharp flick throws a real spatter.",
    timeToJoy: "instant",
    vibes: ["beautiful", "calming", "weird"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2003,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "beepbox",
    name: "BeepBox",
    url: "https://www.beepbox.co/",
    category: "generative-toys",
    blurb: "A chiptune sequencer that fits a whole song in a URL",
    description:
      "BeepBox is a small tracker for writing bleepy loops, with separate channels for lead, harmony, bass and drums and a waveform selector for each one. Every note you place is encoded into the address bar, so sharing a song means sharing a link and nothing else.",
    whyItsGood:
      "With the whole composition living in the URL, somebody can open your song, change eight notes and send it straight back to you.",
    timeToJoy: "coffee-break",
    vibes: ["nostalgic", "brainy", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "turtletoy",
    name: "Turtletoy",
    url: "https://turtletoy.net/",
    category: "generative-toys",
    blurb: "A tiny turtle draws whatever code you feed it",
    description:
      "Turtletoy runs single-line generative drawings written in a stripped-back JavaScript, using the old turtle graphics model of pen, angle and distance. Every piece on the site is editable in place, so you can open somebody's spiral and change one number in it.",
    whyItsGood:
      "The forkable code sitting next to every drawing turns passive browsing into tinkering within about a minute.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "beautiful", "mesmerising"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: null,
    source: "altf-curated",
  },

  // ---------------------------------------------------------------------------
  // pixel-nostalgia
  // ---------------------------------------------------------------------------
  {
    slug: "windows93",
    name: "Windows 93",
    url: "https://www.windows93.net/",
    category: "pixel-nostalgia",
    blurb: "An OS that never existed, full of cursed little apps",
    description:
      "Windows 93 boots into a desktop somewhere between Windows 3.1 and a fever dream, with working windows, a Start menu and dozens of small programs. Some are jokes, some are real, and there is a Solitaire, a terminal and a folder of things that crash on purpose.",
    whyItsGood:
      "Opening Cat Explorer or the piano app reveals properly finished little programs hiding inside what looks like a one-note gag.",
    timeToJoy: "coffee-break",
    vibes: ["weird", "nostalgic", "funny"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "v86",
    name: "v86",
    url: "https://copy.sh/v86/",
    category: "pixel-nostalgia",
    blurb: "Boot Windows 95, Linux or FreeDOS inside a browser tab",
    description:
      "Fabian Hemmer's x86 emulator runs real operating system images in JavaScript, and the demo page offers a menu of them stretching from Windows 1.01 to Windows 98 to several small Linux builds. Disks are pre-loaded, so there is nothing to configure.",
    whyItsGood:
      "This is not a mock-up: you can open the real Windows 98 Control Panel and break the real registry from inside a browser tab.",
    timeToJoy: "one-minute",
    vibes: ["nostalgic", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2012,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "infinite-mac",
    name: "Infinite Mac",
    url: "https://infinitemac.org/",
    category: "pixel-nostalgia",
    blurb: "Every classic Mac OS, booting in seconds, discs included",
    description:
      "Mihai Parparita packaged System 1 through Mac OS 9 as instant-loading browser emulators, each with a hard disk full of period software. Pick a year, land in a working Finder, and open HyperCard, Kid Pix or Marathon without downloading a single file.",
    whyItsGood:
      "Dragging a file from your own desktop into the window actually mounts it inside the emulated Mac.",
    timeToJoy: "one-minute",
    vibes: ["nostalgic", "cosy", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2022,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "msdos-games-library",
    name: "Internet Archive MS-DOS Games",
    url: "https://archive.org/details/softwarelibrary_msdos_games",
    category: "pixel-nostalgia",
    blurb: "Thousands of DOS games, playable inside the page",
    description:
      "Several thousand MS-DOS titles sit in the Internet Archive's software library running through an in-browser DOSBox, from Prince of Persia and Oregon Trail down to shareware nobody remembers. Click a cover, let the emulator warm up for a moment, and press a key.",
    whyItsGood:
      "The long tail is the real prize: forgotten shareware with three ratings is often stranger than any of the famous titles.",
    timeToJoy: "coffee-break",
    vibes: ["nostalgic", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: "altfgame",
    source: "altf-curated",
  },
  {
    slug: "winxp-in-react",
    name: "WinXP in React",
    url: "https://winxp.vercel.app/",
    category: "pixel-nostalgia",
    blurb: "Bliss wallpaper, Luna taskbar, working Minesweeper",
    description:
      "A careful reconstruction of the Windows XP desktop in the browser, from the Luna theme's rounded blue taskbar to the two-column Start menu. Notepad, Paint, Minesweeper and a stand-in Internet Explorer all open in draggable, resizable windows.",
    whyItsGood:
      "Window shadows, the Start menu gradient and the log-off dialogue are pixel-accurate rather than merely approximate.",
    timeToJoy: "instant",
    vibes: ["nostalgic", "cosy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "windows96",
    name: "Windows 96",
    url: "https://windows96.net/",
    category: "pixel-nostalgia",
    blurb: "A fictional 90s OS with far too much software in it",
    description:
      "Windows 96 is an invented operating system built as a full web desktop, with its own file system, app store, media player and multi-user chat. Development has run for years, so the bundled software is genuinely deep rather than decorative.",
    whyItsGood:
      "A working music sequencer and a text adventure engine live inside a fake operating system, which is a strange amount of effort in the best way.",
    timeToJoy: "coffee-break",
    vibes: ["weird", "nostalgic", "cosy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "emupedia-emuos",
    name: "Emupedia EmuOS",
    url: "https://emupedia.net/beta/emuos/",
    category: "pixel-nostalgia",
    blurb: "A Windows 98 desktop stocked with era-correct games",
    description:
      "EmuOS recreates a late-90s Windows desktop and fills it with what a school computer would have had: Minesweeper, Chip's Challenge, Encarta, flying-object screensavers and a folder of DOS games running in emulators. Everything launches from the Start menu.",
    whyItsGood:
      "The Program Files folder is stocked exactly as a 1999 family PC would have been, right down to the demo discs.",
    timeToJoy: "coffee-break",
    vibes: ["nostalgic", "cosy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: "games",
    source: "altf-curated",
  },
  {
    slug: "ninety-eight-js",
    name: "98.js",
    url: "https://98.js.org/",
    category: "pixel-nostalgia",
    blurb: "Windows 98 rebuilt in JavaScript, down to the fonts",
    description:
      "Isaiah Odhner reimplemented the Windows 98 shell in the browser, with a real Start menu, working window management and versions of Notepad, Paint and Minesweeper. Sound effects, dialogue boxes and the shutdown screen are all reproduced faithfully.",
    whyItsGood:
      "Right-clicking the desktop opens the genuine 98 context menu, Active Desktop options included, and they still do something.",
    timeToJoy: "instant",
    vibes: ["nostalgic", "cosy", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "jspaint",
    name: "JS Paint",
    url: "https://jspaint.app/",
    category: "pixel-nostalgia",
    blurb: "MS Paint, faithfully rebuilt and quietly improved",
    description:
      "A recreation of Windows 98's Paint that gets the tool palette, the colour strip and the jagged pencil exactly right, then adds what the original lacked, including unlimited undo and transparency. It works offline and opens and saves real image files.",
    whyItsGood:
      "The airbrush hisses at the same rate and sprays the same speckled pattern, which is the sort of detail nobody had to get right.",
    timeToJoy: "instant",
    vibes: ["nostalgic", "cosy", "useful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2017,
    altfAlternative: "sketchflow",
    source: "altf-curated",
  },
  {
    slug: "pcjs-machines",
    name: "PCjs Machines",
    url: "https://www.pcjs.org/",
    category: "pixel-nostalgia",
    blurb: "Original IBM PCs, emulated down to the clock cycle",
    description:
      "PCjs runs faithful emulations of early hardware in the browser, covering the 1981 IBM PC, the PDP-11, several early Macs and a shelf of calculators. Each machine arrives with contemporary disk images and documentation explaining what you are looking at.",
    whyItsGood:
      "Cycle-accurate timing means the original IBM PC boots at its true speed, which is far slower than anybody remembers it being.",
    timeToJoy: "coffee-break",
    vibes: ["nostalgic", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2012,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "fake-update",
    name: "Fake Update",
    url: "https://fakeupdate.net/",
    category: "pixel-nostalgia",
    blurb: "Full-screen system update screens that never finish",
    description:
      "Pick an operating system and the page goes full screen with a convincing update display, stuck at some low percentage and warning you not to switch the computer off. Blue screens, macOS installers, Ubuntu boots and old Windows versions are all on the menu.",
    whyItsGood:
      "Progress numbers creep upward just enough to look real, which is exactly what makes it work on a colleague's unattended laptop.",
    timeToJoy: "instant",
    vibes: ["funny", "nostalgic", "weird"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: "pranx",
    source: "altf-curated",
  },
  {
    slug: "winamp-skin-museum",
    name: "Winamp Skin Museum",
    url: "https://skins.webamp.org/",
    category: "pixel-nostalgia",
    blurb: "Tens of thousands of Winamp skins, all of them playable",
    description:
      "Jordan Eldredge assembled the largest surviving collection of Winamp skins into one scrolling wall of thumbnails, searchable by name. Clicking any of them loads a working Winamp in the browser wearing that skin, with a track queued and ready to play.",
    whyItsGood:
      "Every skin is live rather than a screenshot, so you can hear a song through the exact skin somebody hand-drew in 1999.",
    timeToJoy: "rabbit-hole",
    vibes: ["nostalgic", "mesmerising", "cosy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2020,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "jsspeccy",
    name: "JSSpeccy",
    url: "https://jsspeccy.zxdemo.org/",
    category: "pixel-nostalgia",
    blurb: "A ZX Spectrum in your browser, loading noise included",
    description:
      "JSSpeccy emulates the 48K and 128K Spectrum with accurate timing and colour clash, and ships with a menu of games you can load straight from the page. Tape loading, the keyboard overlay and the rubber-key layout are all handled properly.",
    whyItsGood:
      "The attribute clash is faithfully wrong, so sprites still smear colour across the character grid exactly as they used to.",
    timeToJoy: "one-minute",
    vibes: ["nostalgic", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "console-living-room",
    name: "Console Living Room",
    url: "https://archive.org/details/consolelivingroom",
    category: "pixel-nostalgia",
    blurb: "Atari, Colecovision and Intellivision, inside the page",
    description:
      "Early cartridge systems run in the browser here, covering the Atari 2600, Colecovision, Intellivision, the Magnavox Odyssey and several machines that barely sold. Titles in this Internet Archive collection load with their box art and surviving manuals, and need no configuration.",
    whyItsGood:
      "Reading a scanned 1982 instruction manual before playing the game is the part that genuinely recreates the era.",
    timeToJoy: "coffee-break",
    vibes: ["nostalgic", "cosy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: "games",
    source: "altf-curated",
  },
  {
    slug: "poolsuite",
    name: "Poolsuite FM",
    url: "https://poolsuite.net/",
    category: "pixel-nostalgia",
    blurb: "A sun-bleached 90s Mac desktop that plays summer radio",
    description:
      "Poolsuite opens into a retro Macintosh interface with pixel icons, a windowed video player showing grainy pool footage and a set of curated radio channels. You drag windows around a beige desktop while the stations run uninterrupted in the background.",
    whyItsGood:
      "The boot sequence, the chunky window furniture and the VHS-grade video all commit to the same imaginary summer of 1994.",
    timeToJoy: "instant",
    vibes: ["nostalgic", "cosy", "calming"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "after-dark-css",
    name: "After Dark in CSS",
    url: "https://www.bryanbraun.com/after-dark-css/",
    category: "pixel-nostalgia",
    blurb: "The flying toasters screensaver, rebuilt in pure CSS",
    description:
      "Bryan Braun recreated the After Dark screensavers of the early 1990s using nothing but CSS animation, including Flying Toasters, Warp, Bad Dog and Starry Night. Each one runs full screen in a browser tab with the original timing and palette intact.",
    whyItsGood:
      "The toasters flap at the original cadence, and the slices of toast still tumble past at a different speed to the toasters.",
    timeToJoy: "instant",
    vibes: ["nostalgic", "mesmerising", "cosy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "telehack",
    name: "Telehack",
    url: "https://telehack.com/",
    category: "pixel-nostalgia",
    blurb: "A simulated 1980s network you explore by typing",
    description:
      "Telehack drops you at a shell prompt wired into a reconstructed ARPANET-era network of thousands of hosts, assembled from real historical records. Run period utilities, read archived text files, dial other machines and play the original text adventures.",
    whyItsGood:
      "The host list is drawn from genuine 1980s network data, so the machines you connect to actually existed and had those names.",
    timeToJoy: "rabbit-hole",
    vibes: ["nostalgic", "brainy", "weird"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2010,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "js-kid-pix",
    name: "JS Kid Pix",
    url: "https://kidpix.app/",
    category: "pixel-nostalgia",
    blurb: "Kid Pix 1.0 rebuilt, dynamite eraser and all",
    description:
      "A faithful browser version of the 1989 children's drawing program, complete with its stamps, wacky brushes, letter sounds and the set of tools designed purely to destroy your picture. Firecracker, black hole and moving van each clear the canvas their own way.",
    whyItsGood:
      "Choosing the dynamite eraser still detonates your drawing with the original sound effect, which is the whole reason anyone remembers Kid Pix.",
    timeToJoy: "instant",
    vibes: ["nostalgic", "wholesome", "funny"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2021,
    altfAlternative: "sketchflow",
    source: "altf-curated",
  },
];

export default sites;
