// packages/core/src/rabbithole/sites/part-2.js
/** Puzzles, interactive explainers, and simulations that run without a goal. */
const sites = [
  // ---------------------------------------------------------------------------
  // Mind Benders
  // ---------------------------------------------------------------------------
  {
    slug: "2048",
    name: "2048",
    url: "https://play2048.co/",
    category: "mind-benders",
    blurb: "Slide tiles, double numbers, lose an hour to one more go",
    description:
      "Gabriele Cirulli's tile game gives you a four-by-four grid where every swipe slides all the numbers in one direction and matching pairs merge into their double. New tiles keep appearing, the board fills up, and the only goal is a single 2048 tile before you run out of legal moves.",
    whyItsGood:
      "The rules take five seconds to learn, yet every loss is traceable to one careless swipe about twenty moves earlier.",
    timeToJoy: "instant",
    vibes: ["brainy", "competitive"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: "altfgame",
    source: "listicle",
  },
  {
    slug: "drench",
    name: "Drench",
    url: "https://www.flashbynight.com/drench/",
    category: "mind-benders",
    blurb: "Flood the whole board with one colour in thirty moves",
    description:
      "The grid starts as random coloured squares and you own the one in the top-left corner. Pick a colour and your territory absorbs every touching square of that colour, growing outward each turn. You get thirty moves to swallow the whole board, so each choice is a bet on which colour opens the most ground.",
    whyItsGood:
      "Greedy play stalls around move twenty, which is when you work out the real skill is spreading wide early rather than eating the biggest patch first.",
    timeToJoy: "instant",
    vibes: ["brainy", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2010,
    altfAlternative: "games",
    source: "listicle",
  },
  {
    slug: "little-alchemy-2",
    name: "Little Alchemy 2",
    url: "https://littlealchemy2.com/",
    category: "mind-benders",
    blurb: "Start with four elements, end with 700-odd absurd ones",
    description:
      "You begin with air, earth, fire and water, and drag any two together to see what they make. Combinations branch quickly from mud and steam into humans, cities, philosophy and the occasional joke item, with hundreds of recipes hiding behind the obvious ones.",
    whyItsGood:
      "The discovery log fills up with things you never set out to make, which is how you notice you have accidentally invented Time.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "cosy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2017,
    altfAlternative: "games",
    source: "listicle",
  },
  {
    slug: "wordle",
    name: "Wordle",
    url: "https://www.nytimes.com/games/wordle/index.html",
    category: "mind-benders",
    blurb: "One five-letter word a day, same word for everybody",
    description:
      "Six guesses, one hidden five-letter word, and green or yellow tiles telling you which letters are correctly placed or merely present. Everyone in the world gets the same puzzle each day, which is why a small grid of coloured squares became a shareable result rather than a score.",
    whyItsGood:
      "The daily limit is the whole design: one puzzle, no rematch, and a shared answer that turns a private guess into a conversation with everyone you know.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "competitive"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2021,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "nyt-connections",
    name: "Connections",
    url: "https://www.nytimes.com/games/connections",
    category: "mind-benders",
    blurb: "Sixteen words, four secret groups, four mistakes allowed",
    description:
      "A grid of sixteen words hides four groups of four, and your job is to find the idea binding each set together. The trap is deliberate overlap: several words fit two categories at once, and the puzzle is built so that the tempting grouping is usually the wrong one.",
    whyItsGood:
      "Difficulty comes from misdirection rather than vocabulary, so the moment a category finally clicks feels like catching the setter out.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "competitive"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2023,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "nerdle",
    name: "Nerdle",
    url: "https://nerdlegame.com/",
    category: "mind-benders",
    blurb: "Wordle for people who would rather guess an equation",
    description:
      "The daily puzzle hides an eight-character arithmetic equation instead of a word, and you get six attempts to find it. Tiles turn green or purple to show which digits and operators sit in the right place, so solving becomes a mix of mental arithmetic and constraint elimination.",
    whyItsGood:
      "Because the answer has to balance as a genuine equation, one confirmed digit can collapse dozens of remaining possibilities at once.",
    timeToJoy: "one-minute",
    vibes: ["brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2022,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "semantle",
    name: "Semantle",
    url: "https://semantle.com/",
    category: "mind-benders",
    blurb: "Guess the word by meaning, not by letters",
    description:
      "Every guess is scored by how close it sits to the secret word in a word-vector model, so ocean might rate highly for ship while sharing no letters at all. There is no letter feedback and no guess limit, only a similarity number telling you whether you are getting warmer.",
    whyItsGood:
      "Watching your score jump from 12 to 48 because you switched a noun for its verb form teaches more about semantics than any lesson would.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2022,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "waffle-game",
    name: "Waffle",
    url: "https://wafflegame.net/",
    category: "mind-benders",
    blurb: "Swap letters until six words fall into place",
    description:
      "The board is a waffle-shaped grid already full of letters, but scrambled, and you fix it by swapping pairs. Fifteen swaps are allowed and a perfect solve takes ten, so your score depends on spotting which letters are already home before you start moving anything.",
    whyItsGood:
      "It inverts the usual word game: every letter is handed to you up front and the entire challenge is restraint about which ones to touch.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "cosy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2022,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "puzzmo",
    name: "Puzzmo",
    url: "https://www.puzzmo.com/",
    category: "mind-benders",
    blurb: "A daily puzzle page designed by people who love puzzles",
    description:
      "Zach Gage and Orta Therox built a games page around a rotating set of daily puzzles, including a crossword, a chess variant, a word tower and several original logic games. Everything is redrawn with proper typography and scored on speed as well as accuracy.",
    whyItsGood:
      "Each game has been rebuilt rather than reskinned, so even the crossword carries small interface fixes that make the standard version feel clumsy afterwards.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "beautiful", "competitive"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2023,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "simon-tathams-puzzles",
    name: "Simon Tatham's Portable Puzzle Collection",
    url: "https://www.chiark.greenend.org.uk/~sgtatham/puzzles/js/",
    category: "mind-benders",
    blurb: "Forty small logic puzzles, endlessly generated, no fuss",
    description:
      "Around forty single-player logic puzzles run directly in the browser, from Slitherlink and Light Up to Galaxies and Solo. Each one generates fresh grids at whatever size and difficulty you pick, and every generated puzzle has exactly one solution reachable by deduction alone.",
    whyItsGood:
      "The guarantee that no puzzle ever needs a guess means a stuck board is always your own fault, which is oddly motivating at one in the morning.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "nostalgic"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2004,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "the-password-game",
    name: "The Password Game",
    url: "https://neal.fun/password-game/",
    category: "mind-benders",
    blurb: "Every password rule you feared, plus a chess puzzle",
    description:
      "You are asked to choose a password, and each time you satisfy a rule a stranger one appears. By rule twenty you are embedding a chess move, the current phase of the moon and a country flag, while a chicken wanders across the box eating your characters if you type too slowly.",
    whyItsGood:
      "Rules escalate from bureaucratic to openly hostile, and the point where your password must contain a fire you are not allowed to let go out is where most people give up laughing.",
    timeToJoy: "coffee-break",
    vibes: ["funny", "brainy", "weird"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2023,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "lichess-puzzles",
    name: "Lichess Puzzles",
    url: "https://lichess.org/training",
    category: "mind-benders",
    blurb: "Endless chess tactics drawn from real losing positions",
    description:
      "Millions of tactical positions harvested from real games are served one at a time, rated against your own puzzle rating so difficulty tracks you. Themes can be filtered, so you can drill only forks, only endgames, or run Puzzle Storm against a three-minute clock.",
    whyItsGood:
      "Every position actually occurred in somebody's game, so the winning move is never an artificial construction, only a chance one player missed.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "competitive"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "minesweeper-online",
    name: "Minesweeper Online",
    url: "https://minesweeper.online/",
    category: "mind-benders",
    blurb: "Minesweeper with leaderboards and no Windows required",
    description:
      "Beginner through expert boards plus custom sizes all sit on a faithful rebuild of the original grid. Timing, no-guess board generation and global leaderboards are layered on top, and replays let you watch exactly how a fast solver reads a board that would take you five minutes.",
    whyItsGood:
      "No-guess generation removes the one thing that always ruined Minesweeper, which was losing on a coin flip with three squares left.",
    timeToJoy: "instant",
    vibes: ["nostalgic", "competitive", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: "altfgame",
    source: "altf-curated",
  },
  {
    slug: "puzzle-nonograms",
    name: "Puzzle Nonograms",
    url: "https://www.puzzle-nonograms.com/",
    category: "mind-benders",
    blurb: "Numbers along the edges, a picture hiding in the grid",
    description:
      "Nonograms are logic puzzles where clue numbers on each row and column describe the runs of filled squares, and careful deduction uncovers a small pixel image. Fresh grids appear daily from five-by-five up to twenty-five-by-twenty-five, with weekly and monthly specials.",
    whyItsGood:
      "The reward is the moment a half-finished grid stops being abstract and you suddenly recognise what it is you have been drawing.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "calming"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "sudokupad",
    name: "SudokuPad",
    url: "https://sudokupad.app/",
    category: "mind-benders",
    blurb: "The sudoku app built for puzzles with unusual rules",
    description:
      "Sven Neumann's solver is the tool the Cracking the Cryptic community uses, handling variant sudoku where the constraints are thermometers, killer cages, arrows or renban lines rather than plain boxes. Pencil marks, cell colouring and shareable puzzle links are all built in.",
    whyItsGood:
      "Variant sudoku turns the puzzle into a fresh logic system every time, and this is the interface that makes those exotic rulesets actually playable.",
    timeToJoy: "coffee-break",
    vibes: ["brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2020,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "human-benchmark",
    name: "Human Benchmark",
    url: "https://humanbenchmark.com/",
    category: "mind-benders",
    blurb: "Measure your reaction time against millions of strangers",
    description:
      "A set of short browser tests covering reaction time, visual memory, number memory, typing speed, aim training and verbal memory. Each takes well under a minute and then plots your result on a distribution built from tens of millions of previous attempts.",
    whyItsGood:
      "Landing at the fortieth percentile for reaction time is a small and very specific humbling that no general brain-training app ever manages to deliver.",
    timeToJoy: "instant",
    vibes: ["brainy", "competitive"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2007,
    altfAlternative: "human-benchmark",
    source: "altf-curated",
  },
  {
    slug: "project-euler",
    name: "Project Euler",
    url: "https://projecteuler.net/",
    category: "mind-benders",
    blurb: "Maths problems you solve by writing a bit of code",
    description:
      "More than nine hundred numbered problems need both a mathematical insight and a short program to compute the answer. Brute force works for the first handful and then stops working entirely, at which point the problems start teaching number theory whether you intended to learn it or not.",
    whyItsGood:
      "Each problem is tuned so that a well-chosen insight runs in under a minute while the obvious loop would still be running next year.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy"],
    bestOn: "desktop",
    needsAccount: true,
    free: true,
    year: 2001,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "tetrio",
    name: "TETR.IO",
    url: "https://tetr.io/",
    category: "mind-benders",
    blurb: "Modern competitive stacking against real opponents",
    description:
      "A browser stacking game with modern handling, configurable delay settings and multiplayer modes where cleared lines are sent across as garbage to your opponent. Ranked ladders, forty-line sprints and a hundred-player battle royale all run without installing anything.",
    whyItsGood:
      "The input tuning is precise enough that the competitive scene lives here, so you can feel your finesse improving frame by frame instead of guessing.",
    timeToJoy: "one-minute",
    vibes: ["competitive", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2020,
    altfAlternative: "altfgame",
    source: "altf-curated",
  },
  {
    slug: "puzzling-stack-exchange",
    name: "Puzzling Stack Exchange",
    url: "https://puzzling.stackexchange.com/",
    category: "mind-benders",
    blurb: "A whole site of people inventing puzzles for each other",
    description:
      "Users post original riddles, lateral-thinking problems, cryptic clues, grid deductions and mathematical brain teasers, and other users solve them in the answers below. Solutions sit behind spoiler blocks, so you can read a discussion without ruining the puzzle for yourself.",
    whyItsGood:
      "The best threads show the solver's reasoning step by step, so a puzzle you failed turns into a lesson in how the setter was thinking.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "jane-street-puzzles",
    name: "Jane Street Puzzles",
    url: "https://www.janestreet.com/puzzles/",
    category: "mind-benders",
    blurb: "One properly hard maths puzzle, every single month",
    description:
      "A trading firm posts a single problem each month, usually combinatorial or geometric, and gives you until the end of the month to submit an answer. Past puzzles stay online with full worked solutions, so the archive doubles as a long course in this style of thinking.",
    whyItsGood:
      "The published solutions explain the elegant route rather than only the answer, which is exactly where most puzzle archives stop.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "sandtris",
    name: "Sandtris",
    url: "https://sandtris.com/",
    category: "mind-benders",
    blurb: "Tetris, except every block collapses into loose sand",
    description:
      "Blocks fall as they would in Tetris but shatter into thousands of coloured grains on landing, piling up and flowing around whatever is already there. A line clears only when one colour forms an unbroken path from the left wall to the right, so physics settles the board rather than geometry.",
    whyItsGood:
      "Watching a carefully planned stack slump sideways into a colour bridge you never intended is a kind of luck the original game could never produce.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "competitive"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2024,
    altfAlternative: "altfgame",
    source: "altf-curated",
  },
  {
    slug: "flexbox-froggy",
    name: "Flexbox Froggy",
    url: "https://flexboxfroggy.com/",
    category: "mind-benders",
    blurb: "Learn CSS flexbox by getting frogs onto lily pads",
    description:
      "Twenty-four levels each hand you a pond and some misplaced frogs, and the only way to move them is by typing real CSS flexbox properties into the code panel. Levels introduce justify-content, align-items, flex-wrap and order one at a time, with the pond redrawing as you type.",
    whyItsGood:
      "You remember what align-items does because you watched a frog slide to the wrong side of a pond the first time you got it wrong.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "useful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: null,
    source: "altf-curated",
  },

  // ---------------------------------------------------------------------------
  // Explain Everything
  // ---------------------------------------------------------------------------
  {
    slug: "evolution-of-trust",
    name: "The Evolution of Trust",
    url: "https://ncase.me/trust/",
    category: "explain-everything",
    blurb: "A playable argument about why societies stop cooperating",
    description:
      "Nicky Case turns game theory into a series of short playable rounds, starting with a single prisoner's dilemma and building to a tournament of strategies. By the end you have run a small society and watched trust build or collapse depending on the rules you set.",
    whyItsGood:
      "You reach the conclusion by playing rather than being told it, which is why the argument sticks weeks later.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2017,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "howstuffworks",
    name: "HowStuffWorks",
    url: "https://www.howstuffworks.com/",
    category: "explain-everything",
    blurb: "Plain answers to how ordinary machines actually work",
    description:
      "A long-running reference that takes one object or process at a time, whether a jet engine, a credit score or a nuclear reactor, and walks through it in ordered steps with diagrams. Articles assume no background and stop at the point where you could explain the thing to somebody else.",
    whyItsGood:
      "It answers the specific question you had rather than the adjacent one an encyclopaedia would answer, and it never assumes you already know the jargon.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 1998,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "neal-fun",
    name: "Neal.fun",
    url: "https://neal.fun/",
    category: "explain-everything",
    blurb: "One-page toys that teach by letting you try the thing",
    description:
      "Neal Agarwal builds small interactive pages, each committing to exactly one idea: spending a billionaire's fortune, running an oil empire, or dragging a slider through the artefacts of internet history. Everything loads instantly and needs no instructions.",
    whyItsGood:
      "Internet Artifacts is the standout, because you actually play the 1977 modem handshake and use the first webcam rather than reading about them.",
    timeToJoy: "instant",
    vibes: ["brainy", "funny", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "ciechanowski",
    name: "Bartosz Ciechanowski",
    url: "https://ciechanow.ski/",
    category: "explain-everything",
    blurb: "The best interactive explainers anyone is making",
    description:
      "Long articles on how a single physical thing works, covering GPS, gears, cameras, internal combustion, sound and the Moon's orbit. Each is built around dozens of custom diagrams you drag, spin and scrub through. Nothing here is a video; every figure is a live model responding to your input.",
    whyItsGood:
      "The diagrams are constructed so that the second you drag the slider yourself, the equation stops being notation and becomes something you have watched happen.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "beautiful", "mesmerising"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2017,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "the-pudding",
    name: "The Pudding",
    url: "https://pudding.cool/",
    category: "explain-everything",
    blurb: "Visual essays that argue with data instead of decorating it",
    description:
      "A small team of journalists and engineers publish one visual essay at a time, on subjects such as how pockets differ by gender, how rappers' vocabularies compare, or what a film script reveals about who gets to speak. Each piece is built as a scrolling argument.",
    whyItsGood:
      "The pieces are edited like essays rather than assembled like dashboards, so the chart always arrives at the exact point the sentence needs it.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2017,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "parable-of-the-polygons",
    name: "Parable of the Polygons",
    url: "https://ncase.me/polygons/",
    category: "explain-everything",
    blurb: "How mildly biased shapes end up in segregated cities",
    description:
      "Vi Hart and Nicky Case turn Schelling's segregation model into something you operate by hand. Squares and triangles want only a small fraction of their neighbours to resemble them, and you drag shapes around until you feel how a slight individual preference compounds into a divided neighbourhood.",
    whyItsGood:
      "The turn comes when you try to repair a segregated board and find that removing the bias is not enough, because the shapes have to actively want a mix.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "unsettling"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "explained-visually",
    name: "Explained Visually",
    url: "https://setosa.io/ev/",
    category: "explain-everything",
    blurb: "One statistics concept per page, all of it draggable",
    description:
      "Victor Powell's short pages each take a single idea from maths or statistics, such as eigenvectors, conditional probability, Markov chains or principal component analysis, and hand you a diagram to pull about. Change any input and every downstream number and shape updates immediately.",
    whyItsGood:
      "The eigenvector page makes the definition obvious after about ten seconds of dragging, having been a memorised formula for years beforehand.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "distill-pub",
    name: "Distill",
    url: "https://distill.pub/",
    category: "explain-everything",
    blurb: "Machine learning papers you can actually see working",
    description:
      "A research journal that published peer-reviewed machine learning work as interactive articles, with live diagrams in place of static figures. It stopped taking submissions in 2021, but the archive stays online and the pieces on feature visualisation and attention remain the clearest treatments anywhere.",
    whyItsGood:
      "Clicking through what each layer of a network is actually looking at, layer by layer, explains more in ten minutes than the original papers do at all.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "wait-but-why",
    name: "Wait But Why",
    url: "https://waitbutwhy.com/",
    category: "explain-everything",
    blurb: "Very long posts with stick figures that still land",
    description:
      "Tim Urban writes exhaustively researched posts on artificial intelligence, the Fermi paradox, procrastination and human history, illustrated throughout with deliberately crude stick drawings. Individual pieces run to tens of thousands of words and are split across several parts.",
    whyItsGood:
      "The bad drawings do real work: the Instant Gratification Monkey is a scribble, and also the most useful model of procrastination anyone has written down.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "funny"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "3blue1brown",
    name: "3Blue1Brown",
    url: "https://www.3blue1brown.com/",
    category: "explain-everything",
    blurb: "Grant Sanderson's maths lessons, with the visuals inline",
    description:
      "The written home of the animated maths series, where each lesson pairs the video with the same explanation as an illustrated article. Topics run from linear algebra and calculus through Fourier series, neural networks and probability, all drawn with the animation engine he wrote for the purpose.",
    whyItsGood:
      "The linear algebra series does one thing no textbook does: it shows the grid itself deforming, after which a matrix stops being a table of numbers.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "explorable-explanations",
    name: "Explorable Explanations",
    url: "https://explorabl.es/",
    category: "explain-everything",
    blurb: "A hub for every explainer you can play with",
    description:
      "Nicky Case's index of interactive learning pieces, sorted by subject and gathered from across the web. Entries cover social systems, biology, maths, art and civics, and a separate section explains how to build your own explorable if you catch the bug.",
    whyItsGood:
      "It is the best jumping-off point in the entire genre, because every link has been checked by somebody who makes these things himself.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "red-blob-games",
    name: "Red Blob Games",
    url: "https://www.redblobgames.com/",
    category: "explain-everything",
    blurb: "Game maths, explained with diagrams you can drag",
    description:
      "Pathfinding, hexagonal grids, map generation, curved paths and line-of-sight all get reference-quality treatment here, written by Amit Patel for people building games. Almost every page carries interactive diagrams where you move the start and goal and watch the algorithm rerun.",
    whyItsGood:
      "The A-star page became the standard explanation of pathfinding largely because you can drag an obstacle and see precisely which nodes the search stops visiting.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "useful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "better-explained",
    name: "BetterExplained",
    url: "https://betterexplained.com/",
    category: "explain-everything",
    blurb: "Maths taught as intuition first, notation afterwards",
    description:
      "Standard maths topics get rebuilt around an analogy that arrives before any symbols do, covering e, imaginary numbers, calculus, Bayes' theorem and Fourier transforms. Kalid Azad states plainly what the textbook version leaves out, then supplies the missing picture.",
    whyItsGood:
      "The account of e as continuous compound growth is the one that leaves people wondering why nobody taught it that way in the first place.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2006,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "seeing-theory",
    name: "Seeing Theory",
    url: "https://seeing-theory.brown.edu/",
    category: "explain-everything",
    blurb: "Probability and statistics, entirely as moving pictures",
    description:
      "A Brown University project covering basic probability, distributions, inference, regression and Bayesian methods across six chapters, each built from animated visualisations you control. Sampling distributions are demonstrated by drawing thousands of samples in front of you.",
    whyItsGood:
      "The central limit theorem chapter lets you pick an absurd population shape and watch the sample means fall into a bell curve anyway, which settles the idea for good.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "mathigon",
    name: "Mathigon",
    url: "https://mathigon.org/",
    category: "explain-everything",
    blurb: "A maths textbook that talks back while you read it",
    description:
      "Courses on geometry, graph theory, fractals, probability and cryptography pause and ask you to do something before continuing, unlocking the next paragraph once you have done it. Polypad, its virtual manipulatives board, comes with tiles, tangrams, number bars and fraction strips.",
    whyItsGood:
      "The text genuinely refuses to move on until you have solved the small step in front of you, which turns reading into something closer to a conversation.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "byrnes-euclid",
    name: "Byrne's Euclid",
    url: "https://www.c82.net/euclid/",
    category: "explain-everything",
    blurb: "An 1847 geometry book where colour replaces the labels",
    description:
      "Nicholas Rougeux rebuilt Oliver Byrne's coloured edition of Euclid's Elements as a website, keeping the original conceit: proofs use coloured shapes in place of letters such as ABC. Diagrams are redrawn as scalable vectors and set alongside the proofs they belong to.",
    whyItsGood:
      "Byrne's colour trick means you follow a proof by matching a red line to a red line, and it works well enough that an 1847 idea still beats modern notation.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "beautiful", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "complexity-explorables",
    name: "Complexity Explorables",
    url: "https://www.complexity-explorables.org/",
    category: "explain-everything",
    blurb: "Play with the models behind epidemics, flocks and chaos",
    description:
      "Dirk Brockmann collects small interactive models of complex systems: synchronising fireflies, disease spread across networks, chaotic pendulums, forest fires and reaction-diffusion patterns. Each explorable comes with a short written explanation and a full set of parameters to move.",
    whyItsGood:
      "Turning one parameter until an orderly system tips into chaos in front of you is the quickest possible way to understand what a critical threshold means.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "mesmerising"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2017,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "phet-simulations",
    name: "PhET Interactive Simulations",
    url: "https://phet.colorado.edu/",
    category: "explain-everything",
    blurb: "Free lab equipment for physics, chemistry and maths",
    description:
      "The University of Colorado maintains around 160 browser simulations covering circuits, gas laws, wave interference, natural selection, molecule building and projectile motion. Each is designed for classroom use, giving you sliders and meters rather than instructions to read.",
    whyItsGood:
      "The circuit construction kit lets you short a battery and watch the wire glow, which is a lesson no school can safely give you with real components.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2002,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "cpu-land",
    name: "CPU Land",
    url: "https://cpu.land/",
    category: "explain-everything",
    blurb: "What happens between typing a command and seeing output",
    description:
      "A single long article tracing how a program actually runs, from the shell's fork and exec through system calls, kernel mode, interrupts, virtual memory and the scheduler. Diagrams and short asides break it up, and it assumes only that you have used a terminal before.",
    whyItsGood:
      "It answers the question most programmers quietly avoid, which is what the operating system is doing while your code waits, and does it in one sitting.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2023,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "bezier-primer",
    name: "A Primer on Bézier Curves",
    url: "https://pomax.github.io/bezierinfo/",
    category: "explain-everything",
    blurb: "Everything about the curve behind every vector graphic",
    description:
      "Pomax's book-length guide covers control points, tangents, curvature, offsetting, intersection and arc length, with a live editable graphic beside nearly every section. The maths is fully shown, but the diagrams do most of the explaining and you can edit their source in place.",
    whyItsGood:
      "Dragging a control point while the de Casteljau construction redraws makes the algorithm obvious in a way the recursive formula never will.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "useful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "animagraffs",
    name: "Animagraffs",
    url: "https://www.animagraffs.com/",
    category: "explain-everything",
    blurb: "Machines taken apart in animation, layer by layer",
    description:
      "Complicated objects get pulled apart in animated cutaways: a car engine, a submarine, a passenger jet, a helicopter, a pair of headphones. Jacob O'Neal labels every part and then runs the mechanism, so you see what moves against what and in which order.",
    whyItsGood:
      "Seeing a four-stroke engine's valves, pistons and crankshaft animated in one frame explains the timing far better than four separate diagrams ever could.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "quantum-country",
    name: "Quantum Country",
    url: "https://quantum.country/",
    category: "explain-everything",
    blurb: "An essay that quizzes you so the physics actually sticks",
    description:
      "Andy Matuschak and Michael Nielsen wrote an introduction to quantum computing that embeds short recall questions directly in the prose, then schedules them to reappear over following weeks. The subject is qubits and quantum circuits; the experiment is whether reading can be made to stick.",
    whyItsGood:
      "Questions arrive mid-paragraph rather than at the end of a chapter, so you catch yourself having already forgotten something two screens after learning it.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: null,
    source: "altf-curated",
  },

  // ---------------------------------------------------------------------------
  // Sandboxes & Simulators
  // ---------------------------------------------------------------------------
  {
    slug: "orb-farm",
    name: "Orb.Farm",
    url: "https://orb.farm/",
    category: "sandboxes",
    blurb: "A sealed glass ecosystem that keeps going without you",
    description:
      "Max Bittker's closed aquatic terrarium runs on falling-sand physics. You add water, sand, algae, plants, fish and snails, then adjust light and heat and watch whether the nutrient cycle balances or collapses. There is no score, only whether the jar is still alive tomorrow.",
    whyItsGood:
      "Everything is coupled, so overfeeding the fish clouds the water, starves the plants and kills the fish a few minutes later without you touching anything.",
    timeToJoy: "one-minute",
    vibes: ["calming", "mesmerising", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "sandspiel",
    name: "Sandspiel",
    url: "https://sandspiel.club/",
    category: "sandboxes",
    blurb: "Draw with sand, water, fire and plants and step back",
    description:
      "A falling-sand world where each pixel is an element with its own rules: sand falls, water flows and puts out fire, plants creep along anything wet, and wind pushes the lot sideways. Finished scenes can be posted to a shared gallery for other people to poke at.",
    whyItsGood:
      "The plant element is the trick, because drawing one wet line grows vegetation on its own and turns a drawing tool into something that keeps working after you stop.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "beautiful", "calming"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "sandboxels",
    name: "Sandboxels",
    url: "https://sandboxels.r74n.com/",
    category: "sandboxes",
    blurb: "Falling sand with hundreds of elements and real chemistry",
    description:
      "Well over five hundred elements are on offer here, from ordinary water and stone through to specific acids, gases, foods, alloys and living things. Reactions are modelled properly, so heating limestone drives off carbon dioxide and mixing the wrong two things makes a mess of the screen.",
    whyItsGood:
      "The element list runs deep enough that you can accidentally do genuine chemistry, such as electrolysing water into hydrogen and oxygen and then igniting it.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "weird", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2021,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "falstad-circuit-simulator",
    name: "Falstad Circuit Simulator",
    url: "https://www.falstad.com/circuit/",
    category: "sandboxes",
    blurb: "Build a circuit and watch the electrons move through it",
    description:
      "Current is drawn as moving dots along the wires, with colour showing voltage at every point. Dozens of prebuilt examples load from a menu, from a simple RC filter through op-amps and logic gates to a full 555 timer, and any component value can be changed while it runs.",
    whyItsGood:
      "Seeing the dots slow to a crawl as they cross a resistor turns Ohm's law from a formula you memorised into something you can sit and watch happen.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "mesmerising", "useful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 1998,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "eater-boids",
    name: "Boids",
    url: "https://eater.net/boids",
    category: "sandboxes",
    blurb: "Three rules are all a flock of birds needs",
    description:
      "Ben Eater's page runs Craig Reynolds's flocking model, in which every bird obeys three local rules only: steer away from crowding, match the heading of nearby birds, and move toward the centre of the group. Sliders let you weaken each rule and watch the flock come apart.",
    whyItsGood:
      "Setting separation to zero and watching the flock collapse into a single point proves the behaviour lived in the rules and never in any leader.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2020,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "traffic-simulation",
    name: "Traffic Simulation",
    url: "https://traffic-simulation.de/",
    category: "sandboxes",
    blurb: "Find out why a jam appears when nothing is blocking",
    description:
      "Ring roads, motorway merges, roadworks and junctions each get their own scenario, with sliders for inflow, politeness, time headway and driver aggression. Trucks and cars follow separate rules, and you can drop an obstacle into a lane while the whole thing is running.",
    whyItsGood:
      "The ring road demo shows a phantom jam forming out of nothing but one driver braking slightly too hard, which quietly explains most of your commute.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "mesmerising"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "game-of-life",
    name: "Conway's Game of Life",
    url: "https://playgameoflife.com/",
    category: "sandboxes",
    blurb: "Four rules, and cells that build spaceships anyway",
    description:
      "The classic cellular automaton: each cell lives or dies based only on how many of its eight neighbours are alive. Draw a starting pattern or load known ones such as gliders, guns, oscillators and puffers, then step or run the grid and see what the rules make of it.",
    whyItsGood:
      "Loading a glider gun and realising a fixed four-rule system is manufacturing moving objects indefinitely is where cellular automata stop being a curiosity.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: null,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "lenia",
    name: "Lenia",
    url: "https://chakazul.github.io/Lenia/JavaScript/Lenia.html",
    category: "sandboxes",
    blurb: "Game of Life made continuous, and it grows creatures",
    description:
      "Replacing the crisp on-off cells of Conway's automaton with smooth continuous values changes the result entirely. Bert Chan's system grows a family of drifting, pulsing lifeforms with names like orbium and scutium that swim, rotate, collide and sometimes reproduce.",
    whyItsGood:
      "None of these creatures were designed, they were found by searching parameter space, which makes watching one glide across the grid genuinely strange.",
    timeToJoy: "one-minute",
    vibes: ["mesmerising", "weird", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "particle-life",
    name: "Particle Life",
    url: "https://hunar4321.github.io/particle-life/particle_life.html",
    category: "sandboxes",
    blurb: "Coloured dots that attract and repel start forming cells",
    description:
      "Each coloured particle attracts or repels every other colour by an amount you set in a small matrix, and that is the whole rule set. Even so, the dots reliably organise themselves into membranes, chasing pairs, orbiting clusters and structures that look unmistakably biological.",
    whyItsGood:
      "Randomising the attraction matrix a few times is usually enough to stumble on something that behaves like a dividing cell, from rules containing no notion of life.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "weird", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2022,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "minecraft-classic",
    name: "Minecraft Classic",
    url: "https://classic.minecraft.net/",
    category: "sandboxes",
    blurb: "The 2009 version of Minecraft, free in a browser tab",
    description:
      "Mojang put the original creative-mode build of Minecraft on the web for the game's tenth anniversary. Thirty-two block types, no crafting, no monsters and no survival, just a wide flat world, a hand, and a shareable URL that lets nine other people build alongside you.",
    whyItsGood:
      "The block palette is small enough that you stop optimising and simply build, which is what the game felt like before it acquired systems.",
    timeToJoy: "instant",
    vibes: ["nostalgic", "cosy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "loopy",
    name: "Loopy",
    url: "https://ncase.me/loopy/",
    category: "sandboxes",
    blurb: "Draw a system of feedback loops and press play",
    description:
      "Sketch circles for the things in a system and arrows for how they affect each other, marking every arrow as increasing or decreasing. Press play and Nicky Case's tool runs the whole model, so a scribbled diagram of rabbits and foxes starts oscillating on its own.",
    whyItsGood:
      "Adding one reinforcing arrow to a stable model and watching it spiral out of control is systems thinking taught in roughly fifteen seconds.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "useful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2017,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "keiwan-evolution",
    name: "Evolution",
    url: "https://keiwan.itch.io/evolution",
    category: "sandboxes",
    blurb: "Build a jointed creature and let it learn to walk",
    description:
      "You assemble a creature from bones, joints and muscles, pick a task such as running, jumping or climbing, and a genetic algorithm breeds successive generations toward it. Fitness graphs track the population while the best specimen of each generation is shown moving.",
    whyItsGood:
      "The winning strategies are almost always wrong in a funny way, like creatures that learn to fall forward permanently rather than take a second step.",
    timeToJoy: "coffee-break",
    vibes: ["funny", "brainy", "mesmerising"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2017,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "genetic-cars-2",
    name: "Genetic Cars 2",
    url: "https://rednuht.org/genetic_cars_2/",
    category: "sandboxes",
    blurb: "Random two-wheeled cars, bred over generations, on hills",
    description:
      "A population of randomly shaped vehicles with two wheels each attempts to drive across rough terrain. Those that travel furthest are bred together with a little mutation, and after twenty or thirty generations the shapes converge on something that genuinely works.",
    whyItsGood:
      "Watching a hopeless blob with a wheel in the wrong place become a competent buggy, with nobody designing it, is evolution at a speed you can sit through.",
    timeToJoy: "coffee-break",
    vibes: ["mesmerising", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "powder-game",
    name: "Powder Game",
    url: "https://dan-ball.jp/en/javagame/dust/",
    category: "sandboxes",
    blurb: "The falling-sand classic, still updated after fifteen years",
    description:
      "Around fifty materials and tools sit on the palette: powder, water, fire, magma, ice, lasers, fans, bombs and small stickmen who react to all of it. Scenes can be uploaded when you are done, and there is a permanent gallery of what everybody else has built.",
    whyItsGood:
      "The stickmen are why people stay: they flee from fire, drown in water and can be handed weapons, which turns a physics toy into a small cruel theatre.",
    timeToJoy: "instant",
    vibes: ["nostalgic", "weird", "mesmerising"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2007,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "micropolisjs",
    name: "micropolisJS",
    url: "https://www.graememcc.co.uk/micropolisJS/",
    category: "sandboxes",
    blurb: "The original open-source SimCity, rewritten for browsers",
    description:
      "Graeme McCutcheon ported Micropolis, the open-source release of the first SimCity code, to JavaScript. You zone residential, commercial and industrial land, run power lines and roads, set the tax rate, then deal with fires, traffic and the occasional requested disaster.",
    whyItsGood:
      "It keeps the original's slow tempo, so a city takes real time to grow and you notice precisely which road you should not have built.",
    timeToJoy: "rabbit-hole",
    vibes: ["nostalgic", "cosy", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "matter-js-demos",
    name: "Matter.js Demos",
    url: "https://brm.io/matter-js/demo/",
    category: "sandboxes",
    blurb: "Two dozen physics scenes you can grab and throw about",
    description:
      "The demo gallery for a 2D physics engine, running everything from stacked boxes and chains to soft bodies, catapults, car suspension, gravity wells and Newton's cradle. Every scene is live and every object can be dragged, flung or dropped while the solver keeps up.",
    whyItsGood:
      "The soft-body and chain scenes catch people out, because you can pick up a wobbling blob and it deforms convincingly under its own weight.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "netlogo-web",
    name: "NetLogo Web",
    url: "https://www.netlogoweb.org/",
    category: "sandboxes",
    blurb: "Hundreds of agent-based models, running in the browser",
    description:
      "The browser version of NetLogo opens its full model library: wolf and sheep predation, ant foraging, segregation, virus spread, flocking, traffic grids and forest fires. Each model exposes its parameters as sliders, and the code behind it is readable on the same page.",
    whyItsGood:
      "Opening the code tab and changing the rule that produced the behaviour you just watched is what separates this from a gallery of finished demos.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "useful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "gray-scott-reaction-diffusion",
    name: "Gray-Scott Reaction-Diffusion",
    url: "https://pmneila.github.io/jsexp/grayscott/",
    category: "sandboxes",
    blurb: "Two chemicals, two dials, and every pattern in nature",
    description:
      "The Gray-Scott model has two chemicals spreading across a grid, one feeding and one killing. Adjusting the feed and kill rates by dragging across a parameter map switches the output between spots, stripes, mazes, self-replicating blobs and slow coral-like growth.",
    whyItsGood:
      "The same two numbers that produce leopard spots also produce fingerprint whorls, and you can slide continuously between them with one cursor.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "beautiful", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2012,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "regex-crossword",
    name: "Regex Crossword",
    url: "https://regexcrossword.com/",
    category: "mind-benders",
    blurb: "Crosswords where every clue is a regular expression",
    description:
      "Each grid gives you a pattern for every row and every column, and the only letters that fit are the ones satisfying both at once. Puzzles start at two-by-two with literal matches and build through character classes, backreferences and lookaheads across several dozen levels.",
    whyItsGood:
      "It teaches regex the way a crossword teaches vocabulary: by making you want the answer badly enough to work out the syntax yourself.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "competitive"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
];

export default sites;
