/** Space and scale, live planetary data, and music discovery. */
const sites = [
  {
    slug: "hundred-thousand-stars",
    name: "100,000 Stars",
    url: "https://stars.chromeexperiments.com/",
    category: "cosmos-and-scale",
    blurb: "Fly out through our stellar neighbourhood, one star at a time",
    description:
      "Google's WebGL experiment plots the hundred thousand or so stars nearest the Sun in three dimensions, with the named ones labelled and annotated. Zooming out carries you from the Sun to the local neighbourhood to the whole Milky Way, and a guided tour narrates the trip over a Sam Hulick score.",
    whyItsGood:
      "The zoom never cuts. You pull back continuously from one star to a hundred thousand, and the moment the galaxy resolves around you is the payoff.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "beautiful", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2012,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "nasa-eyes-solar-system",
    name: "NASA's Eyes on the Solar System",
    url: "https://eyes.nasa.gov/apps/solar-system/",
    category: "cosmos-and-scale",
    blurb: "Ride along with any NASA mission, on any date you choose",
    description:
      "NASA's browser model of the solar system runs on real mission and ephemeris data, so planets, moons and spacecraft sit where they actually were or will be. You can lock the camera to a probe, scrub the clock forward to a future flyby, or run the whole system at a thousand times normal speed.",
    whyItsGood:
      "Setting the date to your own birthday and finding exactly where Voyager 1 was that day turns a mission timeline into something you lived alongside.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2010,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "stellarium-web",
    name: "Stellarium Web",
    url: "https://stellarium-web.org/",
    category: "cosmos-and-scale",
    blurb: "Tonight's real sky, from your exact spot, in a browser tab",
    description:
      "The web edition of the Stellarium planetarium renders the sky above whatever location you give it, with constellation lines, planets, deep-sky objects and satellite passes drawn in. Time can be wound forward or back, so you can check what will be up after dinner or what stood overhead on a given night.",
    whyItsGood:
      "Dragging the time slider through sunset and watching the stars fade in exactly as they will later is more use than any written list of viewing times.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "calming"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "scale-of-the-universe",
    name: "Scale of the Universe",
    url: "https://scaleofuniverse.com/",
    category: "cosmos-and-scale",
    blurb: "Scroll from quantum foam out to the observable universe",
    description:
      "One horizontal slider carries you across every order of magnitude, from strings and neutrinos up through cells, people, mountains, stars and superclusters. Objects appear at their correct relative size as you pass, and clicking any of them opens a short note on what it actually is.",
    whyItsGood:
      "The stretch between the largest animals and the smallest moons takes far longer to cross than anyone expects, which is precisely the point being made.",
    timeToJoy: "instant",
    vibes: ["brainy", "mesmerising"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2022,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "if-the-moon-were-only-one-pixel",
    name: "If the Moon Were Only 1 Pixel",
    url: "https://joshworth.com/dev/pixelspace/pixelspace_solarsystem.html",
    category: "cosmos-and-scale",
    blurb: "A map of the solar system with the empty space left in",
    description:
      "Josh Worth sets the Moon at one pixel wide and draws the rest of the solar system to that scale, which leaves almost the entire page blank. Scrolling from the Sun out to Pluto takes a genuinely long time, broken only by occasional captions commenting on how little there is to look at.",
    whyItsGood:
      "The jokes buried in the empty stretches keep you scrolling, and somewhere past Jupiter the scale stops being a number and becomes actual tedium.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "funny"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "size-of-space",
    name: "Size of Space",
    url: "https://neal.fun/size-of-space/",
    category: "cosmos-and-scale",
    blurb: "Begin beside an astronaut, finish at the Local Group",
    description:
      "Neal Agarwal's scroller starts next to a person in a spacesuit and works upward, adding one larger object at a time until the previous one has shrunk to a dot. Each step is drawn against the last, moving through asteroids, moons, planets, stars, nebulae and finally galaxies.",
    whyItsGood:
      "Every step is a like-for-like comparison with the thing immediately before it, so the growth compounds and the arrival of UY Scuti lands as a real shock.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "mesmerising"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "here-is-today",
    name: "Here Is Today",
    url: "https://hereistoday.com/",
    category: "cosmos-and-scale",
    blurb: "Today, then the month, then the epoch, then everything",
    description:
      "A single day sits on screen as a small coloured block. Each click zooms one level out, to the month, the year, the century, then to geological periods and eras, until today is an invisible sliver against the age of the universe. The whole sequence runs in roughly a minute.",
    whyItsGood:
      "The animation is unhurried and identical at every level, so your day shrinks by the same visual rule each time rather than through any rhetorical flourish.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "calming"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "ancient-earth-globe",
    name: "Ancient Earth Globe",
    url: "https://dinosaurpictures.org/ancient-earth",
    category: "cosmos-and-scale",
    blurb: "Type your address, watch it drift 750 million years",
    description:
      "Ian Webster's globe pairs modern place names with palaeogeographic reconstructions of Earth's continents. Choose a date from the dropdown, anywhere from 750 million years ago to the present, and a marker shows where your town's ground was sitting then, with a note on what was going on at the time.",
    whyItsGood:
      "Discovering that your street spent the Cretaceous underwater somewhere near the equator gives plate tectonics a home address.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "astronomy-picture-of-the-day",
    name: "Astronomy Picture of the Day",
    url: "https://apod.nasa.gov/apod/astropix.html",
    category: "cosmos-and-scale",
    blurb: "One space image a day, explained by a working astronomer",
    description:
      "Every day since June 1995, APOD has published a single astronomical image with a short caption written by a professional astronomer and links out to the underlying research. The archive now holds more than ten thousand entries, and the page design has barely shifted in thirty years.",
    whyItsGood:
      "The captions come from working astronomers rather than press officers, so they tell you which instrument took the shot and what is genuinely odd about it.",
    timeToJoy: "instant",
    vibes: ["beautiful", "brainy", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 1995,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "worldwide-telescope",
    name: "WorldWide Telescope",
    url: "https://worldwidetelescope.org/webclient/",
    category: "cosmos-and-scale",
    blurb: "Every major sky survey, stitched into one seamless view",
    description:
      "Originally a Microsoft Research project and now run by the American Astronomical Society, WWT layers real survey imagery across the entire sky, from radio through to X-ray. Pan and zoom between wavelengths, switch to a 3D solar system view, or play back guided tours built by other users.",
    whyItsGood:
      "Cross-fading one patch of sky between visible light and infrared makes the dust clouds appear and vanish, which no single photograph can show you.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2008,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "esasky",
    name: "ESASky",
    url: "https://sky.esa.int/",
    category: "cosmos-and-scale",
    blurb: "Search the sky the way the ESA science archives see it",
    description:
      "The European Space Agency's public window onto its science archives lets you type an object name, land on it, and then overlay observations from Hubble, Webb, Gaia, XMM-Newton and others. Footprints mark exactly which patch of sky each telescope has already covered.",
    whyItsGood:
      "Those observation footprints reveal how patchy our coverage still is, dense over the famous targets and empty almost everywhere else.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "aladin-lite",
    name: "Aladin Lite",
    url: "https://aladin.cds.unistra.fr/AladinLite/",
    category: "cosmos-and-scale",
    blurb: "The sky atlas professional astronomers use, in a tab",
    description:
      "Aladin Lite is the browser version of the atlas maintained by the Strasbourg astronomical data centre. It streams tiled survey imagery at any zoom level and overlays catalogue entries and published measurements on top, which is how objects in a paper get checked against the real sky.",
    whyItsGood:
      "It is the same tool cited in research papers, so you can paste a coordinate from a preprint and see precisely what the authors were pointing at.",
    timeToJoy: "coffee-break",
    vibes: ["brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "the-sky-live",
    name: "TheSkyLive",
    url: "https://theskylive.com/",
    category: "cosmos-and-scale",
    blurb: "Where every planet and bright comet is, right now",
    description:
      "TheSkyLive computes live positions for the planets, the Moon, bright comets and a long list of tracked objects, then gives rise and set times for your location. Each object gets a finder chart, a distance readout that ticks in real time, and a plot of how its brightness is changing.",
    whyItsGood:
      "The comet pages are the reason to bookmark it: a chart, a current magnitude and an honest answer on whether it is worth walking outside tonight.",
    timeToJoy: "instant",
    vibes: ["useful", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "in-the-sky-org",
    name: "In-The-Sky.org",
    url: "https://in-the-sky.org/",
    category: "cosmos-and-scale",
    blurb: "A calendar of everything visible from where you live",
    description:
      "Dominic Ford's site lists what is happening in the sky above a location you set, covering conjunctions, meteor showers, satellite passes, eclipses and lunar phases. Every event links through to a chart and a plain explanation of the geometry producing it.",
    whyItsGood:
      "The event list is filtered to your own latitude, so it never teases you with an eclipse only visible from the far side of the planet.",
    timeToJoy: "one-minute",
    vibes: ["useful", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "helioviewer",
    name: "Helioviewer",
    url: "https://helioviewer.org/",
    category: "cosmos-and-scale",
    blurb: "The Sun in every wavelength, going back fifteen years",
    description:
      "Helioviewer pulls imagery from SDO, SOHO and other solar observatories, letting you stack wavelengths, scrub through time and export the result as a video. Flares, filaments and coronal mass ejections are catalogued as events you can jump straight to.",
    whyItsGood:
      "Building a film of one specific flare out of raw observatory frames takes about four clicks, and the loop you get back is the footage the science teams work from.",
    timeToJoy: "coffee-break",
    vibes: ["mesmerising", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2009,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "galaxy-zoo",
    name: "Galaxy Zoo",
    url: "https://www.zooniverse.org/projects/zookeeper/galaxy-zoo/",
    category: "cosmos-and-scale",
    blurb: "Classify a galaxy nobody has ever properly looked at",
    description:
      "Galaxy Zoo shows you a telescope image and asks straightforward questions about it: smooth or spiral, how many arms, anything strange in the frame. Answers from many volunteers are combined into morphology catalogues that have supported hundreds of published papers.",
    whyItsGood:
      "Most of these images have never been examined by a person, so the first galaxy you are handed is quite likely the first time anyone has really seen it.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "wholesome"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2007,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "mars-trek",
    name: "Mars Trek",
    url: "https://trek.nasa.gov/mars/",
    category: "cosmos-and-scale",
    blurb: "Fly the whole of Mars on real orbiter mapping data",
    description:
      "NASA's Trek portal turns decades of orbiter surveys into a browsable globe of Mars, with elevation, mineral and thermal layers you can switch between. Landing sites and rover routes are marked, and the tools will measure a distance, plot an elevation profile or export terrain for 3D printing.",
    whyItsGood:
      "Drawing a line across Valles Marineris and getting a real elevation profile back turns a famous photograph into a place with measurable depth.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "asterank",
    name: "Asterank",
    url: "https://www.asterank.com/",
    category: "cosmos-and-scale",
    blurb: "Which asteroids would pay for the trip out to reach them",
    description:
      "Asterank holds data on more than half a million asteroids and ranks them by estimated composition, mining value and the fuel a mission would need to get there. A 3D viewer shows the orbits in motion, and filters let you ask for the most accessible or the most profitable rocks.",
    whyItsGood:
      "Sorting by cost-effectiveness returns a shortlist of unremarkable grey lumps carrying billion-dollar valuations, which is a very strange way to read the solar system.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "weird"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2012,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "where-is-roadster",
    name: "Where Is Roadster",
    url: "https://www.whereisroadster.com/",
    category: "cosmos-and-scale",
    blurb: "Tracking one car through interplanetary space since 2018",
    description:
      "The Tesla launched on the first Falcon Heavy test flight is still orbiting the Sun, and this tracker computes its position, speed and distance from Earth in real time. Running totals cover the odometer reading and how many times over the car has now exceeded its warranty mileage.",
    whyItsGood:
      "The battery died years ago and the tyres have long since disintegrated, but the counter ticking past the warranty limit by a factor of thousands stays funny.",
    timeToJoy: "instant",
    vibes: ["funny", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "heavens-above",
    name: "Heavens-Above",
    url: "https://www.heavens-above.com/",
    category: "cosmos-and-scale",
    blurb: "When the space station crosses your sky, to the second",
    description:
      "Set a location and Heavens-Above produces pass predictions for the space station, Starlink trains and thousands of other satellites, each with a chart showing the exact path across your local horizon. Comet and planet ephemerides sit alongside the satellite listings.",
    whyItsGood:
      "The predictions are accurate enough that you can stand outside at the stated minute, look at the stated point on the horizon, and watch it arrive.",
    timeToJoy: "one-minute",
    vibes: ["useful", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 1998,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "space-telescope-live",
    name: "Space Telescope Live",
    url: "https://www.spacetelescopelive.org/",
    category: "cosmos-and-scale",
    blurb: "What Hubble and Webb are pointed at this very minute",
    description:
      "The observing schedules for Hubble and the James Webb Space Telescope are public, and this site renders them as a live view of the current target: which object, which instrument, which proposal and whose research it belongs to. A countdown runs to the next observation in the queue.",
    whyItsGood:
      "Reading the name of the scientist whose proposal is executing right now, on a telescope a million miles away, makes the queue for observing time feel like a real place.",
    timeToJoy: "instant",
    vibes: ["brainy", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },

  {
    slug: "ocearch-shark-tracker",
    name: "OCEARCH Shark Tracker",
    url: "https://www.ocearch.org/tracker/",
    category: "live-planet",
    blurb: "Named great whites, pinging the map when they surface",
    description:
      "OCEARCH fits sharks, turtles and other large marine animals with satellite tags, then publishes the pings on an open map. Every animal has a profile carrying its name, length, weight and full track history, and a fresh ping appears whenever a tagged fin breaks the surface for long enough.",
    whyItsGood:
      "Following one named shark along thousands of miles of coastline, Mary Lee being the famous case, turns an anonymous species into an individual with a travel schedule.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2012,
    altfAlternative: null,
    source: "listicle",
  },
  {
    slug: "flightradar24",
    name: "Flightradar24",
    url: "https://www.flightradar24.com/",
    category: "live-planet",
    blurb: "Every aircraft in the air, updating as they move",
    description:
      "Flightradar24 pools thousands of volunteer-run ADS-B receivers into a single live map of civil aviation. Clicking an aircraft gives you the route, altitude, speed and registration, usually a photograph of that exact airframe, and a vertical profile of the flight so far.",
    whyItsGood:
      "Watching the transatlantic tracks fill overnight and empty again by breakfast exposes a daily rhythm in the sky that is invisible from the ground.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2006,
    altfAlternative: "flightradar",
    source: "altf-curated",
  },
  {
    slug: "adsb-exchange",
    name: "ADS-B Exchange",
    url: "https://globe.adsbexchange.com/",
    category: "live-planet",
    blurb: "The flight tracker that filters nothing out of the sky",
    description:
      "ADS-B Exchange runs on the same volunteer receiver network as the commercial trackers but refuses requests to hide aircraft, so military transports, government jets and private planes blocked elsewhere still show up. The interface is spartan and the filtering is unusually powerful.",
    whyItsGood:
      "Filtering for military squawks and finding a tanker flying long racetrack loops off a coastline is exactly what the tidier maps quietly remove.",
    timeToJoy: "one-minute",
    vibes: ["useful", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: "flightradar",
    source: "altf-curated",
  },
  {
    slug: "marinetraffic",
    name: "MarineTraffic",
    url: "https://www.marinetraffic.com/",
    category: "live-planet",
    blurb: "Live shipping, from container giants down to harbour tugs",
    description:
      "AIS transponders broadcast the position, heading and identity of ships at sea, and MarineTraffic plots the lot on one map. Vessel pages carry photographs, dimensions, cargo type, destination port and an estimated arrival, while port pages list everything currently tied up alongside.",
    whyItsGood:
      "The queue of ships anchored outside a congested port shows up as a visible cluster of dots, which makes a supply chain story into something you can look at.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2007,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "windy",
    name: "Windy",
    url: "https://www.windy.com/",
    category: "live-planet",
    blurb: "Weather models rendered as moving air you can read",
    description:
      "Windy animates output from the major forecast models as flowing particles across a map, with layers for wind, rain, temperature, waves, pressure and air quality. You can switch between the European and American models to see where they disagree, and open a full meteogram anywhere.",
    whyItsGood:
      "Swapping models mid-forecast and watching a storm track jump several hundred miles is the clearest demonstration of forecast uncertainty a non-meteorologist will get.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "useful", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "zoom-earth",
    name: "Zoom Earth",
    url: "https://zoom.earth/",
    category: "live-planet",
    blurb: "Near-live satellite imagery of storms as they form",
    description:
      "Zoom Earth stitches images from geostationary and polar-orbiting weather satellites into a smooth global map that refreshes every few minutes. Active tropical cyclones carry their forecast cones, and wildfire hotspots and rainfall radar can be layered over the top.",
    whyItsGood:
      "During a hurricane it updates fast enough to watch the eye reorganise itself, at a resolution broadcast weather graphics never show.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "ventusky",
    name: "Ventusky",
    url: "https://www.ventusky.com/",
    category: "live-planet",
    blurb: "Weather as painted colour fields, sliding through time",
    description:
      "Ventusky presents forecast data as smooth colour gradients rather than icons, covering temperature, precipitation, cloud, snow, waves and dozens of other variables. A time bar along the bottom scrubs the whole planet forward day by day and the animation stays fluid throughout.",
    whyItsGood:
      "At continental zoom the temperature layer shows cold air spilling south in visible lobes, which makes a weather front look like the physical object it really is.",
    timeToJoy: "instant",
    vibes: ["beautiful", "mesmerising"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "earth-nullschool",
    name: "earth.nullschool.net",
    url: "https://earth.nullschool.net/",
    category: "live-planet",
    blurb: "The planet's wind, drawn as one continuous flowing sheet",
    description:
      "Cameron Beccario's globe animates wind at any altitude as thousands of drifting particles, and the same projection will show ocean currents, wave height, sea temperature, chemical concentrations and particulate levels. The globe is draggable and every layer is one keystroke away.",
    whyItsGood:
      "Spinning it to the Southern Ocean and finding the westerlies circling an entire hemisphere without interruption explains the roaring forties in about two seconds.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "beautiful", "brainy"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "usgs-earthquake-map",
    name: "USGS Earthquake Map",
    url: "https://earthquake.usgs.gov/earthquakes/map/",
    category: "live-planet",
    blurb: "Every earthquake on Earth, minutes after it happens",
    description:
      "The US Geological Survey publishes automatically detected earthquakes worldwide, sized by magnitude and coloured by how recent they are. Each event opens onto shaking intensity maps, felt reports submitted by people who were there, and the fault mechanism once analysts have reviewed it.",
    whyItsGood:
      "Set the filter to all magnitudes, leave it running for an hour, and it becomes obvious the planet is shaking constantly at levels nobody ever notices.",
    timeToJoy: "instant",
    vibes: ["brainy", "unsettling"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2010,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "lightningmaps",
    name: "LightningMaps.org",
    url: "https://www.lightningmaps.org/",
    category: "live-planet",
    blurb: "Individual strikes, plotted a second after they land",
    description:
      "Blitzortung is a network of hobbyist radio receivers that time the arrival of the pulse from each lightning strike and triangulate where it hit. LightningMaps draws the results live, with a sound for every detection and expanding circles showing which stations picked it up.",
    whyItsGood:
      "The rings racing out from each receiving station and converging on a strike let you watch the triangulation happen rather than only see the result.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "unsettling"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "radio-garden-live",
    name: "Radio Garden",
    url: "https://radio.garden/",
    category: "live-planet",
    blurb: "Spin the globe, land on a live station somewhere real",
    description:
      "Green dots cover a 3D globe, each one a radio station broadcasting right now. Dragging the planet under the crosshair tunes you into whatever is playing in that town, whether that is drive-time chatter in Reykjavik, a Cairo phone-in or a lone community station in the Australian interior.",
    whyItsGood:
      "There is no genre filter and no menu, so the only way to choose is geographically, and hearing an advert break in a language you cannot place is the entire point.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "cosy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: "radio-garden",
    source: "altf-curated",
  },
  {
    slug: "earthcam",
    name: "EarthCam",
    url: "https://www.earthcam.com/",
    category: "live-planet",
    blurb: "Thousands of public cameras, pointed at everywhere at once",
    description:
      "EarthCam has run a directory of live public webcams since the mid-1990s, taking in Times Square, Abbey Road, harbours, mountain passes, zoo enclosures and construction sites. Many of the streams keep a rolling time-lapse, so a whole day at one location replays in a few seconds.",
    whyItsGood:
      "The construction cameras are the unexpected pleasure, compressing a year of a skyscraper going up into about a minute of footage.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "cosy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 1996,
    altfAlternative: "windowswap",
    source: "altf-curated",
  },
  {
    slug: "skylinewebcams",
    name: "SkylineWebcams",
    url: "https://www.skylinewebcams.com/",
    category: "live-planet",
    blurb: "Live HD cameras on piazzas, volcanoes and coral reefs",
    description:
      "A directory of high-definition public webcams, weighted towards Italian town squares but reaching worldwide, taking in Etna, ski resorts, harbours, wildlife hides and underwater reef cameras. Streams run continuously and most carry live audio from the location.",
    whyItsGood:
      "Opening a Roman piazza camera at eight in the evening local time, with the sound turned up, works as a functioning substitute for being there.",
    timeToJoy: "instant",
    vibes: ["calming", "cosy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2010,
    altfAlternative: "windowswap",
    source: "altf-curated",
  },
  {
    slug: "global-forest-watch",
    name: "Global Forest Watch",
    url: "https://www.globalforestwatch.org/map/",
    category: "live-planet",
    blurb: "Satellite alerts wherever tree cover vanished this week",
    description:
      "Global Forest Watch compares satellite imagery over time to flag forest loss, often within days of it happening, then maps the results against protected areas, logging concessions and fire hotspots. Loss and gain can be animated year by year back to 2000 for any country or region.",
    whyItsGood:
      "Zoom to a single concession boundary and the deforestation alerts stop dead at the line, which says more about enforcement than any report could.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "unsettling"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2014,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "nasa-firms-fire-map",
    name: "NASA FIRMS Fire Map",
    url: "https://firms.modaps.eosdis.nasa.gov/map/",
    category: "live-planet",
    blurb: "Every active fire the satellites spotted in the last day",
    description:
      "The Fire Information for Resource Management System plots thermal anomalies picked up by the MODIS and VIIRS instruments, usually within three hours of the satellite passing overhead. Detections can be filtered by confidence and replayed over the past week to follow a fire front.",
    whyItsGood:
      "Agricultural burning season across the Sahel or the Punjab arrives as a solid band of detections thousands of kilometres long, which no news bulletin ever conveys.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "unsettling"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2007,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "light-pollution-map",
    name: "Light Pollution Map",
    url: "https://www.lightpollutionmap.info/",
    category: "live-planet",
    blurb: "Find out where your nearest genuinely dark sky is",
    description:
      "Satellite radiance data from VIIRS is overlaid on a world map alongside the Bortle scale, so you can read night-sky brightness at any point and compare years to see where lighting has spread. Clicking a location returns numerical sky quality readings rather than a colour band alone.",
    whyItsGood:
      "The year slider shows the glow around most cities measurably expanding over a decade, a rare case of environmental change visible at a personal scale.",
    timeToJoy: "one-minute",
    vibes: ["useful", "unsettling"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "world-air-quality-index",
    name: "World Air Quality Index",
    url: "https://waqi.info/",
    category: "live-planet",
    blurb: "Live readings from thousands of monitoring stations",
    description:
      "The project aggregates official government monitoring stations from more than a hundred countries onto a single map, showing the current air quality index at each site with the individual pollutant readings sitting behind it. Every station page carries historical charts and a forecast.",
    whyItsGood:
      "Comparing two stations a few kilometres apart in one city, one beside a motorway and one in a park, quantifies something you can otherwise only smell.",
    timeToJoy: "instant",
    vibes: ["useful", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2007,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "global-fishing-watch",
    name: "Global Fishing Watch",
    url: "https://globalfishingwatch.org/map/",
    category: "live-planet",
    blurb: "Industrial fishing effort, drawn as tracks across the sea",
    description:
      "Vessel transmissions are fed through models that infer when a boat is fishing rather than simply transiting, producing a global map of apparent fishing effort. Marine protected area boundaries can be layered on, and vessels that switch their transponders off are flagged as gaps.",
    whyItsGood:
      "Lines of fishing activity pressed hard against a marine reserve boundary and stopping abruptly at the edge make the map read like a fence.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "unsettling"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "volcano-discovery",
    name: "VolcanoDiscovery",
    url: "https://www.volcanodiscovery.com/",
    category: "live-planet",
    blurb: "Which volcanoes are erupting today, and what they are doing",
    description:
      "A daily updated log of volcanic activity worldwide, combining seismic readings, satellite thermal data and observatory bulletins with photographs taken from the ground. The interactive map lists every currently erupting volcano alongside the recent earthquakes recorded near each one.",
    whyItsGood:
      "The running count of volcanoes erupting at this moment usually sits somewhere around forty, which is a good deal more than most people would guess.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "unsettling"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2004,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "mini-tokyo-3d",
    name: "Mini Tokyo 3D",
    url: "https://minitokyo3d.com/",
    category: "live-planet",
    blurb: "Tokyo's entire rail network, running live in 3D",
    description:
      "Every train on the Tokyo network appears as a moving object on a tilted 3D map, driven by open timetable and live delay feeds. Aircraft on approach to Haneda are included too, the model follows real daylight and weather, and tapping a train shows its service and next stop.",
    whyItsGood:
      "Watching the Yamanote line trains hold an even spacing right around the loop through rush hour is a quietly astonishing piece of choreography.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2019,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "birdcast",
    name: "BirdCast",
    url: "https://birdcast.info/",
    category: "live-planet",
    blurb: "Weather radar, counting the birds that migrate overnight",
    description:
      "Cornell's team reads the national weather radar network for the signature of migrating birds and turns it into live migration maps and forecasts. Through spring and autumn the tools estimate how many birds crossed each county last night, and which direction they were heading.",
    whyItsGood:
      "Learning that four hundred million birds crossed the country while you slept, measured rather than guessed, reframes what a quiet night actually is.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "wholesome"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2018,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "noaa-aurora-forecast",
    name: "NOAA Aurora Forecast",
    url: "https://www.swpc.noaa.gov/products/aurora-30-minute-forecast",
    category: "live-planet",
    blurb: "Where the aurora will be visible in thirty minutes",
    description:
      "The Space Weather Prediction Center models the auroral oval using live solar wind measurements taken by spacecraft sitting upstream of Earth. The map gives predicted brightness and the equatorward edge of visibility for both poles, refreshed every few minutes.",
    whyItsGood:
      "The forecast window is short enough to act on, so a green band creeping south over your latitude counts as an instruction to go and find a coat.",
    timeToJoy: "instant",
    vibes: ["useful", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: null,
    source: "altf-curated",
  },

  {
    slug: "every-noise-at-once",
    name: "Every Noise at Once",
    url: "https://everynoise.com/",
    category: "sound-and-signal",
    blurb: "Six thousand music genres, plotted on one scrollable map",
    description:
      "Glenn McDonald's scatterplot arranges thousands of algorithmically identified genres by texture, with organic and atmospheric sounds toward one edge and dense mechanical ones toward the other. Clicking any label plays a representative track immediately.",
    whyItsGood:
      "The genre names are half the appeal, and the map's axes turn out to correspond to something you can actually hear as you move across it.",
    timeToJoy: "instant",
    vibes: ["brainy", "mesmerising"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "listicle",
  },
  // Forgotify (forgotify.com) was here and has been pulled. The domain still
  // resolves, but its Spotify credentials are unconfigured so the player only
  // returns a setup error — listing it would contradict the promise on the
  // landing page that dead entries come out rather than sit in the list. It is
  // the first candidate for a "sites we lost" page if one is ever built.
  {
    slug: "radiooooo",
    name: "Radiooooo",
    url: "https://radiooooo.com/",
    category: "sound-and-signal",
    blurb: "Pick a country and a decade, hear what was playing",
    description:
      "A world map crossed with a timeline: choose Mali in the 1970s, or Japan in the 1930s, and the site plays records from that exact place and period, uploaded and moderated by its own community. A mood switch shuffles between slow, fast and weird within whatever you have selected.",
    whyItsGood:
      "The gaps are as informative as the hits, because a country with no records for a given decade usually turns out to have had something else going on at the time.",
    timeToJoy: "instant",
    vibes: ["mesmerising", "nostalgic", "weird"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "music-map",
    name: "Music-Map",
    url: "https://music-map.com/",
    category: "sound-and-signal",
    blurb: "Type one band, get a constellation of adjacent ones",
    description:
      "Enter an artist and Music-Map returns a cloud of related names positioned by similarity, with the closest matches sitting nearest the centre. The relationships come from what listeners have said belongs together rather than from audio analysis, so the links are often social rather than sonic.",
    whyItsGood:
      "Because the data is decades of human association rather than a model, you get the odd neighbour no audio-similarity engine would ever have proposed.",
    timeToJoy: "instant",
    vibes: ["brainy", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2000,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "gnoosic",
    name: "Gnoosic",
    url: "https://www.gnoosic.com/",
    category: "sound-and-signal",
    blurb: "Name three bands you like and it guesses the fourth",
    description:
      "Gnoosic asks for three favourite artists, then proposes others one at a time and learns from whether you say you like it, dislike it or have never heard of it. The interface has barely changed since the early 2000s and the whole thing runs on collective input, not audio features.",
    whyItsGood:
      "Answering 'don't know' repeatedly pushes it further from your comfort zone rather than retreating to safe picks, which is the opposite of how streaming radio behaves.",
    timeToJoy: "one-minute",
    vibes: ["nostalgic", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2001,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "bandcamp-discover",
    name: "Bandcamp Discover",
    url: "https://bandcamp.com/discover",
    category: "sound-and-signal",
    blurb: "Filter by genre, format and location, then simply listen",
    description:
      "Bandcamp's discovery page narrows the whole catalogue by genre, subgenre, format and geography, then streams full albums in the browser with no sign-up. Every record links back to the artist's own page, where most of the money from a purchase goes directly to them.",
    whyItsGood:
      "Setting the location filter to one country and sorting by recent arrivals surfaces a scene rather than a playlist, complete with the tag each band chose for itself.",
    timeToJoy: "coffee-break",
    vibes: ["useful", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2008,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "nts-radio",
    name: "NTS Radio",
    url: "https://nts.live/",
    category: "sound-and-signal",
    blurb: "Two live channels of specialist shows, free and unbroken",
    description:
      "NTS broadcasts around the clock from London and beyond on two live streams, backed by several thousand archived shows hosted by musicians, collectors and specialists. Its Infinite Mixtapes run as themed continuous channels for anyone who wants the sound without the talking.",
    whyItsGood:
      "Show pages publish the full tracklist, so a two-hour set becomes a list of records you can go and find rather than something you half remember.",
    timeToJoy: "instant",
    vibes: ["cosy", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2011,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "somafm",
    name: "SomaFM",
    url: "https://somafm.com/",
    category: "sound-and-signal",
    blurb: "Thirty listener-funded stations, no adverts anywhere",
    description:
      "A San Francisco internet radio operation running around thirty channels, each one programmed by a person, from lounge and dub through to a station of nothing but cover versions. It carries no advertising at all and lives on listener donations, which is why the channels stay so specific.",
    whyItsGood:
      "Channels as narrow as Underground 80s or the all-covers stream are things no commercial service would ever commission, and they have been running for twenty years.",
    timeToJoy: "instant",
    vibes: ["cosy", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2000,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "radio-paradise",
    name: "Radio Paradise",
    url: "https://radioparadise.com/",
    category: "sound-and-signal",
    blurb: "Hand-picked, hand-sequenced radio with no advertising",
    description:
      "Every song on Radio Paradise is chosen and ordered by a small team rather than a rotation engine, across four channels including a mellow mix and a global one. It streams in lossless quality for free, funded by listeners, with artwork and a full play history alongside.",
    whyItsGood:
      "The sequencing is the product. What follows a track has been chosen deliberately, so the joins between songs make sense in a way shuffled playlists never manage.",
    timeToJoy: "instant",
    vibes: ["calming", "cosy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2000,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "kexp",
    name: "KEXP",
    url: "https://www.kexp.org/",
    category: "sound-and-signal",
    blurb: "A radio station whose DJs still choose every record",
    description:
      "The Seattle public station streams live with human presenters and publishes a complete, searchable playlist of everything it has aired, timestamped to the minute. Its archive of in-studio live performances runs to thousands of sessions, all free to watch or stream.",
    whyItsGood:
      "Hear something on the stream, open the playlist page, and you have the artist within seconds, which turns passive listening into a dependable way to find records.",
    timeToJoy: "instant",
    vibes: ["cosy", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2001,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "mixcloud",
    name: "Mixcloud",
    url: "https://www.mixcloud.com/",
    category: "sound-and-signal",
    blurb: "DJ sets and radio shows, hours long and properly licensed",
    description:
      "Mixcloud hosts the long-form audio other platforms take down, meaning DJ mixes, radio archives and specialist shows, with rights holders paid through its licensing deals. Uploads are tagged by genre and city, and shows can be followed in much the same way as podcasts.",
    whyItsGood:
      "Because it is built for continuous mixes, searching a niche genre can return a three-hour set recorded in one specific club in one specific year.",
    timeToJoy: "coffee-break",
    vibes: ["cosy", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2008,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "smithsonian-folkways",
    name: "Smithsonian Folkways",
    url: "https://folkways.si.edu/",
    category: "sound-and-signal",
    blurb: "The US national collection of folk and world recordings",
    description:
      "Folkways is the Smithsonian's non-profit record label, holding tens of thousands of tracks of folk, blues, field recordings, spoken word and traditional music from across the world. The catalogue is browsable and streamable online, and every title ever released is kept permanently in print.",
    whyItsGood:
      "Liner notes are digitised alongside the audio, so a 1957 field recording arrives with the collector's own account of the village he recorded it in.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 1998,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "allmusic",
    name: "AllMusic",
    url: "https://www.allmusic.com/",
    category: "sound-and-signal",
    blurb: "Browse by genre, mood, decade or who played on it",
    description:
      "AllMusic has been building a structured database of recorded music since the days of print, with staff reviews, full personnel credits and every release tagged by style, mood and theme. Artist pages carry influence and follower links that let you walk a genre's family tree.",
    whyItsGood:
      "The credits are the hidden feature. Following one session drummer from record to record uncovers a run of albums no genre tag would ever have grouped together.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 1991,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "rate-your-music",
    name: "Rate Your Music",
    url: "https://rateyourmusic.com/",
    category: "sound-and-signal",
    blurb: "Charts for any genre, year or country you can name",
    description:
      "RYM is a community-built catalogue where users rate releases and file them into an unusually precise genre taxonomy. Its chart tool crosses genre with year, country and descriptor, so you can ask for the best-rated Ethiopian jazz of the 1970s and get a ranked, listenable answer.",
    whyItsGood:
      "The descriptor tags, things like melancholic or lethargic, are voted on by listeners and turn out to be a far better search handle than genre on its own.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "competitive"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2000,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "lastfm",
    name: "Last.fm",
    url: "https://www.last.fm/",
    category: "sound-and-signal",
    blurb: "Twenty years of listening data, turned into neighbours",
    description:
      "Last.fm has been logging what people play since 2002, and those scrobbles power its similar-artist pages, tag radio and charts reaching back two decades. Any artist page shows which acts their listeners also play, ranked by genuine overlap rather than by label promotion.",
    whyItsGood:
      "Similar-artist lists are built from what real listeners queued up next, which is why they include the unfashionable neighbour a curated playlist would drop.",
    timeToJoy: "coffee-break",
    vibes: ["brainy", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2002,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "whosampled",
    name: "WhoSampled",
    url: "https://www.whosampled.com/",
    category: "sound-and-signal",
    blurb: "Every sample, cover and remix, traced to its source",
    description:
      "WhoSampled documents the connections between recordings sample by sample, with timestamped audio snippets playing the original and then the track that borrowed from it. Contributors have mapped well over a million links across hip hop, dance, pop and film scores.",
    whyItsGood:
      "Hearing a four-second break from a 1969 record and then the song built on it, back to back at the exact timestamps, is the clearest possible proof of a lineage.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2008,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "discogs",
    name: "Discogs",
    url: "https://www.discogs.com/",
    category: "sound-and-signal",
    blurb: "A catalogue of very nearly every record ever pressed",
    description:
      "Built by collectors since 2000, Discogs catalogues physical releases down to the pressing, matrix number and country of manufacture, with credits for everyone involved. Label pages list a company's entire discography in order, which makes it a good way to work through a scene.",
    whyItsGood:
      "Opening a small label's page and following its catalogue numbers in sequence reconstructs a scene in the order it actually happened.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "nostalgic"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2000,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "free-music-archive",
    name: "Free Music Archive",
    url: "https://freemusicarchive.org/",
    category: "sound-and-signal",
    blurb: "Legally free music, curated rather than simply dumped",
    description:
      "Started by the radio station WFMU, the FMA collects music released under open licences, sorted by genre and vetted by curators instead of accepting whatever turns up. Tracks can be streamed or downloaded outright, with the licence terms stated plainly on every page.",
    whyItsGood:
      "The curation is what separates it from a free-music dump: someone with radio programming instincts decided which of these records were worth filing.",
    timeToJoy: "coffee-break",
    vibes: ["useful", "brainy"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2009,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "jamendo",
    name: "Jamendo",
    url: "https://www.jamendo.com/",
    category: "sound-and-signal",
    blurb: "Independent artists giving their catalogue away, legally",
    description:
      "Jamendo hosts music from independent musicians who publish under Creative Commons licences, browsable by genre, mood and instrument. Everything streams free and most of it can be downloaded, with a separate licensing arm for anyone who needs commercial rights.",
    whyItsGood:
      "The mood and instrument filters make it usable as a crate to dig through, rather than yet another list of tracks sorted by upload date.",
    timeToJoy: "coffee-break",
    vibes: ["useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2005,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "hype-machine",
    name: "Hype Machine",
    url: "https://hypem.com/",
    category: "sound-and-signal",
    blurb: "What the music blogs posted today, ranked by how many",
    description:
      "Hype Machine has read a curated list of music blogs since 2005, aggregating whatever they post into one feed ranked by how many writers covered a track. It survives on listener funding rather than advertising, and the blogroll behind it is still maintained by hand.",
    whyItsGood:
      "Because the inputs are people writing prose about records, the popular chart reflects actual enthusiasm rather than playlist placement or promotional spend.",
    timeToJoy: "one-minute",
    vibes: ["nostalgic", "useful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2005,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "playback-fm",
    name: "Playback.fm",
    url: "https://playback.fm/",
    category: "sound-and-signal",
    blurb: "The number one song on the day you were born",
    description:
      "Give Playback.fm a date and it returns the record topping the charts that week, alongside playable charts for every year running back through the twentieth century. Country-by-country lists and a set of music quizzes sit next to the birthday tool.",
    whyItsGood:
      "Working forward a year at a time through the charts of your own childhood is an unusually efficient way to trigger memories you were not looking for.",
    timeToJoy: "one-minute",
    vibes: ["nostalgic", "funny"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2013,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "solar-system-scope",
    name: "Solar System Scope",
    url: "https://www.solarsystemscope.com/",
    category: "cosmos-and-scale",
    blurb: "The planets where they actually are, right now",
    description:
      "A 3D model of the solar system running on real orbital data, so every planet and moon sits where it genuinely is at the moment you load it. You can switch between a heliocentric view, a geocentric one and a flat night sky, and wind the clock forward to line up an eclipse or a conjunction.",
    whyItsGood:
      "Switching from the sun-centred view to the earth-centred one, and watching the outer planets suddenly loop backwards, explains retrograde motion in about four seconds.",
    timeToJoy: "one-minute",
    vibes: ["brainy", "beautiful"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2012,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "musicmap",
    name: "Musicmap",
    url: "https://musicmap.info/",
    category: "sound-and-signal",
    blurb: "The family tree of every popular music genre",
    description:
      "Kwinten Crauwels spent seven years plotting how roughly two hundred and thirty genres descend from one another, drawing the lines of influence between them and writing a history for each. Zooming in moves from broad families down to individual scenes, with sample tracks attached.",
    whyItsGood:
      "It takes arguments that normally happen in comment sections and settles them with a diagram, and the essay behind each node is better sourced than most music writing.",
    timeToJoy: "rabbit-hole",
    vibes: ["brainy", "beautiful"],
    bestOn: "desktop",
    needsAccount: false,
    free: true,
    year: 2016,
    altfAlternative: null,
    source: "altf-curated",
  },
  {
    slug: "cities-and-memory",
    name: "Cities and Memory",
    url: "https://citiesandmemory.com/",
    category: "sound-and-signal",
    blurb: "A world map where every pin is a field recording",
    description:
      "A global sound project that pairs each field recording with a second, reimagined version composed from it, both pinned to the spot they were captured. Thousands of contributors have covered protests, markets, migrations, glaciers and empty rooms across more than a hundred countries.",
    whyItsGood:
      "Hearing the raw recording and then the composed response back to back turns a map pin into something closer to a short documentary.",
    timeToJoy: "coffee-break",
    vibes: ["mesmerising", "brainy", "calming"],
    bestOn: "both",
    needsAccount: false,
    free: true,
    year: 2015,
    altfAlternative: null,
    source: "altf-curated",
  },
];

export default sites;
