// Demand-mined keyword variants per tool slug, layered ahead of the derived
// phrases in buildToolKeywords. Every phrase is a real query observed in
// Google autocomplete (geo=IN) for the tool's own head term, kept only after
// a capability check against the tool's source and an adversarial review —
// a query like "image compressor to 20kb" only belongs on a tool that can
// target an output size. Full method: docs/SEARCH_DEMAND_NOTES.md.
//
// Regenerate with the mining + selection pipeline; hand edits must follow
// the same rules (on-topic, capability-true, no privacy or brand claims).
const toolKeywordOverrides = {
  "2fa-authenticator": ["2fa authenticator code"],
  "aac-phrase-board": ["aac word board", "aac common phrases"],
  "aadhaar-masking-tool": ["masking of aadhaar number", "what is aadhaar masking"],
  "ac-tonnage-calculator": ["ac tonnage calculator india", "ac tonnage calculator for room", "ac tonnage calculator formula", "ac tonnage calculator per square foot"],
  "acronym-generator": ["acronym generator from words", "acronym generator from letters", "acronym generator from names"],
  "adhesive-selector": ["adhesive selector guide"],
  "afterimage-generator": ["negative afterimage generator", "afterimage effect generator"],
  "age-calculator": ["age calculator by date of birth"],
  "ai-face-match": ["ai face match photo", "ai face match percentage", "ai face matcher"],
  "ai-object-counter": ["ai image object counter"],
  "ai-policy-quiz": ["ai policy questions"],
  "ai-prompt-organizer": ["ai prompt storage"],
  "ai-quiz-generator": ["ai quiz generator from text", "ai quiz generator for students"],
  "ai-roi-calculator": ["ai automation roi calculator", "ai agent roi calculator"],
  "ai-selfie-enhancer": ["ai selfie improver", "ai photo selfie enhancer"],
  "air-fryer-converter": ["air fryer converter calculator", "air fryer converter celsius", "air fryer converter oven", "air fryer converter time"],
  "aktu-sgpa-calculator": ["aktu gpa calculator", "aktu sgpa to cgpa calculator", "aktu sgpa to percentage calculator", "aktu sgpa calculation formula"],
  "algebra-solver": ["algebra equation solver", "algebra problem solver", "algebra solver calculator"],
  "allen-key-size-finder": ["allen wrench size finder", "allen key size guide", "hex key size guide", "allen key standard sizes"],
  "anagram-generator": ["anagram generator name", "anagram generator from letters", "anagram generator multiple words"],
  "analog-clock-alarm": ["analog alarm clock with snooze", "analog clock alarm set"],
  "anger-test": ["anger test quiz"],
  "ansi-escape-reference": ["ansi color reference", "list of ansi escape codes", "ansi escape characters"],
  "api-tester": ["api tester tool"],
  "apr-to-apy-converter": ["apr to apy calculator"],
  "aqi-today": ["aqi today delhi", "aqi today gurugram", "aqi today live"],
  "ascii-explorer": ["special characters list ascii"],
  "ashtakoot-matching": ["ashtakoot matching calculator", "ashtakoot matching points", "ashtakoot matching for marriage", "ashtakoot matching between male and female"],
  "attendance-calculator": ["attendance calculator 75", "attendance calculator college", "attendance calculator percentage", "attendance calculator formula"],
  "attention-span-test": ["attention span test for adults", "attention span test game", "attention span test psychology"],
  "audio-to-base64": ["audio to base64 string", "audio file to base64"],
  "aura-color-generator": ["aura color maker"],
  "baking-pan-converter": ["cake pan converter", "baking pan conversion calculator", "baking tray converter", "baking dish converter"],
  "band-name-generator": ["band name generator rock", "band name generator metal", "band name generator no ai"],
  "bank-exam-countdown": ["ibps exam countdown", "upcoming bank exam countdown"],
  "barcode-generator": ["barcode generator bulk", "barcode generator 128"],
  "barcode-scanner": ["barcode scanner online camera"],
  "base-converter": ["base converter calculator", "base converter math"],
  "base58-encoder": ["base58 encoder decoder"],
  "base64-to-file": ["base64 to file converter", "base64 to file download", "base64 to file pdf"],
  "base64-to-hex": ["base64 to hex converter", "base64 to hex decoder", "base64 to hexadecimal converter"],
  "base64-to-image": ["base64 to image decoder", "base64 to image viewer", "base64 to image download"],
  "base64-to-pdf": ["base64 to pdf converter", "base64 to pdf viewer", "base64 to pdf decoder"],
  "base64-to-text": ["base64 to text converter", "base64 to text conversion"],
  "base64-to-video": ["base64 to video converter", "base64 to video decoder", "base64 to video mp4", "base64 string to video"],
  "base64-url-converter": ["base64 url decoder", "base64 url encoder", "base64 to base64url converter"],
  "beautify-code-tool": ["format code tool", "code formatter tool", "beautify html code", "code formatting tool online"],
  "beauty-score": ["beauty score test"],
  "bg-remover": ["bg remover from image", "bg remover ai"],
  "bike-mileage-tracker": ["motorcycle mileage tracker"],
  "binary-learning-tool": ["how to learn binary", "how to learn binary system"],
  "birthday-wishes-hindi": ["birthday wishes hindi me", "birthday wishes hindi and english", "birthday wishes hindi text", "birthday wishes hindi meaning"],
  "birthday-wishes-odia": ["birthday wishes odia language", "birthday wishes odia text", "birthday wishes odia for friend", "birthday wishes odia for sister"],
  "birthday-wishes-tamil": ["birthday wishes tamil and english", "birthday wishes tamil text", "birthday wishes tamil meaning"],
  "birthday-wishes-urdu": ["birthday wishes urdu me", "birthday wishes urdu shayari", "birthday wishes urdu dua", "birthday wishes urdu in english"],
  "block-stacker": ["block stacker game"],
  "blog-post-ideas": ["blog post ideas for beginners", "blog post ideas for writers", "blog post ideas for students", "blog post ideas for small business"],
  "blog-title-generator": ["blog headline generator"],
  "blood-pressure-log": ["blood pressure log sheet"],
  "blur-comparison": ["gaussian blur comparison"],
  "blur-detector": ["blur detection", "blur image detection"],
  "bmi-calculator": ["bmi calculator for men", "bmi calculator women", "bmi calculator formula", "bmi calculator kg and feet"],
  "bmi-prime-calculator": ["what is bmi prime"],
  "bmr-calculator": ["bmr calculator for men", "bmr calculator female", "bmr calculator to lose weight", "bmr calculator formula"],
  "board-exam-countdown": ["board exam countdown class 10", "board exam countdown class 12", "board exam countdown 2026", "board exam countdown 2027"],
  "board-foot-calculator": ["board foot calculator for lumber", "board foot calculator wood", "board foot calculator formula", "board foot calculator price"],
  "body-fat-calculator": ["body fat calculator us navy", "body fat calculator for men", "body fat calculator female"],
  "body-fat-estimator": ["body fat estimator navy", "body fat estimator male", "body fat estimator women"],
  "bond-yield-calculator": ["bond yield calculator india", "bond yield calculator formula"],
  "box-breathing": ["box breathing timer", "box breathing exercise"],
  "box-shadow-generator": ["box shadow generator css", "box shadow generator inset"],
  "bpm-tap-counter": ["beats per minute tap counter", "tempo tap counter", "bpm tap calculator", "bpm tap tempo counter"],
  "braille-learning-tool": ["braille teaching tools", "how can i teach myself braille"],
  "brick-breaker": ["brick breaker game", "brick breaker classic"],
  "btu-to-ton-converter": ["btu to ton calculator", "btu hr to ton converter", "btu to tons cooling converter", "btu refrigeration ton converter"],
  "bubble-text-generator": ["bubble text generator copy paste", "bubble text generator font", "bubble text generator discord"],
  "buffer-ph-calculator": ["buffer solution ph calculator", "buffer ph calculation formula"],
  "bulk-find-replace": ["batch find replace", "mass find replace"],
  "bulk-url-opener": ["bulk url opener website"],
  "burnout-self-check": ["burnout self test", "burnout self assessment checklist"],
  "business-card": ["business card design"],
  "byte-converter": ["byte converter to gb", "byte converter to mb"],
  "caddyfile-generator": ["caddy generator"],
  "cagr-calculator": ["cagr calculator formula", "cagr calculator lumpsum"],
  "cagr-calculator-tool": ["formula to calculate cagr"],
  "calender-panchang": ["calendar panchang", "calendar panchangam", "calendar panchang today"],
  "calorie-calculator": ["calorie calculator to gain weight", "calorie calculator to lose weight", "calorie calculator for weight loss"],
  "candy-match-3": ["candy match 3 games"],
  "capital-city-quiz": ["capital city quiz with answers", "capital city quiz questions multiple choice", "capital city quiz game"],
  "captcha-generator": ["captcha generator image", "captcha generator text"],
  "car-loan-calculator": ["car loan calculator emi", "car loan calculator india"],
  "car-storage-checklist": ["vehicle storage checklist", "long term car storage checklist", "car winter storage checklist"],
  "card-picker": ["card picker generator"],
  "cat-exam-countdown": ["cat exam timer"],
  "celebrity-look-alike": ["celebrity look alike finder"],
  "chatgpt-chat-export": ["chatgpt chat exporter", "chatgpt chat export to pdf"],
  "chess-multiplayer": ["chess multiplayer with friends", "chess multiplayer same device", "chess multiplayer 2 player"],
  "chess-puzzle-trainer": ["chess puzzle training"],
  "chit-fund-calculator": ["chit fund calculator for 5 lakhs", "chit fund calculator for 1 lakh", "chit fund calculator for 3 lakhs", "chit fund calculator for 50000"],
  "chore-chart-maker": ["chore list maker", "kids chore chart maker"],
  "churn-rate-calculator": ["retention rate calculator", "attrition rate calculator", "churn rate calculation formula", "churn rate calculation example"],
  "citation-generator": ["citation generator apa", "citation generator apa 7", "citation generator mla", "citation generator vancouver"],
  "cloud-status-board": ["service status board", "cloud status page", "cloud status dashboard"],
  "coffee-brew-ratio": ["espresso coffee brew ratio", "coffee brew ratio french press", "coffee brew ratio drip"],
  "coin-flip": ["coin flip simulator", "coin flipper", "coin flip 3d", "coin flip game"],
  "coin-toss-streak-game": ["coin flip streak game"],
  "color-name-finder": ["color name finder from hex", "color name finder by code"],
  "compatibility-quiz": ["compatibility quiz for couples", "compatibility quiz for friends", "compatibility quiz for dating"],
  "computer-parts-quiz": ["computer parts quiz with answers", "computer hardware quiz", "pc parts quiz", "computer components quiz"],
  "conways-game-of-life": ["conway's game of life simulator"],
  "countdown-timer": ["countdown timer for study"],
  "country-quiz": ["country quiz flag", "country quiz game", "country quiz questions"],
  "critical-value-tables": ["z value tables", "t critical value tables", "f critical value tables", "critical value charts"],
  "crontab-evaluator": ["cron evaluator", "crontab expression evaluator"],
  "crush-percentage": ["crush percentage calculator", "crush percentage test", "crush name percentage", "crush love percentage"],
  "crypto-wallet-checker": ["crypto wallet checker ltc", "crypto wallet checker tron", "crypto wallet check trc20"],
  "css-button-generator": ["css button maker", "css button style generator", "css button gradient generator", "css3 button generator"],
  "css-clamp-generator": ["css font clamp generator", "css font size clamp generator", "css width clamp generator"],
  "css-filter-effects": ["css photo effects", "css image filter effects"],
  "css-flexbox-generator": ["css flexbox maker", "css flexbox layout generator"],
  "csv-to-json": ["csv to json file converter"],
  "cups-to-grams": ["cups to grams flour", "cups to grams butter", "cups to grams sugar", "cups to grams calculator"],
  "curl-command-builder": ["curl command generator", "curl command maker"],
  "currency-converter": ["currency converter usd to inr", "currency converter aed to inr", "currency converter euro to inr", "currency converter calculator"],
  "currency-quiz": ["currency quiz questions", "currency quiz game"],
  "cute-text-generator": ["cute text generator copy and paste", "cute text generator symbols"],
  "cymatics-simulator": ["cymatics digital simulator"],
  "d-d-dice-roller": ["d & d dice roller", "dnd online dice roller"],
  "dad-joke-machine": ["dad jokes for workplace"],
  "daily-spend-planner": ["daily budget planner"],
  "daily-word-challenge": ["daily word challenge game", "daily word challenge today"],
  "daily-word-game": ["daily word games", "daily word game guess the word"],
  "dark-circle-detector": ["how to check dark circles"],
  "date-time-conversions": ["date time conversion calculator", "date time conversion to utc"],
  "dca-calculator": ["dca calculator stock", "dca calculator crypto"],
  "decimal-converter": ["decimal converter calculator", "decimal convert into fraction", "decimal convert to percentage"],
  "decision-matrix-tool": ["decision making matrix tool", "weighted decision matrix tool", "decision analysis matrix tool"],
  "decision-wheel": ["decision wheel yes or no", "decision wheel maker", "decision wheel generator"],
  "declutter-planner": ["home declutter planner"],
  "deep-breathing-guide": ["deep breathing guided exercise"],
  "density-calculator": ["density calculator kg/m3"],
  "design-compare": ["compare design ui"],
  "dice-roller": ["dice roller 1-6", "dice roller 1-6 with dots"],
  "dictionary-app": ["dictionary app english to hindi"],
  "diff-checker": ["diff checker text", "diff checker code"],
  "digit-span-test": ["digit span test forward and backward", "digit span test psychology", "digit span test for attention", "digit span test scoring"],
  "digital-compass": ["digital compass direction"],
  "digital-legacy-vault": ["what is a digital legacy"],
  "dino-run": ["dino run game"],
  "dino-runner": ["dino runner game"],
  "discount-calculator": ["discount calculator in percentage"],
  "division-practice": ["division practice problems", "division practice questions", "division practice set"],
  "dns-record-generator": ["dns record maker", "dns txt record generator"],
  "dots-score-calculator": ["dots points calculator", "dots score formula", "what is a good dots score"],
  "dream-vacation-finder": ["dream vacation list"],
  "drinking-game-picker": ["drinking game generator"],
  "dst-clock-changes": ["dst time changes", "dst time changes 2026", "dst clock change date", "dst time changes in us"],
  "ecg-qtc-calculator": ["ecg qt calculator", "ecg qtc calculation normal range", "ecg qtc calculation bazett", "paediatric ecg qtc calculator"],
  "eclipse-simulator": ["solar eclipse simulator"],
  "email-header-analyzer": ["email header analyzer for spam", "email header analyzer phishing"],
  "email-validator": ["email validator tool", "email validator check"],
  "emom-workout-timer": ["emom interval timer", "emom workout clock", "emom training timer"],
  "emotion-detector": ["emotion detector ai"],
  "epf-calculator": ["epf calculator with existing balance", "epf calculator on salary", "epf calculator india", "epf calculator for private employees"],
  "equation-practice": ["equation practice questions", "equation practice problems", "quadratic equation practice"],
  "eth-gas-now": ["eth gas price now", "eth gas fee now", "eth gas right now", "eth gas today"],
  "exam-score-analyzer": ["exam score calculator", "exam result analysis", "exam score analysis"],
  "excel-formula": ["excel formulas list", "excel formulas list with examples"],
  "excel-to-chart": ["excel to chart converter", "excel to chart maker"],
  "excuse-generator": ["random excuse generator", "funny excuse generator"],
  "exif-data-viewer": ["exif data viewer location"],
  "eye-rest-timer": ["eye break timer", "eye relax timer"],
  "face-shape-detector": ["face shape detector for glasses", "face shape detector and hair style", "face shape detector ai"],
  "face-symmetry-checker": ["face symmetry checker ai"],
  "fake-chat-maker": ["fake chat maker screenshot", "fake chat maker messages"],
  "fake-data": ["fake data json", "fake data excel"],
  "fancy-text-generator": ["fancy text generator for instagram", "fancy text generator whatsapp"],
  "fast-click-challenge": ["fastest click challenge", "speed click challenge", "quick click challenge"],
  "feng-shui-room-guide": ["feng shui bedroom guide", "feng shui living room guide", "feng shui room tips", "feng shui room rules"],
  "fetal-kick-counter": ["baby kick counter", "fetal movement count", "baby kick counter online"],
  "ffmi-calculator": ["ffmi calculator kg", "ffmi calculator male", "ffmi calculator female"],
  "file-to-base64": ["file to base64 converter", "file to base64 string", "file to base64 encoder"],
  "filler-word-detector": ["filler word finder"],
  "fire-calculator": ["fire calculator india", "fire calculator with inflation", "fire calculator for retirement"],
  "first-aid-kit-builder": ["first aid kit build your own"],
  "flag-quiz": ["flag quiz game", "flag quiz challenge"],
  "focus-timer": ["focus timer for study"],
  "food-shelf-life-guide": ["food shelf life guidelines"],
  "form-builder": ["form builder react", "form builder ui"],
  "four-in-a-row": ["four in a row game", "four in a row 2 player"],
  "fraction-calculator": ["fraction calculator with whole numbers", "fraction calculator simplify", "fraction calculator with steps", "fraction calculator with solution"],
  "fraction-visualizer": ["fraction addition visualizer", "fraction bar visualizer", "equivalent fraction visualizer", "interactive fraction visualizer"],
  "frame-rate-converter": ["frame rate converter video"],
  "friendship-challenge": ["friendship challenge quiz", "friendship challenge game", "friendship challenge questions"],
  "friendship-meter": ["friendship meter test"],
  "friendship-score": ["friendship score quiz", "friendship score test"],
  "future-job-predictor": ["future career prediction", "future job prediction quiz"],
  "gaj-to-sqft-converter": ["gaj to sqft calculator", "1 gaj to square feet converter", "sqft to gaj converter online", "how to convert gaj into square feet"],
  "gift-budget-tracker": ["christmas gift budget tracker"],
  "gift-finder": ["gift finder quiz"],
  "github-profile-finder": ["git profile finder", "github user finder", "github account finder", "github profile viewer"],
  "gold-price-checker": ["gold value checker", "gold price check calculator", "gold price checker uk"],
  "gpa-cgpa-calculator": ["gpa calculator cgpa to percentage", "gpa cgpa conversion", "gpa to cgpa calculator india"],
  "gps-speedometer": ["gps speedometer for car", "gps speedometer for bike", "gps speedometer for cycle", "gps speedometer live"],
  "grammar-quiz": ["grammar quiz questions", "grammar quiz with answers", "grammar quiz articles a an the"],
  "gratuity-calculator": ["gratuity calculator india", "gratuity calculator for private employees", "gratuity calculator formula"],
  "grep-command-builder": ["grep command generator", "grep command maker"],
  "grocery-list-builder": ["grocery list generator", "grocery list maker online"],
  "grounding-exercise": ["grounding exercises for anxiety", "grounding exercise 54321", "grounding exercises for panic attacks", "grounding exercise 5 senses"],
  "group-bill-splitter": ["group bill split calculator", "group bill split"],
  "gst-calculator": ["gst calculator india", "gst calculator cgst sgst"],
  "guest-room-checklist": ["guest bedroom checklist"],
  "gym-rest-timer": ["workout rest timer", "fitness rest timer", "gym break timer"],
  "hair-color-preview": ["hair dye preview"],
  "hairstyle-preview": ["hairstyle preview men"],
  "hangman": ["hangman game", "hangman word game"],
  "heart-rate-calculator": ["heart rate calculator by age", "heart rate calculator formula", "heart rate calculator zones"],
  "heart-rate-zones": ["heart rate zones by age", "heart rate zones for running", "heart rate zones bpm", "heart rate zones for fat burning"],
  "heart-rate-zones-hiit": ["heart rate hiit calculator", "heart rate zone for hiit workout", "hiit heart rate zones by age", "what heart rate zone should hiit be in"],
  "heic-to-jpg": ["heic to jpg high quality"],
  "helmet-size-finder": ["helmet size guide", "helmet size calculator", "helmet size guide motorcycle"],
  "hex-to-base64": ["hex to base64url", "hex to base64 decode"],
  "hex-to-cmyk-converter": ["rgb hex to cmyk converter", "hex to cmyk calculator", "colour code converter hex to cmyk"],
  "hexadecimal-converter": ["hexadecimal converter to decimal", "hexadecimal converter to binary", "hexadecimal converter to number"],
  "hiit-timer": ["hiit timer 45 15"],
  "hindi-vernamala": ["hindi varnamala in english"],
  "holi-wishes-generator": ["holi wishes maker"],
  "how-lucky-are-you": ["how lucky are you quiz", "how lucky are you test"],
  "hp-to-kw-converter": ["hp to kw converter calculator", "hp to kw converter formula"],
  "html-email-checker": ["html email tester"],
  "html-js-converter": ["html to js converter", "javascript html converter"],
  "html-php-converter": ["html to php code converter"],
  "html-table-generator": ["html table generator with css", "html table generator code"],
  "icc-profile-explainer": ["icc profile explained"],
  "icon-maker": ["icon maker from image", "icon maker for website"],
  "image-collage-maker": ["image collage maker simple"],
  "image-metadata-viewer": ["image metadata viewer location"],
  "image-quality-checker": ["image resolution checker", "photo quality checker"],
  "image-resizer": ["image resizer in pixels"],
  "img-to-pdf": ["image to pdf merge"],
  "inflation-calculator": ["inflation calculator india", "inflation calculator inr", "inflation calculator rupees"],
  "instagram-dp-enhancer": ["insta dp enhancer"],
  "internet-speed-test": ["internet speed test mbps"],
  "interview-question": ["interview questions and answers"],
  "invoice-generator": ["invoice generator inr", "invoice generator india"],
  "ip-address-to-number": ["ip address to number converter", "ipv4 address to number", "ip address to binary number", "ip address to decimal number"],
  "ip-finder": ["ip finder tool"],
  "ip-geolocation-lookup": ["ip geolocation lookup bulk"],
  "ipa-to-text": ["ipa to text converter", "ipa text to english"],
  "ipu-sgpa-calculator": ["ipu gpa calculator", "ggsipu sgpa calculator", "ipu result sgpa calculator"],
  "ipv6-expander": ["ipv6 address expander"],
  "isitdown-now": ["is it down now or just me"],
  "iso-8601-formatter": ["iso 8601 format converter", "iso 8601 format date", "iso 8601 format example", "iso 8601 format timestamp"],
  "jdbc-url-builder": ["jdbc url generator"],
  "jee-exam-countdown": ["jee main countdown", "jee exam timer"],
  "jntu-sgpa-calculator": ["jntuk sgpa calculator", "jntuk sgpa calculator r20", "jntuk sgpa calculator r16", "how to calculate sgpa in jntuh"],
  "joke-generator": ["random humor generator"],
  "json-compare": ["json compare diff", "json compare tool"],
  "json-editor": ["json editor formatter"],
  "json-formatter": ["json formatter and validator", "json formatter beautify"],
  "json-parser": ["json parser formatter"],
  "json-to-excel-csv": ["json to excel csv converter", "json array to csv excel", "json file to csv excel"],
  "json-to-go-struct": ["json to go struct converter", "json to golang struct"],
  "json-to-typescript": ["json to typescript interface", "json to typescript converter", "json to typescript type generator", "json to typescript model"],
  "kegel-exercise-timer": ["kegel trainer timer"],
  "keto-macro-calculator": ["keto macro calculator for weight loss"],
  "key-signature-quiz": ["key signature quiz major and minor", "key signature quiz flats", "key signature quiz game"],
  "kids-brushing-timer": ["kids timer brushing teeth", "kids toothbrush timer"],
  "kitchen-multi-timer": ["kitchen multiple timer", "cooking multi timer", "kitchen timer multiple alarms"],
  "klondike-solitaire": ["klondike solitaire rules", "klondike solitaire turn one", "klondike solitaire turn 3"],
  "ktu-sgpa-calculator": ["ktu sgpa calculator for btech", "ktu gpa calculator", "ktu cgpa sgpa calculator"],
  "kundli-matching": ["kundli matching for marriage"],
  "land-area-converter": ["land area converter to square feet", "land area converter calculator", "land area converter india", "land area converter west bengal"],
  "laptop-hack": ["laptop hacker prank"],
  "life-stats": ["life stats calculator"],
  "line-break-remover": ["line break remover from text", "line feed remove", "paragraph line break remover"],
  "link-organizer": ["link organizer website"],
  "link-sorter": ["free link shortener no sign up"],
  "lipid-risk-calculator": ["lipid score calculator", "lipid profile risk calculator", "lipid panel risk calculator"],
  "list-sorter": ["list sorter alphabetical", "list sorter random", "list sorter number"],
  "live-caption-overlay": ["live subtitles overlay"],
  "loan-emi-calculator": ["loan emi calculator india", "loan emi calculator with prepayment"],
  "logic-gate-simulator": ["logic gate simulator with truth table"],
  "logo-prompt-generator": ["logo prompt generator ai", "logo prompt maker", "logo design prompt generator"],
  "long-weekend-planner": ["long weekend planner 2026"],
  "lorem-ipsum-generator": ["lorem ipsum generator word"],
  "love-calculator": ["love calculator name", "love calculator name test", "love calculator percentage"],
  "love-poem-generator": ["love poem generator for her", "love poem generator for him", "love poem maker"],
  "lucky-color-picker": ["lucky color generator"],
  "lucky-day-predictor": ["lucky day prediction", "lucky day calculator", "lucky day calculator by date of birth", "lucky day calculator numerology"],
  "ludo-multiplayer": ["ludo multiplayer with friends"],
  "lumpsum-calculator": ["lumpsum calculator mutual fund"],
  "macro-calculator": ["macro calculator for fat loss", "macro calculator for weight loss", "macro calculator for muscle gain", "macro calculator for women"],
  "magic-8-ball": ["magic 8 ball answers"],
  "makeup-shade-finder": ["makeup shade finder with photo", "makeup shade finder concealer", "makeup color finder"],
  "mandi-bhav": ["mandi bhav aaj ka", "mandi bhav india", "mandi bhav sarson", "mandi bhav gehu today"],
  "manglik-dosha-checker": ["manglik dosha test"],
  "map-puzzle": ["map puzzle game"],
  "markup-calculator": ["markup calculator percentage"],
  "marla-kanal-converter": ["marla kanal calculator", "marla kanal conversion", "in 1 kanal how many marla"],
  "math-speed-challenge": ["fast math challenge"],
  "md5-hash-generator": ["md5 hash generator 128 bit"],
  "media-query-generator": ["media query maker", "media query example"],
  "meditation-timer": ["meditation timer bell", "meditation timer 10 minutes", "meditation timer 20 minutes"],
  "meme-generator": ["meme generator templates", "meme generator text"],
  "memory-palace-builder": ["mind palace builder", "memory palace creator"],
  "mental-rotation-test": ["mental rotation test practice"],
  "meta-tag-generator": ["meta tag generator html", "meta tag generator for website", "meta tag generator for blogger"],
  "metronome": ["metronome guitar"],
  "minesweeper": ["minesweeper game"],
  "mirr-calculator": ["mirr formula calculator", "mirr calculator with reinvestment approach"],
  "mirror-text-generator": ["mirror text generator copy and paste"],
  "moon-phase-simulator": ["moon cycle simulator", "moon phase simulator for kids"],
  "moon-phase-viewer": ["moon phase status"],
  "morse-code-audio": ["morse code audio generator", "morse code audio maker", "morse code audio practice"],
  "morse-code-translator": ["morse code translator to text", "morse code translator english to morse"],
  "mortgage-calculator": ["mortgage calculator india"],
  "motivation-reminder": ["motivational reminder quotes"],
  "mountain-quiz": ["mountain quiz questions and answers", "mountain quiz game", "mountain quiz with answers"],
  "moving-checklist": ["moving checklist timeline"],
  "mpg-to-kmpl-converter": ["miles per gallon to kmpl converter", "uk mpg to kmpl converter", "mpg to kpl converter"],
  "mttr-mtbf-calculator": ["mttr and mtbf formula calculator", "mttr mtbf formula"],
  "multi-country-clock": ["multi time zone clock digital"],
  "multi-touch-tester": ["multi touch test website", "multi touch test android", "multi touch test iphone"],
  "multiplication-table": ["multiplication table 1 to 20", "multiplication table 11 to 20", "multiplication tables 2 to 20", "multiplication table chart"],
  "nail-size-selector": ["nail size chart construction", "nail size chart mm", "nail size chart in inches"],
  "name-compatibility": ["name compatibility for marriage", "name compatibility test", "name compatibility numerology"],
  "neet-exam-countdown": ["neet exam countdown 2026", "neet exam date countdown"],
  "net-worth-calculator": ["net worth calculator india", "net worth calculator formula"],
  "never-have-i-ever": ["never have i ever questions"],
  "new-year-wishes-hindi": ["new year wishes hindi 2026", "new year wishes hindi quotes", "new year wishes hindi text"],
  "new-year-wishes-odia": ["new year wishes odia 2026", "new year wishes odia text", "new year greetings odia"],
  "new-year-wishes-tamil": ["new year wishes tamil 2026", "new year wishes tamil quotes", "new year wishes tamil text"],
  "new-year-wishes-urdu": ["new year wishes urdu 2026", "new year wishes urdu text", "new year sms in urdu", "new year greetings urdu"],
  "nm-to-ftlb-converter": ["newton meters to foot pounds converter", "torque nm to ft lbs converter", "nm to ft lbf converter"],
  "nonogram": ["nonogram game", "nonogram puzzle"],
  "note-frequency-chart": ["note frequency chart hz", "note frequency chart 432", "note frequency chart 440", "note frequency table"],
  "notice-file-generator": ["oss notice file generator"],
  "nps-calculator": ["nps calculator pension", "nps calculator for government employees", "nps calculator lumpsum"],
  "number-guessing-game": ["number guessing game 1-100"],
  "number-plate-decoder": ["licence plate decoder", "registration plate decoder", "types of number plates"],
  "nursery-rhyme-maker": ["nursery rhyme generator"],
  "oauth-scope-explainer": ["oauth scope explained"],
  "ohms-law-calculator": ["ohms law calculator watts", "ohms law calculator dc"],
  "old-photo-restorer": ["vintage photo restorer"],
  "onam-wishes-generator": ["onam wishes maker"],
  "online-compiler": ["online compiler html", "online compiler javascript"],
  "online-notepad": ["online notepad for typing"],
  "ovulation-calculator": ["ovulation calculator for pregnancy"],
  "pan-format-validator": ["valid pan number format", "trust pan number format", "pan number format example"],
  "pangram-checker": ["pangram checker with letters"],
  "pantry-expiry-tracker": ["shelf life of pantry items"],
  "para-phrasing-tool": ["paraphrasing tool without ai"],
  "party-food-planner": ["party food planning calculator", "party food planning"],
  "patch-test-timer": ["patch test time", "patch test time hair dye", "patch test 24 hours"],
  "pdf-password-remover": ["pdf password remover without password", "pdf password remover tool"],
  "pdf-preview-tool": ["pdf viewer tool"],
  "pdf-to-base64": ["pdf to base64 string"],
  "pdf-to-word-converter": ["pdf to word converter editable"],
  "percentage-calculator": ["percentage calculator formula", "percentage calculator kaise nikale"],
  "percentage-practice": ["percentage practice questions", "percentage practice set"],
  "perfect-egg-timer": ["perfect egg timer boil"],
  "period-cycle-tracker": ["period cycle tracker calculator"],
  "periodic-table-game": ["periodic table game quiz", "periodic table game to memorize", "periodic table game for kids"],
  "pest-control-planner": ["pest control planning"],
  "pet-age-converter": ["dog age converter", "dog age converter to human", "pet age calculator"],
  "pet-name-generator": ["pet name generator cat", "pet name generator dog"],
  "photo-to-sketch": ["photo to sketch converter", "photo to sketch pencil"],
  "pickup-line-generator": ["random pickup line generator", "chat up line generator", "pickup line maker"],
  "pigmentation-analyzer": ["skin pigmentation analyzer"],
  "pirate-name-generator": ["pirate name generator for kids", "pirate name generator fantasy", "pirate name generator funny"],
  "pixar-style-generator": ["pixar style image generator", "pixar art style generator", "3d pixar style generator"],
  "planet-retrograde-now": ["planet retrograde today", "is any planet retrograde now", "what planet went retrograde today"],
  "portfolio-maker-tool": ["portfolio builder tool"],
  "portfolio-rebalancer": ["portfolio rebalancer tool"],
  "prayer-times-qibla": ["prayer times qibla finder"],
  "pregnancy-due-date": ["pregnancy due date calculator", "pregnancy due date calculator india", "pregnancy due date calculator by week"],
  "prime-number-checker": ["prime number checker logic", "prime number checker algorithm"],
  "product-image-compare": ["product image comparison"],
  "profile-picture-maker": ["profile picture maker for whatsapp", "profile picture maker for youtube"],
  "proportion-solver": ["proportion solver calculator", "direct proportion solver", "ratio proportion solver"],
  "puja-room-planner": ["puja room plan"],
  "quake-near-me": ["quake near me now", "quake near me today", "earthquake near me", "earthquake near me today"],
  "query-string-parser": ["query params parser online", "url query string parser", "query params parser"],
  "quit-smoking-tracker": ["stop smoking tracker"],
  "quiz-prompt-builder": ["quiz generator prompt"],
  "random-business-idea": ["random company idea generator", "random company ideas", "give me a random business idea", "random small business ideas"],
  "random-decision-maker": ["random decision maker yes or no"],
  "random-fun-picker": ["random fun name picker"],
  "random-name-generator": ["random name generator list"],
  "random-name-picker": ["random name picker from list", "random name picker no repeats", "random name picker for lucky draw"],
  "random-word-generator": ["random word generator for pictionary", "random word generator for drawing", "random word generator for charades"],
  "rashi-finder": ["rashi finder by date of birth", "rashi finder by dob"],
  "ratio-calculator": ["ratio calculator 2 numbers", "ratio calculator 3 numbers", "ratio calculator pixels"],
  "reaction-speed-test": ["reaction speed test game"],
  "reaction-time-test": ["reaction time test spacebar", "reaction time test game", "reaction time test mobile"],
  "readability-checker": ["readability checker grade level", "readability checker flesch kincaid"],
  "recipe-scaler": ["recipe scaler calculator", "recipe ingredient scaler", "baking recipe scaler"],
  "relationship-adviser": ["relationship advisor"],
  "remove-extra-spaces": ["remove extra spaces from text"],
  "render-time-estimator": ["render time calculator"],
  "rent-vs-buy": ["rent vs buy calculator india", "rent vs buy house calculator"],
  "retirement-planner": ["retirement planner calculator", "retirement planner calculator india"],
  "rice-water-ratio": ["rice water ratio in cooker", "rice water ratio in pressure cooker", "rice water ratio in pot", "rice water ratio for basmati rice"],
  "rich-text-editor": ["rich text editor html"],
  "river-quiz": ["river quiz questions", "river quiz questions and answers"],
  "roas-calculator": ["roas calculator break even", "roas calculator formula", "roas calculator dropshipping", "target roas calculator"],
  "roc-filing-calendar": ["roc filing due date", "roc annual filing due date", "roc filing compliance calendar", "roc filing deadline"],
  "roi-calculator": ["roi calculator india", "roi calculator formula"],
  "roof-area-calculator": ["roof area calculator with pitch"],
  "roof-pitch-calculator": ["roof pitch calculator degrees", "roof pitch calculator metric"],
  "room-paint-calculator": ["wall paint calculator", "wall paint calculator square feet", "bedroom paint calculator"],
  "rto-mock-test": ["rto mock test for two wheeler", "rto mock test english"],
  "rug-size-selector": ["rug size guide living room", "rug size guide bedroom", "rug size guide for dining room", "rug size chart"],
  "rule-of-72-calculator": ["rule of 72 calculator compound interest", "rule of 72 calculator inflation", "rule of 72 calculator with steps"],
  "run-streak-tracker": ["run streak rules"],
  "running-feet-to-sqft": ["running feet to square feet", "running feet to sq ft calculator", "running feet to sq ft calculator india", "running feet vs sqft"],
  "salary-slip-generator": ["salary slip generator pdf"],
  "salary-tax-calculator": ["salary tax calculator india"],
  "sarcasm-generator": ["sarcasm generator text"],
  "sbom-generator": ["sbom generator cyclonedx", "sbom generator npm"],
  "sbv-to-srt-converter": ["sbv to srt converter for subtitles", "sbv to srt file converter", "change sbv to srt"],
  "screen-recorder": ["screen recorder for windows", "screen recorder for pc"],
  "screenshot-compare": ["screenshot compare tool", "screenshot compare slider"],
  "seating-chart-maker": ["seating chart maker wedding"],
  "severe-weather-watch": ["severe weather watch near me", "current severe weather watches", "severe weather watch today"],
  "shoe-size-converter": ["shoe size converter uk to india", "shoe size converter india to us", "shoe size converter uk to us", "shoe size converter women"],
  "sikh-baby-name-finder": ["sikh baby name generator", "sikh baby boy names"],
  "sip-calculator": ["sip calculator step up", "sip calculator mutual fund"],
  "sitemap-generator": ["sitemap generator for website", "sitemap generator tool"],
  "skin-tone-analyzer": ["skin tone analyzer photo", "skin color analyzer"],
  "sleep-calculator": ["sleep calculator cycle", "sleep calculator when to wake up"],
  "sleep-debt-calculator": ["sleep deprivation calculator"],
  "sliding-puzzle": ["sliding puzzle game", "sliding puzzle 3x3"],
  "small-caps-generator": ["small caps generator copy and paste", "small capital letters generator", "unicode small caps generator", "small caps maker"],
  "snake-draft-board": ["snake draft board 12 team", "snake draft board 10 team", "fantasy football snake draft board", "fantasy snake draft board"],
  "snake-water-gun-game": ["snake water gun game rules", "snake water gun game how to play"],
  "sop-prompt-builder": ["sop structure example"],
  "spam-checker": ["spam checker email"],
  "spelling-checker": ["spelling checker english"],
  "spin-the-bottle": ["spin the bottle with names", "spin the bottle online with names"],
  "spirit-animal-finder": ["spirit animal finder quiz", "my spirit animal finder"],
  "split-csv": ["split csv into multiple files", "split csv file", "split csv into 2"],
  "split-excel": ["split excel sheet", "split excel into multiple files", "split excel file"],
  "split-pdf": ["split pdf pages", "split pdf file", "split pdf into two parts"],
  "sppu-sgpa-calculator": ["pune university sgpa calculator", "sppu gpa calculator", "sppu sgpa calculation formula", "sppu sgpa to cgpa calculator"],
  "sprint-goal-generator": ["sprint goal examples"],
  "sql-formatter-online": ["sql formatter online one line", "sql formatter online beautify", "sql beautifier online"],
  "srt-to-vtt-converter": ["srt to webvtt converter", "srt to vtt subtitle converter", "srt to vtt conversion"],
  "stamp-duty-estimator": ["stamp duty calculator"],
  "step-counter": ["step counter online without app", "step counter online website", "step counter online live"],
  "stopwatch": ["stopwatch timer", "stopwatch for study"],
  "string-escape-tool": ["string unescape tool", "json string escape tool"],
  "stroop-effect": ["stroop effect game", "stroop effect experiment", "stroop effect challenge"],
  "study-room-planner": ["study room plan with dimensions"],
  "subnet-calculator": ["subnet calculator ipv4"],
  "subscript-generator": ["subscript generator copy paste", "subscript generator chemistry", "subscript generator number", "subscript generator unicode"],
  "sudoku": ["sudoku puzzle", "sudoku game"],
  "sudoku-solver": ["sudoku solver - step by step"],
  "superscript-generator": ["superscript generator copy paste", "superscript generator numbers", "how to make a number superscript"],
  "svg-arrow-generator": ["svg arrow path generator"],
  "svg-blob-generator": ["svg blob maker"],
  "svg-optimizer": ["svg optimizer for web"],
  "svg-to-image": ["svg to image converter", "svg to image high quality"],
  "swim-pace-calculator": ["swim pace calculator per 100m", "swim pace calculator meters", "swim pace calculator per 50", "swim pace calculator open water"],
  "swp-calculator": ["swp calculator with step up", "swp calculator monthly"],
  "syllable-counter": ["syllable counter haiku", "syllable counter for poems", "syllable counter by line"],
  "symptom-diary": ["symptom diary pdf"],
  "synonym-finder": ["synonym finder english"],
  "tabata-interval-timer": ["tabata workout timer", "tabata workout timer 40 20"],
  "tar-command-builder": ["tar command generator"],
  "tdee-calculator": ["tdee calculator with body fat", "tdee calculator kg", "tdee calculator to gain weight", "tdee calculator india"],
  "tds-194c-calculator": ["194c tds calculation with example", "194c tds rate calculator", "how to calculate tds under section 194c"],
  "tds-194ib-calculator": ["194ib tds calculation", "what is 194ib in tds"],
  "tds-194j-calculator": ["194j tds calculation example", "194j tds limit with example"],
  "team-generator": ["team generator with names"],
  "teen-bmi-calculator": ["teen bmi calculator women", "teen bmi calculator male", "teen obesity calculator", "teen overweight calculator"],
  "temperature-converter": ["temperature converter formula"],
  "text-behind-image": ["text behind image editor"],
  "text-diff-viewer": ["text diff tool"],
  "text-encryptor": ["text encryptor decryptor"],
  "text-extractor": ["text extractor from image"],
  "text-repeater": ["text repeater copy", "text repeater 1000 times", "text repeater 10 000 times"],
  "text-reverser": ["text reverser generator"],
  "text-summarizer": ["text summarizer no ai"],
  "text-to-ascii-art": ["text to ascii art generator", "text to ascii art converter"],
  "text-to-base64": ["text to base64 converter"],
  "text-to-binary": ["text to binary converter", "text to binary code", "text to binary translator"],
  "text-to-handwriting": ["text to handwriting converter", "text to handwriting assignment"],
  "text-to-ipa": ["text to ipa converter", "text to ipa translator", "text to ipa english"],
  "text-to-qr-code": ["text to qr code generator", "text to qr code converter"],
  "text-to-slug": ["text to slug converter", "text to slug generator", "text to url slug converter", "text slugify"],
  "text-translator": ["text translator english to hindi", "text translator to english", "text translator to voice"],
  "tile-calculator": ["tile calculator square feet", "tile calculator for floor", "tile calculator wall", "tile calculator square meters"],
  "time-zone-explorer": ["time zone browser"],
  "timeline-builder": ["timeline builder for writers"],
  "tip-calculator": ["tip calculator india", "tip calculator formula"],
  "tip-split-calculator": ["tax and tip split calculator"],
  "to-pdf": ["to pdf converter", "to pdf jpg", "to pdf image"],
  "toothbrushing-timer": ["toothbrushing timer for kids", "toothbrushing timer 2 minutes"],
  "trim-video": ["trim video online free no watermark"],
  "truth-or-dare": ["truth or dare questions", "truth or dare questions for friends", "truth or dare questions for couples"],
  "turf-roll-calculator": ["sod roll calculator", "grass roll calculator", "lawn roll calculator"],
  "twin-finder": ["twin finder by photo"],
  "twitter-card-preview": ["twitter card preview tool", "twitter preview card validator", "check twitter card preview", "x twitter card preview"],
  "typing-master": ["typing master test"],
  "typing-speed-game": ["typing speed game test", "typing speed game for mobile"],
  "typing-speed-test": ["typing speed test mobile"],
  "typing-tutor": ["typing tutorial"],
  "tyre-pressure-guide": ["tyre pressure guide car", "tyre pressure guide 4wd"],
  "ufw-rule-generator": ["ufw rule creator", "ufw allow rule", "ufw deny rule"],
  "ugc-brief-generator": ["ugc brief template", "ugc creator brief"],
  "ulid-generator": ["random ulid generator"],
  "umask-calculator": ["umask calculator linux", "unix umask calculator", "chmod umask calculator", "umask to permissions calculator"],
  "unit-circle-explorer": ["interactive unit circle explorer"],
  "unit-converter": ["unit converter length", "unit converter meter to feet"],
  "unlock-pdf": ["unlock pdf password", "unlock pdf file"],
  "upi-qr-code-generator": ["upi qr code generator with amount", "upi qr code generator with fixed amount"],
  "upside-down-text": ["upside down text copy and paste", "upside down text converter"],
  "urea-bun-converter": ["urea bun conversion factor", "urea to bun conversion formula", "blood urea to bun conversion"],
  "url-slug-generator": ["bulk url slug generator", "seo friendly url slug generator", "website slug generator", "url slug generator slugify online"],
  "username-generator": ["username generator with name", "username generator gaming", "username generator for instagram", "username generator for discord"],
  "utm-link-builder": ["utm builder meta", "utm builder for google ads"],
  "vastu-colour-guide": ["vastu colour chart", "vastu colour chart for house", "vastu colors directions"],
  "vat-calculator": ["vat calculator formula"],
  "vat-calculator-italy": ["vat tax calculator italy", "italy vat rates"],
  "vat-calculator-spain": ["vat calculator españa", "vat tax calculator spain", "how much vat in spain"],
  "vat-calculator-uae": ["5 vat calculator uae", "reverse vat calculator uae", "vat calculator abu dhabi", "vat amount calculator uae"],
  "vat-calculator-uk": ["vat calculator uk 2026", "vat calculator uk 2025", "how much is vat calculator uk", "what rate is vat in the uk"],
  "video-compressor": ["video compressor without losing quality"],
  "video-script-timer": ["video script time calculator", "script length timer"],
  "video-to-gif": ["video to gif converter", "video to gif maker", "video to gif high quality"],
  "video-to-webp": ["video to webp animation"],
  "video-trimmer": ["video trimmer without watermark"],
  "vo2-max-estimator": ["vo2 max estimator running"],
  "voice-to-text": ["voice to text converter"],
  "vtt-to-srt-converter": ["webvtt to srt converter"],
  "vtu-sgpa-calculator": ["vtu sgpa calculator 2022 scheme", "vtu sgpa calculator 22 scheme", "vtu sgpa calculator 21 scheme", "vtu sgpa calculator 2nd sem"],
  "wacc-calculator": ["wacc calculator formula"],
  "wallpaper-calculator": ["wallpaper calculator with pattern repeat", "wallpaper calculator uk", "wallpaper calculator for one wall"],
  "watermark-remover": ["watermark remover from image"],
  "webp-to-png-jpg": ["webp to png jpg converter", "convert webp to png jpg", "change webp to png or jpg", "save webp to png jpg"],
  "whack-a-mole": ["whack a mole game for kids", "whack a mole game for adults"],
  "what-kind-of-genius": ["what kind of genius are you", "what kind of geniuses are there"],
  "which-animal-are-you": ["which animal are you quiz", "which animal are you test", "which animal are you personality test"],
  "which-movie-genre": ["which movie genre are you quiz", "which movie genre are you", "which movie genre am i"],
  "whitespace-cleaner": ["clean white space"],
  "who-pays-the-bill": ["who pays the bill game"],
  "whois-lookup": ["whois lookup domain"],
  "wifi-qr-generator": ["wifi qr generator wpa3"],
  "wilks-calculator": ["wilks calculator for powerlifting", "wilks calculator ipf", "wilks calculator kg"],
  "word-scramble-game": ["word scramble game for adults", "word scramble game for kids"],
  "word-search": ["word search game", "word search puzzle"],
  "xirr-calculator": ["xirr calculator sip", "xirr calculator lumpsum", "xirr calculator for one time investment"],
  "xml-to-csv": ["xml to csv conversion", "xml to csv file"],
  "xml-to-excel": ["xml to excel converter"],
  "xml-to-json": ["xml to json formatter"],
  "yaml-formatter": ["yaml formatter and validator"],
  "zakat-calculator": ["zakat calculator india", "zakat calculator on gold", "zakat calculator on silver", "zakat calculator in rupees"],
  "zalgo-text-generator": ["zalgo text generator (copy and paste)", "zalgo text generator for discord", "zalgo text generator for roblox", "how to make zalgo text"],
};

export default toolKeywordOverrides;
