"use client";

import React, { useState, useEffect } from "react";
import { FileText, CheckCircle2, Copy, FileDown, Plus, Trash2, Sliders, Eye } from "lucide-react";

export default function ToolHome() {
  const [globalPermission, setGlobalPermission] = useState("allow"); // 'allow' | 'disallow'
  const [crawlDelay, setCrawlDelay] = useState("");
  const [sitemapUrl, setSitemapUrl] = useState("https://www.yourdomain.com/sitemap.xml");
  const [disallowedPaths, setDisallowedPaths] = useState(["/admin/", "/private/", "/tmp/"]);
  const [newDisallowedPath, setNewDisallowedPath] = useState("");
  const [customRules, setCustomRules] = useState([
    { userAgent: "Googlebot", action: "disallow", path: "/no-google/" },
    { userAgent: "Bingbot", action: "allow", path: "/public/" }
  ]);
  const [newAgent, setNewAgent] = useState("Googlebot");
  const [newAgentAction, setNewAgentAction] = useState("disallow");
  const [newAgentPath, setNewAgentPath] = useState("");

  const [output, setOutput] = useState("");
  const [copied, setCopied] = useState(false);
  const [downloaded, setDownloaded] = useState(false);

  useEffect(() => {
    let result = "# robots.txt generated by ALTFTool\n\n";

    // Global rule
    result += "User-agent: *\n";
    if (globalPermission === "allow") {
      result += "Disallow:\n";
    } else {
      result += "Disallow: /\n";
    }

    // Crawl delay if set
    if (crawlDelay) {
      result += `Crawl-delay: ${crawlDelay}\n`;
    }

    // Global disallowed paths
    if (globalPermission === "allow") {
      disallowedPaths.forEach((path) => {
        if (path.trim()) {
          result += `Disallow: ${path.trim()}\n`;
        }
      });
    }

    result += "\n";

    // Custom Rules Grouped by User-Agent
    const agents = [...new Set(customRules.map((r) => r.userAgent))];
    agents.forEach((agent) => {
      if (!agent.trim()) return;
      result += `User-agent: ${agent.trim()}\n`;
      customRules
        .filter((r) => r.userAgent === agent)
        .forEach((rule) => {
          if (rule.path.trim()) {
            const actionLabel = rule.action === "allow" ? "Allow" : "Disallow";
            result += `${actionLabel}: ${rule.path.trim()}\n`;
          }
        });
      result += "\n";
    });

    // Sitemap URL
    if (sitemapUrl.trim()) {
      result += `Sitemap: ${sitemapUrl.trim()}\n`;
    }

    setOutput(result);
  }, [globalPermission, crawlDelay, sitemapUrl, disallowedPaths, customRules]);

  const addDisallowedPath = () => {
    if (newDisallowedPath.trim()) {
      setDisallowedPaths([...disallowedPaths, newDisallowedPath.trim()]);
      setNewDisallowedPath("");
    }
  };

  const removeDisallowedPath = (idx) => {
    setDisallowedPaths(disallowedPaths.filter((_, i) => i !== idx));
  };

  const addCustomRule = () => {
    if (newAgent.trim() && newAgentPath.trim()) {
      setCustomRules([
        ...customRules,
        {
          userAgent: newAgent.trim(),
          action: newAgentAction,
          path: newAgentPath.trim()
        }
      ]);
      setNewAgentPath("");
    }
  };

  const removeCustomRule = (idx) => {
    setCustomRules(customRules.filter((_, i) => i !== idx));
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      console.error(e);
    }
  };

  const handleDownload = () => {
    const textBlob = new Blob([output], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(textBlob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `robots.txt`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 2000);
  };

  return (
    <div className="min-h-screen bg-background p-4 sm:p-6 lg:p-8">
      <div className="w-full max-w-7xl mx-auto space-y-8">
        
        {/* Header */}
        <section className="rounded-xl border border-border bg-card p-4 sm:p-5 shadow-sm group">
          <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-surface-soft text-primary group-hover:bg-primary/10 transition-colors duration-300">
                <FileText className="h-5 w-5 text-primary group-hover:scale-110 group-hover:-rotate-6 transition-transform duration-300" />
              </div>
              <div>
                <div className="flex flex-wrap items-center gap-2">
                  <h1 className="text-xl font-bold text-foreground leading-none">
                    Robots.txt Generator
                  </h1>
                  <span className="inline-flex rounded-md border border-border bg-background px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-wide text-muted-foreground">
                    Developer, SEO
                  </span>
                </div>
                <p className="text-xs text-muted-foreground mt-1 max-w-xl leading-relaxed">
                  Generate SEO-compliant robots.txt crawlers rules. Allow/disallow bots, set crawl delays, and define sitemap references.
                </p>
              </div>
            </div>
            <div className="flex flex-wrap gap-1.5 text-[10px] font-semibold text-muted-foreground shrink-0 self-start md:self-auto">
              {["Runs locally", "No upload", "SEO Friendly"].map((item) => (
                <span key={item} className="inline-flex items-center gap-1 rounded-md border border-border bg-background px-2 py-1">
                  <CheckCircle2 className="h-3 w-3 text-primary" />
                  {item}
                </span>
              ))}
            </div>
          </div>
        </section>

        {/* Workspace Layout */}
        <div className="w-full space-y-6">
          
          {/* Builder Form */}
          <div className="bg-card border border-border rounded-2xl p-6 shadow-sm space-y-6">
            <h2 className="text-xs font-bold text-foreground uppercase tracking-wider border-b border-border pb-3 flex items-center gap-1.5">
              <Sliders size={14} className="text-primary" />
              Crawler Configuration Form
            </h2>

            {/* Global Rule */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-foreground uppercase tracking-wider block">
                  Global Bot Access
                </label>
                <select
                  value={globalPermission}
                  onChange={(e) => setGlobalPermission(e.target.value)}
                  className="w-full bg-surface-soft border border-border rounded-xl p-2.5 text-xs font-bold text-foreground outline-none focus:ring-1 focus:ring-primary focus:border-primary"
                >
                  <option value="allow">Allow All Bots (*)</option>
                  <option value="disallow">Block All Bots (*)</option>
                </select>
              </div>

              <div className="space-y-1.5">
                <label className="text-xs font-bold text-foreground uppercase tracking-wider block">
                  Crawl Delay (Seconds)
                </label>
                <select
                  value={crawlDelay}
                  onChange={(e) => setCrawlDelay(e.target.value)}
                  className="w-full bg-surface-soft border border-border rounded-xl p-2.5 text-xs font-bold text-foreground outline-none focus:ring-1 focus:ring-primary focus:border-primary"
                >
                  <option value="">No Delay (Default)</option>
                  <option value="2">2 Seconds</option>
                  <option value="5">5 Seconds</option>
                  <option value="10">10 Seconds</option>
                </select>
              </div>
            </div>

            {/* Sitemap URL */}
            <div className="space-y-1.5">
              <label className="text-xs font-bold text-foreground uppercase tracking-wider block">
                Sitemap Path
              </label>
              <input
                type="url"
                value={sitemapUrl}
                onChange={(e) => setSitemapUrl(e.target.value)}
                placeholder="https://example.com/sitemap.xml"
                className="w-full bg-surface-soft border border-border rounded-xl p-2.5 text-xs font-semibold text-foreground outline-none focus:ring-1 focus:ring-primary focus:border-primary"
              />
            </div>

            {/* Disallowed Directories List */}
            {globalPermission === "allow" && (
              <div className="space-y-3 pt-4 border-t border-border">
                <label className="text-xs font-bold text-foreground uppercase tracking-wider block">
                  Global Disallowed Directories
                </label>
                
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={newDisallowedPath}
                    onChange={(e) => setNewDisallowedPath(e.target.value)}
                    placeholder="e.g. /cgi-bin/"
                    className="flex-1 bg-surface-soft border border-border rounded-xl p-2.5 text-xs font-semibold text-foreground outline-none focus:ring-1 focus:ring-primary focus:border-primary"
                  />
                  <button
                    onClick={addDisallowedPath}
                    className="bg-primary text-primary-foreground px-4 py-2.5 rounded-xl font-bold text-xs flex items-center gap-1.5 hover:brightness-110"
                  >
                    <Plus size={14} /> Add
                  </button>
                </div>

                <div className="flex flex-wrap gap-2 max-h-[120px] overflow-y-auto pt-1">
                  {disallowedPaths.map((path, idx) => (
                    <div
                      key={idx}
                      className="inline-flex items-center gap-2 bg-surface-soft border border-border/80 rounded-lg px-2.5 py-1 text-xs"
                    >
                      <span className="font-mono text-red-500">{path}</span>
                      <button
                        onClick={() => removeDisallowedPath(idx)}
                        className="text-muted-foreground hover:text-red-500 transition"
                      >
                        <Trash2 size={12} />
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Custom Agent Rules */}
            <div className="space-y-4 pt-4 border-t border-border">
              <label className="text-xs font-bold text-foreground uppercase tracking-wider block">
                Add Bot-Specific Directives
              </label>

              <div className="grid grid-cols-1 sm:grid-cols-12 gap-2">
                <div className="sm:col-span-4">
                  <select
                    value={newAgent}
                    onChange={(e) => setNewAgent(e.target.value)}
                    className="w-full bg-surface-soft border border-border rounded-xl p-2.5 text-xs font-bold text-foreground outline-none"
                  >
                    <option value="Googlebot">Googlebot</option>
                    <option value="Bingbot">Bingbot</option>
                    <option value="Baiduspider">Baiduspider</option>
                    <option value="Yandex">Yandex</option>
                    <option value="Slurp">Yahoo Slurp</option>
                    <option value="ia_archiver">Alexa ia_archiver</option>
                  </select>
                </div>
                
                <div className="sm:col-span-3">
                  <select
                    value={newAgentAction}
                    onChange={(e) => setNewAgentAction(e.target.value)}
                    className="w-full bg-surface-soft border border-border rounded-xl p-2.5 text-xs font-bold text-foreground outline-none"
                  >
                    <option value="disallow">Disallow</option>
                    <option value="allow">Allow</option>
                  </select>
                </div>

                <div className="sm:col-span-5 flex gap-2">
                  <input
                    type="text"
                    value={newAgentPath}
                    onChange={(e) => setNewAgentPath(e.target.value)}
                    placeholder="/no-crawling/"
                    className="flex-1 bg-surface-soft border border-border rounded-xl p-2.5 text-xs font-semibold text-foreground outline-none"
                  />
                  <button
                    onClick={addCustomRule}
                    className="bg-primary text-primary-foreground px-4 py-2.5 rounded-xl font-bold text-xs flex items-center gap-1.5"
                  >
                    <Plus size={14} /> Add
                  </button>
                </div>
              </div>

              {customRules.length > 0 && (
                <div className="space-y-2 pt-2 max-h-[140px] overflow-y-auto">
                  {customRules.map((rule, idx) => (
                    <div
                      key={idx}
                      className="flex items-center justify-between p-2.5 rounded-xl bg-surface-soft border border-border text-xs"
                    >
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-foreground">{rule.userAgent}:</span>
                        <span className={rule.action === "allow" ? "text-primary font-bold" : "text-red-500 font-bold"}>
                          {rule.action.toUpperCase()}
                        </span>
                        <span className="font-mono text-muted-foreground">{rule.path}</span>
                      </div>
                      <button
                        onClick={() => removeCustomRule(idx)}
                        className="text-muted-foreground hover:text-red-500 transition"
                      >
                        <Trash2 size={13} />
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>

          </div>

          {/* Generated Code Output */}
          <div className="bg-card border border-border rounded-2xl p-6 shadow-sm space-y-6">
            
            <div className="flex items-center justify-between border-b border-border pb-3">
              <h2 className="text-xs font-bold text-foreground uppercase tracking-wider flex items-center gap-1.5">
                <Eye size={14} className="text-primary" />
                File Preview (robots.txt)
              </h2>
              <div className="flex gap-1.5">
                <button
                  onClick={handleCopy}
                  disabled={!output}
                  className="inline-flex items-center gap-1 text-[10px] font-bold text-foreground bg-background border border-border rounded-lg px-2.5 py-1.5 hover:border-primary transition disabled:opacity-50"
                >
                  {copied ? <CheckCircle2 size={10} className="text-primary" /> : <Copy size={10} />}
                  {copied ? "Copied" : "Copy"}
                </button>
                <button
                  onClick={handleDownload}
                  disabled={!output}
                  className="inline-flex items-center gap-1 text-[10px] font-bold text-foreground bg-background border border-border rounded-lg px-2.5 py-1.5 hover:border-primary transition disabled:opacity-50"
                >
                  {downloaded ? <CheckCircle2 size={10} className="text-primary" /> : <FileDown size={10} />}
                  {downloaded ? "Download" : "Download"}
                </button>
              </div>
            </div>

            <textarea
              value={output}
              readOnly
              rows={10}
              className="w-full bg-surface-soft border border-border rounded-xl font-mono text-xs leading-relaxed p-4 outline-none resize-none cursor-text animate-fade-in"
            />

            <div className="text-[10px] text-muted-foreground leading-relaxed bg-surface-soft p-3 rounded-lg border border-border/80">
              💡 **SEO Tip:** Save this file as `robots.txt` and upload it to the root directory of your website (e.g., `https://yourdomain.com/robots.txt`) to guide search crawler indexers.
            </div>

          </div>

        </div>

      </div>
    </div>
  );
}
