import React from "react";
import { BarChart, FileSpreadsheet, Key, Shield, Download, Sparkles } from "lucide-react";

export default function Features() {
  return (
    <section className="py-16 bg-(--page) border-t border-(--border)">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Title */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl font-bold tracking-tight text-(--foreground) sm:text-4xl">
            Why Use Excel to Chart Converter?
          </h2>
          <p className="mt-4 text-lg text-slate-600 dark:text-slate-300">
            Transform raw numbers into stunning visuals within seconds, without installing any software or uploading your sensitive financial data to any server.
          </p>
        </div>

        {/* Feature Cards Grid */}
        <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
          <div className="bg-(--surface) p-6 rounded-xl border border-(--border) shadow-sm hover:shadow-lg hover:-translate-y-1 hover:border-teal-500/40 transition-all duration-300">
            <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-teal-500/10 text-teal-600 dark:text-teal-400 mb-4">
              <FileSpreadsheet className="h-6 w-6" />
            </div>
            <h3 className="text-lg font-semibold text-(--foreground) mb-2">Import XLSX, XLS, and CSV</h3>
            <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
              Drag and drop files generated by Microsoft Excel, Google Sheets, or CSV exports from your databases.
            </p>
          </div>

          <div className="bg-(--surface) p-6 rounded-xl border border-(--border) shadow-sm hover:shadow-lg hover:-translate-y-1 hover:border-teal-500/40 transition-all duration-300">
            <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-teal-500/10 text-teal-600 dark:text-teal-400 mb-4">
              <BarChart className="h-6 w-6" />
            </div>
            <h3 className="text-lg font-semibold text-(--foreground) mb-2">Dynamic Chart Options</h3>
            <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
              Instantly toggle between Line, Bar, Stacked Bar, Area, Stacked Area, Pie, Doughnut, and Radar charts.
            </p>
          </div>

          <div className="bg-(--surface) p-6 rounded-xl border border-(--border) shadow-sm hover:shadow-lg hover:-translate-y-1 hover:border-teal-500/40 transition-all duration-300">
            <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-teal-500/10 text-teal-600 dark:text-teal-400 mb-4">
              <Shield className="h-6 w-6" />
            </div>
            <h3 className="text-lg font-semibold text-(--foreground) mb-2">100% Client-Side Privacy</h3>
            <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
              Your spreadsheets never leave your device. All rendering and data parsing happen securely inside your browser.
            </p>
          </div>

          <div className="bg-(--surface) p-6 rounded-xl border border-(--border) shadow-sm hover:shadow-lg hover:-translate-y-1 hover:border-teal-500/40 transition-all duration-300">
            <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-teal-500/10 text-teal-600 dark:text-teal-400 mb-4">
              <Sparkles className="h-6 w-6" />
            </div>
            <h3 className="text-lg font-semibold text-(--foreground) mb-2">Multiple Series Mapping</h3>
            <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
              Compare multiple parameters by plotting multiple numeric columns simultaneously on a single axis.
            </p>
          </div>

          <div className="bg-(--surface) p-6 rounded-xl border border-(--border) shadow-sm hover:shadow-lg hover:-translate-y-1 hover:border-teal-500/40 transition-all duration-300">
            <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-teal-500/10 text-teal-600 dark:text-teal-400 mb-4">
              <Key className="h-6 w-6" />
            </div>
            <h3 className="text-lg font-semibold text-(--foreground) mb-2">Highly Customizable</h3>
            <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
              Adjust color themes, grid lines, line smoothness, legends, chart titles, and axis labels on the fly.
            </p>
          </div>

          <div className="bg-(--surface) p-6 rounded-xl border border-(--border) shadow-sm hover:shadow-lg hover:-translate-y-1 hover:border-teal-500/40 transition-all duration-300">
            <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-teal-500/10 text-teal-600 dark:text-teal-400 mb-4">
              <Download className="h-6 w-6" />
            </div>
            <h3 className="text-lg font-semibold text-(--foreground) mb-2">Vector and Image Exports</h3>
            <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
              Download your configured chart as a transparent high-quality PNG image, vector SVG file, or copy the clean dataset.
            </p>
          </div>
        </div>

        {/* FAQ Section */}
        <div className="mt-20 max-w-4xl mx-auto">
          <h3 className="text-2xl font-bold text-center text-(--foreground) mb-10">Frequently Asked Questions</h3>
          <div className="space-y-6">
            <div className="bg-(--surface) p-6 rounded-xl border border-(--border) shadow-sm">
              <h4 className="font-semibold text-(--foreground) mb-2">Are my business spreadsheet files uploaded to any server?</h4>
              <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                No. The Excel to Chart converter processes data using Javascript APIs entirely in your local browser sandbox. No file chunks, data arrays, or keys are transferred over the internet.
              </p>
            </div>
            <div className="bg-(--surface) p-6 rounded-xl border border-(--border) shadow-sm">
              <h4 className="font-semibold text-(--foreground) mb-2">What file extensions are supported?</h4>
              <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                We support Excel workbooks (`.xlsx`, `.xls`) containing one or multiple sheets, as well as comma-separated values (`.csv`) plain text files.
              </p>
            </div>
            <div className="bg-(--surface) p-6 rounded-xl border border-(--border) shadow-sm">
              <h4 className="font-semibold text-(--foreground) mb-2">How should I structure my spreadsheet to make a chart?</h4>
              <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                For best results, use the first row of your spreadsheet as a Header row containing column labels. One column should contain category labels (such as months, product names, or years), and the remaining columns should contain numerical values.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
