import { jsPDF } from "jspdf";

/**
 * Creates a sample PDF File object containing structured document elements:
 * - Title & Headings (H1, H2, H3)
 * - Multi-column paragraphs
 * - Image placeholders with captions
 * - Data tables
 * - Form field labels
 * - Header / Footer artifacts
 */
export function generateSamplePdfFile() {
  const doc = new jsPDF({
    unit: "pt",
    format: "a4",
  });

  // Page 1: Annual Accessibility Audit & Reading Order Demo
  doc.setFontSize(22);
  doc.setTextColor(30, 41, 59); // dark slate
  doc.text("Annual Accessibility & PDF/UA Audit", 40, 50);

  // Header artifact
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Doc ID: ACC-2026-089 | Page 1", 420, 30);

  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text("1. Executive Summary & Reading Flow", 40, 85);

  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  const introText =
    "Accessible document standards require screen readers to navigate content in a logical sequence. Reading order is primarily determined by PDF structure tags.";
  doc.text(doc.splitTextToSize(introText, 515), 40, 110);

  // Left Column vs Right Column (Simulating multi-column layout)
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text("Key Findings (Column A)", 40, 160);

  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  const colAText =
    "Column A outlines the automated scan results. Over 85% of evaluated headings follow WCAG SC 1.3.1 standards. Contrast ratios passed all thresholds.";
  doc.text(doc.splitTextToSize(colAText, 240), 40, 180);

  // Right column (placed at X: 310)
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text("Remediation Roadmap (Column B)", 310, 160);

  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  const colBText =
    "Column B details manual remediation steps. Designers must verify figure alt text and ensure reading order tags match visual column flow.";
  doc.text(doc.splitTextToSize(colBText, 240), 310, 180);

  // Figure box simulated
  doc.setDrawColor(203, 213, 225);
  doc.setFillColor(241, 245, 249);
  doc.rect(40, 270, 515, 120, "FD");

  doc.setFontSize(11);
  doc.setTextColor(99, 102, 241);
  doc.text("[Figure 1.1: Document Reading Order Node Graph]", 140, 335);

  // Caption before/after image demo
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text("Figure 1.1 — Visualization of spatial reading paths across PDF layout nodes.", 40, 405);

  // Section 2: Table structure demo
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text("2. Compliance Metrics Summary", 40, 440);

  // Table header
  doc.setFillColor(226, 232, 240);
  doc.rect(40, 460, 515, 24, "F");
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text("Criterion", 50, 476);
  doc.text("Standard", 200, 476);
  doc.text("Status", 360, 476);
  doc.text("Score", 480, 476);

  // Table rows
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text("Logical Reading Sequence", 50, 500);
  doc.text("WCAG 1.3.2", 200, 500);
  doc.text("Pass", 360, 500);
  doc.text("95%", 480, 500);

  doc.text("Headings Structure", 50, 525);
  doc.text("WCAG 1.3.1", 200, 525);
  doc.text("Review Needed", 360, 525);
  doc.text("78%", 480, 525);

  doc.text("Image Alt Text & Captions", 50, 550);
  doc.text("WCAG 1.1.1", 200, 550);
  doc.text("Pass", 360, 550);
  doc.text("90%", 480, 550);

  // Footer artifact
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Confidential — Generated by PDF Reading-Order Preview Tool", 40, 810);

  // Page 2: Advanced Layout & Form Fields
  doc.addPage();

  doc.setFontSize(20);
  doc.setTextColor(30, 41, 59);
  doc.text("Page 2: Detailed Tag Structure & Form Accessibility", 40, 50);

  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text("3. Form Label Sequence Test", 40, 90);

  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text("Full Name:", 40, 120);
  doc.text("Email Address:", 40, 150);
  doc.text("Department / Role:", 40, 180);

  doc.text("[ Input Box: John Doe ]", 160, 120);
  doc.text("[ Input Box: john@example.com ]", 160, 150);
  doc.text("[ Select: Accessibility Lead ]", 160, 180);

  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text("4. Conclusion & Recommendations", 40, 230);

  const concText =
    "By previewing and validating reading order early in the authoring lifecycle, organizations avoid expensive PDF remediation down the line.";
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  doc.text(doc.splitTextToSize(concText, 515), 40, 255);

  // Footer page 2
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Doc ID: ACC-2026-089 | Page 2 of 2", 420, 810);

  const pdfArrayBuffer = doc.output("arraybuffer");
  const blob = new Blob([pdfArrayBuffer], { type: "application/pdf" });
  return new File([blob], "sample-reading-order-demo.pdf", {
    type: "application/pdf",
  });
}
