const ANSWER_TEXT = `
ABOUT ABOVE ACTOR ADMIT ADOPT ADULT AFTER AGAIN AGENT AGREE
AHEAD ALARM ALBUM ALERT ALIKE ALIVE ALLOW ALONE ALONG ALOUD
ALTER ANGEL ANGER ANGLE ANGRY ANKLE APART APPLE APPLY AUDIO
AVOID AWAKE AWARD AWARE
BACON BASIC BEACH BEARD BEAST BEGAN BEGIN BEING BELLY BELOW
BENCH BIRTH BLACK BLADE BLAME BLANK BLAST BLIND BLINK BLOCK
BLOOD BLOOM BOARD BONUS BOOST BOUND BRAIN BRAND BRAVE BREAD
BREAK BRICK BRIDE BRIEF BRING BROAD BROWN BRUSH BUDDY BUILD
BUILT BUNCH BURST BUYER
CABLE CANDY CARGO CARRY CATCH CAUSE CHAIN CHAIR CHARM CHART
CHASE CHEAP CHECK CHEEK CHEER CHEST CHIEF CHILD CHILL CHOSE
CIVIL CLAIM CLASS CLEAN CLEAR CLERK CLICK CLIFF CLIMB CLOCK
CLOSE CLOTH CLOUD COACH COAST COCOA COLOR COMIC COUCH COUGH
COULD COUNT COURT COVER CRAFT CRANE CRASH CRAWL CRAZY CREAM
CREEK CROSS CROWD CROWN CRUSH CURVE CYCLE
DAILY DAIRY DANCE DECAY DELAY DENSE DEPTH DIARY DIGIT DIRTY
DODGE DOING DOUBT DOZEN DRAFT DRAIN DRAMA DREAM DRESS DRIED
DRIFT DRILL DRINK DRIVE DUSTY
EAGLE EARLY EARTH EIGHT ELBOW ELDER EMPTY ENEMY ENJOY ENTER
ENTRY EQUAL ERROR EVENT EVERY EXACT EXIST EXTRA
FAINT FAIRY FAITH FALSE FANCY FAULT FAVOR FEAST FENCE FERRY
FEVER FIELD FIFTH FIFTY FIGHT FINAL FIRST FLAME FLASH FLOAT
FLOCK FLOOD FLOOR FLOUR FLUID FLUTE FOCUS FOGGY FORCE FORTH
FORTY FOUND FRAME FRESH FRIED FRONT FROST FROWN FRUIT FULLY
FUNNY
GHOST GIANT GIVEN GLASS GLIDE GLOBE GLOVE GOING GOOSE GRACE
GRADE GRAIN GRAND GRANT GRAPE GRAPH GRASS GRAVE GREAT GREEN
GRILL GRIND GROUP GROWN GUARD GUESS GUEST GUIDE
HABIT HANDY HAPPY HATCH HEARD HEART HEAVY HELLO HOBBY HONEY
HORSE HOTEL HOUSE HUMAN HUMOR HURRY
IDEAL IMAGE INDEX INNER INPUT ISSUE
JELLY JEWEL JOINT JUDGE JUICE JUICY
KNIFE KNOCK KNOWN
LABEL LABOR LARGE LASER LATER LAUGH LAYER LEARN LEAST LEAVE
LEGAL LEMON LEVEL LIGHT LIMIT LOCAL LOGIC LOOSE LOWER LUCKY
LUNCH
MAGIC MAJOR MANGO MAPLE MARCH MATCH MAYBE MAYOR MEANT MEDAL
MEDIA MELON MERCY METAL MIGHT MINOR MODEL MONEY MONTH MOTOR
MOUNT MOUSE MOUTH MOVIE MUSIC
NASTY NERVE NEVER NIGHT NOISE NORTH NOVEL NURSE
OCCUR OCEAN OFFER OFTEN ONION ORBIT ORDER OTHER OUTER OWNER
PAINT PANEL PANIC PAPER PARTY PASTA PATCH PAUSE PEACE PEACH
PEARL PEDAL PENNY PHASE PHONE PHOTO PIANO PIECE PILOT PITCH
PIZZA PLACE PLAIN PLANE PLANT PLATE POINT POWER PRESS PRICE
PRIDE PRIME PRINT PRIZE PROOF PROUD PROVE PUNCH PUPIL PURSE
QUEEN QUERY QUEST QUEUE QUICK QUIET QUITE QUOTE
RADAR RADIO RAINY RAISE RANGE RAPID RATIO REACH REACT READY
RELAX REPLY RIGHT RISKY RIVAL RIVER ROAST ROBIN ROBOT ROCKY
ROUGH ROUND ROUTE ROYAL RULER RURAL
SAINT SALAD SALON SAUCE SCALE SCENE SCOPE SCORE SCOUT SENSE
SERVE SEVEN SHADE SHAKE SHALL SHAME SHAPE SHARE SHARK SHARP
SHEEP SHEET SHELF SHELL SHIFT SHINE SHIRT SHOCK SHORE SHORT
SHOUT SIGHT SILLY SINCE SKILL SKIRT SLEEP SLICE SLIDE SLOPE
SMALL SMART SMELL SMILE SMOKE SNACK SNAKE SOLAR SOLID SOLVE
SORRY SOUND SOUTH SPACE SPARE SPARK SPEAK SPEED SPELL SPEND
SPICE SPLIT SPOON SPORT SPRAY STAFF STAGE STAMP STAND STARE
START STATE STEAM STEEL STICK STILL STOCK STONE STORE STORM
STORY STUCK STUDY STUFF STYLE SUGAR SUITE SUNNY SUPER SWEAR
SWEAT SWEEP SWEET SWING
TABLE TAKEN TASTE TEACH TEETH TEMPO THANK THEME THERE THESE
THICK THIEF THING THINK THIRD THOSE THREE THROW THUMB TIGER
TIGHT TIMER TITLE TODAY TOKEN TOOTH TOPIC TOTAL TOUCH TOUGH
TOWER TRACK TRADE TRAIL TRAIN TREAT TREND TRIAL TRIBE TRICK
TRIED TRUCK TRULY TRUNK TRUST TRUTH TWICE TWIST
UNCLE UNDER UNION UNITE UNITY UNTIL UPPER UPSET USUAL
VALID VALUE VIDEO VIRUS VISIT VITAL VIVID VOCAL VOICE VOTER
WATCH WATER WHALE WHEAT WHEEL WHERE WHICH WHILE WHITE WHOLE
WIDOW WIDTH WINDY WITCH WOMAN WORLD WORRY WORSE WORST WORTH
WOULD WOUND WRIST WRITE WRONG WROTE
YACHT YIELD YOUNG YOUTH
ZEBRA
`;

const EXTRA_TEXT = `
ABBEY ABIDE ABYSS ACORN ACUTE ADAPT ADMIN ADOBE ADORE AGILE
AGING AGONY AISLE ALGAE ALIAS ALIBI ALIEN ALIGN ALLEY ALLOY
ALPHA ALTAR AMBER AMEND AMPLE AMUSE ANIME ANNEX ANNOY APRON
ARENA ARGUE ARISE ARMOR AROMA ARRAY ASHES ASIDE ASSET ATTIC
AUDIT AWAIT AWFUL
BADGE BADLY BAGEL BAKER BALMY BANJO BARGE BARON BASIL BASIN
BATCH BATON BEGUN BEIGE BERRY BIKER BINGE BINGO BIRCH BLAND
BLAZE BLEAK BLEED BLEND BLESS BLISS BLITZ BLOKE BLOND BLOWN
BLUFF BLUNT BLUSH BOAST BOGUS BOOTH BOSSY BOTCH BOXER BRACE
BRAID BRAKE BRASS BRAVO BRAWL BREED BRIBE BRINK BRISK BROKE
BROOK BROOM BROTH BRUTE BUGGY BULGE BULKY BULLY BUMPY BUNNY
CABIN CACHE CADET CAMEL CAMEO CANAL CANNY CANOE CANON CAROL
CARVE CEASE CEDAR CELLO CHALK CHAMP CHANT CHAOS CHESS CHILI
CHIME CHIRP CHOIR CHOKE CHORD CHORE CHUNK CIDER CIGAR CIVIC
CLAMP CLANG CLASH CLASP CLING CLOAK CLONE CLOVE CLOWN COBRA
COLON COMBO COMET COMFY CORAL CORGI CORNY CRAMP CRANK CRATE
CRAVE CRAZE CREED CREPE CREPT CREST CRIME CRISP CROOK CRUDE
CRUEL CRUMB CRUST CRYPT CUBIC CURLY CURRY CURSE
DADDY DAISY DANDY DEBIT DEBUT DECAL DECOR DEFER DELTA DELVE
DEMON DENIM DEPOT DETER DEVIL DINER DISCO DITCH DIVER DIZZY
DONOR DONUT DOUGH DRANK DRAPE DRAWN DREAD DRONE DROVE DRYER
DUMMY DWARF DWELL
EAGER EASEL EATEN EATER EERIE EJECT ELECT ELITE ELOPE ELUDE
EMAIL EMBED EMBER ENACT EPOCH EQUIP ERASE ERODE ERUPT ESSAY
EVADE EVOKE EXCEL EXILE
FABLE FARCE FATAL FELON FEMUR FERAL FETCH FEWER FIBER FIEND
FIERY FILET FINCH FISHY FLAIR FLAKE FLAKY FLANK FLARE FLEET
FLESH FLICK FLING FLINT FLIRT FLOSS FLOWN FLUFF FLUKE FLUNG
FLUNK FLUSH FOCAL FOLLY FORGE FORGO FORUM FOYER FRAIL FRANK
FREAK FRILL FROCK FROTH FROZE FUDGE FUNGI FUNKY FUZZY
GAMER GAMMA GAUGE GAUNT GAUZE GECKO GEEKY GENIE GENRE GHOUL
GIDDY GIVER GIZMO GLAND GLARE GLAZE GLEAM GLOAT GLOOM GLORY
GLOSS GOODY GOOEY GOOFY GRAFT GRASP GRATE GRAVY GRAZE GREED
GREET GRIEF GRIME GRIPE GROAN GROOM GROSS GROUT GROVE GROWL
GRUFF GRUNT GUAVA GUILD GUILE GUILT GULLY
HAIKU HAIRY HARSH HASTE HASTY HAUNT HAVEN HAVOC HAZEL HEDGE
HEFTY HEIST HELIX HENCE HERON HIKER HILLY HINGE HIPPO HITCH
HOARD HOLLY HONOR HOUND HOVER HUMID HUNCH HUSKY
ICING IDIOM IGLOO IMPLY INBOX INCUR INEPT INFER INLET IRATE
IRONY ITCHY IVORY
JAZZY JERKY JIFFY JOKER JOLLY JUMBO JUMPY JUROR
KARMA KAYAK KEBAB KHAKI KIOSK KITTY KNACK KNEAD KNEEL KNELT
KOALA
LADLE LAGER LANCE LANKY LAPEL LAPSE LASSO LATCH LATHE LATTE
LEAKY LEAPT LEASE LEASH LEECH LEFTY LEDGE LEVER LILAC LIMBO
LINEN LIVER LIVID LLAMA LOBBY LODGE LOFTY LOGIN LONER LOTUS
LOUSY LOVER LOWLY LOYAL LUMPY LUNAR LUNGE LURCH LYING LYRIC
MACRO MADAM MADLY MAIZE MANGA MANIA MANIC MANOR MARSH MASON
MAUVE MEDIC MERGE MERIT MERRY METER MIDST MIMIC MINCE MINER
MINTY MINUS MISTY MOCHA MODEM MOGUL MOIST MOLDY MOODY MOOSE
MORAL MOTEL MOTIF MOTTO MOUND MOURN MOWER MUDDY MUMMY MUNCH
MURAL MURKY
NAIVE NANNY NAVEL NEIGH NERDY NEWER NEWLY NICER NICHE NIECE
NIFTY NINJA NINTH NOBLE NOISY NOMAD NOTCH NUDGE NUTTY NYLON
OASIS ODDLY OLDER OLIVE OMEGA ONSET OPERA OPTIC ORGAN OTTER
OUGHT OUNCE OVERT OXIDE OZONE
PANDA PARKA PASTE PASTY PATIO PATTY PECAN PERCH PERIL PERKY
PESKY PETAL PETTY PHONY PIGGY PINCH PINKY PIPER PIVOT PIXEL
PIXIE PLAID PLANK PLAZA PLEAD PLUCK PLUME PLUMP PLUSH POKER
POLAR POOCH POPPY PORCH POUCH POUND PRANK PRAWN PRIOR PRISM
PROBE PRONE PRONG PROWL PROXY PRUNE PUDGY PUFFY PULSE PUPPY
PUREE PURGE PUTTY
QUACK QUAIL QUAKE QUALM QUART QUELL QUILT QUIRK QUOTA
RABID RACER RALLY RAMEN RANCH RASPY RAVEN RAZOR REALM REBEL
RECAP RECUR REHAB REIGN RELAY RELIC RENEW REPAY REPEL RERUN
RESET RETRO RETRY REUSE REVEL RHINO RHYME RIDER RIDGE RIFLE
RIGID RINSE RIPEN RISEN ROACH ROGUE ROOMY ROUSE ROVER ROWDY
RUGBY RUMOR RUPEE RUSTY
SADLY SALSA SAMBA SANDY SATIN SAUNA SAVOR SAVVY SCALD SCALP
SCARE SCARF SCARY SCENT SCOLD SCOOP SCOOT SCORN SCRAP SCREW
SCRUB SCUBA SCUFF SEDAN SEIZE SETUP SEWER SHACK SHADY SHAFT
SHAKY SHAWL SHEAR SHEER SHINY SHOOK SHOVE SHOWN SHRED SHRUB
SHRUG SHUSH SILKY SIREN SIXTH SIXTY SKATE SKIER SKUNK SLACK
SLANG SLANT SLASH SLATE SLEEK SLEET SLIMY SLING SLOTH SLUMP
SLUSH SMACK SMASH SNAIL SNEAK SNIFF SNOOP SNORE SNORT SNOWY
SOBER SOGGY SONIC SPADE SPAWN SPEAR SPECK SPICY SPIKE SPIKY
SPILL SPINE SPIRE SPITE SPOIL SPOKE SPOOF SPOOK SQUAD SQUAT
STAIN STAIR STAKE STALE STALK STALL STEAK STEEP STEER STERN
STIFF STING STOMP STOOD STOOL STOUT STOVE STRAP STRAY STRUT
STUMP STUNG STUNT SUEDE SURGE SUSHI SWAMP SWARM SWELL SWEPT
SWIFT SWIRL SWISH SWOOP SWORD SWORN SYRUP
TABBY TACKY TALLY TANGO TANGY TARDY TASTY TAUNT TEASE TEDDY
TEMPT TENTH TEPID THEFT THIGH THORN THREW TIARA TIDAL TIMID
TITAN TOAST TONIC TOPAZ TORCH TORSO TOWEL TOXIC TOXIN TRACE
TRAIT TREAD TROLL TROOP TROUT TRUCE TULIP TUMMY TUNIC TURBO
TUTOR TWEAK TWEET TWIRL
UDDER ULCER ULTRA UNCUT UNDUE UNFIT UNIFY UNLIT UNMET UNTIE
UNZIP URBAN USAGE USHER USING UTTER
VAGUE VALET VALVE VAPOR VAULT VEGAN VENOM VENUE VERGE VERSE
VEXED VIGOR VILLA VINYL VIPER VIRAL VISOR VISTA VOGUE VOUCH
VOWEL
WACKY WAFER WAGER WAGON WAIST WAIVE WALTZ WASTE WEARY WEAVE
WEDGE WEIGH WEIRD WHACK WHIFF WHINE WHIRL WHISK WHOSE WIDEN
WIDER WINCE WINCH WISER WISPY WITTY WOKEN WOVEN WRATH WRECK
YEARN YEAST YUMMY
ZESTY ZILCH
`;

export const ANSWERS = ANSWER_TEXT.trim().split(/\s+/);

export const ALLOWED = new Set([...ANSWERS, ...EXTRA_TEXT.trim().split(/\s+/)]);
