import { CheckCircle2, Download, Languages, ShieldCheck } from "lucide-react";

const features = [
  ["Byte-first conversion", "Files are read as ArrayBuffers, decoded, re-encoded, and downloaded from generated bytes.", CheckCircle2],
  ["Multilingual preview", "Unicode text, Hindi, Chinese, emoji, CSV, JSON, logs, and code previews stay scroll-safe.", Languages],
  ["Validation workflow", "BOM, confidence, replacement characters, and target encoding limitations are surfaced before export.", ShieldCheck],
  ["Copy and download", "Copy the converted text or download each converted file with a preserved filename suffix.", Download],
];

export default function Features() {
  return (
    <section className="mx-auto mt-5 grid max-w-7xl gap-3 sm:grid-cols-2 xl:grid-cols-4">
      {features.map(([title, text, Icon]) => (
        <article key={title} className="animate-fade-up min-w-0 rounded-2xl border border-[var(--border)] bg-[var(--card)]/80 p-4 shadow-lg backdrop-blur-xl">
          <Icon className="mb-3 h-5 w-5 text-cyan-500" />
          <h3 className="break-words text-sm font-black text-[var(--foreground)]">{title}</h3>
          <p className="mt-2 break-words text-xs leading-5 text-[var(--muted-foreground)]">{text}</p>
        </article>
      ))}
    </section>
  );
}
