export const SIGNAL_DATA_AS_OF = "2026-07-22";

export const SIGNAL_CATEGORIES = Object.freeze([
  "All",
  "AI & Content",
  "Documents",
  "Business",
  "Developer",
  "Security",
]);

export const SIGNAL_CATALOG = Object.freeze([
  {
    slug: "ai-content-detector",
    name: "AI content detector",
    query: "ai detector",
    category: "AI & Content",
    summary: "People want clearer signals about whether text was likely generated or heavily assisted by AI.",
    searchVolume: 2740000,
    opportunityScore: 94,
    competition: "High",
    momentum: "Surging",
    region: "Worldwide",
    relatedPaths: ["/tools/all/text-compare", "/tools/all/word-character-counter"],
    actions: ["Confidence-based detector", "Document scan", "Publisher verification report"],
  },
  {
    slug: "plagiarism-checker",
    name: "Plagiarism checker",
    query: "plagiarism checker",
    category: "AI & Content",
    summary: "Education, publishing, and marketing teams continue to need source-aware originality checks.",
    searchVolume: 450000,
    opportunityScore: 89,
    competition: "High",
    momentum: "Rising",
    region: "Worldwide",
    relatedPaths: ["/tools/all/word-character-counter", "/tools/all/citation-generator"],
    actions: ["Similarity report", "Citation helper", "Private document workflow"],
  },
  {
    slug: "ai-humanizer",
    name: "AI writing humanizer",
    query: "ai humanizer",
    category: "AI & Content",
    summary: "Users are looking for clearer, more natural revisions with tone and readability controls.",
    searchVolume: 368000,
    opportunityScore: 90,
    competition: "High",
    momentum: "Surging",
    region: "Worldwide",
    relatedPaths: ["/tools/all/text-summarizer", "/tools/all/text-compare"],
    actions: ["Tone presets", "Side-by-side revisions", "Readability explanation"],
  },
  {
    slug: "ai-logo-generator",
    name: "AI logo generator",
    query: "ai logo generator",
    category: "Business",
    summary: "Early-stage teams want fast identity concepts that can become a complete brand starter kit.",
    searchVolume: 110000,
    opportunityScore: 81,
    competition: "High",
    momentum: "Rising",
    region: "Worldwide",
    relatedPaths: ["/tools/all/brand-kit-manager", "/tools/all/color-palette-from-image"],
    actions: ["Logo directions", "Color and type system", "Social asset export"],
  },
  {
    slug: "edit-pdf-online",
    name: "Edit PDF online",
    query: "edit pdf",
    category: "Documents",
    summary: "A complete, private browser workflow can consolidate common PDF editing and conversion jobs.",
    searchVolume: 90500,
    opportunityScore: 84,
    competition: "High",
    momentum: "Stable demand",
    region: "Worldwide",
    relatedPaths: ["/altflovepdf", "/tools/all/pdf-to-word-converter"],
    actions: ["Edit and annotate", "Sign and redact", "Convert and compress"],
  },
  {
    slug: "whois-domain-lookup",
    name: "WHOIS and domain lookup",
    query: "whois",
    category: "Developer",
    summary: "Domain owners need one readable report for registration, DNS, SSL, and operational risks.",
    searchVolume: 74000,
    opportunityScore: 78,
    competition: "Medium",
    momentum: "Stable demand",
    region: "Worldwide",
    relatedPaths: ["/tools/all/domain-checker", "/tools/all/web-speed-checker"],
    actions: ["RDAP lookup", "DNS health", "Expiry and SSL alerts"],
  },
  {
    slug: "dns-health-check",
    name: "DNS health check",
    query: "dns checker",
    category: "Developer",
    summary: "Global DNS visibility and plain-language fixes are useful to developers and small businesses.",
    searchVolume: 40500,
    opportunityScore: 80,
    competition: "Medium",
    momentum: "Rising",
    region: "Worldwide",
    relatedPaths: ["/tools/all/domain-checker", "/tools/all/web-speed-checker"],
    actions: ["Propagation map", "SPF, DKIM, and DMARC", "Shareable health report"],
  },
  {
    slug: "ai-headshot-generator",
    name: "AI headshot generator",
    query: "ai headshot generator",
    category: "AI & Content",
    summary: "Professional profile imagery remains a strong creator, hiring, and personal-brand use case.",
    searchVolume: 33100,
    opportunityScore: 76,
    competition: "High",
    momentum: "Rising",
    region: "Worldwide",
    relatedPaths: ["/tools/all/ai-passport-photo-maker", "/tools/all/profile-picture-maker"],
    actions: ["Professional presets", "Background cleanup", "Profile-ready crops"],
  },
  {
    slug: "meeting-summary-ai",
    name: "AI meeting summaries",
    query: "ai meeting summary",
    category: "Business",
    summary: "Teams want transcripts converted into decisions, owners, deadlines, and follow-up messages.",
    searchVolume: null,
    opportunityScore: 83,
    competition: "High",
    momentum: "Rising",
    region: "Worldwide",
    relatedPaths: ["/tools/all/meeting-transcript-action-extractor", "/tools/all/meeting-agenda-builder"],
    actions: ["Transcript summary", "Decision log", "Action and follow-up export"],
  },
  {
    slug: "startup-idea-validator",
    name: "Startup idea validator",
    query: "startup idea validator",
    category: "Business",
    summary: "Founders need an evidence-led path from a rough concept to a testable MVP and market thesis.",
    searchVolume: null,
    opportunityScore: 82,
    competition: "Medium",
    momentum: "Rising",
    region: "Worldwide",
    relatedPaths: ["/tools/all/random-business-idea", "/tools/all/startup-name-generator"],
    actions: ["Demand and risk score", "Competitor map", "MVP experiment plan"],
  },
  {
    slug: "website-accessibility-audit",
    name: "Website accessibility audit",
    query: "website accessibility checker",
    category: "Developer",
    summary: "Teams need actionable WCAG checks that connect each issue to an understandable fix.",
    searchVolume: null,
    opportunityScore: 79,
    competition: "Medium",
    momentum: "Rising",
    region: "Worldwide",
    relatedPaths: ["/tools/all/web-speed-checker", "/tools/all/color-contrast-checker"],
    actions: ["Automated audit", "Keyboard checklist", "Shareable remediation report"],
  },
  {
    slug: "two-factor-authenticator",
    name: "Private 2FA authenticator",
    query: "2fa authenticator",
    category: "Security",
    summary: "A transparent local-only authenticator can help users generate and understand time-based codes safely.",
    searchVolume: null,
    opportunityScore: 72,
    competition: "High",
    momentum: "Stable demand",
    region: "Worldwide",
    relatedPaths: ["/tools/all/password-generator", "/tools/all/password-strength-checker"],
    actions: ["Local TOTP", "No secret storage", "Backup-code guidance"],
  },
]);

export function getSignalBySlug(slug) {
  return SIGNAL_CATALOG.find((signal) => signal.slug === slug) || null;
}

export function formatSearchVolume(value) {
  if (!Number.isFinite(value)) return "Researching";
  if (value >= 1000000) return `${(value / 1000000).toFixed(value >= 10000000 ? 0 : 1)}M`;
  if (value >= 1000) return `${(value / 1000).toFixed(value >= 100000 ? 0 : 1)}K`;
  return String(value);
}
