// src/tools/constellation-finder/data.js

export const CONSTELLATIONS_DATA = [
  {
    id: "orion",
    name: "Orion",
    subtitle: "The Hunter",
    season: "Winter",
    ra: "05h 35m",
    dec: "+05° 23'",
    area: "594 sq deg",
    bestSeason: "Dec – Mar",
    genitive: "Orionis",
    brightestStar: "Rigel (β Ori) – 0.18 mag",
    iconName: "Compass",
    description: "Orion is one of the most recognizable constellations in the night sky, straddling the celestial equator. According to Greek mythology, Orion was a giant, handsome hunter who boasted he could slay any beast on Earth.",
    mythology: "Gaia sent a giant scorpion (Scorpius) to defeat Orion after his boast. Zeus placed both in the sky, positioned 180° apart so they never occupy the night sky at the same time.",
    stars: [
      { name: "Betelgeuse", type: "Orange Supergiant", mag: 0.50, color: "#fb923c", ra: "05h 55m", dec: "+07° 24'", temp: "M2Iab" },
      { name: "Bellatrix", type: "Blue Giant", mag: 1.64, color: "#818cf8", ra: "05h 25m", dec: "+06° 20'", temp: "B2III" },
      { name: "Alnitak", type: "Blue Supergiant", mag: 1.89, color: "#38bdf8", ra: "05h 40m", dec: "-01° 56'", temp: "O9.5Iab" },
      { name: "Alnilam", type: "Blue Supergiant", mag: 1.70, color: "#38bdf8", ra: "05h 36m", dec: "-01° 12'", temp: "B0Iab" },
      { name: "Mintaka", type: "Multiple Star System", mag: 2.25, color: "#818cf8", ra: "05h 32m", dec: "-00° 17'", temp: "O9.5II" },
      { name: "Saiph", type: "Blue Giant", mag: 2.06, color: "#60a5fa", ra: "05h 47m", dec: "-09° 40'", temp: "B0.5Iab" },
      { name: "Rigel", type: "Blue Supergiant", mag: 0.18, color: "#38bdf8", ra: "05h 14m", dec: "-08° 12'", temp: "B8Ia" },
    ],
    starNodes: [
      { id: 0, x: 600, y: 280, name: "Betelgeuse", mag: 0.5 }, // Shoulder L
      { id: 1, x: 680, y: 270, name: "Bellatrix", mag: 1.6 },  // Shoulder R
      { id: 2, x: 620, y: 345, name: "Alnitak", mag: 1.9 },    // Belt L
      { id: 3, x: 640, y: 340, name: "Alnilam", mag: 1.7 },    // Belt C
      { id: 4, x: 660, y: 335, name: "Mintaka", mag: 2.2 },    // Belt R
      { id: 5, x: 610, y: 420, name: "Saiph", mag: 2.1 },      // Foot L
      { id: 6, x: 675, y: 410, name: "Rigel", mag: 0.18 },     // Foot R
    ],
    lines: [[0, 1], [0, 2], [1, 4], [2, 3], [3, 4], [2, 5], [4, 6], [5, 6]]
  },
  {
    id: "ursa-major",
    name: "Ursa Major",
    subtitle: "The Great Bear",
    season: "Spring",
    ra: "11h 15m",
    dec: "+55° 00'",
    area: "1280 sq deg",
    bestSeason: "Apr – Jun",
    genitive: "Ursae Majoris",
    brightestStar: "Alioth (ε UMa) – 1.76 mag",
    iconName: "Shield",
    description: "Ursa Major is the third largest constellation and home to the famous 'Big Dipper' asterism. It is a circumpolar constellation in northern latitudes, visible year-round.",
    mythology: "In Roman myth, Jupiter fell in love with Callisto. Juno transformed Callisto into a bear out of jealousy. Jupiter later placed Callisto and her son Arcas safely in the starry sky.",
    stars: [
      { name: "Dubhe", type: "Orange Giant", mag: 1.79, color: "#fb923c", ra: "11h 03m", dec: "+61° 45'", temp: "K0III" },
      { name: "Merak", type: "Subgiant Star", mag: 2.37, color: "#f1f5f9", ra: "11h 01m", dec: "+56° 22'", temp: "A1V" },
      { name: "Phecda", type: "Main-Sequence", mag: 2.44, color: "#f1f5f9", ra: "11h 53m", dec: "+53° 41'", temp: "A0Ve" },
      { name: "Megrez", type: "Main-Sequence", mag: 3.31, color: "#ffffff", ra: "12h 15m", dec: "+57° 01'", temp: "A3V" },
      { name: "Alioth", type: "White Main-Sequence", mag: 1.76, color: "#e2e8f0", ra: "12h 54m", dec: "+55° 57'", temp: "A0p" },
      { name: "Mizar", type: "Quadruple Star System", mag: 2.23, color: "#cbd5e1", ra: "13h 23m", dec: "+54° 55'", temp: "A1V" },
      { name: "Alkaid", type: "Blue Main-Sequence", mag: 1.86, color: "#38bdf8", ra: "13h 47m", dec: "+49° 18'", temp: "B3V" },
    ],
    starNodes: [
      { id: 0, x: 220, y: 120, name: "Dubhe", mag: 1.8 },
      { id: 1, x: 220, y: 170, name: "Merak", mag: 2.4 },
      { id: 2, x: 280, y: 180, name: "Phecda", mag: 2.4 },
      { id: 3, x: 290, y: 130, name: "Megrez", mag: 3.3 },
      { id: 4, x: 340, y: 115, name: "Alioth", mag: 1.76 },
      { id: 5, x: 390, y: 95, name: "Mizar", mag: 2.2 },
      { id: 6, x: 440, y: 70, name: "Alkaid", mag: 1.86 },
    ],
    lines: [[0, 1], [1, 2], [2, 3], [3, 0], [3, 4], [4, 5], [5, 6]]
  },
  {
    id: "cassiopeia",
    name: "Cassiopeia",
    subtitle: "The Seated Queen",
    season: "Fall",
    ra: "01h 00m",
    dec: "+60° 00'",
    area: "598 sq deg",
    bestSeason: "Oct – Dec",
    genitive: "Cassiopeiae",
    brightestStar: "Schedar (α Cas) – 2.24 mag",
    iconName: "Sparkles",
    description: "Cassiopeia is instantly recognized by its distinctive 'W' shape formed by five bright stars. Positioned opposite the Big Dipper across Polaris, it spans rich Milky Way star fields.",
    mythology: "Cassiopeia was a vain Ethiopian queen who claimed her daughter Andromeda was more beautiful than the sea Nereids. Poseidon punished her by placing her on a celestial throne.",
    stars: [
      { name: "Caph", type: "Yellow-White Giant", mag: 2.28, color: "#fde047", ra: "00h 09m", dec: "+59° 08'", temp: "F2III" },
      { name: "Schedar", type: "Orange Giant", mag: 2.24, color: "#fb923c", ra: "00h 40m", dec: "+56° 32'", temp: "K0IIIa" },
      { name: "Gamma Cas", type: "Eruptive Variable", mag: 2.47, color: "#38bdf8", ra: "00h 56m", dec: "+60° 43'", temp: "B0IV" },
      { name: "Ruchbah", type: "Eclipsing Binary", mag: 2.66, color: "#cbd5e1", ra: "01h 25m", dec: "+60° 14'", temp: "A5IV" },
      { name: "Segin", type: "Blue-White Giant", mag: 3.37, color: "#818cf8", ra: "01h 54m", dec: "+63° 40'", temp: "B3V" },
    ],
    starNodes: [
      { id: 0, x: 500, y: 110, name: "Caph", mag: 2.3 },
      { id: 1, x: 535, y: 145, name: "Schedar", mag: 2.2 },
      { id: 2, x: 575, y: 100, name: "γ Cas", mag: 2.5 },
      { id: 3, x: 610, y: 130, name: "Ruchbah", mag: 2.7 },
      { id: 4, x: 645, y: 90, name: "Segin", mag: 3.4 },
    ],
    lines: [[0, 1], [1, 2], [2, 3], [3, 4]]
  },
  {
    id: "cygnus",
    name: "Cygnus",
    subtitle: "The Swan",
    season: "Summer",
    ra: "20h 35m",
    dec: "+42° 00'",
    area: "804 sq deg",
    bestSeason: "Jul – Oct",
    genitive: "Cygni",
    brightestStar: "Deneb (α Cyg) – 1.25 mag",
    iconName: "Telescope",
    description: "Cygnus glides gracefully down the plane of the Milky Way, forming the famous 'Northern Cross' asterism anchored by brilliant supergiant Deneb.",
    mythology: "Zeus disguised himself as a majestic swan to visit Leda, Queen of Sparta. Another tale connects it to Orpheus transformed into a swan upon death.",
    stars: [
      { name: "Deneb", type: "White Supergiant", mag: 1.25, color: "#f8fafc", ra: "20h 41m", dec: "+45° 16'", temp: "A2Ia" },
      { name: "Sadr", type: "Supergiant Star", mag: 2.23, color: "#fde047", ra: "20h 22m", dec: "+40° 15'", temp: "F8Iab" },
      { name: "Albireo", type: "Double Star", mag: 3.05, color: "#fb923c", ra: "19h 30m", dec: "+27° 57'", temp: "K3II+B9V" },
      { name: "Fawaris", type: "Blue-White Star", mag: 2.86, color: "#38bdf8", ra: "19h 44m", dec: "+45° 07'", temp: "B9III" },
      { name: "Gienah", type: "Orange Giant", mag: 2.48, color: "#fb923c", ra: "20h 46m", dec: "+33° 58'", temp: "K0III" },
    ],
    starNodes: [
      { id: 0, x: 780, y: 80, name: "Deneb", mag: 1.25 },
      { id: 1, x: 750, y: 135, name: "Sadr", mag: 2.2 },
      { id: 2, x: 710, y: 200, name: "Albireo", mag: 3.0 },
      { id: 3, x: 690, y: 115, name: "Fawaris", mag: 2.8 },
      { id: 4, x: 810, y: 155, name: "Gienah", mag: 2.5 },
    ],
    lines: [[0, 1], [1, 2], [3, 1], [1, 4]]
  },
  {
    id: "lyra",
    name: "Lyra",
    subtitle: "The Lyre",
    season: "Summer",
    ra: "18h 50m",
    dec: "+36° 00'",
    area: "286 sq deg",
    bestSeason: "Jul – Sep",
    genitive: "Lyrae",
    brightestStar: "Vega (α Lyr) – 0.03 mag",
    iconName: "Star",
    description: "Lyra is a small constellation dominated by Vega, one of the brightest stars in the northern sky and a key vertex of the Summer Triangle asterism.",
    mythology: "Lyra represents the enchanted lyre crafted by Hermes from a tortoise shell and presented to Orpheus, whose music enchanted all living things.",
    stars: [
      { name: "Vega", type: "White Main-Sequence", mag: 0.03, color: "#f8fafc", ra: "18h 36m", dec: "+38° 47'", temp: "A0V" },
      { name: "Sheliak", type: "Beta Lyrae Variable", mag: 3.52, color: "#818cf8", ra: "18h 50m", dec: "+33° 21'", temp: "B2V" },
      { name: "Sulafat", type: "Blue Giant", mag: 3.25, color: "#38bdf8", ra: "18h 58m", dec: "+32° 41'", temp: "B9III" },
      { name: "δ Lyr", type: "Multiple Star", mag: 4.30, color: "#fde047", ra: "18h 54m", dec: "+36° 53'", temp: "M4II" },
    ],
    starNodes: [
      { id: 0, x: 910, y: 80, name: "Vega", mag: 0.03 },
      { id: 1, x: 890, y: 130, name: "Sheliak", mag: 3.5 },
      { id: 2, x: 935, y: 135, name: "Sulafat", mag: 3.25 },
      { id: 3, x: 930, y: 95, name: "δ Lyr", mag: 4.3 },
    ],
    lines: [[0, 1], [1, 2], [2, 3], [3, 0]]
  },
  {
    id: "leo",
    name: "Leo",
    subtitle: "The Lion",
    season: "Spring",
    ra: "10h 40m",
    dec: "+15° 00'",
    area: "947 sq deg",
    bestSeason: "Mar – May",
    genitive: "Leonis",
    brightestStar: "Regulus (α Leo) – 1.36 mag",
    iconName: "Award",
    description: "Leo features a distinct 'Sickle' pattern outlining the lion's mane, anchored by Regulus — the 'Little King' star sitting close to the ecliptic plane.",
    mythology: "Representing the fierce Nemean Lion whose hide was impervious to weapons. Hercules defeated the beast as his first labor.",
    stars: [
      { name: "Regulus", type: "Quadruple Star", mag: 1.36, color: "#38bdf8", ra: "10h 08m", dec: "+11° 58'", temp: "B7V" },
      { name: "Algieba", type: "Binary Giant System", mag: 2.01, color: "#fb923c", ra: "10h 20m", dec: "+19° 50'", temp: "K0III" },
      { name: "Adhafera", type: "Giant Star", mag: 3.44, color: "#fde047", ra: "10h 16m", dec: "+23° 25'", temp: "F0III" },
      { name: "Zosma", type: "Subgiant Star", mag: 2.56, color: "#f1f5f9", ra: "11h 14m", dec: "+20° 31'", temp: "A4IV" },
      { name: "Denebola", type: "Main-Sequence", mag: 2.14, color: "#e2e8f0", ra: "11h 49m", dec: "+14° 34'", temp: "A3V" },
    ],
    starNodes: [
      { id: 0, x: 180, y: 340, name: "Regulus", mag: 1.36 },
      { id: 1, x: 195, y: 285, name: "Algieba", mag: 2.0 },
      { id: 2, x: 220, y: 255, name: "Adhafera", mag: 3.4 },
      { id: 3, x: 275, y: 285, name: "Zosma", mag: 2.56 },
      { id: 4, x: 330, y: 320, name: "Denebola", mag: 2.14 },
    ],
    lines: [[0, 1], [1, 2], [1, 3], [3, 4], [0, 3]]
  },
  {
    id: "gemini",
    name: "Gemini",
    subtitle: "The Twins",
    season: "Winter",
    ra: "07h 00m",
    dec: "+20° 00'",
    area: "514 sq deg",
    bestSeason: "Jan – Mar",
    genitive: "Geminorum",
    brightestStar: "Pollux (β Gem) – 1.14 mag",
    iconName: "Star",
    description: "Gemini is easily spotted by twin stars Castor and Pollux standing side-by-side near the Milky Way edge.",
    mythology: "Castor and Pollux were inseparable twin brothers. When mortal Castor fell in battle, Pollux begged Zeus to let them share immortality together.",
    stars: [
      { name: "Castor", type: "Sextuple Star System", mag: 1.58, color: "#e2e8f0", ra: "07h 34m", dec: "+31° 53'", temp: "A1V" },
      { name: "Pollux", type: "Orange Giant", mag: 1.14, color: "#fb923c", ra: "07h 45m", dec: "+28° 01'", temp: "K0III" },
      { name: "Wasat", type: "Subgiant Star", mag: 3.53, color: "#fde047", ra: "07h 20m", dec: "+21° 58'", temp: "F2IV" },
      { name: "Mebsuta", type: "Supergiant", mag: 2.98, color: "#fde047", ra: "06h 43m", dec: "+25° 07'", temp: "G8Ib" },
      { name: "Alhena", type: "Subgiant Star", mag: 1.93, color: "#38bdf8", ra: "06h 37m", dec: "+16° 23'", temp: "A0IV" },
    ],
    starNodes: [
      { id: 0, x: 410, y: 260, name: "Castor", mag: 1.58 },
      { id: 1, x: 455, y: 268, name: "Pollux", mag: 1.14 },
      { id: 2, x: 425, y: 325, name: "Wasat", mag: 3.5 },
      { id: 3, x: 470, y: 335, name: "Mebsuta", mag: 3.0 },
      { id: 4, x: 395, y: 380, name: "Alhena", mag: 1.93 },
    ],
    lines: [[0, 1], [0, 2], [1, 3], [2, 4]]
  },
  {
    id: "taurus",
    name: "Taurus",
    subtitle: "The Bull",
    season: "Winter",
    ra: "04h 42m",
    dec: "+16° 00'",
    area: "797 sq deg",
    bestSeason: "Nov – Feb",
    genitive: "Tauri",
    brightestStar: "Aldebaran (α Tau) – 0.87 mag",
    iconName: "Globe",
    description: "Taurus features the fiery red eye of Aldebaran and two of the sky's most famous open star clusters: the Pleiades and the Hyades.",
    mythology: "Zeus assumed the form of a majestic white bull with golden horns to entice Europa across the Mediterranean Sea to Crete.",
    stars: [
      { name: "Pleiades", type: "Star Cluster Anchor", mag: 1.60, color: "#38bdf8", ra: "03h 47m", dec: "+24° 06'", temp: "B7IIIe" },
      { name: "Aldebaran", type: "Orange Giant", mag: 0.87, color: "#fb923c", ra: "04h 35m", dec: "+16° 30'", temp: "K5III" },
      { name: "Elnath", type: "Giant Star", mag: 1.65, color: "#818cf8", ra: "05h 26m", dec: "+28° 36'", temp: "B7III" },
      { name: "Tianguan", type: "Spectroscopic Binary", mag: 3.00, color: "#38bdf8", ra: "05h 37m", dec: "+21° 08'", temp: "B2IVe" },
    ],
    starNodes: [
      { id: 0, x: 750, y: 260, name: "Pleiades", mag: 1.6 },
      { id: 1, x: 800, y: 300, name: "Aldebaran", mag: 0.87 },
      { id: 2, x: 855, y: 250, name: "Elnath", mag: 1.65 },
      { id: 3, x: 870, y: 320, name: "Tianguan", mag: 3.0 },
    ],
    lines: [[0, 1], [1, 2], [1, 3]]
  },
  {
    id: "pegasus",
    name: "Pegasus",
    subtitle: "The Winged Horse",
    season: "Fall",
    ra: "22h 40m",
    dec: "+20° 00'",
    area: "1121 sq deg",
    bestSeason: "Sep – Nov",
    genitive: "Pegasi",
    brightestStar: "Enif (ε Peg) – 2.39 mag",
    iconName: "Sparkles",
    description: "Pegasus is dominated by the 'Great Square of Pegasus', a prominent landmark used by stargazers to navigate autumn skies.",
    mythology: "The mythical winged stallion born from Medusa's neck after she was vanquished by Perseus. Bellerophon rode Pegasus to slay the Chimera.",
    stars: [
      { name: "Scheat", type: "Red Giant Variable", mag: 2.44, color: "#f43f5e", ra: "23h 03m", dec: "+28° 04'", temp: "M2III" },
      { name: "Alpheratz", type: "Subgiant Star", mag: 2.06, color: "#38bdf8", ra: "00h 08m", dec: "+29° 05'", temp: "B8IV" },
      { name: "Markab", type: "Subgiant Star", mag: 2.49, color: "#e2e8f0", ra: "23h 04m", dec: "+15° 12'", temp: "A0IV" },
      { name: "Algenib", type: "Pulsating Variable", mag: 2.83, color: "#38bdf8", ra: "00h 13m", dec: "+15° 11'", temp: "B2IV" },
      { name: "Enif", type: "Orange Supergiant", mag: 2.39, color: "#fb923c", ra: "21h 44m", dec: "+09° 52'", temp: "K2Ib" },
    ],
    starNodes: [
      { id: 0, x: 970, y: 250, name: "Scheat", mag: 2.44 },
      { id: 1, x: 1050, y: 255, name: "Alpheratz", mag: 2.06 },
      { id: 2, x: 975, y: 330, name: "Markab", mag: 2.49 },
      { id: 3, x: 1055, y: 335, name: "Algenib", mag: 2.83 },
      { id: 4, x: 915, y: 370, name: "Enif", mag: 2.39 },
    ],
    lines: [[0, 1], [1, 3], [3, 2], [2, 0], [2, 4]]
  },
  {
    id: "andromeda",
    name: "Andromeda",
    subtitle: "The Chained Princess",
    season: "Fall",
    ra: "00h 48m",
    dec: "+38° 00'",
    area: "722 sq deg",
    bestSeason: "Oct – Dec",
    genitive: "Andromedae",
    brightestStar: "Alpheratz (α And) – 2.07 mag",
    iconName: "Shield",
    description: "Home to the majestic Andromeda Galaxy (M31) — the most distant object visible to the naked eye at 2.5 million light-years away.",
    mythology: "Daughter of King Cepheus and Queen Cassiopeia, chained to a coastal rock as a sacrifice before being heroically rescued by Perseus.",
    stars: [
      { name: "Alpheratz", type: "Binary Mercury-Manganese", mag: 2.07, color: "#38bdf8", ra: "00h 08m", dec: "+29° 05'", temp: "B8IV" },
      { name: "Mirach", type: "Red Giant", mag: 2.07, color: "#f43f5e", ra: "01h 09m", dec: "+35° 37'", temp: "M0III" },
      { name: "Almach", type: "Multiple Star System", mag: 2.26, color: "#fb923c", ra: "02h 03m", dec: "+42° 19'", temp: "K2III" },
      { name: "M31 Galaxy", type: "Spiral Galaxy", mag: 3.44, color: "#38bdf8", ra: "00h 42m", dec: "+41° 16'", temp: "M31" },
    ],
    starNodes: [
      { id: 0, x: 1050, y: 255, name: "Alpheratz", mag: 2.07 },
      { id: 1, x: 1090, y: 195, name: "Mirach", mag: 2.07 },
      { id: 2, x: 1140, y: 135, name: "Almach", mag: 2.26 },
      { id: 3, x: 1060, y: 160, name: "M31 Galaxy", mag: 3.4 },
    ],
    lines: [[0, 1], [1, 2], [1, 3]]
  },
  {
    id: "scorpius",
    name: "Scorpius",
    subtitle: "The Scorpion",
    season: "Summer",
    ra: "16h 53m",
    dec: "-30° 20'",
    area: "497 sq deg",
    bestSeason: "Jun – Aug",
    genitive: "Scorpii",
    brightestStar: "Antares (α Sco) – 0.96 mag",
    iconName: "Target",
    description: "Scorpius is one of the brightest zodiac constellations, with its curving tail dipping into the dense stellar heart of the southern Milky Way.",
    mythology: "Scorpius was dispatched by Mother Earth (Gaia) to tame the legendary hunter Orion. Their legendary rivalry led both to be cast among the stars on opposite sides of the heavens.",
    stars: [
      { name: "Graffias", type: "Multiple Star System", mag: 2.62, color: "#818cf8", ra: "16h 05m", dec: "-19° 48'", temp: "B1V" },
      { name: "Dschubba", type: "Subgiant Star", mag: 2.32, color: "#38bdf8", ra: "16h 00m", dec: "-22° 37'", temp: "B2V" },
      { name: "Antares", type: "Red Supergiant", mag: 0.96, color: "#f43f5e", ra: "16h 29m", dec: "-26° 25'", temp: "M1.5Iab" },
      { name: "Wei", type: "Orange Giant", mag: 2.29, color: "#fb923c", ra: "16h 50m", dec: "-34° 17'", temp: "K2III" },
      { name: "Sargas", type: "Bright Giant", mag: 1.86, color: "#fde047", ra: "17h 37m", dec: "-42° 59'", temp: "F1II" },
      { name: "Shaula", type: "Triple Star System", mag: 1.62, color: "#38bdf8", ra: "17h 33m", dec: "-37° 06'", temp: "B1.5IV" },
    ],
    starNodes: [
      { id: 0, x: 920, y: 460, name: "Graffias", mag: 2.6 },
      { id: 1, x: 940, y: 490, name: "Dschubba", mag: 2.3 },
      { id: 2, x: 955, y: 535, name: "Antares", mag: 0.96 },
      { id: 3, x: 980, y: 580, name: "Wei", mag: 2.3 },
      { id: 4, x: 1015, y: 610, name: "Sargas", mag: 1.86 },
      { id: 5, x: 1050, y: 590, name: "Shaula", mag: 1.62 },
    ],
    lines: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5]]
  },
  {
    id: "sagittarius",
    name: "Sagittarius",
    subtitle: "The Archer / Teapot",
    season: "Summer",
    ra: "19h 00m",
    dec: "-25° 00'",
    area: "867 sq deg",
    bestSeason: "Jul – Sep",
    genitive: "Sagittarii",
    brightestStar: "Kaus Australis (ε Sgr) – 1.79 mag",
    iconName: "Compass",
    description: "Sagittarius points directly toward the center of the Milky Way galaxy. Its main stars form the famous 'Teapot' asterism.",
    mythology: "Depicted as Chiron the wise centaur archer aiming his bow toward the heart of Scorpius.",
    stars: [
      { name: "Kaus Australis", type: "Binary System", mag: 1.79, color: "#38bdf8", ra: "18h 24m", dec: "-34° 23'", temp: "B9.5III" },
      { name: "Nunki", type: "Blue Main-Sequence", mag: 2.05, color: "#38bdf8", ra: "18h 55m", dec: "-26° 17'", temp: "B2V" },
      { name: "Ascella", type: "Binary System", mag: 2.60, color: "#e2e8f0", ra: "19h 02m", dec: "-29° 52'", temp: "A2V" },
      { name: "Kaus Media", type: "Orange Giant", mag: 2.70, color: "#fb923c", ra: "18h 20m", dec: "-29° 49'", temp: "K0III" },
    ],
    starNodes: [
      { id: 0, x: 740, y: 510, name: "Kaus Australis", mag: 1.79 },
      { id: 1, x: 780, y: 470, name: "Nunki", mag: 2.05 },
      { id: 2, x: 810, y: 505, name: "Ascella", mag: 2.6 },
      { id: 3, x: 720, y: 475, name: "Kaus Media", mag: 2.7 },
    ],
    lines: [[0, 1], [1, 2], [2, 0], [0, 3], [3, 1]]
  },
  {
    id: "canis-major",
    name: "Canis Major",
    subtitle: "The Greater Dog",
    season: "Winter",
    ra: "06h 45m",
    dec: "-20° 00'",
    area: "380 sq deg",
    bestSeason: "Jan – Mar",
    genitive: "Canis Majoris",
    brightestStar: "Sirius (α CMa) – –1.46 mag",
    iconName: "Star",
    description: "Canis Major contains Sirius, the brightest star in the entire night sky, situated just south of Orion.",
    mythology: "Represents Laelaps, the fastest dog in ancient myth who was so swift no prey could escape him.",
    stars: [
      { name: "Sirius", type: "White Main-Sequence", mag: -1.46, color: "#f8fafc", ra: "06h 45m", dec: "-16° 42'", temp: "A1V" },
      { name: "Adhara", type: "Bright Giant", mag: 1.51, color: "#38bdf8", ra: "06h 58m", dec: "-28° 58'", temp: "B2II" },
      { name: "Wezen", type: "Yellow-White Supergiant", mag: 1.86, color: "#fde047", ra: "07h 08m", dec: "-26° 23'", temp: "F8Ia" },
    ],
    starNodes: [
      { id: 0, x: 490, y: 490, name: "Sirius", mag: -1.46 },
      { id: 1, x: 530, y: 550, name: "Adhara", mag: 1.51 },
      { id: 2, x: 560, y: 530, name: "Wezen", mag: 1.86 },
    ],
    lines: [[0, 1], [1, 2], [2, 0]]
  },
  {
    id: "perseus",
    name: "Perseus",
    subtitle: "The Hero",
    season: "Fall",
    ra: "03h 10m",
    dec: "+45° 00'",
    area: "615 sq deg",
    bestSeason: "Oct – Dec",
    genitive: "Persei",
    brightestStar: "Mirfak (α Per) – 1.79 mag",
    iconName: "Shield",
    description: "Perseus lies along the northern Milky Way and is famous for the radiant of the annual Perseid meteor shower in August.",
    mythology: "The legendary demigod son of Zeus who defeated Medusa using his polished shield as a mirror.",
    stars: [
      { name: "Mirfak", type: "Yellow-White Supergiant", mag: 1.79, color: "#fef08a", ra: "03h 24m", dec: "+49° 51'", temp: "F5Ib" },
      { name: "Algol", type: "Demon Star (Eclipsing Binary)", mag: 2.12, color: "#38bdf8", ra: "03h 08m", dec: "+40° 57'", temp: "B8V" },
    ],
    starNodes: [
      { id: 0, x: 340, y: 150, name: "Mirfak", mag: 1.79 },
      { id: 1, x: 310, y: 195, name: "Algol", mag: 2.12 },
      { id: 2, x: 370, y: 200, name: "Atik", mag: 3.8 },
    ],
    lines: [[0, 1], [0, 2]]
  },
  {
    id: "cancer",
    name: "Cancer",
    subtitle: "The Crab",
    season: "Spring",
    ra: "08h 38m",
    dec: "+20° 00'",
    area: "506 sq deg",
    bestSeason: "Mar – May",
    genitive: "Cancri",
    brightestStar: "Tarf (β Cnc) – 3.52 mag",
    iconName: "Target",
    description: "The faintest constellation of the zodiac, Cancer contains the magnificent Beehive Cluster (M44).",
    mythology: "Hera dispatched a giant crab to pinch Hercules' heel during his battle with the Hydra.",
    stars: [
      { name: "Tarf", type: "Orange Giant", mag: 3.52, color: "#fb923c", ra: "08h 16m", dec: "+09° 11'", temp: "K4III" },
      { name: "Acubens", type: "Multiple System", mag: 4.26, color: "#e2e8f0", ra: "08h 58m", dec: "+11° 51'", temp: "A5m" },
    ],
    starNodes: [
      { id: 0, x: 280, y: 440, name: "Asellus Bor.", mag: 4.6 },
      { id: 1, x: 305, y: 470, name: "Beehive (M44)", mag: 3.1 },
      { id: 2, x: 285, y: 505, name: "Tarf", mag: 3.52 },
      { id: 3, x: 330, y: 490, name: "Acubens", mag: 4.26 },
    ],
    lines: [[0, 1], [1, 2], [1, 3]]
  },
  {
    id: "aries",
    name: "Aries",
    subtitle: "The Ram",
    season: "Fall",
    ra: "02h 38m",
    dec: "+20° 47'",
    area: "441 sq deg",
    bestSeason: "Oct – Dec",
    genitive: "Arietis",
    brightestStar: "Hamal (α Ari) – 2.01 mag",
    iconName: "Globe",
    description: "Aries marks the golden ram whose fleece inspired Jason and the Argonauts' legendary quest.",
    mythology: "Sent by Nephele to rescue her children. The golden fleece was hung in Colchis and guarded by a dragon.",
    stars: [
      { name: "Hamal", type: "Orange Giant", mag: 2.01, color: "#fb923c", ra: "02h 07m", dec: "+23° 27'", temp: "K2III" },
      { name: "Sheratan", type: "Binary System", mag: 2.64, color: "#f1f5f9", ra: "01h 54m", dec: "+20° 48'", temp: "A5V" },
    ],
    starNodes: [
      { id: 0, x: 170, y: 480, name: "Hamal", mag: 2.01 },
      { id: 1, x: 130, y: 505, name: "Sheratan", mag: 2.64 },
      { id: 2, x: 100, y: 520, name: "Mesarthim", mag: 3.88 },
    ],
    lines: [[0, 1], [1, 2]]
  }
];

export const STARGAZING_TIPS = [
  {
    iconName: "Sparkles",
    title: "Tips for Stargazing",
    desc: "Choose a dark location away from urban light pollution. Avoid using bright phone screens to preserve dark-adapted vision."
  },
  {
    iconName: "Telescope",
    title: "Use Binoculars",
    desc: "A modest pair of 7x50 or 10x50 binoculars reveals thousands of faint stars, double stars, and nebulae invisible to the naked eye."
  },
  {
    iconName: "Eye",
    title: "Let Your Eyes Adjust",
    desc: "Human eyes require 20 to 30 minutes in complete darkness to build full rhodopsin sensitivity for night vision."
  },
  {
    iconName: "Compass",
    title: "Check Weather",
    desc: "Prioritize clear, transparent nights with low relative humidity and minimal high-altitude haze for optimal star contrast."
  },
  {
    iconName: "Shield",
    title: "Red Light Mode",
    desc: "Use red flashlight or night red filter UI mode. Red light wavelengths do not break down dark-adapted eye pigments."
  }
];
