"use client";

export const CATEGORIES = [
  {
    id: "signs-mandatory",
    label: "Mandatory / regulatory signs",
    short: "Mandatory signs",
    blurb: "Circular signs that carry the force of law. Red ring means a prohibition or limit, solid blue means a compulsory action.",
  },
  {
    id: "signs-cautionary",
    label: "Cautionary / warning signs",
    short: "Cautionary signs",
    blurb: "Upward triangles with a red border. They warn of a hazard ahead so you slow down and read the road.",
  },
  {
    id: "signs-informatory",
    label: "Informatory signs",
    short: "Informatory signs",
    blurb: "Rectangular signs, usually blue or green, that guide you to facilities, destinations and services.",
  },
  {
    id: "road-rules",
    label: "Road rules & markings",
    short: "Road rules",
    blurb: "Lane discipline, road markings, signals, hand signals and the everyday rules of the road.",
  },
  {
    id: "right-of-way",
    label: "Right of way",
    short: "Right of way",
    blurb: "Who goes first at junctions, roundabouts, crossings and on narrow hill roads.",
  },
  {
    id: "documents",
    label: "Documents & legal",
    short: "Documents",
    blurb: "Licences, registration, insurance, fitness, permits and the paperwork you must carry.",
  },
  {
    id: "penalties",
    label: "Penalties & offences",
    short: "Penalties",
    blurb: "Fines and consequences under the Motor Vehicles Act as amended in 2019.",
  },
  {
    id: "safe-driving",
    label: "Safe driving",
    short: "Safe driving",
    blurb: "Defensive driving, night and weather driving, braking, skids and vehicle handling.",
  },
];

export const QUESTIONS = [
  {
    id: "sm-1",
    cat: "signs-mandatory",
    q: "A circular sign with a white background, a thick red ring and the black numeral 50 inside means:",
    sign: { kind: "mandatory", glyph: "50" },
    options: [
      "You must not exceed 50 km/h on this stretch",
      "You must maintain exactly 50 km/h",
      "The next town is 50 km away",
      "Minimum speed on this road is 50 km/h",
    ],
    answer: 0,
    why: "A red-ringed numeral is a maximum speed limit — it is the ceiling, not a target or a distance.",
  },
  {
    id: "sm-2",
    cat: "signs-mandatory",
    q: "A solid red circle with a single white horizontal bar across it means:",
    sign: { kind: "no-entry", glyph: "" },
    options: ["No entry", "No parking", "Road closed for repairs", "One way ahead"],
    answer: 0,
    why: "The red disc with a white bar is the No Entry sign — no vehicle may enter that road from this point.",
  },
  {
    id: "sm-3",
    cat: "signs-mandatory",
    q: "What shape is used for the STOP sign in India?",
    sign: { kind: "stop", glyph: "STOP" },
    options: ["Octagonal", "Circular", "Triangular", "Rectangular"],
    answer: 0,
    why: "STOP is the only octagonal sign, so its shape alone is recognisable even if the face is dirty or snow-covered.",
  },
  {
    id: "sm-4",
    cat: "signs-mandatory",
    q: "A downward-pointing triangle with a red border and white centre means:",
    sign: { kind: "giveway", glyph: "" },
    options: [
      "Give way to traffic on the road you are joining",
      "Stop completely and switch off the engine",
      "Narrow bridge ahead",
      "You have priority over crossing traffic",
    ],
    answer: 0,
    why: "The inverted triangle is GIVE WAY — slow down, be ready to stop, and let the traffic already on the main road pass.",
  },
  {
    id: "sm-5",
    cat: "signs-mandatory",
    q: "A solid blue circle with a white arrow pointing straight up means:",
    sign: { kind: "blue-circle", glyph: "↑" },
    options: [
      "Compulsory ahead — you must go straight",
      "Ahead only if the road is clear",
      "One way street begins",
      "Overtaking permitted ahead",
    ],
    answer: 0,
    why: "Solid blue circles are compulsory-direction signs. They order a manoeuvre rather than forbid one.",
  },
  {
    id: "sm-6",
    cat: "signs-mandatory",
    q: "A white circle with a red ring showing a black horn with a red slash across it means:",
    sign: { kind: "prohibitory-bar", glyph: "♪" },
    options: [
      "Horn prohibited",
      "Silent zone ends here",
      "Use horn before proceeding",
      "Loudspeakers prohibited",
    ],
    answer: 0,
    why: "Horn prohibited is common near hospitals, schools and courts. A red slash over a symbol always forbids that thing.",
  },
  {
    id: "sm-7",
    cat: "signs-mandatory",
    q: "A circular sign with a red ring containing the letter P struck through by a red diagonal bar means:",
    sign: { kind: "prohibitory-bar", glyph: "P" },
    options: [
      "No parking",
      "Paid parking ahead",
      "Parking for two-wheelers only",
      "No stopping or standing at any time",
    ],
    answer: 0,
    why: "One bar through P is No Parking — you may stop briefly to pick up or set down, but you may not park.",
  },
  {
    id: "sm-8",
    cat: "signs-mandatory",
    q: "A circular sign with a red ring and a red diagonal cross (X) on a blue background means:",
    options: [
      "No stopping or standing",
      "No parking on odd dates",
      "No entry for heavy vehicles",
      "Road ends ahead",
    ],
    answer: 0,
    why: "The red cross is No Stopping — stricter than No Parking. You may not even halt briefly except in an emergency.",
  },
  {
    id: "sm-9",
    cat: "signs-mandatory",
    q: "A red ring showing a black car and a red car side by side means:",
    options: [
      "Overtaking prohibited",
      "Two-way traffic ahead",
      "Car parking ahead",
      "Give way to oncoming cars",
    ],
    answer: 0,
    why: "The red car in the pair marks the vehicle you must not pass — overtaking is prohibited on that stretch.",
  },
  {
    id: "sm-10",
    cat: "signs-mandatory",
    q: "A red ring with a truck symbol inside and no diagonal bar means:",
    options: [
      "Trucks prohibited on this road",
      "Truck lay-by ahead",
      "Truck weighing station ahead",
      "Trucks must keep left",
    ],
    answer: 0,
    why: "A vehicle symbol inside a plain red ring bans that class of vehicle from the road.",
  },
  {
    id: "sm-11",
    cat: "signs-mandatory",
    q: "A red ring with a U-turn arrow and a red diagonal bar means:",
    sign: { kind: "prohibitory-bar", glyph: "↶" },
    options: [
      "U-turn prohibited",
      "U-turn permitted only for light vehicles",
      "Roundabout ahead",
      "Sharp bend ahead",
    ],
    answer: 0,
    why: "U-turn prohibited. Turning back here is an offence and usually reflects poor sight lines or heavy flow.",
  },
  {
    id: "sm-12",
    cat: "signs-mandatory",
    q: "Mandatory signs that are ignored by a driver:",
    options: [
      "Are a punishable offence under the Motor Vehicles Act",
      "Carry only advisory weight and no penalty",
      "Apply only to commercial vehicles",
      "Apply only between sunrise and sunset",
    ],
    answer: 0,
    why: "Mandatory signs are legally enforceable. Disobeying one is an offence regardless of vehicle class or time of day.",
  },
  {
    id: "sm-13",
    cat: "signs-mandatory",
    q: "A red ring containing a walking pedestrian symbol means:",
    options: [
      "Pedestrians prohibited on this road",
      "Pedestrian crossing ahead",
      "Pedestrian subway ahead",
      "Give way to pedestrians",
    ],
    answer: 0,
    why: "Pedestrians prohibited — typical on expressways where people on foot would be in serious danger.",
  },
  {
    id: "sm-14",
    cat: "signs-mandatory",
    q: "A solid blue circle with a white arrow curving to the left means:",
    sign: { kind: "blue-circle", glyph: "←" },
    options: [
      "Compulsory turn left",
      "Left turn prohibited",
      "Left bend ahead",
      "Keep to the left of the divider",
    ],
    answer: 0,
    why: "A blue disc with a left arrow orders you to turn left. Blue commands, red forbids.",
  },
  {
    id: "sm-15",
    cat: "signs-mandatory",
    q: "A circular sign showing 3.5 m between two facing arrows means:",
    sign: { kind: "mandatory", glyph: "3.5m" },
    options: [
      "Width limit — vehicles wider than 3.5 m may not proceed",
      "The road is 3.5 m from the kerb",
      "Height limit of 3.5 m",
      "Keep 3.5 m from the vehicle ahead",
    ],
    answer: 0,
    why: "Facing horizontal arrows indicate a width limit. Vertical arrows on a similar sign would indicate a height limit.",
  },
  {
    id: "sm-16",
    cat: "signs-mandatory",
    q: "A white circular sign with a black diagonal band and no other symbol means:",
    options: [
      "All previously signed restrictions end here",
      "Road closed ahead",
      "End of the divided carriageway",
      "No overtaking begins",
    ],
    answer: 0,
    why: "The black diagonal band on white is the derestriction sign — the restrictions signed earlier no longer apply.",
  },
  {
    id: "sc-1",
    cat: "signs-cautionary",
    q: "What shape and colour identify a cautionary sign in India?",
    sign: { kind: "cautionary", glyph: "!" },
    options: [
      "An upward triangle with a red border and white centre",
      "A circle with a blue centre",
      "A rectangle with a green centre",
      "A downward triangle with a yellow centre",
    ],
    answer: 0,
    why: "Cautionary signs are upward triangles bordered in red. They warn, they do not order.",
  },
  {
    id: "sc-2",
    cat: "signs-cautionary",
    q: "A red-bordered triangle containing a plus-shaped symbol (a cross) means:",
    sign: { kind: "cautionary", glyph: "✚" },
    options: [
      "Cross road ahead",
      "Hospital ahead",
      "First aid post ahead",
      "Church ahead",
    ],
    answer: 0,
    why: "In a warning triangle, the cross is a road layout — an intersection ahead. A hospital would be a blue rectangle with H.",
  },
  {
    id: "sc-3",
    cat: "signs-cautionary",
    q: "A red-bordered triangle showing two children walking means:",
    options: [
      "School ahead — slow down and watch for children",
      "Children may not cross here",
      "Playground ahead, no vehicles allowed",
      "Pedestrian subway ahead",
    ],
    answer: 0,
    why: "The school-ahead warning tells you children may step out unpredictably. Reduce speed and cover the brake.",
  },
  {
    id: "sc-4",
    cat: "signs-cautionary",
    q: "A red-bordered triangle with a symbol of a person digging means:",
    options: [
      "Men at work ahead",
      "Mining area ahead",
      "Agricultural vehicles crossing",
      "Excavated road closed",
    ],
    answer: 0,
    why: "Men at work warns of roadworks — expect workers, loose material, narrowed lanes and sudden stops.",
  },
  {
    id: "sc-5",
    cat: "signs-cautionary",
    q: "A red-bordered triangle showing a wavy arrow bending right then left means:",
    options: [
      "Series of bends ahead",
      "Slippery road ahead",
      "Road widens ahead",
      "Zigzag road markings ahead",
    ],
    answer: 0,
    why: "A double-bend warning. Slow down before the first bend — braking mid-curve upsets the car's balance.",
  },
  {
    id: "sc-6",
    cat: "signs-cautionary",
    q: "A red-bordered triangle showing a car with wavy skid lines under it means:",
    options: [
      "Slippery road ahead",
      "Loose gravel ahead",
      "Speed breaker ahead",
      "Sharp turn ahead",
    ],
    answer: 0,
    why: "Slippery road. Reduce speed early, avoid harsh braking or steering, and increase your following distance.",
  },
  {
    id: "sc-7",
    cat: "signs-cautionary",
    q: "A red-bordered triangle showing a train engine means:",
    options: [
      "Unguarded level crossing ahead",
      "Railway station ahead",
      "Guarded level crossing with a gate ahead",
      "Railway workshop ahead",
    ],
    answer: 0,
    why: "The engine symbol warns of an unguarded level crossing — no gate, no gateman. Stop, look both ways, then cross.",
  },
  {
    id: "sc-8",
    cat: "signs-cautionary",
    q: "A red-bordered triangle showing a fence-like gate symbol means:",
    options: [
      "Guarded level crossing ahead",
      "Toll gate ahead",
      "State border checkpost ahead",
      "Private road ahead",
    ],
    answer: 0,
    why: "The gate symbol means a guarded level crossing — a gate and gateman control the crossing.",
  },
  {
    id: "sc-9",
    cat: "signs-cautionary",
    q: "A red-bordered triangle with a bump symbol means:",
    options: [
      "Hump or rough road ahead",
      "Hill climb ahead",
      "Bridge ahead",
      "Speed limit ends",
    ],
    answer: 0,
    why: "A hump or rough road ahead. Slow well before it — hitting a hump at speed damages suspension and unsettles the car.",
  },
  {
    id: "sc-10",
    cat: "signs-cautionary",
    q: "A red-bordered triangle showing two arrows pointing in opposite vertical directions means:",
    options: [
      "Two-way traffic ahead on a road that was one-way",
      "Overtaking permitted from both sides",
      "Dual carriageway begins",
      "Traffic merges from the right",
    ],
    answer: 0,
    why: "Two-way traffic ahead. Expect oncoming vehicles where you may have been used to a single flow — keep left.",
  },
  {
    id: "sc-11",
    cat: "signs-cautionary",
    q: "A red-bordered triangle showing a narrowing road symbol means:",
    options: [
      "Road narrows ahead",
      "Road widens ahead",
      "Lane closed for repairs",
      "Narrow bridge ends",
    ],
    answer: 0,
    why: "Road narrows ahead. Adjust your lane position early and be prepared to give way where only one vehicle fits.",
  },
  {
    id: "sc-12",
    cat: "signs-cautionary",
    q: "A red-bordered triangle showing a cow or deer means:",
    options: [
      "Cattle or wild animals may cross the road",
      "Cattle market ahead",
      "Dairy farm ahead",
      "Animal transport prohibited",
    ],
    answer: 0,
    why: "Animals may stray onto the carriageway. They move unpredictably — slow down and be ready to stop.",
  },
  {
    id: "sc-13",
    cat: "signs-cautionary",
    q: "A red-bordered triangle showing a steep gradient with a percentage such as 10% means:",
    options: [
      "Steep descent or ascent ahead at that gradient",
      "The road curves by 10 degrees",
      "10% of the road is under repair",
      "Speed must be reduced by 10%",
    ],
    answer: 0,
    why: "A gradient warning. On a steep descent, use a lower gear and engine braking rather than riding the brakes.",
  },
  {
    id: "sc-14",
    cat: "signs-cautionary",
    q: "A red-bordered triangle showing a Y-shaped road with the branch to the right means:",
    options: [
      "Side road on the right ahead",
      "Right turn compulsory",
      "Road forks and ends",
      "Right lane closed",
    ],
    answer: 0,
    why: "A side road joins from the right. Watch for vehicles emerging and do not be surprised by traffic entering your lane.",
  },
  {
    id: "sc-15",
    cat: "signs-cautionary",
    q: "A red-bordered triangle showing a circular arrow loop means:",
    options: [
      "Roundabout ahead",
      "U-turn ahead",
      "Hairpin bend ahead",
      "Vehicle may skid",
    ],
    answer: 0,
    why: "Roundabout ahead. Approach at a controlled speed and prepare to give way to traffic already circulating.",
  },
  {
    id: "sc-16",
    cat: "signs-cautionary",
    q: "When you see a cautionary sign you should:",
    options: [
      "Slow down and be prepared for the hazard it describes",
      "Stop the vehicle immediately",
      "Sound the horn continuously until past it",
      "Maintain speed since the sign is only advisory",
    ],
    answer: 0,
    why: "Cautionary signs buy you reaction time. The correct response is to reduce speed and raise your scanning.",
  },
  {
    id: "sc-17",
    cat: "signs-cautionary",
    q: "A red-bordered triangle showing a hairpin symbol with the bend doubling back means:",
    options: [
      "Hairpin bend ahead",
      "Series of gentle curves",
      "Road loops under a flyover",
      "Reverse turn prohibited",
    ],
    answer: 0,
    why: "A hairpin bend doubles back almost 180 degrees — common on ghat roads. Drop to a low gear and stay well left.",
  },
  {
    id: "si-1",
    cat: "signs-informatory",
    q: "A blue rectangular sign with a white letter H means:",
    sign: { kind: "informatory", glyph: "H" },
    options: ["Hospital ahead", "Helipad ahead", "Highway begins", "Hotel ahead"],
    answer: 0,
    why: "H on a blue rectangle marks a hospital. Keep noise down and expect ambulances entering and leaving.",
  },
  {
    id: "si-2",
    cat: "signs-informatory",
    q: "A blue rectangular sign with a white letter P means:",
    sign: { kind: "informatory", glyph: "P" },
    options: [
      "Parking place ahead",
      "Petrol pump ahead",
      "Police station ahead",
      "Pedestrian zone ahead",
    ],
    answer: 0,
    why: "P on a blue rectangle is an informatory parking sign. A red ring around a P would instead forbid parking.",
  },
  {
    id: "si-3",
    cat: "signs-informatory",
    q: "What shape are informatory signs?",
    options: ["Rectangular", "Triangular", "Circular", "Octagonal"],
    answer: 0,
    why: "Informatory signs are rectangular, usually blue or green. They guide rather than warn or command.",
  },
  {
    id: "si-4",
    cat: "signs-informatory",
    q: "A blue rectangle showing a person walking on stripes means:",
    options: [
      "Pedestrian crossing at this point",
      "Pedestrians prohibited",
      "Footpath ends",
      "Zebra crossing ahead in 100 m",
    ],
    answer: 0,
    why: "The blue rectangular version marks the crossing itself. The triangular red-bordered version warns of one ahead.",
  },
  {
    id: "si-5",
    cat: "signs-informatory",
    q: "A blue rectangle with a white cross on a red background inside means:",
    options: ["First aid post", "Hospital", "Chemist shop", "Blood bank"],
    answer: 0,
    why: "First aid post — basic emergency care. A hospital is signed separately with the letter H.",
  },
  {
    id: "si-6",
    cat: "signs-informatory",
    q: "A blue rectangle with a fuel pump symbol means:",
    options: [
      "Filling station ahead",
      "Compressed gas cylinders prohibited",
      "Vehicle repair shop",
      "Fuel tanker route",
    ],
    answer: 0,
    why: "A filling station is signed on a blue informatory rectangle, often with the distance below it.",
  },
  {
    id: "si-7",
    cat: "signs-informatory",
    q: "Green rectangular signs on a national highway usually show:",
    options: [
      "Destination and distance information",
      "Emergency instructions only",
      "Speed limits for heavy vehicles",
      "Toll rates",
    ],
    answer: 0,
    why: "Green direction boards carry destinations, route numbers and distances on highways and expressways.",
  },
  {
    id: "si-8",
    cat: "signs-informatory",
    q: "A rectangular sign reading ONE WAY with an arrow means:",
    options: [
      "Traffic flows only in the direction of the arrow",
      "Overtaking allowed only in that direction",
      "The road ends in that direction",
      "One lane is open in that direction",
    ],
    answer: 0,
    why: "One way — you may travel only in the arrow's direction. Entering against it risks a head-on collision.",
  },
  {
    id: "si-9",
    cat: "signs-informatory",
    q: "A blue rectangle with a knife-and-fork symbol means:",
    options: [
      "Eating place / restaurant ahead",
      "Rest area with no facilities",
      "Food loading zone",
      "Picnic prohibited",
    ],
    answer: 0,
    why: "Standard informatory symbol for an eating place, commonly grouped with fuel and rest facilities on highways.",
  },
  {
    id: "si-10",
    cat: "signs-informatory",
    q: "A sign reading NO THROUGH ROAD or showing a dead-end symbol means:",
    options: [
      "The road has no exit at the far end",
      "The road is closed for repairs today",
      "Through traffic must use the right lane",
      "The road is private",
    ],
    answer: 0,
    why: "A dead end — the road does not lead anywhere else, so you must return the way you came.",
  },
  {
    id: "si-11",
    cat: "signs-informatory",
    q: "A blue rectangle with a telephone handset symbol on a highway usually indicates:",
    options: [
      "Public or emergency telephone ahead",
      "Mobile phones may be used here",
      "Telephone exchange building",
      "Mobile network coverage begins",
    ],
    answer: 0,
    why: "An emergency or public telephone. On expressways these mark the SOS points spaced along the carriageway.",
  },
  {
    id: "si-12",
    cat: "signs-informatory",
    q: "Informatory signs differ from mandatory signs because they:",
    options: [
      "Provide guidance and facility information rather than orders",
      "Are always larger in size",
      "Apply only to commercial vehicles",
      "Are only used inside city limits",
    ],
    answer: 0,
    why: "Informatory signs inform. Mandatory signs command or forbid and carry legal penalties when disobeyed.",
  },
  {
    id: "si-13",
    cat: "signs-informatory",
    q: "A rectangular sign showing a bed or a cup symbol on a highway means:",
    options: [
      "Rest area or refreshment facility ahead",
      "Hospital ward ahead",
      "Sleeping in vehicles permitted",
      "Night halt prohibited",
    ],
    answer: 0,
    why: "These pictograms mark rest and refreshment stops — useful markers for planning breaks on long drives.",
  },
  {
    id: "si-14",
    cat: "signs-informatory",
    q: "A blue rectangle with a spanner or wrench symbol means:",
    options: [
      "Vehicle repair facility ahead",
      "Roadworks ahead",
      "Tools prohibited",
      "Vehicle inspection compulsory",
    ],
    answer: 0,
    why: "A repair or mechanic facility. Roadworks would instead be a red-bordered warning triangle.",
  },
  {
    id: "rr-1",
    cat: "road-rules",
    q: "In India, on which side of the road must you normally drive?",
    options: ["Left", "Right", "Centre", "Whichever side is clearer"],
    answer: 0,
    why: "India drives on the left. Keeping left also keeps the faster lanes free for overtaking traffic.",
  },
  {
    id: "rr-2",
    cat: "road-rules",
    q: "You should normally overtake another vehicle from which side?",
    options: [
      "The right",
      "The left",
      "Either side, whichever is free",
      "The left on highways and the right in cities",
    ],
    answer: 0,
    why: "Because we drive on the left, overtaking is done on the right. Passing on the left surprises the other driver.",
  },
  {
    id: "rr-3",
    cat: "road-rules",
    q: "A continuous single white or yellow line along the centre of the road means:",
    options: [
      "You must not cross it or overtake across it",
      "You may cross it to overtake if the road is clear",
      "It marks the edge of the carriageway",
      "It is only a guide and carries no restriction",
    ],
    answer: 0,
    why: "A continuous centre line must not be crossed. It is used where sight distance is too short to overtake safely.",
  },
  {
    id: "rr-4",
    cat: "road-rules",
    q: "A broken white line along the road means:",
    options: [
      "You may cross it to change lanes or overtake when it is safe",
      "You must never cross it",
      "Parking is permitted along it",
      "It marks a cycle lane",
    ],
    answer: 0,
    why: "A broken line is a permissive lane line. You may cross it when the manoeuvre is safe and clear.",
  },
  {
    id: "rr-5",
    cat: "road-rules",
    q: "You approach a line that is continuous on your side and broken on the other side. You:",
    options: [
      "Must not cross it, though oncoming traffic may",
      "May cross it whenever you wish",
      "Must stop before it",
      "May cross it only at night",
    ],
    answer: 0,
    why: "The line nearest you governs your behaviour. Continuous on your side means no crossing from your side.",
  },
  {
    id: "rr-6",
    cat: "road-rules",
    q: "A yellow box with criss-cross lines painted at a junction means:",
    options: [
      "Do not enter the box unless your exit is clear",
      "Stop inside the box and wait for the signal",
      "Parking is permitted inside the box",
      "Pedestrians may cross inside the box",
    ],
    answer: 0,
    why: "The yellow box keeps junctions from locking up. Enter only when you can clear it without stopping.",
  },
  {
    id: "rr-7",
    cat: "road-rules",
    q: "The hand signal for a right turn is:",
    options: [
      "Right arm extended straight out horizontally with the palm facing forward",
      "Right arm extended and rotated anticlockwise",
      "Right arm extended and moved up and down",
      "Right forearm raised vertically with palm forward",
    ],
    answer: 0,
    why: "Arm straight out to the right signals a right turn. Rotating it anticlockwise signals a left turn.",
  },
  {
    id: "rr-8",
    cat: "road-rules",
    q: "The hand signal for a left turn is:",
    options: [
      "Right arm extended and rotated anticlockwise",
      "Left arm extended straight out horizontally",
      "Right forearm raised vertically",
      "Right arm moved up and down slowly",
    ],
    answer: 0,
    why: "The right arm is used for all Indian hand signals because it is visible to following and oncoming traffic.",
  },
  {
    id: "rr-9",
    cat: "road-rules",
    q: "The hand signal to indicate that you are slowing down is:",
    options: [
      "Right arm extended, palm downward, moved slowly up and down",
      "Right arm raised vertically with palm forward",
      "Right arm rotated anticlockwise",
      "Right arm swung forward and backward in a semicircle",
    ],
    answer: 0,
    why: "The palm-down patting motion signals slowing. The forward-and-backward semicircle instead invites a vehicle to overtake.",
  },
  {
    id: "rr-10",
    cat: "road-rules",
    q: "The hand signal to stop is:",
    options: [
      "Right forearm raised vertically with the palm facing forward",
      "Right arm extended horizontally",
      "Right arm rotated clockwise",
      "Both arms raised above the head",
    ],
    answer: 0,
    why: "The raised palm is understood as stop by drivers and pedestrians alike, mirroring a police officer's stop signal.",
  },
  {
    id: "rr-11",
    cat: "road-rules",
    q: "A flashing amber traffic light means:",
    options: [
      "Proceed with caution after slowing down",
      "Stop and wait for green",
      "The signal is out of order, ignore the junction",
      "Traffic from the right has priority",
    ],
    answer: 0,
    why: "Flashing amber means caution — the junction is uncontrolled, so slow down and give way as the situation demands.",
  },
  {
    id: "rr-12",
    cat: "road-rules",
    q: "A steady amber light after green means:",
    options: [
      "Stop unless you are so close that stopping would be unsafe",
      "Speed up to clear the junction",
      "Continue as though it were green",
      "Prepare to move off from a stop",
    ],
    answer: 0,
    why: "Amber means stop. You may continue only if you are already too close to halt safely.",
  },
  {
    id: "rr-13",
    cat: "road-rules",
    q: "When a police officer's signal contradicts the traffic light, you must:",
    options: [
      "Obey the police officer",
      "Obey the traffic light",
      "Stop and wait for both to agree",
      "Follow the vehicle in front",
    ],
    answer: 0,
    why: "A traffic officer's directions override signals and signs — they usually reflect a situation the signal cannot see.",
  },
  {
    id: "rr-14",
    cat: "road-rules",
    q: "You must not overtake when:",
    options: [
      "Approaching a bend, hill crest, junction or pedestrian crossing",
      "The road ahead is straight and clear",
      "The vehicle ahead is slower than the speed limit",
      "You are on a dual carriageway",
    ],
    answer: 0,
    why: "Overtaking needs sight distance. Bends, crests, junctions and crossings hide oncoming traffic and pedestrians.",
  },
  {
    id: "rr-15",
    cat: "road-rules",
    q: "Zebra stripes painted across the road mark:",
    options: [
      "A pedestrian crossing where people on foot have priority",
      "A parking bay for two-wheelers",
      "A no-overtaking zone only",
      "A bus stop",
    ],
    answer: 0,
    why: "At a zebra crossing pedestrians have right of way. Stop behind the line and let them finish crossing.",
  },
  {
    id: "rr-16",
    cat: "road-rules",
    q: "Using a horn is prohibited:",
    options: [
      "In silence zones near hospitals, schools and courts",
      "Only between midnight and 5 am",
      "Only inside tunnels",
      "Only for two-wheelers",
    ],
    answer: 0,
    why: "Silence zones ban the horn. Elsewhere it should be used sparingly to warn, never to vent frustration.",
  },
  {
    id: "rr-17",
    cat: "road-rules",
    q: "Before making any turn or changing lane you should:",
    options: [
      "Check mirrors, check the blind spot, then signal in good time",
      "Signal and turn immediately",
      "Sound the horn and turn",
      "Turn first and signal afterwards",
    ],
    answer: 0,
    why: "Mirror, signal, manoeuvre. Signalling without looking tells others your plan but does not tell you if it is safe.",
  },
  {
    id: "rr-18",
    cat: "road-rules",
    q: "The maximum speed limit for a car (M1 category) on an expressway under the 2018 MoRTH notification is:",
    options: ["120 km/h", "100 km/h", "80 km/h", "140 km/h"],
    answer: 0,
    why: "120 km/h on expressways, 100 on four-lane divided national highways and 70 on municipal roads for cars.",
  },
  {
    id: "rr-19",
    cat: "road-rules",
    q: "Parking your vehicle on a footpath is:",
    options: [
      "An offence — it forces pedestrians onto the carriageway",
      "Permitted if no pedestrians are present",
      "Permitted for two-wheelers only",
      "Permitted for up to 30 minutes",
    ],
    answer: 0,
    why: "Footpaths are for people on foot. Parking on one pushes pedestrians, including children, into moving traffic.",
  },
  {
    id: "rr-20",
    cat: "road-rules",
    q: "When you intend to stop or park at the roadside you should:",
    options: [
      "Check mirrors, signal left, and pull over close to the left kerb",
      "Stop wherever convenient without signalling",
      "Signal right and stop in the middle lane",
      "Reverse into the flow of traffic",
    ],
    answer: 0,
    why: "Signal your intention and leave the carriageway clear. An unsignalled stop is a common cause of rear-end collisions.",
  },
  {
    id: "rr-21",
    cat: "road-rules",
    q: "Reversing your vehicle on a one-way street is:",
    options: [
      "Prohibited",
      "Permitted if you signal",
      "Permitted at low speed",
      "Permitted only at night",
    ],
    answer: 0,
    why: "Reversing against a one-way flow is prohibited. Other drivers do not expect anything moving against them.",
  },
  {
    id: "rr-22",
    cat: "road-rules",
    q: "Solid double continuous lines in the centre of a road mean:",
    options: [
      "No vehicle from either side may cross",
      "Both sides may overtake with care",
      "The road is a dual carriageway",
      "Overtaking is allowed only for two-wheelers",
    ],
    answer: 0,
    why: "Double continuous lines forbid crossing from either direction — sight distance is inadequate for both flows.",
  },
  {
    id: "rw-1",
    cat: "right-of-way",
    q: "At an uncontrolled intersection with no signs or signals, you should give way to:",
    options: [
      "Traffic approaching from your right",
      "Traffic approaching from your left",
      "The larger vehicle",
      "Whoever sounds the horn first",
    ],
    answer: 0,
    why: "The give-way-to-the-right convention applies at uncontrolled crossings in India, so priority is predictable.",
  },
  {
    id: "rw-2",
    cat: "right-of-way",
    q: "An ambulance with its siren and lights on approaches from behind. You must:",
    options: [
      "Pull to the left where safe and let it pass",
      "Speed up to stay ahead of it",
      "Stop immediately in your lane",
      "Continue as normal; it must find its own way",
    ],
    answer: 0,
    why: "Emergency vehicles have priority. Failing to give way to one is a specific offence under the amended MV Act.",
  },
  {
    id: "rw-3",
    cat: "right-of-way",
    q: "You are entering a roundabout. You must give way to:",
    options: [
      "Traffic already on the roundabout, coming from your right",
      "Traffic waiting to enter from your left",
      "Nobody; entering traffic has priority",
      "The vehicle that arrived first",
    ],
    answer: 0,
    why: "Traffic circulating on the roundabout has priority. It comes from your right because we circulate clockwise.",
  },
  {
    id: "rw-4",
    cat: "right-of-way",
    q: "You want to turn right at a junction while a vehicle comes straight towards you. You should:",
    options: [
      "Wait and let the oncoming vehicle pass",
      "Turn quickly before it arrives",
      "Sound the horn and turn",
      "Flash your headlights and turn",
    ],
    answer: 0,
    why: "A turning vehicle crosses the path of oncoming traffic, so the vehicle going straight has right of way.",
  },
  {
    id: "rw-5",
    cat: "right-of-way",
    q: "On a narrow hill road, when two vehicles meet, right of way belongs to:",
    options: [
      "The vehicle going uphill",
      "The vehicle going downhill",
      "The heavier vehicle",
      "The vehicle that arrived first",
    ],
    answer: 0,
    why: "The uphill vehicle keeps its momentum and has less control reversing, so the downhill vehicle gives way.",
  },
  {
    id: "rw-6",
    cat: "right-of-way",
    q: "A pedestrian has already stepped onto a zebra crossing. You should:",
    options: [
      "Stop and allow them to complete the crossing",
      "Sound the horn so they hurry",
      "Pass behind them quickly",
      "Proceed if you can squeeze past",
    ],
    answer: 0,
    why: "Pedestrians on a zebra crossing have absolute priority. Stop behind the line until the crossing is clear.",
  },
  {
    id: "rw-7",
    cat: "right-of-way",
    q: "You are emerging from a minor road onto a main road. You must:",
    options: [
      "Give way to all traffic on the main road",
      "Proceed since the main road traffic must slow",
      "Take priority if your vehicle is larger",
      "Give way only to vehicles from your right",
    ],
    answer: 0,
    why: "Traffic on the major road has priority. Emerge only when there is a gap you can join without forcing anyone to brake.",
  },
  {
    id: "rw-8",
    cat: "right-of-way",
    q: "A fire engine on an emergency call has:",
    options: [
      "Right of way over all other traffic",
      "The same priority as any other vehicle",
      "Priority only at signals",
      "Priority only on highways",
    ],
    answer: 0,
    why: "Fire services, ambulances and other emergency vehicles get unconditional priority when on a call.",
  },
  {
    id: "rw-9",
    cat: "right-of-way",
    q: "At a junction controlled by a green light, you still have to:",
    options: [
      "Give way to pedestrians and vehicles still clearing the junction",
      "Proceed regardless because green means absolute priority",
      "Stop and check for police",
      "Sound the horn before entering",
    ],
    answer: 0,
    why: "Green permits you to go only if the way is clear. It never entitles you to drive into someone still crossing.",
  },
  {
    id: "rw-10",
    cat: "right-of-way",
    q: "A funeral procession or a marching military column is passing. You should:",
    options: [
      "Not cut through or break the procession",
      "Overtake it at speed",
      "Drive through any gap you find",
      "Sound the horn to clear a path",
    ],
    answer: 0,
    why: "Processions and columns must be allowed to pass intact. Cutting through them is both unsafe and an offence.",
  },
  {
    id: "rw-11",
    cat: "right-of-way",
    q: "You are on a road with a STOP sign at the junction ahead. You must:",
    options: [
      "Come to a complete halt behind the line, then proceed when clear",
      "Slow down and roll through if no traffic is visible",
      "Stop only if another vehicle is approaching",
      "Sound the horn and proceed",
    ],
    answer: 0,
    why: "STOP requires a complete halt every time, not a rolling pause. Only then may you proceed when the way is clear.",
  },
  {
    id: "rw-12",
    cat: "right-of-way",
    q: "When a school bus has stopped and children are getting on or off, you should:",
    options: [
      "Slow down or stop and pass only when it is clearly safe",
      "Overtake quickly on the right",
      "Sound the horn continuously",
      "Maintain your speed as usual",
    ],
    answer: 0,
    why: "Children step out without looking and are hidden by the bus. Treat a stopped school bus as a stop-and-check situation.",
  },
  {
    id: "rw-13",
    cat: "right-of-way",
    q: "Two vehicles arrive at a T-junction: one on the through road, one on the terminating road. Priority goes to:",
    options: [
      "The vehicle on the through road",
      "The vehicle on the terminating road",
      "Whichever indicates first",
      "The vehicle turning right",
    ],
    answer: 0,
    why: "At a T-junction the road that ends must give way to the road that continues.",
  },
  {
    id: "rw-14",
    cat: "right-of-way",
    q: "You are in a lane that is ending and must merge. You should:",
    options: [
      "Signal early, match the speed of the flow and merge into a gap",
      "Force your way in at the last metre",
      "Stop at the end of the lane and wait for a full gap",
      "Merge without signalling to avoid confusion",
    ],
    answer: 0,
    why: "The merging vehicle gives way. Signal early and match speed so you slot into a gap without forcing a brake.",
  },
  {
    id: "rw-15",
    cat: "right-of-way",
    q: "A visually impaired person with a white cane is waiting to cross the road. You should:",
    options: [
      "Stop and allow them to cross safely",
      "Sound the horn to alert them",
      "Drive past quickly",
      "Wave them across from behind your windscreen",
    ],
    answer: 0,
    why: "They cannot see your gesture and may not judge your speed. Stop fully and let them cross in their own time.",
  },
  {
    id: "dl-1",
    cat: "documents",
    q: "A learner's licence in India is valid for:",
    options: ["6 months", "1 year", "3 months", "2 years"],
    answer: 0,
    why: "A learner's licence is valid for six months, within which you must attempt the permanent driving test.",
  },
  {
    id: "dl-2",
    cat: "documents",
    q: "The minimum age to obtain a licence for a motorcycle without gears up to 50 cc is:",
    options: ["16 years", "18 years", "20 years", "21 years"],
    answer: 0,
    why: "16 with the guardian's consent for a gearless 50 cc motorcycle. Geared motorcycles and cars require 18.",
  },
  {
    id: "dl-3",
    cat: "documents",
    q: "The minimum age to obtain a licence to drive a light motor vehicle (car) is:",
    options: ["18 years", "16 years", "20 years", "21 years"],
    answer: 0,
    why: "18 years for an LMV or a geared motorcycle. Transport vehicles require a minimum of 20 years.",
  },
  {
    id: "dl-4",
    cat: "documents",
    q: "The minimum age to obtain a licence to drive a transport vehicle is:",
    options: ["20 years", "18 years", "21 years", "25 years"],
    answer: 0,
    why: "20 years, along with a minimum education qualification and completion of the prescribed training.",
  },
  {
    id: "dl-5",
    cat: "documents",
    q: "Which insurance is legally compulsory for every motor vehicle used in a public place?",
    options: [
      "Third-party liability insurance",
      "Comprehensive insurance",
      "Own-damage insurance",
      "Zero-depreciation insurance",
    ],
    answer: 0,
    why: "Section 146 of the MV Act makes third-party cover compulsory. It protects the people you might injure.",
  },
  {
    id: "dl-6",
    cat: "documents",
    q: "A permanent driving licence for a private LMV is normally valid for:",
    options: [
      "20 years, or until the holder turns 40 — whichever is earlier",
      "10 years from the date of issue",
      "Lifetime",
      "5 years from the date of issue",
    ],
    answer: 0,
    why: "20 years or age 40, whichever comes first. After 40 it is renewed for shorter periods with a medical certificate.",
  },
  {
    id: "dl-7",
    cat: "documents",
    q: "Which of these must you be able to produce while driving?",
    options: [
      "Driving licence, registration certificate, insurance and PUC certificate",
      "Driving licence only",
      "Registration certificate only",
      "Aadhaar card and PAN card",
    ],
    answer: 0,
    why: "DL, RC, valid insurance and a valid PUC. All four may be produced digitally through DigiLocker or mParivahan.",
  },
  {
    id: "dl-8",
    cat: "documents",
    q: "PUC stands for:",
    options: [
      "Pollution Under Control certificate",
      "Permit for Urban Commuting",
      "Public Utility Certificate",
      "Passenger Under Cover",
    ],
    answer: 0,
    why: "The Pollution Under Control certificate confirms your exhaust emissions are within the prescribed limits.",
  },
  {
    id: "dl-9",
    cat: "documents",
    q: "The registration of a new private vehicle is initially valid for:",
    options: ["15 years", "5 years", "10 years", "20 years"],
    answer: 0,
    why: "15 years initially, then renewable in five-year blocks subject to a fitness check.",
  },
  {
    id: "dl-10",
    cat: "documents",
    q: "An International Driving Permit issued in India is normally valid for:",
    options: ["1 year", "6 months", "3 years", "5 years"],
    answer: 0,
    why: "One year from issue, and only alongside your valid Indian driving licence.",
  },
  {
    id: "dl-11",
    cat: "documents",
    q: "If you change your permanent address, you must inform the licensing authority within:",
    options: ["30 days", "7 days", "90 days", "6 months"],
    answer: 0,
    why: "30 days. Records must stay current so that notices and enforcement actually reach you.",
  },
  {
    id: "dl-12",
    cat: "documents",
    q: "A vehicle displaying an L plate indicates:",
    options: [
      "It is being driven by a learner's licence holder",
      "It is a light commercial vehicle",
      "It is carrying a load",
      "It is a leased vehicle",
    ],
    answer: 0,
    why: "The red L on white marks a learner. A learner must also be accompanied by a full licence holder.",
  },
  {
    id: "dl-13",
    cat: "documents",
    q: "A learner's licence holder driving a car must:",
    options: [
      "Be accompanied by a person holding a valid permanent licence for that class",
      "Drive alone to gain confidence",
      "Drive only after sunset",
      "Be accompanied by any adult",
    ],
    answer: 0,
    why: "A qualified supervisor holding a licence for that class must sit beside you, and L plates must be displayed.",
  },
  {
    id: "dl-14",
    cat: "documents",
    q: "Transferring vehicle ownership must be reported to the registering authority within:",
    options: ["14 days for the same state", "60 days", "6 months", "1 year"],
    answer: 0,
    why: "14 days within the same state and 45 days when the vehicle moves to another state's jurisdiction.",
  },
  {
    id: "dl-15",
    cat: "documents",
    q: "A Fitness Certificate is mandatory for:",
    options: [
      "Transport / commercial vehicles",
      "All private cars from year one",
      "Two-wheelers only",
      "Electric vehicles only",
    ],
    answer: 0,
    why: "Transport vehicles need periodic fitness certification. Private vehicles undergo fitness checks at renewal.",
  },
  {
    id: "dl-16",
    cat: "documents",
    q: "To drive a vehicle carrying hazardous goods, the driver additionally needs:",
    options: [
      "A hazardous goods endorsement and specific training",
      "Nothing beyond a normal transport licence",
      "Only a commercial insurance policy",
      "Only the owner's authorisation letter",
    ],
    answer: 0,
    why: "Carrying hazardous goods requires an endorsement backed by prescribed training in handling and emergency response.",
  },
  {
    id: "pn-1",
    cat: "penalties",
    q: "Under the Motor Vehicles (Amendment) Act 2019, driving without a valid licence attracts a fine of:",
    options: ["Rs 5,000", "Rs 500", "Rs 1,000", "Rs 10,000"],
    answer: 0,
    why: "Rs 5,000. The 2019 amendment raised penalties sharply to deter repeat offending.",
  },
  {
    id: "pn-2",
    cat: "penalties",
    q: "The legal blood alcohol limit for a driver in India is:",
    options: [
      "30 mg per 100 ml of blood",
      "50 mg per 100 ml of blood",
      "80 mg per 100 ml of blood",
      "There is no limit",
    ],
    answer: 0,
    why: "30 mg per 100 ml — among the strictest limits in the world. Above it you are driving under the influence.",
  },
  {
    id: "pn-3",
    cat: "penalties",
    q: "The penalty for drunk driving (first offence) under the amended Act is:",
    options: [
      "Rs 10,000 and/or up to 6 months imprisonment",
      "Rs 2,000 only",
      "Rs 500 and a warning",
      "Licence suspension only",
    ],
    answer: 0,
    why: "Rs 10,000 and/or six months for a first offence, rising to Rs 15,000 and/or two years for a repeat.",
  },
  {
    id: "pn-4",
    cat: "penalties",
    q: "Riding a two-wheeler without a helmet attracts:",
    options: [
      "Rs 1,000 and disqualification of the licence for 3 months",
      "Rs 100 only",
      "A verbal warning for the first offence",
      "Rs 5,000 and vehicle seizure",
    ],
    answer: 0,
    why: "Rs 1,000 plus a three-month licence disqualification. Head injury is the leading cause of two-wheeler deaths.",
  },
  {
    id: "pn-5",
    cat: "penalties",
    q: "Not wearing a seat belt attracts a fine of:",
    options: ["Rs 1,000", "Rs 100", "Rs 5,000", "Rs 500"],
    answer: 0,
    why: "Rs 1,000. The rule applies to rear passengers too, not only to those in the front seats.",
  },
  {
    id: "pn-6",
    cat: "penalties",
    q: "Driving without valid insurance attracts a first-offence fine of:",
    options: ["Rs 2,000", "Rs 1,000", "Rs 5,000", "Rs 500"],
    answer: 0,
    why: "Rs 2,000 for a first offence and Rs 4,000 for a subsequent one, with possible imprisonment.",
  },
  {
    id: "pn-7",
    cat: "penalties",
    q: "Using a mobile phone while driving is treated as:",
    options: [
      "Dangerous driving, attracting a fine of Rs 5,000",
      "A minor offence with a Rs 100 fine",
      "Permitted if the call is short",
      "Permitted if you are stopped at a signal",
    ],
    answer: 0,
    why: "It is booked as dangerous driving — Rs 5,000. Even hands-free conversation measurably delays your reactions.",
  },
  {
    id: "pn-8",
    cat: "penalties",
    q: "Not giving way to an emergency vehicle attracts a fine of:",
    options: ["Rs 10,000", "Rs 1,000", "Rs 500", "Rs 2,000"],
    answer: 0,
    why: "Rs 10,000 — a new offence introduced in 2019, reflecting how often blocked ambulances cost lives.",
  },
  {
    id: "pn-9",
    cat: "penalties",
    q: "If a juvenile commits a road offence, the guardian or vehicle owner may face:",
    options: [
      "Rs 25,000 with 3 years imprisonment and cancellation of the vehicle registration",
      "A Rs 500 fine only",
      "No liability at all",
      "A warning for the first offence",
    ],
    answer: 0,
    why: "The adult is held responsible, and the juvenile is barred from a licence until age 25.",
  },
  {
    id: "pn-10",
    cat: "penalties",
    q: "Over-speeding by a light motor vehicle attracts a fine of:",
    options: ["Rs 1,000 to Rs 2,000", "Rs 100", "Rs 10,000", "Rs 25,000"],
    answer: 0,
    why: "Rs 1,000–2,000 for LMVs, and Rs 2,000–4,000 for medium and heavy vehicles.",
  },
  {
    id: "pn-11",
    cat: "penalties",
    q: "Racing or speed-testing on a public road attracts a first-offence fine of:",
    options: ["Rs 5,000", "Rs 500", "Rs 1,000", "Rs 100"],
    answer: 0,
    why: "Rs 5,000 for a first offence and Rs 10,000 for a repeat, with imprisonment possible in both cases.",
  },
  {
    id: "pn-12",
    cat: "penalties",
    q: "Driving an unregistered vehicle attracts a fine of:",
    options: ["Rs 5,000", "Rs 500", "Rs 100", "Rs 20,000"],
    answer: 0,
    why: "Rs 5,000 for a first offence. Registration ties a vehicle to an accountable owner.",
  },
  {
    id: "pn-13",
    cat: "penalties",
    q: "Overloading a passenger vehicle beyond its permitted seating attracts:",
    options: [
      "Rs 1,000 per extra passenger",
      "A flat Rs 500 fine",
      "No penalty if the passengers are children",
      "Rs 100 per extra passenger",
    ],
    answer: 0,
    why: "Rs 1,000 for every extra passenger. Overloading alters braking and handling and defeats the restraint design.",
  },
  {
    id: "pn-14",
    cat: "penalties",
    q: "If a traffic enforcement officer commits a traffic offence, the penalty is:",
    options: [
      "Twice the penalty prescribed for that offence",
      "The same as for any citizen",
      "Half the normal penalty",
      "A departmental warning only",
    ],
    answer: 0,
    why: "Section 210B doubles the penalty for enforcement authorities — those who enforce the law are held to a higher bar.",
  },
  {
    id: "pn-15",
    cat: "penalties",
    q: "Driving without a valid Pollution Under Control certificate can attract a fine of up to:",
    options: ["Rs 10,000", "Rs 100", "Rs 500", "Rs 1,000"],
    answer: 0,
    why: "Up to Rs 10,000 for breaching emission standards, and your licence may be suspended.",
  },
  {
    id: "pn-16",
    cat: "penalties",
    q: "Refusing to submit to a breath analyser test when asked by police:",
    options: [
      "Is itself an offence and the officer may arrest you without a warrant",
      "Is your legal right with no consequence",
      "Is permitted if you have not been drinking",
      "Only results in a Rs 100 fine",
    ],
    answer: 0,
    why: "Refusal is an offence in its own right under Section 203 and allows arrest without a warrant.",
  },
  {
    id: "pn-17",
    cat: "penalties",
    q: "Driving when disqualified from holding a licence attracts a fine of:",
    options: ["Rs 10,000", "Rs 1,000", "Rs 500", "Rs 100"],
    answer: 0,
    why: "Rs 10,000. A disqualification is a court or authority finding that you are currently unfit to be on the road.",
  },
  {
    id: "sd-1",
    cat: "safe-driving",
    q: "Under normal dry conditions, a safe following distance is best judged by:",
    options: [
      "The two-second rule against a fixed roadside object",
      "Staying exactly one car length behind",
      "Keeping the vehicle ahead's number plate readable",
      "Following as close as possible to save fuel",
    ],
    answer: 0,
    why: "The two-second rule scales with speed, unlike a fixed car length. Double it to four seconds in rain.",
  },
  {
    id: "sd-2",
    cat: "safe-driving",
    q: "At night, when a vehicle approaches from the opposite direction, you must:",
    options: [
      "Dip your headlights to low beam",
      "Switch to high beam to see better",
      "Switch off your headlights briefly",
      "Flash your high beam repeatedly",
    ],
    answer: 0,
    why: "High beam blinds the oncoming driver for several seconds. Dip early, and look slightly left to avoid their glare.",
  },
  {
    id: "sd-3",
    cat: "safe-driving",
    q: "In dense fog you should use:",
    options: [
      "Low beam headlights and fog lamps if fitted",
      "High beam headlights",
      "Hazard lights while driving normally",
      "Parking lights only",
    ],
    answer: 0,
    why: "High beam reflects off the fog straight back at you. Low beam and fog lamps throw light under the fog bank.",
  },
  {
    id: "sd-4",
    cat: "safe-driving",
    q: "If your vehicle begins to skid, you should:",
    options: [
      "Ease off the accelerator and steer gently in the direction of the skid",
      "Brake hard immediately",
      "Turn the steering sharply the opposite way",
      "Pull the handbrake",
    ],
    answer: 0,
    why: "Steering into the skid realigns the wheels with your direction of travel. Hard braking locks the wheels and worsens it.",
  },
  {
    id: "sd-5",
    cat: "safe-driving",
    q: "The blind spot is:",
    options: [
      "The area beside and behind your vehicle not covered by the mirrors",
      "The area directly in front of the bonnet",
      "The area hidden by fog",
      "The area behind a truck you are following",
    ],
    answer: 0,
    why: "Mirrors do not cover everything. A quick head turn before every lane change is what catches the vehicle hiding there.",
  },
  {
    id: "sd-6",
    cat: "safe-driving",
    q: "Descending a steep hill, the safest technique is to:",
    options: [
      "Select a low gear and use engine braking",
      "Coast in neutral to save fuel",
      "Hold the brake pedal down continuously",
      "Switch off the engine and roll down",
    ],
    answer: 0,
    why: "Engine braking controls speed without heating the brakes. Continuous braking causes brake fade — and then no brakes.",
  },
  {
    id: "sd-7",
    cat: "safe-driving",
    q: "Stopping distance is made up of:",
    options: [
      "Thinking distance plus braking distance",
      "Braking distance only",
      "The length of the vehicle plus braking distance",
      "The distance to the vehicle ahead",
    ],
    answer: 0,
    why: "You travel a real distance while reacting. At 60 km/h a one-second reaction alone covers about 17 metres.",
  },
  {
    id: "sd-8",
    cat: "safe-driving",
    q: "Under-inflated tyres:",
    options: [
      "Increase braking distance, overheat and raise the risk of a blowout",
      "Improve grip in all conditions",
      "Improve fuel efficiency",
      "Have no effect on handling",
    ],
    answer: 0,
    why: "Low pressure flexes the sidewall, builds heat and can destroy the tyre at speed. Check pressures cold, monthly.",
  },
  {
    id: "sd-9",
    cat: "safe-driving",
    q: "ABS (Anti-lock Braking System) is designed to:",
    options: [
      "Prevent the wheels from locking so you can steer while braking hard",
      "Shorten the stopping distance on every surface",
      "Replace the need to brake early",
      "Stop the vehicle automatically",
    ],
    answer: 0,
    why: "ABS preserves steering control under emergency braking. On loose gravel it may even lengthen the stopping distance.",
  },
  {
    id: "sd-10",
    cat: "safe-driving",
    q: "You feel drowsy on a long drive. The correct action is to:",
    options: [
      "Stop at a safe place and rest before continuing",
      "Open the window and drive faster to finish sooner",
      "Turn the music up loudly",
      "Drink coffee and carry on without stopping",
    ],
    answer: 0,
    why: "Only sleep cures sleepiness. Microsleeps last seconds — long enough to cross a whole carriageway unconscious.",
  },
  {
    id: "sd-11",
    cat: "safe-driving",
    q: "Aquaplaning happens when:",
    options: [
      "A film of water lifts the tyres off the road surface",
      "The windscreen fogs up in the rain",
      "The brakes get wet after a puddle",
      "The wipers cannot clear heavy rain",
    ],
    answer: 0,
    why: "The tyre rides on water and loses contact. Ease off the accelerator, hold the wheel steady and do not brake hard.",
  },
  {
    id: "sd-12",
    cat: "safe-driving",
    q: "When following a heavy truck, you should:",
    options: [
      "Stay well back so you can see past it and its driver can see you",
      "Follow closely to draft and save fuel",
      "Stay in its blind spot alongside the cab",
      "Overtake immediately regardless of the road",
    ],
    answer: 0,
    why: "If you cannot see the truck's mirrors, the driver cannot see you. Distance also restores your view of the road ahead.",
  },
  {
    id: "sd-13",
    cat: "safe-driving",
    q: "Before starting the engine, a driver should first:",
    options: [
      "Adjust the seat, mirrors and fasten the seat belt",
      "Switch on the music system",
      "Rev the engine to warm it",
      "Sound the horn once",
    ],
    answer: 0,
    why: "Set up the cockpit before you move. Adjusting a mirror at 60 km/h means driving blind while you do it.",
  },
  {
    id: "sd-14",
    cat: "safe-driving",
    q: "Your vehicle breaks down on a highway. You should:",
    options: [
      "Move it off the carriageway, switch on hazard lights and place a warning triangle behind it",
      "Leave it in the lane and wait inside",
      "Stand behind the vehicle to flag down help",
      "Push it into the fast lane and call for help",
    ],
    answer: 0,
    why: "Get the vehicle and yourself off the live lane, then warn approaching traffic from a safe distance behind.",
  },
  {
    id: "sd-15",
    cat: "safe-driving",
    q: "The most effective protection for occupants in a frontal crash is:",
    options: [
      "A correctly worn seat belt, with the airbag as a supplement",
      "The airbag alone",
      "Holding the dashboard with both hands",
      "Sitting in the rear without a belt",
    ],
    answer: 0,
    why: "Airbags are supplementary restraints — they are designed to work with a belt, and are dangerous without one.",
  },
  {
    id: "sd-16",
    cat: "safe-driving",
    q: "Approaching a bend, the correct sequence is to:",
    options: [
      "Brake to the right speed before the bend, then steer smoothly through it",
      "Brake hard in the middle of the bend",
      "Accelerate into the bend then brake",
      "Coast through the bend in neutral",
    ],
    answer: 0,
    why: "Braking mid-bend shifts weight forward and can break rear grip. Do your slowing in a straight line.",
  },
  {
    id: "sd-17",
    cat: "safe-driving",
    q: "Hazard warning lights should be used:",
    options: [
      "When your vehicle is stationary and creating a hazard",
      "While driving straight through a junction",
      "While overtaking a slow vehicle",
      "In rain, to be more visible while driving",
    ],
    answer: 0,
    why: "Hazards mean a stationary hazard. Using them while moving hides your indicators, so nobody knows where you are going.",
  },
  {
    id: "sd-18",
    cat: "safe-driving",
    q: "A child under 14 travelling in a car must:",
    options: [
      "Use an appropriate restraint or seat belt for their size",
      "Sit on an adult's lap in the front seat",
      "Stand between the front seats",
      "Travel unrestrained if the journey is short",
    ],
    answer: 0,
    why: "In a crash an unrestrained child becomes a projectile. A lap is not a restraint at any speed.",
  },
  {
    id: "sd-19",
    cat: "safe-driving",
    q: "Tailgating (following too closely) is dangerous mainly because:",
    options: [
      "It removes the space you need to react and brake",
      "It wastes fuel",
      "It annoys the other driver",
      "It wears out your tyres",
    ],
    answer: 0,
    why: "Safety comes from space and time. Tailgating eliminates both, so any sudden stop ahead becomes your collision.",
  },
  {
    id: "sd-20",
    cat: "safe-driving",
    q: "You are about to overtake. The first thing to confirm is:",
    options: [
      "That the road ahead is clear for long enough to complete the pass and return",
      "That your horn works",
      "That the vehicle ahead has seen you",
      "That you are in the highest gear",
    ],
    answer: 0,
    why: "Overtaking commits you to the opposing lane. If you cannot see far enough to finish and return, do not start.",
  },
  {
    id: "sd-21",
    cat: "safe-driving",
    q: "Driving while wearing headphones in both ears is:",
    options: [
      "Unsafe and an offence, because you lose awareness of horns and sirens",
      "Perfectly safe at low volume",
      "Allowed on highways only",
      "Allowed if only music is playing",
    ],
    answer: 0,
    why: "Hearing is part of your hazard scan. Sealed ears remove the ambulance siren and the horn from behind.",
  },
  {
    id: "sd-22",
    cat: "safe-driving",
    q: "When driving through standing water, you should afterwards:",
    options: [
      "Test the brakes gently at low speed to dry them",
      "Brake hard immediately to check they work",
      "Accelerate hard to blow the water off",
      "Do nothing; brakes are unaffected by water",
    ],
    answer: 0,
    why: "Wet brakes bite poorly. Light drag on the pedal at low speed dries them before you actually need them.",
  },
  {
    id: "sd-23",
    cat: "safe-driving",
    q: "The safest way to deal with an aggressive driver behind you is to:",
    options: [
      "Stay calm, maintain your lane and let them pass when safe",
      "Brake sharply to teach them a lesson",
      "Speed up to match their pace",
      "Block them from overtaking",
    ],
    answer: 0,
    why: "Escalation puts you in the crash. Letting them go costs seconds and removes the hazard from behind you.",
  },
  {
    id: "sd-24",
    cat: "safe-driving",
    q: "At an unguarded railway level crossing you must:",
    options: [
      "Stop, look both ways and listen before crossing",
      "Cross quickly without stopping",
      "Cross only if another vehicle has just crossed",
      "Sound the horn and cross",
    ],
    answer: 0,
    why: "A train needs about a kilometre to stop and cannot swerve. Stop, look, listen — and never stop on the tracks.",
  },
];

export const RULE_CARDS = [
  {
    title: "Keep left, overtake right",
    body: "India drives on the left. Overtake only from the right, and only when you can see far enough to complete the pass and return.",
  },
  {
    title: "Sign shapes tell you the type",
    body: "Circle = mandatory (red ring forbids, blue disc commands). Triangle = cautionary warning. Rectangle = informatory. Octagon = STOP. Inverted triangle = GIVE WAY.",
  },
  {
    title: "Give way to the right",
    body: "At an uncontrolled intersection, yield to traffic approaching from your right. On a roundabout, yield to traffic already circulating.",
  },
  {
    title: "Uphill has priority",
    body: "On a narrow hill road the vehicle going uphill has right of way. The downhill vehicle backs up to the nearest wide spot.",
  },
  {
    title: "Never overtake at",
    body: "A bend, a hill crest, a junction, a pedestrian crossing, a narrow bridge, or wherever a continuous line runs on your side.",
  },
  {
    title: "Line markings",
    body: "Broken line — may cross when safe. Continuous line on your side — do not cross. Double continuous — neither side may cross. Yellow box — enter only if your exit is clear.",
  },
  {
    title: "Carry four documents",
    body: "Driving licence, registration certificate, valid insurance and a valid PUC certificate. Digital copies via DigiLocker or mParivahan are accepted.",
  },
  {
    title: "The limits that matter",
    body: "Blood alcohol 30 mg / 100 ml. Learner's licence valid 6 months. LMV licence at 18, gearless 50 cc at 16, transport vehicle at 20.",
  },
  {
    title: "Hand signals use the right arm",
    body: "Right turn — arm straight out. Left turn — arm out, rotated anticlockwise. Slow down — arm out, palm down, moving up and down. Stop — forearm raised, palm forward.",
  },
  {
    title: "Emergency vehicles always win",
    body: "Pull left and let ambulances and fire engines through. Failing to give way is a Rs 10,000 offence under the amended Act.",
  },
];
