export const airports = [
  { city: "New York", code: "JFK", airport: "John F. Kennedy International" },
  { city: "New York", code: "LGA", airport: "LaGuardia Airport" },
  { city: "Newark", code: "EWR", airport: "Newark Liberty International" },
  { city: "Los Angeles", code: "LAX", airport: "Los Angeles International" },
  { city: "Chicago", code: "ORD", airport: "O'Hare International" },
  { city: "Dallas", code: "DFW", airport: "Dallas Fort Worth International" },
  { city: "Miami", code: "MIA", airport: "Miami International" },
  { city: "Atlanta", code: "ATL", airport: "Hartsfield-Jackson Atlanta International" },
  { city: "San Francisco", code: "SFO", airport: "San Francisco International" },
  { city: "Seattle", code: "SEA", airport: "Seattle-Tacoma International" },
  { city: "Boston", code: "BOS", airport: "Boston Logan International" },
  { city: "Denver", code: "DEN", airport: "Denver International" },
  { city: "Las Vegas", code: "LAS", airport: "Harry Reid International" },
  { city: "Orlando", code: "MCO", airport: "Orlando International" },
  { city: "Phoenix", code: "PHX", airport: "Phoenix Sky Harbor International" },
  { city: "Houston", code: "IAH", airport: "George Bush Intercontinental" },
  { city: "Philadelphia", code: "PHL", airport: "Philadelphia International" },
  { city: "Charlotte", code: "CLT", airport: "Charlotte Douglas International" },
  { city: "Detroit", code: "DTW", airport: "Detroit Metropolitan Wayne County" },
  { city: "Minneapolis", code: "MSP", airport: "Minneapolis-Saint Paul International" },
];
