import {
  Activity,
  AppWindow,
  BookOpen,
  Brain,
  BriefcaseBusiness,
  Building2,
  Calculator,
  Code2,
  Dumbbell,
  FileText,
  FlaskConical,
  Gamepad2,
  Gavel,
  HandHeart,
  Gem,
  Ghost,
  Globe2,
  GraduationCap,
  HeartPulse,
  House,
  ImageIcon,
  Landmark,
  Laugh,
  LayoutGrid,
  Library,
  Lightbulb,
  Link2,
  Maximize2,
  Bot,
  MapPin,
  Monitor,
  Music4,
  Newspaper,
  Palette,
  PawPrint,
  PenTool,
  Plane,
  Puzzle,
  Radar,
  Radio,
  SearchCheck,
  ScrollText,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Tags,
  TextCursorInput,
  Trophy,
  TrendingUp,
  Video,
  Waves,
  Workflow,
  Wrench,
} from "lucide-react";
import {
  EXPERIENCE_CATALOG,
  EXPERIENCE_GROUPS,
} from "@altftool/core/experiences";
import { PRODUCT_SUITE_CATALOG } from "@altftool/core/product-suites";
import { CANONICAL_CATEGORIES } from "../registry/categoryTaxonomy.js";

const PRODUCT_SUITE_ICONS = {
  "idea-lab": Lightbulb,
  domainops: Globe2,
  minutes: FileText,
  security: ShieldCheck,
  authenticator: ShieldCheck,
  netcheck: Radar,
  career: BriefcaseBusiness,
  creator: Sparkles,
  flow: Workflow,
  impact: Globe2,
  campus: GraduationCap,
  developers: Wrench,
  vault: ShieldCheck,
};

const PRODUCT_SUITE_GROUPS = {
  "idea-lab": "Build & create",
  minutes: "Build & create",
  creator: "Build & create",
  flow: "Build & create",
  domainops: "Operate & protect",
  security: "Operate & protect",
  authenticator: "Operate & protect",
  netcheck: "Operate & protect",
  developers: "Operate & protect",
  vault: "Operate & protect",
  career: "Career & impact",
  impact: "Career & impact",
  campus: "Career & impact",
};

const EXPERIENCE_ICONS = {
  Activity,
  AppWindow,
  BookOpen,
  Brain,
  Gamepad2,
  Ghost,
  ImageIcon,
  Landmark,
  Laugh,
  LayoutGrid,
  Library,
  Music4,
  PenTool,
  Plane,
  Puzzle,
  Radio,
  ScrollText,
  Sparkles,
  Waves,
};

const TOOL_CATEGORY_ICONS = {
  "ai-tools": Bot,
  "pdf-documents": FileText,
  "image-photo": ImageIcon,
  "video-audio": Video,
  "text-writing": TextCursorInput,
  converters: Workflow,
  generators: Sparkles,
  calculators: Calculator,
  "finance-calculators": Gem,
  "health-calculators": HeartPulse,
  "health-fitness": Dumbbell,
  developer: Code2,
  "design-color": Palette,
  "marketing-social": Radar,
  "security-privacy": ShieldCheck,
  "education-science": GraduationCap,
  productivity: Workflow,
  business: Building2,
  lifestyle: House,
  fun: Laugh,
  games: Gamepad2,
  other: LayoutGrid,
};

const TOOL_CATEGORY_GROUPS = {
  "ai-tools": "Create & work",
  "image-photo": "Create & work",
  "video-audio": "Create & work",
  "text-writing": "Create & work",
  generators: "Create & work",
  "design-color": "Create & work",
  "marketing-social": "Create & work",
  productivity: "Create & work",
  business: "Create & work",
  "pdf-documents": "Build & calculate",
  developer: "Build & calculate",
  "security-privacy": "Build & calculate",
  converters: "Build & calculate",
  calculators: "Build & calculate",
  "finance-calculators": "Build & calculate",
  "health-calculators": "Build & calculate",
  "education-science": "Learn & everyday",
  "health-fitness": "Learn & everyday",
  lifestyle: "Learn & everyday",
  fun: "Learn & everyday",
  games: "Learn & everyday",
  other: "Learn & everyday",
};

export const PRODUCT_SUITE_ROUTE_OPTIONS = PRODUCT_SUITE_CATALOG.map((suite) => ({
  label: suite.name.replace(/^AltF\s+/, ""),
  href: `/products/${suite.slug}`,
  group: PRODUCT_SUITE_GROUPS[suite.slug] || "Product suites",
  icon: PRODUCT_SUITE_ICONS[suite.slug] || LayoutGrid,
}));

export const EXPERIENCE_ROUTE_OPTIONS = EXPERIENCE_CATALOG.map((experience) => ({
  label: experience.name,
  href: experience.href,
  match: [experience.href],
  group: EXPERIENCE_GROUPS[experience.group]?.label || "Labs",
  icon: EXPERIENCE_ICONS[experience.icon] || FlaskConical,
}));

export const TOOL_CATEGORY_ROUTE_OPTIONS = CANONICAL_CATEGORIES.map((category) => ({
  label: category.label,
  href: `/tools/${category.slug}`,
  match: [`/tools/${category.slug}`],
  group: TOOL_CATEGORY_GROUPS[category.slug] || "More tool categories",
  icon: TOOL_CATEGORY_ICONS[category.slug] || LayoutGrid,
}));

export const SITE_ROUTES = {
  home: { label: "Home", href: "/" },
  tools: { label: "Tools", href: "/tools/all", match: ["/tools"] },
  apps: { label: "Android Apps", href: "/apps", match: ["/apps"] },
  products: { label: "Products", href: "/products" },
  labs: { label: "Labs", href: "/labs" },
  signals: { label: "Signals", href: "/signals" },
  ideaLab: { label: "IdeaLab", href: "/products/idea-lab" },
  domainOps: { label: "DomainOps", href: "/products/domainops" },
  minutes: { label: "Minutes", href: "/products/minutes" },
  flow: { label: "Flow", href: "/products/flow" },
  impact: { label: "Impact", href: "/products/impact" },
  businessOps: { label: "Business Ops", href: "/bops" },
  tradeon: {
    label: "Tradeon Markets",
    href: "/tradeon",
    match: ["/tradeon"],
  },
  loans: {
    label: "Loans",
    href: "/bops/loans",
    match: ["/bops/loans"],
  },
  insurance: {
    label: "Insurance",
    href: "/bops/insurance",
    match: ["/bops/insurance"],
  },
  homeServices: {
    label: "Home Services",
    href: "/homeserv",
    match: ["/homeserv"],
  },
  housingNeeds: { label: "Housing Needs", href: "/bops/housingneeds", match: ["/bops/housingneeds", "/housingneeds"] },
  housingServices: {
    label: "Housing Services",
    href: "/bops/housing-services",
    match: ["/bops/housing-services"],
  },
  legalServices: {
    label: "Legal Services",
    href: "/bops/legal-services",
    match: ["/bops/legal-services"],
  },
  seniorCare: {
    label: "Senior Care",
    href: "/bops/senior-care",
    match: ["/bops/senior-care"],
  },
  petServices: {
    label: "Pet Services",
    href: "/bops/pet-services",
    match: ["/bops/pet-services"],
  },
  tripFindBox: {
    label: "TripFindBox",
    href: "/bops/tripfindbox",
    match: ["/bops/tripfindbox"],
  },
  calculators: {
    label: "Calculators",
    href: "/altfcalculators",
    match: ["/altfcalculators"],
  },
  promptStudio: {
    label: "AI Prompt Studio",
    href: "/imgprompt",
    match: ["/imgprompt"],
  },
  automationLibrary: {
    label: "Automation Library",
    href: "/n8n",
    match: ["/n8n"],
  },
  smartLink: {
    label: "Smart Link",
    href: "/smartlink",
    match: ["/smartlink"],
  },
  fullScreen: {
    label: "Fullscreen Browser",
    href: "/fullscrn",
    match: ["/fullscrn"],
  },
  webSearch: {
    label: "Web Search",
    href: "/search-eng",
    match: ["/search-eng"],
  },
  seedreamPrompts: {
    label: "Seedream Prompts",
    href: "/prompts/seedream-5-pro",
    match: ["/prompts/seedream-5-pro"],
  },
  factNet: { label: "FactNet", href: "/fact-net", match: ["/fact-net"] },
  bharatVirasat: {
    label: "Bharat Virasat",
    href: "/bharat-virasat",
    match: ["/bharat-virasat"],
  },
  mockly: {
    label: "Mockly",
    href: "/prank-socialmedia",
    match: ["/prank-socialmedia"],
  },
  games: { label: "Games", href: "/games" },
  altfGames: { label: "AltF Games", href: "/altfgame", match: ["/altfgame"] },
  extensions: { label: "Extensions", href: "/extensions" },
  altfDeals: { label: "AltF Deals", href: "/deals" },
  exclusiveDeals: { label: "Exclusive Deals", href: "/exclusivedeals" },
  buySmart: { label: "BuySmart", href: "/buysmart" },
  saleLocator: { label: "Sale Locator", href: "/sale" },
  imgPrompt: { label: "Img Prompt", href: "/imgprompt" },
  freeAiTool: { label: "Free-Ai-Tool", href: "/free-ai-tool" },
  academy: { label: "Academy", href: "/academy" },
  blogs: { label: "Blog", href: "/blogs" },
  brandRatings: { label: "Brand Ratings", href: "/brandrating" },
  support: { label: "Support", href: "/supportsetting" },
  requestTool: { label: "Request a Tool", href: "/request-a-tool" },
  faq: { label: "FAQ", href: "/policypages/faq" },
  status: { label: "Status", href: "/status" },
  licenses: { label: "Open Source Licenses", href: "/licenses" },
  siteMap: { label: "Site Map", href: "/site-map" },
  imageTools: { label: "Image Tools", href: "/altfloveimg" },
  pdfTools: { label: "PDF Tools", href: "/altflovepdf" },
  news: { label: "News", href: "/news" },
  locations: { label: "Locations", href: "/locations" },
  desktop: { label: "Desktop Software", href: "/desktop" },
  trendingVideos: { label: "Trending Videos", href: "/trendingvids" },
  personality: { label: "Personality", href: "/personality" },
  top11: { label: "Top11", href: "/top11" },
  top9: { label: "Top9", href: "/top9" },
  about: { label: "About AltFTool", href: "/policypages/about" },
  contact: { label: "Contact", href: "/policypages/contact" },
  privacy: { label: "Privacy", href: "/policypages/privacy" },
  terms: { label: "Terms", href: "/policypages/termsandconditions" },
  disclaimer: { label: "Disclaimer", href: "/policypages/disclaimer" },
  affiliate: { label: "Affiliate", href: "/policypages/affiliate" },
  cookie: { label: "Cookie", href: "/policypages/cookie" },
};

export const PUBLIC_NAV_ITEMS = [
  {
    ...SITE_ROUTES.products,
    icon: LayoutGrid,
    menuAlign: "left",
    menuColumns: 3,
    options: [
      { ...SITE_ROUTES.products, group: "Overview", icon: LayoutGrid },
      { ...SITE_ROUTES.signals, group: "Overview", icon: Radar },
      { ...SITE_ROUTES.tradeon, group: "Overview", icon: TrendingUp },
      ...PRODUCT_SUITE_ROUTE_OPTIONS,
      { ...SITE_ROUTES.businessOps, group: "Business operations", icon: BriefcaseBusiness },
      { ...SITE_ROUTES.homeServices, group: "Business operations", icon: House },
      { ...SITE_ROUTES.housingNeeds, group: "Business operations", icon: House },
      { ...SITE_ROUTES.housingServices, group: "Business operations", icon: Wrench },
      { ...SITE_ROUTES.tripFindBox, group: "Business operations", icon: Plane },
      { ...SITE_ROUTES.loans, group: "Business operations", icon: Landmark },
      { ...SITE_ROUTES.insurance, group: "Business operations", icon: ShieldCheck },
      { ...SITE_ROUTES.petServices, group: "Business operations", icon: PawPrint },
      { ...SITE_ROUTES.legalServices, group: "Business operations", icon: Gavel },
      { ...SITE_ROUTES.seniorCare, group: "Business operations", icon: HandHeart },
    ],
  },
  {
    ...SITE_ROUTES.tools,
    icon: Wrench,
    menuAlign: "left",
    menuColumns: 4,
    options: [
      { ...SITE_ROUTES.tools, group: "Directories & apps", icon: Wrench },
      { ...SITE_ROUTES.calculators, group: "Directories & apps", icon: Calculator },
      { ...SITE_ROUTES.imageTools, group: "Directories & apps", icon: ImageIcon },
      { ...SITE_ROUTES.pdfTools, group: "Directories & apps", icon: FileText },
      { ...SITE_ROUTES.apps, group: "Directories & apps", icon: Smartphone },
      { ...SITE_ROUTES.desktop, group: "Directories & apps", icon: Monitor },
      { ...SITE_ROUTES.games, group: "Directories & apps", icon: Gamepad2 },
      { ...SITE_ROUTES.altfGames, group: "Directories & apps", icon: Gamepad2 },
      ...TOOL_CATEGORY_ROUTE_OPTIONS,
      { ...SITE_ROUTES.promptStudio, group: "Create & work", icon: Sparkles },
      { ...SITE_ROUTES.automationLibrary, group: "Create & work", icon: Bot },
      { ...SITE_ROUTES.smartLink, group: "Build & calculate", icon: Link2 },
      { ...SITE_ROUTES.fullScreen, group: "Build & calculate", icon: Maximize2 },
      { ...SITE_ROUTES.webSearch, group: "Build & calculate", icon: SearchCheck },
      { ...SITE_ROUTES.seedreamPrompts, group: "Learn & everyday", icon: Sparkles },
    ],
  },
  {
    ...SITE_ROUTES.extensions,
    icon: Puzzle,
    menuColumns: 2,
    options: [
      { ...SITE_ROUTES.extensions, group: "Browser", icon: Puzzle },
      { ...SITE_ROUTES.apps, group: "Apps & software", icon: Smartphone },
      { ...SITE_ROUTES.desktop, group: "Apps & software", icon: Monitor },
    ],
  },
  {
    ...SITE_ROUTES.altfDeals,
    label: "Deals",
    icon: Tags,
    menuColumns: 2,
    options: [
      { ...SITE_ROUTES.altfDeals, label: "All Deals", group: "Find deals", icon: Gem },
      { ...SITE_ROUTES.exclusiveDeals, group: "Find deals", icon: Tags },
      { ...SITE_ROUTES.buySmart, group: "Find deals", icon: ShoppingBag },
      { ...SITE_ROUTES.saleLocator, group: "Find deals", icon: MapPin },
      { ...SITE_ROUTES.brandRatings, group: "Research", icon: ShieldCheck },
      { ...SITE_ROUTES.top11, group: "Research", icon: Trophy },
      { ...SITE_ROUTES.top9, group: "Research", icon: LayoutGrid },
    ],
  },
  {
    ...SITE_ROUTES.academy,
    label: "Learn",
    icon: BookOpen,
    menuColumns: 3,
    options: [
      { ...SITE_ROUTES.academy, group: "Learn & follow", icon: GraduationCap },
      { ...SITE_ROUTES.blogs, group: "Learn & follow", icon: BookOpen },
      { ...SITE_ROUTES.news, group: "Learn & follow", icon: Newspaper },
      { ...SITE_ROUTES.trendingVideos, group: "Learn & follow", icon: Sparkles },
      { ...SITE_ROUTES.locations, group: "Learn & follow", icon: MapPin },
      { ...SITE_ROUTES.factNet, group: "Knowledge", icon: Library },
      { ...SITE_ROUTES.bharatVirasat, group: "Knowledge", icon: Landmark },
      { ...SITE_ROUTES.seedreamPrompts, group: "Knowledge", icon: Sparkles },
      { ...SITE_ROUTES.requestTool, group: "Help & directory", icon: Wrench },
      { ...SITE_ROUTES.support, group: "Help & directory", icon: ShieldCheck },
      { ...SITE_ROUTES.faq, group: "Help & directory", icon: BookOpen },
      { ...SITE_ROUTES.siteMap, group: "Help & directory", icon: LayoutGrid },
      { ...SITE_ROUTES.status, group: "Help & directory", icon: Activity },
    ],
  },
  {
    ...SITE_ROUTES.labs,
    icon: FlaskConical,
    menuAlign: "right",
    menuColumns: 3,
    options: [
      { ...SITE_ROUTES.labs, group: "Create & experiment", icon: FlaskConical },
      ...EXPERIENCE_ROUTE_OPTIONS,
    ],
  },
];

export const FOOTER_ROUTE_GROUPS = [
  {
    title: "Products",
    links: [
      SITE_ROUTES.products,
      SITE_ROUTES.signals,
      SITE_ROUTES.ideaLab,
      SITE_ROUTES.domainOps,
      SITE_ROUTES.flow,
      SITE_ROUTES.tradeon,
      SITE_ROUTES.businessOps,
      SITE_ROUTES.housingNeeds,
    ],
  },
  {
    title: "Tools",
    links: [
      SITE_ROUTES.tools,
      SITE_ROUTES.calculators,
      SITE_ROUTES.imageTools,
      SITE_ROUTES.pdfTools,
      SITE_ROUTES.extensions,
      SITE_ROUTES.apps,
      SITE_ROUTES.desktop,
      SITE_ROUTES.automationLibrary,
    ],
  },
  {
    title: "Discover",
    links: [
      SITE_ROUTES.labs,
      SITE_ROUTES.games,
      SITE_ROUTES.altfGames,
      SITE_ROUTES.academy,
      SITE_ROUTES.blogs,
      SITE_ROUTES.news,
      SITE_ROUTES.locations,
      SITE_ROUTES.trendingVideos,
    ],
  },
  {
    title: "Shopping",
    links: [
      SITE_ROUTES.altfDeals,
      SITE_ROUTES.exclusiveDeals,
      SITE_ROUTES.buySmart,
      SITE_ROUTES.brandRatings,
      SITE_ROUTES.top11,
      SITE_ROUTES.top9,
    ],
  },
  {
    title: "Company",
    links: [
      SITE_ROUTES.about,
      SITE_ROUTES.contact,
      SITE_ROUTES.support,
      SITE_ROUTES.requestTool,
      SITE_ROUTES.status,
      SITE_ROUTES.siteMap,
      SITE_ROUTES.licenses,
    ],
  },
];

export const LEGAL_ROUTE_LINKS = [
  SITE_ROUTES.disclaimer,
  SITE_ROUTES.affiliate,
  SITE_ROUTES.cookie,
];

// Top tools surfaced as server-rendered links in the footer (every page) to push
// crawl equity to the highest-value canonical tool pages.
export const POPULAR_TOOL_LINKS = [
  { label: "Image Resizer", href: "/tools/all/image-resizer" },
  { label: "Image Compressor", href: "/tools/all/image-compressor" },
  { label: "Unit Converter", href: "/tools/all/unit-converter" },
  { label: "Base Converter", href: "/tools/all/base-converter" },
  { label: "Scientific Notation Calculator", href: "/tools/all/scientific-notation-calculator" },
  { label: "Invoice Generator", href: "/tools/all/invoice-generator" },
  { label: "Web Speed Checker", href: "/tools/all/web-speed-checker" },
  { label: "Password Generator", href: "/tools/all/password-generator" },
  { label: "BMI Calculator", href: "/tools/all/bmi-calculator" },
  { label: "Age Calculator", href: "/tools/all/age-calculator" },
  { label: "Percentage Calculator", href: "/tools/all/percentage-calculator" },
  { label: "Markdown Preview", href: "/tools/all/markdown-preview" },
  { label: "Resume Maker", href: "/tools/all/resume-maker" },
  { label: "Meme Generator", href: "/tools/all/meme-generator" },
  { label: "Currency Converter", href: "/tools/all/currency-converter" },
  { label: "UUID Generator", href: "/tools/all/uuid-generator" },
  { label: "Aspect Ratio Calculator", href: "/tools/all/aspect-ratio-calculator" },
  { label: "Barcode Generator", href: "/tools/all/barcode-generator" },
  { label: "Lorem Ipsum Generator", href: "/tools/all/lorem-ipsum-generator" },
  { label: "Emoji Hub", href: "/tools/all/emoji-hub" },
  { label: "Lucky Number Generator", href: "/tools/all/lucky-number-generator" },
  { label: "Rock Paper Scissors", href: "/tools/all/rock-paper-scissors" },
  { label: "Snake Game", href: "/tools/all/snake-game" },
  { label: "Tic Tac Toe", href: "/tools/all/tic-tac-toe-game" },
  { label: "Joke Generator", href: "/tools/all/joke-generator" },
  { label: "Dice Roller (3D)", href: "/tools/all/dice-roller-3d" },
  { label: "Whack-a-Mole", href: "/tools/all/whack-a-mole" },
  { label: "Emoji Quiz", href: "/tools/all/emoji-quiz" },
  { label: "Memory Card Game", href: "/tools/all/memory-card-game" },
  { label: "Compliment Generator", href: "/tools/all/compliment-generator" },
];

const HIDDEN_PUBLIC_SHELL_PREFIXES = ["/search-eng"];
const HIDDEN_PUBLIC_SHELL_PATTERNS = [];

export function isPublicShellHidden(pathname = "") {
  return (
    HIDDEN_PUBLIC_SHELL_PREFIXES.some(
      (prefix) => pathname === prefix || pathname.startsWith(`${prefix}/`),
    ) || HIDDEN_PUBLIC_SHELL_PATTERNS.some((pattern) => pattern.test(pathname))
  );
}

export function isPublicRouteActive(pathname = "", route = {}) {
  const hrefs = [route.href, ...(route.match || [])].filter(Boolean);
  return hrefs.some((href) => pathname === href || pathname.startsWith(`${href}/`));
}
