export const STATE_CODES = {
  AN: { name: "Andaman & Nicobar Islands", type: "Union Territory" },
  AP: { name: "Andhra Pradesh", type: "State" },
  AR: { name: "Arunachal Pradesh", type: "State" },
  AS: { name: "Assam", type: "State" },
  BR: { name: "Bihar", type: "State" },
  CG: { name: "Chhattisgarh", type: "State" },
  CH: { name: "Chandigarh", type: "Union Territory" },
  DD: { name: "Dadra & Nagar Haveli and Daman & Diu", type: "Union Territory" },
  DL: { name: "Delhi", type: "Union Territory" },
  GA: { name: "Goa", type: "State" },
  GJ: { name: "Gujarat", type: "State" },
  HP: { name: "Himachal Pradesh", type: "State" },
  HR: { name: "Haryana", type: "State" },
  JH: { name: "Jharkhand", type: "State" },
  JK: { name: "Jammu & Kashmir", type: "Union Territory" },
  KA: { name: "Karnataka", type: "State" },
  KL: { name: "Kerala", type: "State" },
  LA: { name: "Ladakh", type: "Union Territory" },
  LD: { name: "Lakshadweep", type: "Union Territory" },
  MH: { name: "Maharashtra", type: "State" },
  ML: { name: "Meghalaya", type: "State" },
  MN: { name: "Manipur", type: "State" },
  MP: { name: "Madhya Pradesh", type: "State" },
  MZ: { name: "Mizoram", type: "State" },
  NL: { name: "Nagaland", type: "State" },
  OD: { name: "Odisha", type: "State" },
  PB: { name: "Punjab", type: "State" },
  PY: { name: "Puducherry", type: "Union Territory" },
  RJ: { name: "Rajasthan", type: "State" },
  SK: { name: "Sikkim", type: "State" },
  TG: { name: "Telangana", type: "State" },
  TN: { name: "Tamil Nadu", type: "State" },
  TR: { name: "Tripura", type: "State" },
  UK: { name: "Uttarakhand", type: "State" },
  UP: { name: "Uttar Pradesh", type: "State" },
  WB: { name: "West Bengal", type: "State" },
};

export const LEGACY_CODES = {
  DN: {
    name: "Dadra & Nagar Haveli",
    type: "Union Territory",
    legacy: "Merged into the DD code when the UTs combined in 2020. Existing plates stay valid.",
  },
  OR: {
    name: "Odisha",
    type: "State",
    legacy: "Replaced by OD in 2011. Existing plates stay valid.",
  },
  TS: {
    name: "Telangana",
    type: "State",
    legacy: "Replaced by TG in 2024. Existing plates stay valid.",
  },
  UA: {
    name: "Uttarakhand",
    type: "State",
    legacy: "Replaced by UK in 2007. Existing plates stay valid.",
  },
};

const range = (from, to, name) => {
  const out = {};
  for (let index = from; index <= to; index += 1) {
    out[String(index).padStart(2, "0")] = name;
  }
  return out;
};

export const DISTRICTS = {
  MH: {
    "01": "Mumbai Central (Tardeo)",
    "02": "Mumbai West (Andheri)",
    "03": "Mumbai East (Wadala)",
    "04": "Thane",
    "05": "Kalyan",
    "06": "Raigad (Pen)",
    "07": "Sindhudurg",
    "08": "Ratnagiri",
    "09": "Kolhapur",
    10: "Sangli",
    11: "Satara",
    12: "Pune",
    13: "Solapur",
    14: "Pimpri-Chinchwad",
    15: "Nashik",
    16: "Shrirampur",
    17: "Ahmednagar",
    18: "Dhule",
    19: "Jalgaon",
    20: "Chhatrapati Sambhajinagar (Aurangabad)",
    21: "Jalna",
    22: "Parbhani",
    23: "Beed",
    24: "Latur",
    25: "Dharashiv (Osmanabad)",
    26: "Nanded",
    27: "Amravati",
    28: "Buldhana",
    29: "Yavatmal",
    30: "Akola",
    31: "Nagpur",
    32: "Wardha",
    33: "Gadchiroli",
    34: "Chandrapur",
    35: "Gondia",
    36: "Bhandara",
    37: "Washim",
    38: "Hingoli",
    39: "Nandurbar",
    40: "Nagpur (Rural)",
    41: "Malegaon",
    42: "Baramati",
    43: "Navi Mumbai (Vashi)",
    44: "Ambejogai",
    45: "Akluj",
    46: "Panvel",
    47: "Mumbai North (Borivali)",
    48: "Vasai-Virar",
    49: "Nagpur (East)",
    50: "Karad",
  },
  DL: {
    "01": "Delhi (Mall Road)",
    "02": "Delhi (Tilak Marg)",
    "03": "Delhi (Sheikh Sarai)",
    "04": "Delhi (Janakpuri)",
    "05": "Delhi (Loni Road, Shahdara)",
    "06": "Delhi (Sarai Kale Khan)",
    "07": "Delhi (Mayur Vihar)",
    "08": "Delhi (Wazirpur)",
    "09": "Delhi (Dwarka, South West)",
    10: "Delhi (Raja Garden)",
    11: "Delhi (Rohini)",
    12: "Delhi (Vasant Vihar)",
    13: "Delhi (Surajmal Vihar)",
  },
  KA: {
    "01": "Bengaluru Central (Koramangala)",
    "02": "Bengaluru West (Rajajinagar)",
    "03": "Bengaluru East (Indiranagar)",
    "04": "Bengaluru North (Yeshwanthpur)",
    "05": "Bengaluru South (Jayanagar)",
    "06": "Tumakuru",
    "07": "Kolar",
    "08": "Kolar Gold Fields",
    "09": "Mysuru",
    10: "Chamarajanagar",
    11: "Mandya",
    12: "Madikeri (Kodagu)",
    13: "Hassan",
    14: "Shivamogga",
    15: "Sagara",
    16: "Chitradurga",
    17: "Davanagere",
    18: "Chikkamagaluru",
    19: "Mangaluru (Dakshina Kannada)",
    20: "Udupi",
    21: "Puttur",
    22: "Belagavi",
    23: "Chikkodi",
    24: "Bailhongal",
    25: "Hubballi-Dharwad",
    26: "Gadag",
    27: "Haveri",
    28: "Vijayapura (Bijapur)",
    29: "Bagalkot",
    30: "Karwar (Uttara Kannada)",
    31: "Sirsi",
    32: "Kalaburagi (Gulbarga)",
    33: "Yadgir",
    34: "Ballari",
    35: "Hosapete",
    36: "Raichur",
    37: "Koppal",
    38: "Bidar",
    39: "Bhalki",
    40: "Basavakalyan",
    41: "Bengaluru North (Jnanabharathi)",
    42: "Ramanagara",
    43: "Bengaluru East (Whitefield)",
    44: "Tiptur",
    46: "Sakleshpur",
    47: "Honnavar",
    48: "Jamkhandi",
    49: "Gokak",
    50: "Bengaluru North (Yelahanka)",
    51: "Bengaluru South (Electronic City)",
    52: "Nelamangala",
  },
  TN: {
    "01": "Chennai (Central)",
    "02": "Chennai (North West)",
    "03": "Chennai (North East)",
    "04": "Chennai (Central)",
    "05": "Chennai (North)",
    "06": "Chennai (South)",
    "07": "Chennai (South East)",
    "09": "Chennai (East)",
    10: "Chennai (West)",
    11: "Tambaram",
    12: "Poonamallee",
    13: "Ambattur",
    14: "Chennai (Kodambakkam)",
    21: "Kanchipuram",
    23: "Tindivanam",
    28: "Salem (West)",
    30: "Salem (East)",
    31: "Namakkal",
    33: "Erode",
    37: "Coimbatore (Central)",
    38: "Coimbatore (South)",
    39: "Tiruppur",
    41: "Pollachi",
    42: "Udhagamandalam (Ooty)",
    45: "Tiruchirappalli",
    47: "Karur",
    49: "Thanjavur",
    50: "Kumbakonam",
    54: "Pudukkottai",
    57: "Madurai (Central)",
    58: "Madurai (South)",
    59: "Madurai (North)",
    69: "Thoothukudi",
    72: "Tirunelveli",
    74: "Kanyakumari (Nagercoil)",
  },
  UP: {
    11: "Saharanpur",
    12: "Muzaffarnagar",
    13: "Bulandshahr",
    14: "Ghaziabad",
    15: "Meerut",
    16: "Gautam Buddha Nagar (Noida)",
    17: "Baghpat",
    20: "Bijnor",
    21: "Moradabad",
    22: "Rampur",
    23: "Amroha (Jyotiba Phule Nagar)",
    24: "Budaun",
    25: "Bareilly",
    26: "Pilibhit",
    27: "Shahjahanpur",
    30: "Hardoi",
    31: "Lakhimpur Kheri",
    32: "Lucknow",
    33: "Raebareli",
    34: "Sitapur",
    35: "Unnao",
    40: "Bahraich",
    41: "Barabanki",
    42: "Ayodhya (Faizabad)",
    43: "Gonda",
    44: "Sultanpur",
    45: "Ambedkar Nagar",
    50: "Azamgarh",
    51: "Basti",
    52: "Deoria",
    53: "Gorakhpur",
    54: "Mau",
    55: "Siddharthnagar",
    56: "Maharajganj",
    57: "Kushinagar (Padrauna)",
    58: "Sant Kabir Nagar",
    60: "Ballia",
    61: "Ghazipur",
    62: "Jaunpur",
    63: "Mirzapur",
    64: "Sonbhadra",
    65: "Varanasi",
    66: "Bhadohi (Sant Ravidas Nagar)",
    67: "Chandauli",
    70: "Prayagraj (Allahabad)",
    71: "Fatehpur",
    72: "Pratapgarh",
    73: "Kaushambi",
    74: "Kannauj",
    75: "Etawah",
    76: "Farrukhabad",
    77: "Kanpur Dehat",
    78: "Kanpur Nagar",
    79: "Auraiya",
    80: "Agra",
    81: "Aligarh",
    82: "Etah",
    83: "Firozabad",
    84: "Mainpuri",
    85: "Mathura",
    86: "Hathras (Mahamaya Nagar)",
    87: "Kasganj",
    90: "Banda",
    91: "Hamirpur",
    92: "Jalaun (Orai)",
    93: "Jhansi",
    94: "Lalitpur",
    95: "Mahoba",
    96: "Chitrakoot",
  },
  GJ: {
    "01": "Ahmedabad",
    "02": "Mehsana",
    "03": "Rajkot",
    "04": "Bhavnagar",
    "05": "Surat",
    "06": "Vadodara",
    "07": "Nadiad (Kheda)",
    "08": "Palanpur (Banaskantha)",
    "09": "Himmatnagar (Sabarkantha)",
    10: "Jamnagar",
    11: "Junagadh",
    12: "Bhuj (Kutch)",
    13: "Surendranagar",
    14: "Amreli",
    15: "Valsad",
    16: "Bharuch",
    17: "Godhra (Panchmahal)",
    18: "Gandhinagar",
    19: "Bardoli",
    20: "Dahod",
    21: "Navsari",
    22: "Rajpipla (Narmada)",
    23: "Anand",
    24: "Patan",
    25: "Porbandar",
    26: "Vyara (Tapi)",
    27: "Ahmedabad (East, Vastral)",
    30: "Ahwa (Dang)",
    31: "Modasa (Aravalli)",
    32: "Botad",
    33: "Chhota Udaipur",
    34: "Khambhalia (Devbhoomi Dwarka)",
    35: "Veraval (Gir Somnath)",
    36: "Lunawada (Mahisagar)",
    37: "Morbi",
  },
  RJ: {
    "01": "Ajmer",
    "02": "Alwar",
    "03": "Banswara",
    "04": "Barmer",
    "05": "Bharatpur",
    "06": "Bhilwara",
    "07": "Bikaner",
    "08": "Bundi",
    "09": "Chittorgarh",
    10: "Churu",
    11: "Dholpur",
    12: "Dungarpur",
    13: "Sri Ganganagar",
    14: "Jaipur (South)",
    15: "Jaisalmer",
    16: "Jalore",
    17: "Jhalawar",
    18: "Jhunjhunu",
    19: "Jodhpur",
    20: "Kota",
    21: "Nagaur",
    22: "Pali",
    23: "Sikar",
    24: "Sirohi",
    25: "Sawai Madhopur",
    26: "Tonk",
    27: "Udaipur",
    28: "Baran",
    29: "Dausa",
    30: "Rajsamand",
    31: "Hanumangarh",
    34: "Karauli",
    35: "Pratapgarh",
    45: "Jaipur (North)",
  },
  WB: {
    ...range(1, 10, "Kolkata (Beltala RTO)"),
    ...range(11, 20, "Kolkata (Kasba RTO)"),
    ...range(23, 26, "North 24 Parganas (Barasat / Barrackpore)"),
    ...range(33, 36, "Howrah"),
    ...range(37, 38, "Hooghly (Chinsurah)"),
    ...range(39, 40, "Purba Medinipur (Tamluk)"),
    ...range(41, 42, "Paschim Medinipur (Midnapore)"),
    ...range(45, 46, "Purba Bardhaman (Burdwan)"),
    ...range(47, 48, "Paschim Bardhaman (Asansol)"),
    ...range(51, 52, "Birbhum (Suri)"),
    ...range(53, 54, "Murshidabad (Berhampore)"),
    ...range(55, 56, "Nadia (Krishnanagar)"),
    ...range(57, 58, "Uttar Dinajpur (Raiganj)"),
    ...range(59, 60, "Dakshin Dinajpur (Balurghat)"),
    ...range(61, 62, "Malda"),
    ...range(63, 64, "Jalpaiguri"),
    ...range(65, 66, "Darjeeling"),
    ...range(67, 68, "Cooch Behar"),
    ...range(73, 74, "Siliguri (Darjeeling)"),
  },
};

export const STATE_NOTES = {
  DL: "Delhi puts a vehicle-class letter straight after the RTO code, so DL 1C is a private car from RTO 1 and DL 3S is a two-wheeler from RTO 3. No other state does this.",
  WB: "West Bengal gives each RTO a block of codes rather than one number, because separate blocks are used for different vehicle classes.",
  UP: "Uttar Pradesh has no UP 01 to UP 10. Its RTO codes begin at UP 11 (Saharanpur) and run to UP 96.",
};

export const DELHI_CLASSES = {
  C: "Private car",
  S: "Scooter or motorcycle",
  T: "Taxi",
  R: "Three-wheeler rickshaw",
  P: "Passenger service vehicle (bus)",
};

export const DIPLOMATIC_SERIES = {
  CD: "Corps Diplomatique - an accredited diplomatic mission",
  CC: "Consular Corps - a consular post",
  UN: "United Nations agency",
};

export const PLATE_TYPES = [
  {
    id: "white",
    name: "White plate, black text",
    use: "Private vehicles",
    detail:
      "Your own car or two-wheeler, used for non-commercial purposes. Cannot legally be hired out or used to carry paying passengers.",
    bg: "#FFFFFF",
    fg: "#111111",
    outline: true,
    sample: "MH 12 AB 1234",
  },
  {
    id: "yellow",
    name: "Yellow plate, black text",
    use: "Commercial and transport",
    detail:
      "Taxis, auto-rickshaws, trucks and buses. Needs a transport permit, a commercial driving licence and a fitness certificate.",
    bg: "#F2C200",
    fg: "#111111",
    sample: "KA 01 AC 5678",
  },
  {
    id: "green-private",
    name: "Green plate, white text",
    use: "Private electric vehicle",
    detail:
      "Battery electric vehicles registered for personal use. Many states waive or cut road tax and registration fees on these.",
    bg: "#0B7A4B",
    fg: "#FFFFFF",
    sample: "DL 1C EV 0007",
  },
  {
    id: "green-commercial",
    name: "Green plate, yellow text",
    use: "Commercial electric vehicle",
    detail:
      "Electric taxis, e-buses and electric goods carriers. Green marks the powertrain, yellow lettering marks the commercial permit.",
    bg: "#0B7A4B",
    fg: "#F2C200",
    sample: "TN 09 EV 4321",
  },
  {
    id: "black",
    name: "Black plate, yellow text",
    use: "Self-drive rental",
    detail:
      "Rent-a-cab vehicles you drive yourself. Commercially registered, but no commercial licence is needed because there is no hired driver.",
    bg: "#141414",
    fg: "#F2C200",
    sample: "GA 03 Z 9012",
  },
  {
    id: "blue",
    name: "Blue plate, white text",
    use: "Diplomatic corps",
    detail:
      "Foreign missions and UN agencies. Carries CD, CC or UN instead of a state code, and a number that identifies the country.",
    bg: "#12369E",
    fg: "#FFFFFF",
    sample: "13 CD 0001",
  },
  {
    id: "red",
    name: "Red plate, white text",
    use: "Temporary registration",
    detail:
      "A brand new vehicle running on a dealer-issued temporary number, valid for up to one month while the permanent registration is processed.",
    bg: "#B3252B",
    fg: "#FFFFFF",
    sample: "MH 04 TC 1234",
  },
  {
    id: "red-emblem",
    name: "Red plate, national emblem",
    use: "President and State Governors",
    detail:
      "The only vehicles in India allowed to run with no registration number at all. The Emblem of India replaces the number entirely.",
    bg: "#B3252B",
    fg: "#E3C377",
    sample: "Emblem of India",
  },
  {
    id: "military",
    name: "Black plate, broad arrow",
    use: "Armed forces",
    detail:
      "Registered by the Ministry of Defence, not by any RTO. The number opens with an upward broad arrow, then the year of procurement.",
    bg: "#141414",
    fg: "#FFFFFF",
    sample: "↑ 10A 123456 K",
  },
];

export const HSRP_FACTS = [
  {
    title: "What an HSRP actually is",
    body: "An aluminium plate with a permanent 10-digit laser-etched code, a hot-stamped chromium IND hologram, and a snap lock that breaks if anyone tries to remove it. The laser code is unique to your vehicle, which is what makes a fake plate hard to pass off.",
  },
  {
    title: "The third sticker on your windscreen",
    body: "A colour-coded fuel sticker comes with the HSRP: light blue for petrol and CNG, orange for diesel. It carries the registration number, the registering authority, the laser code and the chassis number.",
  },
  {
    title: "Getting one fitted",
    body: "Book through your state transport department portal or an authorised dealer, pick a fitment centre and slot, and pay online. New vehicles come fitted from the dealer. Fines for running without one vary by state and are enforced hardest in Delhi-NCR.",
  },
  {
    title: "FASTag is tied to this number",
    body: "The RFID tag on your windscreen is linked to the registration number and is mandatory for four-wheelers on national highways. Under the One Vehicle One FASTag rule, a second tag for the same vehicle gets blacklisted.",
  },
  {
    title: "Selling the vehicle?",
    body: "Close or transfer the FASTag before you hand over the keys. It stays linked to the old number, so tolls keep coming out of your wallet until the account is deactivated and the transfer of ownership is filed.",
  },
];

export const FUN_FACTS = [
  {
    title: "BH means you never re-register",
    body: "A Bharat-series number moves states with you. No NOC, no re-registration, no chasing a road-tax refund. Road tax is paid every two years instead of fifteen years up front.",
  },
  {
    title: "The BH digits are a year, not an RTO",
    body: "In 22 BH 1234 A the leading 22 is the year of first registration. It is the one Indian format where the opening digits tell you when, not where.",
  },
  {
    title: "Who can get a BH number",
    body: "Central and state government staff, defence personnel, and employees of companies with offices in four or more states or UTs. It was built for people who get transferred.",
  },
  {
    title: "0001 is worth real money",
    body: "Fancy numbers are auctioned, not allotted. States earn hundreds of crores a year from them, and 0001 in a fresh series routinely goes for lakhs. 0786, 1111, 7777 and 9999 are the other perennial favourites.",
  },
  {
    title: "Series letters roll over",
    body: "Each series holds 10,000 numbers, 0001 to 9999. When an RTO exhausts single letters it moves to two (AA, AB), then three. A three-letter series is a sign of a very busy RTO.",
  },
  {
    title: "Some state codes have changed",
    body: "Odisha went from OR to OD in 2011, Uttarakhand from UA to UK in 2007, and Telangana from TS to TG in 2024. Old plates stay valid, which is why you still see all six on the road.",
  },
];

export const EXAMPLES = [
  { label: "MH 12 AB 1234", value: "MH 12 AB 1234", hint: "Pune" },
  { label: "DL 1C AA 0001", value: "DL 1C AA 0001", hint: "Delhi, fancy number" },
  { label: "KA 01 AB 1234", value: "KA 01 AB 1234", hint: "Bengaluru Central" },
  { label: "22 BH 1234 A", value: "22 BH 1234 A", hint: "Bharat series" },
  { label: "TN 09 BZ 5678", value: "TN 09 BZ 5678", hint: "Chennai East" },
  { label: "WB 06 AB 1234", value: "WB 06 AB 1234", hint: "Kolkata" },
  { label: "13 CD 0001", value: "13 CD 0001", hint: "Diplomatic" },
  { label: "GJ 05 ZZ 12345", value: "GJ 05 ZZ 12345", hint: "Invalid on purpose" },
];
