// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type AppRouteHandlerRoutes = "/api/admin/access-requests" | "/api/admin/access-requests/approve" | "/api/admin/access-requests/reject" | "/api/admin/audit/list" | "/api/admin/blogs/export" | "/api/admin/change-password" | "/api/admin/create" | "/api/admin/delete" | "/api/admin/google-login" | "/api/admin/list" | "/api/admin/me" | "/api/admin/request-access" | "/api/admin/superadmins" | "/api/admin/toggle-status" | "/api/admin/update" | "/api/analytics" | "/api/audit/log" | "/api/blogs/link-check" | "/api/blogs/revalidate" | "/api/blogs/runtime-qa" | "/api/firebase-messaging-sw" | "/api/health" | "/api/notifications/broadcast" | "/api/notifications/mark-read" | "/api/notifications/save-token" | "/api/notifications/scheduler" | "/api/notifications/test-push" | "/api/security/audit" | "/api/security/consent" | "/api/security/events" | "/api/security/login-event" | "/api/security/session/current" | "/api/security/session/end" | "/api/security/session/heartbeat" | "/api/security/session/location" | "/api/security/session/start" | "/api/security/sessions" | "/api/security/sessions/revoke" | "/api/security/settings" | "/api/seo/config" | "/api/seo/gsc" | "/api/seo/gsc/callback" | "/api/seo/gsc/connect" | "/api/seo/gsc/index-request" | "/api/seo/gsc/inspect" | "/api/seo/gsc/oauth" | "/api/seo/gsc/report" | "/api/seo/gsc/sitemaps" | "/api/seo/gsc/sync" | "/api/seo/health" | "/api/seo/links/check" | "/api/seo/recommendations" | "/api/seo/registry" | "/api/seo/search" | "/api/support/all" | "/api/support/auto-delete" | "/api/support/create" | "/api/support/my-tickets" | "/api/support/reopen" | "/api/support/reply" | "/api/support/update-status" | "/api/youtube/meta"
type PageRoutes = never
type LayoutRoutes = "/" | "/[project]"
type RedirectRoutes = "/admin/dashboard" | "/altftool/consumerrating/[[...path]]" | "/altftool/salelocator/[[...path]]" | "/altftool/trendingVideos/[[...path]]" | "/leadtree/creditcard/[[...path]]" | "/leadtree/expertvideos/[[...path]]"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[project]": { "project": string; }
  "/admin/dashboard": {}
  "/altftool/consumerrating/[[...path]]": { "path"?: string[]; }
  "/altftool/salelocator/[[...path]]": { "path"?: string[]; }
  "/altftool/trendingVideos/[[...path]]": { "path"?: string[]; }
  "/api/admin/access-requests": {}
  "/api/admin/access-requests/approve": {}
  "/api/admin/access-requests/reject": {}
  "/api/admin/audit/list": {}
  "/api/admin/blogs/export": {}
  "/api/admin/change-password": {}
  "/api/admin/create": {}
  "/api/admin/delete": {}
  "/api/admin/google-login": {}
  "/api/admin/list": {}
  "/api/admin/me": {}
  "/api/admin/request-access": {}
  "/api/admin/superadmins": {}
  "/api/admin/toggle-status": {}
  "/api/admin/update": {}
  "/api/analytics": {}
  "/api/audit/log": {}
  "/api/blogs/link-check": {}
  "/api/blogs/revalidate": {}
  "/api/blogs/runtime-qa": {}
  "/api/firebase-messaging-sw": {}
  "/api/health": {}
  "/api/notifications/broadcast": {}
  "/api/notifications/mark-read": {}
  "/api/notifications/save-token": {}
  "/api/notifications/scheduler": {}
  "/api/notifications/test-push": {}
  "/api/security/audit": {}
  "/api/security/consent": {}
  "/api/security/events": {}
  "/api/security/login-event": {}
  "/api/security/session/current": {}
  "/api/security/session/end": {}
  "/api/security/session/heartbeat": {}
  "/api/security/session/location": {}
  "/api/security/session/start": {}
  "/api/security/sessions": {}
  "/api/security/sessions/revoke": {}
  "/api/security/settings": {}
  "/api/seo/config": {}
  "/api/seo/gsc": {}
  "/api/seo/gsc/callback": {}
  "/api/seo/gsc/connect": {}
  "/api/seo/gsc/index-request": {}
  "/api/seo/gsc/inspect": {}
  "/api/seo/gsc/oauth": {}
  "/api/seo/gsc/report": {}
  "/api/seo/gsc/sitemaps": {}
  "/api/seo/gsc/sync": {}
  "/api/seo/health": {}
  "/api/seo/links/check": {}
  "/api/seo/recommendations": {}
  "/api/seo/registry": {}
  "/api/seo/search": {}
  "/api/support/all": {}
  "/api/support/auto-delete": {}
  "/api/support/create": {}
  "/api/support/my-tickets": {}
  "/api/support/reopen": {}
  "/api/support/reply": {}
  "/api/support/update-status": {}
  "/api/youtube/meta": {}
  "/leadtree/creditcard/[[...path]]": { "path"?: string[]; }
  "/leadtree/expertvideos/[[...path]]": { "path"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[project]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
