"use client";

// IPA -> candidate English words. Used by the IPA to Text Helper.
// Built from a focused common-word set; the reverse lookup returns multiple
// candidate words whose pronunciation matches the given IPA.

export const IPA_TO_WORDS = {
  ə: ["a"],
  ən: ["an"],
  ðə: ["the"],
  ənd: ["and"],
  ɔr: ["or"],
  bʌt: ["but"],
  ɪf: ["if"],
  tu: ["to", "two"],
  əv: ["of"],
  ɪn: ["in"],
  ɑn: ["on"],
  æt: ["at"],
  baɪ: ["by", "buy"],
  fɔr: ["for", "four"],
  wɪð: ["with"],
  ɪz: ["is"],
  ɑr: ["are", "our"],
  wʌz: ["was"],
  wɜr: ["were"],
  bi: ["be"],
  bɪn: ["been"],
  æm: ["am"],
  du: ["do"],
  dʌz: ["does"],
  dɪd: ["did"],
  hæv: ["have"],
  hæz: ["has"],
  hæd: ["had"],
  wɪl: ["will"],
  wʊd: ["would"],
  kæn: ["can"],
  kʊd: ["could"],
  ʃʊd: ["should"],
  meɪ: ["may"],
  maɪt: ["might"],
  mʌst: ["must"],
  ðɪs: ["this"],
  ðæt: ["that"],
  ðiz: ["these"],
  ðoʊz: ["those"],
  aɪ: ["I", "eye"],
  ju: ["you"],
  hi: ["he"],
  ʃi: ["she"],
  wi: ["we"],
  ðeɪ: ["they"],
  ɪt: ["it"],
  mi: ["me"],
  hɪm: ["him"],
  hɜr: ["her"],
  ʌs: ["us"],
  ðɛm: ["them"],
  maɪ: ["my"],
  jɔr: ["your"],
  hɪz: ["his"],
  aʊr: ["our"],
  ðɛr: ["their", "there"],
  nɑt: ["not"],
  noʊ: ["no", "know"],
  jɛs: ["yes"],
  soʊ: ["so"],
  vɛri: ["very"],
  dʒʌst: ["just"],
  naʊ: ["now"],
  ðɛn: ["then"],
  ðæn: ["than"],
  wɛn: ["when"],
  wɛr: ["where", "were"],
  wʌt: ["what"],
  hu: ["who"],
  haʊ: ["how"],
  waɪ: ["why"],
  wɪtʃ: ["which"],
  əbaʊt: ["about"],
  frʌm: ["from"],
  ɪntu: ["into"],
  oʊvər: ["over"],
  æftər: ["after"],
  bɪfɔr: ["before"],
  bɪkɔz: ["because"],
  ɔlsoʊ: ["also"],
  hɪr: ["here"],
  aʊt: ["out"],
  ʌp: ["up"],
  daʊn: ["down"],
  ɔf: ["off"],
  æz: ["as"],
  ɔl: ["all"],
  ɛni: ["any"],
  itʃ: ["each"],
  mɔr: ["more"],
  moʊst: ["most"],
  sʌm: ["some"],
  sʌtʃ: ["such"],
  oʊnli: ["only"],
  oʊn: ["own"],
  seɪm: ["same"],
  ʌðər: ["other"],
  nju: ["new"],
  oʊld: ["old"],
  gʊd: ["good"],
  bæd: ["bad"],
  bɪg: ["big"],
  smɔl: ["small"],
  lɪtəl: ["little"],
  greɪt: ["great"],
  lɑrdʒ: ["large"],
  haɪ: ["high"],
  loʊ: ["low"],
  lɔŋ: ["long"],
  ʃɔrt: ["short"],
  raɪt: ["right", "write"],
  lɛft: ["left"],
  fɜrst: ["first"],
  læst: ["last"],
  taɪm: ["time"],
  deɪ: ["day"],
  jɪr: ["year"],
  wɜrk: ["work"],
  wɜrld: ["world"],
  laɪf: ["life"],
  pipəl: ["people"],
  mæn: ["man"],
  wʊmən: ["woman"],
  tʃaɪld: ["child"],
  tʃɪldrən: ["children"],
  haʊs: ["house"],
  hoʊm: ["home"],
  wɔtər: ["water"],
  fud: ["food"],
  lʌv: ["love"],
  mʌni: ["money"],
  skul: ["school"],
  studənt: ["student"],
  titʃər: ["teacher"],
  bʊk: ["book"],
  wɜrd: ["word"],
  læŋgwɪdʒ: ["language"],
  ɪŋglɪʃ: ["english"],
  nʌmbər: ["number"],
  kəmpjutər: ["computer"],
  foʊn: ["phone"],
  mjuzɪk: ["music"],
  hæpi: ["happy"],
  hɛloʊ: ["hello"],
  pliz: ["please"],
  θæŋks: ["thanks"],
  θæŋk: ["thank"],
  wɛlkəm: ["welcome"],
  frɛnd: ["friend"],
  fæməli: ["family"],
  kʌlər: ["color", "colour"],
  sɪti: ["city"],
  kʌntri: ["country"],
  neɪm: ["name"],
  hɛlp: ["help"],
  lɜrn: ["learn"],
  rid: ["read"],
  spiːk: ["speak"],
  lɪsən: ["listen"],
  pleɪ: ["play"],
  rʌn: ["run"],
  wɔk: ["walk"],
  it: ["eat"],
  drɪŋk: ["drink"],
  slip: ["sleep"],
  θɪŋk: ["think"],
  fil: ["feel"],
  si: ["see"],
  lʊk: ["look"],
  goʊ: ["go"],
  kʌm: ["come"],
  gɛt: ["get"],
  meɪk: ["make"],
  faɪnd: ["find"],
  juz: ["use"],
  gɪv: ["give"],
  teɪk: ["take"],
  kip: ["keep"],
  pʊt: ["put"],
  seɪ: ["say"],
  tɛl: ["tell"],
  æsk: ["ask"],
  wɑnt: ["want"],
  nid: ["need"],
  laɪk: ["like"],
  kɔl: ["call"],
  tɜrn: ["turn"],
  muv: ["move"],
  lɪv: ["live"],
  bɪliv: ["believe"],
  tʃeɪndʒ: ["change"],
  maɪnd: ["mind"],
  hænd: ["hand"],
  feɪs: ["face"],
  hɛd: ["head"],
  hɑrt: ["heart"],
  saʊnd: ["sound"],
  laɪt: ["light"],
  naɪt: ["night"],
  mɔrnɪŋ: ["morning"],
  ivnɪŋ: ["evening"],
  tədeɪ: ["today"],
  təmɑroʊ: ["tomorrow"],
  jɛstərdeɪ: ["yesterday"],
  kæt: ["cat"],
  dɔg: ["dog"],
  bɜrd: ["bird"],
  fɪʃ: ["fish"],
  tri: ["tree"],
  flaʊər: ["flower"],
  sʌn: ["sun", "son"],
  mun: ["moon"],
  stɑr: ["star"],
  reɪn: ["rain"],
  snoʊ: ["snow"],
  wɪnd: ["wind"],
  faɪr: ["fire"],
  ɜrθ: ["earth"],
  kɑr: ["car"],
  bʌs: ["bus"],
  treɪn: ["train"],
  roʊd: ["road"],
  strit: ["street"],
  dɔr: ["door"],
  wɪndoʊ: ["window"],
  teɪbəl: ["table"],
  tʃɛr: ["chair"],
  bɛd: ["bed"],
  rɛd: ["red"],
  blu: ["blue"],
  grin: ["green"],
  blæk: ["black"],
  waɪt: ["white"],
  wʌn: ["one"],
  θri: ["three"],
  faɪv: ["five"],
  sɪks: ["six"],
  sɛvən: ["seven"],
  eɪt: ["eight"],
  naɪn: ["nine"],
  tɛn: ["ten"],
  hʌndrəd: ["hundred"],
  θaʊzənd: ["thousand"],
  mɪljən: ["million"],
  bjutəfəl: ["beautiful"],
  ɪmpɔrtənt: ["important"],
  dɪfrənt: ["different"],
  əveɪləbəl: ["available"],
  pɑsəbəl: ["possible"],
  prɑbləm: ["problem"],
  kwɛstʃən: ["question"],
  ænsər: ["answer"],
  ɪgzæmpəl: ["example"],
  sɪstəm: ["system"],
  pɑrt: ["part"],
  grum: ["groom"],
  grups: ["groups"],
  fækt: ["fact"],
  stɔri: ["story"],
  aɪdiə: ["idea"],
  praɪs: ["price"],
  bɪznəs: ["business"],
  gʌvərnmənt: ["government"],
  prɛzɪdənt: ["president"],
  kʌmpəni: ["company"],
  sɜrvɪs: ["service"],
  mɑrkɪt: ["market"],
  prɑdʌkt: ["product"],
  hɛlθ: ["health"],
  paʊər: ["power"],
  neɪtʃər: ["nature"],
  saɪəns: ["science"],
  hɪstəri: ["history"],
  ænəməl: ["animal"],
  plænt: ["plant"],
  bɑdi: ["body"],
  geɪm: ["game"],
  spɔrt: ["sport"],
  ɑrt: ["art"],
  sɔŋ: ["song"],
  fɪlm: ["film"],
  pɪktʃər: ["picture"],
  lɛtər: ["letter"],
  sɛntəns: ["sentence"],
  peɪdʒ: ["page"],
  laɪn: ["line"],
  weɪ: ["way"],
  θɪŋ: ["thing"],
  pleɪs: ["place"],
  pɔɪnt: ["point"],
  saɪd: ["side"],
  ɛnd: ["end"],
  kaɪnd: ["kind"],
  taɪp: ["type"],
  fɔrm: ["form"],
  keɪs: ["case"],
  lɛvəl: ["level"],
  mɑdəl: ["model"],
  sɔrs: ["source"],
  steɪt: ["state"],
  fild: ["field"],
  rɪleɪʃən: ["relation"],
  wɪmən: ["women"],
  mɛn: ["men"],
  bɔɪ: ["boy"],
  gɜrl: ["girl"],
  beɪbi: ["baby"],
  dɑktər: ["doctor"],
  mʌðər: ["mother"],
  fɑðər: ["father"],
  brʌðər: ["brother"],
  sɪstər: ["sister"],
  dɔtər: ["daughter"],
  kɪŋ: ["king"],
  kwin: ["queen"],
  lidər: ["leader"],
  wɜrkər: ["worker"],
  ɛnəmi: ["enemy"],
  neɪʃən: ["nation"],
  gɑd: ["god"],
  tʃɜrtʃ: ["church"],
  wɔr: ["war"],
  pis: ["peace"],
  lɔ: ["law"],
  rul: ["rule"],
  kɔrt: ["court"],
  pəlis: ["police"],
  prɪzən: ["prison"],
  klæs: ["class"],
  kɔrs: ["course"],
  tɛst: ["test"],
  ɪgzæm: ["exam"],
  greɪd: ["grade"],
  stʌdi: ["study"],
  risɜrtʃ: ["research"],
  θɪri: ["theory"],
  mɛθəd: ["method"],
  rɪzʌlt: ["result"],
  ɪfɛkt: ["effect"],
  kɔz: ["cause"],
  rizn: ["reason"],
  pɜrpəs: ["purpose"],
  goʊl: ["goal"],
  plæn: ["plan"],
  dɪzaɪn: ["design"],
  bɪld: ["build"],
  krieɪt: ["create"],
  stɑrt: ["start"],
  stɑp: ["stop"],
  fɪnɪʃ: ["finish"],
  oʊpən: ["open"],
  kloʊz: ["close"],
  ʃoʊ: ["show"],
  haɪd: ["hide"],
  breɪk: ["break"],
  kʌt: ["cut"],
  dʒɔɪn: ["join"],
  mit: ["meet"],
  wɪn: ["win"],
  luz: ["lose"],
  peɪ: ["pay"],
  baɪ: ["buy"],
  sɛl: ["sell"],
  seɪv: ["save"],
  spɛnd: ["spend"],
  kɔst: ["cost"],
  vælju: ["value"],
  ril: ["real"],
  tru: ["true"],
  fɔls: ["false"],
  fri: ["free"],
  fʊl: ["full"],
  ɛmpti: ["empty"],
  strɔŋ: ["strong"],
  wik: ["weak"],
  hɑrd: ["hard"],
  sɔft: ["soft"],
  fæst: ["fast"],
  sloʊ: ["slow"],
  ɜrli: ["early"],
  leɪt: ["late"],
  nɪr: ["near"],
  fɑr: ["far"],
  kwaɪət: ["quiet"],
  laʊd: ["loud"],
  klin: ["clean"],
  dɜrti: ["dirty"],
  hɑt: ["hot"],
  koʊld: ["cold"],
  wɔrm: ["warm"],
  kul: ["cool"],
  dɑrk: ["dark"],
  braɪt: ["bright"],
  hɛvi: ["heavy"],
  diːp: ["deep"],
  ʃæloʊ: ["shallow"],
  jʌŋ: ["young"],
  ədʌlt: ["adult"],
  dɛd: ["dead"],
  əlaɪv: ["alive"],
  sɪk: ["sick"],
  wɛl: ["well"],
  rɪtʃ: ["rich"],
  pʊr: ["poor"],
  seɪf: ["safe"],
  deɪndʒər: ["danger"],
  izi: ["easy"],
  dɪfɪkəlt: ["difficult"],
  sɪmpəl: ["simple"],
  kɑmplɛks: ["complex"],
  klɪr: ["clear"],
  kɑmən: ["common"],
  spɛʃəl: ["special"],
  pʌblɪk: ["public"],
  praɪvɪt: ["private"],
  soʊʃəl: ["social"],
  nætʃərəl: ["natural"],
  hjumən: ["human"],
  pɜrsənəl: ["personal"],
  pɑzətɪv: ["positive"],
  nɛgətɪv: ["negative"],
  toʊtəl: ["total"],
  dʒɛnərəl: ["general"],
  mɑdərn: ["modern"],
  loʊkəl: ["local"],
  næʃənəl: ["national"],
  ɪntərnæʃənəl: ["international"],
  gloʊbəl: ["global"],
  mɛn: ["men"],
};

// Valid IPA symbol set for validation (basic English-oriented set).
export const VALID_IPA_SYMBOLS = new Set([
  "ə", "ɪ", "ʊ", "ʌ", "ɔ", "æ", "ɛ", "ɑ", "ɜ", "i", "u", "e", "o", "a",
  "p", "b", "t", "d", "k", "g", "f", "v", "θ", "ð", "s", "z", "ʃ", "ʒ",
  "tʃ", "dʒ", "m", "n", "ŋ", "l", "r", "w", "j", "h",
  "ˈ", "ˌ", "ː", ".", "̃", "̯",
]);

export function isLikelyIpa(input) {
  const clean = input.replace(/[\s/[\]()]/g, "");
  if (!clean) return false;
  // At least 40% of characters should be valid IPA symbols to be "likely IPA".
  let valid = 0;
  let i = 0;
  while (i < clean.length) {
    // Check two-char symbols first.
    if (i + 1 < clean.length && VALID_IPA_SYMBOLS.has(clean.slice(i, i + 2))) {
      valid += 2;
      i += 2;
    } else if (VALID_IPA_SYMBOLS.has(clean[i])) {
      valid += 1;
      i += 1;
    } else {
      i += 1;
    }
  }
  return valid / clean.length >= 0.4;
}

export function ipaToWords(ipa) {
  const clean = ipa.replace(/[\s/[\]()]/g, "");
  if (!clean) return { words: [], found: false };
  const candidates = IPA_TO_WORDS[clean];
  if (candidates && candidates.length) {
    return { words: candidates, found: true };
  }
  return { words: [], found: false };
}
