"use client";

export const AREAS = [
  { id: "neck", label: "Neck" },
  { id: "shoulders", label: "Shoulders" },
  { id: "upper-back", label: "Upper back" },
  { id: "lower-back", label: "Lower back" },
  { id: "wrists", label: "Wrists" },
  { id: "hips", label: "Hips" },
  { id: "legs", label: "Legs" },
  { id: "eyes", label: "Eyes" },
];

export const EQUIPMENT = [
  { id: "chair", label: "Chair" },
  { id: "desk", label: "Desk" },
  { id: "wall", label: "Wall" },
];

export const STRETCHES = [
  {
    id: "neck-side-bend",
    name: "Neck Side Bend",
    area: "neck",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 2,
    steps: [
      "Sit tall, shoulders down and relaxed.",
      "Tip one ear toward the shoulder on that side.",
      "Let the opposite shoulder sink away to deepen it.",
    ],
  },
  {
    id: "chin-tuck",
    name: "Chin Tuck",
    area: "neck",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 1,
    steps: [
      "Look straight ahead and keep your gaze level.",
      "Glide your chin straight back, making a double chin.",
      "Hold, then release slowly. Repeat the glide throughout the hold.",
    ],
  },
  {
    id: "levator-scap",
    name: "Look-to-Armpit Stretch",
    area: "neck",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 2,
    steps: [
      "Turn your head about 45 degrees to one side.",
      "Drop your gaze down toward that armpit.",
      "Rest the same-side hand on the back of your head for light weight only.",
    ],
    caution: "Let the hand rest, never pull. This one goes wrong when people yank.",
  },
  {
    id: "upper-trap-anchor",
    name: "Anchored Upper Trap Stretch",
    area: "neck",
    equipment: "chair",
    difficulty: "gentle",
    hold: 25,
    sides: 2,
    steps: [
      "Grip the edge of the seat with one hand to anchor that shoulder down.",
      "Tip the opposite ear toward the free shoulder.",
      "Keep your nose pointing forward the whole time.",
    ],
  },
  {
    id: "neck-rotation",
    name: "Neck Rotation Hold",
    area: "neck",
    equipment: "none",
    difficulty: "gentle",
    hold: 15,
    sides: 2,
    steps: [
      "Sit tall with your chin level.",
      "Turn your head slowly to look over one shoulder.",
      "Stop at mild tension and breathe into the hold.",
    ],
  },
  {
    id: "neck-extension",
    name: "Gentle Neck Extension",
    area: "neck",
    equipment: "none",
    difficulty: "moderate",
    hold: 15,
    sides: 1,
    steps: [
      "Support the back of your neck with both hands.",
      "Lift your chest and look up and slightly back.",
      "Go only as far as feels open, then return slowly.",
    ],
    caution: "Skip this if you get dizzy looking up, or have known neck disc issues.",
  },
  {
    id: "cross-body-shoulder",
    name: "Cross-Body Shoulder Stretch",
    area: "shoulders",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 2,
    steps: [
      "Bring one arm straight across your chest.",
      "Hook the other forearm under it and draw it closer.",
      "Keep the stretching shoulder pressed down, not shrugged.",
    ],
  },
  {
    id: "shoulder-rolls",
    name: "Slow Shoulder Rolls",
    area: "shoulders",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 1,
    steps: [
      "Roll both shoulders up toward your ears.",
      "Draw them back, squeeze, then let them drop.",
      "Make the circles as large and slow as you can.",
    ],
  },
  {
    id: "wall-chest-opener",
    name: "Wall Chest Opener",
    area: "shoulders",
    equipment: "wall",
    difficulty: "moderate",
    hold: 25,
    sides: 2,
    steps: [
      "Place one forearm flat on a wall or door frame, elbow at shoulder height.",
      "Step the same-side foot forward and turn your chest away.",
      "Stop as soon as you feel a broad stretch across the chest.",
    ],
    caution: "Ease off if you feel pinching at the front of the shoulder joint.",
  },
  {
    id: "overhead-triceps",
    name: "Overhead Triceps Stretch",
    area: "shoulders",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 2,
    steps: [
      "Reach one arm overhead, then bend the elbow to touch your upper back.",
      "Use the other hand to guide the elbow gently back.",
      "Keep your ribs down so you do not arch your lower back.",
    ],
  },
  {
    id: "scap-squeeze",
    name: "Shoulder Blade Squeeze",
    area: "shoulders",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 1,
    steps: [
      "Bend both elbows to 90 degrees at your sides.",
      "Draw the shoulder blades together and slightly down.",
      "Hold the squeeze without letting the shoulders creep up.",
    ],
  },
  {
    id: "behind-back-clasp",
    name: "Behind-Back Clasp",
    area: "shoulders",
    equipment: "none",
    difficulty: "moderate",
    hold: 20,
    sides: 1,
    steps: [
      "Clasp your hands behind your back, arms straight.",
      "Lift the hands away from your body and open the chest.",
      "If you cannot clasp, hold opposite wrists or a rolled towel.",
    ],
    caution: "Keep it low and wide. Sharp shoulder pain means stop.",
  },
  {
    id: "seated-thoracic-ext",
    name: "Chair-Back Thoracic Extension",
    area: "upper-back",
    equipment: "chair",
    difficulty: "moderate",
    hold: 20,
    sides: 1,
    steps: [
      "Sit back so the chair edge meets your mid-back.",
      "Support your head with both hands, elbows forward.",
      "Drape your upper back over the chair edge and breathe wide.",
    ],
    caution: "Only over a firm chair back below the shoulder blades. Never over the neck.",
  },
  {
    id: "seated-cat-cow",
    name: "Seated Cat-Cow",
    area: "upper-back",
    equipment: "chair",
    difficulty: "gentle",
    hold: 30,
    sides: 1,
    steps: [
      "Rest your hands on your knees, feet flat.",
      "Inhale: lift the chest, roll shoulders back, look up slightly.",
      "Exhale: round the spine, tuck the chin, push the mid-back backward.",
      "Keep flowing slowly with your breath for the whole hold.",
    ],
  },
  {
    id: "seated-thread-needle",
    name: "Seated Thread the Needle",
    area: "upper-back",
    equipment: "chair",
    difficulty: "moderate",
    hold: 20,
    sides: 2,
    steps: [
      "Sit tall and reach one arm up toward the ceiling.",
      "Thread it down and across underneath the opposite arm.",
      "Let the shoulder blade spread as you rotate the upper back.",
    ],
  },
  {
    id: "wall-angels",
    name: "Wall Angels",
    area: "upper-back",
    equipment: "wall",
    difficulty: "moderate",
    hold: 30,
    sides: 1,
    steps: [
      "Stand with your back, head and hips lightly touching a wall.",
      "Put the backs of your hands on the wall at shoulder height.",
      "Slide the arms up and down slowly, keeping contact where you can.",
    ],
    caution: "If your hands lift off the wall, shorten the range rather than forcing it.",
  },
  {
    id: "upper-back-round",
    name: "Standing Upper Back Round",
    area: "upper-back",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 1,
    steps: [
      "Wrap your arms around yourself as if hugging your shoulders.",
      "Round the upper back and push it toward the wall behind you.",
      "Let your head drop and breathe into the space between the shoulder blades.",
    ],
  },
  {
    id: "overhead-reach",
    name: "Overhead Reach and Lengthen",
    area: "upper-back",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 1,
    steps: [
      "Interlace your fingers and turn the palms toward the ceiling.",
      "Press upward and lift tall through the ribs.",
      "Keep the shoulders away from your ears and breathe wide.",
    ],
  },
  {
    id: "standing-thoracic-rotation",
    name: "Standing Thoracic Rotation",
    area: "upper-back",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 2,
    steps: [
      "Stand with both feet planted and cross your arms over your chest.",
      "Turn your shoulders to one side, keeping the hips facing forward.",
      "Move slowly and let the rotation come from the mid-back.",
    ],
  },
  {
    id: "seated-twist",
    name: "Seated Spinal Twist",
    area: "lower-back",
    equipment: "chair",
    difficulty: "moderate",
    hold: 20,
    sides: 2,
    steps: [
      "Sit tall with both feet planted and knees facing forward.",
      "Turn your torso to one side, hand on the chair back for light leverage.",
      "Lengthen up on the inhale, twist a touch further on the exhale.",
    ],
    caution: "Twist from the ribs, not by cranking on the chair.",
  },
  {
    id: "seated-forward-fold",
    name: "Seated Forward Fold",
    area: "lower-back",
    equipment: "chair",
    difficulty: "moderate",
    hold: 25,
    sides: 1,
    steps: [
      "Sit near the edge with feet wide and flat.",
      "Hinge forward and let your torso and arms hang between your knees.",
      "Let the head be heavy and release the low back.",
    ],
    caution: "Come up slowly, rolling up one vertebra at a time, to avoid a head rush.",
  },
  {
    id: "standing-back-ext",
    name: "Standing Back Extension",
    area: "lower-back",
    equipment: "none",
    difficulty: "moderate",
    hold: 15,
    sides: 1,
    steps: [
      "Stand with feet hip-width and hands on your lower back.",
      "Press your hips gently forward and lean back a small amount.",
      "Keep the movement short and controlled, chin tucked.",
    ],
    caution: "Small range only. Any pain shooting into the legs means stop immediately.",
  },
  {
    id: "standing-side-bend",
    name: "Standing Side Bend",
    area: "lower-back",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 2,
    steps: [
      "Stand tall and reach one arm overhead.",
      "Bend sideways toward the opposite side, keeping both feet planted.",
      "Reach long through the top hand rather than collapsing down.",
    ],
  },
  {
    id: "seated-pelvic-tilt",
    name: "Seated Pelvic Tilts",
    area: "lower-back",
    equipment: "chair",
    difficulty: "gentle",
    hold: 30,
    sides: 1,
    steps: [
      "Sit with feet flat and hands resting on your thighs.",
      "Roll your pelvis forward to arch the low back slightly.",
      "Then roll it back to flatten and tuck. Keep alternating slowly.",
    ],
  },
  {
    id: "standing-pelvic-tilt",
    name: "Standing Pelvic Tilt",
    area: "lower-back",
    equipment: "none",
    difficulty: "gentle",
    hold: 25,
    sides: 1,
    steps: [
      "Stand with knees slightly bent and hands on your hips.",
      "Tuck the tailbone under to flatten the low back.",
      "Release to a small arch, then keep rocking slowly between the two.",
    ],
  },
  {
    id: "standing-gentle-twist",
    name: "Standing Gentle Twist",
    area: "lower-back",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 2,
    steps: [
      "Stand with feet hip-width and let your arms hang loose.",
      "Rotate your torso to one side and let the arms swing with you.",
      "Keep it slow and relaxed rather than forcing the end range.",
    ],
  },
  {
    id: "wrist-flexor",
    name: "Wrist Flexor Stretch",
    area: "wrists",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 2,
    steps: [
      "Extend one arm forward, palm facing up.",
      "With the other hand, draw the fingers down and back.",
      "Keep the elbow straight to reach the forearm.",
    ],
  },
  {
    id: "wrist-extensor",
    name: "Wrist Extensor Stretch",
    area: "wrists",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 2,
    steps: [
      "Extend one arm forward, palm facing down.",
      "Let the wrist drop and gently draw the back of the hand toward you.",
      "This is the one that helps mouse-hand ache.",
    ],
  },
  {
    id: "prayer-stretch",
    name: "Prayer Stretch",
    area: "wrists",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 1,
    steps: [
      "Press your palms together in front of your chest.",
      "Keeping the palms touching, lower the hands toward your waist.",
      "Stop when you feel a stretch through both inner forearms.",
    ],
  },
  {
    id: "wrist-circles",
    name: "Wrist Circles",
    area: "wrists",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 1,
    steps: [
      "Make loose fists and hold your forearms still.",
      "Circle both wrists slowly in one direction.",
      "Halfway through the hold, reverse the direction.",
    ],
  },
  {
    id: "finger-fan",
    name: "Finger Fan and Fist",
    area: "wrists",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 1,
    steps: [
      "Spread all ten fingers as wide as they will go.",
      "Hold the spread for a beat, then curl into a soft fist.",
      "Keep alternating slowly and deliberately.",
    ],
  },
  {
    id: "desk-wrist-extension",
    name: "Desk Wrist Extension",
    area: "wrists",
    equipment: "desk",
    difficulty: "moderate",
    hold: 20,
    sides: 1,
    steps: [
      "Place both palms flat on the desk with fingers pointing back toward you.",
      "Keep the palms down and lean back a little at the hips.",
      "Start with fingers sideways if pointing back is too much.",
    ],
    caution: "Back off at once if you feel tingling or numbness in the fingers.",
  },
  {
    id: "seated-figure-4",
    name: "Seated Figure-4",
    area: "hips",
    equipment: "chair",
    difficulty: "moderate",
    hold: 25,
    sides: 2,
    steps: [
      "Cross one ankle over the opposite knee, letting the knee open out.",
      "Sit tall, then hinge forward from the hips with a flat back.",
      "You should feel this deep in the outer hip and glute.",
    ],
    caution: "Hinge from the hips. Rounding the back turns this into a low-back strain.",
  },
  {
    id: "standing-hip-flexor",
    name: "Standing Hip Flexor Lunge",
    area: "hips",
    equipment: "none",
    difficulty: "moderate",
    hold: 25,
    sides: 2,
    steps: [
      "Step one foot well back into a split stance.",
      "Tuck your tailbone under and squeeze the back glute.",
      "Sink forward slightly until the front of the back hip opens.",
    ],
  },
  {
    id: "chair-hip-flexor",
    name: "Chair-Assisted Hip Flexor",
    area: "hips",
    equipment: "chair",
    difficulty: "moderate",
    hold: 25,
    sides: 2,
    steps: [
      "Sit sideways on the chair so one leg can drop off the back edge.",
      "Let that thigh hang down and back behind your hip line.",
      "Tuck the tailbone under to find the stretch at the front of the hip.",
    ],
    caution: "Only on a stable, non-rolling chair. Lock the castors or use a fixed seat.",
  },
  {
    id: "seated-butterfly",
    name: "Seated Butterfly",
    area: "hips",
    equipment: "chair",
    difficulty: "gentle",
    hold: 25,
    sides: 1,
    steps: [
      "Sit near the edge and open both knees wide, heels drawn in.",
      "Rest your hands on your inner thighs.",
      "Sit tall and let gravity widen the knees on each exhale.",
    ],
  },
  {
    id: "standing-knee-hug",
    name: "Supported Knee Hug",
    area: "hips",
    equipment: "wall",
    difficulty: "gentle",
    hold: 20,
    sides: 2,
    steps: [
      "Stand with one hand on a wall for balance.",
      "Draw one knee up toward your chest and hold the shin.",
      "Stand tall rather than curling around the knee.",
    ],
  },
  {
    id: "hip-circles",
    name: "Standing Hip Circles",
    area: "hips",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 1,
    steps: [
      "Stand with feet hip-width and hands on your hips.",
      "Circle the hips slowly as if stirring a large pot.",
      "Reverse direction halfway through the hold.",
    ],
  },
  {
    id: "standing-hip-shift",
    name: "Standing Hip Shift",
    area: "hips",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 1,
    steps: [
      "Stand with feet a little wider than your hips.",
      "Shift your weight slowly over one hip, then the other.",
      "Keep the shoulders level and let the hips do the moving.",
    ],
  },
  {
    id: "standing-glute-squeeze",
    name: "Standing Glute Squeeze",
    area: "hips",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 1,
    steps: [
      "Stand tall with feet hip-width and knees soft.",
      "Squeeze both glutes and tuck the tailbone slightly under.",
      "Hold, then release. Long sitting switches these muscles off.",
    ],
  },
  {
    id: "marching-in-place",
    name: "Marching in Place",
    area: "legs",
    equipment: "none",
    difficulty: "gentle",
    hold: 25,
    sides: 1,
    steps: [
      "Stand tall with your arms relaxed at your sides.",
      "Lift one knee toward hip height, lower it, then swap.",
      "Keep a slow, even rhythm and let the ankles work.",
    ],
  },
  {
    id: "leg-swings",
    name: "Gentle Leg Swings",
    area: "legs",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 2,
    steps: [
      "Shift your weight onto one leg and stand tall.",
      "Swing the free leg forward and back like a loose pendulum.",
      "Stay relaxed and keep the swing small to start.",
    ],
  },
  {
    id: "standing-calf-pump",
    name: "Standing Calf Pump",
    area: "legs",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 1,
    steps: [
      "Stand with feet hip-width apart.",
      "Rise slowly onto the balls of both feet.",
      "Lower under control until the heels rest, then repeat.",
    ],
  },
  {
    id: "standing-hamstring",
    name: "Standing Hamstring Hinge",
    area: "legs",
    equipment: "none",
    difficulty: "moderate",
    hold: 25,
    sides: 2,
    steps: [
      "Step one heel forward and flex that foot, toes up.",
      "Keep the front leg long and hinge back over the rear hip.",
      "Chest stays lifted so the stretch stays in the hamstring.",
    ],
  },
  {
    id: "seated-hamstring",
    name: "Seated Hamstring Extension",
    area: "legs",
    equipment: "chair",
    difficulty: "gentle",
    hold: 20,
    sides: 2,
    steps: [
      "Sit near the edge and straighten one leg out, heel on the floor.",
      "Flex the toes toward you and sit tall.",
      "Hinge forward from the hips until the back of the thigh wakes up.",
    ],
  },
  {
    id: "wall-calf",
    name: "Wall Calf Stretch",
    area: "legs",
    equipment: "wall",
    difficulty: "moderate",
    hold: 25,
    sides: 2,
    steps: [
      "Place both hands on the wall and step one foot back.",
      "Keep the back heel down and that leg straight.",
      "Bend the front knee to press the back heel toward the floor.",
    ],
  },
  {
    id: "standing-quad",
    name: "Standing Quad Stretch",
    area: "legs",
    equipment: "wall",
    difficulty: "moderate",
    hold: 25,
    sides: 2,
    steps: [
      "Hold a wall for balance and bend one knee behind you.",
      "Catch the ankle and draw the heel toward your glute.",
      "Keep the knees side by side and the tailbone tucked.",
    ],
    caution: "Skip or use a strap if your knee complains when it bends fully.",
  },
  {
    id: "ankle-circles",
    name: "Seated Ankle Circles",
    area: "legs",
    equipment: "chair",
    difficulty: "gentle",
    hold: 20,
    sides: 2,
    steps: [
      "Lift one foot slightly off the floor.",
      "Draw slow circles with the toes, moving only the ankle.",
      "Reverse direction halfway through the hold.",
    ],
  },
  {
    id: "desk-calf-raise",
    name: "Desk Calf Raise Hold",
    area: "legs",
    equipment: "desk",
    difficulty: "gentle",
    hold: 20,
    sides: 1,
    steps: [
      "Rest your fingertips on the desk for balance.",
      "Rise onto the balls of both feet and hold at the top.",
      "Lower slowly, letting the heels drop past level if you can.",
    ],
  },
  {
    id: "eye-20-20-20",
    name: "20-20-20 Distance Gaze",
    area: "eyes",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 1,
    steps: [
      "Look away from every screen to something at least 20 feet away.",
      "A window works best. A far wall will do.",
      "Let your eyes rest there softly without straining to focus.",
    ],
  },
  {
    id: "eye-palming",
    name: "Palming",
    area: "eyes",
    equipment: "none",
    difficulty: "gentle",
    hold: 30,
    sides: 1,
    steps: [
      "Rub your palms together until they feel warm.",
      "Cup them over your closed eyes without pressing on the eyeballs.",
      "Rest in the darkness and let your jaw and brow soften.",
    ],
  },
  {
    id: "eye-figure-8",
    name: "Eye Figure-8",
    area: "eyes",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 1,
    steps: [
      "Imagine a large figure-8 lying on its side about 10 feet away.",
      "Trace it slowly with your eyes, keeping your head still.",
      "Reverse the direction halfway through.",
    ],
  },
  {
    id: "eye-focus-shift",
    name: "Near-Far Focus Shift",
    area: "eyes",
    equipment: "none",
    difficulty: "gentle",
    hold: 20,
    sides: 1,
    steps: [
      "Hold a thumb up about 25 cm from your face and focus on it.",
      "Shift your focus to something far across the room.",
      "Alternate near and far every few seconds, letting focus fully settle.",
    ],
  },
  {
    id: "eye-blink-break",
    name: "Deliberate Blink Break",
    area: "eyes",
    equipment: "none",
    difficulty: "gentle",
    hold: 15,
    sides: 1,
    steps: [
      "Close your eyes softly, pause, then squeeze gently for a beat.",
      "Open and blink rapidly a few times.",
      "Screen work halves your blink rate, so this resets the tear film.",
    ],
  },
];
