export const UNIVERSAL_UNITS = [
  { id: "sqft", name: "Square Feet", short: "sq ft", sqft: 1, basis: "Base unit of this converter" },
  { id: "sqyd", name: "Square Yard (Gaj)", short: "gaj", sqft: 9, basis: "1 gaj = 3 ft x 3 ft = 9 sq ft" },
  { id: "sqm", name: "Square Metre", short: "sq m", sqft: 10.7639104167, basis: "1 sq m = 10.7639 sq ft" },
  { id: "acre", name: "Acre", short: "acre", sqft: 43560, basis: "1 acre = 4,840 gaj = 43,560 sq ft" },
  { id: "hectare", name: "Hectare", short: "ha", sqft: 107639.104167, basis: "1 hectare = 10,000 sq m = 2.471 acre" },
];

export const STATES = [
  {
    id: "up",
    name: "Uttar Pradesh",
    zone: "North India",
    note: "Revenue records run bigha - biswa - biswansi. The UP bigha is one of the largest in the country.",
    units: [
      { id: "bigha", family: "bigha", name: "Bigha", sqft: 27000, basis: "UP standard: 1 bigha = 20 biswa = 27,000 sq ft (0.62 acre)" },
      { id: "biswa", family: "biswa", name: "Biswa", sqft: 1350, basis: "1 bigha = 20 biswa, so 1 biswa = 1,350 sq ft" },
      { id: "biswansi", family: "biswansi", name: "Biswansi", sqft: 67.5, basis: "1 biswa = 20 biswansi = 67.5 sq ft" },
      { id: "katha", family: "katha", name: "Katha", sqft: 1350, basis: "Eastern UP: 1 bigha = 20 katha = 1,350 sq ft (same size as a UP biswa)" },
    ],
  },
  {
    id: "bihar",
    name: "Bihar",
    zone: "East India",
    note: "The bigha - katha - dhur chain. A Bihar katha is nearly double a Bengal katha, so never assume.",
    units: [
      { id: "bigha", family: "bigha", name: "Bigha", sqft: 27220, basis: "1 bigha = 20 katha = 27,220 sq ft (0.625 acre)" },
      { id: "katha", family: "katha", name: "Katha", sqft: 1361, basis: "1 katha = 20 dhur = 1,361 sq ft" },
      { id: "dhur", family: "dhur", name: "Dhur", sqft: 68.05, basis: "1 katha = 20 dhur = 68.05 sq ft" },
      { id: "dhurki", family: "dhurki", name: "Dhurki", sqft: 3.4025, basis: "1 dhur = 20 dhurki = 3.4025 sq ft" },
      { id: "decimal", family: "decimal", name: "Decimal (Dismil)", sqft: 435.6, basis: "1 acre = 100 decimal = 435.6 sq ft" },
    ],
  },
  {
    id: "wb",
    name: "West Bengal",
    zone: "East India",
    note: "Kolkata property is quoted in katha (cottah). One WB bigha is barely half a UP bigha.",
    units: [
      { id: "bigha", family: "bigha", name: "Bigha", sqft: 14400, basis: "1 bigha = 20 katha = 14,400 sq ft (0.33 acre)" },
      { id: "katha", family: "katha", name: "Katha (Cottah)", sqft: 720, basis: "1 katha = 16 chatak = 720 sq ft = 80 gaj" },
      { id: "chatak", family: "chatak", name: "Chatak", sqft: 45, basis: "1 katha = 16 chatak = 45 sq ft" },
      { id: "decimal", family: "decimal", name: "Decimal (Dismil)", sqft: 435.6, basis: "1 acre = 100 decimal = 435.6 sq ft" },
    ],
  },
  {
    id: "rj",
    name: "Rajasthan",
    zone: "North India",
    note: "Pucca and kacha bigha are both in daily use and differ by 1.56x. Always ask a seller which one they mean.",
    units: [
      { id: "bigha-pucca", family: "bigha", name: "Bigha (Pucca)", sqft: 27225, basis: "165 ft x 165 ft = 3,025 gaj = 27,225 sq ft" },
      { id: "bigha-kacha", family: "bigha", name: "Bigha (Kacha)", sqft: 17424, basis: "132 ft x 132 ft = 1,936 gaj = 17,424 sq ft" },
      { id: "biswa-pucca", family: "biswa", name: "Biswa (Pucca)", sqft: 1361.25, basis: "1 pucca bigha = 20 biswa = 1,361.25 sq ft" },
      { id: "biswa-kacha", family: "biswa", name: "Biswa (Kacha)", sqft: 871.2, basis: "1 kacha bigha = 20 biswa = 871.2 sq ft" },
      { id: "biswansi", family: "biswansi", name: "Biswansi (Pucca)", sqft: 68.0625, basis: "1 pucca biswa = 20 biswansi = 68.06 sq ft" },
    ],
  },
  {
    id: "mp",
    name: "Madhya Pradesh",
    zone: "Central India",
    note: "The smallest widely used bigha in India at 12,000 sq ft - less than half the Rajasthan pucca bigha.",
    units: [
      { id: "bigha", family: "bigha", name: "Bigha", sqft: 12000, basis: "1 bigha = 20 katha = 12,000 sq ft (0.28 acre)" },
      { id: "katha", family: "katha", name: "Katha", sqft: 600, basis: "1 bigha = 20 katha = 600 sq ft" },
      { id: "decimal", family: "decimal", name: "Decimal (Dismil)", sqft: 435.6, basis: "1 acre = 100 decimal = 435.6 sq ft" },
    ],
  },
  {
    id: "pb",
    name: "Punjab",
    zone: "North India",
    note: "Kanal - marla is the working system for plots; killa (acre) is used for farmland.",
    units: [
      { id: "killa", family: "killa", name: "Killa / Ghumaon", sqft: 43560, basis: "1 killa = 1 acre = 8 kanal = 43,560 sq ft" },
      { id: "kanal", family: "kanal", name: "Kanal", sqft: 5445, basis: "8 kanal = 1 acre, so 1 kanal = 5,445 sq ft = 605 gaj" },
      { id: "marla", family: "marla", name: "Marla", sqft: 272.25, basis: "1 kanal = 20 marla = 272.25 sq ft = 30.25 gaj" },
      { id: "sarsahi", family: "sarsahi", name: "Sarsahi", sqft: 30.25, basis: "1 marla = 9 sarsahi = 30.25 sq ft" },
      { id: "bigha", family: "bigha", name: "Bigha (Kacha)", sqft: 9075, basis: "Punjab kacha bigha = one-third pucca bigha = 1,008.33 gaj = 9,075 sq ft" },
      { id: "biswa", family: "biswa", name: "Biswa", sqft: 453.75, basis: "1 kacha bigha = 20 biswa = 453.75 sq ft" },
    ],
  },
  {
    id: "hr",
    name: "Haryana",
    zone: "North India",
    note: "Kanal - marla for plots, killa for farmland, pucca bigha in revenue records. 1 pucca bigha = exactly 5 kanal.",
    units: [
      { id: "killa", family: "killa", name: "Killa / Ghumaon", sqft: 43560, basis: "1 killa = 1 acre = 8 kanal = 43,560 sq ft" },
      { id: "kanal", family: "kanal", name: "Kanal", sqft: 5445, basis: "8 kanal = 1 acre, so 1 kanal = 5,445 sq ft = 605 gaj" },
      { id: "marla", family: "marla", name: "Marla", sqft: 272.25, basis: "1 kanal = 20 marla = 272.25 sq ft = 30.25 gaj" },
      { id: "sarsahi", family: "sarsahi", name: "Sarsahi", sqft: 30.25, basis: "1 marla = 9 sarsahi = 30.25 sq ft" },
      { id: "bigha", family: "bigha", name: "Bigha (Pucca)", sqft: 27225, basis: "1 pucca bigha = 3,025 gaj = 5 kanal = 27,225 sq ft" },
      { id: "biswa", family: "biswa", name: "Biswa", sqft: 1361.25, basis: "1 pucca bigha = 20 biswa = 1,361.25 sq ft" },
    ],
  },
  {
    id: "hp",
    name: "Himachal Pradesh",
    zone: "North India",
    note: "One HP bigha is exactly one-fifth of an acre - the neatest bigha definition in India.",
    units: [
      { id: "bigha", family: "bigha", name: "Bigha", sqft: 8712, basis: "1 bigha = one-fifth acre = 968 gaj = 8,712 sq ft" },
      { id: "biswa", family: "biswa", name: "Biswa", sqft: 435.6, basis: "1 bigha = 20 biswa = 435.6 sq ft (exactly 1 cent)" },
      { id: "biswansi", family: "biswansi", name: "Biswansi", sqft: 21.78, basis: "1 biswa = 20 biswansi = 21.78 sq ft" },
      { id: "kanal", family: "kanal", name: "Kanal", sqft: 5445, basis: "8 kanal = 1 acre = 5,445 sq ft" },
      { id: "marla", family: "marla", name: "Marla", sqft: 272.25, basis: "1 kanal = 20 marla = 272.25 sq ft" },
    ],
  },
  {
    id: "jk",
    name: "Jammu & Kashmir",
    zone: "North India",
    note: "Kanal and marla dominate - a Srinagar or Jammu plot is almost always quoted in kanal.",
    units: [
      { id: "kanal", family: "kanal", name: "Kanal", sqft: 5445, basis: "8 kanal = 1 acre, so 1 kanal = 5,445 sq ft = 605 gaj" },
      { id: "marla", family: "marla", name: "Marla", sqft: 272.25, basis: "1 kanal = 20 marla = 272.25 sq ft" },
      { id: "sarsahi", family: "sarsahi", name: "Sarsahi", sqft: 30.25, basis: "1 marla = 9 sarsahi = 30.25 sq ft" },
    ],
  },
  {
    id: "uk",
    name: "Uttarakhand",
    zone: "North India",
    note: "Hill districts measure in nali and muthi; the plains near UP use bigha - biswa.",
    units: [
      { id: "bigha", family: "bigha", name: "Bigha", sqft: 6804, basis: "1 bigha = 756 gaj = 6,804 sq ft (0.156 acre)" },
      { id: "biswa", family: "biswa", name: "Biswa", sqft: 340.2, basis: "1 bigha = 20 biswa = 340.2 sq ft" },
      { id: "nali", family: "nali", name: "Nali", sqft: 2160, basis: "1 nali = 240 gaj = 2,160 sq ft (hill districts)" },
      { id: "muthi", family: "muthi", name: "Muthi", sqft: 135, basis: "1 nali = 16 muthi = 135 sq ft" },
    ],
  },
  {
    id: "dl",
    name: "Delhi (NCT)",
    zone: "North India",
    note: "Both pucca and kacha bigha appear in Delhi revenue records and they differ by exactly 3x.",
    units: [
      { id: "bigha-pucca", family: "bigha", name: "Bigha (Pucca)", sqft: 27225, basis: "1 pucca bigha = 3,025 gaj = 27,225 sq ft" },
      { id: "bigha-kacha", family: "bigha", name: "Bigha (Kacha)", sqft: 9075, basis: "1 kacha bigha = one-third pucca = 1,008.33 gaj = 9,075 sq ft" },
      { id: "biswa-pucca", family: "biswa", name: "Biswa (Pucca)", sqft: 1361.25, basis: "1 pucca bigha = 20 biswa = 1,361.25 sq ft" },
      { id: "biswa-kacha", family: "biswa", name: "Biswa (Kacha)", sqft: 453.75, basis: "1 kacha bigha = 20 biswa = 453.75 sq ft" },
    ],
  },
  {
    id: "gj",
    name: "Gujarat",
    zone: "West India",
    note: "Vigha (bigha) for farmland. The 7/12 record itself is written in hectare - are - sq m.",
    units: [
      { id: "bigha", family: "bigha", name: "Bigha (Vigha)", sqft: 17427, basis: "1 vigha = 1,936 gaj = 17,427 sq ft (0.4 acre)" },
      { id: "guntha", family: "guntha", name: "Guntha", sqft: 1089, basis: "40 guntha = 1 acre, so 1 guntha = 1,089 sq ft = 121 gaj" },
      { id: "are", family: "are", name: "Are", sqft: 1076.391, basis: "1 are = 100 sq m; records read as hectare - are - sq m" },
    ],
  },
  {
    id: "mh",
    name: "Maharashtra",
    zone: "West India",
    note: "Guntha is the everyday farmland unit. The 7/12 extract shows hectare - are - sq m (H-R-P).",
    units: [
      { id: "guntha", family: "guntha", name: "Guntha", sqft: 1089, basis: "40 guntha = 1 acre, so 1 guntha = 1,089 sq ft = 121 gaj" },
      { id: "are", family: "are", name: "Are (R)", sqft: 1076.391, basis: "1 are = 100 sq m; 100 are = 1 hectare" },
    ],
  },
  {
    id: "ka",
    name: "Karnataka",
    zone: "South India",
    note: "Guntha for farmland, cent near the Tamil Nadu belt, ankanam for old Bengaluru house plots.",
    units: [
      { id: "guntha", family: "guntha", name: "Guntha", sqft: 1089, basis: "40 guntha = 1 acre = 1,089 sq ft = 121 gaj" },
      { id: "cent", family: "cent", name: "Cent", sqft: 435.6, basis: "100 cent = 1 acre, so 1 cent = 435.6 sq ft" },
      { id: "ankanam", family: "ankanam", name: "Ankanam", sqft: 72, basis: "1 ankanam = 8 gaj = 72 sq ft" },
    ],
  },
  {
    id: "tn",
    name: "Tamil Nadu",
    zone: "South India",
    note: "Chennai plots are quoted in ground; farmland uses cent and cawnie.",
    units: [
      { id: "cawnie", family: "cawnie", name: "Cawnie", sqft: 57600, basis: "1 cawnie = 24 ground = 57,600 sq ft (1.32 acre)" },
      { id: "ground", family: "ground", name: "Ground", sqft: 2400, basis: "1 ground = 2,400 sq ft = 266.67 gaj (Chennai standard)" },
      { id: "cent", family: "cent", name: "Cent", sqft: 435.6, basis: "100 cent = 1 acre, so 1 cent = 435.6 sq ft" },
      { id: "kuli", family: "kuli", name: "Kuli (Kuzhi)", sqft: 57.6, basis: "1 cawnie = 1,000 kuli = 57.6 sq ft" },
      { id: "sqkaram", family: "sqkaram", name: "Square Karam", sqft: 30.25, basis: "1 karam = 5.5 ft, so 1 sq karam = 5.5 x 5.5 = 30.25 sq ft" },
    ],
  },
  {
    id: "kl",
    name: "Kerala",
    zone: "South India",
    note: "Cent is the default unit in almost every listing; the record itself often reads in are.",
    units: [
      { id: "cent", family: "cent", name: "Cent", sqft: 435.6, basis: "100 cent = 1 acre, so 1 cent = 435.6 sq ft" },
      { id: "are", family: "are", name: "Are", sqft: 1076.391, basis: "1 are = 100 sq m = 2.47 cent" },
    ],
  },
  {
    id: "ap",
    name: "Andhra Pradesh",
    zone: "South India",
    note: "Cent and guntha for land, ankanam for house plots, kuncham in the coastal districts.",
    units: [
      { id: "kuncham", family: "kuncham", name: "Kuncham", sqft: 4356, basis: "1 kuncham = 10 cent = 484 gaj = 4,356 sq ft" },
      { id: "guntha", family: "guntha", name: "Guntha", sqft: 1089, basis: "40 guntha = 1 acre = 1,089 sq ft = 121 gaj" },
      { id: "cent", family: "cent", name: "Cent", sqft: 435.6, basis: "100 cent = 1 acre, so 1 cent = 435.6 sq ft" },
      { id: "ankanam", family: "ankanam", name: "Ankanam", sqft: 72, basis: "1 ankanam = 8 gaj = 72 sq ft" },
      { id: "sqkaram", family: "sqkaram", name: "Square Karam", sqft: 30.25, basis: "1 karam = 5.5 ft, so 1 sq karam = 30.25 sq ft" },
    ],
  },
  {
    id: "tg",
    name: "Telangana",
    zone: "South India",
    note: "Guntha and acre for farmland; Hyderabad plots are usually quoted straight in sq yard (gaj).",
    units: [
      { id: "guntha", family: "guntha", name: "Guntha", sqft: 1089, basis: "40 guntha = 1 acre = 1,089 sq ft = 121 gaj" },
      { id: "cent", family: "cent", name: "Cent", sqft: 435.6, basis: "100 cent = 1 acre, so 1 cent = 435.6 sq ft" },
      { id: "ankanam", family: "ankanam", name: "Ankanam", sqft: 72, basis: "1 ankanam = 8 gaj = 72 sq ft" },
      { id: "sqkaram", family: "sqkaram", name: "Square Karam", sqft: 30.25, basis: "1 karam = 5.5 ft, so 1 sq karam = 30.25 sq ft" },
    ],
  },
  {
    id: "as",
    name: "Assam",
    zone: "Northeast India",
    note: "One Assam bigha = 5 katha, not 20. That makes the Assam katha four times a Bengal katha.",
    units: [
      { id: "bigha", family: "bigha", name: "Bigha", sqft: 14400, basis: "1 bigha = 5 katha = 14,400 sq ft (0.33 acre)" },
      { id: "katha", family: "katha", name: "Katha", sqft: 2880, basis: "1 katha = 20 lecha = 2,880 sq ft" },
      { id: "lecha", family: "lecha", name: "Lecha", sqft: 144, basis: "1 katha = 20 lecha = 144 sq ft" },
    ],
  },
  {
    id: "jh",
    name: "Jharkhand",
    zone: "East India",
    note: "Shares the Bihar bigha - katha - dhur chain; decimal is what most sale deeds actually use.",
    units: [
      { id: "bigha", family: "bigha", name: "Bigha", sqft: 27220, basis: "1 bigha = 20 katha = 27,220 sq ft (0.625 acre)" },
      { id: "katha", family: "katha", name: "Katha", sqft: 1361, basis: "1 katha = 20 dhur = 1,361 sq ft" },
      { id: "dhur", family: "dhur", name: "Dhur", sqft: 68.05, basis: "1 katha = 20 dhur = 68.05 sq ft" },
      { id: "decimal", family: "decimal", name: "Decimal (Dismil)", sqft: 435.6, basis: "1 acre = 100 decimal = 435.6 sq ft" },
    ],
  },
  {
    id: "od",
    name: "Odisha",
    zone: "East India",
    note: "Decimal is the standard record unit; guntha turns up in the western districts.",
    units: [
      { id: "decimal", family: "decimal", name: "Decimal (Dismil)", sqft: 435.6, basis: "1 acre = 100 decimal = 435.6 sq ft" },
      { id: "guntha", family: "guntha", name: "Guntha", sqft: 1089, basis: "40 guntha = 1 acre = 1,089 sq ft" },
    ],
  },
  {
    id: "cg",
    name: "Chhattisgarh",
    zone: "Central India",
    note: "Records are kept in hectare and acre; decimal is the everyday small unit for homestead land.",
    units: [
      { id: "decimal", family: "decimal", name: "Decimal (Dismil)", sqft: 435.6, basis: "1 acre = 100 decimal = 435.6 sq ft" },
      { id: "katha", family: "katha", name: "Katha", sqft: 600, basis: "Legacy Madhya Pradesh chain: 1 bigha = 20 katha = 600 sq ft" },
    ],
  },
];

export const FAMILY_LABELS = {
  bigha: "Bigha",
  katha: "Katha / Cottah",
  biswa: "Biswa",
  biswansi: "Biswansi",
  kanal: "Kanal",
  marla: "Marla",
  sarsahi: "Sarsahi",
  killa: "Killa / Ghumaon",
  guntha: "Guntha",
  cent: "Cent",
  decimal: "Decimal (Dismil)",
  ground: "Ground",
  ankanam: "Ankanam",
  sqkaram: "Square Karam",
  are: "Are",
  dhur: "Dhur",
  dhurki: "Dhurki",
  chatak: "Chatak",
  lecha: "Lecha",
  nali: "Nali",
  muthi: "Muthi",
  kuncham: "Kuncham",
  cawnie: "Cawnie",
  kuli: "Kuli (Kuzhi)",
};

export const QUICK_FACTS = [
  {
    title: "Why does the bigha change size?",
    body: "The bigha was never standardised by any central law. Each princely state and revenue settlement fixed its own, and those local definitions survived into modern land records. That is why 1 bigha is 27,225 sq ft in Rajasthan but only 6,804 sq ft in Uttarakhand - a 4x gap for the same word.",
  },
  {
    title: "Pucca vs kacha",
    body: "In Rajasthan, Punjab, Haryana and Delhi a bigha comes in two sizes. Pucca is the full revenue bigha, kacha is a fraction of it (one-third in Delhi and Punjab, 1/1.5625 in Rajasthan). Sellers quoting a low price per bigha are often quoting kacha.",
  },
  {
    title: "The units that never move",
    body: "Acre, hectare, sq ft, sq m and gaj mean the same thing everywhere in India. Cent (435.6 sq ft), guntha (1,089 sq ft), kanal (5,445 sq ft) and marla (272.25 sq ft) are also fixed nationally - they are derived from the acre, so they cannot drift.",
  },
  {
    title: "What to put in the agreement",
    body: "Write the area in sq ft or sq m in the sale deed, with the local unit only in brackets. A deed that says 'two bigha' and nothing else is genuinely ambiguous, and district-level variation inside a state exists too. Cross-check against the khasra, 7/12 or RTC record.",
  },
];
