export const services = [
  {
    slug: "kitchen-refresh",
    title: "Kitchen Refresh",
    shortTitle: "Kitchen",
    category: "Kitchen Pros",
    text: "Cabinets, counters, layout, lighting, and finish upgrades.",
    icon: "hammer",
    tone: "mint",
    headline: "Compare kitchen remodel estimates from trusted local pros.",
    subhead: "Plan cabinet, counter, flooring, layout, and lighting upgrades with quote ranges before you commit.",
    savings: "Save up to $10,000",
    bullets: [
      "Cabinet, counter, island, flooring, and layout specialists.",
      "Local availability checked after your ZIP code is entered.",
      "No-obligation estimates from vetted kitchen contractors.",
    ],
    benefits: [
      { title: "Boost Value", text: "High-ROI upgrades for daily living and resale." },
      { title: "Custom Layout", text: "Better storage, flow, prep space, and lighting." },
      { title: "More Storage", text: "Smart cabinet, pantry, and island planning." },
      { title: "Vetted Pros", text: "Compare specialists with clear project scopes." },
    ],
    howItWorks: [
      "Check your ZIP code",
      "Tell us about your kitchen project",
      "Compare quotes from local contractors",
      "Choose the best fit for your budget",
    ],
    projects: [
      {
        title: "Full Kitchen Renovation",
        text: "For wall changes, new layouts, full cabinet packages, flooring, and finish selections. Best for homeowners planning a bigger transformation.",
        cta: "Start Your Remodel",
        image: "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=82",
      },
      {
        title: "Cabinets & Countertops",
        text: "Refresh the most visible parts of your kitchen without rebuilding the whole room. A strong choice for faster upgrades with clear material options.",
        cta: "See Design Options",
        image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=900&q=82",
      },
    ],
    quoteTypes: [
      { title: "Full Remodel", text: "Demolition, layout changes, cabinets, counters, and finishing." },
      { title: "Cabinets & Storage", text: "Custom cabinetry, refacing, pantry systems, and islands." },
      { title: "Countertops", text: "Quartz, granite, marble, butcher block, and installation." },
      { title: "Flooring & Tile", text: "Durable surfaces, backsplashes, and transition details." },
      { title: "Lighting Plan", text: "Task lighting, pendants, recessed fixtures, and dimmer upgrades." },
      { title: "Island Upgrades", text: "Seating, prep space, outlets, storage, and waterfall edges." },
    ],
    savingsRows: [
      { city: "Atlanta", job: "Complete Kitchen", low: "$15,000", high: "$28,000", saved: "$13,000" },
      { city: "Dallas", job: "Cabinets & Counters", low: "$8,900", high: "$16,500", saved: "$7,600" },
      { city: "Orlando", job: "Island Addition", low: "$2,500", high: "$4,800", saved: "$2,300" },
      { city: "Chicago", job: "Countertop Swap", low: "$4,900", high: "$8,600", saved: "$3,700" },
      { city: "Seattle", job: "Cabinet Refacing", low: "$7,200", high: "$13,400", saved: "$6,200" },
      { city: "San Diego", job: "Lighting & Tile", low: "$3,800", high: "$7,100", saved: "$3,300" },
      { city: "Minneapolis", job: "Kitchen Flooring", low: "$3,400", high: "$6,900", saved: "$3,500" },
      { city: "Boston", job: "Pantry Buildout", low: "$2,900", high: "$5,500", saved: "$2,600" },
    ],
    insights: [
      { title: "Budgeting for a Remodel", text: "Pros often recommend planning around 10-15% of home value for major kitchen work." },
      { title: "Optimizing the Work Triangle", text: "A good layout reduces steps between sink, fridge, cooktop, and prep zones." },
      { title: "Lighting Matters", text: "Layered task, ambient, and accent lighting can change how the entire kitchen feels." },
    ],
    resultPros: [
      { name: "Craft Cabinet Studio", rating: "4.9", reviews: "218 reviews", years: "14 years in business", hires: "Hired 462 times", badge: "Top Rated" },
      { name: "Modern Kitchen Works", rating: "4.8", reviews: "176 reviews", years: "11 years in business", hires: "Hired 389 times", badge: "Fastest Response" },
      { name: "Stone & Storage Remodelers", rating: "4.9", reviews: "241 reviews", years: "17 years in business", hires: "Hired 517 times", badge: "Best Value" },
    ],
  },
  {
    slug: "bath-remodel",
    title: "Bath Remodel",
    shortTitle: "Bathroom",
    category: "Bathroom Remodelers",
    text: "Showers, tubs, tile, vanities, waterproofing, and fixtures.",
    icon: "bath",
    tone: "blue",
    headline: "Find bathroom remodel quotes for a cleaner, calmer space.",
    subhead: "Compare pros for shower conversions, tile work, vanities, lighting, waterproofing, and full bath upgrades.",
    savings: "Save up to $7,500",
    bullets: [
      "Shower, tub, vanity, tile, and accessibility specialists.",
      "Compare remodel timelines and material approaches.",
      "ZIP-based matching keeps results local to your area.",
    ],
    benefits: [
      { title: "Waterproof First", text: "Pros who handle prep, drainage, and durable finishes." },
      { title: "Better Storage", text: "Vanities, niches, shelving, and compact layouts." },
      { title: "Fixture Refresh", text: "Updated valves, glass, lighting, and hardware." },
      { title: "Cleaner Install", text: "Compare teams that fit your schedule and scope." },
    ],
    howItWorks: [
      "Enter your ZIP code",
      "Pick shower, tub, vanity, or full remodel",
      "Review matching remodelers",
      "Book a quote window",
    ],
    projects: [
      {
        title: "Shower Conversion",
        text: "Swap tubs, improve waterproofing, update glass, and choose durable wall finishes. Ideal when comfort, safety, and easy cleaning matter.",
        cta: "Plan My Shower",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=82",
      },
      {
        title: "Full Bath Upgrade",
        text: "Coordinate tile, vanity, lighting, flooring, paint, fixtures, and ventilation. Useful for a complete refresh with one planned scope.",
        cta: "Compare Remodelers",
        image: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=900&q=82",
      },
    ],
    quoteTypes: [
      { title: "Walk-In Shower", text: "Tile, panels, glass doors, waterproofing, and fixtures." },
      { title: "Vanity & Storage", text: "Cabinets, counters, mirrors, lighting, and plumbing updates." },
      { title: "Tile & Flooring", text: "Floor tile, wall tile, heated floors, and grout work." },
      { title: "Accessibility", text: "Grab bars, low-threshold entries, seating, and safer layouts." },
      { title: "Tub Replacement", text: "Soaking tubs, surrounds, valves, drains, and clean installation." },
      { title: "Ventilation", text: "Fans, ducting, moisture control, and quieter bathroom airflow." },
    ],
    savingsRows: [
      { city: "Phoenix", job: "Shower Conversion", low: "$6,200", high: "$11,800", saved: "$5,600" },
      { city: "Tampa", job: "Full Bathroom", low: "$12,500", high: "$20,000", saved: "$7,500" },
      { city: "Denver", job: "Vanity & Tile", low: "$4,100", high: "$7,900", saved: "$3,800" },
      { city: "Portland", job: "Walk-In Shower", low: "$7,400", high: "$12,900", saved: "$5,500" },
      { city: "Austin", job: "Tile & Flooring", low: "$3,600", high: "$6,800", saved: "$3,200" },
      { city: "Miami", job: "Tub Replacement", low: "$5,900", high: "$10,600", saved: "$4,700" },
      { city: "Cleveland", job: "Vanity Upgrade", low: "$2,700", high: "$5,100", saved: "$2,400" },
      { city: "Sacramento", job: "Accessibility Bath", low: "$8,200", high: "$14,300", saved: "$6,100" },
    ],
    insights: [
      { title: "Ventilation Is Not Optional", text: "A strong fan and proper ducting help protect paint, tile, and cabinetry." },
      { title: "Tile Prep Drives Quality", text: "Level walls, waterproof membranes, and careful layout matter more than tile price alone." },
      { title: "Fixtures Shape the Feel", text: "Faucets, valves, shower heads, and lighting often deliver the most noticeable upgrade." },
    ],
    resultPros: [
      { name: "Clearwater Bath Design", rating: "4.9", reviews: "203 reviews", years: "13 years in business", hires: "Hired 421 times", badge: "Top Rated" },
      { name: "Tile & Shower Specialists", rating: "4.8", reviews: "164 reviews", years: "10 years in business", hires: "Hired 354 times", badge: "Fastest Response" },
      { name: "Fresh Vanity Remodel Co.", rating: "4.9", reviews: "197 reviews", years: "16 years in business", hires: "Hired 438 times", badge: "Best Value" },
    ],
  },
  {
    slug: "hvac-tune-up",
    title: "HVAC Tune-Up",
    shortTitle: "HVAC",
    category: "HVAC Technicians",
    text: "AC repair, furnace installs, ductwork, and urgent diagnostics.",
    icon: "snowflake",
    tone: "sky",
    headline: "Get HVAC repair and replacement quotes from local technicians.",
    subhead: "Check availability for AC repair, furnace service, heat pumps, ductwork, tune-ups, and replacement systems.",
    savings: "Save up to $4,000",
    bullets: [
      "Repair, maintenance, replacement, and emergency options.",
      "Compare licensed technicians and system recommendations.",
      "Start with ZIP code availability before scheduling.",
    ],
    benefits: [
      { title: "Fast Diagnostics", text: "Find techs for urgent cooling or heating issues." },
      { title: "Right-Sized Systems", text: "Avoid overpaying for equipment your home does not need." },
      { title: "Cleaner Airflow", text: "Filter, duct, and vent checks for better comfort." },
      { title: "Maintenance Help", text: "Keep systems efficient before peak seasons." },
    ],
    howItWorks: [
      "Enter your ZIP code",
      "Choose AC, furnace, ductwork, or replacement",
      "Compare local HVAC pros",
      "Schedule service or an estimate",
    ],
    projects: [
      {
        title: "AC Repair & Tune-Up",
        text: "Get help with weak cooling, noisy units, thermostat issues, leaks, and seasonal service. Compare quick diagnostics before peak weather hits.",
        cta: "Check AC Availability",
        image: "https://loremflickr.com/900/675/hvac,technician?lock=421",
      },
      {
        title: "System Replacement",
        text: "Compare equipment options, efficiency ratings, installation scope, and warranties. Helpful when repairs no longer feel worth the cost.",
        cta: "Compare Systems",
        image: "https://loremflickr.com/900/675/air-conditioner,home?lock=422",
      },
    ],
    quoteTypes: [
      { title: "AC Repair", text: "Capacitors, refrigerant checks, coils, fans, and diagnostics." },
      { title: "Furnace Service", text: "Ignition, airflow, burners, filters, and safety checks." },
      { title: "Heat Pumps", text: "Efficient heating and cooling system replacement quotes." },
      { title: "Ductwork", text: "Leaks, airflow balancing, insulation, and replacement." },
      { title: "Thermostats", text: "Smart controls, zoning support, calibration, and setup." },
      { title: "Seasonal Tune-Up", text: "Preventive checks before heavy cooling or heating months." },
    ],
    savingsRows: [
      { city: "Houston", job: "AC Replacement", low: "$6,900", high: "$10,800", saved: "$3,900" },
      { city: "Charlotte", job: "Heat Pump", low: "$7,500", high: "$11,200", saved: "$3,700" },
      { city: "Las Vegas", job: "AC Repair", low: "$290", high: "$850", saved: "$560" },
      { city: "San Antonio", job: "Duct Sealing", low: "$1,200", high: "$2,600", saved: "$1,400" },
      { city: "Nashville", job: "Furnace Service", low: "$420", high: "$1,100", saved: "$680" },
      { city: "Riverside", job: "Mini Split Install", low: "$4,800", high: "$8,900", saved: "$4,100" },
      { city: "Kansas City", job: "Thermostat Setup", low: "$260", high: "$690", saved: "$430" },
      { city: "Jacksonville", job: "Seasonal Tune-Up", low: "$180", high: "$520", saved: "$340" },
    ],
    insights: [
      { title: "Sizing Beats Guessing", text: "A load calculation helps prevent noisy short-cycling and uneven room temperatures." },
      { title: "Filters Affect Everything", text: "Restricted airflow can make systems work harder and fail sooner." },
      { title: "Duct Leaks Waste Money", text: "Sealing and insulating ducts can improve comfort before buying new equipment." },
    ],
    resultPros: [
      { name: "ComfortFlow HVAC Pros", rating: "4.9", reviews: "229 reviews", years: "18 years in business", hires: "Hired 544 times", badge: "Top Rated" },
      { name: "Rapid Air Repair Team", rating: "4.8", reviews: "188 reviews", years: "12 years in business", hires: "Hired 476 times", badge: "Fastest Response" },
      { name: "Peak Season Heating & Air", rating: "4.9", reviews: "216 reviews", years: "15 years in business", hires: "Hired 501 times", badge: "Best Value" },
    ],
  },
  {
    slug: "whole-home-repairs",
    title: "Whole-Home Repairs",
    shortTitle: "Repairs",
    category: "Home Repair Pros",
    text: "Reliable help for roofing, drywall, plumbing, and punch lists.",
    icon: "wrench",
    tone: "coral",
    headline: "Match with repair pros for the projects your home keeps asking for.",
    subhead: "From drywall and plumbing to roofing, trim, doors, and punch lists, compare local help for practical fixes.",
    savings: "Save time and avoid repeat visits",
    bullets: [
      "General repairs, punch lists, small installs, and urgent fixes.",
      "Compare crews by project type and local availability.",
      "Use one ZIP-based starting point for multiple needs.",
    ],
    benefits: [
      { title: "One Clear Start", text: "Describe the repair and find the right type of pro." },
      { title: "Less Phone Tag", text: "Compare availability before committing your day." },
      { title: "Bundled Fixes", text: "Group small repairs into one practical visit." },
      { title: "Practical Scope", text: "Handle small jobs before they become bigger ones." },
    ],
    howItWorks: [
      "Enter your ZIP code",
      "Choose the repair category",
      "Compare local matches",
      "Schedule a quote or service visit",
    ],
    projects: [
      {
        title: "Repair Punch List",
        text: "Bundle drywall, doors, trim, fixtures, caulk, paint touch-ups, and hardware into one plan. Great for finishing several small jobs at once.",
        cta: "Build My List",
        image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=900&q=82",
      },
      {
        title: "Urgent Home Fix",
        text: "Find nearby help for leaks, damage, broken fixtures, and repairs that cannot wait. Start with local availability and a clean repair category.",
        cta: "Find Repair Help",
        image: "https://loremflickr.com/900/675/plumber,repair?lock=423",
      },
    ],
    quoteTypes: [
      { title: "Drywall & Paint", text: "Patches, texture matching, touch-ups, and room refreshes." },
      { title: "Plumbing Fixes", text: "Leaks, fixtures, drains, valves, and minor installs." },
      { title: "Roof & Exterior", text: "Shingles, flashing, gutters, siding, and weather damage." },
      { title: "Door & Trim", text: "Interior doors, casing, baseboards, hardware, and adjustments." },
      { title: "Fixture Installs", text: "Lights, fans, faucets, shelves, hardware, and small upgrades." },
      { title: "Punch Lists", text: "Grouped repairs for move-ins, sale prep, and overdue fixes." },
    ],
    savingsRows: [
      { city: "Raleigh", job: "Repair Bundle", low: "$850", high: "$1,900", saved: "$1,050" },
      { city: "Nashville", job: "Drywall & Paint", low: "$650", high: "$1,400", saved: "$750" },
      { city: "Columbus", job: "Exterior Repairs", low: "$1,200", high: "$2,600", saved: "$1,400" },
      { city: "Pittsburgh", job: "Door & Trim", low: "$480", high: "$1,150", saved: "$670" },
      { city: "Salt Lake City", job: "Fixture Installs", low: "$390", high: "$980", saved: "$590" },
      { city: "Indianapolis", job: "Plumbing Fixes", low: "$340", high: "$920", saved: "$580" },
      { city: "Omaha", job: "Punch List", low: "$720", high: "$1,650", saved: "$930" },
      { city: "Milwaukee", job: "Gutter Repair", low: "$560", high: "$1,300", saved: "$740" },
    ],
    insights: [
      { title: "Bundle Small Jobs", text: "Combining repairs can reduce repeat trip charges and scheduling friction." },
      { title: "Document Damage", text: "Photos and measurements help pros quote faster and more accurately." },
      { title: "Fix Water Issues Early", text: "Leaks and exterior gaps tend to get more expensive the longer they wait." },
    ],
    resultPros: [
      { name: "Reliable Repair Collective", rating: "4.8", reviews: "159 reviews", years: "9 years in business", hires: "Hired 336 times", badge: "Top Rated" },
      { name: "Patch & Fix Home Crew", rating: "4.9", reviews: "191 reviews", years: "14 years in business", hires: "Hired 402 times", badge: "Fastest Response" },
      { name: "All-Around Home Repairs", rating: "4.8", reviews: "173 reviews", years: "12 years in business", hires: "Hired 367 times", badge: "Best Value" },
    ],
  },
];

export function getService(slug) {
  return services.find((service) => service.slug === slug);
}
