export const EXPERIENCE_GROUPS = Object.freeze({
  create: Object.freeze({ id: "create", label: "Create & experiment" }),
  explore: Object.freeze({ id: "explore", label: "Explore & discover" }),
  play: Object.freeze({ id: "play", label: "Play & focus" }),
});

export const EXPERIENCE_CATALOG = Object.freeze([
  {
    slug: "sketchflow",
    name: "SketchFlow",
    href: "/sketchflow",
    tagline: "Turn rough ideas into polished visual flows on an infinite canvas.",
    description: "Map ideas, journeys, and lightweight diagrams in a focused visual workspace.",
    cta: "Open SketchFlow",
    tag: "Create",
    group: "create",
    tone: "teal",
    icon: "PenTool",
    featured: true,
    selfChrome: true,
    priority: 0.62,
  },
  {
    slug: "radio-garden",
    name: "OpenAir Garden",
    href: "/radio-garden",
    tagline: "Spin the globe and discover live radio from cities around the world.",
    description: "Explore internet radio geographically through an interactive globe.",
    cta: "Explore stations",
    tag: "Explore",
    group: "explore",
    tone: "cyan",
    icon: "Radio",
    featured: true,
    selfChrome: true,
    priority: 0.58,
  },
  {
    slug: "patatap",
    name: "KeyCanvas",
    href: "/patatap",
    tagline: "Turn every key press into a synchronized burst of sound and motion.",
    description: "A keyboard-driven sound and animation canvas for quick creative play.",
    cta: "Play KeyCanvas",
    tag: "Play",
    group: "play",
    tone: "violet",
    icon: "Music4",
    featured: true,
    selfChrome: true,
    priority: 0.56,
  },
  {
    slug: "pixel-thought",
    name: "Pixel Thought",
    href: "/pixel-thought",
    tagline: "Take a 60-second mindfulness break and put one worry back in perspective.",
    description: "A short guided visual reset designed for calm, focus, and perspective.",
    cta: "Take a mindful minute",
    tag: "Focus",
    group: "play",
    tone: "teal",
    icon: "Sparkles",
    featured: true,
    selfChrome: true,
    priority: 0.6,
  },
  {
    slug: "prank-socialmedia",
    name: "Mockly",
    href: "/prank-socialmedia",
    description: "Create clearly labelled social-media mockups for demos, stories, and prototypes.",
    tag: "Create",
    group: "create",
    tone: "cyan",
    icon: "ImageIcon",
    selfChrome: true,
    priority: 0.64,
  },
  {
    slug: "altpintrest",
    name: "AltF Pinboard",
    href: "/altpintrest",
    description: "Collect and arrange visual ideas in a lightweight inspiration board.",
    tag: "Create",
    group: "create",
    tone: "violet",
    icon: "LayoutGrid",
    selfChrome: false,
    priority: 0.62,
  },
  {
    slug: "live-activity-simulation",
    name: "Live Activity Simulator",
    href: "/live-activity-simulation",
    description: "Generate simulated activity streams for prototypes, demos, and interface testing.",
    tag: "Create",
    group: "create",
    tone: "teal",
    icon: "Activity",
    selfChrome: true,
    priority: 0.56,
  },
  {
    slug: "windowswap",
    name: "World Windows",
    href: "/windowswap",
    description: "Open a virtual window somewhere else in the world and enjoy the view.",
    tag: "Explore",
    group: "explore",
    tone: "teal",
    icon: "AppWindow",
    selfChrome: true,
    priority: 0.6,
  },
  {
    slug: "flightradar",
    name: "Flight Radar Simulator",
    href: "/flightradar",
    description: "Explore simulated aircraft movement in an interactive radar-style dashboard.",
    tag: "Explore",
    group: "explore",
    tone: "violet",
    icon: "Plane",
    selfChrome: true,
    priority: 0.62,
  },
  {
    slug: "fact-net",
    name: "FactNet",
    href: "/fact-net",
    description: "Browse original topic guides and concise facts through clear categories.",
    tag: "Discover",
    group: "explore",
    tone: "teal",
    icon: "Library",
    selfChrome: true,
    priority: 0.7,
  },
  {
    slug: "bharat-virasat",
    name: "Bharat Virasat",
    href: "/bharat-virasat",
    description: "Journey through India's heritage sites, monuments, and living traditions.",
    tag: "Explore",
    group: "explore",
    tone: "cyan",
    icon: "Landmark",
    selfChrome: true,
    priority: 0.66,
  },
  {
    slug: "kym",
    name: "Meme Atlas",
    href: "/kym",
    description: "Browse explainers for internet culture, formats, and trending memes.",
    tag: "Discover",
    group: "explore",
    tone: "violet",
    icon: "Laugh",
    selfChrome: false,
    priority: 0.62,
  },
  {
    slug: "ancestory",
    name: "Name Origins",
    href: "/ancestory",
    description: "Discover the meaning, origin, and cultural story behind a name.",
    tag: "Discover",
    group: "explore",
    tone: "cyan",
    icon: "ScrollText",
    selfChrome: false,
    priority: 0.64,
  },
  {
    slug: "soft-murmur",
    name: "Ambient Mixer",
    href: "/soft-murmur",
    description: "Blend ambient sounds into a personal soundscape for focus, sleep, or study.",
    tag: "Focus",
    group: "play",
    tone: "cyan",
    icon: "Waves",
    selfChrome: true,
    priority: 0.58,
  },
  {
    slug: "personality",
    name: "Personality Lab",
    href: "/personality",
    description: "Take quick reflective quizzes and explore different personality dimensions.",
    tag: "Play",
    group: "play",
    tone: "violet",
    icon: "Brain",
    selfChrome: false,
    priority: 0.66,
  },
  {
    slug: "playbuzz",
    name: "Quiz Studio",
    href: "/playbuzz",
    description: "Try shareable trivia, quizzes, and light personality experiences.",
    tag: "Play",
    group: "play",
    tone: "teal",
    icon: "Puzzle",
    selfChrome: true,
    priority: 0.62,
  },
  {
    slug: "buzzfeed",
    name: "AltF Pulse",
    href: "/buzzfeed",
    description: "Editorial preview paused while source records and publishing controls are rebuilt.",
    tag: "Preview",
    group: "explore",
    tone: "cyan",
    icon: "Newspaper",
    selfChrome: false,
    noindex: true,
    priority: 0.58,
  },
  {
    slug: "fodey-new",
    name: "Maker Studio",
    href: "/fodey-new",
    description: "Create playful posters, newspaper clippings, scene cards, and character graphics.",
    tag: "Create",
    group: "create",
    tone: "teal",
    icon: "Wrench",
    selfChrome: true,
    priority: 0.6,
  },
  {
    slug: "geektyper",
    name: "Code Theater",
    href: "/geektyper",
    description: "Run cinematic fictional terminal interfaces for demos, streams, and harmless play.",
    tag: "Play",
    group: "play",
    tone: "violet",
    icon: "Sparkles",
    selfChrome: true,
    priority: 0.56,
  },
  {
    slug: "human-benchmark",
    name: "Reflex Lab",
    href: "/human-benchmark",
    description: "Practice reaction time, memory, typing, aim, and visual sequence challenges.",
    tag: "Train",
    group: "play",
    tone: "teal",
    icon: "Trophy",
    selfChrome: true,
    priority: 0.64,
  },
  {
    slug: "pranx",
    name: "Pranx Studio",
    href: "/pranx",
    description: "Open harmless simulated screens for demos and good-natured jokes.",
    tag: "Play",
    group: "play",
    tone: "cyan",
    icon: "Ghost",
    selfChrome: true,
    priority: 0.62,
  },
  {
    slug: "games",
    name: "Games Arcade",
    href: "/games",
    description: "Browse quick browser games grouped by puzzle, arcade, word, board, and casual play.",
    tag: "Play",
    group: "play",
    tone: "teal",
    icon: "Gamepad2",
    selfChrome: false,
    priority: 0.72,
  },
  {
    slug: "altfgame",
    name: "AltF Games",
    href: "/altfgame",
    description: "Play polished native browser games with fullscreen controls, related picks, and no downloads.",
    tag: "Play",
    group: "play",
    tone: "cyan",
    icon: "Gamepad2",
    selfChrome: false,
    priority: 0.7,
  },
  {
    slug: "wattpad",
    name: "Story Reader",
    href: "/wattpad",
    description: "Browse serialized stories and continue reading through organized chapters.",
    tag: "Read",
    group: "play",
    tone: "violet",
    icon: "BookOpen",
    selfChrome: false,
    priority: 0.66,
  },
  {
    slug: "altfworld",
    name: "AltfWorld",
    href: "/altfworld",
    tagline: "A display-only community interface demo.",
    description:
      "Explore a generated community-interface demo for builders, tool users, creators, and privacy-minded digital explorers.",
    cta: "Explore the demo",
    tag: "Preview",
    group: "explore",
    tone: "cyan",
    icon: "Users",
    selfChrome: true,
    noindex: true,
    priority: 0.64,
  },
]);

export function getExperienceBySlug(slug) {
  return EXPERIENCE_CATALOG.find((experience) => experience.slug === slug) || null;
}

export function getExperiencesByGroup(group) {
  return EXPERIENCE_CATALOG.filter((experience) => experience.group === group);
}
