export const PRODUCT_SUITE_STATUSES = Object.freeze({
  working: "Working",
  beta: "Public beta",
  gated: "Security gated",
});

export const PRODUCT_SUITE_CATALOG = Object.freeze([
  {
    slug: "idea-lab",
    productId: "idea-lab",
    name: "AltF IdeaLab",
    eyebrow: "Validate before you build",
    description: "Turn a rough idea into an evidence-led score, risk review, and practical validation plan.",
    status: "working",
    privacy: "Runs locally in your browser",
    capabilities: ["Opportunity score", "Risk review", "Validation experiments"],
    relatedTools: [
      ["Business Idea Generator", "/tools/all/random-business-idea"],
      ["Startup Name Generator", "/tools/all/startup-name-generator"],
      ["Decision Matrix", "/tools/all/decision-matrix-tool"],
      ["Survey Builder", "/tools/all/survey-builder"],
    ],
  },
  {
    slug: "domainops",
    productId: "domain-ops",
    name: "AltF DomainOps",
    eyebrow: "One readable domain report",
    description: "Inspect DNS, mail, ownership, and policy records with plain-language findings and source visibility.",
    status: "beta",
    privacy: "Only the requested hostname is sent to DNS and RDAP providers",
    capabilities: ["DNS records", "SPF and DMARC", "RDAP registration"],
    relatedTools: [
      ["Domain Checker", "/tools/all/domain-checker"],
      ["AI Domain Generator", "/tools/all/ai-domain-generator"],
      ["Web Speed Checker", "/tools/all/web-speed-checker"],
      ["Redirect Inspector", "/tools/all/wheregoes-tool"],
    ],
  },
  {
    slug: "minutes",
    productId: "minutes",
    name: "AltF Minutes",
    eyebrow: "Meetings into decisions",
    description: "Extract a concise summary, decisions, action items, and open questions from a transcript locally.",
    status: "working",
    privacy: "Transcript processing stays in your browser",
    capabilities: ["Summary", "Decision log", "Action and question extraction"],
    relatedTools: [
      ["Transcript Action Extractor", "/tools/all/meeting-transcript-action-extractor"],
      ["Meeting Agenda Builder", "/tools/all/meeting-agenda-builder"],
      ["Meeting Cost Calculator", "/tools/all/meeting-cost-calculator"],
      ["Text Summarizer", "/tools/all/text-summarizer"],
    ],
  },
  {
    slug: "security",
    productId: "security",
    name: "AltF Security",
    eyebrow: "Understand the issue and the fix",
    description: "Run a private HTML accessibility and security-readiness review, then open focused security utilities.",
    status: "working",
    privacy: "Pasted HTML never leaves your browser",
    capabilities: ["HTML readiness audit", "Password tools", "Privacy diagnostics"],
    relatedTools: [
      ["Password Strength Checker", "/tools/all/password-strength-checker"],
      ["Password Generator", "/tools/all/password-generator"],
      ["Browser Fingerprint Viewer", "/tools/all/browser-fingerprint-visualizer"],
      ["Cookie Viewer", "/tools/all/cookie-viewer"],
    ],
  },
  {
    slug: "authenticator",
    productId: "authenticator",
    name: "AltF Authenticator",
    eyebrow: "Private local TOTP",
    description: "Generate time-based verification codes locally without storing or transmitting the shared secret.",
    status: "working",
    privacy: "Secrets are held in memory only and never sent to a server",
    capabilities: ["RFC-compatible TOTP", "30-second countdown", "Backup-code generator"],
    relatedTools: [
      ["Password Generator", "/tools/all/password-generator"],
      ["Password Strength Checker", "/tools/all/password-strength-checker"],
      ["Text Encryptor", "/tools/all/text-encryptor"],
      ["QR Generator", "/tools/all/qr-generator"],
    ],
  },
  {
    slug: "netcheck",
    productId: "net-check",
    name: "AltF NetCheck",
    eyebrow: "Fast, bounded network diagnostics",
    description: "Measure latency, jitter, download, and upload performance using small cost-controlled test payloads.",
    status: "working",
    privacy: "No browsing history or file content is collected",
    capabilities: ["Latency and jitter", "Bounded speed test", "Connection quality summary"],
    relatedTools: [
      ["Internet Speed Test", "/tools/all/internet-speed-test"],
      ["Web Speed Checker", "/tools/all/web-speed-checker"],
      ["User Info Finder", "/tools/all/user-info-finder"],
    ],
  },
  {
    slug: "career",
    productId: "career",
    name: "AltF Career",
    eyebrow: "Plan, apply, and improve",
    description: "A focused workspace for resumes, interviews, skill demand, compensation, and application materials.",
    status: "working",
    privacy: "Individual tools explain when data stays local or uses an API",
    capabilities: ["Resume and cover letter", "Interview preparation", "Salary and skill research"],
    relatedTools: [
      ["Resume Maker", "/tools/all/resume-maker"],
      ["Cover Letter Builder", "/tools/all/cover-letter"],
      ["Interview Questions", "/tools/all/interview-question"],
      ["Skill Demand Analyzer", "/tools/all/skill-demand-analyzer"],
      ["Salary Calculator", "/tools/all/salary-in-hand-calculator"],
    ],
  },
  {
    slug: "creator",
    productId: "creator",
    name: "AltF Creator",
    eyebrow: "A practical publishing toolkit",
    description: "Move from recording to captions, thumbnails, video optimization, and channel research in one workspace.",
    status: "working",
    privacy: "Media tools disclose local and remote processing before use",
    capabilities: ["Capture and edit", "Caption and thumbnail", "Channel research"],
    relatedTools: [
      ["Screen Recorder", "/tools/all/screen-recorder"],
      ["Subtitle Timing", "/tools/all/subtitle-timing-adjuster"],
      ["Video Compressor", "/tools/all/video-compressor"],
      ["Thumbnail Downloader", "/tools/all/youtube-thumbnail-downloader"],
      ["YouTube Analyzer", "/tools/all/youtube-video-analyzer"],
    ],
  },
  {
    slug: "flow",
    productId: "flow",
    name: "AltF Flow",
    eyebrow: "Local workflow automation",
    description: "Build and run repeatable text and data transformations with ordered actions, logs, and saved recipes.",
    status: "beta",
    privacy: "Current workflows execute entirely in your browser",
    capabilities: ["Ordered actions", "Reusable recipes", "Execution log"],
    relatedTools: [
      ["Bulk Text Replacer", "/tools/all/bulk-text-replacer"],
      ["JSON Editor", "/tools/all/json-editor"],
      ["Cron Generator", "/tools/all/cron-expression-generator"],
      ["cURL to Code", "/tools/all/curl-to-code-converter"],
    ],
  },
  {
    slug: "impact",
    productId: "impact",
    name: "AltF Impact",
    eyebrow: "Trusted public-service starting points",
    description: "Choose a country edition and find official benefits, skills, education, and startup resources without eligibility guesswork.",
    status: "beta",
    privacy: "No eligibility or identity information is collected",
    capabilities: ["Country editions", "Official sources", "Source and freshness labels"],
    relatedTools: [
      ["Salary Calculator", "/tools/all/salary-in-hand-calculator"],
      ["Attendance Calculator", "/tools/all/attendance-calculator"],
      ["Resume Maker", "/tools/all/resume-maker"],
    ],
  },
  {
    slug: "campus",
    productId: "campus",
    name: "AltF Campus",
    eyebrow: "Student work, organized",
    description: "A student toolkit for citations, attendance, grades, study material, quizzes, and document workflows.",
    status: "working",
    privacy: "Tool-level privacy labels apply",
    capabilities: ["Academic planning", "Study tools", "Document workflows"],
    relatedTools: [
      ["Citation Generator", "/tools/all/citation-generator"],
      ["Attendance Calculator", "/tools/all/attendance-calculator"],
      ["Final Grade Calculator", "/tools/all/final-grade-calculator"],
      ["Quiz Builder", "/tools/all/quiz-app"],
      ["PDF Summarizer", "/tools/all/pdf-summarizer"],
    ],
  },
  {
    slug: "developers",
    productId: "api-widgets",
    name: "AltF API & Widgets",
    eyebrow: "Build on AltFTool",
    description: "Explore public read APIs, test responses, and launch developer utilities from a documented workspace.",
    status: "working",
    privacy: "API requests follow the privacy policy of each endpoint",
    capabilities: ["Live API tester", "Copyable examples", "Developer utilities"],
    relatedTools: [
      ["API Tester", "/tools/all/api-tester"],
      ["API Documentation Maker", "/tools/all/api-documentation-maker"],
      ["API Stress Estimator", "/tools/all/api-stress-estimator"],
      ["JSON Editor", "/tools/all/json-editor"],
    ],
  },
  {
    slug: "vault",
    productId: "vault",
    name: "AltF Vault",
    eyebrow: "Security review required",
    description: "The password vault remains intentionally unavailable until its cryptography, recovery, telemetry, and extension model pass independent review.",
    status: "gated",
    privacy: "No password storage is active",
    capabilities: ["Threat model", "Independent audit gate", "Safe password utilities"],
    relatedTools: [
      ["Password Generator", "/tools/all/password-generator"],
      ["Password Strength Checker", "/tools/all/password-strength-checker"],
      ["Text Encryptor", "/tools/all/text-encryptor"],
    ],
  },
]);

export function getProductSuiteBySlug(slug) {
  return PRODUCT_SUITE_CATALOG.find((suite) => suite.slug === slug) || null;
}

export function getProductSuiteByProductId(productId) {
  return PRODUCT_SUITE_CATALOG.find((suite) => suite.productId === productId) || null;
}
