const seo = {
  title: "Is This MAC Address Randomised? U/L and I/G Bits",
  metaDescription:
    "Paste any MAC address to read the U/L and I/G flag bits: a private Wi-Fi address always has 2, 6, A or E as its second hex digit. Nothing is sent.",
  steps: [
    "Paste a MAC address into the MAC address box — colon, hyphen, Cisco dotted or bare hex all work — or tap one of the example chips such as 3A:2F:19:8C:41:0D.",
    "The page reads the U/L bit (0x02) and I/G bit (0x01) of the first octet, per IEEE Std 802-2014, to say whether the address came from an IEEE manufacturer block or was made up locally.",
    "Read the Verdict headline and what it means, including which router rules a rotating address breaks — DHCP reservations, MAC allow-lists, per-device schedules — then press Copy result.",
  ],
  intro:
    "This explainer classifies any MAC address by reading the two flag bits IEEE Std 802-2014 defines in the first octet: the U/L bit (0x02) says whether the address was assigned from an IEEE manufacturer block or made up locally, and the I/G bit (0x01) says whether it addresses one interface or a group. Because operating systems build private Wi-Fi addresses by setting U/L and clearing I/G, a randomised address always has 2, 6, A or E as its second hex digit — which the page shows alongside the router features a rotating address breaks. Useful to anyone puzzled by unfamiliar devices in a router list or by parental controls that quietly stopped applying.",
  useCases: [
    "Working out whether an unknown entry in the router's device list is a neighbour's laptop or your own phone with a fresh private address.",
    "Diagnosing a DHCP reservation, QoS rule or parental control that stopped applying after a phone update.",
    "Explaining to a household why MAC filtering is not a security control before someone spends an evening configuring one.",
    "Deciding which networks deserve a fixed private address and which should keep rotating for tracking resistance.",
  ],
  benefits: [
    ["Reads the actual standard", "Classification comes from the U/L and I/G bits, not from guesswork about vendor prefixes."],
    ["Format tolerant", "Colon, hyphen, Cisco dotted-quad and bare hex are all accepted and normalised."],
    ["Nothing leaves the page", "No OUI lookup, no logging — the address you paste is analysed in the browser only."],
  ],
  faqs: [
    [
      "How do I know if a MAC address is randomised?",
      "Check the second hex digit: a private Wi-Fi address generated by an operating system is unicast and locally administered, which forces that digit to 2, 6, A or E. So 3A:2F:19:8C:41:0D is randomised, while AC:DE:48:00:11:22 comes from an IEEE-assigned manufacturer block. It is a strong signal rather than proof, because any address can be spoofed manually.",
    ],
    [
      "Why does my phone show a different MAC address on each Wi-Fi network?",
      "iOS 14 and later, and Android 10 and later, generate a separate randomised address per network by default so shops, airports and other venues cannot link your visits across locations into one profile. The address normally stays the same for a given network, unless you enable a rotating option or forget and rejoin the network.",
    ],
    [
      "Does MAC randomisation break my router's parental controls or DHCP reservations?",
      "Yes, whenever a rule is keyed on the address. Static DHCP reservations, MAC allow-lists, per-device schedules, bandwidth limits and presence automations all stop matching once the device presents a new address, which usually looks like the feature failing. The fix is to set that one network to use a fixed or hardware address on the device, rather than turning randomisation off everywhere.",
    ],
    [
      "Should I turn MAC randomisation off?",
      "Leave it on for public and guest networks, where it is doing real work against passive tracking, and consider a fixed private address only for your own home network if you rely on per-device rules. Turning it off globally gives every venue you visit a permanent identifier for your device.",
    ],
  ],
};

export default seo;
