export const RATES_UPDATED = "Rates compiled for FY 2025-26";

export const STATES = [
  {
    id: "maharashtra",
    name: "Maharashtra",
    hasRural: true,
    duty: { male: 6, female: 5, joint: 5.5 },
    ruralDuty: { male: 4, female: 3, joint: 3.5 },
    commercialDuty: { male: 6, female: 6, joint: 6 },
    extras: [],
    registration: { rate: 1, cap: 30000 },
    note: "Municipal corporation areas (Mumbai, Pune, Thane, Nagpur, Nashik) pay 5% stamp duty plus a 1% metro cess. Women buyers get a 1% concession on residential property held in a woman's name — the concession does not apply to commercial property, and the flat cannot be resold to a male buyer within 15 years without paying back the difference. Registration is 1% capped at ₹30,000.",
  },
  {
    id: "delhi",
    name: "Delhi (NCT)",
    hasRural: false,
    duty: { male: 6, female: 4, joint: 5 },
    commercialDuty: { male: 6, female: 6, joint: 6 },
    extras: [],
    registration: { rate: 1, cap: null },
    note: "One of the widest gender gaps in the country — 6% for men, 4% for women, 5% for joint male-female ownership. Registration is 1% of the consideration with no cap, plus a ₹100 pasting charge. Properties inside NDMC limits are charged slightly differently.",
  },
  {
    id: "karnataka",
    name: "Karnataka",
    hasRural: true,
    dutyMode: "slab",
    slabs: [
      { upTo: 2000000, rate: 2, label: "Up to ₹20 lakh" },
      { upTo: 4500000, rate: 3, label: "₹20 lakh to ₹45 lakh" },
      { upTo: Infinity, rate: 5, label: "Above ₹45 lakh" },
    ],
    duty: { male: 5, female: 5, joint: 5 },
    ruralDuty: { male: 5, female: 5, joint: 5 },
    extras: [
      { label: "Cess (10% of stamp duty)", ofDuty: 0.1 },
      { label: "Surcharge (2% of stamp duty, urban)", ofDuty: 0.02, urbanOnly: true },
      { label: "Surcharge (3% of stamp duty, rural)", ofDuty: 0.03, ruralOnly: true },
    ],
    registration: { rate: 1, cap: null },
    note: "Slab-based: 2% below ₹20 lakh, 3% for ₹20-45 lakh, 5% above ₹45 lakh — the rate applies to the whole value, not just the amount above the slab. Cess and surcharge are charged on the stamp duty itself, not the property value, which pushes the effective rate to about 6.6% in BBMP areas. Karnataka gives no gender concession.",
  },
  {
    id: "tamil-nadu",
    name: "Tamil Nadu",
    hasRural: false,
    duty: { male: 7, female: 7, joint: 7 },
    extras: [],
    registration: { rate: 4, cap: null },
    note: "Among the costliest in India at a flat 11% all-in, driven by an unusually high 4% registration fee. No gender concession and no urban/rural split — the same rate applies to every buyer.",
  },
  {
    id: "uttar-pradesh",
    name: "Uttar Pradesh",
    hasRural: false,
    duty: { male: 7, female: 6, joint: 6.5 },
    extras: [],
    registration: { rate: 1, cap: 30000 },
    womenConcessionCap: 10000,
    note: "The women's 1% rebate only applies to the first ₹10 lakh of the consideration, so the maximum a woman can save is ₹10,000 no matter how expensive the property is. Registration is 1% capped at ₹30,000.",
  },
  {
    id: "gujarat",
    name: "Gujarat",
    hasRural: false,
    duty: { male: 4.9, female: 4.9, joint: 4.9 },
    extras: [],
    registration: { rate: 1, cap: null, femaleRate: 0 },
    note: "Basic stamp duty is 3.5% plus a 40% surcharge on the basic duty, which is why the headline figure is 4.9%. Gujarat's concession works differently from most states: women pay the same stamp duty but are fully exempt from the 1% registration fee when the property is in a woman's sole name.",
  },
  {
    id: "rajasthan",
    name: "Rajasthan",
    hasRural: false,
    duty: { male: 6, female: 5, joint: 5.5 },
    extras: [{ label: "Labour cess (20% of stamp duty)", ofDuty: 0.2 }],
    registration: { rate: 1, cap: null },
    note: "A 20% labour cess is charged on the stamp duty amount, which most online quotes leave out — it takes the effective duty from 6% to about 7.2% for men. Women get a 1% concession on the base duty.",
  },
  {
    id: "west-bengal",
    name: "West Bengal",
    hasRural: true,
    duty: { male: 6, female: 6, joint: 6 },
    ruralDuty: { male: 5, female: 5, joint: 5 },
    highValue: { threshold: 10000000, urban: 7, rural: 6 },
    extras: [],
    registration: { rate: 1, cap: null },
    note: "Rates step up above ₹1 crore — 7% in urban areas and 6% in rural areas instead of 6%/5%. The 2% pandemic-era rebate ended in June 2024 and has not been extended. No gender concession.",
  },
  {
    id: "telangana",
    name: "Telangana",
    hasRural: false,
    duty: { male: 4, female: 4, joint: 4 },
    extras: [{ label: "Transfer duty (1.5% of value)", ofValue: 0.015 }],
    registration: { rate: 0.5, cap: null },
    note: "Telangana splits the cost three ways: 4% stamp duty, 1.5% transfer duty, and 0.5% registration — 6% all in. No gender concession. Duty is charged on the higher of the agreement value or the government market value.",
  },
  {
    id: "andhra-pradesh",
    name: "Andhra Pradesh",
    hasRural: false,
    duty: { male: 5, female: 5, joint: 5 },
    extras: [{ label: "Transfer duty (1.5% of value)", ofValue: 0.015 }],
    registration: { rate: 1, cap: null },
    note: "Same three-part structure as Telangana but higher: 5% stamp duty, 1.5% transfer duty, 1% registration — 7.5% all in. No gender concession.",
  },
  {
    id: "haryana",
    name: "Haryana",
    hasRural: true,
    duty: { male: 7, female: 5, joint: 6 },
    ruralDuty: { male: 5, female: 3, joint: 4 },
    extras: [],
    registration: { rate: 1, cap: 50000 },
    note: "Both a gender concession and an urban/rural split, and they stack — a woman buying in a rural area pays 3% against a man's 7% in a municipal area. Registration is capped at ₹50,000.",
  },
  {
    id: "punjab",
    name: "Punjab",
    hasRural: false,
    duty: { male: 7, female: 5, joint: 6 },
    extras: [],
    registration: { rate: 1, cap: 200000 },
    note: "A full 2% concession for women — one of the largest gender gaps after Delhi and Haryana. Registration is 1% capped at ₹2 lakh, so the cap only bites on properties above ₹2 crore.",
  },
  {
    id: "madhya-pradesh",
    name: "Madhya Pradesh",
    hasRural: false,
    duty: { male: 7.5, female: 6.5, joint: 7 },
    extras: [],
    registration: { rate: 3, cap: null },
    note: "The 7.5% headline bundles the base stamp duty with municipal and janpad duties. A 3% registration fee on top makes MP one of the more expensive states at 10.5% for men.",
  },
  {
    id: "kerala",
    name: "Kerala",
    hasRural: false,
    duty: { male: 8, female: 8, joint: 8 },
    extras: [],
    registration: { rate: 2, cap: null },
    note: "The highest headline stamp duty in the country at 8%, with 2% registration on top — 10% all in. No gender concession and no urban/rural split.",
  },
  {
    id: "bihar",
    name: "Bihar",
    hasRural: false,
    duty: { male: 6, female: 6, joint: 6 },
    extras: [],
    registration: { rate: 2, cap: null },
    note: "Bihar's gender rule is unusual and depends on the seller, not just the buyer: a man buying from a woman pays 5.7%, a woman buying from a man pays 6.3%, and same-gender transfers pay 6%. This estimate uses the 6% same-gender figure — confirm your case with the sub-registrar.",
  },
  {
    id: "odisha",
    name: "Odisha",
    hasRural: false,
    duty: { male: 5, female: 4, joint: 4.5 },
    extras: [],
    registration: { rate: 2, cap: null },
    note: "A 1% concession for women on stamp duty, plus a flat 2% registration fee with no cap.",
  },
  {
    id: "jharkhand",
    name: "Jharkhand",
    hasRural: false,
    duty: { male: 4, female: 4, joint: 4 },
    extras: [],
    registration: { rate: 3, cap: null },
    note: "Low stamp duty at 4% but a steep 3% registration fee. The ₹1 token registration scheme for women buying property up to ₹50 lakh was withdrawn and is no longer available.",
  },
  {
    id: "chhattisgarh",
    name: "Chhattisgarh",
    hasRural: false,
    duty: { male: 5, female: 4, joint: 4.5 },
    extras: [],
    registration: { rate: 4, cap: null },
    note: "A 1% women's concession on stamp duty, but the 4% registration fee is one of the highest in India and applies regardless of gender.",
  },
  {
    id: "assam",
    name: "Assam",
    hasRural: false,
    duty: { male: 6, female: 5, joint: 5.5 },
    extras: [],
    registration: { rate: 8.5, cap: null },
    note: "Assam's registration fee is exceptionally high — commonly published at 8.5%, far above every other state. Because this figure is so far out of line with the rest of the country, confirm the current fee with the sub-registrar before budgeting.",
  },
  {
    id: "goa",
    name: "Goa",
    hasRural: false,
    dutyMode: "slab",
    slabs: [
      { upTo: 5000000, rate: 3.5, label: "Up to ₹50 lakh" },
      { upTo: 7500000, rate: 4, label: "₹50 lakh to ₹75 lakh" },
      { upTo: 10000000, rate: 4.5, label: "₹75 lakh to ₹1 crore" },
      { upTo: Infinity, rate: 5, label: "Above ₹1 crore" },
    ],
    duty: { male: 5, female: 5, joint: 5 },
    extras: [],
    registration: { rate: 3, cap: null },
    note: "Slab-based duty that climbs from 3.5% to 5% with the property value, and a flat 3% registration fee. No gender concession.",
  },
  {
    id: "uttarakhand",
    name: "Uttarakhand",
    hasRural: false,
    duty: { male: 5, female: 3.75, joint: 4.4 },
    extras: [],
    registration: { rate: 2, cap: null },
    note: "Women get a 1.25% concession, but only on the first ₹25 lakh of the property value — above that the standard 5% applies to the excess.",
  },
  {
    id: "himachal-pradesh",
    name: "Himachal Pradesh",
    hasRural: false,
    duty: { male: 5, female: 4, joint: 4.5 },
    extras: [],
    registration: { rate: 2, cap: null },
    note: "A 1% women's concession on stamp duty and a flat 2% registration fee.",
  },
  {
    id: "chandigarh",
    name: "Chandigarh (UT)",
    hasRural: false,
    duty: { male: 6, female: 4, joint: 5 },
    extras: [],
    registration: { rate: 1, cap: null },
    note: "Follows a Delhi-style structure — 6% for men, 4% for women, 5% joint, plus 1% registration.",
  },
];

export const PROPERTY_TYPES = [
  { id: "residential", label: "Residential" },
  { id: "commercial", label: "Commercial" },
];

export const OWNERS = [
  { id: "male", label: "Male" },
  { id: "female", label: "Female" },
  { id: "joint", label: "Joint (male + female)" },
];
