export const airports = [
  { city: "New York", code: "JFK", airport: "John F. Kennedy International" },
  { city: "New York", code: "LGA", airport: "LaGuardia Airport" },
  { city: "Newark", code: "EWR", airport: "Newark Liberty International" },
  { city: "Los Angeles", code: "LAX", airport: "Los Angeles International" },
  { city: "Chicago", code: "ORD", airport: "O'Hare International" },
  { city: "Dallas", code: "DFW", airport: "Dallas Fort Worth International" },
  { city: "Miami", code: "MIA", airport: "Miami International" },
  { city: "Atlanta", code: "ATL", airport: "Hartsfield-Jackson Atlanta International" },
  { city: "San Francisco", code: "SFO", airport: "San Francisco International" },
  { city: "Seattle", code: "SEA", airport: "Seattle-Tacoma International" },
  { city: "Boston", code: "BOS", airport: "Boston Logan International" },
  { city: "Denver", code: "DEN", airport: "Denver International" },
  { city: "Las Vegas", code: "LAS", airport: "Harry Reid International" },
  { city: "Orlando", code: "MCO", airport: "Orlando International" },
  { city: "Phoenix", code: "PHX", airport: "Phoenix Sky Harbor International" },
  { city: "Houston", code: "IAH", airport: "George Bush Intercontinental" },
  { city: "Philadelphia", code: "PHL", airport: "Philadelphia International" },
  { city: "Charlotte", code: "CLT", airport: "Charlotte Douglas International" },
  { city: "Detroit", code: "DTW", airport: "Detroit Metropolitan Wayne County" },
  { city: "Minneapolis", code: "MSP", airport: "Minneapolis-Saint Paul International" },
  { city: "Delhi", code: "DEL", airport: "Indira Gandhi International" },
  { city: "Mumbai", code: "BOM", airport: "Chhatrapati Shivaji Maharaj International" },
  { city: "Bengaluru", code: "BLR", airport: "Kempegowda International" },
  { city: "Chennai", code: "MAA", airport: "Chennai International" },
  { city: "Hyderabad", code: "HYD", airport: "Rajiv Gandhi International" },
  { city: "Kolkata", code: "CCU", airport: "Netaji Subhas Chandra Bose International" },
  { city: "Goa", code: "GOI", airport: "Dabolim Airport" },
  { city: "Jaipur", code: "JAI", airport: "Jaipur International" },
  { city: "Kathmandu", code: "KTM", airport: "Tribhuvan International" },
  { city: "Dubai", code: "DXB", airport: "Dubai International" },
  { city: "Singapore", code: "SIN", airport: "Singapore Changi" },
  { city: "Bangkok", code: "BKK", airport: "Suvarnabhumi Airport" },
  { city: "Tokyo", code: "HND", airport: "Tokyo Haneda" },
  { city: "Seoul", code: "ICN", airport: "Incheon International" },
  { city: "Hong Kong", code: "HKG", airport: "Hong Kong International" },
  { city: "London", code: "LHR", airport: "London Heathrow" },
  { city: "Paris", code: "CDG", airport: "Paris Charles de Gaulle" },
  { city: "Frankfurt", code: "FRA", airport: "Frankfurt Airport" },
  { city: "Amsterdam", code: "AMS", airport: "Amsterdam Schiphol" },
  { city: "Rome", code: "FCO", airport: "Rome Fiumicino" },
  { city: "Zurich", code: "ZRH", airport: "Zurich Airport" },
  { city: "Sydney", code: "SYD", airport: "Sydney Kingsford Smith" },
  { city: "Melbourne", code: "MEL", airport: "Melbourne Airport" },
  { city: "Toronto", code: "YYZ", airport: "Toronto Pearson International" },
  { city: "Vancouver", code: "YVR", airport: "Vancouver International" },
];
