"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Download, FileJson, Image as ImageIcon, Loader2 } from "lucide-react";
import { canvasToBlob, downloadBlob } from "../utils/helpers";

export default function DownloadDialog({ open, onClose, imageA, imageB, result }) {
  const [busy, setBusy] = useState(null);

  const handleDownloadImage = async () => {
    if (!imageA || !imageB || !result) return;
    setBusy("image");
    try {
      const canvas = document.createElement("canvas");
      canvas.width = 800;
      canvas.height = 600;
      const ctx = canvas.getContext("2d");

      ctx.fillStyle = "#0B1220";
      ctx.fillRect(0, 0, 800, 600);

      ctx.fillStyle = "#101827";
      ctx.beginPath();
      ctx.roundRect(20, 20, 760, 560, 16);
      ctx.fill();

      const loadImage = (src) =>
        new Promise((resolve) => {
          const img = new Image();
          img.crossOrigin = "anonymous";
          img.onload = () => resolve(img);
          img.src = src;
        });

      const imgA = await loadImage(imageA);
      const imgB = await loadImage(imageB);

      const imgW = 280;
      const imgH = 210;
      ctx.drawImage(imgA, 60, 80, imgW, imgH);
      ctx.drawImage(imgB, 460, 80, imgW, imgH);

      ctx.fillStyle = "#14B8A6";
      ctx.font = "bold 24px sans-serif";
      ctx.textAlign = "center";
      ctx.fillText(`Similarity: ${result.percentage}%`, 400, 350);

      ctx.fillStyle = "#94A3B8";
      ctx.font = "14px sans-serif";
      ctx.textAlign = "center";
      ctx.fillText(result.insights, 400, 390);

      ctx.fillStyle = "#607083";
      ctx.font = "12px sans-serif";
      ctx.textAlign = "center";
      ctx.fillText("Generated by ALTFTool Twin Finder", 400, 560);

      const blob = await canvasToBlob(canvas);
      const ts = new Date().toISOString().slice(0, 10);
      downloadBlob(blob, `twin-finder-${ts}.png`);
    } catch {
      /* silent */
    } finally {
      setBusy(null);
    }
  };

  const handleDownloadJson = () => {
    if (!result) return;
    setBusy("json");
    try {
      const data = {
        tool: "Twin Finder",
        version: "1.0",
        generatedAt: new Date().toISOString(),
        result: {
          percentage: result.percentage,
          insights: result.insights,
          funFact: result.funFact,
        },
      };
      const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
      const ts = new Date().toISOString().slice(0, 10);
      downloadBlob(blob, `twin-finder-${ts}.json`);
    } catch {
      /* silent */
    } finally {
      setBusy(null);
    }
  };

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4 backdrop-blur-sm"
          onClick={onClose}
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            transition={{ duration: 0.2 }}
            onClick={(e) => e.stopPropagation()}
            className="w-full max-w-md rounded-2xl border border-(--border) bg-(--card) p-6 shadow-lg"
          >
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-bold text-(--foreground)">Download</h2>
              <button
                onClick={onClose}
                aria-label="Close dialog"
                className="rounded-lg p-1.5 min-w-11 min-h-11 inline-flex items-center justify-center text-(--muted-foreground) transition hover:bg-(--muted) hover:text-(--foreground) focus-visible:outline-none focus-visible:ring-[3px] focus-visible:ring-(--primary)/35"
              >
                <X size={18} />
              </button>
            </div>

            <p className="mt-2 text-sm text-(--muted-foreground)">
              Download your comparison result as an image or JSON data.
            </p>

            <div className="mt-6 space-y-3">
              <button
                onClick={handleDownloadImage}
                disabled={busy !== null}
                className="flex w-full items-center justify-center gap-2 rounded-xl bg-(--primary) px-4 py-3 text-sm font-semibold text-(--primary-foreground) transition hover:opacity-90 active:scale-[0.98] motion-reduce:active:scale-100 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-[3px] focus-visible:ring-(--primary)/35"
              >
                {busy === "image" ? (
                  <Loader2 size={16} className="animate-spin" />
                ) : (
                  <ImageIcon size={16} alt="" />
                )}
                Download as Image (PNG)
              </button>

              <button
                onClick={handleDownloadJson}
                disabled={busy !== null}
                className="flex w-full items-center justify-center gap-2 rounded-xl border border-(--border) px-4 py-3 text-sm font-semibold text-(--foreground) transition hover:bg-(--muted) active:scale-[0.98] motion-reduce:active:scale-100 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-[3px] focus-visible:ring-(--primary)/35"
              >
                {busy === "json" ? (
                  <Loader2 size={16} className="animate-spin" />
                ) : (
                  <FileJson size={16} />
                )}
                Download as JSON
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
