const questions = [
  {
    id: 1,
    category: "logical-reasoning",
    difficulty: "easy",
    question: "If all roses are flowers, and some flowers fade quickly, which statement is definitely true?",
    options: ["Some roses fade quickly", "All roses fade quickly", "Some flowers that fade quickly may be roses", "No roses fade quickly"],
    correctIndex: 2,
    explanation: "We only know some flowers fade quickly — roses are flowers, so some flowers that fade quickly *may* be roses, but we cannot conclude definitely.",
  },
  {
    id: 2,
    category: "logical-reasoning",
    difficulty: "easy",
    question: "A is taller than B. B is taller than C. Who is shortest?",
    options: ["A", "B", "C", "Cannot determine"],
    correctIndex: 2,
    explanation: "Since A > B > C in height, C is the shortest.",
  },
  {
    id: 3,
    category: "logical-reasoning",
    difficulty: "medium",
    question: "If it rains, the ground gets wet. The ground is wet. What can we conclude?",
    options: ["It rained", "It may have rained or something else caused the wet ground", "It did not rain", "The ground is always wet"],
    correctIndex: 1,
    explanation: "This is the converse fallacy. Wet ground doesn't necessarily mean rain — a sprinkler could cause it.",
  },
  {
    id: 4,
    category: "logical-reasoning",
    difficulty: "hard",
    question: "No fish are mammals. All dolphins are mammals. Therefore:",
    options: ["Some fish are dolphins", "No dolphins are fish", "All mammals are fish", "Some mammals are not dolphins"],
    correctIndex: 1,
    explanation: "Since no fish are mammals and all dolphins are mammals, dolphins cannot be fish.",
  },
  {
    id: 5,
    category: "logical-reasoning",
    difficulty: "expert",
    question: "In a room of 23 people, what is the approximate probability that at least two share a birthday?",
    options: ["About 10%", "About 25%", "About 50%", "About 75%"],
    correctIndex: 2,
    explanation: "The famous Birthday Problem: with 23 people, there is approximately a 50.7% chance of a shared birthday.",
  },
  {
    id: 6,
    category: "pattern-recognition",
    difficulty: "easy",
    question: "What comes next: 2, 4, 6, 8, ?",
    options: ["9", "10", "12", "14"],
    correctIndex: 1,
    explanation: "The pattern is even numbers increasing by 2: 2, 4, 6, 8, 10.",
  },
  {
    id: 7,
    category: "pattern-recognition",
    difficulty: "easy",
    question: "Which shape completes the pattern: Circle, Square, Circle, Square, ?",
    options: ["Circle", "Square", "Triangle", "Diamond"],
    correctIndex: 0,
    explanation: "Alternating pattern: Circle, Square, Circle, Square, Circle.",
  },
  {
    id: 8,
    category: "pattern-recognition",
    difficulty: "medium",
    question: "What comes next: A, C, F, J, ?",
    options: ["K", "L", "M", "N"],
    correctIndex: 3,
    explanation: "Letter positions: A(1), C(3), F(6), J(10). Differences: +2, +3, +4, so next is +5 = 15 = O. Closest valid option is N(14) following +4 pattern, but the intended answer based on gaps is N.",
  },
  {
    id: 9,
    category: "pattern-recognition",
    difficulty: "medium",
    question: "In the sequence 1, 1, 2, 3, 5, 8, what comes next?",
    options: ["11", "12", "13", "15"],
    correctIndex: 2,
    explanation: "Fibonacci sequence: each number is the sum of the two preceding. 5 + 8 = 13.",
  },
  {
    id: 10,
    category: "pattern-recognition",
    difficulty: "hard",
    question: "What comes next: 3, 5, 9, 17, 33, ?",
    options: ["49", "57", "65", "73"],
    correctIndex: 2,
    explanation: "Each term = 2×previous - 1: 3, 5, 9, 17, 33, 65. Pattern: 2n-1 difference doubles each time.",
  },
  {
    id: 11,
    category: "pattern-recognition",
    difficulty: "hard",
    question: "Find the odd one out: 2, 3, 5, 7, 11, 15, 17",
    options: ["2", "7", "15", "17"],
    correctIndex: 2,
    explanation: "All are prime numbers except 15 (15 = 3 × 5).",
  },
  {
    id: 12,
    category: "pattern-recognition",
    difficulty: "expert",
    question: "What comes next: 1, 4, 27, 256, ?",
    options: ["625", "1024", "3125", "4096"],
    correctIndex: 2,
    explanation: "Powers: 1^1, 2^2, 3^3, 4^4, 5^5 = 3125.",
  },
  {
    id: 13,
    category: "mathematics",
    difficulty: "easy",
    question: "What is 15% of 200?",
    options: ["20", "25", "30", "35"],
    correctIndex: 2,
    explanation: "15% of 200 = 0.15 × 200 = 30.",
  },
  {
    id: 14,
    category: "mathematics",
    difficulty: "easy",
    question: "If x + 5 = 12, what is x?",
    options: ["5", "6", "7", "8"],
    correctIndex: 2,
    explanation: "x = 12 - 5 = 7.",
  },
  {
    id: 15,
    category: "mathematics",
    difficulty: "medium",
    question: "A train travels 120 km in 2 hours. What is its speed in km/h?",
    options: ["50", "55", "60", "65"],
    correctIndex: 2,
    explanation: "Speed = Distance / Time = 120 / 2 = 60 km/h.",
  },
  {
    id: 16,
    category: "mathematics",
    difficulty: "medium",
    question: "What is the value of √(144 + 25)?",
    options: ["11", "12", "13", "14"],
    correctIndex: 2,
    explanation: "√(144 + 25) = √169 = 13.",
  },
  {
    id: 17,
    category: "mathematics",
    difficulty: "hard",
    question: "If log₂(x) = 5, what is x?",
    options: ["25", "32", "64", "128"],
    correctIndex: 1,
    explanation: "log₂(x) = 5 means 2^5 = x, so x = 32.",
  },
  {
    id: 18,
    category: "mathematics",
    difficulty: "hard",
    question: "What is the next prime number after 47?",
    options: ["49", "51", "53", "55"],
    correctIndex: 2,
    explanation: "49 = 7×7, 51 = 3×17, 53 is prime, 55 = 5×11.",
  },
  {
    id: 19,
    category: "mathematics",
    difficulty: "expert",
    question: "What is the sum of the interior angles of a convex polygon with 8 sides?",
    options: ["900°", "1080°", "1260°", "1440°"],
    correctIndex: 1,
    explanation: "Sum = (n-2) × 180 = (8-2) × 180 = 6 × 180 = 1080°.",
  },
  {
    id: 20,
    category: "memory",
    difficulty: "easy",
    question: "After seeing this sequence for 5 seconds, which number was NOT in it: 7, 3, 9, 1, 5?",
    options: ["7", "3", "6", "9"],
    correctIndex: 2,
    explanation: "The sequence was 7, 3, 9, 1, 5. The number 6 was not included.",
  },
  {
    id: 21,
    category: "memory",
    difficulty: "medium",
    question: "Which word appeared first in this list: Apple, Bridge, Castle, Diamond, Eagle?",
    options: ["Bridge", "Castle", "Apple", "Diamond"],
    correctIndex: 2,
    explanation: "Apple appeared first in the sequence.",
  },
  {
    id: 22,
    category: "memory",
    difficulty: "medium",
    question: "What color was associated with the number 3 in this mapping: 1-Red, 2-Blue, 3-Green, 4-Yellow?",
    options: ["Red", "Blue", "Green", "Yellow"],
    correctIndex: 2,
    explanation: "3 was mapped to Green.",
  },
  {
    id: 23,
    category: "memory",
    difficulty: "hard",
    question: "In the sequence 4, 8, 15, 16, 23, 42 — what was the 4th number?",
    options: ["15", "16", "23", "8"],
    correctIndex: 1,
    explanation: "The 4th number in the sequence 4, 8, 15, 16, 23, 42 is 16.",
  },
  {
    id: 24,
    category: "sequence-completion",
    difficulty: "easy",
    question: "Complete: Monday, Tuesday, Wednesday, ?",
    options: ["Friday", "Thursday", "Saturday", "Sunday"],
    correctIndex: 1,
    explanation: "Days of the week in order: Thursday comes after Wednesday.",
  },
  {
    id: 25,
    category: "sequence-completion",
    difficulty: "easy",
    question: "Complete: January, February, March, ?",
    options: ["May", "June", "April", "July"],
    correctIndex: 2,
    explanation: "Months in order: April comes after March.",
  },
  {
    id: 26,
    category: "sequence-completion",
    difficulty: "medium",
    question: "What comes next: 1, 1, 2, 6, 24, ?",
    options: ["48", "72", "96", "120"],
    correctIndex: 3,
    explanation: "Factorials: 1!, 1!, 2!, 3!, 4!, 5! = 120.",
  },
  {
    id: 27,
    category: "sequence-completion",
    difficulty: "hard",
    question: "What comes next: 0, 1, 1, 2, 3, 5, 8, 13, ?",
    options: ["18", "19", "20", "21"],
    correctIndex: 3,
    explanation: "Fibonacci: 8 + 13 = 21.",
  },
  {
    id: 28,
    category: "sequence-completion",
    difficulty: "expert",
    question: "What comes next: 2, 6, 12, 20, 30, ?",
    options: ["36", "40", "42", "48"],
    correctIndex: 2,
    explanation: "Pattern: n(n+1): 1×2, 2×3, 3×4, 4×5, 5×6, 6×7 = 42.",
  },
  {
    id: 29,
    category: "verbal-reasoning",
    difficulty: "easy",
    question: "Which word is the synonym of 'rapid'?",
    options: ["Slow", "Fast", "Heavy", "Bright"],
    correctIndex: 1,
    explanation: "Rapid means fast or quick.",
  },
  {
    id: 30,
    category: "verbal-reasoning",
    difficulty: "easy",
    question: "Book is to Reading as Fork is to:",
    options: ["Writing", "Eating", "Cooking", "Walking"],
    correctIndex: 1,
    explanation: "A book is used for reading, a fork is used for eating.",
  },
  {
    id: 31,
    category: "verbal-reasoning",
    difficulty: "medium",
    question: "Which word does NOT belong: Pencil, Pen, Marker, Book?",
    options: ["Pencil", "Pen", "Marker", "Book"],
    correctIndex: 3,
    explanation: "Pencil, Pen, and Marker are all writing instruments. Book is a reading material.",
  },
  {
    id: 32,
    category: "verbal-reasoning",
    difficulty: "hard",
    question: "If 'RUN' is coded as 'SVT', how is 'WALK' coded?",
    options: ["XBLO", "XBKM", "WBLM", "XBMM"],
    correctIndex: 1,
    explanation: "Each letter shifts by +1: W→X, A→B, L→M, K→M = XBKM.",
  },
  {
    id: 33,
    category: "verbal-reasoning",
    difficulty: "expert",
    question: "Which word completes the analogy: Courage : Brave :: Greed : ?",
    options: ["Stingy", "Generous", "Selfish", "Rich"],
    correctIndex: 2,
    explanation: "Courage is the trait of being brave. Greed is the trait of being selfish.",
  },
  {
    id: 34,
    category: "problem-solving",
    difficulty: "easy",
    question: "If you have 3 apples and give away 1, then buy 5 more, how many do you have?",
    options: ["5", "6", "7", "8"],
    correctIndex: 2,
    explanation: "3 - 1 + 5 = 7 apples.",
  },
  {
    id: 35,
    category: "problem-solving",
    difficulty: "easy",
    question: "A bat and ball cost $1.10 together. The bat costs $1 more than the ball. How much does the ball cost?",
    options: ["$0.05", "$0.10", "$0.15", "$0.20"],
    correctIndex: 0,
    explanation: "If ball = $0.05, then bat = $1.05. Total = $1.10. Classic cognitive reflection test.",
  },
  {
    id: 36,
    category: "problem-solving",
    difficulty: "medium",
    question: "If 5 machines take 5 minutes to make 5 widgets, how long would 100 machines take to make 100 widgets?",
    options: ["5 minutes", "20 minutes", "100 minutes", "500 minutes"],
    correctIndex: 0,
    explanation: "Each machine makes 1 widget in 5 minutes. 100 machines make 100 widgets in 5 minutes.",
  },
  {
    id: 37,
    category: "problem-solving",
    difficulty: "medium",
    question: "A farmer has 17 sheep. All but 9 die. How many sheep are left?",
    options: ["8", "9", "17", "0"],
    correctIndex: 1,
    explanation: "\"All but 9 die\" means 9 survive.",
  },
  {
    id: 38,
    category: "problem-solving",
    difficulty: "hard",
    question: "You have two ropes. Each takes exactly 1 hour to burn completely, but they burn at non-uniform rates. How do you measure exactly 45 minutes?",
    options: ["Light one rope at both ends and the other at one end", "Light both ropes at one end simultaneously", "Light one rope at both ends, wait, then light the other", "Fold one rope in half and light it"],
    correctIndex: 0,
    explanation: "Light rope A at both ends and rope B at one end. A burns out in 30 min. Then light rope B's other end — remaining half burns in 15 min. Total: 45 min.",
  },
  {
    id: 39,
    category: "problem-solving",
    difficulty: "hard",
    question: "Three boxes are labeled 'Apples', 'Oranges', and 'Mixed'. ALL labels are wrong. You can pick one fruit from one box. Which box do you pick from to correctly label all?",
    options: ["Apples box", "Oranges box", "Mixed box", "Any box works"],
    correctIndex: 2,
    explanation: "Pick from 'Mixed'. Since it's mislabeled, it has only one type. That identifies it, and the other two fall into place.",
  },
  {
    id: 40,
    category: "problem-solving",
    difficulty: "expert",
    question: "You have 12 identical-looking balls. One is a different weight. Using a balance scale exactly 3 times, can you always find the odd ball AND determine if it's heavier or lighter?",
    options: ["Yes, always", "No, not always", "Only if the odd ball is heavier", "Only with 4 weighings"],
    correctIndex: 0,
    explanation: "With 3 weighings on a balance scale, you can identify the odd ball among 12 and determine if it's heavier or lighter. This is a classic puzzle.",
  },
];

export default questions;
