"use client";

import { useMemo, useState } from "react";
import { Check, Copy, Grid3x3, RotateCcw } from "lucide-react";

const INPUT_CLASS = "h-11 w-full rounded-md border border-[var(--border)] bg-[var(--background)] px-3 text-[var(--foreground)] focus:border-[var(--primary)] focus:ring-[3px] focus:ring-[var(--primary)]/25 focus:outline-none";
const PRIMARY_BTN = "inline-flex min-h-11 items-center justify-center gap-2 rounded-md bg-[var(--primary)] px-4 text-sm font-semibold text-[var(--primary-foreground)]";
const GHOST_BTN = "inline-flex min-h-11 items-center justify-center gap-2 rounded-md border border-[var(--border)] bg-[var(--background)] px-4 text-sm font-semibold text-[var(--foreground)]";
export default function ToolHome() {
  const [spacing, setSpacing] = useState("24"); const [dot, setDot] = useState("2"); const [opacity, setOpacity] = useState("0.22"); const [copied, setCopied] = useState(false);
  const css = useMemo(() => `background-image: radial-gradient(circle, color-mix(in srgb, var(--primary) ${Number(opacity) * 100}%, transparent) ${dot}px, transparent ${Number(dot) + 0.5}px);\nbackground-size: ${spacing}px ${spacing}px;`, [spacing, dot, opacity]);
  const copy = async () => { try { await navigator.clipboard.writeText(css); setCopied(true); setTimeout(() => setCopied(false), 1500); } catch { setCopied(false); } };
  return <main className="mx-auto w-full max-w-3xl px-4 py-8 text-[var(--foreground)] sm:px-6"><header className="mb-6"><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-[var(--muted)] px-3 py-1 text-xs font-semibold uppercase tracking-wide text-[var(--primary)]"><Grid3x3 className="h-4 w-4" aria-hidden="true" />CSS pattern</div><h1 className="text-3xl font-semibold leading-tight sm:text-4xl">Dot Grid Background Generator</h1><p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">Generate a semantic-token dot grid background with CSS export.</p></header><section className="rounded-xl bg-[var(--card)] p-5 ring-1 ring-[var(--border)]"><div className="grid gap-4 sm:grid-cols-3">{[["Spacing px", spacing, setSpacing], ["Dot px", dot, setDot], ["Opacity", opacity, setOpacity]].map(([label, value, setter]) => <div key={label}><label className="block text-sm font-semibold" htmlFor={`dot-${label}`}>{label}</label><input id={`dot-${label}`} className={`mt-2 ${INPUT_CLASS}`} type="number" step="0.01" value={value} onChange={(event) => setter(event.target.value)} /></div>)}</div></section><section className="mt-6 rounded-xl bg-[var(--card)] p-5 ring-1 ring-[var(--border)]"><div className="h-56 rounded-lg bg-[var(--background)] ring-1 ring-[var(--border)]" style={{ backgroundImage: `radial-gradient(circle, color-mix(in srgb, var(--primary) ${Number(opacity) * 100}%, transparent) ${dot}px, transparent ${Number(dot) + 0.5}px)`, backgroundSize: `${spacing}px ${spacing}px` }} /><pre className="mt-4 rounded-lg bg-[var(--surface-soft)] p-4 text-sm">{css}</pre><div className="mt-5 flex flex-wrap gap-2"><button className={GHOST_BTN} type="button" onClick={() => { setSpacing("24"); setDot("2"); setOpacity("0.22"); }}><RotateCcw className="h-4 w-4" aria-hidden="true" />Reset</button><button className={PRIMARY_BTN} type="button" onClick={copy}>{copied ? <Check className="h-4 w-4" aria-hidden="true" /> : <Copy className="h-4 w-4" aria-hidden="true" />}{copied ? "Copied" : "Copy CSS"}</button></div></section></main>;
}
