/**
 * Image usage rights explainer.
 *
 * Pure module: no DOM, no React, no clock, no randomness. The same answers
 * always produce the same checklist.
 *
 * This is an informational decision aid, not legal advice. It applies the
 * general structure of copyright, licence terms, personality rights and
 * trademark law, and flags where a lawyer or the rights holder has to be
 * involved. Specific outcomes vary by country and by the exact wording of the
 * licence you hold.
 *
 * Rules referenced:
 *  - Copyright subsists in a photograph from creation; using it needs the
 *    owner's permission unless a licence or a statutory exception applies.
 *  - Indian Copyright Act 1957, s.52(1)(s) and s.52(1)(t): a painting, drawing
 *    or photograph of a work of architecture, or of a sculpture or other
 *    artistic work permanently situated in a public place, is not an
 *    infringement. Freedom of panorama is narrower or absent in many other
 *    countries.
 *  - Indian Copyright Act 1957, s.57: the author keeps moral rights, including
 *    the right to object to distortion or mutilation, even after assigning
 *    the copyright.
 *  - Creative Commons 4.0: NC forbids commercial use, ND forbids sharing
 *    adaptations, SA requires adaptations under the same licence, and BY
 *    requires attribution in every case.
 *  - Personality and publicity rights are separate from copyright, so a public
 *    domain photograph of a recognisable person still needs a model release
 *    for advertising use.
 */

/** Where the image came from. */
export const SOURCES = {
  ownShot: {
    id: "ownShot",
    label: "I shot or created it myself",
    holdsCopyright: true,
    needsLicenceDocument: false,
    note: "You own the copyright, but the people and property in the frame have rights of their own.",
  },
  employeeOrCommission: {
    id: "employeeOrCommission",
    label: "Shot by an employee or a commissioned photographer",
    holdsCopyright: "check",
    needsLicenceDocument: true,
    note: "Ownership turns on the contract. Without a written assignment the photographer often keeps the copyright.",
  },
  stockRoyaltyFree: {
    id: "stockRoyaltyFree",
    label: "Royalty-free stock licence",
    holdsCopyright: false,
    needsLicenceDocument: true,
    note: "Broad but not unlimited: standard RF licences exclude resale items and usually cap print runs.",
  },
  stockRightsManaged: {
    id: "stockRightsManaged",
    label: "Rights-managed stock licence",
    holdsCopyright: false,
    needsLicenceDocument: true,
    note: "Licensed for a named use, medium, territory and period. Anything outside that grant needs a new licence.",
  },
  ccPermissive: {
    id: "ccPermissive",
    label: "Creative Commons BY or BY-SA",
    holdsCopyright: false,
    needsLicenceDocument: false,
    note: "Commercial use allowed. Attribution is mandatory, and BY-SA requires adaptations under the same licence.",
  },
  ccNonCommercial: {
    id: "ccNonCommercial",
    label: "Creative Commons with NC",
    holdsCopyright: false,
    needsLicenceDocument: false,
    note: "Non-commercial only. Any use primarily aimed at commercial advantage is outside the licence.",
  },
  ccNoDerivatives: {
    id: "ccNoDerivatives",
    label: "Creative Commons with ND",
    holdsCopyright: false,
    needsLicenceDocument: false,
    note: "You may share it unchanged. You may not publish a cropped, filtered or composited version.",
  },
  publicDomain: {
    id: "publicDomain",
    label: "Public domain or CC0",
    holdsCopyright: true,
    needsLicenceDocument: false,
    note: "No copyright to clear. Personality, privacy and trademark rights are unaffected and still apply.",
  },
  clientSupplied: {
    id: "clientSupplied",
    label: "Supplied by a client or a third party",
    holdsCopyright: "check",
    needsLicenceDocument: true,
    note: "Get the chain of rights in writing. Being handed a file is not the same as being licensed to publish it.",
  },
  aiGenerated: {
    id: "aiGenerated",
    label: "Generated by an AI image model",
    holdsCopyright: "check",
    needsLicenceDocument: true,
    note: "Your rights come from the generator's terms, not from copyright: purely machine-made output generally has no human author to own it.",
  },
  webFound: {
    id: "webFound",
    label: "Found online with no licence",
    holdsCopyright: false,
    needsLicenceDocument: true,
    note: "No permission of any kind. A credit line, a reverse image search or a takedown policy is not a licence.",
  },
};

/** What you plan to do with it. */
export const USES = {
  editorial: {
    id: "editorial",
    label: "Editorial — news, reporting or commentary",
    commercial: false,
    resale: false,
    note: "Illustrating a story about the subject, not selling anything.",
  },
  educational: {
    id: "educational",
    label: "Education or internal training material",
    commercial: false,
    resale: false,
    note: "Classroom, coursework or an internal deck that is never sold.",
  },
  organicSocial: {
    id: "organicSocial",
    label: "Brand website or organic social post",
    commercial: true,
    resale: false,
    note: "Promoting an organisation counts as commercial even when nobody pays for the placement.",
  },
  paidAdvertising: {
    id: "paidAdvertising",
    label: "Paid advertising campaign",
    commercial: true,
    resale: false,
    note: "The strictest ordinary use: media spend, endorsement risk and usually the largest audience.",
  },
  packaging: {
    id: "packaging",
    label: "Product packaging or a book cover",
    commercial: true,
    resale: false,
    note: "The image helps sell the object it is printed on, which most licences treat separately.",
  },
  merchandise: {
    id: "merchandise",
    label: "Merchandise or print on demand for resale",
    commercial: true,
    resale: true,
    note: "The image is the product. Standard stock licences exclude this outright.",
  },
  trainingData: {
    id: "trainingData",
    label: "Training or fine-tuning an AI model",
    commercial: true,
    resale: false,
    note: "A distinct and contested use. Almost no ordinary licence grants it by default.",
  },
};

/** Who is in the frame. */
export const PEOPLE_OPTIONS = {
  none: { id: "none", label: "No people, or nobody identifiable" },
  crowd: { id: "crowd", label: "People in a public crowd, not the subject" },
  recognisable: { id: "recognisable", label: "One or more recognisable people" },
  minor: { id: "minor", label: "A recognisable child under 18" },
};

/** What else is in the frame. */
export const PROPERTY_OPTIONS = {
  none: { id: "none", label: "Nothing distinctive" },
  privateProperty: { id: "privateProperty", label: "Recognisable private property or interiors" },
  publicArtwork: { id: "publicArtwork", label: "A sculpture or building permanently in a public place" },
  indoorArtwork: { id: "indoorArtwork", label: "Someone else's artwork, indoors or not permanent" },
  trademark: { id: "trademark", label: "A visible logo, brand or trade dress" },
};

/** Statuses a checklist item can carry, ordered by severity. */
export const STATUS_ORDER = ["blocker", "required", "recommended", "ok", "na"];

const STATUS_LABELS = {
  blocker: "Stop",
  required: "Must clear",
  recommended: "Worth doing",
  ok: "Covered",
  na: "Not applicable",
};

/**
 * Assess a planned image use and return an ordered checklist plus a verdict.
 */
export function assessImageUse({
  sourceId = "ownShot",
  useId = "editorial",
  people = "none",
  property = "none",
  willModify = false,
  hasWrittenPermission = false,
} = {}) {
  const source = SOURCES[sourceId];
  const use = USES[useId];
  const peopleOption = PEOPLE_OPTIONS[people];
  const propertyOption = PROPERTY_OPTIONS[property];

  if (!source) return { error: "Choose where the image came from." };
  if (!use) return { error: "Choose what you plan to do with the image." };
  if (!peopleOption) return { error: "Choose who appears in the image." };
  if (!propertyOption) return { error: "Choose what else appears in the image." };
  if (typeof willModify !== "boolean") return { error: "Say whether you will modify the image." };
  if (typeof hasWrittenPermission !== "boolean") {
    return { error: "Say whether you hold written permission." };
  }

  const items = [];
  const add = (id, title, status, detail) => items.push({ id, title, status, detail });

  // 1. The underlying copyright.
  if (source.id === "webFound" && !hasWrittenPermission) {
    add(
      "copyright",
      "Permission from the copyright owner",
      "blocker",
      "An image found online carries no licence. Find the owner and get written permission, buy a stock licence, or use a different image. Crediting the source does not create a licence.",
    );
  } else if (source.holdsCopyright === true) {
    add(
      "copyright",
      "Permission from the copyright owner",
      "ok",
      source.id === "publicDomain"
        ? "No copyright remains to clear. Confirm the public domain status for your own country — terms differ, and a modern scan or restoration can carry its own rights."
        : "You are the author, so the copyright is yours.",
    );
  } else if (source.holdsCopyright === "check" && !hasWrittenPermission) {
    add(
      "copyright",
      "Written proof of the chain of rights",
      "required",
      source.id === "aiGenerated"
        ? "Read the generator's terms: they, not copyright law, decide what you may do with the output. Purely machine-made images generally have no human author, so there may be nothing for anyone to own or to stop others copying."
        : "Get a signed assignment or licence. Possession of a file, an invoice, or a verbal agreement is not proof that you may publish it.",
    );
  } else {
    add(
      "copyright",
      "Permission from the copyright owner",
      "ok",
      hasWrittenPermission
        ? "You hold written permission. Keep it filed with the artwork so the grant can be checked later."
        : "The licence covers your right to copy and publish the image, within its own limits.",
    );
  }

  // 2. Licence scope against the intended use.
  if (source.id === "ccNonCommercial" && use.commercial) {
    add(
      "licence-scope",
      "Commercial use under an NC licence",
      "blocker",
      "The NC term forbids use primarily intended for commercial advantage. Promoting a business is commercial even if the post is unpaid. You need a separate licence from the creator.",
    );
  } else if (source.id === "ccNoDerivatives" && willModify) {
    add(
      "licence-scope",
      "Modifying an ND-licensed image",
      "blocker",
      "The ND term lets you share the image unchanged but not publish an adapted version. Cropping, colour grading and compositing all produce an adaptation.",
    );
  } else if (source.id === "stockRoyaltyFree" && use.resale) {
    add(
      "licence-scope",
      "Extended or merchandise licence",
      "required",
      "Standard royalty-free licences exclude items where the image is what is being sold — prints, phone cases, t-shirts, templates. Buy the extended or merchandise licence the agency offers.",
    );
  } else if (source.id === "stockRightsManaged") {
    add(
      "licence-scope",
      "Use inside the rights-managed grant",
      "required",
      "Check the licence covers this exact medium, territory, print run and time period. A rights-managed grant does not roll over to a new campaign.",
    );
  } else if (use.id === "trainingData") {
    add(
      "licence-scope",
      "Explicit permission to train on the image",
      "required",
      "Training rights are a separate grant. Most stock, Creative Commons and commission agreements say nothing about it, and silence is not consent. Get it in writing.",
    );
  } else if (source.id === "ccPermissive" || source.id === "ccNonCommercial" || source.id === "ccNoDerivatives") {
    add(
      "licence-scope",
      "Licence covers this use",
      "ok",
      "The Creative Commons terms allow what you have described. Check the exact version on the original page — the licence, not a summary, is what binds you.",
    );
  } else {
    add("licence-scope", "Licence covers this use", "ok", "Nothing in this use falls outside the usual scope of the licence you described.");
  }

  // 3. Attribution.
  if (source.id === "ccPermissive" || source.id === "ccNonCommercial" || source.id === "ccNoDerivatives") {
    add(
      "attribution",
      "Attribution in the required form",
      "required",
      "Every current Creative Commons licence includes BY. Name the creator, the title, the source link and the licence with a link, and say if you changed it.",
    );
  } else if (source.id === "publicDomain") {
    add(
      "attribution",
      "Credit the source",
      "recommended",
      "Not legally required for a public domain work, but crediting the archive or photographer is good practice and helps the next person verify the status.",
    );
  } else {
    add(
      "attribution",
      "Credit line",
      source.id === "stockRightsManaged" || source.id === "stockRoyaltyFree" ? "recommended" : "na",
      source.id === "stockRightsManaged" || source.id === "stockRoyaltyFree"
        ? "Many agencies require a credit for editorial use and waive it for advertising. Check your agreement."
        : "No attribution obligation applies to this source.",
    );
  }

  // 4. Moral rights and modification.
  if (willModify) {
    add(
      "moral-rights",
      "Moral rights of the author",
      source.holdsCopyright === true && source.id !== "publicDomain" ? "na" : "recommended",
      source.holdsCopyright === true && source.id !== "publicDomain"
        ? "You are the author, so there is nobody else's integrity right to consider."
        : "Under Indian law the author keeps the right to object to distortion or mutilation of the work even after assigning copyright (Copyright Act 1957, s.57). Avoid edits that change the meaning or hold the author up to ridicule.",
    );
  }

  // 5. People in the frame.
  if (peopleOption.id === "none") {
    add("model-release", "Model release", "na", "Nobody identifiable appears, so there is no personality right to clear.");
  } else if (peopleOption.id === "minor") {
    add(
      "model-release",
      "Model release signed by a parent or guardian",
      use.commercial ? "blocker" : "required",
      use.commercial
        ? "Commercial use of a recognisable child needs a release signed by a parent or legal guardian, and many platforms and broadcasters add their own rules on top. Do not proceed on an unsigned image."
        : "Even for editorial use, get guardian consent for an identifiable child, and consider whether publication is in the child's interest at all.",
    );
  } else if (peopleOption.id === "recognisable" && use.commercial) {
    add(
      "model-release",
      "Signed model release",
      "required",
      "Using someone's likeness to promote a product or a brand engages their personality and publicity rights, which sit outside copyright entirely. A release is needed even if you own the photograph or it is in the public domain.",
    );
  } else if (peopleOption.id === "recognisable") {
    add(
      "model-release",
      "Model release",
      "recommended",
      "Genuine editorial use of a recognisable person generally does not need a release, but privacy and defamation still apply. Take extra care with health, religion, caste, sexuality or anything else sensitive.",
    );
  } else {
    add(
      "model-release",
      "Model release for crowd shots",
      use.commercial ? "recommended" : "na",
      use.commercial
        ? "Incidental people in a public crowd are usually acceptable, but if any single face is prominent enough to be identified as endorsing the brand, get a release or blur them."
        : "Incidental crowd members in an editorial context do not need releases.",
    );
  }

  // 6. Property, artwork and trademarks in the frame.
  if (propertyOption.id === "privateProperty") {
    add(
      "property-release",
      "Property release",
      use.commercial ? "required" : "recommended",
      use.commercial
        ? "Recognisable private homes, interiors and identifiable possessions normally need the owner's written release for advertising and packaging use."
        : "Editorial use of private property is usually acceptable, but check you were lawfully present and that no privacy expectation is being breached.",
    );
  } else if (propertyOption.id === "publicArtwork") {
    add(
      "property-release",
      "Freedom of panorama check",
      "recommended",
      "Indian law permits photographs of architecture and of sculptures permanently situated in a public place (Copyright Act 1957, s.52(1)(s) and (t)). Many countries are far narrower — France, Italy and Greece among them — so check the country the work stands in and the countries you will publish in.",
    );
  } else if (propertyOption.id === "indoorArtwork") {
    add(
      "property-release",
      "Licence from the artwork's copyright owner",
      use.commercial ? "blocker" : "required",
      "A photograph of someone else's painting, poster, mural or non-permanent installation reproduces that work too. You need the artist's permission separately from any licence covering the photograph.",
    );
  } else if (propertyOption.id === "trademark") {
    add(
      "trademark",
      "Trademark clearance",
      use.commercial ? "required" : "recommended",
      use.commercial
        ? "Trademark law bites when the use suggests an association, sponsorship or endorsement that does not exist. Either clear it with the brand owner or remove the mark from the frame."
        : "Incidental appearance of a logo in genuine reporting is normally fine. Avoid using the mark as decoration or as a headline element.",
    );
  } else {
    add("property-release", "Property or trademark clearance", "na", "Nothing distinctive enough in the frame to clear.");
  }

  // 7. Sensitive context.
  if (use.commercial && (peopleOption.id === "recognisable" || peopleOption.id === "minor")) {
    add(
      "sensitive-use",
      "Sensitive-subject restriction",
      "recommended",
      "Almost every licence and release forbids using a person's image with subjects such as illness, addiction, crime or sexual content without a specific disclaimer and, usually, a specific consent.",
    );
  }

  const counts = STATUS_ORDER.reduce((acc, status) => {
    acc[status] = items.filter((item) => item.status === status).length;
    return acc;
  }, {});

  const blockers = items.filter((item) => item.status === "blocker");
  const required = items.filter((item) => item.status === "required");

  let verdict;
  let verdictDetail;
  if (blockers.length > 0) {
    verdict = "Not permitted as described";
    verdictDetail = `${blockers.length} ${blockers.length === 1 ? "issue stops" : "issues stop"} this use outright. Change the image, the licence, or the plan.`;
  } else if (required.length > 0) {
    verdict = "Permitted once you clear the conditions";
    verdictDetail = `${required.length} ${required.length === 1 ? "item has" : "items have"} to be cleared in writing before you publish.`;
  } else {
    verdict = "No blockers found for this use";
    verdictDetail = "Nothing in your answers requires a clearance. Keep records of the licence and any consent anyway.";
  }

  const sortedItems = [...items].sort(
    (a, b) => STATUS_ORDER.indexOf(a.status) - STATUS_ORDER.indexOf(b.status),
  );

  return {
    sourceId: source.id,
    sourceLabel: source.label,
    sourceNote: source.note,
    useId: use.id,
    useLabel: use.label,
    useNote: use.note,
    commercial: use.commercial,
    resale: use.resale,
    peopleLabel: peopleOption.label,
    propertyLabel: propertyOption.label,
    willModify,
    hasWrittenPermission,
    items: sortedItems,
    counts,
    statusLabels: STATUS_LABELS,
    blockerCount: blockers.length,
    requiredCount: required.length,
    verdict,
    verdictDetail,
  };
}

/** Plain-text version of the checklist, for pasting into a brief or a ticket. */
export function formatAssessment(result) {
  if (!result || result.error) return "";
  return [
    "Image usage rights check",
    `Source: ${result.sourceLabel}`,
    `Planned use: ${result.useLabel}${result.commercial ? " (commercial)" : " (non-commercial)"}`,
    `People in frame: ${result.peopleLabel}`,
    `Other content: ${result.propertyLabel}`,
    `Will be modified: ${result.willModify ? "yes" : "no"}`,
    "",
    `Verdict: ${result.verdict}`,
    result.verdictDetail,
    "",
    ...result.items.map(
      (item) => `[${result.statusLabels[item.status]}] ${item.title}\n    ${item.detail}`,
    ),
    "",
    "Informational only. This is not legal advice — confirm anything commercially significant with a lawyer in the relevant jurisdiction.",
  ].join("\n");
}
