/*
 * AltF Backlinks — catalogue access (server only)
 *
 * Data is generated by scripts/import-backlinks.mjs from a maintained Google
 * Sheet. The sheet keeps growing, so nothing here hardcodes a value the sheet
 * happens to contain today; groups, costs and statuses all come from the
 * normalised import.
 *
 * Filtering happens on the server against URL params rather than in the
 * browser. The catalogue is ~385KB, which is too much to ship for an instant
 * filter, and every filter combination being a real URL is what makes the
 * facets crawlable instead of invisible to search and answer engines.
 */

import { readFile } from "node:fs/promises";
import path from "node:path";

const DATA_DIR = path.join(process.cwd(), "public", "data", "backlinks");
const cache = new Map();

async function load(file) {
  if (cache.has(file)) return cache.get(file);
  const promise = readFile(path.join(DATA_DIR, file), "utf8")
    .then(JSON.parse)
    .catch((error) => {
      cache.delete(file);
      throw new Error(
        `AltF Backlinks data missing "${file}". Run "npm run import:backlinks" first. (${error.message})`,
      );
    });
  cache.set(file, promise);
  return promise;
}

export const getManifest = () => load("manifest.json");
export const getAllItems = () => load("items.json");

/* Presentation metadata. Kept beside the data rather than in the page so the
   listing, the detail page and the category hubs cannot disagree. */
export const COST_LABELS = Object.freeze({
  free: "Free",
  freemium: "Free + paid tier",
  paid: "Paid",
  unknown: "Not stated",
});

export const STATUS_LABELS = Object.freeze({
  verified: "Verified live",
  conditional: "Live, conditional",
  unverified: "Needs checking",
  todo: "Not submitted",
});

export const EFFORT_LABELS = Object.freeze({
  low: "Quick",
  medium: "Moderate",
  high: "Involved",
});

export const PRIORITY_LABELS = Object.freeze({
  P0: "Do first",
  P1: "High",
  P2: "Medium",
  P3: "Later",
});

/** Impact tiers, used for the score colour. Anchored to the priority bands the
 *  importer assigns, so a tier boundary never lands mid-band. */
export function impactTier(impact) {
  if (impact >= 90) return { id: "s", label: "Highest impact" };
  if (impact >= 75) return { id: "a", label: "High impact" };
  if (impact >= 58) return { id: "b", label: "Useful" };
  return { id: "c", label: "Long tail" };
}

export async function getItemBySlug(slug) {
  const items = await getAllItems();
  return items.find((i) => i.slug === slug) ?? null;
}

export async function getGroups() {
  const manifest = await getManifest();
  return manifest.groups;
}

export async function getGroup(id) {
  const groups = await getGroups();
  return groups.find((g) => g.id === id) ?? null;
}

const SORTS = {
  impact: (a, b) => b.impact - a.impact || a.website.localeCompare(b.website),
  name: (a, b) => a.website.localeCompare(b.website),
  effort: (a, b) => {
    const order = { low: 0, medium: 1, high: 2 };
    return order[a.effort] - order[b.effort] || b.impact - a.impact;
  },
};

/**
 * Filter and page the catalogue. Every argument is optional; unknown values are
 * ignored rather than producing an empty page, because these come straight off
 * user-editable query strings.
 */
export async function queryItems({
  group,
  cost,
  status,
  priority,
  effort,
  q,
  freeOnly,
  quickWins,
  sort = "impact",
  page = 1,
  perPage = 30,
} = {}) {
  const all = await getAllItems();
  let rows = all;

  if (group) rows = rows.filter((i) => i.group === group);
  if (cost) rows = rows.filter((i) => i.cost === cost);
  if (status) rows = rows.filter((i) => i.status === status);
  if (priority) rows = rows.filter((i) => i.priority === priority);
  if (effort) rows = rows.filter((i) => i.effort === effort);
  if (freeOnly) rows = rows.filter((i) => i.cost === "free" || i.cost === "freemium");
  if (quickWins) rows = rows.filter((i) => i.cost === "free" && i.effort === "low" && i.priority !== "P3");

  if (q) {
    const needle = String(q).toLowerCase().trim();
    if (needle) {
      rows = rows.filter(
        (i) =>
          i.website.toLowerCase().includes(needle) ||
          i.domain.toLowerCase().includes(needle) ||
          i.rawCategory.toLowerCase().includes(needle) ||
          i.rawType.toLowerCase().includes(needle),
      );
    }
  }

  const sorted = [...rows].sort(SORTS[sort] ?? SORTS.impact);
  const total = sorted.length;
  const lastPage = Math.max(1, Math.ceil(total / perPage));
  const current = Math.min(Math.max(1, page), lastPage);
  const start = (current - 1) * perPage;

  return {
    rows: sorted.slice(start, start + perPage),
    total,
    page: current,
    perPage,
    lastPage,
  };
}

/** Minimal index for client-side type-ahead: ~40KB rather than 385KB. */
export async function getSearchIndex() {
  const all = await getAllItems();
  return all.map((i) => ({ s: i.slug, w: i.website, d: i.domain, i: i.impact }));
}
