export const KAABA = { lat: 21.4225, lng: 39.8262 };

export const CITIES = [
  { id: "delhi", name: "Delhi", region: "India", lat: 28.6139, lng: 77.209, tz: "Asia/Kolkata" },
  { id: "mumbai", name: "Mumbai", region: "India", lat: 19.076, lng: 72.8777, tz: "Asia/Kolkata" },
  { id: "kolkata", name: "Kolkata", region: "India", lat: 22.5726, lng: 88.3639, tz: "Asia/Kolkata" },
  { id: "chennai", name: "Chennai", region: "India", lat: 13.0827, lng: 80.2707, tz: "Asia/Kolkata" },
  { id: "bengaluru", name: "Bengaluru", region: "India", lat: 12.9716, lng: 77.5946, tz: "Asia/Kolkata" },
  { id: "hyderabad", name: "Hyderabad", region: "India", lat: 17.385, lng: 78.4867, tz: "Asia/Kolkata" },
  { id: "ahmedabad", name: "Ahmedabad", region: "India", lat: 23.0225, lng: 72.5714, tz: "Asia/Kolkata" },
  { id: "pune", name: "Pune", region: "India", lat: 18.5204, lng: 73.8567, tz: "Asia/Kolkata" },
  { id: "surat", name: "Surat", region: "India", lat: 21.1702, lng: 72.8311, tz: "Asia/Kolkata" },
  { id: "jaipur", name: "Jaipur", region: "India", lat: 26.9124, lng: 75.7873, tz: "Asia/Kolkata" },
  { id: "lucknow", name: "Lucknow", region: "India", lat: 26.8467, lng: 80.9462, tz: "Asia/Kolkata" },
  { id: "kanpur", name: "Kanpur", region: "India", lat: 26.4499, lng: 80.3319, tz: "Asia/Kolkata" },
  { id: "nagpur", name: "Nagpur", region: "India", lat: 21.1458, lng: 79.0882, tz: "Asia/Kolkata" },
  { id: "indore", name: "Indore", region: "India", lat: 22.7196, lng: 75.8577, tz: "Asia/Kolkata" },
  { id: "bhopal", name: "Bhopal", region: "India", lat: 23.2599, lng: 77.4126, tz: "Asia/Kolkata" },
  { id: "patna", name: "Patna", region: "India", lat: 25.5941, lng: 85.1376, tz: "Asia/Kolkata" },
  { id: "ludhiana", name: "Ludhiana", region: "India", lat: 30.901, lng: 75.8573, tz: "Asia/Kolkata" },
  { id: "agra", name: "Agra", region: "India", lat: 27.1767, lng: 78.0081, tz: "Asia/Kolkata" },
  { id: "varanasi", name: "Varanasi", region: "India", lat: 25.3176, lng: 82.9739, tz: "Asia/Kolkata" },
  { id: "srinagar", name: "Srinagar", region: "India", lat: 34.0837, lng: 74.7973, tz: "Asia/Kolkata" },
  { id: "amritsar", name: "Amritsar", region: "India", lat: 31.634, lng: 74.8723, tz: "Asia/Kolkata" },
  { id: "ranchi", name: "Ranchi", region: "India", lat: 23.3441, lng: 85.3096, tz: "Asia/Kolkata" },
  { id: "guwahati", name: "Guwahati", region: "India", lat: 26.1445, lng: 91.7362, tz: "Asia/Kolkata" },
  { id: "chandigarh", name: "Chandigarh", region: "India", lat: 30.7333, lng: 76.7794, tz: "Asia/Kolkata" },
  { id: "kochi", name: "Kochi", region: "India", lat: 9.9312, lng: 76.2673, tz: "Asia/Kolkata" },
  { id: "thiruvananthapuram", name: "Thiruvananthapuram", region: "India", lat: 8.5241, lng: 76.9366, tz: "Asia/Kolkata" },
  { id: "coimbatore", name: "Coimbatore", region: "India", lat: 11.0168, lng: 76.9558, tz: "Asia/Kolkata" },
  { id: "visakhapatnam", name: "Visakhapatnam", region: "India", lat: 17.6868, lng: 83.2185, tz: "Asia/Kolkata" },
  { id: "vadodara", name: "Vadodara", region: "India", lat: 22.3072, lng: 73.1812, tz: "Asia/Kolkata" },
  { id: "nashik", name: "Nashik", region: "India", lat: 19.9975, lng: 73.7898, tz: "Asia/Kolkata" },
  { id: "aurangabad", name: "Chhatrapati Sambhajinagar", region: "India", lat: 19.8762, lng: 75.3433, tz: "Asia/Kolkata" },
  { id: "hubli", name: "Hubballi", region: "India", lat: 15.3647, lng: 75.124, tz: "Asia/Kolkata" },
  { id: "mysuru", name: "Mysuru", region: "India", lat: 12.2958, lng: 76.6394, tz: "Asia/Kolkata" },
  { id: "madurai", name: "Madurai", region: "India", lat: 9.9252, lng: 78.1198, tz: "Asia/Kolkata" },
  { id: "jodhpur", name: "Jodhpur", region: "India", lat: 26.2389, lng: 73.0243, tz: "Asia/Kolkata" },
  { id: "raipur", name: "Raipur", region: "India", lat: 21.2514, lng: 81.6296, tz: "Asia/Kolkata" },
  { id: "dehradun", name: "Dehradun", region: "India", lat: 30.3165, lng: 78.0322, tz: "Asia/Kolkata" },
  { id: "shimla", name: "Shimla", region: "India", lat: 31.1048, lng: 77.1734, tz: "Asia/Kolkata" },
  { id: "jammu", name: "Jammu", region: "India", lat: 32.7266, lng: 74.857, tz: "Asia/Kolkata" },
  { id: "bhubaneswar", name: "Bhubaneswar", region: "India", lat: 20.2961, lng: 85.8245, tz: "Asia/Kolkata" },
  { id: "aligarh", name: "Aligarh", region: "India", lat: 27.8974, lng: 78.088, tz: "Asia/Kolkata" },
  { id: "moradabad", name: "Moradabad", region: "India", lat: 28.8386, lng: 78.7733, tz: "Asia/Kolkata" },
  { id: "malappuram", name: "Malappuram", region: "India", lat: 11.051, lng: 76.0711, tz: "Asia/Kolkata" },
  { id: "bhagalpur", name: "Bhagalpur", region: "India", lat: 25.2425, lng: 86.9842, tz: "Asia/Kolkata" },
  { id: "gorakhpur", name: "Gorakhpur", region: "India", lat: 26.7606, lng: 83.3732, tz: "Asia/Kolkata" },
  { id: "hyderabad-sindh", name: "Hyderabad", region: "Pakistan", lat: 25.396, lng: 68.3578, tz: "Asia/Karachi" },
  { id: "mecca", name: "Mecca (Makkah)", region: "Saudi Arabia", lat: 21.4225, lng: 39.8262, tz: "Asia/Riyadh" },
  { id: "madinah", name: "Madinah", region: "Saudi Arabia", lat: 24.4672, lng: 39.6111, tz: "Asia/Riyadh" },
  { id: "riyadh", name: "Riyadh", region: "Saudi Arabia", lat: 24.7136, lng: 46.6753, tz: "Asia/Riyadh" },
  { id: "jeddah", name: "Jeddah", region: "Saudi Arabia", lat: 21.4858, lng: 39.1925, tz: "Asia/Riyadh" },
  { id: "dubai", name: "Dubai", region: "UAE", lat: 25.2048, lng: 55.2708, tz: "Asia/Dubai" },
  { id: "abudhabi", name: "Abu Dhabi", region: "UAE", lat: 24.4539, lng: 54.3773, tz: "Asia/Dubai" },
  { id: "sharjah", name: "Sharjah", region: "UAE", lat: 25.3463, lng: 55.4209, tz: "Asia/Dubai" },
  { id: "doha", name: "Doha", region: "Qatar", lat: 25.2854, lng: 51.531, tz: "Asia/Qatar" },
  { id: "kuwait", name: "Kuwait City", region: "Kuwait", lat: 29.3759, lng: 47.9774, tz: "Asia/Kuwait" },
  { id: "manama", name: "Manama", region: "Bahrain", lat: 26.2285, lng: 50.586, tz: "Asia/Bahrain" },
  { id: "muscat", name: "Muscat", region: "Oman", lat: 23.588, lng: 58.3829, tz: "Asia/Muscat" },
  { id: "karachi", name: "Karachi", region: "Pakistan", lat: 24.8607, lng: 67.0011, tz: "Asia/Karachi" },
  { id: "lahore", name: "Lahore", region: "Pakistan", lat: 31.5204, lng: 74.3587, tz: "Asia/Karachi" },
  { id: "islamabad", name: "Islamabad", region: "Pakistan", lat: 33.6844, lng: 73.0479, tz: "Asia/Karachi" },
  { id: "dhaka", name: "Dhaka", region: "Bangladesh", lat: 23.8103, lng: 90.4125, tz: "Asia/Dhaka" },
  { id: "chittagong", name: "Chattogram", region: "Bangladesh", lat: 22.3569, lng: 91.7832, tz: "Asia/Dhaka" },
  { id: "colombo", name: "Colombo", region: "Sri Lanka", lat: 6.9271, lng: 79.8612, tz: "Asia/Colombo" },
  { id: "kathmandu", name: "Kathmandu", region: "Nepal", lat: 27.7172, lng: 85.324, tz: "Asia/Kathmandu" },
  { id: "male", name: "Malé", region: "Maldives", lat: 4.1755, lng: 73.5093, tz: "Indian/Maldives" },
  { id: "kualalumpur", name: "Kuala Lumpur", region: "Malaysia", lat: 3.139, lng: 101.6869, tz: "Asia/Kuala_Lumpur" },
  { id: "singapore", name: "Singapore", region: "Singapore", lat: 1.3521, lng: 103.8198, tz: "Asia/Singapore" },
  { id: "jakarta", name: "Jakarta", region: "Indonesia", lat: -6.2088, lng: 106.8456, tz: "Asia/Jakarta" },
  { id: "istanbul", name: "Istanbul", region: "Türkiye", lat: 41.0082, lng: 28.9784, tz: "Europe/Istanbul" },
  { id: "cairo", name: "Cairo", region: "Egypt", lat: 30.0444, lng: 31.2357, tz: "Africa/Cairo" },
  { id: "tehran", name: "Tehran", region: "Iran", lat: 35.6892, lng: 51.389, tz: "Asia/Tehran" },
  { id: "baghdad", name: "Baghdad", region: "Iraq", lat: 33.3152, lng: 44.3661, tz: "Asia/Baghdad" },
  { id: "amman", name: "Amman", region: "Jordan", lat: 31.9454, lng: 35.9284, tz: "Asia/Amman" },
  { id: "jerusalem", name: "Jerusalem", region: "Israel / Palestine", lat: 31.7683, lng: 35.2137, tz: "Asia/Jerusalem" },
  { id: "tashkent", name: "Tashkent", region: "Uzbekistan", lat: 41.2995, lng: 69.2401, tz: "Asia/Tashkent" },
  { id: "moscow", name: "Moscow", region: "Russia", lat: 55.7558, lng: 37.6173, tz: "Europe/Moscow" },
  { id: "london", name: "London", region: "United Kingdom", lat: 51.5074, lng: -0.1278, tz: "Europe/London" },
  { id: "birmingham", name: "Birmingham", region: "United Kingdom", lat: 52.4862, lng: -1.8904, tz: "Europe/London" },
  { id: "paris", name: "Paris", region: "France", lat: 48.8566, lng: 2.3522, tz: "Europe/Paris" },
  { id: "berlin", name: "Berlin", region: "Germany", lat: 52.52, lng: 13.405, tz: "Europe/Berlin" },
  { id: "amsterdam", name: "Amsterdam", region: "Netherlands", lat: 52.3676, lng: 4.9041, tz: "Europe/Amsterdam" },
  { id: "newyork", name: "New York", region: "United States", lat: 40.7128, lng: -74.006, tz: "America/New_York" },
  { id: "chicago", name: "Chicago", region: "United States", lat: 41.8781, lng: -87.6298, tz: "America/Chicago" },
  { id: "houston", name: "Houston", region: "United States", lat: 29.7604, lng: -95.3698, tz: "America/Chicago" },
  { id: "losangeles", name: "Los Angeles", region: "United States", lat: 34.0522, lng: -118.2437, tz: "America/Los_Angeles" },
  { id: "toronto", name: "Toronto", region: "Canada", lat: 43.6532, lng: -79.3832, tz: "America/Toronto" },
  { id: "sydney", name: "Sydney", region: "Australia", lat: -33.8688, lng: 151.2093, tz: "Australia/Sydney" },
  { id: "melbourne", name: "Melbourne", region: "Australia", lat: -37.8136, lng: 144.9631, tz: "Australia/Melbourne" },
  { id: "johannesburg", name: "Johannesburg", region: "South Africa", lat: -26.2041, lng: 28.0473, tz: "Africa/Johannesburg" },
  { id: "lagos", name: "Lagos", region: "Nigeria", lat: 6.5244, lng: 3.3792, tz: "Africa/Lagos" },
  { id: "nairobi", name: "Nairobi", region: "Kenya", lat: -1.2921, lng: 36.8219, tz: "Africa/Nairobi" },
  { id: "casablanca", name: "Casablanca", region: "Morocco", lat: 33.5731, lng: -7.5898, tz: "Africa/Casablanca" },
];

export const METHODS = [
  {
    id: "mwl",
    name: "Muslim World League",
    short: "MWL",
    fajrAngle: 18,
    ishaAngle: 17,
    note: "Fajr 18° · Isha 17°. Widely used across Europe, the Far East and parts of South Asia.",
  },
  {
    id: "isna",
    name: "Islamic Society of North America",
    short: "ISNA",
    fajrAngle: 15,
    ishaAngle: 15,
    note: "Fajr 15° · Isha 15°. The common convention in North America.",
  },
  {
    id: "makkah",
    name: "Umm al-Qura, Makkah",
    short: "Umm al-Qura",
    fajrAngle: 18.5,
    ishaMinutes: 90,
    note: "Fajr 18.5° · Isha 90 minutes after Maghrib. Used in Saudi Arabia (120 minutes during Ramadan).",
  },
  {
    id: "karachi",
    name: "University of Islamic Sciences, Karachi",
    short: "Karachi",
    fajrAngle: 18,
    ishaAngle: 18,
    note: "Fajr 18° · Isha 18°. Common in Pakistan, Bangladesh, India and Afghanistan.",
  },
];

export const HIGH_LAT_RULES = [
  { id: "anglebased", name: "Angle based", note: "Twilight portion of the night is set by the Fajr/Isha angle divided by 60." },
  { id: "oneseventh", name: "One seventh", note: "Fajr starts one seventh of the night before sunrise; Isha one seventh after sunset." },
  { id: "nightmiddle", name: "Middle of the night", note: "The night is split in half; Fajr and Isha fall on either side of the midpoint." },
  { id: "none", name: "None", note: "No adjustment. Fajr or Isha may be undefined in high-latitude summers." },
];

export const PRAYER_META = [
  { id: "fajr", name: "Fajr", meaning: "Dawn — from first light until sunrise" },
  { id: "dhuhr", name: "Dhuhr", meaning: "Just after the sun passes its highest point" },
  { id: "asr", name: "Asr", meaning: "Afternoon — set by the length of an object's shadow" },
  { id: "maghrib", name: "Maghrib", meaning: "Just after sunset" },
  { id: "isha", name: "Isha", meaning: "Night — once the evening twilight has gone" },
];
