"use client";

import { safeCopyText } from "@/shared/utils/clipboard";

export function exportToJSON(report) {
  try {
    const payload = JSON.stringify(report, null, 2);
    const blob = new Blob([payload], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `ai-detection-report-${Date.now()}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    return true;
  } catch {
    return false;
  }
}

export function exportToPDF(report) {
  try {
    const w = window.open("", "_blank");
    if (!w) return false;

    const summary = report.summary || {};
    const techInfo = report.technicalInfo || {};
    const analysis = report.detailedAnalysis || {};
    const recs = report.recommendations || [];

    const analysisRows = Object.entries(analysis)
      .map(([key, val]) => {
        const name = key.charAt(0).toUpperCase() + key.slice(1);
        const scoreBar =
          val.score <= 35
            ? "bg-green-500"
            : val.score <= 55
              ? "bg-amber-500"
              : "bg-red-500";
        return `
          <tr>
            <td style="padding:10px 16px;border-bottom:1px solid #E2E8F0;font-weight:600;">${name}</td>
            <td style="padding:10px 16px;border-bottom:1px solid #E2E8F0;">
              <div style="display:flex;align-items:center;gap:10px;">
                <div style="width:120px;height:8px;background:#E2E8F0;border-radius:4px;overflow:hidden;">
                  <div style="width:${val.score}%;height:100%;border-radius:4px;" class="${scoreBar}"></div>
                </div>
                <span style="font-weight:600;">${val.score}</span>
              </div>
            </td>
            <td style="padding:10px 16px;border-bottom:1px solid #E2E8F0;">${val.confidence}%</td>
            <td style="padding:10px 16px;border-bottom:1px solid #E2E8F0;font-size:13px;color:#607083;">${val.description}</td>
          </tr>`;
      })
      .join("");

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>AI Fake Image Detection Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #111827; background: #fff; padding: 40px; }
    .header { text-align: center; margin-bottom: 32px; padding-bottom: 24px; border-bottom: 2px solid #E2E8F0; }
    .header h1 { font-size: 28px; font-weight: 700; color: #14B8A6; }
    .header p { font-size: 14px; color: #607083; margin-top: 8px; }
    .score-badge { display: inline-block; padding: 8px 24px; border-radius: 8px; font-size: 20px; font-weight: 700; margin: 16px 0; }
    .safe { background: #DCFCE7; color: #16A34A; }
    .suspicious { background: #FEF3C7; color: #D97706; }
    .risky { background: #FEE2E2; color: #EF4444; }
    .section { margin-bottom: 32px; }
    .section h2 { font-size: 18px; font-weight: 600; margin-bottom: 12px; color: #111827; }
    table { width: 100%; border-collapse: collapse; }
    th { padding: 10px 16px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #607083; background: #F7F8FB; border-bottom: 2px solid #E2E8F0; }
    .tech-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px 24px; }
    .tech-grid dt { font-size: 13px; color: #607083; }
    .tech-grid dd { font-size: 14px; font-weight: 500; }
    .recs { list-style: none; padding: 0; }
    .recs li { padding: 8px 0; border-bottom: 1px solid #F1F5F9; font-size: 14px; }
    .recs li::before { content: "\\2022"; color: #14B8A6; font-weight: 700; margin-right: 10px; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #E2E8F0; text-align: center; font-size: 12px; color: #607083; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>AI Fake Image Detection Report</h1>
    <p>Generated by ALTFTool AI Fake Image Detector</p>
    <div class="score-badge ${summary.riskLevel?.label?.includes("Authentic") ? "safe" : summary.riskLevel?.label?.includes("Possibly") ? "suspicious" : "risky"}">
      Score: ${summary.overallScore} / 100 &mdash; ${summary.riskLevel?.label || "Unknown"}
    </div>
    <p>Confidence: ${summary.confidence}%</p>
  </div>

  <div class="section">
    <h2>Summary</h2>
    <p style="font-size:14px;line-height:1.7;color:#374151;">${summary.summary}</p>
  </div>

  <div class="section">
    <h2>Technical Details</h2>
    <dl class="tech-grid">
      <dt>File Name</dt><dd>${techInfo.fileName}</dd>
      <dt>File Size</dt><dd>${(techInfo.fileSize / 1024).toFixed(1)} KB</dd>
      <dt>File Type</dt><dd>${techInfo.fileType}</dd>
      <dt>Dimensions</dt><dd>${techInfo.dimensions?.width} x ${techInfo.dimensions?.height}</dd>
      <dt>Aspect Ratio</dt><dd>${techInfo.aspectRatio}</dd>
      <dt>EXIF Data</dt><dd>${techInfo.hasExif ? "Found" : "Not Found"}</dd>
    </dl>
    ${techInfo.exifSummary ? `<p style="margin-top:12px;font-size:13px;color:#607083;">${techInfo.exifSummary}</p>` : ""}
  </div>

  <div class="section">
    <h2>Detailed Analysis</h2>
    <table>
      <thead>
        <tr><th>Check</th><th>Score</th><th>Confidence</th><th>Description</th></tr>
      </thead>
      <tbody>${analysisRows}</tbody>
    </table>
  </div>

  <div class="section">
    <h2>Recommendations</h2>
    <ul class="recs">${recs.map((r) => `<li>${r}</li>`).join("")}</ul>
  </div>

  <div class="footer">
    <p>Report generated on ${new Date().toLocaleString()}. Analysis is performed client-side and is for informational purposes only.</p>
  </div>

  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`;

    w.document.write(html);
    w.document.close();
    return true;
  } catch {
    return false;
  }
}

export async function copyReportToClipboard(report) {
  try {
    const text = formatReport(report);
    return await safeCopyText(text);
  } catch {
    return false;
  }
}

export function formatReport(report) {
  const summary = report.summary || {};
  const techInfo = report.technicalInfo || {};
  const analysis = report.detailedAnalysis || {};
  const recs = report.recommendations || [];

  const lines = [];
  lines.push("=== AI Fake Image Detection Report ===");
  lines.push(`Generated: ${new Date().toLocaleString()}`);
  lines.push("");
  lines.push(`OVERALL SCORE: ${summary.overallScore}/100`);
  lines.push(`RISK LEVEL: ${summary.riskLevel?.label || "Unknown"}`);
  lines.push(`CONFIDENCE: ${summary.confidence}%`);
  lines.push("");
  lines.push("SUMMARY:");
  lines.push(summary.summary);
  lines.push("");
  lines.push("--- Technical Details ---");
  lines.push(`File: ${techInfo.fileName}`);
  lines.push(`Size: ${(techInfo.fileSize / 1024).toFixed(1)} KB`);
  lines.push(`Type: ${techInfo.fileType}`);
  lines.push(`Dimensions: ${techInfo.dimensions?.width} x ${techInfo.dimensions?.height}`);
  lines.push(`Aspect Ratio: ${techInfo.aspectRatio}`);
  lines.push(`EXIF: ${techInfo.hasExif ? "Present" : "Not Found"}`);
  if (techInfo.exifSummary) lines.push(`EXIF Info: ${techInfo.exifSummary}`);
  lines.push("");
  lines.push("--- Detailed Analysis ---");
  for (const [key, val] of Object.entries(analysis)) {
    const name = key.charAt(0).toUpperCase() + key.slice(1);
    lines.push(`[${name}] Score: ${val.score}/100 (Confidence: ${val.confidence}%)`);
    lines.push(`  ${val.description}`);
    if (val.details && val.details.length > 0) {
      for (const d of val.details) {
        lines.push(`  - ${d}`);
      }
    }
    lines.push("");
  }
  lines.push("--- Recommendations ---");
  for (const r of recs) {
    lines.push(`- ${r}`);
  }
  lines.push("");
  lines.push("---");
  lines.push("Analysis performed client-side. For informational purposes only.");

  return lines.join("\n");
}
