export const WORDS = [
  {
    word: "ubiquitous",
    definition: "Present, appearing, or found everywhere.",
    synonyms: ["omnipresent", "everywhere", "universal"],
    example: "His ubiquitous influence was felt by all the family.",
    hint: "Starts with 'u', ends with 's', has 10 letters.",
    length: 10,
  },
  {
    word: "ephemeral",
    definition: "Lasting for a very short time.",
    synonyms: ["transitory", "transient", "fleeting"],
    example: "Fashions are ephemeral.",
    hint: "Starts with 'e', ends with 'l', has 9 letters.",
    length: 9,
  },
  {
    word: "eloquent",
    definition: "Fluent or persuasive in speaking or writing.",
    synonyms: ["fluent", "articulate", "expressive"],
    example: "An eloquent speech.",
    hint: "Starts with 'e', ends with 't', has 8 letters.",
    length: 8,
  },
  {
    word: "meticulous",
    definition: "Showing great attention to detail; very careful and precise.",
    synonyms: ["careful", "conscientious", "diligent"],
    example: "He had always been so meticulous about his appearance.",
    hint: "Starts with 'm', ends with 's', has 10 letters.",
    length: 10,
  },
  {
    word: "pragmatic",
    definition: "Dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations.",
    synonyms: ["practical", "matter-of-fact", "sensible"],
    example: "A pragmatic approach to politics.",
    hint: "Starts with 'p', ends with 'c', has 9 letters.",
    length: 9,
  },
  {
    word: "resilient",
    definition: "(of a person or animal) able to withstand or recover quickly from difficult conditions.",
    synonyms: ["strong", "tough", "hardy"],
    example: "Babies are generally far more resilient than new parents realize.",
    hint: "Starts with 'r', ends with 't', has 9 letters.",
    length: 9,
  },
  {
    word: "lucid",
    definition: "Expressed clearly; easy to understand.",
    synonyms: ["intelligible", "comprehensible", "understandable"],
    example: "A lucid account.",
    hint: "Starts with 'l', ends with 'd', has 5 letters.",
    length: 5,
  },
  {
    word: "ambiguous",
    definition: "Open to more than one interpretation; having a double meaning.",
    synonyms: ["equivocal", "ambivalent", "arguable"],
    example: "The question is rather ambiguous.",
    hint: "Starts with 'a', ends with 's', has 9 letters.",
    length: 9,
  },
  {
    word: "candid",
    definition: "Truthful and straightforward; frank.",
    synonyms: ["frank", "outspoken", "forthright"],
    example: "His responses were remarkably candid.",
    hint: "Starts with 'c', ends with 'd', has 6 letters.",
    length: 6,
  },
  {
    word: "diligent",
    definition: "Having or showing care and conscientiousness in one's work or duties.",
    synonyms: ["industrious", "hard-working", "assiduous"],
    example: "Many caves are located only after a diligent search.",
    hint: "Starts with 'd', ends with 't', has 8 letters.",
    length: 8,
  },
  {
    word: "tenacious",
    definition: "Tending to keep a firm hold of something; clinging or adhering closely.",
    synonyms: ["firm", "tight", "fast"],
    example: "A tenacious grip.",
    hint: "Starts with 't', ends with 's', has 9 letters.",
    length: 9,
  },
  {
    word: "prolific",
    definition: "Present in large numbers or quantities; plentiful.",
    synonyms: ["plentiful", "abundant", "bountiful"],
    example: "Mahogany was once prolific in the tropical forests.",
    hint: "Starts with 'p', ends with 'c', has 8 letters.",
    length: 8,
  },
  {
    word: "aesthetic",
    definition: "Concerned with beauty or the appreciation of beauty.",
    synonyms: ["artistic", "tasteful", "beautiful"],
    example: "The pictures give great aesthetic pleasure.",
    hint: "Starts with 'a', ends with 'c', has 9 letters.",
    length: 9,
  },
  {
    word: "nostalgia",
    definition: "A sentimental longing or wistful affection for the past.",
    synonyms: ["reminiscence", "remembrance", "recollection"],
    example: "I was overcome with acute nostalgia for my days in college.",
    hint: "Starts with 'n', ends with 'a', has 9 letters.",
    length: 9,
  },
  {
    word: "paradigm",
    definition: "A typical example or pattern of something; a model.",
    synonyms: ["model", "pattern", "example"],
    example: "There is a new paradigm for public art in this country.",
    hint: "Starts with 'p', ends with 'm', has 8 letters.",
    length: 8,
  },
  {
    word: "esoteric",
    definition: "Intended for or likely to be understood by only a small number of people with a specialized knowledge or interest.",
    synonyms: ["abstruse", "obscure", "arcane"],
    example: "Esoteric philosophical debates.",
    hint: "Starts with 'e', ends with 'c', has 8 letters.",
    length: 8,
  },
  {
    word: "stoic",
    definition: "A person who can endure pain or hardship without showing their feelings or complaining.",
    synonyms: ["patient", "forbearing", "accepting"],
    example: "He remained stoic despite the pain.",
    hint: "Starts with 's', ends with 'c', has 5 letters.",
    length: 5,
  },
  {
    word: "anomaly",
    definition: "Something that deviates from what is standard, normal, or expected.",
    synonyms: ["oddity", "peculiarity", "abnormality"],
    example: "There are a number of anomalies in the present system.",
    hint: "Starts with 'a', ends with 'y', has 7 letters.",
    length: 7,
  },
  {
    word: "eclectic",
    definition: "Deriving ideas, style, or taste from a broad and diverse range of sources.",
    synonyms: ["wide-ranging", "broad-based", "extensive"],
    example: "Her musical tastes are eclectic.",
    hint: "Starts with 'e', ends with 'c', has 8 letters.",
    length: 8,
  },
  {
    word: "cathartic",
    definition: "Providing psychological relief through the open expression of strong emotions.",
    synonyms: ["purging", "cleansing", "purifying"],
    example: "Crying is a cathartic release.",
    hint: "Starts with 'c', ends with 'c', has 9 letters.",
    length: 9,
  },
  {
    word: "superfluous",
    definition: "Unnecessary, especially through being more than enough.",
    synonyms: ["surplus", "redundant", "unneeded"],
    example: "The purchaser should avoid asking for superfluous information.",
    hint: "Starts with 's', ends with 's', has 11 letters.",
    length: 11,
  },
  {
    word: "cacophony",
    definition: "A harsh, discordant mixture of sounds.",
    synonyms: ["din", "racket", "noise"],
    example: "A cacophony of deafening alarm bells.",
    hint: "Starts with 'c', ends with 'y', has 9 letters.",
    length: 9,
  },
  {
    word: "serendipity",
    definition: "The occurrence and development of events by chance in a happy or beneficial way.",
    synonyms: ["chance", "happy coincidence", "fluke"],
    example: "A fortunate stroke of serendipity.",
    hint: "Starts with 's', ends with 'y', has 11 letters.",
    length: 11,
  },
  {
    word: "vindicative",
    definition: "Having or showing a strong or unreasoning desire for revenge.",
    synonyms: ["vengeful", "revengeful", "unforgiving"],
    example: "The criticism was both vindictive and personalized.",
    hint: "Starts with 'v', ends with 'e', has 11 letters.",
    length: 11,
  },
  {
    word: "cynical",
    definition: "Believing that people are motivated by self-interest; distrustful of human sincerity or integrity.",
    synonyms: ["skeptical", "doubtful", "distrustful"],
    example: "Her cynical attitude.",
    hint: "Starts with 'c', ends with 'l', has 7 letters.",
    length: 7,
  },
  {
    word: "empathy",
    definition: "The ability to understand and share the feelings of another.",
    synonyms: ["compassion", "sympathy", "understanding"],
    example: "He had a lot of empathy for his neighbor.",
    hint: "Starts with 'e', ends with 'y', has 7 letters.",
    length: 7,
  },
  {
    word: "ineffable",
    definition: "Too great or extreme to be expressed or described in words.",
    synonyms: ["inexpressible", "indescribable", "beyond words"],
    example: "The ineffable natural beauty of the Everglades.",
    hint: "Starts with 'i', ends with 'e', has 9 letters.",
    length: 9,
  },
  {
    word: "panacea",
    definition: "A solution or remedy for all difficulties or diseases.",
    synonyms: ["cure-all", "universal cure", "magic bullet"],
    example: "The panacea for all corporate ills.",
    hint: "Starts with 'p', ends with 'a', has 7 letters.",
    length: 7,
  },
  {
    word: "solitude",
    definition: "The state or situation of being alone.",
    synonyms: ["loneliness", "isolation", "seclusion"],
    example: "She savored her few hours of freedom and solitude.",
    hint: "Starts with 's', ends with 'e', has 8 letters.",
    length: 8,
  },
  {
    word: "vicarious",
    definition: "Experienced in the imagination through the feelings or actions of another person.",
    synonyms: ["indirect", "second-hand", "secondary"],
    example: "I could glean vicarious pleasure from the struggles of my imaginary film friends.",
    hint: "Starts with 'v', ends with 's', has 9 letters.",
    length: 9,
  }
];
