// Idiom data — 60 curated English idioms across categories and difficulty levels
export const IDIOMS = [
  {
    id: 1,
    idiom: "break the ice",
    meaning: "To do or say something to relieve tension or awkwardness in a social situation.",
    literalMeaning: "To literally break frozen water.",
    usage: "Used when starting a conversation or activity in a new or uncomfortable social setting.",
    origin: "Derived from the historical practice of sending ships to break ice in frozen rivers to open trade routes.",
    category: "Social",
    difficulty: "beginner",
    examples: [
      "He told a joke to break the ice at the party.",
      "The team-building exercise was designed to break the ice among new employees.",
    ],
    synonyms: ["ease the tension", "warm up", "get the ball rolling"],
    related: ["get the ball rolling", "warm up to someone"],
  },
  {
    id: 2,
    idiom: "bite the bullet",
    meaning: "To endure a painful or difficult situation with courage and determination.",
    literalMeaning: "To literally bite a bullet.",
    usage: "Used when someone must face a hard task or difficult situation.",
    origin: "From the pre-anesthetic era practice of giving soldiers a bullet to bite during surgery.",
    category: "Courage",
    difficulty: "beginner",
    examples: [
      "I hated going to the dentist, but I bit the bullet and made the appointment.",
      "She bit the bullet and asked for the raise she deserved.",
    ],
    synonyms: ["grin and bear it", "tough it out", "face the music"],
    related: ["face the music", "take the plunge"],
  },
  {
    id: 3,
    idiom: "spill the beans",
    meaning: "To reveal secret or confidential information.",
    literalMeaning: "To accidentally knock over a container of beans, scattering them.",
    usage: "Used informally when someone accidentally or intentionally reveals a secret.",
    origin: "Possibly from ancient Greek voting practices using beans.",
    category: "Communication",
    difficulty: "beginner",
    examples: [
      "Don't spill the beans about the surprise party!",
      "He couldn't keep quiet and spilled the beans to the whole office.",
    ],
    synonyms: ["let the cat out of the bag", "blab", "give away"],
    related: ["let the cat out of the bag", "blurt out"],
  },
  {
    id: 4,
    idiom: "let the cat out of the bag",
    meaning: "To accidentally reveal a secret or surprise.",
    literalMeaning: "To release a cat that was hidden in a bag.",
    usage: "Used when a secret is revealed unintentionally.",
    origin: "From medieval markets where merchants would replace a pig with a worthless cat in a bag to cheat customers.",
    category: "Communication",
    difficulty: "beginner",
    examples: [
      "She let the cat out of the bag when she mentioned the promotion.",
      "The journalist let the cat out of the bag before the official announcement.",
    ],
    synonyms: ["spill the beans", "blow the secret", "reveal"],
    related: ["spill the beans", "blow the whistle"],
  },
  {
    id: 5,
    idiom: "hit the nail on the head",
    meaning: "To describe exactly what is causing a situation or problem.",
    literalMeaning: "To strike a nail precisely on its head with a hammer.",
    usage: "Used when someone identifies or describes something accurately.",
    origin: "From carpentry — hitting a nail precisely on its head is the most effective technique.",
    category: "Accuracy",
    difficulty: "beginner",
    examples: [
      "You hit the nail on the head with your analysis.",
      "Her feedback really hit the nail on the head.",
    ],
    synonyms: ["be spot on", "get it right", "nail it"],
    related: ["get to the point", "cut to the chase"],
  },
  {
    id: 6,
    idiom: "under the weather",
    meaning: "Feeling ill or unwell.",
    literalMeaning: "To be literally below the weather.",
    usage: "A polite way to say someone is sick or not feeling well.",
    origin: "From nautical terms — sailors who were ill were sent below deck to be sheltered from the weather.",
    category: "Health",
    difficulty: "beginner",
    examples: [
      "I'm feeling a little under the weather today.",
      "She called in sick because she was under the weather.",
    ],
    synonyms: ["under the weather", "not feeling well", "sick"],
    related: ["feeling rough", "off color"],
  },
  {
    id: 7,
    idiom: "costs an arm and a leg",
    meaning: "Something that is very expensive.",
    literalMeaning: "The literal cost of losing an arm and a leg.",
    usage: "Used to describe something extremely expensive.",
    origin: "Possibly from WWII, referring to the high physical cost paid by soldiers.",
    category: "Finance",
    difficulty: "beginner",
    examples: [
      "That new smartphone costs an arm and a leg.",
      "The renovation costs an arm and a leg, but it's worth it.",
    ],
    synonyms: ["a fortune", "pricey", "expensive"],
    related: ["a pretty penny", "break the bank"],
  },
  {
    id: 8,
    idiom: "a blessing in disguise",
    meaning: "Something that seems bad at first, but turns out to be good.",
    literalMeaning: "A blessing that is hidden behind a disguise.",
    usage: "Used when a seemingly unfortunate event leads to a positive outcome.",
    origin: "From the hymn 'Since all the downward tracts of time' by James Hervey (1746).",
    category: "Perspective",
    difficulty: "intermediate",
    examples: [
      "Losing that job was a blessing in disguise; I found a much better one.",
      "The delay was a blessing in disguise because it saved us from the storm.",
    ],
    synonyms: ["silver lining", "unexpected benefit", "hidden advantage"],
    related: ["every cloud has a silver lining", "turn lemons into lemonade"],
  },
  {
    id: 9,
    idiom: "beat around the bush",
    meaning: "To avoid talking about something directly or clearly.",
    literalMeaning: "To beat around a bush instead of going straight to it.",
    usage: "Used when someone avoids the main point of a conversation.",
    origin: "From bird hunting — beaters would bang around bushes to flush out birds.",
    category: "Communication",
    difficulty: "intermediate",
    examples: [
      "Stop beating around the bush and tell me what happened.",
      "He always beats around the bush when asked difficult questions.",
    ],
    synonyms: ["hem and haw", "skirt the issue", "avoid the topic"],
    related: ["get to the point", "cut to the chase"],
  },
  {
    id: 10,
    idiom: "burn bridges",
    meaning: "To permanently damage a relationship or opportunity.",
    literalMeaning: "To literally burn a bridge, preventing return.",
    usage: "Used when someone ends a relationship or situation in a way that makes reconciliation impossible.",
    origin: "From military strategy — burning bridges prevented armies from retreating.",
    category: "Relationships",
    difficulty: "intermediate",
    examples: [
      "Don't burn bridges when you leave a job.",
      "His harsh words burned every bridge he had in the industry.",
    ],
    synonyms: ["cut ties", "sever relations", "close doors"],
    related: ["leave on bad terms", "bite the hand that feeds you"],
  },
  {
    id: 11,
    idiom: "the ball is in your court",
    meaning: "It is your turn to make a decision or take action.",
    literalMeaning: "The ball is in your section of a sports court.",
    usage: "Used when the responsibility for the next action shifts to another person.",
    origin: "From tennis, where the ball must be returned by whoever's side of the court it is on.",
    category: "Decision Making",
    difficulty: "intermediate",
    examples: [
      "I've made my offer; the ball is in your court now.",
      "After the meeting, the ball was in the client's court.",
    ],
    synonyms: ["your move", "your turn", "your decision"],
    related: ["make the call", "take the lead"],
  },
  {
    id: 12,
    idiom: "bite off more than you can chew",
    meaning: "To take on more responsibility than you can handle.",
    literalMeaning: "To put more food in your mouth than you can chew.",
    usage: "Used as a warning against overcommitting.",
    origin: "From the literal act of taking too large a bite of food.",
    category: "Work",
    difficulty: "intermediate",
    examples: [
      "He bit off more than he could chew by taking on three projects at once.",
      "Don't bite off more than you can chew when accepting new responsibilities.",
    ],
    synonyms: ["overextend", "overcommit", "take on too much"],
    related: ["spread yourself thin", "over-promise"],
  },
  {
    id: 13,
    idiom: "out of the blue",
    meaning: "Happening unexpectedly or without warning.",
    literalMeaning: "Appearing from out of a blue sky.",
    usage: "Used to describe something that happens suddenly and without prior indication.",
    origin: "From the phrase 'a bolt from the blue' — lightning from a seemingly clear sky.",
    category: "Surprise",
    difficulty: "intermediate",
    examples: [
      "Out of the blue, she called me after five years.",
      "The announcement came completely out of the blue.",
    ],
    synonyms: ["out of nowhere", "unexpectedly", "suddenly"],
    related: ["bolt from the blue", "catch off guard"],
  },
  {
    id: 14,
    idiom: "sit on the fence",
    meaning: "To remain neutral, avoiding commitment to any position.",
    literalMeaning: "To literally sit on a fence between two sides.",
    usage: "Used when someone refuses to take sides in a debate or decision.",
    origin: "From the literal image of sitting on a fence between two properties.",
    category: "Decision Making",
    difficulty: "intermediate",
    examples: [
      "Politicians often sit on the fence when controversial topics arise.",
      "Stop sitting on the fence and make a decision.",
    ],
    synonyms: ["neutral", "indecisive", "non-committal"],
    related: ["on the fence", "play both sides"],
  },
  {
    id: 15,
    idiom: "once in a blue moon",
    meaning: "Something that happens very rarely.",
    literalMeaning: "Once per blue moon — a rare astronomical event.",
    usage: "Used to describe rare occurrences.",
    origin: "From the astronomical 'blue moon' — the second full moon in a calendar month.",
    category: "Frequency",
    difficulty: "beginner",
    examples: [
      "We only see each other once in a blue moon.",
      "He visits his hometown once in a blue moon.",
    ],
    synonyms: ["rarely", "seldom", "infrequently"],
    related: ["few and far between", "not often"],
  },
  {
    id: 16,
    idiom: "add fuel to the fire",
    meaning: "To make a bad or difficult situation even worse.",
    literalMeaning: "To literally add fuel to an existing fire, making it larger.",
    usage: "Used when someone's actions escalate a problem.",
    origin: "From the literal consequence of adding combustible material to flames.",
    category: "Conflict",
    difficulty: "intermediate",
    examples: [
      "His criticism only added fuel to the fire.",
      "Don't add fuel to the fire by discussing it now.",
    ],
    synonyms: ["exacerbate", "worsen", "inflame"],
    related: ["fan the flames", "pour oil on troubled waters"],
  },
  {
    id: 17,
    idiom: "get out of hand",
    meaning: "To get out of control.",
    literalMeaning: "To escape from a person's hand or grip.",
    usage: "Used when a situation escalates beyond manageable levels.",
    origin: "From horse riding — when a horse gets out of the rider's hand (control).",
    category: "Control",
    difficulty: "intermediate",
    examples: [
      "The argument got out of hand quickly.",
      "Things got out of hand at the festival.",
    ],
    synonyms: ["out of control", "unmanageable", "chaotic"],
    related: ["get out of control", "spiral out of control"],
  },
  {
    id: 18,
    idiom: "you can't judge a book by its cover",
    meaning: "You shouldn't judge something or someone based on appearance alone.",
    literalMeaning: "You cannot determine the quality of a book just by its cover.",
    usage: "Used as a reminder not to form opinions based solely on outward appearance.",
    origin: "A common English proverb with roots in the 19th century.",
    category: "Wisdom",
    difficulty: "beginner",
    examples: [
      "Don't judge a book by its cover — get to know people before forming opinions.",
      "She looked quiet, but you can't judge a book by its cover.",
    ],
    synonyms: ["looks can be deceiving", "don't judge by appearance"],
    related: ["all that glitters is not gold", "appearances are deceiving"],
  },
  {
    id: 19,
    idiom: "pull someone's leg",
    meaning: "To joke with someone or tease them.",
    literalMeaning: "To literally pull a person's leg.",
    usage: "Used in casual conversation to indicate a joke or playful deception.",
    origin: "Possibly from thieves who tripped victims by pulling their legs to rob them.",
    category: "Humor",
    difficulty: "beginner",
    examples: [
      "I'm just pulling your leg — it's not actually broken.",
      "Are you serious or just pulling my leg?",
    ],
    synonyms: ["joke", "tease", "kid"],
    related: ["wind someone up", "have someone on"],
  },
  {
    id: 20,
    idiom: "hit the sack",
    meaning: "To go to bed.",
    literalMeaning: "To literally hit a sack (mattress).",
    usage: "Informal expression for going to sleep.",
    origin: "From when mattresses were made of sacks filled with hay.",
    category: "Daily Life",
    difficulty: "beginner",
    examples: [
      "I'm exhausted; I'm going to hit the sack.",
      "After a long day, all I want to do is hit the sack.",
    ],
    synonyms: ["hit the hay", "go to bed", "turn in"],
    related: ["hit the hay", "catch some z's"],
  },
  {
    id: 21,
    idiom: "burn the midnight oil",
    meaning: "To work late into the night.",
    literalMeaning: "To burn oil lamps late at night while working.",
    usage: "Used to describe working or studying into the late hours.",
    origin: "Before electricity, people worked by oil lamp light; burning oil at midnight meant working very late.",
    category: "Work",
    difficulty: "intermediate",
    examples: [
      "She burned the midnight oil to finish the report.",
      "Students burn the midnight oil before exams.",
    ],
    synonyms: ["work late", "pull an all-nighter", "stay up late"],
    related: ["pull an all-nighter", "work overtime"],
  },
  {
    id: 22,
    idiom: "the tip of the iceberg",
    meaning: "A small, visible part of a much larger problem.",
    literalMeaning: "The visible top of an iceberg, with most of it hidden underwater.",
    usage: "Used when describing a problem that is much larger than what is immediately apparent.",
    origin: "From the fact that only about 10% of an iceberg is visible above water.",
    category: "Problems",
    difficulty: "intermediate",
    examples: [
      "The leaked documents are just the tip of the iceberg.",
      "This complaint is just the tip of the iceberg.",
    ],
    synonyms: ["a fraction of", "small part of a bigger problem"],
    related: ["just scratching the surface", "hidden depths"],
  },
  {
    id: 23,
    idiom: "a piece of cake",
    meaning: "Something that is very easy to do.",
    literalMeaning: "A literal piece of cake — simple and pleasant.",
    usage: "Used to describe a task that requires very little effort.",
    origin: "From the 1930s American South, where 'cakewalk' referred to an easy competition.",
    category: "Difficulty",
    difficulty: "beginner",
    examples: [
      "The test was a piece of cake.",
      "Don't worry, fixing that bug is a piece of cake.",
    ],
    synonyms: ["easy", "effortless", "simple"],
    related: ["walk in the park", "child's play"],
  },
  {
    id: 24,
    idiom: "put your foot in your mouth",
    meaning: "To say something embarrassing or inappropriate.",
    literalMeaning: "To literally place your foot in your mouth.",
    usage: "Used when someone says something that causes embarrassment or offense.",
    origin: "From a 17th-century saying about self-incrimination.",
    category: "Communication",
    difficulty: "intermediate",
    examples: [
      "He really put his foot in his mouth when he asked when she was due.",
      "I put my foot in my mouth by mentioning his ex at dinner.",
    ],
    synonyms: ["say the wrong thing", "blunder", "misspeak"],
    related: ["open mouth, insert foot", "speak out of turn"],
  },
  {
    id: 25,
    idiom: "see eye to eye",
    meaning: "To agree with someone.",
    literalMeaning: "To look at each other at the same eye level.",
    usage: "Used when two or more people share the same opinion.",
    origin: "From the Bible — Isaiah 52:8 mentions watchmen 'seeing eye to eye'.",
    category: "Agreement",
    difficulty: "intermediate",
    examples: [
      "We don't always see eye to eye on politics.",
      "The two managers finally saw eye to eye on the budget.",
    ],
    synonyms: ["agree", "be in accord", "concur"],
    related: ["on the same page", "singing from the same hymn sheet"],
  },
  {
    id: 26,
    idiom: "miss the boat",
    meaning: "To miss an opportunity.",
    literalMeaning: "To arrive too late to board a boat.",
    usage: "Used when someone fails to take advantage of an opportunity.",
    origin: "From literally missing a boat departure.",
    category: "Opportunity",
    difficulty: "intermediate",
    examples: [
      "He missed the boat by not investing early.",
      "If you don't apply now, you'll miss the boat.",
    ],
    synonyms: ["miss the opportunity", "lose the chance", "too late"],
    related: ["too little too late", "missed the window"],
  },
  {
    id: 27,
    idiom: "silver lining",
    meaning: "A positive aspect of a negative situation.",
    literalMeaning: "The silver-colored edge of a cloud lit by the sun behind it.",
    usage: "Used to point out something good in an otherwise bad situation.",
    origin: "From the proverb 'every cloud has a silver lining'.",
    category: "Optimism",
    difficulty: "intermediate",
    examples: [
      "The silver lining of the delay was more time to prepare.",
      "Look for the silver lining in every setback.",
    ],
    synonyms: ["bright side", "positive aspect", "upside"],
    related: ["blessing in disguise", "every cloud has a silver lining"],
  },
  {
    id: 28,
    idiom: "cut corners",
    meaning: "To do something poorly to save time or money.",
    literalMeaning: "To cut the corner of a path to save distance.",
    usage: "Used when someone sacrifices quality for speed or economy.",
    origin: "From literally cutting the corner of a road while driving.",
    category: "Work",
    difficulty: "intermediate",
    examples: [
      "The contractor cut corners, and the building failed inspection.",
      "Never cut corners when safety is involved.",
    ],
    synonyms: ["take shortcuts", "do a shoddy job", "rush"],
    related: ["take shortcuts", "do things the easy way"],
  },
  {
    id: 29,
    idiom: "go back to the drawing board",
    meaning: "To start over from the beginning after a failure.",
    literalMeaning: "To return to an architectural drawing board to redesign.",
    usage: "Used when a plan has failed and must be completely redesigned.",
    origin: "From a 1941 New Yorker cartoon showing designers returning to their drawing board.",
    category: "Failure",
    difficulty: "intermediate",
    examples: [
      "The prototype failed. It's back to the drawing board.",
      "Their proposal was rejected — back to the drawing board.",
    ],
    synonyms: ["start fresh", "start from scratch", "restart"],
    related: ["start from scratch", "square one"],
  },
  {
    id: 30,
    idiom: "raining cats and dogs",
    meaning: "Raining very heavily.",
    literalMeaning: "Cats and dogs falling from the sky.",
    usage: "Used to describe extremely heavy rainfall.",
    origin: "Possibly from Norse mythology or from old English streets flooding with dead animals during heavy rain.",
    category: "Weather",
    difficulty: "beginner",
    examples: [
      "Don't forget your umbrella — it's raining cats and dogs.",
      "We couldn't go outside because it was raining cats and dogs.",
    ],
    synonyms: ["pouring", "heavy rain", "downpour"],
    related: ["pouring down", "bucketing down"],
  },
  {
    id: 31,
    idiom: "barking up the wrong tree",
    meaning: "To pursue a mistaken or misguided course of action.",
    literalMeaning: "A hunting dog barking at the wrong tree where prey is not present.",
    usage: "Used when someone is wrong about the source of a problem or solution.",
    origin: "From hunting dogs in the 19th century American wilderness.",
    category: "Mistake",
    difficulty: "intermediate",
    examples: [
      "If you think I took your book, you're barking up the wrong tree.",
      "The police were barking up the wrong tree.",
    ],
    synonyms: ["on the wrong track", "mistaken", "off course"],
    related: ["on the wrong track", "miss the point"],
  },
  {
    id: 32,
    idiom: "let sleeping dogs lie",
    meaning: "To avoid bringing up old problems.",
    literalMeaning: "To not disturb a sleeping dog.",
    usage: "Used as advice against raising controversial or resolved past issues.",
    origin: "From Chaucer's Troilus and Criseyde — 'Let sleeping hounds lie'.",
    category: "Advice",
    difficulty: "intermediate",
    examples: [
      "I know you're upset, but let sleeping dogs lie.",
      "The issue has been resolved — let sleeping dogs lie.",
    ],
    synonyms: ["leave well enough alone", "let it go", "don't stir the pot"],
    related: ["leave well alone", "don't rock the boat"],
  },
  {
    id: 33,
    idiom: "take it with a grain of salt",
    meaning: "To be skeptical about something; not take it too seriously.",
    literalMeaning: "To consume something (perhaps bitter or questionable) with a grain of salt for palatability.",
    usage: "Used when advising skepticism about something you've heard.",
    origin: "From Pliny the Elder's antidote to poison, which was to be taken with a grain of salt.",
    category: "Skepticism",
    difficulty: "intermediate",
    examples: [
      "Take his advice with a grain of salt.",
      "Reviews on that site should be taken with a grain of salt.",
    ],
    synonyms: ["be skeptical", "question", "doubt"],
    related: ["pinch of salt", "question the source"],
  },
  {
    id: 34,
    idiom: "hit the nail on the head",
    meaning: "To identify or describe something exactly.",
    literalMeaning: "Striking a nail squarely on the head.",
    usage: "Used when someone explains something perfectly.",
    origin: "From carpentry — hitting a nail on the head is the most effective way to drive it.",
    category: "Accuracy",
    difficulty: "beginner",
    examples: [
      "Your summary really hit the nail on the head.",
      "The analyst hit the nail on the head with her prediction.",
    ],
    synonyms: ["spot on", "exactly right", "bulls-eye"],
    related: ["right on the money", "on point"],
  },
  {
    id: 35,
    idiom: "actions speak louder than words",
    meaning: "What you do is more important than what you say.",
    literalMeaning: "Physical actions make more noise than speech.",
    usage: "Used to emphasize the importance of behavior over promises.",
    origin: "An old English proverb, traced back to Abraham Lincoln.",
    category: "Wisdom",
    difficulty: "beginner",
    examples: [
      "He promised to change, but actions speak louder than words.",
      "If you care, show it — actions speak louder than words.",
    ],
    synonyms: ["practice what you preach", "walk the walk"],
    related: ["put your money where your mouth is", "walk the talk"],
  },
  {
    id: 36,
    idiom: "kick the bucket",
    meaning: "To die.",
    literalMeaning: "To literally kick a bucket.",
    usage: "A humorous or informal way to refer to death.",
    origin: "Possibly from the platform (a 'bucket') used in hangings, which was kicked away.",
    category: "Dark Humor",
    difficulty: "intermediate",
    examples: [
      "He kicked the bucket at a ripe old age.",
      "When I kick the bucket, I want a big party.",
    ],
    synonyms: ["pass away", "die", "meet one's maker"],
    related: ["bite the dust", "give up the ghost"],
  },
  {
    id: 37,
    idiom: "bite the dust",
    meaning: "To fail, die, or come to an end.",
    literalMeaning: "To fall face-first into dirt.",
    usage: "Used to describe failure, defeat, or death in an informal way.",
    origin: "From Homer's Iliad, translated by Pope as 'bite the bloody sand'.",
    category: "Failure",
    difficulty: "intermediate",
    examples: [
      "Another startup bit the dust this year.",
      "Three of their proposals bit the dust before this one succeeded.",
    ],
    synonyms: ["fail", "perish", "be defeated"],
    related: ["kick the bucket", "go under"],
  },
  {
    id: 38,
    idiom: "back to square one",
    meaning: "Starting over again from the beginning.",
    literalMeaning: "Returning to the first square on a board game.",
    usage: "Used when progress is lost and one must start again.",
    origin: "Possibly from Snakes and Ladders game or from BBC radio football commentary in the 1930s.",
    category: "Failure",
    difficulty: "intermediate",
    examples: [
      "The client rejected the entire proposal — it's back to square one.",
      "After the crash, the developers went back to square one.",
    ],
    synonyms: ["start fresh", "start over", "from scratch"],
    related: ["go back to the drawing board", "fresh start"],
  },
  {
    id: 39,
    idiom: "throw caution to the wind",
    meaning: "To take a risk without worrying about consequences.",
    literalMeaning: "Literally throwing something into the wind, where control is lost.",
    usage: "Used when someone acts boldly or recklessly.",
    origin: "From the idea of releasing something into the wind, making control impossible.",
    category: "Risk",
    difficulty: "advanced",
    examples: [
      "She threw caution to the wind and quit her job to travel.",
      "Sometimes you have to throw caution to the wind.",
    ],
    synonyms: ["take a risk", "be bold", "go for broke"],
    related: ["take the plunge", "go all in"],
  },
  {
    id: 40,
    idiom: "the elephant in the room",
    meaning: "An obvious problem or controversial issue that no one wants to discuss.",
    literalMeaning: "A literal elephant in a room that everyone ignores.",
    usage: "Used when pointing out a significant issue being avoided by a group.",
    origin: "From a Russian fable by Ivan Krylov (1814) about a man who ignores an elephant in a museum.",
    category: "Problems",
    difficulty: "intermediate",
    examples: [
      "No one mentioned the budget cuts — it was the elephant in the room.",
      "Their failing marriage was the elephant in the room.",
    ],
    synonyms: ["unspoken issue", "obvious problem", "avoided topic"],
    related: ["the pink elephant", "sweep under the rug"],
  },
  {
    id: 41,
    idiom: "burn your bridges",
    meaning: "To destroy your relationships or future opportunities irreparably.",
    literalMeaning: "To literally burn bridges, cutting off the route back.",
    usage: "Used as a warning to avoid destroying valuable relationships.",
    origin: "Military strategy of burning bridges behind troops to force forward momentum.",
    category: "Relationships",
    difficulty: "intermediate",
    examples: [
      "Don't burn your bridges at your old company.",
      "She burned her bridges with every mentor she had.",
    ],
    synonyms: ["cut off", "sever ties", "alienate"],
    related: ["burn bridges", "leave on bad terms"],
  },
  {
    id: 42,
    idiom: "fly off the handle",
    meaning: "To suddenly become very angry.",
    literalMeaning: "For an axe head to fly off its handle during use.",
    usage: "Used to describe someone who loses their temper suddenly.",
    origin: "From the early 1800s — if an axe head flew off, it was dangerous and uncontrolled.",
    category: "Emotion",
    difficulty: "intermediate",
    examples: [
      "He flies off the handle at the slightest criticism.",
      "She flew off the handle when she saw the mess.",
    ],
    synonyms: ["lose one's temper", "blow a fuse", "blow up"],
    related: ["blow a fuse", "lose it"],
  },
  {
    id: 43,
    idiom: "on the ball",
    meaning: "Alert, quick to understand, or doing one's job well.",
    literalMeaning: "Keeping one's eye on a ball during a game.",
    usage: "Used to compliment someone who is attentive and efficient.",
    origin: "From sports — keeping your eye on the ball is crucial to good performance.",
    category: "Performance",
    difficulty: "intermediate",
    examples: [
      "She's really on the ball with her client follow-ups.",
      "The new manager is on the ball.",
    ],
    synonyms: ["alert", "sharp", "on top of things"],
    related: ["on the case", "on it"],
  },
  {
    id: 44,
    idiom: "hang in there",
    meaning: "To persist in difficult circumstances.",
    literalMeaning: "To literally hang on to something.",
    usage: "Used as encouragement to someone going through difficulties.",
    origin: "From the 1970s motivational poster featuring a cat hanging from a branch.",
    category: "Encouragement",
    difficulty: "beginner",
    examples: [
      "Hang in there — things will get better.",
      "I know it's tough, but hang in there.",
    ],
    synonyms: ["persevere", "hold on", "keep going"],
    related: ["keep your chin up", "stay strong"],
  },
  {
    id: 45,
    idiom: "read between the lines",
    meaning: "To find the hidden meaning in something said or written.",
    literalMeaning: "To read the invisible text between the lines of a document.",
    usage: "Used when someone needs to understand an implied meaning.",
    origin: "Historically from deciphering coded messages written between lines of regular text.",
    category: "Understanding",
    difficulty: "intermediate",
    examples: [
      "If you read between the lines, she's asking for help.",
      "The report is positive, but read between the lines.",
    ],
    synonyms: ["infer", "interpret", "look deeper"],
    related: ["read the subtext", "implied meaning"],
  },
  {
    id: 46,
    idiom: "jump the gun",
    meaning: "To do something too soon or prematurely.",
    literalMeaning: "A runner starting before the starting gun fires.",
    usage: "Used when someone acts too hastily or prematurely.",
    origin: "From track and field — jumping the gun means starting before the signal.",
    category: "Timing",
    difficulty: "intermediate",
    examples: [
      "Don't jump the gun — wait for the official announcement.",
      "She jumped the gun by sending the email before approval.",
    ],
    synonyms: ["act prematurely", "rush", "anticipate too early"],
    related: ["get ahead of yourself", "count your chickens"],
  },
  {
    id: 47,
    idiom: "kill two birds with one stone",
    meaning: "To accomplish two things with a single action.",
    literalMeaning: "To literally hit two birds with one stone.",
    usage: "Used when one action achieves two goals simultaneously.",
    origin: "From an old proverb about efficiency in hunting.",
    category: "Efficiency",
    difficulty: "beginner",
    examples: [
      "I'll visit my friend and collect the package — kill two birds with one stone.",
      "The new policy kills two birds with one stone.",
    ],
    synonyms: ["two for one", "efficient", "accomplish both"],
    related: ["get two things done at once", "multitask"],
  },
  {
    id: 48,
    idiom: "steal someone's thunder",
    meaning: "To upstage someone by taking attention away from them.",
    literalMeaning: "To take the thunder (dramatic effect) meant for another person.",
    usage: "Used when someone takes credit or attention from another person's achievement.",
    origin: "From playwright John Dennis, who invented a stage thunder device and saw it used in another play.",
    category: "Social",
    difficulty: "advanced",
    examples: [
      "His surprise announcement stole the bride's thunder.",
      "Don't steal her thunder — let her share the news.",
    ],
    synonyms: ["upstage", "outshine", "take the spotlight"],
    related: ["hog the limelight", "take center stage"],
  },
  {
    id: 49,
    idiom: "drawing a blank",
    meaning: "Being unable to remember something.",
    literalMeaning: "Drawing a blank ticket in a lottery — getting nothing.",
    usage: "Used when someone cannot recall information despite trying.",
    origin: "From lottery draws where a blank ticket wins nothing.",
    category: "Memory",
    difficulty: "intermediate",
    examples: [
      "I'm drawing a blank on his name.",
      "She drew a blank when asked about the meeting.",
    ],
    synonyms: ["can't remember", "forgot", "memory lapse"],
    related: ["tip of the tongue", "brain freeze"],
  },
  {
    id: 50,
    idiom: "up in the air",
    meaning: "Uncertain or undecided.",
    literalMeaning: "Suspended in the air with no ground support.",
    usage: "Used when a situation or decision is still unresolved.",
    origin: "From 18th-century English, describing unsettled matters.",
    category: "Uncertainty",
    difficulty: "intermediate",
    examples: [
      "The project timeline is still up in the air.",
      "Everything is up in the air until the board meets.",
    ],
    synonyms: ["undecided", "uncertain", "unresolved"],
    related: ["on the fence", "in limbo"],
  },
  {
    id: 51,
    idiom: "hit the ground running",
    meaning: "To begin something quickly and with great energy.",
    literalMeaning: "Hitting the ground while already running — like a paratrooper landing.",
    usage: "Used to describe someone who starts a new task with enthusiasm and efficiency.",
    origin: "From military paratroopers trained to run immediately upon landing.",
    category: "Work",
    difficulty: "intermediate",
    examples: [
      "She hit the ground running in her new role.",
      "The new hire hit the ground running from day one.",
    ],
    synonyms: ["start strong", "dive in", "jump right in"],
    related: ["get off to a flying start", "waste no time"],
  },
  {
    id: 52,
    idiom: "a dime a dozen",
    meaning: "Something very common and not special.",
    literalMeaning: "Getting twelve items for a dime — extremely cheap and abundant.",
    usage: "Used to describe something that is commonplace and of little value.",
    origin: "From the 19th-century American phrase when dimes had significant purchasing power.",
    category: "Value",
    difficulty: "intermediate",
    examples: [
      "App ideas are a dime a dozen — execution is what matters.",
      "Cheap gadgets are a dime a dozen these days.",
    ],
    synonyms: ["common", "plentiful", "ordinary"],
    related: ["run of the mill", "ten a penny"],
  },
  {
    id: 53,
    idiom: "face the music",
    meaning: "To confront the unpleasant consequences of one's actions.",
    literalMeaning: "To face forward toward the music (such as a military band playing during punishment).",
    usage: "Used when someone must accept punishment or criticism.",
    origin: "From the military practice of drumming out dishonorable soldiers.",
    category: "Responsibility",
    difficulty: "intermediate",
    examples: [
      "He made mistakes, and now he must face the music.",
      "It's time to face the music and apologize.",
    ],
    synonyms: ["accept consequences", "own up", "take responsibility"],
    related: ["bite the bullet", "take the heat"],
  },
  {
    id: 54,
    idiom: "cross that bridge when we come to it",
    meaning: "To deal with a problem only when it actually occurs.",
    literalMeaning: "Waiting to cross a bridge until you physically reach it.",
    usage: "Used to suggest not worrying about future problems.",
    origin: "A common proverb used widely since the 19th century.",
    category: "Patience",
    difficulty: "intermediate",
    examples: [
      "We'll cross that bridge when we come to it.",
      "Don't worry about it now — cross that bridge when we come to it.",
    ],
    synonyms: ["deal with it later", "take it one step at a time"],
    related: ["take it one day at a time", "cross that road when you come to it"],
  },
  {
    id: 55,
    idiom: "wrapped around someone's finger",
    meaning: "To be completely controlled or influenced by someone.",
    literalMeaning: "Like thread wound tightly around a finger.",
    usage: "Used when describing strong personal influence or control over someone.",
    origin: "From the image of thread wound around a finger, easily controlled.",
    category: "Influence",
    difficulty: "advanced",
    examples: [
      "He had her wrapped around his finger.",
      "The child had the grandparents wrapped around her finger.",
    ],
    synonyms: ["under someone's thumb", "controlled by", "devoted to"],
    related: ["under someone's thumb", "at someone's beck and call"],
  },
  {
    id: 56,
    idiom: "raise the bar",
    meaning: "To increase the standard or level of quality expected.",
    literalMeaning: "To physically raise a bar in high jump or other events.",
    usage: "Used to describe setting higher standards.",
    origin: "From athletics where competitors literally raise the bar in high jump.",
    category: "Excellence",
    difficulty: "intermediate",
    examples: [
      "The new product raises the bar in the industry.",
      "She raised the bar for customer service.",
    ],
    synonyms: ["set higher standards", "improve", "elevate expectations"],
    related: ["up the ante", "set the benchmark"],
  },
  {
    id: 57,
    idiom: "straight from the horse's mouth",
    meaning: "Directly from the original or most reliable source.",
    literalMeaning: "Hearing information from the horse's own mouth.",
    usage: "Used to say information came from the most credible source.",
    origin: "From horse racing — checking a horse's age by its teeth is the most accurate method.",
    category: "Information",
    difficulty: "advanced",
    examples: [
      "I heard it straight from the horse's mouth.",
      "Get it from the horse's mouth — ask the manager directly.",
    ],
    synonyms: ["firsthand", "from the source", "directly"],
    related: ["from the source", "word of mouth"],
  },
  {
    id: 58,
    idiom: "at the drop of a hat",
    meaning: "Without hesitation; immediately.",
    literalMeaning: "Acting the instant a hat is dropped.",
    usage: "Used to describe someone who acts without any delay.",
    origin: "From 19th-century American frontier practices — dropping a hat signaled the start of a race or fight.",
    category: "Speed",
    difficulty: "intermediate",
    examples: [
      "She would help at the drop of a hat.",
      "He changes his mind at the drop of a hat.",
    ],
    synonyms: ["immediately", "instantly", "without hesitation"],
    related: ["right away", "on the spot"],
  },
  {
    id: 59,
    idiom: "the whole nine yards",
    meaning: "Everything possible; the complete amount.",
    literalMeaning: "All nine yards of something.",
    usage: "Used to mean the entirety or the complete effort.",
    origin: "Origin disputed — possibly from WWII ammunition belts or fabric yardage.",
    category: "Completeness",
    difficulty: "advanced",
    examples: [
      "They gave us the whole nine yards — food, drinks, entertainment.",
      "She went the whole nine yards for the presentation.",
    ],
    synonyms: ["everything", "the works", "all of it"],
    related: ["the whole shebang", "lock, stock and barrel"],
  },
  {
    id: 60,
    idiom: "bite the hand that feeds you",
    meaning: "To harm or show ingratitude to someone who helps you.",
    literalMeaning: "To literally bite the hand of someone feeding you.",
    usage: "Used as a warning against acting against those who help you.",
    origin: "From Aesop's Fables and later Edmund Burke.",
    category: "Wisdom",
    difficulty: "advanced",
    examples: [
      "Criticizing your employer publicly is biting the hand that feeds you.",
      "Don't bite the hand that feeds you.",
    ],
    synonyms: ["show ingratitude", "undermine your benefactor"],
    related: ["burn your bridges", "saw off the branch you sit on"],
  },
];

export const CATEGORIES = [
  "All",
  "Social",
  "Courage",
  "Communication",
  "Accuracy",
  "Health",
  "Finance",
  "Perspective",
  "Relationships",
  "Decision Making",
  "Work",
  "Surprise",
  "Conflict",
  "Opportunity",
  "Optimism",
  "Wisdom",
  "Humor",
  "Daily Life",
  "Failure",
  "Risk",
  "Problems",
  "Emotion",
  "Performance",
  "Encouragement",
  "Understanding",
  "Timing",
  "Efficiency",
  "Memory",
  "Uncertainty",
  "Value",
  "Responsibility",
  "Patience",
  "Influence",
  "Excellence",
  "Information",
  "Speed",
  "Completeness",
  "Dark Humor",
  "Weather",
  "Skepticism",
  "Mistake",
  "Advice",
  "Frequency",
  "Control",
];

export const DIFFICULTIES = ["All", "beginner", "intermediate", "advanced"];

export const ALPHABETS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
