import Link from "next/link";
import {
  ArrowRight,
  AudioLines,
  BookOpen,
  CalendarDays,
  Gauge,
  Layers,
  Music,
  Network,
} from "lucide-react";
import JsonLd from "@/platform/seo/JsonLd";
import {
  createBreadcrumbJsonLd,
  createCollectionPageJsonLd,
  createDefinedTermSetJsonLd,
  createFaqJsonLd,
  createItemListJsonLd,
  createPageMetadata,
} from "@/platform/seo/generateMetadata";
import { COMMONNESS } from "@altftool/core/lexicon";
import {
  getCollectionIndex,
  getManifest,
  getWord,
  getWotd,
} from "@altftool/core/lexicon/corpus";
import {
  AnswerFirst,
  CommonnessMeter,
  LetterTiles,
  PosChips,
  SectionHeading,
  SyllableLine,
} from "./_components/WordAtoms";
import SearchBox from "./_components/SearchBox";

export const revalidate = 86400;

/*
 * The word of the day changes with the calendar, so this page is regenerated
 * daily rather than at request time. Everything else on it — counts, the worked
 * example, the A–Z table — is a property of the corpus and only changes when a
 * new corpus is generated.
 */

/** The word the worked example is built from. Five syllables, stress in the
    middle, a real IPA transcription: it shows every part of the device at once. */
const EXAMPLE_SLUG = "serendipity";

/*
 * Featured collections, chosen for range rather than size. The biggest nine
 * would all be WordNet subject files, which would suggest the only way to slice
 * English is by topic — the shape and sound groups are the ones nobody else has.
 */
const FEATURED_COLLECTIONS = [
  "words-with-many-meanings",
  "hard-to-say",
  "palindromes",
  "idioms-and-phrases",
  "greek-mythology",
  "spelled-nothing-like-said",
  "q-without-u",
  "core-english",
  "animals",
];

const EXPLORE = [
  { href: "/lexicon/browse", label: "Browse A–Z", hint: "Every entry, by first letter" },
  { href: "/lexicon/collections", label: "Collections", hint: "199 curated slices of English" },
  { href: "/lexicon/words", label: "Word lists", hint: "By length, ending and pattern" },
  { href: "/lexicon/thesaurus", label: "Thesaurus", hint: "Synonyms and antonyms, by sense" },
  { href: "/lexicon/word-of-the-day", label: "Word of the day", hint: "A new entry each morning" },
  { href: "/lexicon/games", label: "Word games", hint: "Play against the corpus" },
  { href: "/lexicon/tools", label: "Word tools", hint: "Counters, checkers, generators" },
  { href: "/lexicon/learn", label: "Learn", hint: "How stress, sense and spelling work" },
];

const FAQS = [
  {
    question: "What is AltF Lexicon?",
    answer:
      "AltF Lexicon is a free English dictionary of 147,478 entries and 207,235 senses. Every entry shows its syllable split with the stressed syllable marked, its pronunciation, all of its recorded meanings rather than the first one, and its synonyms, antonyms, broader and narrower terms. No account, no paywall, no ads between you and the definition.",
  },
  {
    question: "Where do the definitions come from?",
    answer:
      "The definitions, examples and semantic relations come from Princeton University's WordNet, a lexical database built and maintained by lexicographers since 1985. Pronunciations come from the CMU Pronouncing Dictionary. Commonness is measured against a large corpus of everyday English. Nothing on the site is generated by a language model.",
  },
  {
    question: "How is pronunciation shown?",
    answer:
      "Three ways at once, because no single notation works for everyone. The syllable line splits the word and inks the stressed syllable — ser · en · DIP · i · ty. The IPA transcription is there for anyone who reads it. And a plain-English respelling (seh-ruhn-DI-pi-tee) is there for everyone who does not.",
  },
  {
    question: "What does the commonness meter mean?",
    answer:
      "Five bands, from Rare to Core, derived from how often a word appears in a large corpus of everyday English rather than from an editor's impression. Core is the few thousand words that carry most of the language; Rare is specialist or archaic vocabulary most readers will never have met. Where no frequency figure exists, the band falls back to how many senses the word carries.",
  },
  {
    question: "Why does a dictionary contain phrases like jack-in-the-pulpit?",
    answer:
      "64,225 of the 147,478 entries are multi-word: idioms, phrasal verbs, compound nouns and species names. WordNet records them because their meaning is not the sum of their parts, which is exactly the case where a reader needs a dictionary. They are marked as phrases wherever they appear so you always know which kind of entry you are reading.",
  },
  {
    question: "Why do some words have no phonetic transcription?",
    answer:
      "35,490 entries appear in the CMU Pronouncing Dictionary and carry a real transcription. The rest get a syllable split derived from spelling, and the page says so in plain words. A guessed IPA string that looks authoritative is worse than none, so we do not print one.",
  },
  {
    question: "Is AltF Lexicon free to use?",
    answer:
      "Yes, entirely, with no account. The source data is free to redistribute under Princeton's WordNet licence, the BSD-2 licence for CMUdict, and CC BY-SA 4.0 for the frequency data — all of which are credited on the sources page.",
  },
];

const description =
  "A free dictionary of 147,478 English words with the syllables split and the stress marked on every entry. Definitions, IPA, plain-English respelling, every sense, synonyms and rhymes.";

export async function generateMetadata() {
  return createPageMetadata({
    title: "AltF Lexicon — every word, with its syllables and stress marked",
    description,
    path: "/lexicon",
    keywords: [
      "dictionary",
      "English dictionary",
      "word meanings",
      "syllables",
      "word stress",
      "how to pronounce",
      "IPA pronunciation",
      "synonyms and antonyms",
    ],
  });
}

/**
 * Which of the 366 word-of-the-day slugs today is.
 *
 * Computed from the UTC calendar date so the same day always resolves to the
 * same word regardless of where the page is rendered. Day 0 is 1 January, and
 * the list is a full leap year long, so no day is ever skipped.
 */
function wordOfTheDayIndex(date, length) {
  const yearStart = Date.UTC(date.getUTCFullYear(), 0, 1);
  const today = Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate());
  return Math.floor((today - yearStart) / 86_400_000) % length;
}

export default async function LexiconHomePage() {
  const [manifest, collectionIndex, wotdSlugs, example] = await Promise.all([
    getManifest(),
    getCollectionIndex(),
    getWotd(),
    getWord(EXAMPLE_SLUG),
  ]);

  const now = new Date();
  const wotdSlug = wotdSlugs[wordOfTheDayIndex(now, wotdSlugs.length)];
  const wotd = await getWord(wotdSlug);

  const bySlug = new Map(collectionIndex.map((collection) => [collection.slug, collection]));
  const featured = FEATURED_COLLECTIONS.map((slug) => bySlug.get(slug)).filter(Boolean);

  const exampleBand = example ? COMMONNESS.find((band) => band.band === example.c) : null;

  const stats = [
    { value: manifest.total.toLocaleString("en-US"), label: "Entries" },
    { value: manifest.senses.toLocaleString("en-US"), label: "Distinct senses" },
    { value: manifest.withSyllables.toLocaleString("en-US"), label: "Syllable splits" },
    { value: manifest.withPronunciation.toLocaleString("en-US"), label: "IPA transcriptions" },
    { value: manifest.collections.toLocaleString("en-US"), label: "Collections" },
    { value: manifest.rhymeGroups.toLocaleString("en-US"), label: "Rhyme groups" },
  ];

  const features = [
    {
      icon: AudioLines,
      title: "Syllables and stress, drawn",
      body: `Every entry splits into its syllables with the stressed one inked and raised. ${manifest.withSyllables.toLocaleString(
        "en-US",
      )} single words carry a split. No other dictionary renders stress as something you can see rather than decode.`,
    },
    {
      icon: Music,
      title: "IPA and a plain respelling",
      body: `${manifest.withPronunciation.toLocaleString(
        "en-US",
      )} entries carry a phonetic transcription from the CMU Pronouncing Dictionary, alongside a respelling anyone can read aloud. Where there is no transcription the page says so rather than guessing.`,
    },
    {
      icon: Layers,
      title: "Every sense, not just the first",
      body: `${manifest.senses.toLocaleString(
        "en-US",
      )} senses across the corpus, grouped by part of speech and left in WordNet's own order. The meaning you were looking for is rarely sense one.`,
    },
    {
      icon: Network,
      title: "The words around the word",
      body: "Synonyms, antonyms, broader terms and narrower terms are listed per sense rather than pooled, because a word with six meanings almost never has one substitute that works for all of them.",
    },
    {
      icon: Gauge,
      title: "How common it actually is",
      body: `A five-band meter measured against a corpus of everyday English, not an editor's impression. ${manifest.withFrequency.toLocaleString(
        "en-US",
      )} entries have a measured frequency behind their band.`,
    },
    {
      icon: BookOpen,
      title: "Rhymes that match the ear",
      body: `${manifest.rhymeGroups.toLocaleString(
        "en-US",
      )} rhyme groups, matched on the phonemes from the last stressed vowel onward — the definition of a rhyme a reader already has in their head.`,
    },
  ];

  return (
    <>
      <JsonLd
        id="altf-lexicon-home"
        data={[
          createDefinedTermSetJsonLd({
            path: "/lexicon",
            name: "AltF Lexicon",
            description,
            termCount: manifest.total,
          }),
          createCollectionPageJsonLd({ path: "/lexicon", name: "AltF Lexicon", description }),
          createItemListJsonLd({
            path: "/lexicon",
            name: "Featured word collections",
            items: featured.map((collection) => ({
              name: collection.title || collection.name,
              path: `/lexicon/collections/${collection.slug}`,
            })),
          }),
          createFaqJsonLd({ path: "/lexicon", questions: FAQS }),
          createBreadcrumbJsonLd([
            { name: "Home", path: "/" },
            { name: "Lexicon", path: "/lexicon" },
          ]),
        ]}
      />

      {/* ---------------- Hero ---------------- */}
      <section className="relative overflow-hidden border-b border-border">
        <div
          className="afl-rule-bg pointer-events-none absolute inset-0 opacity-70"
          style={{
            maskImage:
              "radial-gradient(ellipse 85% 70% at 50% 0%, var(--foreground) 15%, transparent 78%)",
            WebkitMaskImage:
              "radial-gradient(ellipse 85% 70% at 50% 0%, var(--foreground) 15%, transparent 78%)",
          }}
          aria-hidden="true"
        />

        <div className="relative mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:py-20">
          <div className="mx-auto max-w-3xl text-center">
            <span className="inline-flex items-center gap-2 rounded-full border border-border bg-surface/80 px-3.5 py-1.5 text-[0.8125rem] text-foreground backdrop-blur">
              <span className="h-1.5 w-1.5 rounded-full bg-primary ring-4 ring-primary/15" />
              <span className="font-mono tabular-nums">
                {manifest.total.toLocaleString("en-US")}
              </span>{" "}
              entries ·{" "}
              <span className="font-mono tabular-nums">
                {manifest.senses.toLocaleString("en-US")}
              </span>{" "}
              senses
            </span>

            <h1 className="afl-headword mt-6 text-[clamp(2.5rem,6.4vw,4.5rem)] text-foreground">
              Every word, opened up.
            </h1>

            <p className="mx-auto mt-5 max-w-[54ch] text-[clamp(1rem,1.4vw,1.1875rem)] leading-relaxed text-muted-foreground">
              A dictionary that shows you how a word is <em>said</em>, not only what it means. Every
              one of the {manifest.total.toLocaleString("en-US")} entries arrives with its syllables
              split and its stressed syllable marked, next to the definition.
            </p>

            <div className="mx-auto mt-8 max-w-2xl">
              <SearchBox autoFocus size="lg" />
            </div>

            <div className="mt-4 flex flex-wrap items-center justify-center gap-2">
              <span className="font-mono text-xs text-muted-foreground">TRY</span>
              {["serendipity", "ephemeral", "colonel", "quixotic", "labyrinth"].map((word) => (
                <Link
                  key={word}
                  href={`/lexicon/word/${word}`}
                  className="rounded-sm border border-border bg-surface-soft px-2.5 py-1 font-mono text-xs text-muted-foreground no-underline transition hover:border-border-strong hover:text-foreground"
                >
                  {word}
                </Link>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ---------------- The device, demonstrated ---------------- */}
      {example?.pt?.length ? (
        <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:py-20">
          <div className="grid items-center gap-10 lg:grid-cols-[1.15fr_0.85fr] lg:gap-16">
            <figure className="rounded-xl border border-border-strong bg-surface p-6 sm:p-9">
              <figcaption className="font-mono text-xs font-medium uppercase tracking-[0.08em] text-primary">
                What every entry looks like
              </figcaption>

              <Link
                href={`/lexicon/word/${example.s}`}
                className="afl-headword mt-4 block text-[clamp(2.25rem,6vw,3.75rem)] text-foreground no-underline hover:text-primary"
              >
                {example.w}
              </Link>

              <div className="mt-4 [&_.afl-syllables]:text-[clamp(1.5rem,4.4vw,2.5rem)]">
                <SyllableLine parts={example.pt} stress={example.st} size="lg" />
              </div>

              <dl className="mt-7 grid gap-x-8 gap-y-5 sm:grid-cols-2">
                {example.ip ? (
                  <div>
                    <dt className="font-mono text-[0.6875rem] uppercase tracking-[0.06em] text-muted-foreground">
                      IPA
                    </dt>
                    <dd className="mt-1 font-mono text-lg text-foreground">/{example.ip}/</dd>
                  </div>
                ) : null}
                {example.rs ? (
                  <div>
                    <dt className="font-mono text-[0.6875rem] uppercase tracking-[0.06em] text-muted-foreground">
                      Say it
                    </dt>
                    <dd className="mt-1 font-mono text-lg text-foreground">{example.rs}</dd>
                  </div>
                ) : null}
                <div>
                  <dt className="font-mono text-[0.6875rem] uppercase tracking-[0.06em] text-muted-foreground">
                    How common
                  </dt>
                  <dd className="mt-2 flex flex-wrap items-center gap-3">
                    <CommonnessMeter band={example.c} showLabel={false} />
                    <span className="text-base font-semibold text-foreground">
                      {exampleBand?.label}
                    </span>
                    <span className="font-mono text-xs text-muted-foreground">
                      band {example.c} of 5
                    </span>
                  </dd>
                </div>
                <div>
                  <dt className="font-mono text-[0.6875rem] uppercase tracking-[0.06em] text-muted-foreground">
                    Part of speech
                  </dt>
                  <dd className="mt-2">
                    <PosChips parts={example.p} />
                  </dd>
                </div>
              </dl>

              <p className="afl-sense__gloss mt-7 border-t border-border pt-5">
                {example.sn[0].g}
              </p>
            </figure>

            <div>
              <span className="font-mono text-xs font-medium uppercase tracking-[0.08em] text-primary">
                Read it in one glance
              </span>
              <h2 className="mt-3 text-[clamp(1.625rem,3vw,2.125rem)] font-semibold tracking-[-0.02em] text-foreground">
                The stressed syllable is inked, so you never have to decode it
              </h2>
              <p className="mt-4 max-w-[54ch] text-[0.9375rem] leading-relaxed text-muted-foreground">
                Most dictionaries mark stress with an apostrophe buried inside a phonetic string you
                have to already know how to read. Here the word is broken into its syllables and the
                one you lean on is set in capitals and lifted a fraction —{" "}
                <span className="whitespace-nowrap text-foreground">
                  {example.pt.slice(0, example.st).join(" · ")}
                  {example.st > 0 ? " · " : ""}
                  <strong className="font-semibold uppercase">{example.pt[example.st]}</strong>
                  {example.st < example.pt.length - 1 ? " · " : ""}
                  {example.pt.slice(example.st + 1).join(" · ")}
                </span>
                . You can see where the beat falls before you read a word of the definition.
              </p>
              <p className="mt-4 max-w-[54ch] text-[0.9375rem] leading-relaxed text-muted-foreground">
                Below that, the same page gives you the IPA for anyone who reads it, a plain-English
                respelling for everyone who does not, all{" "}
                {example.ns === 1 ? "of the recorded senses" : `${example.ns} recorded senses`}, and
                the synonyms, antonyms and rhymes that go with each one.
              </p>
              <Link
                href={`/lexicon/word/${example.s}`}
                className="mt-6 inline-flex items-center gap-1.5 text-[0.9375rem] font-medium text-primary no-underline hover:underline"
              >
                Open the full entry for {example.w}
                <ArrowRight className="h-3.5 w-3.5" aria-hidden="true" />
              </Link>
            </div>
          </div>
        </section>
      ) : null}

      {/* ---------------- Corpus at a glance ---------------- */}
      <section className="mx-auto max-w-7xl px-4 sm:px-6">
        <dl className="grid grid-cols-2 border-y border-border sm:grid-cols-3 lg:grid-cols-6">
          {stats.map((stat, index) => (
            <div
              key={stat.label}
              className={`px-5 py-6 ${index % 2 === 1 ? "border-l border-border" : ""} ${
                index % 3 !== 0 ? "sm:border-l sm:border-border" : "sm:border-l-0"
              } ${index > 0 ? "lg:border-l lg:border-border" : "lg:border-l-0"}`}
            >
              <dd className="font-mono text-[clamp(1.25rem,2.2vw,1.75rem)] font-semibold tabular-nums text-foreground">
                {stat.value}
              </dd>
              <dt className="mt-0.5 text-[0.8125rem] text-muted-foreground">{stat.label}</dt>
            </div>
          ))}
        </dl>
      </section>

      {/* ---------------- Word of the day ---------------- */}
      {wotd ? (
        <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6">
          <div className="rounded-xl border border-border bg-surface-soft p-6 sm:p-8">
            <div className="flex flex-wrap items-start justify-between gap-6">
              <div className="min-w-0">
                <span className="inline-flex items-center gap-2 font-mono text-xs font-medium uppercase tracking-[0.08em] text-primary">
                  <CalendarDays className="h-3.5 w-3.5" aria-hidden="true" />
                  Word of the day ·{" "}
                  {now.toLocaleDateString("en-US", {
                    month: "long",
                    day: "numeric",
                    timeZone: "UTC",
                  })}
                </span>

                <Link
                  href={`/lexicon/word/${wotd.s}`}
                  className="afl-headword mt-3 block text-[clamp(2rem,4.5vw,3rem)] text-foreground no-underline hover:text-primary"
                >
                  {wotd.w}
                </Link>

                <div className="mt-2 flex flex-wrap items-baseline gap-x-4 gap-y-2">
                  {wotd.pt?.length ? (
                    <SyllableLine parts={wotd.pt} stress={wotd.st} size="md" />
                  ) : null}
                  {wotd.ip ? (
                    <span className="font-mono text-sm text-muted-foreground">/{wotd.ip}/</span>
                  ) : null}
                  <PosChips parts={wotd.p} abbreviated />
                </div>

                <p className="afl-sense__gloss mt-4 max-w-[62ch]">{wotd.sn[0].g}</p>
              </div>

              <div className="flex shrink-0 flex-col gap-3">
                <CommonnessMeter band={wotd.c} />
                <Link
                  href="/lexicon/word-of-the-day"
                  className="inline-flex items-center gap-1.5 text-[0.9375rem] font-medium text-primary no-underline hover:underline"
                >
                  All 366 words of the day
                  <ArrowRight className="h-3.5 w-3.5" aria-hidden="true" />
                </Link>
              </div>
            </div>
          </div>
        </section>
      ) : null}

      {/* ---------------- The A–Z table ---------------- */}
      <section className="mx-auto max-w-7xl px-4 pb-14 sm:px-6 lg:pb-20">
        <SectionHeading
          eyebrow="The A–Z"
          title="Browse the whole dictionary by first letter"
          description={`Each tile carries the number of entries filed under that letter — ${manifest.letters.s.toLocaleString(
            "en-US",
          )} under S against ${manifest.letters.x.toLocaleString(
            "en-US",
          )} under X. It is the shape of English, counted rather than asserted.`}
          action={
            <Link
              href="/lexicon/browse"
              className="inline-flex items-center gap-1.5 text-[0.9375rem] font-medium text-primary no-underline hover:underline"
            >
              Full browse hub
              <ArrowRight className="h-3.5 w-3.5" aria-hidden="true" />
            </Link>
          }
        />

        <div className="mt-7">
          <LetterTiles counts={manifest.letters} />
        </div>

        <p className="mt-4 font-mono text-xs text-muted-foreground">
          # holds the {manifest.letters["0"].toLocaleString("en-US")} entries that begin with a digit
          or a symbol.
        </p>
      </section>

      {/* ---------------- Collections ---------------- */}
      <section className="mx-auto max-w-7xl px-4 pb-14 sm:px-6 lg:pb-20">
        <SectionHeading
          eyebrow="Collections"
          title={`${manifest.collections} ways to cut the corpus`}
          description="Slices by subject, by shape, by sound and for learning. Every one states the rule it was built from, so you can tell what qualified a word before you trust the list."
          action={
            <Link
              href="/lexicon/collections"
              className="inline-flex items-center gap-1.5 text-[0.9375rem] font-medium text-primary no-underline hover:underline"
            >
              All collections
              <ArrowRight className="h-3.5 w-3.5" aria-hidden="true" />
            </Link>
          }
        />

        <ul
          className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"
          style={{ listStyle: "none" }}
        >
          {featured.map((collection) => (
            <li key={collection.slug}>
              <Link
                href={`/lexicon/collections/${collection.slug}`}
                className="afl-card flex h-full flex-col gap-2 rounded-lg border border-border bg-surface p-5 no-underline"
              >
                <span className="flex items-baseline justify-between gap-3">
                  <span className="font-mono text-[0.6875rem] uppercase tracking-[0.06em] text-primary">
                    {collection.group}
                  </span>
                  <span className="font-mono text-xs tabular-nums text-muted-foreground">
                    {collection.count.toLocaleString("en-US")}
                  </span>
                </span>
                <span className="text-[1.0625rem] font-semibold tracking-[-0.01em] text-foreground">
                  {collection.title || collection.name}
                </span>
                <span className="line-clamp-3 text-[0.8125rem] leading-relaxed text-muted-foreground">
                  {collection.description}
                </span>
              </Link>
            </li>
          ))}
        </ul>
      </section>

      {/* ---------------- What every word page gives you ---------------- */}
      <section className="mx-auto max-w-7xl px-4 pb-14 sm:px-6 lg:pb-20">
        <SectionHeading
          eyebrow="On every entry"
          title="Six things you get on all 147,478 pages"
          description="Not a summary page for the popular words and a stub for the rest. The same record is rendered for every entry in the corpus, and where a field is missing the page says why."
        />

        <ul className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3" style={{ listStyle: "none" }}>
          {features.map((feature) => (
            <li
              key={feature.title}
              className="rounded-lg border border-border bg-surface p-5"
            >
              <feature.icon className="h-5 w-5 text-primary" aria-hidden="true" />
              <h3 className="mt-3 text-[1.0625rem] font-semibold tracking-[-0.01em] text-foreground">
                {feature.title}
              </h3>
              <p className="mt-2 text-[0.875rem] leading-relaxed text-muted-foreground">
                {feature.body}
              </p>
            </li>
          ))}
        </ul>
      </section>

      {/* ---------------- Explore ---------------- */}
      <section className="mx-auto max-w-7xl px-4 pb-14 sm:px-6 lg:pb-20">
        <SectionHeading eyebrow="Everything else" title="Where to go from here" />
        <nav aria-label="Explore AltF Lexicon" className="mt-7">
          <ul className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4" style={{ listStyle: "none" }}>
            {EXPLORE.map((item) => (
              <li key={item.href}>
                <Link
                  href={item.href}
                  className="afl-card flex h-full flex-col gap-1 rounded-lg border border-border bg-surface p-4 no-underline"
                >
                  <span className="text-[0.9375rem] font-semibold tracking-[-0.01em] text-foreground">
                    {item.label}
                  </span>
                  <span className="font-mono text-xs text-muted-foreground">{item.hint}</span>
                </Link>
              </li>
            ))}
          </ul>
        </nav>
      </section>

      {/* ---------------- Answer-first + FAQ ---------------- */}
      <section className="mx-auto max-w-7xl px-4 pb-20 sm:px-6">
        <div className="grid gap-10 lg:grid-cols-[0.85fr_1.15fr] lg:gap-16">
          <div>
            <span className="font-mono text-xs font-medium uppercase tracking-[0.08em] text-primary">
              Questions
            </span>
            <h2 className="mt-3 text-[clamp(1.625rem,3vw,2.125rem)] font-semibold tracking-[-0.02em] text-foreground">
              Straight answers
            </h2>

            <AnswerFirst>
              AltF Lexicon is a free English dictionary of{" "}
              {manifest.total.toLocaleString("en-US")} entries and{" "}
              {manifest.senses.toLocaleString("en-US")} senses, built from Princeton&rsquo;s WordNet
              and the CMU Pronouncing Dictionary. Every entry shows its syllable split with the
              stress marked, its pronunciation, and all of its meanings rather than the first one.
            </AnswerFirst>

            <p className="mt-5 text-xs leading-relaxed text-muted-foreground">
              Lexical data from {manifest.source.lexical}. Pronunciation from{" "}
              {manifest.source.pronunciation}. Word frequencies from the OpenSubtitles-derived
              FrequencyWords lists, CC BY-SA 4.0.{" "}
              <Link href="/lexicon/sources" className="text-primary hover:underline">
                Full sources, licences and required notices
              </Link>
              .
            </p>
          </div>

          <div>
            {FAQS.map((faq, index) => (
              <details key={faq.question} className="border-b border-border" open={index === 0}>
                <summary className="cursor-pointer list-none py-4 text-base font-medium tracking-[-0.01em] text-foreground marker:hidden hover:text-primary">
                  {faq.question}
                </summary>
                <div className="max-w-[68ch] pb-5 text-[0.9375rem] leading-relaxed text-muted-foreground">
                  {faq.answer}
                </div>
              </details>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
