/**
 * AI Attribution Statement Builder.
 *
 * Formats a citation for a generative-AI tool in the three major academic
 * styles, following each style body's published guidance:
 *
 *  - APA 7: APA Style blog, "How to cite ChatGPT" (McAdoo, 2023).
 *    Reference pattern:  Provider. (Year). Tool (Version) [Large language model]. URL
 *    In-text pattern:    (Provider, Year)
 *  - MLA 9: MLA Style Center, "How do I cite generative AI in MLA style?".
 *    Pattern: "Prompt" prompt. Tool, Version, Provider, Day Mon. Year, URL.
 *    (The prompt takes the "Title of Source" slot; the tool is the container.)
 *  - Chicago (17th ed.): CMOS Shop Talk guidance — AI output is cited in a
 *    note, not the bibliography:
 *    Pattern: Text generated by Tool, Provider, Month Day, Year, URL.
 *
 * Plus a plain acknowledgement statement of the kind many journals (e.g.
 * Elsevier, Springer Nature author policies) require: state the tool, why it
 * was used, and that authors reviewed and take responsibility.
 */

export const STYLE_OPTIONS = [
  { id: "apa", label: "APA 7" },
  { id: "mla", label: "MLA 9" },
  { id: "chicago", label: "Chicago (notes)" },
];

/** MLA month abbreviations (MLA Handbook: May, June and July are not abbreviated). */
const MLA_MONTHS = ["Jan.", "Feb.", "Mar.", "Apr.", "May", "June", "July", "Aug.", "Sept.", "Oct.", "Nov.", "Dec."];
const FULL_MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

/** Parse yyyy-mm-dd into {year, monthIndex, day} or null. */
export function parseDateParts(value) {
  if (typeof value !== "string" || !DATE_PATTERN.test(value)) return null;
  const [year, month, day] = value.split("-").map(Number);
  if (month < 1 || month > 12 || day < 1 || day > 31) return null;
  const check = new Date(Date.UTC(year, month - 1, day));
  if (check.getUTCMonth() !== month - 1 || check.getUTCDate() !== day) return null;
  return { year, monthIndex: month - 1, day };
}

const MAX_FIELD = 200;

/**
 * Build the attribution.
 * @param {object} input
 * @param {string} input.styleId       One of STYLE_OPTIONS ids.
 * @param {string} input.toolName      e.g. "ChatGPT" (required).
 * @param {string} input.provider      e.g. "OpenAI" (required).
 * @param {string} [input.versionLabel] e.g. "GPT-4o" or "Mar 14 version".
 * @param {string} input.dateUsed      yyyy-mm-dd date the output was generated (required).
 * @param {string} [input.url]         Tool URL.
 * @param {string} [input.promptSummary] The prompt, for MLA's title slot.
 * @param {string} [input.usageDescription] What the AI helped with, for the acknowledgement.
 * @returns {{reference:string, inText:string, acknowledgement:string, note:string}|{error:string}}
 */
export function buildAttribution({
  styleId,
  toolName,
  provider,
  versionLabel = "",
  dateUsed,
  url = "",
  promptSummary = "",
  usageDescription = "",
}) {
  const style = STYLE_OPTIONS.find((s) => s.id === styleId);
  if (!style) return { error: "Choose a citation style." };

  const tool = String(toolName || "").trim();
  const prov = String(provider || "").trim();
  if (!tool) return { error: "Enter the AI tool's name (for example, ChatGPT)." };
  if (!prov) return { error: "Enter the provider (for example, OpenAI)." };
  for (const [label, v] of [["tool name", tool], ["provider", prov], ["version", versionLabel], ["URL", url]]) {
    if (String(v).length > MAX_FIELD) return { error: `Keep the ${label} under ${MAX_FIELD} characters.` };
  }

  const date = parseDateParts(dateUsed);
  if (!date) return { error: "Enter the date the output was generated, in yyyy-mm-dd form." };

  const version = String(versionLabel).trim();
  const link = String(url).trim();
  const prompt = String(promptSummary).trim();
  const usage = String(usageDescription).trim() || "assistance with drafting and editing";

  let reference = "";
  let inText = "";

  if (style.id === "apa") {
    // APA 7: Provider. (Year). Tool (Version) [Large language model]. URL
    const versionPart = version ? ` (${version})` : "";
    const urlPart = link ? ` ${link}` : "";
    reference = `${prov}. (${date.year}). ${tool}${versionPart} [Large language model].${urlPart}`.trim();
    inText = `(${prov}, ${date.year})`;
  } else if (style.id === "mla") {
    // MLA 9: "Prompt" prompt. Tool, Version, Provider, Day Mon. Year, URL.
    const mlaDate = `${date.day} ${MLA_MONTHS[date.monthIndex]} ${date.year}`;
    const promptPart = prompt ? `"${prompt}" prompt. ` : "";
    const versionPart = version ? `${version}, ` : "";
    const urlPart = link ? `, ${link.replace(/^https?:\/\//, "")}` : "";
    reference = `${promptPart}${tool}, ${versionPart}${prov}, ${mlaDate}${urlPart}.`;
    inText = `(${prompt ? `"${prompt.length > 40 ? `${prompt.slice(0, 40)}…` : prompt}"` : tool})`;
  } else {
    // Chicago: note only — Text generated by Tool, Provider, Month Day, Year, URL.
    const chiDate = `${FULL_MONTHS[date.monthIndex]} ${date.day}, ${date.year}`;
    const urlPart = link ? `, ${link}` : "";
    reference = `Text generated by ${tool}, ${prov}, ${chiDate}${urlPart}.`;
    inText = "Cited in a numbered footnote or endnote; Chicago advises against a bibliography entry for AI output.";
  }

  const acknowledgement = `During the preparation of this work, the author used ${tool}${version ? ` (${version})` : ""} (${prov}) for ${usage}. After using this tool, the author reviewed and edited the content as needed and takes full responsibility for the final work.`;

  const note =
    style.id === "chicago"
      ? "Chicago treats AI output like personal communication: cite it in a note, and include the prompt in the note if it is not given in the text."
      : style.id === "mla"
        ? "MLA places your prompt in the title-of-source slot; keep the quoted prompt short and descriptive."
        : "APA treats the model's provider as the author; the version goes in parentheses after the tool name.";

  return { reference, inText, acknowledgement, note, styleLabel: style.label };
}
