const seo = {
  title: "Cite ChatGPT or Any AI Tool in APA 7, MLA 9, Chicago",
  metaDescription:
    "Build an APA 7, MLA 9 or Chicago note citation for a generative AI tool, with the matching in-text form and a journal-style acknowledgement sentence.",
  steps: [
    "Pick a Citation style — APA 7, MLA 9 or Chicago (notes) — then fill in the AI tool name, Provider, Model or version, and the Date the output was generated.",
    "Add the Tool URL, a Prompt summary (MLA puts the prompt in the title-of-source slot) and what the AI helped with for the acknowledgement sentence.",
    "Read the Reference entry, the In-text / note usage line, the Acknowledgement statement and the Style note, then press Copy all to take the three together.",
  ],
  intro:
    "The AI Attribution Statement Builder formats a citation for a generative-AI tool in APA 7, MLA 9 or Chicago style, following each style body's published guidance on citing AI — the APA Style blog's 'How to cite ChatGPT' pattern, the MLA Style Center's prompt-as-title template, and Chicago's note-only approach. It also produces a journal-style acknowledgement sentence stating what the tool did and that the author takes responsibility. It is built for students and researchers who used AI assistance and need to attribute it correctly.",
  useCases: [
    "A psychology student citing a ChatGPT-generated explanation in APA 7 for a term paper reference list",
    "An English literature student building an MLA 9 entry with the exact prompt in the title-of-source slot",
    "A researcher adding the acknowledgement sentence journals such as Elsevier and Springer Nature titles ask for when AI improved readability",
  ],
  benefits: [
    ["Three official patterns", "APA 7, MLA 9 and Chicago formats generated from the same inputs, each following the style body's own template."],
    ["In-text form included", "Shows the matching in-text citation for APA and MLA, and the note-only rule for Chicago."],
    ["Journal-ready acknowledgement", "Adds a disclosure sentence of the kind publisher author policies require, with a responsibility statement."],
  ],
  faqs: [
    [
      "How do I cite ChatGPT in APA 7?",
      "The APA pattern is: OpenAI. (Year). ChatGPT (Version) [Large language model]. URL — with the in-text citation (OpenAI, Year). APA treats the provider (OpenAI) as the author and puts the model version in parentheses after the tool name, per the APA Style blog's 2023 guidance on citing ChatGPT.",
    ],
    [
      "How does MLA style cite generative AI?",
      "MLA puts your prompt in the title-of-source slot, in quotation marks, followed by the tool as container: \"Your prompt\" prompt. ChatGPT, version, OpenAI, day month year, URL. MLA abbreviates months except May, June and July, and dates use day-month-year order.",
    ],
    [
      "Does Chicago style put AI in the bibliography?",
      "No. The Chicago Manual of Style's guidance treats AI output like personal communication: cite it in a numbered footnote or endnote — 'Text generated by ChatGPT, OpenAI, Month Day, Year, URL' — and do not create a bibliography entry. Include the prompt in the note if it is not already given in your text.",
    ],
    [
      "Do journals require an AI acknowledgement statement?",
      "Many do when generative AI contributed to the writing. Publisher policies such as Elsevier's and Springer Nature's ask authors to disclose the tool and purpose in the manuscript (typically in an acknowledgements or declaration section) and to confirm the authors reviewed the output and take full responsibility; most also prohibit listing an AI as an author. Check the specific journal's author guidelines before submission.",
    ],
  ],
};

export default seo;
