const seo = {
  title: "Color Converter: HEX, RGB, HSL, HSV, CMYK & Contrast",
  metaDescription:
    "Convert one color to HEX, RGB, RGBA, HSL, HSLA, HSV and CMYK at once, with WCAG contrast scores against white and black plus hue-rotated harmonies.",
  intro:
    "Color Conversions turns one colour into seven notations at once — HEX, RGB, RGBA, HSL, HSLA, HSV and CMYK — and adds the two things you usually need next: its contrast ratio against white and black scored to WCAG, and a set of harmonies derived by rotating the hue. RGB and HSL sliders plus an alpha slider let you nudge the value and watch every output update live. It suits developers and designers picking a colour rather than merely translating one they already have.",
  useCases: [
    "You are picking an accent colour and want to know immediately whether white text on it clears 4.5:1 before you commit it to a button.",
    "You have one brand HEX and need a complementary and two analogous colours to build the rest of a palette around it.",
    "You are working in a design app that speaks HSV while your CSS wants HSL, and you want both readings of the same colour side by side.",
  ],
  benefits: [
    ["Includes HSV, not just HSL", "Design software and colour pickers usually work in hue-saturation-value, so the HSV reading saves a second conversion step."],
    ["Contrast scored as you pick", "Every colour is rated against white and black on the WCAG scale — AAA at 7:1, AA at 4.5:1, large-text AA at 3:1 — so unusable choices are caught at the point of choosing."],
    ["Harmonies and a shade ramp built in", "Complementary, analogous, triadic and tetradic swatches are generated by hue rotation, plus a five-step lightness ramp from the same base colour."],
  ],
  faqs: [
    [
      "What is the difference between HSL and HSV?",
      "They share hue but differ in the third channel: HSL's lightness reaches pure white at 100 percent, whereas HSV's value reaches the most vivid version of the hue, with white only when saturation is also zero. Both are shown here for the same colour so you can move between CSS and design tools without guessing.",
    ],
    [
      "How are the colour harmonies calculated?",
      "By rotating the hue in HSL while holding saturation and lightness. Complementary is 180 degrees away, analogous is plus and minus 30, triadic is plus and minus 120, and tetradic uses plus and minus 60 together with 180.",
    ],
    [
      "What do the AA and AAA labels next to the swatch mean?",
      "They are the WCAG contrast grades for your colour against white and against black. 7:1 or higher is AAA, 4.5:1 or higher is AA for body text, 3:1 or higher passes only for large text, and anything below 3:1 is marked a fail.",
    ],
    [
      "Can I enter a colour with transparency?",
      "Yes. Eight-digit hex and rgba()/hsla() strings are accepted, and the alpha slider runs from 0 to 1 in steps of 0.01. Alpha appears in the HEX, RGBA and HSLA outputs; RGB, HSL, HSV and CMYK are opaque by definition.",
    ],
  ],
};

export default seo;
