export const batchGenerationConfig = {
  storageKey: "altftools:batch-generation-tool:v1",
  maxQuantity: 500,
  defaultExportName: "batch-generation",
  defaultTemplateNamePrefix: "Template",
  defaultItemSlug: "item",
  defaultFieldKey: "field",
  defaultBatchName: "batch",
  previewLimit: 8,
  copyPreviewLimit: 10,
  validationLimit: 4,
  textDividerMaxLength: 80,
  textDividerFallbackLength: 8,
  messageTimeout: 3500,
  templateHistoryLimit: 30,
  batchHistoryLimit: 40,
  defaultConfig: {
    name: "",
    type: "",
    category: "",
    mode: "Sequential",
    purpose: "",
    quantity: 10,
    namingPattern: "{batch}-{index}",
    variationSeed: "",
    template: "",
  },
  defaultField: { label: "", key: "", value: "", required: true },
  defaultFilters: { query: "", type: "All", sort: "newest" },
  workflowModes: ["Sequential", "Variations", "Mapped Data", "Custom"],
  sortOptions: ["newest", "name", "quantity"],
  baseHistoryType: "All",
  tokens: ["{batch}", "{index}", "{type}", "{category}", "{purpose}", "{seed}"],
  placeholders: {
    batchName: "Launch captions May",
    generationType: "Text, QR, Content, Custom",
    category: "Marketing, Docs, Internal",
    purpose: "Generate launch snippets",
    namingPattern: "{batch}-{index}",
    variationSeed: "Tone, audience, campaign, sprint",
    fieldValue: "Use {index} for per-item variation",
    template: "Write content with variables: {title}, {category}, {index}, {seed}",
    searchHistory: "Search history",
  },
  labels: {
    batchSetup: "Batch Setup",
    batchName: "Batch name",
    generationType: "Generation type",
    category: "Category",
    workflowMode: "Workflow mode",
    purpose: "Batch purpose",
    quantity: "Quantity",
    namingLogic: "Naming logic",
    variationSeed: "Variation seed",
    dynamicInputs: "Dynamic Inputs",
    addField: "Add field",
    label: "Label",
    variableKey: "Variable key",
    value: "Value",
    required: "Required",
    templateEngine: "Template Engine",
    templateContent: "Template content",
    save: "Save",
    batch: "Batch",
    reset: "Reset",
    queueDashboard: "Queue Dashboard",
    pending: "Pending",
    failed: "Failed",
    size: "Size",
    speed: "Speed",
    exportPanel: "Export Panel",
    analytics: "Analytics",
    successRate: "Success rate",
    templatesSaved: "Templates saved",
    batchesSaved: "Batches saved",
    variablesMapped: "Variables mapped",
    previewValidation: "Live Preview & Validation",
    templateManager: "Template Manager",
    savedBatches: "Saved Batches",
    total: "Total",
    generated: "Generated",
    health: "Health",
    export: "Export",
    ready: "Ready",
    blocked: "Blocked",
    noType: "No type",
    noCategory: "No category",
    noOutput: "No output generated yet.",
    missing: "Missing",
    fields: "fields",
    load: "Load",
    delete: "Delete",
    zip: "ZIP",
    csv: "CSV",
    txt: "TXT",
    copy: "Copy",
    dismissMessage: "Dismiss message",
    removeField: "Remove field",
  },
  statuses: {
    generated: "generated",
    failed: "failed",
    pending: "pending",
  },
  statusStyles: {
    generated: "border-emerald-500/25 bg-emerald-500/15 text-emerald-600 dark:text-emerald-200",
    failed: "border-rose-500/25 bg-rose-500/15 text-rose-600 dark:text-rose-200",
    pending: "border-amber-500/25 bg-amber-500/15 text-amber-600 dark:text-amber-200",
  },
  byteUnits: {
    empty: "0 B",
    bytes: "B",
    kilobytes: "KB",
    megabytes: "MB",
  },
  messages: {
    templateContentRequired: "Add template content before saving a template.",
    templateSaved: "Template saved.",
    templateLoaded: "Template loaded into the live workspace.",
    batchSaved: "Batch saved to local history.",
    batchRestored: "Saved batch restored.",
    workspaceReset: "Workspace reset.",
    resolveBeforeZip: "Resolve failed outputs before ZIP export.",
    resolveBeforeCsv: "Resolve failed outputs before CSV export.",
    resolveBeforeTxt: "Resolve failed outputs before TXT export.",
    zipExported: "ZIP exported.",
    csvExported: "CSV exported.",
    txtExported: "TXT exported.",
    previewCopied: "Visible preview copied.",
    exportReady: "Export package is ready.",
    exportBlocked: "Complete validation to unlock exports.",
    emptyFields: "Add fields to expose template variables such as {title}, {description}, or {keywords}.",
    emptyPreview: "Preview appears as soon as quantity and template data exist.",
    emptyTemplates: "Saved templates will appear here after you create one.",
    emptyHistory: "No saved batches match the current filters.",
  },
  validationMessages: {
    nameRequired: "Batch name is required.",
    typeRequired: "Generation type is required.",
    categoryRequired: "Category is required.",
    purposeRequired: "Batch purpose is required.",
    templateRequired: "Template content is required.",
    quantityRange: (maxQuantity) => `Quantity must be between 1 and ${maxQuantity}.`,
    fieldLabelRequired: "Every dynamic field needs a label.",
    fieldKeyRequired: (label) => `Field "${label || "Untitled"}" needs a variable key.`,
    requiredFieldEmpty: (label) => `Required field "${label}" is empty.`,
    duplicateKeys: "Variable keys must be unique.",
  },
  fileTypes: {
    csv: "text/csv;charset=utf-8",
    txt: "text/plain;charset=utf-8",
  },
  exportFiles: {
    manifest: "manifest.json",
    txtExtension: ".txt",
    csvExtension: ".csv",
    zipExtension: ".zip",
  },
  csvHeaders: ["index", "title", "type", "category", "status", "content"],
  header: {
    eyebrow: "Batch Generation Tool",
    title: "Batch Generation Tool",
    description:
      "Configure fields, map variables, generate real outputs, validate the queue, save reusable workflows, and export everything directly from the browser.",
  },
};
