const seo = {
  intro:
    "The Pixar Style Generator turns a photo into a glossy 3D animated character portrait by sending it to the Flux image model with a fixed claymation style prompt, then letting you fine-tune the result with local canvas shaders. Load a picture from your device or paste a direct image URL, and you get a 512x512 PNG with three live controls: emboss depth for rounded clay edges, bloom glow for the soft cinema focus, and a vibrancy multiplier for toy-bright colour. It is aimed at anyone who wants an animated-film avatar without opening a 3D suite or writing prompts.",
  useCases: [
    "You want a stylised avatar for a Discord or WhatsApp profile and would rather upload one selfie than experiment with prompt wording in an image model.",
    "You are making a birthday card or class poster and need everyone's photo rendered in the same glossy animated look so the layout feels consistent.",
    "You already have an AI render but the skin tone looks flat, so you nudge vibrancy up toward 2.2x and add a few pixels of emboss to get the moulded plastic-toy edge back.",
  ],
  benefits: [
    [
      "Two paths to a result",
      "The Flux model does the character restyling, while the local canvas filters keep working on the original photo even if the model call fails.",
    ],
    [
      "Live shader controls",
      "Emboss depth (0-6px), bloom (0-45px) and vibrancy (1x-2.2x) re-render the preview as you drag, so you tune the look instead of re-prompting.",
    ],
    [
      "Square-safe framing",
      "Every source image is centre-cropped and scaled to a 512x512 canvas, so downloads drop straight into avatar slots without extra cropping.",
    ],
  ],
  faqs: [
    [
      "What size image does it produce?",
      "512 by 512 pixels, saved as PNG. Both the AI-generated render and the locally shaded canvas use the same 512px square, and the source photo is centre-cropped with a scale factor that covers the full frame rather than letterboxing it.",
    ],
    [
      "Does my photo get uploaded anywhere?",
      "Yes, and it happens as soon as you load one. Uploading a file or pasting a URL sends the image to image.pollinations.ai, which runs the Flux model that produces the character render — the AI conversion fires automatically on load, so there is no photo-in, local-only mode. The emboss, bloom and vibrancy sliders, by contrast, run purely on a local canvas and never transmit the image.",
    ],
    [
      "What do the three sliders actually change?",
      "Emboss depth offsets a copy of the canvas by 0-6 pixels in overlay mode to fake rounded clay lighting, bloom re-draws the canvas through a 0-45px blur in screen mode at 25% alpha for the soft glow, and vibrancy pushes each pixel away from its luminance value by a factor of 1x to 2.2x.",
    ],
    [
      "Can I use the output commercially?",
      "Treat that as an open question rather than a yes. The style is generated by a third-party model from your input image, so rights depend on that model's terms and on whether you own the source photo and any likeness in it; check both before using a render in paid work.",
    ],
  ],
};

export default seo;
