"use client";

export const NAKSHATRA_LIST = [
  { id: 0, name: "Ashwini", deity: "Ashwini Kumaras", range: "0°00' – 13°20' Aries", symbol: "Horse head", gana: "Deva" },
  { id: 1, name: "Bharani", deity: "Yama", range: "13°20' – 26°40' Aries", symbol: "Yoni", gana: "Manushya" },
  { id: 2, name: "Krittika", deity: "Agni", range: "26°40' Aries – 10°00' Taurus", symbol: "Razor", gana: "Rakshasa" },
  { id: 3, name: "Rohini", deity: "Brahma", range: "10°00' – 23°20' Taurus", symbol: "Chariot", gana: "Manushya" },
  { id: 4, name: "Mrigashira", deity: "Chandra", range: "23°20' Taurus – 6°40' Gemini", symbol: "Deer head", gana: "Deva" },
  { id: 5, name: "Ardra", deity: "Rudra", range: "6°40' – 20°00' Gemini", symbol: "Teardrop", gana: "Manushya" },
  { id: 6, name: "Punarvasu", deity: "Aditi", range: "20°00' Gemini – 3°20' Cancer", symbol: "Quiver", gana: "Deva" },
  { id: 7, name: "Pushya", deity: "Brihaspati", range: "3°20' – 16°40' Cancer", symbol: "Lotus", gana: "Deva" },
  { id: 8, name: "Ashlesha", deity: "Shesha", range: "16°40' – 30°00' Cancer", symbol: "Serpent", gana: "Rakshasa" },
  { id: 9, name: "Magha", deity: "Pitris", range: "0°00' – 13°20' Leo", symbol: "Throne", gana: "Rakshasa" },
  { id: 10, name: "Purva Phalguni", deity: "Bhaga", range: "13°20' – 26°40' Leo", symbol: "Swing", gana: "Manushya" },
  { id: 11, name: "Uttara Phalguni", deity: "Aryaman", range: "26°40' Leo – 10°00' Virgo", symbol: "Cot", gana: "Manushya" },
  { id: 12, name: "Hasta", deity: "Savitr", range: "10°00' – 23°20' Virgo", symbol: "Hand", gana: "Deva" },
  { id: 13, name: "Chitra", deity: "Tvashtr", range: "23°20' Virgo – 6°40' Libra", symbol: "Pearl", gana: "Rakshasa" },
  { id: 14, name: "Swati", deity: "Vayu", range: "6°40' – 20°00' Libra", symbol: "Coral", gana: "Deva" },
  { id: 15, name: "Vishakha", deity: "Indra-Agni", range: "20°00' Libra – 3°20' Scorpio", symbol: "Potter's wheel", gana: "Rakshasa" },
  { id: 16, name: "Anuradha", deity: "Mitra", range: "3°20' – 16°40' Scorpio", symbol: "Lotus", gana: "Deva" },
  { id: 17, name: "Jyeshtha", deity: "Indra", range: "16°40' – 30°00' Scorpio", symbol: "Earring", gana: "Rakshasa" },
  { id: 18, name: "Mula", deity: "Nirriti", range: "0°00' – 13°20' Sagittarius", symbol: "Bunch of roots", gana: "Rakshasa" },
  { id: 19, name: "Purva Ashadha", deity: "Apas", range: "13°20' – 26°40' Sagittarius", symbol: "Fan", gana: "Manushya" },
  { id: 20, name: "Uttara Ashadha", deity: "Vishvadevas", range: "26°40' Sagittarius – 10°00' Capricorn", symbol: "Elephant tusk", gana: "Manushya" },
  { id: 21, name: "Shravana", deity: "Vishnu", range: "10°00' – 23°20' Capricorn", symbol: "Ear", gana: "Deva" },
  { id: 22, name: "Dhanishtha", deity: "Vasus", range: "23°20' Capricorn – 6°40' Aquarius", symbol: "Drum", gana: "Rakshasa" },
  { id: 23, name: "Shatabhisha", deity: "Varuna", range: "6°40' – 20°00' Aquarius", symbol: "Circle", gana: "Rakshasa" },
  { id: 24, name: "Purva Bhadrapada", deity: "Aja Ekapada", range: "20°00' Aquarius – 3°20' Pisces", symbol: "Sword", gana: "Manushya" },
  { id: 25, name: "Uttara Bhadrapada", deity: "Ahir Budhnya", range: "3°20' – 16°40' Pisces", symbol: "Twins", gana: "Manushya" },
  { id: 26, name: "Revati", deity: "Pushan", range: "16°40' – 30°00' Pisces", symbol: "Fish", gana: "Deva" },
];

export const TITHI_LIST = [
  "Pratipada", "Dwitiya", "Tritiya", "Chaturthi", "Panchami",
  "Shashthi", "Saptami", "Ashtami", "Navami", "Dashami",
  "Ekadashi", "Dwadashi", "Trayodashi", "Chaturdashi", "Purnima",
  "Pratipada", "Dwitiya", "Tritiya", "Chaturthi", "Panchami",
  "Shashthi", "Saptami", "Ashtami", "Navami", "Dashami",
  "Ekadashi", "Dwadashi", "Trayodashi", "Chaturdashi", "Amavasya",
];

export const TITHI_DETAILS = {
  "Pratipada": { paksha: "Shukla", deity: "Brahma", activity: "Start new ventures, ceremonies" },
  "Dwitiya": { paksha: "Shukla", deity: "Vidhatr", activity: "Building, foundation laying" },
  "Tritiya": { paksha: "Shukla", deity: "Ganesha", activity: "Marriage, creative work" },
  "Chaturthi": { paksha: "Shukla", deity: "Ganesha", activity: "Remove obstacles, new tasks" },
  "Panchami": { paksha: "Shukla", deity: "Nagas", activity: "Medical treatments, healing" },
  "Shashthi": { paksha: "Shukla", deity: "Kartikeya", activity: "Victory ceremonies, celebrations" },
  "Saptami": { paksha: "Shukla", deity: "Surya", activity: "Travel, purchase vehicles" },
  "Ashtami": { paksha: "Shukla", deity: "Rudra", activity: "Worship, fasting" },
  "Navami": { paksha: "Shukla", deity: "Durga", activity: "Spiritual practices, fasting" },
  "Dashami": { paksha: "Shukla", deity: "Yama", activity: "Travel, important work" },
  "Ekadashi": { paksha: "Shukla", deity: "Vishnu", activity: "Fasting, meditation, spiritual" },
  "Dwadashi": { paksha: "Shukla", deity: "Vishnu", activity: "Charity, religious ceremonies" },
  "Trayodashi": { paksha: "Shukla", deity: "Kama", activity: "Home improvement, celebrations" },
  "Chaturdashi": { paksha: "Shukla", deity: "Shiva", activity: "Offerings, spiritual cleansing" },
  "Purnima": { paksha: "Shukla", deity: "Chandra", activity: "Full moon rituals, meditation" },
  "Pratipada": { paksha: "Krishna", deity: "Brahma", activity: "Start new projects" },
  "Dwitiya": { paksha: "Krishna", deity: "Vidhatr", activity: "Construction, building" },
  "Tritiya": { paksha: "Krishna", deity: "Ganesha", activity: "Art, music, dance" },
  "Chaturthi": { paksha: "Krishna", deity: "Ganesha", activity: "Overcome difficulties" },
  "Panchami": { paksha: "Krishna", deity: "Nagas", activity: "Healing, detox" },
  "Shashthi": { paksha: "Krishna", deity: "Kartikeya", activity: "Competitions, debates" },
  "Saptami": { paksha: "Krishna", deity: "Surya", activity: "Property deals, major tasks" },
  "Ashtami": { paksha: "Krishna", deity: "Rudra", activity: "Fasting, ancestral offerings" },
  "Navami": { paksha: "Krishna", deity: "Durga", activity: "Fasting" },
  "Dashami": { paksha: "Krishna", deity: "Yama", activity: "Travel, loss recovery" },
  "Ekadashi": { paksha: "Krishna", deity: "Vishnu", activity: "Fasting, meditation" },
  "Dwadashi": { paksha: "Krishna", deity: "Vishnu", activity: "Charity" },
  "Trayodashi": { paksha: "Krishna", deity: "Kama", activity: "Home improvement" },
  "Chaturdashi": { paksha: "Krishna", deity: "Shiva", activity: "Cleansing, protection rituals" },
  "Amavasya": { paksha: "Krishna", deity: "Pitris", activity: "Ancestral offerings, meditation" },
};

export const YOGA_LIST = [
  "Vishkumbha", "Priti", "Ayushman", "Saubhagya", "Shobhana",
  "Atiganda", "Sukarma", "Dhriti", "Shoola", "Ganda",
  "Vriddhi", "Dhruva", "Vyaghata", "Harshana", "Vajra",
  "Siddhi", "Vyatipata", "Variyan", "Parigha", "Shiva",
  "Siddha", "Sadhya", "Shubha", "Shukla", "Brahma",
  "Mahendra", "Vaidhriti",
];

export const YOGA_MEANINGS = {
  "Vishkumbha": "Support — good for foundations",
  "Priti": "Affection — relationships and bonding",
  "Ayushman": "Longevity — health and wellness activities",
  "Saubhagya": "Good fortune — new ventures and investments",
  "Shobhana": "Splendour — celebrations and social events",
  "Atiganda": "Danger — avoid risky ventures",
  "Sukarma": "Virtue — charity and spiritual work",
  "Dhriti": "Steadiness — long-term planning",
  "Shoola": "Pain — avoid confrontations and travel",
  "Ganda": "Knot — confusion, avoid major decisions",
  "Vriddhi": "Growth — expansion and investments",
  "Dhruva": "Permanent — real estate, long commitments",
  "Vyaghata": "Strike — conflicts, avoid arguments",
  "Harshana": "Joy — celebrations, entertainment",
  "Vajra": "Thunderbolt — sudden events, caution needed",
  "Siddhi": "Accomplishment — great for all activities",
  "Vyatipata": "Calamity — avoid travel and new work",
  "Variyan": "Grace — spiritual practices, meditation",
  "Parigha": "Obstacle — challenges, need persistence",
  "Shiva": "Auspicious — meditation, spiritual pursuits",
  "Siddha": "Attainment — all activities favoured",
  "Sadhya": "Achievable — good for negotiations",
  "Shubha": "Auspicious — marriages, celebrations",
  "Shukla": "Bright — all positive activities",
  "Brahma": "Creative — art, design, innovation",
  "Mahendra": "Royal — leadership, authority tasks",
  "Vaidhriti": "Separator — avoid new beginnings",
};

export const KARANA_LIST = [
  { id: 0, name: "Bava", type: "Good" },
  { id: 1, name: "Balava", type: "Good" },
  { id: 2, name: "Kaulava", type: "Good" },
  { id: 3, name: "Taitula", type: "Good" },
  { id: 4, name: "Garaja", type: "Good" },
  { id: 5, name: "Vanija", type: "Good" },
  { id: 6, name: "Vishti", type: "Inauspicious" },
  { id: 7, name: "Shakuni", type: "Inauspicious" },
  { id: 8, name: "Chatushpada", type: "Inauspicious" },
  { id: 9, name: "Naga", type: "Inauspicious" },
  { id: 10, name: "Kimstughna", type: "Good" },
];

export const RASHI_LIST = [
  { id: 0, name: "Mesha", english: "Aries", symbol: "Ram", element: "Fire", lord: "Mangal" },
  { id: 1, name: "Vrishabha", english: "Taurus", symbol: "Bull", element: "Earth", lord: "Shukra" },
  { id: 2, name: "Mithuna", english: "Gemini", symbol: "Twins", element: "Air", lord: "Budha" },
  { id: 3, name: "Karka", english: "Cancer", symbol: "Crab", element: "Water", lord: "Chandra" },
  { id: 4, name: "Simha", english: "Leo", symbol: "Lion", element: "Fire", lord: "Surya" },
  { id: 5, name: "Kanya", english: "Virgo", symbol: "Virgin", element: "Earth", lord: "Budha" },
  { id: 6, name: "Tula", english: "Libra", symbol: "Scale", element: "Air", lord: "Shukra" },
  { id: 7, name: "Vrishchika", english: "Scorpio", symbol: "Scorpion", element: "Water", lord: "Mangal" },
  { id: 8, name: "Dhanu", english: "Sagittarius", symbol: "Bow", element: "Fire", lord: "Guru" },
  { id: 9, name: "Makara", english: "Capricorn", symbol: "Crocodile", element: "Earth", lord: "Shani" },
  { id: 10, name: "Kumbha", english: "Aquarius", symbol: "Pot", element: "Air", lord: "Shani" },
  { id: 11, name: "Meena", english: "Pisces", symbol: "Fish", element: "Water", lord: "Guru" },
];

export const VASARA_LORDS = [
  { day: 0, name: "Sunday", hindi: "Ravivar", lord: "Surya", isGood: true },
  { day: 1, name: "Monday", hindi: "Somavar", lord: "Chandra", isGood: true },
  { day: 2, name: "Tuesday", hindi: "Mangalvar", lord: "Mangal", isGood: true },
  { day: 3, name: "Wednesday", hindi: "Budhvar", lord: "Budha", isGood: true },
  { day: 4, name: "Thursday", hindi: "Guruvár", lord: "Guru", isGood: true },
  { day: 5, name: "Friday", hindi: "Shukravar", lord: "Shukra", isGood: true },
  { day: 6, name: "Saturday", hindi: "Shanivar", lord: "Shani", isGood: false },
];

export const MUHURTA_TIMINGS = [
  { name: "Brahma Muhurta", start: "04:24", end: "05:12", description: "Best for meditation, study, spiritual practice" },
  { name: "Abhijit Muhurta", start: "11:45", end: "12:33", description: "Best for new beginnings, important tasks" },
  { name: "Amrit Kaal", start: "06:00", end: "07:30", description: "Auspicious window for all activities" },
  { name: "Rahu Kaal", start: "07:30", end: "09:00", description: "Avoid important activities. Not auspicious" },
  { name: "Gulik Kaal", start: "15:00", end: "16:30", description: "Avoid crucial decisions. Medium impact" },
  { name: "Yamaganda", start: "12:00", end: "13:30", description: "Avoid travel and important tasks" },
];

export const MONTH_NAMES = [
  "Chaitra", "Vaishakha", "Jyeshtha", "Ashadha",
  "Shravana", "Bhadrapada", "Ashvina", "Kartika",
  "Margashirsha", "Pausha", "Magha", "Phalguna",
];
