/**
 * Indian English Loanword Finder — data and pure query helpers.
 *
 * Every entry is an everyday English word whose ancestry runs back to an
 * Indian-subcontinent language: Sanskrit, Hindi/Urdu, Tamil, Malayalam,
 * Telugu, Marathi, Bengali or Odia. Several arrived through an intermediary —
 * Portuguese traders on the west coast, Persian through Urdu, or Greek and
 * Arabic for the very oldest spice and gem words — and the route is recorded.
 *
 * `firstUse` is an approximate first-attestation year in English, rounded to
 * the decade, and is meant for sorting and grouping rather than citation.
 * `certainty` is "settled" where the derivation is generally agreed and
 * "debated" where reputable sources disagree; the tool never presents a
 * disputed etymology as fact.
 */

export const DOMAINS = [
  { id: "food", label: "Food & drink" },
  { id: "clothing", label: "Clothing" },
  { id: "material", label: "Textiles & materials" },
  { id: "nature", label: "Animals & landscape" },
  { id: "society", label: "People & society" },
  { id: "religion", label: "Religion & philosophy" },
  { id: "transport", label: "Boats & transport" },
  { id: "home", label: "House & household" },
  { id: "crime", label: "Crime & disorder" },
  { id: "slang", label: "Army & colonial slang" },
];

export const CERTAINTIES = [
  { id: "settled", label: "Generally agreed" },
  { id: "debated", label: "Disputed by scholars" },
];

export const LOANWORDS = [
  {
    id: "pepper",
    word: "pepper",
    sourceLanguage: "Sanskrit",
    sourceWord: "पिप्पली pippalī",
    sourceMeaning: "long pepper",
    route: "Sanskrit → Greek peperi → Latin piper → Old English pipor",
    firstUse: 900,
    domain: "food",
    certainty: "settled",
    note: "One of the oldest Indian words in English, in the language centuries before any English ship reached India.",
  },
  {
    id: "ginger",
    word: "ginger",
    sourceLanguage: "Tamil",
    sourceWord: "இஞ்சி வேர் iñci-vēr",
    sourceMeaning: "ginger root",
    route: "Dravidian → Pali siṅgivera → Greek → Latin → Old English gingifer",
    firstUse: 1000,
    domain: "food",
    certainty: "settled",
    note: "The Tamil root iñci survives inside the modern English spelling after four separate languages handled it.",
  },
  {
    id: "sugar",
    word: "sugar",
    sourceLanguage: "Sanskrit",
    sourceWord: "शर्करा śarkarā",
    sourceMeaning: "gravel, ground sugar",
    route: "Sanskrit → Persian shakar → Arabic sukkar → Italian → Old French",
    firstUse: 1300,
    domain: "food",
    certainty: "settled",
    note: "The same root also produced 'saccharin' through the Greek and Latin form sakcharon.",
  },
  {
    id: "camphor",
    word: "camphor",
    sourceLanguage: "Sanskrit",
    sourceWord: "कर्पूर karpūra",
    sourceMeaning: "camphor",
    route: "Sanskrit → Arabic kāfūr → Medieval Latin camfora",
    firstUse: 1300,
    domain: "material",
    certainty: "settled",
    note: "Traded west as an aromatic and a medicine long before it was used in English households.",
  },
  {
    id: "orange",
    word: "orange",
    sourceLanguage: "Sanskrit",
    sourceWord: "नारङ्ग nāraṅga",
    sourceMeaning: "orange tree",
    route: "Sanskrit → Persian nārang → Arabic nāranj → Old French orenge",
    firstUse: 1380,
    domain: "food",
    certainty: "settled",
    note: "English lost the initial n- because 'a norange' was reanalysed as 'an orange'.",
  },
  {
    id: "musk",
    word: "musk",
    sourceLanguage: "Sanskrit",
    sourceWord: "मुष्क muṣka",
    sourceMeaning: "testicle, from the shape of the musk deer's gland",
    route: "Sanskrit → Persian mushk → Late Latin muscus",
    firstUse: 1390,
    domain: "material",
    certainty: "settled",
    note: "The anatomical sense of the Sanskrit original explains a name that otherwise looks arbitrary.",
  },
  {
    id: "crimson",
    word: "crimson",
    sourceLanguage: "Sanskrit",
    sourceWord: "कृमिज kṛmi-ja",
    sourceMeaning: "produced by a worm",
    route: "Sanskrit → Arabic qirmiz → Old Spanish cremesin",
    firstUse: 1400,
    domain: "material",
    certainty: "settled",
    note: "The dye came from the kermes scale insect, so the colour is literally named after the creature that made it.",
  },
  {
    id: "candy",
    word: "candy",
    sourceLanguage: "Sanskrit",
    sourceWord: "खण्ड khaṇḍa",
    sourceMeaning: "piece, fragment; crystallised sugar",
    route: "Sanskrit → Persian qand → Arabic qandī → Old French sucre candi",
    firstUse: 1420,
    domain: "food",
    certainty: "settled",
    note: "Originally 'sugar candy', meaning sugar boiled and left to crystallise in pieces.",
  },
  {
    id: "lac",
    word: "lacquer",
    sourceLanguage: "Sanskrit",
    sourceWord: "लाक्षा lākṣā",
    sourceMeaning: "the resin secreted by lac insects",
    route: "Sanskrit → Persian lāk → Portuguese laca",
    firstUse: 1550,
    domain: "material",
    certainty: "settled",
    note: "'Lac', 'lacquer' and 'shellac' all descend from the same insect resin.",
  },
  {
    id: "calico",
    word: "calico",
    sourceLanguage: "Malayalam",
    sourceWord: "Kozhikode",
    sourceMeaning: "the port city on the Malabar coast",
    route: "Place name → Portuguese Calicut → English calico",
    firstUse: 1570,
    domain: "material",
    certainty: "settled",
    note: "Named for its export port rather than the cloth itself, the same way denim was named for Nîmes.",
  },
  {
    id: "mango",
    word: "mango",
    sourceLanguage: "Tamil / Malayalam",
    sourceWord: "மாங்காய் māṅkāy",
    sourceMeaning: "mango fruit",
    route: "Dravidian → Portuguese manga → English",
    firstUse: 1580,
    domain: "food",
    certainty: "settled",
    note: "Portuguese traders on the Malabar coast carried the word to Europe in the 16th century.",
  },
  {
    id: "coir",
    word: "coir",
    sourceLanguage: "Malayalam",
    sourceWord: "കയർ kayaṟ",
    sourceMeaning: "cord, rope",
    route: "Malayalam → Portuguese cairo → English",
    firstUse: 1580,
    domain: "material",
    certainty: "settled",
    note: "Coconut-husk rope was a major Kerala export, so the local word for rope became the English word for the fibre.",
  },
  {
    id: "copra",
    word: "copra",
    sourceLanguage: "Malayalam",
    sourceWord: "കൊപ്ര koppara",
    sourceMeaning: "dried coconut kernel",
    route: "Malayalam → Portuguese copra → English",
    firstUse: 1580,
    domain: "food",
    certainty: "settled",
    note: "Still the standard commodity term in the international coconut oil trade.",
  },
  {
    id: "palanquin",
    word: "palanquin",
    sourceLanguage: "Sanskrit",
    sourceWord: "पर्यङ्क paryaṅka",
    sourceMeaning: "bed, couch",
    route: "Sanskrit → Hindi pālkī → Portuguese palanquim",
    firstUse: 1580,
    domain: "transport",
    certainty: "settled",
    note: "The Hindi 'palki' is the same word, borrowed directly rather than through Portuguese.",
  },
  {
    id: "opal",
    word: "opal",
    sourceLanguage: "Sanskrit",
    sourceWord: "उपल upala",
    sourceMeaning: "stone, gem",
    route: "Sanskrit → Greek opallios → Latin opalus",
    firstUse: 1590,
    domain: "material",
    certainty: "debated",
    note: "The Sanskrit link is widely repeated but not universally accepted; some etymologists treat the Greek form as the earliest secure step.",
  },
  {
    id: "curry",
    word: "curry",
    sourceLanguage: "Tamil",
    sourceWord: "கறி kaṟi",
    sourceMeaning: "sauce or relish eaten with rice",
    route: "Tamil → Portuguese caril → English",
    firstUse: 1600,
    domain: "food",
    certainty: "settled",
    note: "The Tamil original names a specific accompaniment, not the broad category the English word came to cover.",
  },
  {
    id: "chintz",
    word: "chintz",
    sourceLanguage: "Hindi",
    sourceWord: "छींट chīṇṭ",
    sourceMeaning: "spotted or sprayed cloth",
    route: "Hindi → English (originally the plural 'chints')",
    firstUse: 1610,
    domain: "material",
    certainty: "settled",
    note: "English took the Hindi plural as a singular, which is why there is no form 'chint'.",
  },
  {
    id: "cummerbund",
    word: "cummerbund",
    sourceLanguage: "Urdu (from Persian)",
    sourceWord: "कमरबंद kamar-band",
    sourceMeaning: "waist-band",
    route: "Persian → Urdu → Anglo-Indian English",
    firstUse: 1610,
    domain: "clothing",
    certainty: "settled",
    note: "Adopted into formal Western evening dress from the sashes worn in colonial India.",
  },
  {
    id: "toddy",
    word: "toddy",
    sourceLanguage: "Hindi",
    sourceWord: "ताड़ी tāṛī",
    sourceMeaning: "sap of the palmyra palm",
    route: "Hindi tāṛ (palm) → tāṛī → English",
    firstUse: 1610,
    domain: "food",
    certainty: "settled",
    note: "The 'hot toddy' sense developed later in Britain, long after the palm-sap original.",
  },
  {
    id: "guru",
    word: "guru",
    sourceLanguage: "Sanskrit",
    sourceWord: "गुरु guru",
    sourceMeaning: "heavy, weighty; hence a venerable teacher",
    route: "Sanskrit → Hindi → English",
    firstUse: 1610,
    domain: "religion",
    certainty: "settled",
    note: "The weakened business sense — 'a management guru' — is a 20th-century development.",
  },
  {
    id: "pariah",
    word: "pariah",
    sourceLanguage: "Tamil",
    sourceWord: "பறையர் paṟaiyar",
    sourceMeaning: "drummer, from paṟai, a drum",
    route: "Tamil → Anglo-Indian English",
    firstUse: 1610,
    domain: "society",
    certainty: "settled",
    note: "Originally a specific caste name; English generalised it into 'social outcast'. Worth handling carefully for that reason.",
  },
  {
    id: "dungaree",
    word: "dungaree",
    sourceLanguage: "Hindi / Marathi",
    sourceWord: "डूंगरी ḍūṅgrī",
    sourceMeaning: "a coarse cotton cloth, named after a Mumbai locality",
    route: "Hindi → Anglo-Indian English",
    firstUse: 1610,
    domain: "clothing",
    certainty: "settled",
    note: "The cloth came first; the plural garment sense 'dungarees' is a later English extension.",
  },
  {
    id: "nabob",
    word: "nabob",
    sourceLanguage: "Urdu",
    sourceWord: "नवाब nawāb",
    sourceMeaning: "deputy governor",
    route: "Arabic → Urdu → English",
    firstUse: 1610,
    domain: "society",
    certainty: "settled",
    note: "In 18th-century Britain it came to mean someone who had returned from India conspicuously rich.",
  },
  {
    id: "cot",
    word: "cot",
    sourceLanguage: "Hindi",
    sourceWord: "खाट khāṭ",
    sourceMeaning: "light bedstead",
    route: "Hindi → Anglo-Indian English",
    firstUse: 1630,
    domain: "home",
    certainty: "settled",
    note: "The 'baby's cot' sense is British; American English kept the older 'camp bed' meaning.",
  },
  {
    id: "punch",
    word: "punch",
    sourceLanguage: "Hindi",
    sourceWord: "पाँच pāñc",
    sourceMeaning: "five",
    route: "Hindi → Anglo-Indian English",
    firstUse: 1630,
    domain: "food",
    certainty: "debated",
    note: "The traditional explanation is five ingredients — spirit, water, lemon, sugar, spice — but the derivation is not firmly proven.",
  },
  {
    id: "juggernaut",
    word: "juggernaut",
    sourceLanguage: "Odia / Sanskrit",
    sourceWord: "जगन्नाथ Jagannātha",
    sourceMeaning: "lord of the world",
    route: "Sanskrit → Odia → English travel writing",
    firstUse: 1630,
    domain: "society",
    certainty: "settled",
    note: "From accounts of the Puri temple chariot festival; the 'unstoppable crushing force' sense is a 19th-century English invention.",
  },
  {
    id: "shawl",
    word: "shawl",
    sourceLanguage: "Urdu (from Persian)",
    sourceWord: "शाल shāl",
    sourceMeaning: "shawl, mantle",
    route: "Persian → Urdu → English",
    firstUse: 1660,
    domain: "clothing",
    certainty: "settled",
    note: "Kashmir shawls made the word fashionable across Europe by the early 1800s.",
  },
  {
    id: "pundit",
    word: "pundit",
    sourceLanguage: "Sanskrit / Hindi",
    sourceWord: "पण्डित paṇḍita",
    sourceMeaning: "learned man, scholar",
    route: "Sanskrit → Hindi → English",
    firstUse: 1660,
    domain: "society",
    certainty: "settled",
    note: "Originally a Sanskrit scholar consulted on Hindu law; now mostly a media commentator.",
  },
  {
    id: "catamaran",
    word: "catamaran",
    sourceLanguage: "Tamil",
    sourceWord: "கட்டுமரம் kaṭṭumaram",
    sourceMeaning: "tied wood",
    route: "Tamil → English",
    firstUse: 1670,
    domain: "transport",
    certainty: "settled",
    note: "The Tamil original describes lashed logs; the twin-hulled yacht sense is much later.",
  },
  {
    id: "bungalow",
    word: "bungalow",
    sourceLanguage: "Hindi / Bengali",
    sourceWord: "बंगला baṅglā",
    sourceMeaning: "of Bengal, in the Bengal style",
    route: "Hindi → Anglo-Indian English",
    firstUse: 1670,
    domain: "home",
    certainty: "settled",
    note: "Named for the single-storey thatched Bengali house type copied for colonial residences.",
  },
  {
    id: "mongoose",
    word: "mongoose",
    sourceLanguage: "Marathi",
    sourceWord: "मुंगूस muṅgūs",
    sourceMeaning: "mongoose",
    route: "Marathi → English",
    firstUse: 1690,
    domain: "nature",
    certainty: "settled",
    note: "The plural is mongooses — the word has no connection with 'goose', so 'mongeese' is not standard.",
  },
  {
    id: "teak",
    word: "teak",
    sourceLanguage: "Malayalam",
    sourceWord: "തേക്ക് tēkka",
    sourceMeaning: "teak tree",
    route: "Malayalam → Portuguese teca → English",
    firstUse: 1690,
    domain: "material",
    certainty: "settled",
    note: "Malabar teak was the shipbuilding timber that made the word commercially useful in Europe.",
  },
  {
    id: "cheetah",
    word: "cheetah",
    sourceLanguage: "Hindi",
    sourceWord: "चीता cītā",
    sourceMeaning: "leopard, from Sanskrit citraka, 'speckled'",
    route: "Sanskrit → Hindi → English",
    firstUse: 1700,
    domain: "nature",
    certainty: "settled",
    note: "The root citra, 'variegated', also gives the Hindi word for a picture.",
  },
  {
    id: "verandah",
    word: "verandah",
    sourceLanguage: "Hindi / Bengali",
    sourceWord: "बरामदा barāmdā / varaṇḍā",
    sourceMeaning: "railed porch along a house",
    route: "Indian languages and Portuguese varanda reinforced each other",
    firstUse: 1710,
    domain: "home",
    certainty: "debated",
    note: "Scholars disagree on which direction the borrowing ran between the Indian and Portuguese forms.",
  },
  {
    id: "sepoy",
    word: "sepoy",
    sourceLanguage: "Urdu (from Persian)",
    sourceWord: "सिपाही sipāhī",
    sourceMeaning: "soldier, horseman",
    route: "Persian → Urdu → Anglo-Indian English",
    firstUse: 1710,
    domain: "society",
    certainty: "settled",
    note: "The same Persian root gives 'spahi' in Ottoman and French military usage.",
  },
  {
    id: "gunny",
    word: "gunny",
    sourceLanguage: "Sanskrit / Hindi",
    sourceWord: "गोनी gonī",
    sourceMeaning: "sack",
    route: "Sanskrit → Hindi → Anglo-Indian English",
    firstUse: 1710,
    domain: "material",
    certainty: "settled",
    note: "Survives mainly in 'gunny sack' and in the jute trade.",
  },
  {
    id: "jute",
    word: "jute",
    sourceLanguage: "Bengali",
    sourceWord: "ঝুটো jhuṭo",
    sourceMeaning: "matted or coarse fibre",
    route: "Bengali (from Sanskrit jūṭa) → English",
    firstUse: 1740,
    domain: "material",
    certainty: "settled",
    note: "Bengal jute built Dundee's mill industry, which is how the word entered ordinary British English.",
  },
  {
    id: "bandana",
    word: "bandana",
    sourceLanguage: "Hindi",
    sourceWord: "बांधनू bāndhnū",
    sourceMeaning: "tie-dyeing, from bāndhnā, 'to tie'",
    route: "Hindi → English",
    firstUse: 1750,
    domain: "clothing",
    certainty: "settled",
    note: "The name records the resist-dyeing technique, not the shape of the cloth.",
  },
  {
    id: "shampoo",
    word: "shampoo",
    sourceLanguage: "Hindi",
    sourceWord: "चाँपो chāṁpo",
    sourceMeaning: "press! knead! — imperative of chāṁpnā",
    route: "Hindi → Anglo-Indian English",
    firstUse: 1760,
    domain: "home",
    certainty: "settled",
    note: "It meant 'to massage' for roughly seventy years; the hair-washing sense only appears in the 1830s.",
  },
  {
    id: "jungle",
    word: "jungle",
    sourceLanguage: "Hindi",
    sourceWord: "जंगल jaṅgal",
    sourceMeaning: "uncultivated, arid ground",
    route: "Sanskrit jāṅgala → Hindi → English",
    firstUse: 1770,
    domain: "nature",
    certainty: "settled",
    note: "The meaning inverted in English: the Sanskrit original describes dry wasteland, not dense wet forest.",
  },
  {
    id: "bandobast",
    word: "bandobast",
    sourceLanguage: "Urdu (from Persian)",
    sourceWord: "बंदोबस्त band-o-bast",
    sourceMeaning: "tying and binding — hence an arrangement",
    route: "Persian → Urdu → Anglo-Indian English",
    firstUse: 1770,
    domain: "slang",
    certainty: "settled",
    note: "Still standard in Indian English for security or event arrangements.",
  },
  {
    id: "mulligatawny",
    word: "mulligatawny",
    sourceLanguage: "Tamil",
    sourceWord: "மிளகுத்தண்ணீர் miḷaku-taṇṇīr",
    sourceMeaning: "pepper water",
    route: "Tamil → Anglo-Indian English",
    firstUse: 1780,
    domain: "food",
    certainty: "settled",
    note: "The English soup is a colonial reworking of the thin Tamil pepper broth the name describes.",
  },
  {
    id: "bandicoot",
    word: "bandicoot",
    sourceLanguage: "Telugu",
    sourceWord: "పంది కొక్కు pandi-kokku",
    sourceMeaning: "pig-rat",
    route: "Telugu → English",
    firstUse: 1780,
    domain: "nature",
    certainty: "settled",
    note: "English later applied the name to unrelated Australian marsupials, which is why the word now names two different animals.",
  },
  {
    id: "chit",
    word: "chit",
    sourceLanguage: "Hindi",
    sourceWord: "चिट्ठी ciṭṭhī",
    sourceMeaning: "note, short letter",
    route: "Hindi → Anglo-Indian English",
    firstUse: 1780,
    domain: "society",
    certainty: "settled",
    note: "Survives in 'chit fund' and in the older sense of a signed note of credit.",
  },
  {
    id: "bangle",
    word: "bangle",
    sourceLanguage: "Hindi",
    sourceWord: "बंगड़ी baṅgṛī",
    sourceMeaning: "glass bracelet",
    route: "Hindi → English",
    firstUse: 1780,
    domain: "clothing",
    certainty: "settled",
    note: "The Hindi original specifically names a glass bangle rather than any rigid bracelet.",
  },
  {
    id: "sari",
    word: "sari",
    sourceLanguage: "Hindi (from Sanskrit)",
    sourceWord: "साड़ी sāṛī",
    sourceMeaning: "strip of cloth, from Sanskrit śāṭī",
    route: "Sanskrit → Hindi → English",
    firstUse: 1780,
    domain: "clothing",
    certainty: "settled",
    note: "Both 'sari' and 'saree' are accepted English spellings.",
  },
  {
    id: "avatar",
    word: "avatar",
    sourceLanguage: "Sanskrit",
    sourceWord: "अवतार avatāra",
    sourceMeaning: "descent — a deity coming down into the world",
    route: "Sanskrit → English",
    firstUse: 1780,
    domain: "religion",
    certainty: "settled",
    note: "The computing sense of an on-screen figure representing a user dates from the 1980s.",
  },
  {
    id: "loot",
    word: "loot",
    sourceLanguage: "Hindi",
    sourceWord: "लूट lūṭ",
    sourceMeaning: "plunder, booty",
    route: "Sanskrit luṇṭh- → Hindi → Anglo-Indian army slang",
    firstUse: 1790,
    domain: "crime",
    certainty: "settled",
    note: "Entered English as soldiers' slang before becoming an ordinary noun and verb.",
  },
  {
    id: "mantra",
    word: "mantra",
    sourceLanguage: "Sanskrit",
    sourceWord: "मन्त्र mantra",
    sourceMeaning: "instrument of thought, sacred utterance",
    route: "Sanskrit → English",
    firstUse: 1800,
    domain: "religion",
    certainty: "settled",
    note: "The everyday sense of a slogan repeated by an organisation is 20th-century English.",
  },
  {
    id: "pyjamas",
    word: "pyjamas",
    sourceLanguage: "Urdu (from Persian)",
    sourceWord: "पायजामा pāy-jāma",
    sourceMeaning: "leg garment",
    route: "Persian → Urdu → Anglo-Indian English",
    firstUse: 1800,
    domain: "clothing",
    certainty: "settled",
    note: "Spelled 'pajamas' in American English; the original was loose daytime trousers, not nightwear.",
  },
  {
    id: "thug",
    word: "thug",
    sourceLanguage: "Hindi / Marathi",
    sourceWord: "ठग ṭhag",
    sourceMeaning: "cheat, swindler",
    route: "Sanskrit sthaga → Hindi → English",
    firstUse: 1810,
    domain: "crime",
    certainty: "settled",
    note: "Entered English through colonial reporting on the Thuggee bands in the early 19th century.",
  },
  {
    id: "chutney",
    word: "chutney",
    sourceLanguage: "Hindi",
    sourceWord: "चटनी caṭnī",
    sourceMeaning: "something licked, from caṭnā, 'to lick'",
    route: "Hindi → English",
    firstUse: 1810,
    domain: "food",
    certainty: "settled",
    note: "The Indian original is usually fresh and ground; the English bottled version is a sweetened preserve.",
  },
  {
    id: "dinghy",
    word: "dinghy",
    sourceLanguage: "Bengali / Hindi",
    sourceWord: "ডিঙি ḍiṅgī",
    sourceMeaning: "small river boat",
    route: "Bengali → English",
    firstUse: 1810,
    domain: "transport",
    certainty: "settled",
    note: "The h in the English spelling was added to keep the g hard.",
  },
  {
    id: "karma",
    word: "karma",
    sourceLanguage: "Sanskrit",
    sourceWord: "कर्म karman",
    sourceMeaning: "action, deed",
    route: "Sanskrit → English",
    firstUse: 1820,
    domain: "religion",
    certainty: "settled",
    note: "In English it usually means cosmic payback, which narrows a term that originally meant action itself.",
  },
  {
    id: "yoga",
    word: "yoga",
    sourceLanguage: "Sanskrit",
    sourceWord: "योग yoga",
    sourceMeaning: "yoking, union",
    route: "Sanskrit → English",
    firstUse: 1820,
    domain: "religion",
    certainty: "settled",
    note: "Shares an Indo-European root with the English word 'yoke'.",
  },
  {
    id: "nirvana",
    word: "nirvana",
    sourceLanguage: "Sanskrit",
    sourceWord: "निर्वाण nirvāṇa",
    sourceMeaning: "blowing out, extinction",
    route: "Sanskrit → English",
    firstUse: 1830,
    domain: "religion",
    certainty: "settled",
    note: "The image is a flame being extinguished, not a paradise being entered.",
  },
  {
    id: "khaki",
    word: "khaki",
    sourceLanguage: "Urdu (from Persian)",
    sourceWord: "ख़ाकी khākī",
    sourceMeaning: "dust-coloured, from khāk, 'dust'",
    route: "Persian → Urdu → British Indian Army → English",
    firstUse: 1850,
    domain: "clothing",
    certainty: "settled",
    note: "Adopted for uniforms in India in the 1840s-50s precisely because it matched dust.",
  },
  {
    id: "dekko",
    word: "dekko",
    sourceLanguage: "Hindi",
    sourceWord: "देखो dekho",
    sourceMeaning: "look! — imperative of dekhnā",
    route: "Hindi → British army slang",
    firstUse: 1890,
    domain: "slang",
    certainty: "settled",
    note: "Still heard in British English as 'have a dekko at this'.",
  },
  {
    id: "jodhpurs",
    word: "jodhpurs",
    sourceLanguage: "Rajasthani place name",
    sourceWord: "Jodhpur",
    sourceMeaning: "the city in Rajasthan",
    route: "Place name → English riding dress",
    firstUse: 1890,
    domain: "clothing",
    certainty: "settled",
    note: "Named after the riding breeches worn by Jodhpur polo players seen in Britain in the 1890s.",
  },
  {
    id: "ashram",
    word: "ashram",
    sourceLanguage: "Sanskrit",
    sourceWord: "आश्रम āśrama",
    sourceMeaning: "hermitage, stage of life",
    route: "Sanskrit → Hindi → English",
    firstUse: 1910,
    domain: "religion",
    certainty: "settled",
    note: "Entered wider English through 20th-century reporting on Gandhi's ashrams.",
  },
  {
    id: "cushy",
    word: "cushy",
    sourceLanguage: "Urdu / Hindi",
    sourceWord: "ख़ुशी khushī",
    sourceMeaning: "pleasure, happiness",
    route: "Persian/Urdu → British army slang in the First World War",
    firstUse: 1915,
    domain: "slang",
    certainty: "settled",
    note: "A 'cushy job' entered general English from soldiers returning from the Indian Army.",
  },
];

export const ERA_BANDS = [
  { id: "pre1500", label: "Before 1500", min: -Infinity, max: 1499 },
  { id: "1500s", label: "1500–1699", min: 1500, max: 1699 },
  { id: "1700s", label: "1700–1799", min: 1700, max: 1799 },
  { id: "1800s", label: "1800–1899", min: 1800, max: 1899 },
  { id: "1900s", label: "1900 onwards", min: 1900, max: Infinity },
];

export const LANGUAGES = Array.from(
  new Set(LOANWORDS.map((entry) => entry.sourceLanguage))
).sort((a, b) => a.localeCompare(b));

const DOMAIN_IDS = new Set(DOMAINS.map((d) => d.id));
const CERTAINTY_IDS = new Set(CERTAINTIES.map((c) => c.id));
const LANGUAGE_SET = new Set(LANGUAGES);

function normalise(value) {
  return String(value ?? "")
    .toLowerCase()
    .replace(/[.,!?;:'"()\-–—]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function haystack(entry) {
  return normalise(
    [
      entry.word,
      entry.sourceLanguage,
      entry.sourceWord,
      entry.sourceMeaning,
      entry.route,
      entry.note,
    ].join(" ")
  );
}

/**
 * Filter the word list. Unknown filter values fall back to "all".
 * Results are sorted oldest first so the timeline reads chronologically.
 */
export function searchLoanwords({
  query = "",
  language = "all",
  domain = "all",
  certainty = "all",
} = {}) {
  const safeLanguage = language === "all" || LANGUAGE_SET.has(language) ? language : "all";
  const safeDomain = domain === "all" || DOMAIN_IDS.has(domain) ? domain : "all";
  const safeCertainty =
    certainty === "all" || CERTAINTY_IDS.has(certainty) ? certainty : "all";
  const tokens = normalise(query).split(" ").filter(Boolean);

  const results = LOANWORDS.filter((entry) => {
    if (safeLanguage !== "all" && entry.sourceLanguage !== safeLanguage) return false;
    if (safeDomain !== "all" && entry.domain !== safeDomain) return false;
    if (safeCertainty !== "all" && entry.certainty !== safeCertainty) return false;
    if (tokens.length === 0) return true;
    const hay = haystack(entry);
    return tokens.every((token) => hay.includes(token));
  }).sort((a, b) => a.firstUse - b.firstUse || a.word.localeCompare(b.word));

  return {
    results,
    total: LOANWORDS.length,
    matched: results.length,
    language: safeLanguage,
    domain: safeDomain,
    certainty: safeCertainty,
  };
}

/** Count how many of the supplied entries fall in each era band. */
export function eraBands(entries) {
  const list = Array.isArray(entries) ? entries : LOANWORDS;
  return ERA_BANDS.map((band) => ({
    id: band.id,
    label: band.label,
    count: list.filter((entry) => entry.firstUse >= band.min && entry.firstUse <= band.max)
      .length,
  }));
}

/** Oldest and newest first-attestation years in a list. Safe on an empty list. */
export function eraSpan(entries) {
  const list = Array.isArray(entries) ? entries : LOANWORDS;
  if (list.length === 0) return { earliest: null, latest: null, years: 0 };
  const years = list.map((entry) => entry.firstUse);
  const earliest = Math.min(...years);
  const latest = Math.max(...years);
  return { earliest, latest, years: latest - earliest };
}

export function languageCounts() {
  const counts = {};
  for (const entry of LOANWORDS) {
    counts[entry.sourceLanguage] = (counts[entry.sourceLanguage] ?? 0) + 1;
  }
  return counts;
}

export function getLoanwordById(id) {
  return LOANWORDS.find((entry) => entry.id === id) ?? null;
}
