export const WORDS = [
  // ── Easy ──
  { word: "Abandon", def: "To leave behind or give up", pos: "verb", ex: "They had to abandon the sinking ship.", syn: ["desert", "forsake", "leave"], ant: ["keep", "retain"], diff: "easy" },
  { word: "Beneath", def: "Under or below something", pos: "preposition", ex: "The cat hid beneath the bed.", syn: ["under", "below", "underneath"], ant: ["above", "over"], diff: "easy" },
  { word: "Calm", def: "Peaceful and quiet; not upset", pos: "adj", ex: "She stayed calm during the storm.", syn: ["serene", "tranquil", "composed"], ant: ["agitated", "nervous"], diff: "easy" },
  { word: "Delay", def: "To make late or postpone", pos: "verb", ex: "The flight was delayed by two hours.", syn: ["postpone", "defer", "hold up"], ant: ["hasten", "expedite"], diff: "easy" },
  { word: "Eager", def: "Excited and impatient to do something", pos: "adj", ex: "The children were eager to open their presents.", syn: ["keen", "enthusiastic", "anxious"], ant: ["reluctant", "unenthusiastic"], diff: "easy" },
  { word: "Faint", def: "To lose consciousness; barely perceptible", pos: "verb/adj", ex: "She felt faint after standing in the sun.", syn: ["dizzy", "weak", "dim"], ant: ["strong", "bright"], diff: "easy" },
  { word: "Gather", def: "To collect or bring together", pos: "verb", ex: "Let's gather some firewood.", syn: ["collect", "assemble", "accumulate"], ant: ["scatter", "disperse"], diff: "easy" },
  { word: "Honest", def: "Truthful and sincere", pos: "adj", ex: "An honest answer is always appreciated.", syn: ["truthful", "sincere", "candid"], ant: ["dishonest", "deceitful"], diff: "easy" },
  { word: "Insist", def: "To demand firmly", pos: "verb", ex: "I insist that you stay for dinner.", syn: ["demand", "urge", "assert"], ant: ["withdraw", "deny"], diff: "easy" },
  { word: "Journey", def: "A long trip or voyage", pos: "noun", ex: "The journey across the country took three days.", syn: ["trip", "expedition", "voyage"], ant: ["stay", "halt"], diff: "easy" },
  { word: "Launch", def: "To start or send off", pos: "verb", ex: "NASA will launch the rocket tomorrow.", syn: ["begin", "initiate", "propel"], ant: ["terminate", "stop"], diff: "easy" },
  { word: "Mumble", def: "To speak quietly and unclearly", pos: "verb", ex: "He tends to mumble when he's nervous.", syn: ["mutter", "whisper", "murmur"], ant: ["enunciate", "articulate"], diff: "easy" },
  { word: "Narrow", def: "Limited in width; restricted", pos: "adj", ex: "The alley was too narrow for a car.", syn: ["slender", "tight", "slim"], ant: ["wide", "broad"], diff: "easy" },
  { word: "Obtain", def: "To get or acquire", pos: "verb", ex: "You can obtain a license at the city office.", syn: ["acquire", "secure", "procure"], ant: ["lose", "surrender"], diff: "easy" },
  { word: "Patient", def: "Able to wait without frustration", pos: "adj", ex: "A good teacher is patient with students.", syn: ["tolerant", "understanding", "composed"], ant: ["impatient", "restless"], diff: "easy" },
  { word: "Quiet", def: "Making little or no noise", pos: "adj", ex: "The library was very quiet.", syn: ["silent", "still", "hushed"], ant: ["loud", "noisy"], diff: "easy" },
  { word: "Reach", def: "To stretch out to touch or arrive at", pos: "verb", ex: "Can you reach the top shelf?", syn: ["attain", "grasp", "arrive"], ant: ["miss", "fall short"], diff: "easy" },
  { word: "Scatter", def: "To throw or spread around", pos: "verb", ex: "Scatter the seeds across the soil.", syn: ["disperse", "sprinkle", "strewn"], ant: ["gather", "collect"], diff: "easy" },
  { word: "Treat", def: "To behave toward or give medical care", pos: "verb", ex: "They treat all patients with respect.", syn: ["handle", "manage", "attend"], ant: ["neglect", "ignore"], diff: "easy" },
  { word: "Unique", def: "Being the only one of its kind", pos: "adj", ex: "Each snowflake is unique.", syn: ["distinctive", "singular", "unparalleled"], ant: ["common", "ordinary"], diff: "easy" },
  { word: "Value", def: "The worth or importance of something", pos: "noun/verb", ex: "We value your feedback.", syn: ["worth", "merit", "esteem"], ant: ["worthlessness", "disregard"], diff: "easy" },
  { word: "Waste", def: "To use carelessly or unnecessarily", pos: "verb/noun", ex: "Don't waste water.", syn: ["squander", "misuse", "fritter"], ant: ["conserve", "save"], diff: "easy" },
  { word: "Yearn", def: "To desire strongly", pos: "verb", ex: "She yearns to travel the world.", syn: ["long", "crave", "pine"], ant: ["detest", "abhor"], diff: "easy" },
  { word: "Blend", def: "To mix together thoroughly", pos: "verb", ex: "Blend the ingredients until smooth.", syn: ["combine", "mix", "merge"], ant: ["separate", "divide"], diff: "easy" },
  { word: "Claim", def: "To assert as true; demand as one's own", pos: "verb/noun", ex: "He claims he saw the accident.", syn: ["assert", "declare", "allege"], ant: ["deny", "disclaim"], diff: "easy" },
  { word: "Drift", def: "To be carried slowly by wind or water", pos: "verb", ex: "The boat began to drift downstream.", syn: ["float", "glide", "wander"], ant: ["anchor", "settle"], diff: "easy" },
  { word: "Flash", def: "A sudden bright light; to shine briefly", pos: "noun/verb", ex: "A flash of lightning lit the sky.", syn: ["gleam", "sparkle", "glare"], ant: ["dim", "fade"], diff: "easy" },
  { word: "Grab", def: "To take hold of suddenly", pos: "verb", ex: "He grabbed my arm to stop me.", syn: ["seize", "snatch", "clutch"], ant: ["release", "let go"], diff: "easy" },
  { word: "Hunt", def: "To search for or pursue", pos: "verb", ex: "They hunt for food in the forest.", syn: ["chase", "pursue", "stalk"], ant: ["flee", "avoid"], diff: "easy" },
  { word: "Jump", def: "To push off the ground with the legs", pos: "verb", ex: "The cat can jump very high.", syn: ["leap", "spring", "bound"], ant: ["land", "fall"], diff: "easy" },

  // ── Medium ──
  { word: "Abundant", def: "Existing in large quantities", pos: "adj", ex: "The region has abundant natural resources.", syn: ["plentiful", "ample", "copious"], ant: ["scarce", "meager"], diff: "medium" },
  { word: "Benevolent", def: "Well-meaning and kindly", pos: "adj", ex: "A benevolent donor funded the scholarship.", syn: ["charitable", "generous", "compassionate"], ant: ["malevolent", "cruel"], diff: "medium" },
  { word: "Concise", def: "Giving information clearly in few words", pos: "adj", ex: "Her speech was concise and powerful.", syn: ["succinct", "brief", "terse"], ant: ["verbose", "rambling"], diff: "medium" },
  { word: "Diligent", def: "Hardworking and careful", pos: "adj", ex: "A diligent student always completes homework.", syn: ["industrious", "assiduous", "meticulous"], ant: ["lazy", "negligent"], diff: "medium" },
  { word: "Eloquent", def: "Fluent and persuasive in speech", pos: "adj", ex: "The lawyer gave an eloquent closing argument.", syn: ["articulate", "expressive", "silver-tongued"], ant: ["inarticulate", "hesitant"], diff: "medium" },
  { word: "Fluent", def: "Able to speak a language smoothly", pos: "adj", ex: "She is fluent in three languages.", syn: ["smooth", "effortless", "fluid"], ant: ["halting", "stammering"], diff: "medium" },
  { word: "Grateful", def: "Feeling thankful", pos: "adj", ex: "I am grateful for your help.", syn: ["thankful", "appreciative", "indebted"], ant: ["ungrateful", "thankless"], diff: "medium" },
  { word: "Hesitant", def: "Tentative or unsure", pos: "adj", ex: "He was hesitant to accept the offer.", syn: ["uncertain", "reluctant", "wavering"], ant: ["eager", "confident"], diff: "medium" },
  { word: "Illuminate", def: "To light up or clarify", pos: "verb", ex: "The lantern will illuminate the path.", syn: ["brighten", "enlighten", "clarify"], ant: ["darken", "obscure"], diff: "medium" },
  { word: "Jubilant", def: "Feeling great happiness and triumph", pos: "adj", ex: "The team was jubilant after the victory.", syn: ["ecstatic", "elated", "euphoric"], ant: ["despondent", "gloomy"], diff: "medium" },
  { word: "Keen", def: "Eager or enthusiastic; sharp", pos: "adj", ex: "She has a keen interest in astronomy.", syn: ["enthusiastic", "eager", "acute"], ant: ["indifferent", "dull"], diff: "medium" },
  { word: "Lament", def: "To express grief or regret", pos: "verb", ex: "They lament the loss of the old traditions.", syn: ["mourn", "bemoan", "grieve"], ant: ["rejoice", "celebrate"], diff: "medium" },
  { word: "Meticulous", def: "Very careful and precise", pos: "adj", ex: "The artist was meticulous about every brushstroke.", syn: ["thorough", "scrupulous", "fastidious"], ant: ["careless", "sloppy"], diff: "medium" },
  { word: "Notorious", def: "Famous for something bad", pos: "adj", ex: "The city is notorious for its traffic jams.", syn: ["infamous", "disreputable", "scandalous"], ant: ["reputable", "honorable"], diff: "medium" },
  { word: "Obsolete", def: "No longer in use; outdated", pos: "adj", ex: "Floppy disks are now obsolete.", syn: ["outdated", "antiquated", "archaic"], ant: ["current", "modern"], diff: "medium" },
  { word: "Perplex", def: "To confuse or puzzle", pos: "verb", ex: "The riddle continues to perplex researchers.", syn: ["baffle", "bewilder", "confound"], ant: ["enlighten", "clarify"], diff: "medium" },
  { word: "Resilient", def: "Able to recover quickly", pos: "adj", ex: "Children are remarkably resilient.", syn: ["tough", "adaptable", "buoyant"], ant: ["fragile", "vulnerable"], diff: "medium" },
  { word: "Sublime", def: "Of outstanding spiritual or artistic value", pos: "adj", ex: "The sunset was a sublime sight.", syn: ["magnificent", "exalted", "transcendent"], ant: ["mundane", "inferior"], diff: "medium" },
  { word: "Tenacious", def: "Holding firmly; persistent", pos: "adj", ex: "A tenacious reporter never gives up on a story.", syn: ["persistent", "dogged", "unyielding"], ant: ["wavering", "irresolute"], diff: "medium" },
  { word: "Unanimous", def: "In complete agreement", pos: "adj", ex: "The jury reached a unanimous verdict.", syn: ["united", "consensual", "solid"], ant: ["divided", "split"], diff: "medium" },
  { word: "Versatile", def: "Able to adapt to many functions", pos: "adj", ex: "A versatile actor can play any role.", syn: ["adaptable", "flexible", "multifaceted"], ant: ["limited", "specialized"], diff: "medium" },
  { word: "Whimsical", def: "Playfully odd or fanciful", pos: "adj", ex: "The garden had a whimsical charm.", syn: ["playful", "fanciful", "quirky"], ant: ["serious", "solemn"], diff: "medium" },
  { word: "Advocate", def: "To publicly support; a supporter", pos: "verb/noun", ex: "She advocates for animal rights.", syn: ["champion", "promote", "endorse"], ant: ["oppose", "protest"], diff: "medium" },
  { word: "Captivate", def: "To attract and hold attention", pos: "verb", ex: "The performance captivated the audience.", syn: ["enchant", "enthrall", "fascinate"], ant: ["bore", "repel"], diff: "medium" },
  { word: "Deteriorate", def: "To become progressively worse", pos: "verb", ex: "The old building began to deteriorate.", syn: ["decay", "worsen", "decline"], ant: ["improve", "flourish"], diff: "medium" },
  { word: "Facilitate", def: "To make easier", pos: "verb", ex: "The new software will facilitate data analysis.", syn: ["expedite", "assist", "enable"], ant: ["hinder", "complicate"], diff: "medium" },
  { word: "Grandeur", def: "Splendor and impressiveness", pos: "noun", ex: "The palace was built with great grandeur.", syn: ["magnificence", "majesty", "glory"], ant: ["mediocrity", "plainness"], diff: "medium" },
  { word: "Ingenious", def: "Clever and inventive", pos: "adj", ex: "He devised an ingenious solution.", syn: ["brilliant", "resourceful", "innovative"], ant: ["foolish", "unimaginative"], diff: "medium" },
  { word: "Ponder", def: "To think about carefully", pos: "verb", ex: "Let me ponder that question.", syn: ["contemplate", "muse", "reflect"], ant: ["ignore", "dismiss"], diff: "medium" },
  { word: "Reconcile", def: "To restore harmony or resolve differences", pos: "verb", ex: "They need to reconcile their differences.", syn: ["harmonize", "settle", "resolve"], ant: ["estrange", "divide"], diff: "medium" },

  // ── Hard ──
  { word: "Acquiesce", def: "To accept reluctantly without protest", pos: "verb", ex: "He acquiesced to the committee's decision.", syn: ["consent", "submit", "yield"], ant: ["resist", "defy"], diff: "hard" },
  { word: "Ameliorate", def: "To make something bad become better", pos: "verb", ex: "New policies ameliorated the housing crisis.", syn: ["improve", "alleviate", "mitigate"], ant: ["worsen", "aggravate"], diff: "hard" },
  { word: "Antipathy", def: "A deep-seated dislike", pos: "noun", ex: "She felt antipathy toward dishonest people.", syn: ["hostility", "animosity", "aversion"], ant: ["affinity", "sympathy"], diff: "hard" },
  { word: "Austere", def: "Severe and strict; without luxury", pos: "adj", ex: "The monk lived an austere life.", syn: ["ascetic", "stern", "spartan"], ant: ["lavish", "indulgent"], diff: "hard" },
  { word: "Cogent", def: "Clear, logical, and convincing", pos: "adj", ex: "She presented a cogent argument.", syn: ["compelling", "persuasive", "rational"], ant: ["weak", "illogical"], diff: "hard" },
  { word: "Complacent", def: "Smugly self-satisfied; uncritical", pos: "adj", ex: "We cannot become complacent about our success.", syn: ["smug", "self-satisfied", "content"], ant: ["dissatisfied", "ambitious"], diff: "hard" },
  { word: "Convoluted", def: "Extremely complex and difficult to follow", pos: "adj", ex: "The plot was too convoluted to understand.", syn: ["intricate", "tangled", "byzantine"], ant: ["simple", "straightforward"], diff: "hard" },
  { word: "Dearth", def: "A scarcity or lack", pos: "noun", ex: "There is a dearth of affordable housing.", syn: ["shortage", "paucity", "deficiency"], ant: ["abundance", "plenty"], diff: "hard" },
  { word: "Ephemeral", def: "Lasting for a very short time", pos: "adj", ex: "Fame is often ephemeral.", syn: ["fleeting", "transient", "momentary"], ant: ["permanent", "enduring"], diff: "hard" },
  { word: "Esoteric", def: "Likely to be understood by only a few", pos: "adj", ex: "The lecture was full of esoteric references.", syn: ["arcane", "obscure", "recondite"], ant: ["accessible", "mainstream"], diff: "hard" },
  { word: "Egregious", def: "Shockingly bad or obvious", pos: "adj", ex: "The error was egregious and costly.", syn: ["outrageous", "flagrant", "glaring"], ant: ["minor", "negligible"], diff: "hard" },
  { word: "Fastidious", def: "Very attentive to detail and cleanliness", pos: "adj", ex: "A fastidious editor catches every typo.", syn: ["particular", "fussy", "scrupulous"], ant: ["slovenly", "careless"], diff: "hard" },
  { word: "Gregarious", def: "Fond of company; sociable", pos: "adj", ex: "His gregarious nature made him many friends.", syn: ["sociable", "outgoing", "convivial"], ant: ["aloof", "introverted"], diff: "hard" },
  { word: "Iconoclast", def: "Someone who attacks cherished beliefs", pos: "noun", ex: "The artist was an iconoclast who challenged traditions.", syn: ["rebel", "dissident", "nonconformist"], ant: ["traditionalist", "conformist"], diff: "hard" },
  { word: "Ineffable", def: "Too great to be expressed in words", pos: "adj", ex: "The beauty of the scene was ineffable.", syn: ["indescribable", "unspeakable", "transcendent"], ant: ["mundane", "expressible"], diff: "hard" },
  { word: "Intransigent", def: "Unwilling to change one's views", pos: "adj", ex: "The intransigent negotiator refused any compromise.", syn: ["stubborn", "obstinate", "unyielding"], ant: ["flexible", "compliant"], diff: "hard" },
  { word: "Laconic", def: "Using very few words; terse", pos: "adj", ex: "His laconic reply was simply 'No.'", syn: ["terse", "succinct", "curt"], ant: ["verbose", "loquacious"], diff: "hard" },
  { word: "Magnanimous", def: "Generous and forgiving, especially toward a rival", pos: "adj", ex: "The winner was magnanimous in victory.", syn: ["generous", "forgiving", "noble"], ant: ["petty", "vindictive"], diff: "hard" },
  { word: "Malevolent", def: "Having or showing a wish to harm others", pos: "adj", ex: "The villain had a malevolent laugh.", syn: ["malicious", "spiteful", "vicious"], ant: ["benevolent", "kindly"], diff: "hard" },
  { word: "Obfuscate", def: "To make unclear or hard to understand", pos: "verb", ex: "Politicians often obfuscate the truth.", syn: ["confuse", "muddle", "obscure"], ant: ["clarify", "elucidate"], diff: "hard" },
  { word: "Ostentatious", def: "Designed to impress; showy", pos: "adj", ex: "The mansion was grand but not ostentatious.", syn: ["showy", "pretentious", "flamboyant"], ant: ["modest", "unpretentious"], diff: "hard" },
  { word: "Pedantic", def: "Overly concerned with minor details or rules", pos: "adj", ex: "A pedantic teacher corrects every minor mistake.", syn: ["fussy", "punctilious", "dogmatic"], ant: ["informal", "casual"], diff: "hard" },
  { word: "Pernicious", def: "Having a harmful effect, especially gradually", pos: "adj", ex: "Fake news has a pernicious influence on society.", syn: ["harmful", "destructive", "damaging"], ant: ["beneficial", "wholesome"], diff: "hard" },
  { word: "Pragmatic", def: "Dealing with things practically, not theoretically", pos: "adj", ex: "We need a pragmatic approach to the problem.", syn: ["practical", "realistic", "sensible"], ant: ["idealistic", "impractical"], diff: "hard" },
  { word: "Propitious", def: "Indicating a good chance of success; favorable", pos: "adj", ex: "The clear skies were a propitious sign.", syn: ["favorable", "auspicious", "promising"], ant: ["inauspicious", "unfavorable"], diff: "hard" },
  { word: "Recalcitrant", def: "Stubbornly uncooperative", pos: "adj", ex: "The recalcitrant student refused to follow instructions.", syn: ["obstinate", "rebellious", "defiant"], ant: ["cooperative", "obedient"], diff: "hard" },
  { word: "Sanctimonious", def: "Making a show of being morally superior", pos: "adj", ex: "His sanctimonious tone annoyed everyone.", syn: ["self-righteous", "holier-than-thou", "pious"], ant: ["humble", "genuine"], diff: "hard" },
  { word: "Surreptitious", def: "Kept secret, especially because improper", pos: "adj", ex: "She cast a surreptitious glance at the answers.", syn: ["clandestine", "covert", "stealthy"], ant: ["open", "aboveboard"], diff: "hard" },
  { word: "Ubiquitous", def: "Present or found everywhere", pos: "adj", ex: "Smartphones have become ubiquitous.", syn: ["omnipresent", "pervasive", "universal"], ant: ["scarce", "rare"], diff: "hard" },
  { word: "Vociferous", def: "Loud and vehement in expression", pos: "adj", ex: "The crowd was vociferous in its demands.", syn: ["strident", "clamorous", "outspoken"], ant: ["quiet", "muted"], diff: "hard" },
];

export const DIFFICULTIES = ["easy", "medium", "hard"];
