export const CATEGORIES = [
  "All",
  "Programming",
  "General",
  "Dad Joke",
  "Technology",
  "Science",
  "Animals",
  "Office",
  "Food",
  "Kids",
];

export const FALLBACK_JOKES = [
  { id: 1, joke: "Why do programmers prefer dark mode? Because light attracts bugs.", category: "Programming", author: null },
  { id: 2, joke: "There are only 10 types of people in the world: those who understand binary and those who don't.", category: "Programming", author: null },
  { id: 3, joke: "Why do Java developers wear glasses? Because they can't C#.", category: "Programming", author: null },
  { id: 4, joke: "A SQL query walks into a bar, walks up to two tables and asks: 'Can I join you?'", category: "Programming", author: null },
  { id: 5, joke: "Why was the JavaScript developer sad? Because he didn't Node how to Express himself.", category: "Programming", author: null },
  { id: 6, joke: "What's a programmer's favorite hangout place? Foo Bar.", category: "Programming", author: null },
  { id: 7, joke: "Why do programmers hate nature? It has too many bugs.", category: "Programming", author: null },
  { id: 8, joke: "How many programmers does it take to change a light bulb? None — that's a hardware problem.", category: "Programming", author: null },
  { id: 9, joke: "What is a programmer's favorite tea? NullPointerException.", category: "Programming", author: null },
  { id: 10, joke: "Why do Java developers get confused at parties? Because they don't know how to party.", category: "Programming", author: null },
  { id: 11, joke: "I told my wife she was drawing her eyebrows too high. She looked surprised.", category: "Dad Joke", author: null },
  { id: 12, joke: "What do you call a fake noodle? An impasta.", category: "Dad Joke", author: null },
  { id: 13, joke: "Why don't eggs tell jokes? They'd crack each other up.", category: "Dad Joke", author: null },
  { id: 14, joke: "I'm reading a book about anti-gravity. It's impossible to put down.", category: "Dad Joke", author: null },
  { id: 15, joke: "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.", category: "Dad Joke", author: null },
  { id: 16, joke: "What do you call a bear with no teeth? A gummy bear.", category: "Dad Joke", author: null },
  { id: 17, joke: "Why don't scientists trust atoms? Because they make up everything.", category: "Science", author: null },
  { id: 18, joke: "What did the biologist wear on a first date? Designer genes.", category: "Science", author: null },
  { id: 19, joke: "Why can't you trust atoms? They make up literally everything.", category: "Science", author: null },
  { id: 20, joke: "What do you call a cold dog sitting on a bunny? A chili dog on a hare.", category: "Animals", author: null },
  { id: 21, joke: "What do you call an alligator in a vest? An investigator.", category: "Animals", author: null },
  { id: 22, joke: "Why do ducks have feathers? To cover their butt quacks.", category: "Animals", author: null },
  { id: 23, joke: "What do you get when you cross a snowman and a dog? Frostbite.", category: "Animals", author: null },
  { id: 24, joke: "Why did the computer go to the doctor? Because it had a virus.", category: "Technology", author: null },
  { id: 25, joke: "Why was the phone so good at tennis? It had the best service.", category: "Technology", author: null },
  { id: 26, joke: "What do you call a computer that sings? A-Dell.", category: "Technology", author: null },
  { id: 27, joke: "Why did the computer keep sneezing? It had a virus.", category: "Technology", author: null },
  { id: 28, joke: "What did the router say to the doctor? It hurts when IP.", category: "Technology", author: null },
  { id: 29, joke: "Why did the employee get fired from the calendar factory? He took a day off.", category: "Office", author: null },
  { id: 30, joke: "What do you call a group of 8 hobbits? A hobbyte.", category: "Office", author: null },
  { id: 31, joke: "Why don't scientists trust stairs? Because they're always up to something.", category: "Office", author: null },
  { id: 32, joke: "What did the paper clip say to the magnet? I find you very attractive.", category: "Office", author: null },
  { id: 33, joke: "Why did the scarecrow win an award? He was outstanding in his field.", category: "General", author: null },
  { id: 34, joke: "I told my wife she was drawing her eyebrows too high. She looked surprised.", category: "General", author: null },
  { id: 35, joke: "What do you call a dog that does magic tricks? A Labracadabrador.", category: "General", author: null },
  { id: 36, joke: "Why don't skeletons fight each other? They don't have the guts.", category: "General", author: null },
  { id: 37, joke: "What did the ocean say to the beach? Nothing, it just waved.", category: "General", author: null },
  { id: 38, joke: "Why can't a bicycle stand on its own? Because it's two-tired.", category: "General", author: null },
  { id: 39, joke: "What did the grape do when it got stepped on? Nothing, it just let out a little wine.", category: "Food", author: null },
  { id: 40, joke: "Why did the tomato turn red? Because it saw the salad dressing.", category: "Food", author: null },
  { id: 41, joke: "What do you call a fake apple? An im-pasta.", category: "Food", author: null },
  { id: 42, joke: "Why did the cookie go to the hospital? Because it felt crummy.", category: "Food", author: null },
  { id: 43, joke: "What did the baby corn say to the mama corn? Where's pop corn?", category: "Food", author: null },
  { id: 44, joke: "Why did the man bring a ladder to the bar? He heard the drinks were on the house.", category: "Food", author: null },
  { id: 45, joke: "What do you call a sleeping dinosaur? A dino-snore.", category: "Kids", author: null },
  { id: 46, joke: "Why can't your nose be 12 inches long? Because then it would be a foot.", category: "Kids", author: null },
  { id: 47, joke: "What do you call a bear that's stuck in the rain? A drizzly bear.", category: "Kids", author: null },
  { id: 48, joke: "What did the big chimney say to the little chimney? You're too young to smoke.", category: "Kids", author: null },
  { id: 49, joke: "Why did the kid bring a ladder to school? Because they wanted to go to high school.", category: "Kids", author: null },
  { id: 50, joke: "What do you call a dog that's always on time? A watch dog.", category: "Kids", author: null },
  { id: 51, joke: "Why did the gym close down? It just didn't work out.", category: "General", author: null },
  { id: 52, joke: "Parallel lines have so much in common. It's a shame they'll never meet.", category: "General", author: null },
  { id: 53, joke: "I'm on a seafood diet. I see food and I eat it.", category: "General", author: null },
  { id: 54, joke: "What do you call a bear with no teeth? A gummy bear.", category: "General", author: null },
  { id: 55, joke: "What did the sushi say to the bee? Wasabi!", category: "Food", author: null },
  { id: 56, joke: "Why did the Python programmer need glasses? To distinguish between C and see.", category: "Programming", author: null },
  { id: 57, joke: "A programmer's wife tells him: 'Go to the store and buy a loaf of bread. If they have eggs, buy a dozen.' He comes home with 12 loaves.", category: "Programming", author: null },
  { id: 58, joke: "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.", category: "Programming", author: null },
  { id: 59, joke: "What's the object-oriented way to become wealthy? Inheritance.", category: "Programming", author: null },
  { id: 60, joke: "Why did the developer go broke? He used up all his cache.", category: "Technology", author: null },
  { id: 61, joke: "Why was the computer cold? It left its Windows open.", category: "Technology", author: null },
  { id: 62, joke: "What did the duck say when it bought lipstick? Put it on my bill.", category: "Animals", author: null },
  { id: 63, joke: "What do you call a lazy kangaroo? Pouch potato.", category: "Animals", author: null },
  { id: 64, joke: "Why did the man get fired from the orange juice factory? He couldn't concentrate.", category: "Office", author: null },
  { id: 65, joke: "Why did the kid eat his homework? Because his teacher said it was a piece of cake.", category: "Kids", author: null },
];

export const API_URL = "https://official-joke-api.appspot.com/random_joke";
export const API_CATEGORY_URL = "https://official-joke-api.appspot.com/jokes";
