const seo = {
  title: "Announcement Graphic Maker With a Modular Type",
  metaDescription:
    "Six templates at real placement sizes, from 1080x1080 Instagram to a 1200x400 email banner, with type sized by one ratio and a countdown line in UTC days.",
  steps: [
    "Pick one of the six Template buttons — Launch, Product update, Event, We're hiring, Milestone or Maintenance — then fill \"Headline\" (90 characters maximum), \"Eyebrow\" and \"Subhead\".",
    "Set \"Placement size\" from Instagram square 1080x1080 to Email banner 1200x400, choose a \"Palette\", and pick a \"Type scale ratio\" between minor third 1.200 and golden ratio 1.618; on a dated template also set \"Countdown measured from\".",
    "The canvas redraws live and the \"PNG\" button downloads announcement-<template>-<width>x<height>.png, while \"Copy details\" copies the headline size and layout figures.",
  ],
  intro:
    "An announcement graphic is the image that carries a launch, an event date, a new hire or a maintenance window, and this generator builds one from six templates at real placement sizes. Type sizes come off a modular scale rather than being picked by hand: the headline sits at step zero and each supporting line drops one step, multiplied by a chosen ratio — minor third 1.200, major third 1.250, perfect fourth 1.333 or the golden ratio 1.618 — which is what keeps the hierarchy readable at any canvas size. Give the tool a date and a reference day and it adds a countdown line calculated in whole UTC days.",
  useCases: [
    "Announce a release across an Instagram post, a story and a LinkedIn image without re-laying the type out three times.",
    "Build an event graphic that says 'In 13 days' and updates cleanly as the date approaches.",
    "Post a scheduled maintenance window with the start time and no call to action, using the template that hides the CTA automatically.",
    "Produce a 1200x400 email banner from the same headline and palette as the social posts.",
  ],
  benefits: [
    ["Modular type scale", "Every size is derived from one ratio, so headline, subhead and CTA never end up nearly the same size."],
    ["Hierarchy warning", "Flags a headline less than 1.5x the subhead, the point where the two sizes stop reading as a hierarchy."],
    ["Deterministic countdown", "The reference date is an input, not the system clock, so the same settings always produce the same graphic."],
  ],
  faqs: [
    [
      "What is a modular type scale?",
      "It is a set of font sizes generated by repeatedly multiplying a base size by a fixed ratio. With a perfect fourth (1.333) and a 100px headline, the next step down is 75px and the one after that is 56px. Using a scale instead of arbitrary numbers is what makes a hierarchy look intentional.",
    ],
    [
      "Which type scale ratio should I use?",
      "A perfect fourth (1.333) is the safe default for display type — big enough a jump to be obvious, small enough that three steps still fit a canvas. Use the golden ratio (1.618) for a dramatic single-headline layout, and a minor third (1.200) when you have four or more levels to fit.",
    ],
    [
      "How long should an announcement headline be?",
      "Under about 45 characters, or roughly six words. This tool refuses anything over 90 characters because past that the headline has to be set too small to work at feed size — that detail belongs in the subhead or the caption.",
    ],
    [
      "Why does the countdown ask for today's date?",
      "So the calculation is reproducible. The days are counted between two UTC midnights you supply, which means the graphic renders identically on any machine and in any time zone, and you can generate a post dated for the day you actually intend to publish.",
    ],
  ],
};

export default seo;
