import { saveAs } from "file-saver";
import jsPDF from "jspdf";

export function exportAs(results, format, extras = {}) {
  switch (format) {
    case "pdf":
      return exportPDF(results, extras);
    default:
      return exportPDF(results, extras);
  }
}

function exportPDF(results, { paletteA, paletteB, geoA, geoB } = {}) {
  const doc = new jsPDF();
  let y = 20;
  const margin = 20;
  const pw = doc.internal.pageSize.getWidth();

  doc.setFontSize(22);
  doc.setTextColor("#14B8A6");
  doc.text("Logo Similarity Report", pw / 2, y, { align: "center" });
  y += 12;

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated: ${new Date().toLocaleString()}`, pw / 2, y, { align: "center" });
  y += 8;
  doc.text("This tool estimates visual similarity between two uploaded logos.", pw / 2, y, { align: "center" });
  y += 6;
  doc.text("It is intended for design comparison only and should not be used as legal or trademark advice.", pw / 2, y, { align: "center" });
  y += 12;

  doc.setDrawColor("#ddd");
  doc.line(margin, y, pw - margin, y);
  y += 10;

  doc.setFontSize(16);
  doc.setTextColor("#111827");
  doc.text(`Overall Similarity: ${results.overall}%`, margin, y);
  y += 8;

  const metrics = [
    ["Shape", results.shape],
    ["Color", results.color],
    ["Icon", results.icon],
    ["Text/Typography", results.text],
    ["Layout", results.layout],
    ["Edge", results.edge],
    ["Geometry", results.geometry],
    ["Symmetry", results.symmetry],
    ["Brightness", results.brightness],
    ["Contrast", results.contrast],
  ];

  doc.setFontSize(10);
  for (const [label, val] of metrics) {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.text(`${label}: ${val}%`, margin + 5, y);
    y += 6;
  }

  y += 6;
  doc.setDrawColor("#ddd");
  doc.line(margin, y, pw - margin, y);
  y += 8;

  if (paletteA?.length) {
    doc.setFontSize(12);
    doc.text("Dominant Colors — Logo A", margin, y);
    y += 6;
    for (const c of paletteA.slice(0, 5)) {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.setFillColor(...c.rgb);
      doc.rect(margin, y, 8, 8, "F");
      doc.setFontSize(8);
      doc.setTextColor(50);
      doc.text(`${c.hex} (${Math.round(c.percentage)}%)`, margin + 12, y + 6);
      y += 10;
    }
    y += 4;
  }

  if (geoA) {
    doc.setFontSize(12);
    doc.setTextColor("#111827");
    doc.text("Shape Analysis — Logo A", margin, y);
    y += 6;
    doc.setFontSize(8);
    doc.setTextColor(80);
    doc.text(`Coverage: ${geoA.coverage}% | Edge Density: ${geoA.edgeDensity}% | Roundness: ${geoA.roundness}%`, margin, y);
    y += 4;
    doc.text(`Aspect Ratio: ${geoA.aspectRatio} | Complexity: ${geoA.complexity}`, margin, y);
    y += 8;
  }

  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by Logo Similarity Checker", pw / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });

  doc.save("logo-similarity-report.pdf");
}
