/**
 * CI build matrix explosion estimator.
 *
 * Matrix semantics from GitHub's docs, "Running variations of jobs in a
 * workflow" (docs.github.com/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow):
 *  - The matrix generates one job per combination of dimension values —
 *    the cartesian product of every dimension's value count.
 *  - `exclude` removes matching combinations; `include` entries that match no
 *    existing combination ADD extra jobs.
 *  - A matrix may generate at most 256 jobs per workflow run; more fails the
 *    workflow. (GitLab's parallel:matrix caps at 200 jobs per pipeline for
 *    comparison.)
 *  - `max-parallel` caps how many matrix jobs run concurrently; by default
 *    GitHub runs as many as runner availability allows.
 */

/** GitHub's hard cap on jobs generated by one matrix. */
export const GITHUB_MATRIX_JOB_LIMIT = 256;

/** GitLab's parallel:matrix cap, shown for teams on other CI systems. */
export const GITLAB_MATRIX_JOB_LIMIT = 200;

/** Days used to project a monthly total (a fixed 30-day month, stated in the UI). */
export const DAYS_PER_MONTH = 30;

/**
 * Parse dimension lines like "os: ubuntu-latest, windows-latest, macos-latest".
 * A line may also be just a comma-separated list (name auto-assigned).
 * @returns {object} { dimensions: [{ name, values, count }] } or { error }
 */
export function parseDimensions(text) {
  if (typeof text !== "string" || text.trim() === "") {
    return { error: "Enter at least one matrix dimension, e.g. os: ubuntu-latest, macos-latest." };
  }
  const dimensions = [];
  const lines = text.split(/\r?\n/);
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index].trim();
    if (line === "" || line.startsWith("#")) continue;
    const colon = line.indexOf(":");
    const name = colon > 0 ? line.slice(0, colon).trim() : `dim${dimensions.length + 1}`;
    const valuesPart = colon > 0 ? line.slice(colon + 1) : line;
    const values = valuesPart
      .split(",")
      .map((value) => value.trim())
      .filter(Boolean);
    if (values.length === 0) {
      return { error: `Line ${index + 1}: dimension "${name}" has no values.` };
    }
    if (new Set(values).size !== values.length) {
      return { error: `Line ${index + 1}: dimension "${name}" repeats a value — each value counts once.` };
    }
    if (dimensions.some((dimension) => dimension.name === name)) {
      return { error: `Dimension "${name}" is declared twice — merge its values onto one line.` };
    }
    dimensions.push({ name, values, count: values.length });
  }
  if (dimensions.length === 0) {
    return { error: "Enter at least one matrix dimension." };
  }
  if (dimensions.length > 10) {
    return { error: "More than 10 dimensions — no CI system fans out that far; simplify first." };
  }
  return { dimensions };
}

/**
 * Estimate the matrix fan-out.
 * @param {object} input
 * @param {string} input.dimensionsText  One dimension per line.
 * @param {number} [input.includeCount]  include entries that add NEW combinations.
 * @param {number} [input.excludeCount]  combinations removed by exclude.
 * @param {number} input.avgJobMinutes   Average duration of one matrix job.
 * @param {number} [input.maxParallel]   0 or empty = unlimited.
 * @param {number} [input.runsPerDay]    Workflow runs per day for projections.
 * @returns {object} result or { error }
 */
export function estimateMatrix({
  dimensionsText,
  includeCount = 0,
  excludeCount = 0,
  avgJobMinutes,
  maxParallel = 0,
  runsPerDay = 1,
}) {
  const parsed = parseDimensions(dimensionsText);
  if (parsed.error) return { error: parsed.error };
  const { dimensions } = parsed;

  const includes = Number(includeCount);
  const excludes = Number(excludeCount);
  const minutes = Number(avgJobMinutes);
  const parallel = Number(maxParallel);
  const runs = Number(runsPerDay);

  if (!Number.isInteger(includes) || includes < 0) {
    return { error: "Include entries must be a whole number of 0 or more." };
  }
  if (!Number.isInteger(excludes) || excludes < 0) {
    return { error: "Excluded combinations must be a whole number of 0 or more." };
  }
  if (!Number.isFinite(minutes) || minutes <= 0) {
    return { error: "Average job duration must be more than 0 minutes." };
  }
  if (minutes > 360) {
    return { error: "GitHub-hosted jobs are cancelled after 360 minutes — use a shorter average." };
  }
  if (!Number.isInteger(parallel) || parallel < 0) {
    return { error: "max-parallel must be a whole number (0 = unlimited)." };
  }
  if (!Number.isFinite(runs) || runs < 0 || runs > 10000) {
    return { error: "Runs per day must be between 0 and 10,000." };
  }

  const product = dimensions.reduce((total, dimension) => total * dimension.count, 1);
  if (excludes >= product + includes) {
    return {
      error: `You are excluding ${excludes} combinations but the matrix only makes ${product}${includes > 0 ? ` (+${includes} includes)` : ""} — nothing would run.`,
    };
  }

  const jobs = product - excludes + includes;
  const warnings = [];
  if (jobs > GITHUB_MATRIX_JOB_LIMIT) {
    warnings.push(
      `${jobs} jobs exceeds GitHub's ${GITHUB_MATRIX_JOB_LIMIT}-job matrix limit — the workflow will FAIL to start. Split the matrix or cut a dimension.`,
    );
  } else if (jobs > GITLAB_MATRIX_JOB_LIMIT) {
    warnings.push(
      `${jobs} jobs fits GitHub's ${GITHUB_MATRIX_JOB_LIMIT} limit but exceeds GitLab's ${GITLAB_MATRIX_JOB_LIMIT}-job parallel:matrix cap.`,
    );
  }
  if (product > 0 && excludes / product > 0.5) {
    warnings.push(
      "You exclude more than half the matrix — listing the wanted combos directly via include entries is clearer.",
    );
  }

  const minutesPerRun = jobs * minutes;
  const effectiveParallel = parallel === 0 ? jobs : Math.min(parallel, jobs);
  // With N-way parallelism, jobs run in waves of N equal-length jobs.
  const wallClockMinutes = Math.ceil(jobs / effectiveParallel) * minutes;
  const minutesPerDay = minutesPerRun * runs;
  const minutesPerMonth = minutesPerDay * DAYS_PER_MONTH;

  return {
    dimensions,
    product,
    includes,
    excludes,
    jobs,
    withinGithubLimit: jobs <= GITHUB_MATRIX_JOB_LIMIT,
    minutesPerRun,
    wallClockMinutes,
    effectiveParallel,
    minutesPerDay,
    minutesPerMonth,
    warnings,
  };
}
