const seo = {
  intro:
    "A PAN is ten characters in the pattern AAAAA9999A, and its fourth character encodes the status of the holder — P for an individual, C for a company, H for a Hindu Undivided Family, F for a firm, T for a trust. This tool checks that structure offline, decodes the status code, and optionally tests the fifth character against a surname, which is where most PAN-name mismatches come from. It suits accounts teams validating vendor masters and developers who want a client-side check before calling a verification API.",
  useCases: [
    "Working out from a PAN alone whether a counterparty is a company, a firm or an individual before deciding the TDS section to apply.",
    "Explaining a PAN-name mismatch to an employee whose fifth character comes from the surname rather than the first name.",
    "Screening a pasted list of PANs for structurally impossible entries before an upload rejects the whole file.",
  ],
  benefits: [
    ["Decodes the status code", "Maps all ten status characters defined by the Income Tax Department."],
    ["Surname check", "Compares the fifth character with the surname or entity name you supply."],
    ["Redaction output", "Produces a masked form that keeps the status code readable but hides the identifying digits."],
  ],
  faqs: [
    [
      "What does the 4th letter of a PAN card mean?",
      "It is the status of the holder. P means an individual, C a company, H a Hindu Undivided Family, F a firm, A an association of persons, T a trust, B a body of individuals, L a local authority, J an artificial juridical person and G a government body. Limited liability partnerships (LLPs) also use the F code — there is no separate LLP status code.",
    ],
    [
      "Why does my PAN not match my name?",
      "Because the fifth character of a PAN is the first letter of the surname for an individual, not the first name. If your PAN reads ABCPK1234M and your surname is Kumar, the K is correct even though your given name starts with a different letter.",
    ],
    [
      "Can a PAN be verified without the internet?",
      "Only its structure. The tenth character is a check character generated by the Income Tax Department using an algorithm that has never been published, so an offline tool cannot confirm that a PAN was actually issued. Use the e-filing portal's Verify your PAN service for that.",
    ],
    [
      "What is the penalty for quoting a wrong PAN?",
      "Section 272B provides a penalty of Rs 10,000 for quoting a false PAN in any document where it is required. Separately, a landlord's PAN must be reported to your employer once annual rent exceeds Rs 1,00,000, per CBDT Circular No. 8/2013, or the HRA exemption can be denied.",
    ],
  ],
};

export default seo;
