// Themed word pools shared by every puzzle. Entries are uppercase A-Z with no
// spaces or punctuation so they can be written straight onto the letter grid.
// Each theme mixes short and long words so all three grid sizes have plenty of
// candidates (8x8 only uses words of 8 letters or fewer, and so on).

const THEMES = {
  animals: {
    label: "Animals",
    words: [
      "FOX",
      "BEAR",
      "WOLF",
      "DEER",
      "LION",
      "TIGER",
      "ZEBRA",
      "PANDA",
      "EAGLE",
      "SHARK",
      "WHALE",
      "OTTER",
      "KOALA",
      "CAMEL",
      "MOOSE",
      "LEMUR",
      "GECKO",
      "BISON",
      "RABBIT",
      "MONKEY",
      "TURTLE",
      "FALCON",
      "DOLPHIN",
      "GIRAFFE",
      "PENGUIN",
      "LEOPARD",
      "OCTOPUS",
      "ELEPHANT",
      "KANGAROO",
      "HEDGEHOG",
      "SQUIRREL",
      "FLAMINGO",
      "CROCODILE",
      "BUTTERFLY",
      "CHIMPANZEE",
      "RHINOCEROS",
    ],
  },
  countries: {
    label: "Countries",
    words: [
      "PERU",
      "CUBA",
      "CHAD",
      "FIJI",
      "INDIA",
      "JAPAN",
      "CHINA",
      "SPAIN",
      "ITALY",
      "EGYPT",
      "KENYA",
      "CHILE",
      "GHANA",
      "NEPAL",
      "QATAR",
      "BRAZIL",
      "FRANCE",
      "CANADA",
      "MEXICO",
      "NORWAY",
      "POLAND",
      "TURKEY",
      "GREECE",
      "SWEDEN",
      "GERMANY",
      "AUSTRIA",
      "FINLAND",
      "ICELAND",
      "IRELAND",
      "VIETNAM",
      "MOROCCO",
      "PORTUGAL",
      "THAILAND",
      "MALAYSIA",
      "ARGENTINA",
      "AUSTRALIA",
      "INDONESIA",
      "SINGAPORE",
      "SWITZERLAND",
      "NETHERLANDS",
    ],
  },
  food: {
    label: "Fruits & Food",
    words: [
      "PIE",
      "RICE",
      "TACO",
      "PLUM",
      "KIWI",
      "MANGO",
      "APPLE",
      "GRAPE",
      "LEMON",
      "PEACH",
      "OLIVE",
      "BREAD",
      "PIZZA",
      "PASTA",
      "SALAD",
      "HONEY",
      "BANANA",
      "CHERRY",
      "ORANGE",
      "TOMATO",
      "CARROT",
      "CHEESE",
      "WAFFLE",
      "NOODLE",
      "PAPAYA",
      "AVOCADO",
      "COCONUT",
      "PANCAKE",
      "BURRITO",
      "PRETZEL",
      "CUCUMBER",
      "BROCCOLI",
      "DUMPLING",
      "PINEAPPLE",
      "BLUEBERRY",
      "RASPBERRY",
      "STRAWBERRY",
      "WATERMELON",
    ],
  },
  technology: {
    label: "Technology",
    words: [
      "APP",
      "CODE",
      "DATA",
      "WIFI",
      "CHIP",
      "ROBOT",
      "EMAIL",
      "CLOUD",
      "MOUSE",
      "PIXEL",
      "CACHE",
      "LASER",
      "MODEM",
      "DRONE",
      "SERVER",
      "ROUTER",
      "CAMERA",
      "LAPTOP",
      "TABLET",
      "SENSOR",
      "SCREEN",
      "BROWSER",
      "NETWORK",
      "MONITOR",
      "PODCAST",
      "KEYBOARD",
      "INTERNET",
      "SOFTWARE",
      "HARDWARE",
      "COMPILER",
      "DATABASE",
      "FIREWALL",
      "TERMINAL",
      "ALGORITHM",
      "PROCESSOR",
      "SATELLITE",
      "ENCRYPTION",
    ],
  },
};

export const THEME_KEYS = Object.keys(THEMES);

export default THEMES;
