export const DEFAULT_PARAMS = {
  aspectRatio: "16:9",
  resolution: "2048×1152",
  seed: 0,
  imageCount: 4,
  quality: 85,
  chaos: 15,
  stylize: 250,
  promptStrength: 70,
  creativity: 60,
  artStyle: "auto",
  renderStyle: "auto",
  camera: "auto",
  lighting: "auto",
  lens: "auto",
  composition: "auto",
  mood: "auto",
  palette: "auto",
  videoDuration: 5,
  fps: 24,
  motionLevel: 55,
  transition: "cross dissolve",
  voiceStyle: "warm narrator",
  narrationStyle: "documentary",
  musicMood: "cinematic ambient",
  negativePrompt: "",
};
