"use client";

import { useState } from "react";
import {
  Lightbulb,
  Copy,
  Heart,
  TrendingUp,
  Users,
  DollarSign,
  Target,
  AlertTriangle,
  Building2,
  Cpu,
  RefreshCw,
  Briefcase,
  BarChart3,
} from "lucide-react";

function Stat({ icon, label, value, color }) {
  return (
    <div className="flex items-start gap-2.5 p-2.5 rounded-lg bg-(--page) border border-(--border)">
      <div className={`flex-shrink-0 w-8 h-8 rounded-lg flex items-center justify-center ${color}`}>
        {icon}
      </div>
      <div className="min-w-0">
        <p className="text-xs font-medium text-(--muted-foreground)">{label}</p>
        <p className="text-sm font-medium truncate">{value}</p>
      </div>
    </div>
  );
}

const COLOR_MAP = {
  industry: "bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400",
  technology: "bg-violet-100 dark:bg-violet-900/30 text-violet-600 dark:text-violet-400",
  model: "bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400",
  audience: "bg-amber-100 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400",
  cost: "bg-rose-100 dark:bg-rose-900/30 text-rose-600 dark:text-rose-400",
  monetization: "bg-cyan-100 dark:bg-cyan-900/30 text-cyan-600 dark:text-cyan-400",
};

export default function IdeaCard({ idea, rank, onSave, isSaved, onRegenerate }) {
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(false);

  const copyText = () => {
    const lines = [
      `💡 ${idea.companyName}`,
      idea.tagline,
      "",
      `Industry: ${idea.industry}`,
      `Problem: ${capitalize(idea.problem)}`,
      `Technology: ${idea.technology}`,
      `Business Model: ${capitalize(idea.businessModel)}`,
      `Target Audience: ${capitalize(idea.audience)}`,
      `Startup Cost: ${idea.startupCost}`,
      `Monetization: ${idea.monetization}`,
      "",
      idea.description,
      "",
      `Why it could work: ${idea.whyItWorks}`,
      "",
      `Top challenges:`,
      ...idea.challenges.map((c) => `• ${c}`),
      "",
      `Feasibility score: ${idea.score}%`,
      "",
      "Generated by ALTFTool Random Business Idea Generator",
    ];
    navigator.clipboard.writeText(lines.join("\n"));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const capitalize = (s) => s.charAt(0).toUpperCase() + s.slice(1);

  const scoreColor =
    idea.score >= 85
      ? "text-emerald-500"
      : idea.score >= 70
      ? "text-amber-500"
      : "text-sky-500";

  return (
    <div className="rounded-2xl border border-(--border) bg-(--surface) shadow-md overflow-hidden animate-in fade-in zoom-in-95 duration-300">
      <div className="p-5 pb-3 border-b border-(--border)">
        <div className="flex items-start justify-between gap-3">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1">
              {rank !== undefined && (
                <span className="w-6 h-6 rounded-full bg-(--primary) text-white flex items-center justify-center text-xs font-bold flex-shrink-0">
                  {rank + 1}
                </span>
              )}
              <h3 className="text-base font-bold truncate">{idea.companyName}</h3>
            </div>
            <p className="text-sm text-(--muted-foreground) leading-relaxed">{idea.tagline}</p>
          </div>
          <div className="flex flex-col items-center gap-1 flex-shrink-0">
            <div className={`text-lg font-bold ${scoreColor}`}>{idea.score}%</div>
            <p className="text-[10px] text-(--muted-foreground) uppercase tracking-wide">Feasibility</p>
          </div>
        </div>
      </div>

      <div className="p-5 space-y-4">
        <div className="grid grid-cols-2 gap-2">
          <Stat
            icon={<Building2 className="w-4 h-4" />}
            label="Industry"
            value={idea.industry}
            color={COLOR_MAP.industry}
          />
          <Stat
            icon={<Cpu className="w-4 h-4" />}
            label="Technology"
            value={idea.technology}
            color={COLOR_MAP.technology}
          />
          <Stat
            icon={<Briefcase className="w-4 h-4" />}
            label="Business Model"
            value={capitalize(idea.businessModel)}
            color={COLOR_MAP.model}
          />
          <Stat
            icon={<Users className="w-4 h-4" />}
            label="Target Audience"
            value={capitalize(idea.audience)}
            color={COLOR_MAP.audience}
          />
          <Stat
            icon={<DollarSign className="w-4 h-4" />}
            label="Startup Cost"
            value={idea.startupCost}
            color={COLOR_MAP.cost}
          />
          <Stat
            icon={<BarChart3 className="w-4 h-4" />}
            label="Monetization"
            value={idea.monetization}
            color={COLOR_MAP.monetization}
          />
        </div>

        <div className="p-3 rounded-xl bg-(--page) border border-(--border)">
          <p className="text-xs font-semibold text-(--muted-foreground) uppercase tracking-wide mb-1">
            The Problem It Solves
          </p>
          <p className="text-sm">
            <Target className="w-3.5 h-3.5 inline text-(--primary) mr-1" />
            {capitalize(idea.problem)}
          </p>
        </div>

        <div>
          <p className="text-sm leading-relaxed">{idea.description}</p>
        </div>

        {expanded && (
          <div className="space-y-4 animate-in fade-in slide-in-from-top-2 duration-200">
            <div className="p-3 rounded-xl bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800/30">
              <p className="text-xs font-semibold text-emerald-600 dark:text-emerald-400 uppercase tracking-wide mb-1 flex items-center gap-1">
                <TrendingUp className="w-3.5 h-3.5" />
                Why It Could Work
              </p>
              <p className="text-sm">{idea.whyItWorks}</p>
            </div>

            <div className="p-3 rounded-xl bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800/30">
              <p className="text-xs font-semibold text-amber-600 dark:text-amber-400 uppercase tracking-wide mb-1 flex items-center gap-1">
                <AlertTriangle className="w-3.5 h-3.5" />
                Challenges
              </p>
              <ul className="space-y-1">
                {idea.challenges.map((c, i) => (
                  <li key={i} className="text-sm flex items-start gap-2">
                    <span className="w-1 h-1 rounded-full bg-amber-400 mt-1.5 flex-shrink-0" />
                    {c}
                  </li>
                ))}
              </ul>
            </div>

            {idea.competitors && (
              <div>
                <p className="text-xs font-semibold text-(--muted-foreground) uppercase tracking-wide mb-1">
                  Potential Competitors
                </p>
                <ul className="space-y-1">
                  {idea.competitors.map((c, i) => (
                    <li key={i} className="text-sm flex items-center gap-2">
                      <span className="w-4 h-4 rounded-full bg-(--page) border border-(--border) flex items-center justify-center text-[10px] font-bold text-(--muted-foreground)">C</span>
                      {c}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}

        <div className="flex items-center justify-between pt-1">
          <button
            onClick={() => setExpanded(!expanded)}
            className="text-xs font-medium text-(--primary) hover:underline"
          >
            {expanded ? "Show less" : "Show full analysis"}
          </button>

          <div className="flex gap-1.5">
            <button
              onClick={copyText}
              className="p-1.5 rounded-lg hover:bg-(--page) transition border border-(--border)"
              title="Copy"
            >
              {copied ? (
                <span className="text-xs font-medium text-(--primary) px-1">Copied!</span>
              ) : (
                <Copy className="w-3.5 h-3.5 text-(--muted-foreground)" />
              )}
            </button>
            <button
              onClick={() => onSave(idea)}
              className={`p-1.5 rounded-lg border border-(--border) transition ${
                isSaved ? "bg-red-50 dark:bg-red-900/20" : "hover:bg-(--page)"
              }`}
              title={isSaved ? "Saved" : "Save"}
            >
              <Heart
                className={`w-3.5 h-3.5 ${
                  isSaved ? "text-red-500 fill-red-500" : "text-(--muted-foreground)"
                }`}
              />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
