/*
 * AltF Persona — the character sheet as a file
 *
 * The studio renders a sheet you can read. This renders the same sheet as one
 * Markdown document you can commit, attach to a brief, or hand to whoever is
 * actually going to run the generations.
 *
 * That is not a nicety. The whole argument against a hosted AI-influencer
 * product is that a persona should be portable text you own rather than an
 * account you rent — and a product that only ever shows you the text inside its
 * own interface has not really made that argument.
 *
 * Deterministic, like everything else here: no clock, no randomness, so the
 * same spec always produces a byte-identical file and a diff between two
 * versions of a persona is readable.
 */

import { composeSheet, describeSpec, specToQuery } from "./compose.js";
import { buildDisclosure } from "./disclosure.js";
import { buildPlan, buildShotList } from "./plan.js";
import { MARKET_BY_ID } from "./taxonomy.js";

function fence(text, language = "") {
  return ["```" + language, text, "```"].join("\n");
}

/**
 * @param spec    a persona spec
 * @param options.shareUrl  absolute URL that reopens this spec in the studio.
 *                          Passed in rather than derived, because core has no
 *                          business knowing the site's own origin.
 */
export function sheetMarkdown(spec, options = {}) {
  const sheet = composeSheet(spec);
  const { spec: safe, seed, route } = sheet;
  const disclosure = buildDisclosure({ spec: safe });
  const plan = buildPlan(safe, { route });
  const shotList = buildShotList(plan);
  const market = MARKET_BY_ID[safe.market] || MARKET_BY_ID.global;
  const name = safe.name || "Unnamed persona";

  const lines = [];
  const push = (...rows) => lines.push(...rows);

  push(`# ${name}`, "");
  push(
    [
      safe.handle ? `@${safe.handle}` : null,
      sheet.niche.label,
      sheet.platform.label,
      market.label,
      disclosure.language.label,
    ]
      .filter(Boolean)
      .join(" · "),
    "",
  );
  push(
    `- **Identity seed:** \`${seed.token}\``,
    `- **Generation seed:** \`${seed.numeric}\``,
    `- **Production route:** ${route.route.label} — ${route.route.blurb}`,
    "",
  );

  push("## The locked line", "");
  push(
    "Paste this verbatim into every prompt. Rewording it is the single most",
    "common cause of a face moving, and it never looks like the cause because",
    "the sentence still means the same thing to you.",
    "",
  );
  push(fence(sheet.lockedLine), "");

  push("## Styling line", "");
  push(fence(sheet.styleLine), "");

  push("## Negative prompt", "");
  push(fence(sheet.negative), "");

  push("## Prompt kits", "");
  for (const kit of sheet.kits) {
    push(`### ${kit.label}`, "", `_${kit.consistency}_`, "", fence(kit.text), "");
  }

  push("## Why this route", "");
  for (const reason of route.reasons) {
    push(`- ${reason.weight === "up" ? "↑" : "↓"} ${reason.text}`);
  }
  push("");

  push("## Reproduction checklist", "");
  sheet.checklist.forEach((item, index) => {
    push(`${index + 1}. **${item.title}** — ${item.detail}`);
  });
  push("");

  push("## Trait ledger", "", "| Field | Value |", "| --- | --- |");
  for (const row of describeSpec(safe)) {
    push(`| ${row.label} | ${row.value} |`);
  }
  push("");

  push("## Disclosure", "");
  push(`Market: **${market.label}** (${market.regulator}) · Platform: **${disclosure.platform.label}**`, "");
  push(`- Profile line: \`${disclosure.profileLine}\``);
  push(`- Caption line: \`${disclosure.captionLine}\``);
  push(`- Placement: ${disclosure.placement}`);
  push("");
  for (const item of disclosure.obligations) {
    push(`- **${item.title}** — ${item.detail}`);
  }
  push("", `> ${disclosure.disclaimer}`, "");

  push("## First 30 days", "");
  push(
    `${plan.summary.posts} posts, ${plan.summary.restDays} rest days,`,
    `${plan.summary.distinctShots} distinct setups, about`,
    `${Math.round(plan.summary.productionMinutes / 60)} hours of production.`,
    "",
  );
  push("### Batch by setup", "", "| Shot | Times | Days |", "| --- | --- | --- |");
  for (const row of shotList) {
    push(`| ${row.shot.title} | ${row.count} | ${row.days.join(", ")} |`);
  }
  push("");

  push("### Calendar", "", "| Day | Pillar | Shot | Hook |", "| --- | --- | --- | --- |");
  for (const day of plan.days) {
    if (day.rest) continue;
    push(
      `| ${day.day} | ${day.pillar.label} | ${day.shot?.title || "—"} | ${String(
        day.hook || "",
      ).replace(/\|/g, "\\|")} |`,
    );
  }
  push("");

  push("---", "");
  push(
    options.shareUrl
      ? `Generated by AltF Persona. Reopen this sheet: ${options.shareUrl}`
      : "Generated by AltF Persona.",
  );
  push(
    "",
    "AltF Persona does not generate images. It specifies the character so the",
    "images you generate elsewhere are of the same person.",
  );

  return lines.join("\n");
}

/** A stable, filesystem-safe filename for a sheet. */
export function sheetFilename(spec) {
  const { spec: safe, seed } = composeSheet(spec);
  const stem =
    (safe.handle || safe.name || "persona")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "persona";
  return `${stem}-${seed.token}.md`;
}

/** The query string half of a share URL, so callers only add the origin. */
export function sheetShareQuery(spec) {
  return specToQuery(spec);
}
