const seo = {
  intro:
    "The Roast Generator picks a comeback at random from 31 hand-written lines sorted into four intensity tiers — playful, savage, witty and dark humour — and optionally addresses it to a name you type. Choose a tier, hit generate, and you get a one-liner you can copy straight into a group chat or a toast. Nothing is generated by a model, so the tone of each tier is exactly what the tier says it is.",
  useCases: [
    "You are writing a best-man speech or a birthday toast and need one affectionate jab that will not land badly with the grandparents in the room.",
    "A friend is dunking on you in the group chat and you want a witty reply in the next ten seconds rather than the perfect one an hour later.",
    "You are hosting a roast-battle game night and need a stack of prompts at a known intensity so nobody wanders into genuinely hurtful territory.",
  ],
  benefits: [
    ["Intensity is a real setting", "Playful, savage, witty and dark are separate hand-curated lists, so picking a tier actually changes how hard the line hits instead of nudging a slider."],
    ["Personalises without mangling the joke", "Adding a name prefixes the line with a natural opener such as \"Hey\" or \"Yo\" and lowercases the rest so the sentence still reads correctly."],
    ["Instantly reusable", "Every result has a one-tap copy and a re-roll, so you can cycle through the tier until one fits the moment."],
  ],
  faqs: [
    [
      "How does the roast generator work?",
      "It selects one line at random from the list matching your chosen intensity — playful, savage, witty or dark humour — out of 31 written lines in total. If you enter a name, that name is inserted at the front of the line before it is shown.",
    ],
    [
      "Can I put someone's name in the roast?",
      "Yes. Type a name in the optional field and the generated line becomes something like \"Hey Sam — …\", using one of five openers picked at random. Leave the field blank and you get the plain line.",
    ],
    [
      "What is the difference between playful and savage roasts?",
      "Playful lines are gentle absurdities meant for people who will laugh along; savage lines are blunter and land harder. Witty leans on wordplay rather than insult, and dark humour is the sharpest tier — worth previewing before you read it out loud.",
    ],
    [
      "Is it okay to use these on people?",
      "Only where everyone is in on the joke. Roasting works between friends who have agreed to it and fails badly as a way to insult someone who has not — pick the playful tier when in doubt, and never aim any of these at someone's appearance, identity or a subject they are actually sensitive about.",
    ],
  ],
};

export default seo;
