export const APPLIANCES = [
  { id: "led-bulb", name: "LED bulb", watts: 9, group: "Lights" },
  { id: "cfl", name: "CFL bulb", watts: 15, group: "Lights" },
  { id: "tube-light", name: "LED tube light", watts: 20, group: "Lights" },
  { id: "ceiling-fan", name: "Ceiling fan", watts: 75, group: "Fans & cooling" },
  { id: "table-fan", name: "Table / pedestal fan", watts: 55, group: "Fans & cooling" },
  { id: "exhaust-fan", name: "Exhaust fan", watts: 30, group: "Fans & cooling" },
  {
    id: "air-cooler",
    name: "Air cooler",
    watts: 200,
    surge: 450,
    group: "Fans & cooling",
    note: "The pump and blower motor draw a short starting spike.",
  },
  { id: "led-tv", name: "LED TV (43 inch)", watts: 100, group: "Entertainment" },
  { id: "set-top-box", name: "Set-top box", watts: 15, group: "Entertainment" },
  { id: "wifi-router", name: "WiFi router", watts: 10, group: "Entertainment" },
  { id: "laptop", name: "Laptop", watts: 65, group: "Entertainment" },
  { id: "desktop", name: "Desktop PC + monitor", watts: 200, group: "Entertainment" },
  { id: "phone-charger", name: "Mobile charger", watts: 10, group: "Entertainment" },
  { id: "cctv", name: "CCTV cameras + DVR", watts: 40, group: "Entertainment" },
  {
    id: "fridge",
    name: "Refrigerator (250 L)",
    watts: 150,
    surge: 600,
    group: "Kitchen",
    note: "The compressor draws roughly 4× its running watts for a second or two at every start.",
  },
  {
    id: "mixer",
    name: "Mixer grinder",
    watts: 500,
    surge: 1000,
    group: "Kitchen",
    note: "Universal motor — starts hard, especially under load.",
  },
  {
    id: "washing-machine",
    name: "Washing machine (semi-auto)",
    watts: 500,
    surge: 1500,
    group: "Kitchen",
    note: "The spin cycle is the worst moment for the inverter.",
  },
  {
    id: "water-pump",
    name: "Water pump (0.5 HP)",
    watts: 375,
    surge: 1125,
    group: "Appliances",
    note: "Induction motor — needs roughly 3× running watts to start. Many home inverters trip on this.",
  },
  {
    id: "electric-iron",
    name: "Electric iron",
    watts: 1000,
    group: "Heavy",
    heavy: true,
    note: "A pure resistive load — it will flatten a 150 Ah battery in a bit over an hour, far faster than lights or fans.",
  },
  {
    id: "microwave",
    name: "Microwave oven",
    watts: 1200,
    group: "Heavy",
    heavy: true,
    note: "Heating loads convert battery charge straight to heat. Run it on mains.",
  },
  {
    id: "induction",
    name: "Induction cooktop",
    watts: 1500,
    group: "Heavy",
    heavy: true,
    note: "1500 W of cooking will drain a full 150 Ah battery in about 45 minutes.",
  },
  {
    id: "geyser",
    name: "Electric geyser (15 L)",
    watts: 2000,
    group: "Heavy",
    heavy: true,
    note: "Never put a geyser on a home inverter — it is the fastest way to kill a battery bank.",
  },
  {
    id: "ac-1ton",
    name: "Air conditioner (1 ton, non-inverter)",
    watts: 1200,
    surge: 3600,
    group: "Heavy",
    heavy: true,
    note: "A normal home inverter cannot start an AC. An inverter AC needs a special high-capacity pure sine wave inverter and a 48 V+ battery bank — a standard 12 V unit will simply trip.",
  },
];

export const BATTERY_TYPES = [
  {
    id: "flat",
    name: "Flat plate",
    life: "2–3 years (~400–500 cycles)",
    cost: "₹9,000–12,000 (150 Ah)",
    maintenance: "Top up distilled water every 2–3 months",
    dod: "50–60% recommended",
    bestFor: "Areas with short, rare power cuts and the tightest upfront budget",
  },
  {
    id: "tubular",
    name: "Tubular",
    life: "4–6 years (~1,200–1,500 cycles)",
    cost: "₹13,000–18,000 (150 Ah)",
    maintenance: "Top up distilled water every 4–6 months",
    dod: "70–80% recommended",
    bestFor: "Long or frequent cuts — the default choice for most Indian homes",
    popular: true,
  },
  {
    id: "lithium",
    name: "Lithium (LiFePO4)",
    life: "8–10 years (3,000–5,000 cycles)",
    cost: "₹35,000–55,000 (equivalent capacity)",
    maintenance: "None — sealed, no water, no fumes",
    dod: "80–90% usable",
    bestFor: "Daily deep cycling and small spaces; needs a compatible inverter and charger",
  },
];

export const TIPS = [
  [
    "Do not put heating or motor loads on it",
    "Geysers, induction cooktops, microwaves, ovens and ACs are either resistive heaters or hard-starting motors. A normal home inverter either trips or drains the bank in minutes. Keep them on mains.",
  ],
  [
    "Top up the water on lead-acid banks",
    "Flat plate and tubular batteries lose water through electrolysis. Check the level every 2–3 months and top up with distilled water only — never tap water, and never above the max mark.",
  ],
  [
    "Leave headroom on the VA rating",
    "Load an inverter to about 80% of its rating, not 100%. The next standard size up costs a little more and runs cooler, quieter and longer.",
  ],
  [
    "Ventilate and keep it cool",
    "Lead-acid batteries vent hydrogen while charging. Keep the bank in an open, shaded, ventilated spot — not a sealed cupboard. Every 10 °C above 27 °C roughly halves battery life.",
  ],
  [
    "Match the battery to the inverter",
    "A 24 V or 48 V inverter needs its batteries in series, all of the same make, capacity and age. Mixing an old battery with a new one drags the new one down to the old one's condition.",
  ],
  [
    "Pure sine wave for sensitive gear",
    "Square and modified sine wave inverters are cheaper but hum through fans, heat up motors and upset some medical and audio equipment. Pure sine wave is worth the difference.",
  ],
];
