const GO_KEYWORDS = new Set([
  "break", "default", "func", "interface", "select", "case", "defer", "go",
  "map", "struct", "chan", "else", "goto", "package", "switch", "const",
  "fallthrough", "if", "range", "type", "continue", "for", "import", "return",
  "var",
]);

const RESERVED_NAMES = new Set(["ID", "URL", "API", "JSON", "HTTP", "HTTPS", "XML", "SQL", "UUID", "IP"]);

function sanitizeIdentifier(value, fallback = "Field") {
  const words = String(value || "")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean);

  const name = words.map((word) => {
    const upper = word.toUpperCase();
    if (RESERVED_NAMES.has(upper)) return upper;
    return `${word.charAt(0).toUpperCase()}${word.slice(1)}`;
  }).join("") || fallback;

  const safe = /^[0-9]/.test(name) ? `${fallback}${name}` : name;
  return GO_KEYWORDS.has(safe.toLowerCase()) ? `${safe}Field` : safe;
}

function isIntegerNumber(value) {
  return Number.isInteger(value) && Number.isSafeInteger(value);
}

function primitiveType(value, nullableBehavior) {
  if (value === null) return nullableBehavior === "interface" ? "interface{}" : "interface{}";
  if (typeof value === "string") return "string";
  if (typeof value === "boolean") return "bool";
  if (typeof value === "number") return isIntegerNumber(value) ? "int" : "float64";
  return "interface{}";
}

function uniqueStructName(baseName, structs) {
  const base = sanitizeIdentifier(baseName, "AutoGenerated");
  if (!structs.has(base)) return base;
  let index = 2;
  while (structs.has(`${base}${index}`)) index += 1;
  return `${base}${index}`;
}

function mergeTypes(types) {
  const clean = [...new Set(types.filter(Boolean))];
  if (clean.length === 0) return "interface{}";
  if (clean.length === 1) return clean[0];
  if (clean.includes("float64") && clean.includes("int") && clean.length === 2) return "float64";
  return "interface{}";
}

function inferArrayType(values, contextName, structs, options, depth) {
  if (!values.length) return "[]interface{}";

  const nonNull = values.filter((value) => value !== null);
  if (!nonNull.length) {
    return options.nullableBehavior === "pointer" ? "[]interface{}" : "[]interface{}";
  }

  if (nonNull.every((item) => Array.isArray(item))) {
    const nested = mergeTypes(nonNull.map((item) => inferArrayType(item, contextName, structs, options, depth + 1)));
    return `[]${nested}`;
  }

  if (nonNull.every((item) => item && typeof item === "object" && !Array.isArray(item))) {
    const structName = buildStructFromObjects(nonNull, contextName, structs, options, depth + 1);
    return `[]${structName}`;
  }

  const inferred = nonNull.map((item) => inferType(item, contextName, structs, options, depth + 1));
  return `[]${mergeTypes(inferred)}`;
}

function applyNullable(typeName, sawNull, options) {
  if (!sawNull || options.nullableBehavior !== "pointer") return typeName;
  if (typeName.startsWith("[]") || typeName === "interface{}") return typeName;
  return `*${typeName}`;
}

function inferType(value, contextName, structs, options, depth) {
  if (Array.isArray(value)) return inferArrayType(value, contextName, structs, options, depth);
  if (value && typeof value === "object") return buildStructFromObjects([value], contextName, structs, options, depth + 1);
  return primitiveType(value, options.nullableBehavior);
}

function buildStructFromObjects(objects, requestedName, structs, options, depth) {
  const structName = uniqueStructName(requestedName, structs);
  const fieldMap = new Map();

  objects.forEach((object) => {
    Object.entries(object).forEach(([key, value]) => {
      if (!fieldMap.has(key)) {
        fieldMap.set(key, { key, values: [], sawNull: false });
      }
      const field = fieldMap.get(key);
      if (value === null) field.sawNull = true;
      field.values.push(value);
    });
  });

  const fields = [...fieldMap.values()].map((field) => {
    const nonNullValues = field.values.filter((value) => value !== null);
    const fieldName = sanitizeIdentifier(field.key, "Field");
    const childName = `${structName}${fieldName}`;
    const typeName = nonNullValues.length
      ? mergeTypes(nonNullValues.map((value) => inferType(value, childName, structs, options, depth + 1)))
      : "interface{}";

    return {
      name: fieldName,
      type: applyNullable(typeName, field.sawNull, options),
      tag: field.key,
    };
  });

  structs.set(structName, { name: structName, fields, depth });
  return structName;
}

function renderStructs(structs, packageName) {
  const ordered = [...structs.values()].sort((a, b) => a.depth - b.depth);
  const lines = [];
  if (packageName?.trim()) {
    lines.push(`package ${packageName.trim().replace(/[^a-zA-Z0-9_]/g, "").toLowerCase() || "main"}`, "");
  }

  ordered.forEach((item, index) => {
    lines.push(`type ${item.name} struct {`);
    item.fields.forEach((field) => {
      lines.push(`\t${field.name} ${field.type} \`json:"${field.tag}"\``);
    });
    lines.push("}");
    if (index < ordered.length - 1) lines.push("");
  });

  return lines.join("\n");
}

function calculateStats(parsed, code, structs) {
  let fieldCount = 0;
  let maxDepth = 0;

  function walk(value, depth) {
    maxDepth = Math.max(maxDepth, depth);
    if (Array.isArray(value)) {
      value.forEach((item) => walk(item, depth + 1));
      return;
    }
    if (value && typeof value === "object") {
      fieldCount += Object.keys(value).length;
      Object.values(value).forEach((item) => walk(item, depth + 1));
    }
  }

  walk(parsed, 1);

  return {
    jsonSize: new Blob([JSON.stringify(parsed)]).size,
    fieldCount,
    structCount: structs.size,
    nestingDepth: maxDepth,
    outputLines: code ? code.split("\n").length : 0,
  };
}

export function generateGoStructs(jsonText, options) {
  const parsed = JSON.parse(jsonText);
  const rootName = sanitizeIdentifier(options.rootName || "AutoGenerated", "AutoGenerated");
  const structs = new Map();

  if (Array.isArray(parsed)) {
    const nonNullObjects = parsed.filter((item) => item && typeof item === "object" && !Array.isArray(item));
    if (!nonNullObjects.length) {
      throw new Error("Root JSON array must contain objects to generate a root Go struct.");
    }
    buildStructFromObjects(nonNullObjects, rootName, structs, options, 1);
  } else if (parsed && typeof parsed === "object") {
    buildStructFromObjects([parsed], rootName, structs, options, 1);
  } else {
    throw new Error("Root JSON value must be an object or an array of objects.");
  }

  const code = renderStructs(structs, options.packageName);
  return {
    parsed,
    code,
    stats: calculateStats(parsed, code, structs),
    sampleJson: JSON.stringify(parsed, null, 2),
  };
}

export function formatJson(jsonText, mode = "beautify") {
  const parsed = JSON.parse(jsonText);
  return mode === "minify" ? JSON.stringify(parsed) : JSON.stringify(parsed, null, 2);
}

export function highlightGo(code) {
  const escape = (value) => value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  return escape(code)
    .replace(/(`json:&quot;.*?&quot;`|`json:"[^`]+`)/g, '<span class="jg-tag">$1</span>')
    .replace(/\b(type|struct|package)\b/g, '<span class="jg-keyword">$1</span>')
    .replace(/\b(string|int|float64|bool|interface\{\})\b/g, '<span class="jg-type">$1</span>')
    .replace(/\b([A-Z][A-Za-z0-9_]*)\b(?=\s+struct|\s+\[|\s+\*|\s+`)/g, '<span class="jg-name">$1</span>');
}
