export const THEMES = {
  "classic-chatgpt": {
    name: "Classic ChatGPT",
    primary: "#10A37F",
    bgUser: "#F7F7F8",
    bgAssistant: "#FFFFFF",
    textUser: "#1A1A2E",
    textAssistant: "#1A1A2E",
    bubbleUser: "#DCF8C6",
    bubbleAssistant: "#FFFFFF",
    fontFamily: "Söhne, ui-sans-serif, system-ui, sans-serif",
  },
  minimal: {
    name: "Minimal",
    primary: "#6C63FF",
    bgUser: "#F5F5F5",
    bgAssistant: "#FFFFFF",
    textUser: "#333333",
    textAssistant: "#333333",
    bubbleUser: "#EEEEEE",
    bubbleAssistant: "#F9F9F9",
    fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
  },
  dark: {
    name: "Dark",
    primary: "#10A37F",
    bgUser: "#2D2D2D",
    bgAssistant: "#1E1E1E",
    textUser: "#E0E0E0",
    textAssistant: "#E0E0E0",
    bubbleUser: "#3A3A3A",
    bubbleAssistant: "#2A2A2A",
    fontFamily: "Söhne, ui-sans-serif, system-ui, sans-serif",
  },
  light: {
    name: "Light",
    primary: "#007AFF",
    bgUser: "#F2F2F7",
    bgAssistant: "#FFFFFF",
    textUser: "#1C1C1E",
    textAssistant: "#1C1C1E",
    bubbleUser: "#E5E5EA",
    bubbleAssistant: "#F2F2F7",
    fontFamily: "SF, ui-sans-serif, system-ui, sans-serif",
  },
  notion: {
    name: "Notion",
    primary: "#37352F",
    bgUser: "#FBFBFA",
    bgAssistant: "#FFFFFF",
    textUser: "#37352F",
    textAssistant: "#37352F",
    bubbleUser: "#EBE7E0",
    bubbleAssistant: "#F7F6F3",
    fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
  },
  github: {
    name: "GitHub",
    primary: "#0969DA",
    bgUser: "#F6F8FA",
    bgAssistant: "#FFFFFF",
    textUser: "#1F2328",
    textAssistant: "#1F2328",
    bubbleUser: "#E8F0FE",
    bubbleAssistant: "#F6F8FA",
    fontFamily:
      "-apple-system, BlinkMacSystemFont, Segoe UI, sans-serif",
  },
  terminal: {
    name: "Terminal",
    primary: "#00FF41",
    bgUser: "#0D0D0D",
    bgAssistant: "#0A0A0A",
    textUser: "#00FF41",
    textAssistant: "#00FF41",
    bubbleUser: "#1A1A1A",
    bubbleAssistant: "#111111",
    fontFamily: "JetBrains Mono, Fira Code, monospace",
  },
  modern: {
    name: "Modern",
    primary: "#8B5CF6",
    bgUser: "#F8FAFC",
    bgAssistant: "#FFFFFF",
    textUser: "#0F172A",
    textAssistant: "#0F172A",
    bubbleUser: "#EDE9FE",
    bubbleAssistant: "#F1F5F9",
    fontFamily: "Geist, Inter, ui-sans-serif, system-ui, sans-serif",
  },
};

export const FONT_FAMILIES = [
  { value: "Inter, ui-sans-serif, system-ui, sans-serif", label: "Inter" },
  { value: "Söhne, ui-sans-serif, system-ui, sans-serif", label: "Söhne" },
  { value: "SF, ui-sans-serif, system-ui, sans-serif", label: "SF" },
  {
    value: "-apple-system, BlinkMacSystemFont, Segoe UI, sans-serif",
    label: "System UI",
  },
  { value: "Georgia, serif", label: "Georgia" },
  { value: "JetBrains Mono, Fira Code, monospace", label: "JetBrains Mono" },
  { value: "Geist, Inter, ui-sans-serif, system-ui, sans-serif", label: "Geist" },
];

export const FONT_SIZES = [
  { value: 12, label: "12px" },
  { value: 14, label: "14px" },
  { value: 15, label: "15px" },
  { value: 16, label: "16px" },
  { value: 18, label: "18px" },
  { value: 20, label: "20px" },
];

export const SUPPORTED_FORMATS = [
  { value: "json", label: "JSON", mime: "application/json", ext: ".json" },
  { value: "markdown", label: "Markdown", mime: "text/markdown", ext: ".md" },
  { value: "txt", label: "TXT", mime: "text/plain", ext: ".txt" },
  { value: "html", label: "HTML", mime: "text/html", ext: ".html" },
  { value: "csv", label: "CSV", mime: "text/csv", ext: ".csv" },
];

export const SUPPORTED_LANGUAGES = [
  "javascript",
  "python",
  "react",
  "java",
  "cpp",
  "c++",
  "html",
  "css",
  "json",
  "markdown",
  "sql",
  "yaml",
  "typescript",
  "jsx",
  "tsx",
  "bash",
  "shell",
  "go",
  "rust",
  "ruby",
  "php",
  "csharp",
  "swift",
  "kotlin",
  "dart",
];

export const LANGUAGE_ALIASES = {
  js: "javascript",
  py: "python",
  ts: "typescript",
  cpp: "cpp",
  cs: "csharp",
  rb: "ruby",
  rs: "rust",
  sh: "bash",
  zsh: "bash",
  md: "markdown",
  vue: "html",
};
