const seo = {
  title: "Correlate EXIF, MP4 & WAV Timestamps",
  metaDescription:
    "Line up EXIF, PNG tIME, MP4/MOV and WAV dates from up to 20 local files on one timeline. Missing timezones stay unresolved, never guessed.",
  steps: [
    "Click Add media and pick up to 20 local JPG, PNG, WebP, MP4, MOV, M4V or WAV files — 64 MB per file, 128 MB per batch.",
    "Drag the Proximity window slider (5 minutes by default) and, only with external evidence, type a fallback like +05:30 into 'Optional offset for timezone-free fields'.",
    "Read the clustered timeline with its unresolved wall-clock flags, then click 'Download counts-only report' to save media-metadata-timeline-counts.json.",
  ],
  intro:
    "The Media Metadata Timeline Correlator reads the date fields embedded in local JPEG, PNG, WebP, MP4/MOV and WAV files — EXIF DateTimeOriginal, DateTimeDigitized and DateTime with their matching offset tags, PNG tIME, QuickTime/MP4 movie creation and modification times, and WAV INFO ICRD — and lines them up on one timeline alongside each file's browser lastModified property. Timestamps that carry no timezone are kept as unresolved wall-clock values rather than being silently assumed to be local or UTC, and you can apply a fallback offset yourself. It clusters events that fall within a chosen window and flags exact matches across files, without making any claim about whether a file is authentic or edited.",
  useCases: [
    "You have photos and clips of the same event from three different cameras and want to see whether their embedded capture times actually line up or whether one device's clock was off.",
    "A batch of images has EXIF times with no OffsetTime tag, and you want to test what the ordering looks like under a specific UTC offset instead of trusting whatever your viewer assumed.",
    "You are checking a folder where several files share a suspiciously identical timestamp, and want the tool to group exact matches across records so you can see which files came from one export.",
  ],
  benefits: [
    ["Missing timezones stay missing", "An EXIF time with no offset tag is reported as unresolved wall clock, so a guessed zone never silently shifts your timeline by hours."],
    ["Reads containers, not just EXIF", "It parses JPEG APP1/TIFF IFDs, PNG tIME, WebP, MP4/MOV atom headers and WAV INFO chunks, converting QuickTime's 1904 epoch to real dates."],
    ["Points at inconsistencies without judging them", "It clusters nearby events, groups identical timestamps across files, and flags embedded times more than 60 seconds after the file's lastModified — as observations, not verdicts."],
  ],
  faqs: [
    [
      "Which file types and sizes can I load?",
      "JPG, JPEG, PNG, WebP, MP4, MOV, M4V and WAV, up to 20 files per batch with a 64 MB limit per file and 128 MB for the batch overall. Correlation runs across up to 30 records and up to 80 embedded events per file.",
    ],
    [
      "What happens to timestamps that have no timezone?",
      "They are marked unresolved with the reason `timezone-missing` and shown as a wall-clock string, so they are never placed on the absolute timeline by guesswork. If you supply a fallback UTC offset, those events are resolved using it and labelled as having used the fallback, while any timestamp that carried its own offset keeps that offset.",
    ],
    [
      "How does the clustering window work?",
      "Events sorted by absolute time are grouped whenever consecutive events are no further apart than your chosen window, which defaults to 5 minutes and can be set anywhere from 1 minute to 1440 minutes (24 hours). Only groups with more than one event are reported as clusters.",
    ],
    [
      "Can this prove a photo or video was tampered with?",
      "No, and it deliberately makes no authenticity claim. Metadata dates can be edited, stripped, regenerated by any export step, or written by a device with a wrong clock, so a clean or inconsistent timeline is evidence about the metadata only. Treat the output as an investigative aid and involve a qualified forensic examiner when the answer actually matters.",
    ],
  ],
};

export default seo;
