const seo = {
  title: "Binaural Beat Generator — Free Online, No Signup",
  h1: "Binaural Beat Generator",
  metaDescription:
    "Free binaural beat generator: set a 60-500 Hz base tone and a 0.5-40 Hz beat, plus isochronic, solfeggio and guided sessions. Runs in your browser.",
  intro:
    "The Binaural Beat Generator synthesizes every tone locally with the Web Audio API. In binaural mode two sine OscillatorNodes feed a ChannelMergerNode, so the left channel carries your base frequency and the right carries base + beat — the beat you perceive is that arithmetic difference between the ears. Isochronic mode instead amplitude-modulates a single carrier with a sine LFO summed against a ConstantSourceNode offset, and a 2048-point AnalyserNode draws the live waveform above the controls. No audio file is ever downloaded or uploaded: the sound is generated on your own device as it plays.",
  useCases: [
    "Set a 200 Hz base with a 10 Hz alpha beat as background sound while you work, with the session timer set to auto-stop after 45 minutes.",
    "Run the Sleep Induction journey, which steps a binaural beat from 12 Hz to 7 Hz and then 3 Hz across ten minutes without you touching the sliders.",
    "Use isochronic mode on laptop speakers when you have no headphones, pulsing a 200 Hz carrier at 10 Hz with adjustable modulation depth.",
  ],
  benefits: [
    [
      "True stereo split, not a stereo file",
      "The left and right oscillators are routed to separate merger inputs, so the readout can show exactly what each ear receives: base Hz on the left, base + beat Hz on the right.",
    ],
    [
      "Four generators on one page",
      "Binaural (0.5-40 Hz beat over a 60-500 Hz base), isochronic (60-600 Hz carrier with a 0.5-40 Hz pulse), nine solfeggio pure tones, and four multi-stage journey programs of 8 to 12 minutes.",
    ],
    [
      "Session control that behaves",
      "A 3-second exponential fade-in, a timer up to 120 minutes that fades out before stopping, white/pink/brown background noise, and per-ear gain from -20 to +20 dB.",
    ],
    [
      "Nothing leaves your device",
      "Every tone is generated by your browser's Web Audio API. The tool makes no network requests, needs no account, and stores custom presets only in your own browser's localStorage.",
    ],
  ],
  faqs: [
    [
      "Do binaural beats need headphones?",
      "Yes, for binaural mode. The two oscillators are sent to separate stereo channels, so on speakers they mix in the air before reaching you and the beat effectively disappears. If you have no headphones, use the Isochronic tab instead — it pulses one tone on and off, which survives speaker playback.",
    ],
    [
      "What is the difference between binaural beats and isochronic tones?",
      "Binaural uses two continuous tones, one per ear, separated by the beat frequency (for example 200 Hz left and 210 Hz right gives a 10 Hz beat). Isochronic uses a single carrier from 60 to 600 Hz whose volume is switched up and down by a low-frequency oscillator at 0.5-40 Hz, with a 0-100% depth control for how deep the pulse cuts.",
    ],
    [
      "What frequency should I choose?",
      "The tool labels bands the conventional way: Delta at 4 Hz and below, Theta up to 8 Hz, Alpha up to 14 Hz, Beta up to 30 Hz, Gamma above 30 Hz. Its six presets follow those labels — Deep Sleep is 100 Hz base + 2 Hz beat, Meditation 150 + 6, Relaxed Focus 200 + 10, Flow State 250 + 20, Peak Focus 300 + 40, Lucid Dream 120 + 7. These are naming conventions for the frequencies themselves, not clinical prescriptions; the tool is not medical advice.",
    ],
    [
      "Is this binaural beat generator free, and do I need an account?",
      "It is free and requires no signup. The page contains no fetch or API calls — all synthesis happens client-side in the Web Audio API — so no audio, settings, or personal data is sent anywhere. Named presets you save are written to your browser's localStorage under the key bbg_presets and can be deleted from the same panel.",
    ],
    [
      "Can I download the binaural beats as an MP3 or WAV?",
      "No. The tones are synthesized in real time as they play, and there is no recording or export step. Instead you can set the session timer from 0 to 120 minutes in 5-minute increments, where 0 means it plays until you press Stop Audio.",
    ],
    [
      "What are the solfeggio frequencies included?",
      "Nine pure sine tones: 174, 285, 396, 417, 528, 639, 741, 852 and 963 Hz. Unlike binaural mode, each one is sent at the same frequency to both ears, so there is no beat and headphones are optional. The short labels shown beside each tone are traditional associations from sound-meditation practice, not verified physical effects.",
    ],
    [
      "Can I add white or pink noise underneath?",
      "Yes. The Settings tab offers white, pink and brown noise, each generated as a 2-second buffer at your device's sample rate and looped, with a level slider from 0 to 50%. Pink uses a multi-pole filter over white noise and brown uses an integrated random walk, so brown is the deepest and least hissy of the three.",
    ],
    [
      "What do the guided journey programs do?",
      "Each one moves the binaural beat through timed stages automatically. Sleep Induction runs 12 Hz for 2 minutes, 7 Hz for 3, then 3 Hz for 5. Focus Ramp climbs 10 → 18 → 40 Hz over 10 minutes. Meditation Journey runs 10 → 6 → 3 → 7 Hz over 12 minutes, and Creativity Boost runs 8 → 6 → 10 Hz over 8 minutes. Progress bars show the active stage, and audio stops when the last stage ends.",
    ],
  ],
  steps: [
    "Pick a brainwave preset or move the sliders yourself — base frequency 60-500 Hz and beat frequency 0.5-40 Hz in 0.5 Hz steps. The readout at the bottom shows the exact tone going to each ear.",
    "Put on stereo headphones and press Start Audio. The waveform panel draws the live analyser output while the timer counts the session, and changes to the sliders take effect without restarting.",
    "Open Settings to layer in pink or brown noise, trim left and right gain in decibels, switch on the 4-second inhale / 4-second exhale breathing guide, or save the current configuration as a named preset.",
  ],
};

export default seo;
